### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by IceRaider** [NamelessMC/Nameless#10]
I'm experiencing this issue when trying to connect the database 
1045 - Access denied for user 'forum_software'@'localhost' (using password: NO)

**Comment by samerton** [comment]
Try pressing "back" in your browser and trying again.

**Comment by CzEMC** [comment]
Where are you finding this error? Does it show on the webpage or is in you webserver log?

**Comment by samerton** [comment]
I believe this is the same issue as [this reported issue](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-56#post-967246) and is being worked on.

**Comment by samerton** [comment]
Should be fixed in the [latest commit](https://github.com/NamelessMC/Nameless/commit/d95bce0fd42c80135db3066b7a7ba43a7c40672a)
