### ISSUE TITLE
Forums do not appear, even with Parent set

### ISSUE THREAD

**Issue by TheMeq** [NamelessMC/Nameless#100]
Please see screenshot 1: 
https://gyazo.com/f82ad5b3a84f06651a24aa42fed0c968

and screenshot 2:
https://gyazo.com/fd26d25c11df4865c480d706e20a090a

and screenshot 3: 
https://gyazo.com/706d2992bc05956849e6a5601af7da25

I have 2 forums and a parent forum, and they are even set that way in the database. 

But they are not appearing at all. I don't know what the cause is, there is no error log to say there was an error or anything. The forum is like the main hub for any Minecraft website, so this needs fixing as a priority.

**Comment by samerton** [comment]
Can you check the permissions for your parent forum allow groups to view it?

**Comment by TheMeq** [comment]
https://gyazo.com/04842c6ca15e2d8d7753b85ba98684e7

It is set to Can View for everyone, but they still do not appear.

**Comment by TheMeq** [comment]
I figured it out... Please close. I had it on Latest Discussion view, not table view.
