### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1005]
Please, Samerton, can you configure my apache to run installation without problems, my computer was hacked and I cannot do it :(((((

**Comment by DSArtyFixLife** [comment]
And will this work? (I have installed SSL on domain, and i have  A record for www) ***Htaccess
<IfModule mod_rewrite.c>

RewriteEngine On
RewriteCond !{HTTPS} off
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

</IfModule>

**Comment by samerton** [comment]
A Nameless .htaccess file to force SSL is as follows:
```
  Options +FollowSymLinks
  Options -Indexes
  RewriteEngine On

  RewriteCond %{HTTPS} !=on
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  
  RewriteCond %{SCRIPT_FILENAME} !-d
  RewriteCond %{SCRIPT_FILENAME} !-f

  RewriteRule ^.*$ ./index.php
```

If you are still experiencing issues, feel free to send me a private message on [Spigot](https://www.spigotmc.org/members/samerton.10676/) and I can configure the server for you.

**Comment by DSArtyFixLife** [comment]
Thanks you. And can you setup my apache to install nlsmc without problems?

**Comment by samerton** [comment]
Yes, send me a message on Spigot as mentioned in my last reply ^

**Comment by DSArtyFixLife** [comment]
https://upload.hicoria.com/files/yDbPtcK9.png

**Comment by samerton** [comment]
Thanks, I'll close this and use the private message conversation from now on.

**Comment by DSArtyFixLife** [comment]
I sended it to "samerton (supporter) with nlmc logo as profile image)
