### ISSUE TITLE
Homepage not working!

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1008]
Hello, my homepage isnt working after editing index.tpl, I downloaded default index.tpl, but still  nothing - xml installed. Please samerton, help.

**Comment by samerton** [comment]
Why exactly isn't it working? Is there a white screen?

If you enable error reporting in the AdminCP -> Misc tab, do any errors appear on the homepage?

**Comment by DSArtyFixLife** [comment]
Nothing displayed. It is white. Yes.

**Comment by samerton** [comment]
Did you enable error reporting in the AdminCP -> Misc tab, and if so, can you paste any errors from the homepage?

**Comment by DSArtyFixLife** [comment]
Yes.

**Comment by samerton** [comment]
What does it say?

**Comment by DSArtyFixLife** [comment]
I dont see any errors.

**Comment by samerton** [comment]
I've replied to your Spigot private message, I'll mark this as closed (as it's a customisation) and use that instead.
