### ISSUE TITLE
Nameless MC Profiles always Offline

### ISSUE THREAD

**Issue by ryancito02** [NamelessMC/Nameless#101]
Regardless of if one of my fellow admins is online, when I check their profile, it states "Offline" However, going to the forums, the Online Players section includes their name and mine.
Please help. I am using your latest commit.

**Comment by ryancito02** [comment]
Sorry, not your latest. I am using the one on your Downloads page.
I believe I started this a week ago.

**Comment by samerton** [comment]
The online status on user's profiles currently only shows their server status, not their forum status.

**Comment by ryancito02** [comment]
No, it is happening even though they are on the server and the forum.

**Comment by ryancito02** [comment]
I just tried with a friends account.

**Comment by ryancito02** [comment]
Ok, I made a GIF of it.
Watch closely.

![output_31tmwa](https://cloud.githubusercontent.com/assets/17111990/13205035/77a9cd80-d8a3-11e5-94d3-9de36690b7bf.gif)

As you can see, even though he is on the server, it displays him as offline on the website.
Please help ;)

**Comment by samerton** [comment]
I can't reproduce your issue, the online status is working as expected for me. This could potentially be an issue with multiple servers, are you running the server behind a Bungee instance?

**Comment by ryancito02** [comment]
No, I am only running one server. It is running off the same computer as the minecraft host computer, and my friend and I are on the same network. However, I am connecting to the website from behind a VPN, so I don't know what's going wrong. Maybe, replacing all my IP values with localhost will do the trick? Or is it querying the server already from an outward query? 

To answer your question, No, I am running a Forge minecraft server.

**Comment by samerton** [comment]
No idea what could be causing this, I'll take a look into the issue though.

**Comment by ryancito02** [comment]
Alright, thanks! I'll leave this open until you can find a fix for it. (Hopefully sooner than never!)

                                                        Cheers!

**Comment by ryancito02** [comment]
Going to try updating to the newest version.
See if that fixes it.

**Comment by ryancito02** [comment]
Nope, still getting the same problem with V. 1.0.4

**Comment by samerton** [comment]
I'll probably drop this feature in the next release, as it causes more issues than it's worth.

**Comment by ryancito02** [comment]
Alright. Alright. Can we get a feature which displays if a user is online
(the website)?
Such a feature would be fine, all you would have to do is extend the
feature you have in the Forums section (Online Users) and implement it into
the User Pages.

Maybe?

                                                   Cheers!

**Comment by claushbang** [comment]
The online status worked perfectly fine for me. Maybe rather than completely removing the feature, you could add thing where it allows people to see if they are online or not...maybe even on their forum posts you could put a green dot next to their name to signify that they are online.

I could pull this one off if need be.

**Comment by partydragen** [comment]
The online stats worked for me but i run a network we need all servers in the network added to play
Example if your online on Factions server you need factions on play
