### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1010]
Hello, how i can make the loader (displays css loader when is page in browser loading) please help, loader i have but i cannot useit... help! ***1.0.19

**Comment by samerton** [comment]
This isn't something we can help with as it is your own customisation, but you can add any custom CSS to **styles/themes/*theme*/css/custom.css**, and any custom Javascript can be added to **core/includes/template/scripts.php**.

**Comment by DSArtyFixLife** [comment]
Please answear on spigotmc 😂😂

**Comment by samerton** [comment]
I have already responded to your message on there :)

I'll mark this issue as closed as it is a customisation.

**Comment by DSArtyFixLife** [comment]
Is possible to make a window will be displayed after clicking to element in website (pop-up window with custom messages)

**Comment by samerton** [comment]
Nameless uses Bootstrap, so you can use a [Bootstrap modal](http://getbootstrap.com/docs/3.3/javascript/#modals) as per the docs.

**Comment by DSArtyFixLife** [comment]
And what about copy to clip board (i will click to ip and it will copy)

**Comment by samerton** [comment]
[This](https://gist.githubusercontent.com/samerton/53633cbfec5a9d026964a1eb47371f59/raw/1799fc872a5b5965a11207221c3c39368bb7ad96/ip_click.html) is the code you need for copy to clipboard.

**Comment by DSArtyFixLife** [comment]
Thank you múch!

**Comment by DSArtyFixLife** [comment]
Aaand, you selled me tut with image but i want change color of background.

**Comment by DSArtyFixLife** [comment]
Site background***

**Comment by samerton** [comment]
In that case, you need to add
```
body {
    background-color: #fff;
}
```
where `#fff` is your colour, to styles/themes/*theme*/css/custom.css

**Comment by DSArtyFixLife** [comment]
Can I use 5 charset code?

**Comment by samerton** [comment]
You can use any CSS colour code, including hex or rgba.

**Comment by DSArtyFixLife** [comment]
Can you send me tutorial how to setup a zoom-&-unzoom logo on page?

**Comment by samerton** [comment]
I'm not a web designer I'm afraid, I don't know how to do that.

**Comment by DSArtyFixLife** [comment]
Where I can edit profile page? (Do not send me /pages/profile.php, because there I cannot orientate)

**Comment by samerton** [comment]
I'm afraid pages/profile.php is the only place, there is no template file for profile pages in version 1.
