### ISSUE TITLE
Setting background image to full.

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1011]
Hello, how is possible to make the default background site image to be on full? 
( Gets from header, left, right but the down will not get to full ) Sorry for bad English.

**Comment by samerton** [comment]
You need to move
```
<div class="container">
  {$SESSION_FLASH}
```
below the jumbotron in styles/templates/*template*/index.tpl, so it will become
```
  <div class="jumbotron jumbotron-homepage">
    <h1>{$SITENAME}</h1>
	<p>{$PLAYERS_ONLINE}</p>
	<p>{$CONNECT_WITH}</p>
  </div>

<div class="container">
  {$SESSION_FLASH}
```

**Comment by DSArtyFixLife** [comment]
Can you watch why it isnt changing text? - www.spacelands.eu
You can use creditails from spigotmc.

**Comment by DSArtyFixLife** [comment]
And also, what line is in panel type of followers and following? I want change it to success

**Comment by DSArtyFixLife** [comment]
Up

**Comment by samerton** [comment]
Check out the Bootstrap docs for carousels [here](http://getbootstrap.com/docs/3.3/javascript/#carousel), however unfortunately I can't help with that as it's a customisation.

**Comment by DSArtyFixLife** [comment]
Please answear to my question about the slider, and how is possible to make css labels like from there: MiniCube.cz/members ?

**Comment by DSArtyFixLife** [comment]
Ou, already you answeared, sorry

**Comment by DSArtyFixLife** [comment]
How I can add background on the slider?

**Comment by samerton** [comment]
The member labels you mention above are created using a background image for each label, which is a .gif with the effect. Information on adding custom labels is [here](https://www.spigotmc.org/threads/namelessmc.88001/page-45#post-1840257).

As for adding backgrounds to the slider, have a look at the Bootstrap documentation I linked in my last reply which tells you all you need to know, notice the <img> tags in the example code.
