### ISSUE TITLE
issue in subdirectory installation

### ISSUE THREAD

**Issue by GaneshKandu** [NamelessMC/Nameless#1012]
### Template:
**What kind of issue is it** : ```Bug```
**In which version of NamelessMC did it occur** : ```1.0.19```
**How would you describe the issue**?
   trying to install in sub-directory of web accessible directory  
**Do you have (relevant) resources about this issue**
![screenshot-scripts nuftp com-2018-04-24-17-52-27](https://user-images.githubusercontent.com/12833130/39186524-33136310-47ba-11e8-9574-bd8f5dd046cf.png)
**Do you have an idea how or where the issue occurs**

root index.php
```php
// Get the directory the user is trying to access
$directory = $_SERVER['REQUEST_URI'];
$directories = explode("/", $directory);
$lim = count($directories);
```
when i am installing Nameless in http://domain.com/subdirectory/Namelessinstallation/admin
in case ```$directories```  is
```
array(
    [0] = '',
    [1] = 'subdirectory',
    [2] = 'Namelessinstallation'
    [3] = 'admin'
)
```
works in case where Nameless is installed in root ie, http://domain.com/admin but not in case where its installed in sub-directory ie. http://domain.com/subdirectory/admin

**Comment by samerton** [comment]
Unfortunately version 1 of Nameless does not support subdirectory installations, it's only possible in the upcoming version 2 release ([link to branch](https://github.com/NamelessMC/Nameless/tree/v2)).

**Comment by GaneshKandu** [comment]
Version 1.0.19 is a last release
i want to use on production

**Comment by samerton** [comment]
Yes that is correct, unfortunately it is not possible to use version 1 in a subdirectory.

One workaround is a subdomain, for example forum.yoursite.com *will* work.
