### ISSUE TITLE
Not Recognizing MySQL Database on Installer

### ISSUE THREAD

**Issue by nathan93** [NamelessMC/Nameless#1015]
* **What kind of issue is it?** Bug
* **In which version of NamelessMC did it occur (1.x.x):** 1.0.19
* **How would you describe the issue?** I am running the installer for Nameless 1.0.19, but I cannot get past the MySQL configuration. I have created the database, and have double checked that the database name and password are correct when I input them. Yet, the error occurs no matter what, I even tried uninstalling and reinstalling Nameless and trying another database with a different user, and it still won't connect. 
* **Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** This is the only error in the error_log: 
`[29-Apr-2018 20:57:22 Europe/London] PHP Warning:  mysqli::mysqli(): (HY000/2005): Unknown MySQL server host 'database_name' (4) in /home/sioncraf/nameless.sioncraft.net/pages/install.php on line 763`
* **Do you have an idea how or where the issue occurs?** No idea how the issue occurs.

**Comment by samerton** [comment]
Were you able to resolve this issue @nathan93?

**Comment by samerton** [comment]
I'll mark this issue as closed, if you're still experiencing this issue please feel free to re-open.
