### ISSUE TITLE
Cant use Forums!

### ISSUE THREAD

**Issue by BioticMax** [NamelessMC/Nameless#102]
I got nameless for my website, but I try to make new forums and it doesn't let me! I will make them and make sure they save, but when I go to look at the forums page, the new forums don't show up!

**Comment by samerton** [comment]
First, you need to create a "parent forum". This is created in the same way as a normal forum.
Next, any forums that you want to display need to be edited, and their "parent forum" option needs to be set as the new "parent forum" you've just made. This is to accommodate for forum categories which I hope to include in version 1.1.

**Comment by BioticMax** [comment]
:D Thanks! I will try this asap!
