### ISSUE TITLE
3 more questions.

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1028]
Hello, is possible to make my own login interface? I wanna disable the /signin.php and /register.php and make my own interface (no on custom page, just a pop-up modal.) + How is possible to move the login screen buttons? (Original: REGISTER | LOGIN - Wanted: LOGIN | REGISTER) - My friend did it. + How is possible to modify custom page's config in some php file or other?

**Comment by samerton** [comment]
It is only possible to create a custom modal for signing in in version 2 (version 1 requires core code edits which I can't help with).

You can change the order of the buttons [here](https://github.com/NamelessMC/Nameless/blob/master/pages/signin.php#L210-L221), in pages/signin.php

What exactly do you need to change with custom pages? The PHP is pages/extra.php.

**Comment by DSArtyFixLife** [comment]
I need more help, please, go to spigotmc and there I will give friends vps creditails, and please setup on his vps, that namelessmc will work, like on my.
