### ISSUE TITLE
Register system isnt working

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1029]
Hello, Samerton please help me, as classic im using v1.x, but I ever didnt see this, register system isnt working, please help me.

**Comment by samerton** [comment]
Why exactly doesn't it work?

What happens when you try to register?

**Comment by DSArtyFixLife** [comment]
It gives me 500 error page

**Comment by DSArtyFixLife** [comment]
It says the page does not work

**Comment by samerton** [comment]
Can you enable error reporting in the AdminCP -> Misc tab, and then try again.

Then, check your server's Apache error logs to see if there is anything inside (this depends on the installation, but try /var/log/apache2/error.log)

**Comment by DSArtyFixLife** [comment]
I dont have it on vps, I cannot access it.

**Comment by samerton** [comment]
In that case, your web host should provide you with PHP error logs.

**Comment by DSArtyFixLife** [comment]
You can try to watch it, www.overshot.cz/register
You can fill the fields, but if you will click "REGISTROVAT" it will display that page

**Comment by samerton** [comment]
I do need you to find an error message in your web host's PHP logs in order to help fix the problem.

**Comment by DSArtyFixLife** [comment]
What does mean this: Warning: file_put_contents(cache/27676cde0f4debac2971a1249e14df0706f0dd90.cache): failed to open stream: Permission denied in /home/webs/web_13118/overshot.cz/www/core/classes/Cache.php on line 106

**Comment by DSArtyFixLife** [comment]
And this?
Warning: usort() expects parameter 1 to be array, null given in /home/webs/web_13118/overshot.cz/www/core/classes/Forum.php on line 111

Warning: Invalid argument supplied for foreach() in /home/webs/web_13118/overshot.cz/www/pages/forum/index.php on line 339
Notice: Undefined index: forums in /home/webs/web_13118/overshot.cz/www/cache/templates_c/5e7bf2964521f8a3fbdf4cd09c29d9233e461e60_0.file.forum_index_table.tpl.php on line 87

**Comment by samerton** [comment]
The first one is a permissions error, you need to make sure the `cache` folder is writable (ask your web host about doing this).

The second one is only a warning and can be safely ignored.

However, neither of these appear to be related to your register page error.

**Comment by DSArtyFixLife** [comment]
Shit!!! I found what does it say!
Warning: curl_exec() has been disabled for security reasons in /home/webs/web_13118/overshot.cz/www/core/integration/uuid.php on line 109

Warning: curl_exec() has been disabled for security reasons in /home/webs/web_13118/overshot.cz/www/core/integration/uuid.php on line 79

Fatal error: Call to a member function getProfileAsArray() on a non-object in /home/webs/web_13118/overshot.cz/www/pages/register.php on line 173

(after clicking to register)

**Comment by samerton** [comment]
Ah ok, unfortunately that means your web host is not compatible with Nameless.

Some free web hosts block functionality like PHP's cURL library (which the error mentions) to get you to upgrade to their paid plans.

**Comment by DSArtyFixLife** [comment]
But it paid...

**Comment by DSArtyFixLife** [comment]
*is

**Comment by samerton** [comment]
You can try opening a ticket with your web host and asking them to allow the use of cURL in that case.

**Comment by DSArtyFixLife** [comment]
And well, I found very good webhost, it allows you to add your own conf for site in apache, and it give you the console, but I cannot use in it service apache2 restart a2emodule rewrite, is possible to execute these commands in other ways?

**Comment by DSArtyFixLife** [comment]
And can I and my friend write new language file for namelessmc? (Czech and Slovak) Im from slovakia, and it is very bad :( and the czech more... We want to fix it...

**Comment by samerton** [comment]
Web hosts usually have the rewrite module already enabled for you, so there is no need to use the `a2enmod rewrite` command.

As for the translation, that would be great :) All translations are appreciated.

**Comment by DSArtyFixLife** [comment]
So I will download the basic language file and rewrite it, and I will also send it to my friend, he is from czech, so he know, bcs the czech translation is in half in english.

**Comment by DSArtyFixLife** [comment]
And I have a little question... If I will send you complete slovak lang file, can I got a member of namelessmc? I like yours tag.. :3

**Comment by samerton** [comment]
If you submit a pull request on Github, you'll receive a Contributor tag on here :)
