### ISSUE TITLE
Typo Error in Infractions with Advanced Ban

### ISSUE THREAD

**Issue by JavaGuy12** [NamelessMC/Nameless#1030]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.19
* How would you describe the issue? AdvancedBan database typo in code
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? yes
* Do you have an idea how or where the issue occurs? yes
* What Modules are you using ? Infractions is the applicable one
* What theme are you using ?  Cosmo w/ inverted navbar

The code in /addons/Infractions/Infractions.php on line 943 says

`$punishments = $this->_db->get('punishmenthistory', array('uuid', $symbol, $equals))->results();`

No infractions were shown. So, I looked deeper. The MySQL database capitalized the **P** in **P**unishment and the **H** in **H**istory. I modified the code.

`$punishments = $this->_db->get('PunishmentHistory', array('uuid', $symbol, $equals))->results();`

It's now in working condition.

**Comment by JavaGuy12** [comment]
I have reasons to believe this error is made a lot: View >> doesn't work.

**Comment by JavaGuy12** [comment]
Found it - line 1063: same error.

**Comment by samerton** [comment]
I think when I added AdvancedBan integration into Nameless, I was using phpMyAdmin to view the database structure, which in some configurations displays all table names as lowercase so the capital letters were something I missed.

I did update the table names back to upper case in e5433cd8b871173cbc63e8c6790f82bd8dafcdc6 however, which will be included in the next release (hopefully coming very soon).

**Comment by JavaGuy12** [comment]
Thanks so much! You are the most active dev I've ever met. No regrets upgrading from phpBB, 1999 forums software to 2018. Its something modern, powerful, free, and I am very thankful for it. @samerton, and I mean this when I say this, keep up the great work, and DITCH XENFORO!

**Comment by JavaGuy12** [comment]
But, what just came to my mind: how do you accept/deny staff applications?

**Comment by samerton** [comment]
No problem, glad you like Nameless!

Staff applications can be accepted/denied by viewing the staff app in the ModCP; there should be buttons there as long as your group as the necessary permissions in the AdminCP -> Core -> Modules -> Staff Applications settings tab

**Comment by JavaGuy12** [comment]
Thanks again!

**Comment by samerton** [comment]
No problem, I'll mark this as closed. If you have any more questions, feel free to re-open this issue or open a new one.
