### ISSUE TITLE
Portal

### ISSUE THREAD

**Issue by Qr9YT** [NamelessMC/Nameless#1035]
How do you setup the portal in namelessmc 2.0 pr4?

**Comment by samerton** [comment]
In Nameless version 2, you can only add HTML portals (if your portal includes something like a PHP configuration file, a module would have to be made specifically for that portal).

To add an HTML portal, upload the files as normal, **except** for the portal HTML file. 

You then need to paste everything within the `<body>` and `</body>` tags in your portal HTML file to **custom/templates/*template*/portal.tpl**, and also any `<link rel="stylesheet"....>` and `<script>` tags from within the portal HTML file.

You can then switch the homepage to a portal in the AdminCP -> Core -> General Settings tab.

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues please feel free to re-open.
