### ISSUE TITLE
Play system

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1047]
Hello, Samerton.
Can you sell me the clear source of the play page, without navbar, footer and php require in namelessmc.
Smartly. I want to get clear text of play source, where I can manualy add server with port, and it isnt connected with namelessmc, I want to make my full custom page in namelessmc, that is not connected with it. Just Im trying. PLEASE

**Comment by samerton** [comment]
Are you using version 1 or the version 2 pre-release?

**Comment by DSArtyFixLife** [comment]
I have an idea, is possible to add something like if you are doing registration process, it will from name using jquery (it will always update enetered value) and in module it will jquery using placeholder display entered value such as: <img src="https://visage.surgeplay.com/full/' . value . '/300.png" alt="Skin">

**Comment by DSArtyFixLife** [comment]
Emm... Opps?

**Comment by DSArtyFixLife** [comment]
I ment (i cannot start and end code using < >) so img src="https://idk.com/skins/' .valueentered. '.png"

**Comment by DSArtyFixLife** [comment]
Meant

**Comment by samerton** [comment]
This is possible in Nameless version 2, you can modify the template to do this :)

I'll mark this as closed since the original question has been answered, if you are still experiencing issues feel free to re-open.
