### ISSUE TITLE
add ability to translate days of the week 

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1049]
* What kind of issue is it (Question, Bug, etc.)?: Suggestion
* In which version of NamelessMC did it occur (1.x.x)? : pr-4
* How would you describe the issue? : I will add images.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? :
1. http://www.iup.baxandrei.ro/view/photo/poxvr6gpenjp4plg/Screenshot_13.png
2. http://www.iup.baxandrei.ro/view/photo/imtrcgvnvi5hffaj/Screenshot_15.png
* Do you have an idea how or where the issue occurs? : --
* What Modules are you using ? : --
* What theme are you using ? : --

**Comment by baxandrei** [comment]
Edit, i found one more page: http://www.iup.baxandrei.ro/view/photo/mraydqgvvpdmm2ab/Screenshot_14.png

**Comment by samerton** [comment]
Except for the days of the week in the graph, all other terms can be translated in the file **modules/Forum/*language*/forum.php** :)

**Comment by baxandrei** [comment]
and when we can translate days of the week?

**Comment by samerton** [comment]
Days of the week within the graph are automatically translated since [this commit](551c0e3b9efad127ba576dea5d3df5e0caac3a4f).
