### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by FinnehPleh** [NamelessMC/Nameless#105]
Trying to get the website install, but when I uploaded it to my public_html folder it gave me a 500 error.
I checked the error logs and it shows
"Notice: Undefined variable: queries in /home/neonforu/public_html/index.php on line 14
Fatal error: Call to a member function getWhere() on null in /home/neonforu/public_html/index.php on line 14"

I've just uploaded it as I would a MyBB forum or similar.
Edit: It seems that the site is showing that when you load it.
The site in question is http://novaforums.net

**Comment by samerton** [comment]
It looks like the files from within the "pages" directory have been moved out of there into "public_html". Can you remove the files from your web server and reupload, keeping the file structure present in the download?

**Comment by FinnehPleh** [comment]
Interesting, I uploaded it exactly as I downloaded it.
Now after uploading it again it seems to be giving me a 404 error when it gets to install.php but I'm no longer getting a 500 error.

**Comment by samerton** [comment]
Looks like you need to enable Apache's mod_rewrite and also allow the use of .htaccess files. [This post](http://askubuntu.com/a/48363) contains all the steps you need (Ubuntu).

**Comment by FinnehPleh** [comment]
Both are already been enabled.

**Comment by samerton** [comment]
Is there a .htaccess file present in the root directory containing [these rules](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess)?

**Comment by samerton** [comment]
I'm going to close this as I believe this is a server configuration issue.

**Comment by joshwenke** [comment]
To those of you reading this, sorry for bringing this issue back up, but the if 500 error is only present when using this .htaccess file:
https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess

then your issue is that your files aren't at your server's root directory. 

I fixed it by changing the last line to 
  RewriteRule ^.*$ http://full-website-address.com/index.php
