### ISSUE TITLE
html editor, emoji not working

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1050]
when i press emoji button page i get darkly and i see this error.

http://www.iup.baxandrei.ro/view/photo/9epvrrg6zrpxw8zz/Screenshot_132.png

**Comment by baxandrei** [comment]
EDIT: only on new topic i see this bug.

**Comment by samerton** [comment]
This issue was fixed in 4abdbc491efa4f826d0f0be4c1393fbf9334b8bf :)

**Comment by baxandrei** [comment]
Thanx.
