### ISSUE TITLE
widget  for members and staff online not work for me.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1051]
http://www.iup.baxandrei.ro/view/photo/xjeqcj23iecqqs2v/Screenshot_14.png

I refreshed page multiple times.

**Comment by samerton** [comment]
These lists are cached for 2 minutes, so try refreshing the page after 2 minutes.

To get a group to show up in the "Online Staff" widget, you must make sure the staff group option is checked when editing groups in the AdminCP -> Users and Groups -> Groups tab.

You can also configure the "Online Users" widget to select whether staff groups show up in there or not by editing the widget in the AdminCP -> Widgets tab.

**Comment by baxandrei** [comment]
Ok, I will try, thanx you!

**Comment by baxandrei** [comment]
It work, thanx

**Comment by samerton** [comment]
Glad it's working :)
