### ISSUE TITLE
Web push notifications not working.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1053]
I am usign pr4. And web push notifications seems to not work and users don`t revice them.

**Comment by samerton** [comment]
I can't reproduce any issues, the notifications work as intended.

Notifications are sent up to 20 seconds after the alert/message is received, note the website must be open in your browser (but can be hidden in another tab) for them to send.

**Comment by baxandrei** [comment]
I will try , thanx. i will reply if work

**Comment by baxandrei** [comment]
has moments when it goes and moments when it does not work, thank you, you can close now.
