### ISSUE TITLE
Force ssl bug.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1054]
After I set "Force SSL" on, everything works but after I restart the page, the option apears off but it still works and if I press save again it will be disable.

**Comment by baxandrei** [comment]
Now it work, thanks! You will update the code to fix this to newer versions?

**Comment by samerton** [comment]
Glad it's fixed! Yep, the updated code was from this commit: 5754a750870cca5ee6b26988dd9d57ec5874639f, which will be included in the next update.
