### ISSUE TITLE
Minecraft avatars bug. and an question.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1055]
Q: How do I can update user UUID?

Bug: Minecraft avatar source doesn`t work if I select the option: Built-in avatar service
Gives me an 404 error.

**Comment by samerton** [comment]
You can update user UUIDs by editing the user in the AdminCP -> Users and Groups -> Users tab. You can either enter the UUID yourself (make sure you remove all `-` characters first), or you can use the "Update UUID" option in the "Actions" dropdown to do this automatically based on the username.

As for the avatar issue, I've just fixed that now in 9ae853925e97a07f57613876471bbd5e143314d0.

**Comment by baxandrei** [comment]
Where is this option, i can`t find it.. in the past there was the option, but now i can`t find.
http://www.iup.baxandrei.ro/view/photo/4bxqoivk3ivumoq0/Screenshot_14.png
http://www.iup.baxandrei.ro/view/photo/rgzskme9q5ftdjmj/Screenshot_15.png

**Comment by samerton** [comment]
You need to have the "Force premium Minecraft accounts?" in the AdminCP -> Minecraft -> "Minecraft Account Verification" tab in order for the Update UUID option to appear.

**Comment by baxandrei** [comment]
How I can enable it for offline accounts too?

**Comment by samerton** [comment]
It is not possible, as Minecraft avatars require a UUID of a premium Minecraft account to work.

You can remove [this line](https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/pages/admin/users.php#L771) and [this line](https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/pages/admin/users.php#L778) to remove the check to enter a UUID manually though (modules/Core/pages/admin/users.php).

**Comment by baxandrei** [comment]
Thanx, you can close :D
