### ISSUE TITLE
Suggestion for navigation on mobile devices.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1057]
It would look a lot better if on mobile devices these links also have a title (see picture).

http://www.iup.baxandrei.ro/view/photo/8hql2a72zukxgeii/Screenshot_20180618-131809_Samsung Internet.jpg

Nameless version: pr4

**Comment by samerton** [comment]
Added in 6b7a705883ba9c2dfbdf71752f4f3a438b425560, with the UserCP text added in the English UK and US translations (messaging + alerts is independent from language).

To add the UserCP to any other translation, you can add `<span class="mobile_only">Text</span>` to the `user_cp_icon` entry in your language's user.php file, where `Text` is the text you want to show on mobiles.
