### ISSUE TITLE
Navigation icon not working.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1058]
I add and save an icon , but is not working.
see video:
https://youtu.be/_Xwy_ja8Sto

**Comment by baxandrei** [comment]
http://www.iup.baxandrei.ro/view/photo/jetstv1qeuvg10r2/Screenshot_1.png
all is ok on my end.

**Comment by baxandrei** [comment]
Now seems to work after I have overwrite all files from my installation with zip from today`s source-code.

**Comment by IsS127** [comment]
Closing as issue seems solved.
