### ISSUE TITLE
Donate Tab / Shop

### ISSUE THREAD

**Issue by PeterEstephan** [NamelessMC/Nameless#106]
Could It be Possible to Change the "Donate" tab to the "Shop" name so it makes more sense to players sense they are more used to Shop instead of Donate. And would it be possible to make the Shop More neat because from my website, it does not look very neat once it is integrated. 

http://imgur.com/pIJ4JtP
or
https://theshadowsmc.net/donate

Thanks for the Great Website Software.

**Comment by samerton** [comment]
To change the "Donate" word to "Shop", you can change line 12 of **addons/Donate/language.php** to read `'donate' => 'Shop',`

As for the appearance, I can look into changing that in the future. For now it may be disabling the integrated webstore (AdminCP -> Addons -> Settings) so it displays your Buycraft store directly on the page.

**Comment by PeterEstephan** [comment]
Okay, thanks.

**Comment by Azoraqua** [comment]
@samerton @PeterEstephan This is now solved I believe, if so please close this issue.
