### ISSUE TITLE
 icons at every forum or sub-forum

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1068]
I would like to make a suggestion,it would be usefull and it would look much nicer if we could put some personalized icons at every forum or sub-forum,this is just for cosmetic reasons.

https://i28.servimg.com/u/f28/17/31/96/85/screen17.png

**Comment by samerton** [comment]
Added in 67eeae2a80f1a4b079fc9047251c14747ce99793

**Comment by baxandrei** [comment]
Will it work on every subforum of every forum?
http://prntscr.com/jynmnh

**Comment by baxandrei** [comment]
Looks strange on the phone, should not the icon be in line with the title?

http://prntscr.com/jynus6

**Comment by samerton** [comment]
Yep, icons will work for subforums: https://i.imgur.com/jRSTTbH.png

I did have a look at aligning the icon on mobile, unfortunately there seemed to be a Bootstrap issue that overlapped the icon with the forum name + description so I was unable to do this.
