### ISSUE TITLE
Explain what should be entered in the email.php config 

### ISSUE THREAD

**Issue by IMmmKI** [NamelessMC/Nameless#107]
Hey,
I was wondering if someone could explain what should be entered here for something like gmail.com
`<?php 
$GLOBALS['email'] = array(
	'username' => '',
	'password' => '',
	'name' => '',
	'host' => '',
	'port' => 587,
	'secure' => 'tls'
);`

Here is what I would think the config should be. Would this be correct? 

`<?php 
$GLOBALS['email'] = array(
	'username' => 'email@gmail.com',
	'password' => '123456',
	'name' => 'email@gmail.com',
	'host' => 'smtp.gmail.com',
	'port' => 587,
	'secure' => 'tls'
);`

**Comment by samerton** [comment]
Apologies that this isn't well documented so far, there are instructions on what needs filling in within [this Spigot post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-67#post-1018458). I'll get round to adding an FAQ section to the [wiki](https://github.com/NamelessMC/Nameless/wiki) at some point.

**Comment by IMmmKI** [comment]
Hey man, 

Do you mind if I can help with the creation of the wiki? I would like to help out more in the community.

**Comment by samerton** [comment]
That'd be really helpful, thanks for the offer! I believe the permissions are set so anyone can edit the wiki, feel free to add or change anything you see.
