### ISSUE TITLE
suggestion for v2 theme system.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1072]
I suggest that when using a specific theme, and that theme has missing files, the site automatically takes over the missing files from the default theme.

This would also be useful when we want to change a theme a bit, but also receive future updates, so we can only put the files in the theme that we want to modify, and the rest is taken from the default theme.

**Comment by samerton** [comment]
Unfortunately I don't think this can be implemented.

The template is initialised before Nameless knows what the page is (ie, the template specifies page CSS and JS), and the template file for the page is then loaded right at the end.

As Nameless will only be able to detect whether the template file exists or not towards the end, it will be too late to switch to the default template as the other template has already been initialised.

A solution for now is for modules to automatically copy their required template file into other templates as it's installed.
