### ISSUE TITLE
minor bug in pagination

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1073]
'next' and 'back' of the language file is not used in pagination.

My lang file general:
```
....
'back' => 'Înapoi',
....
'next' => 'Înainte',
....
```

Pagination display: 
`Previous 1 Next`

**Comment by samerton** [comment]
Back and Next are used elsewhere, I've added a new language variable "Previous" which suits pagination more in [this commit](34e400134885dbbaf66ae0d8b9a63220d2dcb960), which is now displayed in table pagination.
