### ISSUE TITLE
Suggestion for navigation on mobile devices.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1074]
I propose to move the menu button in parallel with the site name, it would look a lot better: https://i28.servimg.com/u/f28/17/31/96/85/tempfi11.jpg

Also, as it currently looks, it overlaps on some pages due to its height: https://i28.servimg.com/u/f28/17/31/96/85/screen14.png

And it would be helpful to remove the button duplicate to the UCP to save space: https://i28.servimg.com/u/f28/17/31/96/85/screen15.png

**Comment by samerton** [comment]
Moved toggler in 22e1dc782c37c87a1c7a5c0cea92e75effcf2f86

Unfortunately I can't remove the duplicated UCP button on mobile due to how Nameless generates the navbar.

**Comment by baxandrei** [comment]
Ty!
