### ISSUE TITLE
suggestion for forum module v2

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1077]
In the permission tab, when you click on red or green, I would suggest that the checkbox would check itself instead of me clicking the checkbox.

**Comment by samerton** [comment]
Added in 84f6a7e1f64c32f34efc8cf6e6fe03a7f51f1bb0

**Comment by baxandrei** [comment]
You can add it also for `/admin/pages/?action=new`

**Comment by samerton** [comment]
Added in 625752b98c50487023683bcb9502d75a5bcab36b

**Comment by baxandrei** [comment]
Thanx
