### ISSUE TITLE
add posibility to translate those words.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1078]
https://i28.servimg.com/u/f28/17/31/96/85/screen16.png
`YES` and `NO`

**Comment by samerton** [comment]
This is already possible in general.php: https://github.com/NamelessMC/Nameless/blob/v2/custom/languages/EnglishUK/general.php#L56-L57 :)

**Comment by baxandrei** [comment]
ok, you are right, sorry!
