### ISSUE TITLE
Installation Error 404

### ISSUE THREAD

**Issue by AshiroKun** [NamelessMC/Nameless#1090]
#### Installation Error:
**What kind of issue is it (Question, Bug, etc.)?**
Everytime i try to start the Installation of NamelessMC. It says "/Installs page cannot be found" 404 Error requesting /installs.  
**In which version of NamelessMC did it occur (1.x.x)?** 
Release 1.0.19.  
**How would you describe the issue?** 
When I start Installation for the NamelessMC, it instantly goes onto a page that says 404 error. However, i recently checked various issues that has been resolved. I tried them and made sure that my files was in the main directory as well as made sure that the hosting had ".htaccess" allowed. Even after checking all of this. It still doesn't work.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** 
Yes, I have the a screenshot of the error as well as proof that the website host has it enabled.
[Click here](https://gyazo.com/b106d0cf2382ae0cc90fcb256f7db073)  
Please bear in mind, i have changed my error pages. That's why it isn't showing the default 404 not found issue.
[Click here](https://gyazo.com/631eb8846ed6ff017d135039b4ced47f)
**Do you have an idea how or where the issue occurs?** 
I am relatively new to web hosting so I don't really know.

**Comment by samerton** [comment]
Would you be able to send me a link to your website?

**Comment by AshiroKun** [comment]
Okay, I believe I fixed the issue.

For some reason, if you try to extract NamelessMC Zip into the directory. It will not extract the .htaccess files. So you will need to manually upload these files into the cpanel. 

Even after i managed to do that, i still can't see the file in cpanel however, the installation works.

**Comment by samerton** [comment]
Ah great, glad you've solved the issue!

.htaccess files are usually hidden on Linux based systems and web hosts, including (as you say) the cPanel file manager. If you click the settings icon in the top right hand corner of file manager, there should be an option to enable hidden files for future reference :)
