### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xGlenor** [NamelessMC/Nameless#1094]
Help mee
 Error

> Your cache and cache/templates_c directories must be writable. Please check your file permissions. 
> Your core/config.php file must be writable. Please check your file permissions. 
> 

When trying to install

**Comment by xGlenor** [comment]
chown: invalid user: 'apache:apache'

**Comment by baxandrei** [comment]
If you use a VPS, whats OS is ?

**Comment by samerton** [comment]
Were you able to solve the issue with the command in the previous reply @xGlenor?

**Comment by samerton** [comment]
I'll mark this as closed as it's to do with the server configuration, and the chown command above will resolve it.
