### ISSUE TITLE
Editor not working.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1097]
https://i28.servimg.com/u/f28/17/31/96/85/screen24.png

**Comment by samerton** [comment]
Have you tried pressing Ctrl+F5? 
This isn't a Nameless issue, it'll be down to browser cache, or maybe something like Cloudflare's cache if you use that.

**Comment by baxandrei** [comment]
This file is missing: https://www.hartexcraft.tk/core/assets/plugins/ckeditor/core/loader.js

**Comment by samerton** [comment]
That's strange, it should be fixed in 22b9a5d0729dfe7d391c51985f46b8f2a2584899
