### ISSUE TITLE
After update bug.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1098]
After I upgraded from pr3 to pr4 my /core/email.php was updated with an empty one.

**Comment by samerton** [comment]
Make sure you only download the update from the AdminCP -> Update tab.

I've just checked and **core/email.php** is not included in the update, so this won't have been caused by the update (as long as you updated through the AdminCP -> Update tab).

**Comment by baxandrei** [comment]
I downloaded last source form github.,

**Comment by samerton** [comment]
That will be the problem, you should only update through the AdminCP -> Update tab, as the Github download includes all files which will overwrite files such as email.php

**Comment by baxandrei** [comment]
OK, thanx.
