### ISSUE TITLE
Missing /install?

### ISSUE THREAD

**Issue by SoTotallyXray** [NamelessMC/Nameless#11]
Hey,

I've tired installing this on My CreeperHost server and I cannot continue with the installation what so ever. (KingPotato.playat.ch) If you have ago your self you may know the issue. It has full read and write perms and .htaccess is allowed.

http://imgur.com/mPBQjDA

**Comment by samerton** [comment]
It looks as though mod_rewrite isn't functioning correctly; looking at the [requirements page](http://kingpotato.playat.ch/?step=requirements) by navigating to it manually, it seems that your web host is not compatible with the software.

**Comment by SoTotallyXray** [comment]
Reopened, with the correct modules installed, it still does the same thing.

**Comment by samerton** [comment]
Ensure Apache's mod_rewrite is enabled, this differs depending on your operating system. For Ubuntu, the following commands will do it:

sudo a2enmod rewrite
sudo service apache2 restart

**Comment by samerton** [comment]
I'm going to close this issue now as I believe it's a host issue as opposed to a software issue.
