### ISSUE TITLE
Upgrade from XenForo

### ISSUE THREAD

**Issue by itismejoey** [NamelessMC/Nameless#110]
Would like to upgrade to Nameless from Xenforo, but when I click the button it says install.php was not found. Is this still being worked on? Because install.php was not in the download.

EDIT: Can't even start from scratch as the install file was not in 1.0.3 or 1.0.4 downloads.

**Comment by samerton** [comment]
The issue with the install file sounds like it may be caused due to either Apache's mod_rewrite function being disabled, or the use of .htaccess files may not be enabled.

If you're running Ubuntu, [these steps](http://askubuntu.com/a/48363) should resolve the problem with the installer not being found. It's worth noting that the installer's current location (within the pages directory) is the correct location.

As for upgrading from Xenforo, there is no converter from Xenforo to Nameless version 1.0.x, however there is a converter to 0.4.1 (you can find the download [here](https://github.com/samerton/NamelessMC/releases/tag/v0.4.1)). The converter is largely untested however, I'd recommend you back up your Xenforo files and the database before attempting to convert.
You'll need to follow the steps linked above to enable the use of Apache's mod_rewrite and .htaccess files if you're using this method too.

**Comment by itismejoey** [comment]
Okay. I will check that stuff out.

As far as 0.4.1. Would I install using that then upgrade to 1.0.4 once installed? How does the upgrade process go?

**Comment by samerton** [comment]
You can upgrade from 0.4.1 to 1.0.0 following the instructions in the AdminCP's "Upgrade" tab.
Once you've upgraded to 1.0.0, you can upgrade to 1.0.1 via the AdminCP's "Update" tab, which is much easier as it provides a simple package to upload. You can then upgrade to 1.0.2, and then to 1.0.3 etc.

**Comment by itismejoey** [comment]
Looks like adding the mod_rewrite worked! 

Another question, since i'm already here, why can't you create a site in a non-home directory? I want to build/test the NMC site along side of my live site (ie: livesite.com/new). Is this possible?

**Comment by samerton** [comment]
At the moment, it's designed to work in the root directory as it's a standalone package.
It's possible to run Nameless with a subdomain, so something like new.livesite.com.

**Comment by itismejoey** [comment]
Oh derp, didnt think of that! Get an Internal Server Error when i click on either of the install buttons

**Comment by samerton** [comment]
Interesting, can you check your server's Apache logs to see if there are any errors?

**Comment by itismejoey** [comment]
No errors.

**Comment by itismejoey** [comment]
Guess that is a no go...

```
Notice: Undefined index: id in /home/mcfriends/public_html/new/converters/xenforo.php on line 64

Notice: Undefined index: id in /home/mcfriends/public_html/new/converters/xenforo.php on line 67

Notice: Undefined offset: 0 in /home/mcfriends/public_html/new/converters/xenforo.php on line 223

Notice: Trying to get property of non-object in /home/mcfriends/public_html/new/converters/xenforo.php on line 223

Notice: Undefined offset: 0 in /home/mcfriends/public_html/new/converters/xenforo.php on line 234

Notice: Trying to get property of non-object in /home/mcfriends/public_html/new/converters/xenforo.php on line 234

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_creator' cannot be null' in /home/mcfriends/public_html/new/inc/classes/DB.php:68 Stack trace: #0 /home/mcfriends/public_html/new/inc/classes/DB.php(68): PDOStatement->execute() #1 /home/mcfriends/public_html/new/inc/classes/DB.php(167): DB->createQuery('INSERT INTO nmc...', Array) #2 /home/mcfriends/public_html/new/inc/classes/Queries.php(42): DB->insert('topics', Array) #3 /home/mcfriends/public_html/new/converters/xenforo.php(254): Queries->create('topics', Array) #4 /home/mcfriends/public_html/new/pages/install.php(1375): require('/home/mcfriends...') #5 /home/mcfriends/public_html/new/index.php(163): require('/home/mcfriends...') #6 {main} thrown in /home/mcfriends/public_html/new/inc/classes/DB.php on line 68
```

**Comment by samerton** [comment]
Which version of Xenforo are you using? I'll try and investigate.

**Comment by itismejoey** [comment]
XenForo 1.4.8

**Comment by Tuxedhat** [comment]
> Looks like adding the mod_rewrite worked!
mod_rewrite isn't necessary to run xenforo unless you're using friendly URLS, bit of a necro but oh well

**Comment by WASasquatch** [comment]
Most spiders still omit queries for security reasons, Tuxedhat. They can index a static url but dont follow.

**Comment by samerton** [comment]
A new XenForo converter has been added in 2d13e6518d882102b4ccb8156a20aee72c23b612
It's been tested with 1.4.5 and **seems** to work correctly, however think of it as being in a beta stage.
