### ISSUE TITLE
problem on homepage

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1101]
"time_ago" from the last articles from homepage is not updated.

https://i28.servimg.com/u/f28/17/31/96/85/screen26.png
https://i28.servimg.com/u/f28/17/31/96/85/screen25.png

**Comment by samerton** [comment]
Would you be able to send me a link to your website?

Also, is your website have [this commit's changes](https://github.com/NamelessMC/Nameless/commit/d99d4bc73528d16c8d63262535d78e93632df927#diff-216527c4abdcebf236ec7289e9043bf8) applied?

**Comment by baxandrei** [comment]
Yes.
https://www.hartexcraft.tk/

**Comment by samerton** [comment]
Thanks, can you try the following:

- Edit **modules/Forum/front_page.php** in a text editor
- Find the line `$timeago = new Timeago();`
- Replace it with `$timeago = new Timeago(TIMEZONE);`

**Comment by baxandrei** [comment]
Now works, thanx.

**Comment by samerton** [comment]
Great, no problem.

Fixed in 470588d17af70ecde1def871b48469b43432add3
