### ISSUE TITLE
the page load time is displayed wrong on ucp

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1108]
http://www.iup.baxandrei.ro/view/photo/chqcmonadmmeiww0/Screenshot_2.png

**Comment by samerton** [comment]
I can't reproduce any issues (even after testing different timezones), does your template have the changes from https://github.com/NamelessMC/Nameless/commit/2d928e6861ce5d0ae49b6bdcef19583763d4c58c#diff-bebd18366cfbedbd84fc4abaa4138199 applied?

**Comment by samerton** [comment]
182086d5819640c7f93c0d2b32442a28bc87042b
