### ISSUE TITLE
Increase character limit on new pages

### ISSUE THREAD

**Issue by KillerAntMC** [NamelessMC/Nameless#111]
Hello, i've recently installed Nameless on my dedicated server and I was wondering how I would go about changing the character limit when creating new pages. Here's a photo on what i'm talking about:

[Example](http://prntscr.com/a9kp7p)

**Comment by samerton** [comment]
For now you'll need to manually edit **pages/admin/pages.php**. The lines you'll need to change are lines 50 and 100 (the values are currently set at 20480).

**Comment by KillerAntMC** [comment]
Thank you!

**Comment by MerlinTheGreat** [comment]
How do i do this with new nameless update?

**Comment by MerlinTheGreat** [comment]
Essentially I have a really long document i want to add to a page, Its a guide for our entire network. it goes over the traditional character limit. I was wondering if you had a way to adjust the character limit say to 100k or such
