### ISSUE TITLE
reply button bug.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1118]
If the subject is closed and the user is a moderator, the answer button appears, but if the user is not a moderator and the subject is closed, the button does not appear at all.

```
	    {if isset($CAN_REPLY)}
            <div class="btn-group">
			<a{if isset($LOCKED) && !isset($CAN_MODERATE)} disabled="disabled"{else} href="#reply_section"{/if}
                    style="vertical-align:baseline;"
                    class="btn btn-{if isset($LOCKED) && !isset($CAN_MODERATE)}warning disabled{else}primary{/if}">{if isset($LOCKED) && !isset($CAN_MODERATE)}
                    <i class="fa fa-lock" aria-hidden="true"></i>
                {/if}{$NEW_REPLY}</a>
	  </div>
        {/if}
```

**Comment by baxandrei** [comment]
```
if($user->isLoggedIn()){
	// Topic locked?
	if($topic->locked == 0 || $forum->canModerateForum($group_id, $topic->forum_id, $secondary_groups)){
		$can_reply = $forum->canPostReply($topic->forum_id, $group_id, $secondary_groups);
	} else {
		$can_reply = true; // changed here with true.
	}
} else {
	$can_reply = false;
}
```

after modify this code, buton seems to work.

**Comment by samerton** [comment]
This is intended behaviour, moderators can reply to all topics, even if it is locked.

**Comment by baxandrei** [comment]
You do not understand. If you are a member, there is no button, not even the closed topic button, but if you are the moderator, the reply button appears.

mod/admin topic closed: http://prntscr.com/k1oxhr
user topic closed: http://prntscr.com/k1oxw4

Was not he supposed to look like this? on user topic closed: http://prntscr.com/k1oyfn

**Comment by samerton** [comment]
There is not supposed to be a button if the topic is locked in the default template; this is something custom templates can add.

**Comment by baxandrei** [comment]
Ok, and how I can add this to my template?

**Comment by samerton** [comment]
Yep, you need to do the following:

First, check if {$LOCKED} is set, and {$TOPIC_LOCKED_NOTICE} is **not** set (which means the topic is locked *and* the user is not a moderator). Then, you can display your button, and the "Topic Locked" text is {$NEW_REPLY}.

```
{if isset($LOCKED) && !isset($TOPIC_LOCKED_NOTICE)}
  <!-- Topic is locked, this means we can display the locked button -->
  <a class="your locked button class">{$NEW_REPLY}</a>
{/if}
```

**Comment by baxandrei** [comment]
Thanx.
