### ISSUE TITLE
Custom page redirect

### ISSUE THREAD

**Issue by tenten8401** [NamelessMC/Nameless#112]
Would be nice if you could use a custom page to redirect... Preferably without having to break out of an iFrame

**Comment by Fiiily** [comment]
This would be relatively easy to accomplish using meta refresh tags, you can use the custom page source option to put those into a custom page and have content set to 0 for a near-instant redirect. This could be a temporary option until Nameless hits v1.1.0. You can also anyways add a new navigation option manually by making a fork of this and changing the PHP.

`<META http-equiv="refresh" content="0;URL=http://nigge.rs/id/50tank">`

**Comment by tenten8401** [comment]
Problem is, NamlessMC strips all tags that aren't "safe" according to what i see.
