### ISSUE TITLE
Discord Widget problem.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1120]
Sometimes the widget is not working and says that the ID is not correct or settings on the discord server are not turned on.The widget is turned on in discord settings and ID is 100% correct. 

http://prntscr.com/k1t529

**Comment by samerton** [comment]
If this only happens sometimes, it's an issue with your web server querying Discord's API with cURL.

**Comment by baxandrei** [comment]
ok, thnax you can close :D
