### ISSUE TITLE
editor error when upload an new image.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1125]
https://i28.servimg.com/u/f28/17/31/96/85/screen16.jpg

**Comment by samerton** [comment]
This should have been fixed 10 days ago in 158a9fd583d4c076fc23cf8d2dc46ce8ddb0dcf2, can you make sure your **uploads/upload_image.php** is up to date (https://raw.githubusercontent.com/NamelessMC/Nameless/v2/uploads/upload_image.php)?

**Comment by baxandrei** [comment]
Yes, now it works, thank you very much, it seems like I did not update that file too.
