### ISSUE TITLE
Home page suggestion.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1126]
It would be nice if on the front page you could make so that half of each article to be shown to all users.Some article are long and this could help organize things better on the front page also it would be even nicer to be able to put something like "[...]" to show that is indeed a 'sample' of the whole article just displayed and to be able to click on it and redirect you to a page

**Comment by samerton** [comment]
This is planned for a future update, unfortunately it's not as easy as it sounds as any open HTML tags within the post need to be closed.

**Comment by samerton** [comment]
62846000f12f2f76021ea85157d1e4a10e452992
