### ISSUE TITLE
Suggestion for /forum/move/ page.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1129]
I want to suggest that you can make the dropdown menu in /forum/move/  to display in the order that /forum/forum order is displayed,not in order by id from the database.
It would be much easier for moderators to work with this change
Right now, I added sub-forums to the forum above and the sub-forums appear in the bottom of the selection list.

**Comment by samerton** [comment]
9f914f823e803f2bd555c1dbb9b4df58e8ddbbd7

**Comment by samerton** [comment]
Oops, and also a65b6a59c7fbc546141b8726b4c0b8680c1a3d1f
