### ISSUE TITLE
How do I change the picture? 

### ISSUE THREAD

**Issue by BioticMax** [NamelessMC/Nameless#113]
Ok so this is my second question ;D but anyways I have a few pictures that I would like to use for my website instead of the one provided, is that possible? if so what are the required dimensions of the photo?

**Comment by samerton** [comment]
To change the homepage image, you'll need to change **core/assets/img/background-1920x828.jpg** with your own image (dimensions are 1920x828).
To change the image on profile pages, you'll need to change **core/assets/img/profile.jpg** (dimensions are 1920x1080).

**Comment by BioticMax** [comment]
ok thanks again ;D

**Comment by BioticMax** [comment]
where can I get the plugin also? cause I need to install it

**Comment by samerton** [comment]
The plugin isn't available yet, unfortunately there's no date for its completion either.

**Comment by BioticMax** [comment]
oh :P

**Comment by DataPools** [comment]
I've updated both background images and viewed them countless time in my cpanel, yet on the website, they don't update. Is there a caching thing involved?

**Comment by samerton** [comment]
Images aren't cached by Nameless, however services such as Cloudflare do cache them. If you're using Cloudflare, you can purge the cache in your Cloudflare control panel's "Caching" page.

If you're not using Cloudflare, it might just be your browser caching them, try Ctrl-F5 whilst viewing the page to force a refresh to see if it helps.

**Comment by DataPools** [comment]
Ah, I am using cloudflare and it updated after a few hours.

**Comment by DSArtyFixLife** [comment]
Where is configuration of these images please?

**Comment by samerton** [comment]
@DSArtyFixLife 
All the information you need to change the homepage and profile images is in the [first reply](https://github.com/NamelessMC/Nameless/issues/113#issuecomment-192763101).
