### ISSUE TITLE
[question] build-in avatar service.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1134]
If the user has uuid and is a premium account, the skin appears. But if the uuid is not specified or the user name is specified instead of uuid, always steve or an empty picture will appear?

**Comment by samerton** [comment]
Due to how avatars are obtained from Mojang's API, UUIDs are required for the built-in avatar service to work.

It is not possible to obtain an avatar from Mojang's API using a username or a non-premium UUID.

**Comment by baxandrei** [comment]
And if no uuid is provided, will display steve?

**Comment by samerton** [comment]
Yes, that is correct.

**Comment by baxandrei** [comment]
ok, thanx, you can close.
