### ISSUE TITLE
[suggestion] forums

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1135]
I suggest that when an forum post is not readed to highlight it until it is read. Also the forum / category / subcategory who have unread messages must be differentiated from another category where all messages are read.

And also to send a notification to the user when someone responds to his message from the forum.

**Comment by samerton** [comment]
Thanks for the suggestions.

https://github.com/NamelessMC/Nameless/issues/710 regarding unread posts

Apart from tagging users, topics can now be followed from a718d3a14fe96d24c5ee5e22fbdc7c4637333a4b
