### ISSUE TITLE
suggestion for terms page.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1143]
Add posibility to translate {$NAMELESS_TERMS}.

**Comment by partydragen** [comment]
Well its saved in the database in nl2_settings if i remember correct

**Comment by baxandrei** [comment]
I can`t find it. sorry.

**Comment by samerton** [comment]
Currently there are no plans to add the option to translate this I'm afraid.

**Comment by baxandrei** [comment]
Ok, thanx, you can close :D
