### ISSUE TITLE
Bug when changing UUIDs of Users in Admin CP

### ISSUE THREAD

**Issue by niclsw** [NamelessMC/Nameless#1147]
#### Bug:
**What kind of issue is it?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.20.  
**How would you describe the issue?** When changing UUID of a user, if you don't delete the '-' from the UUID, it responds with a blank red box. Having a clearer error message would help. EX: "Please remove '-' from your UUID"
**Do you have an idea how or where the issue occurs?** Admin CP > Users

**Comment by samerton** [comment]
Thanks, fixed in dae5942e700a9fb829377a90d1718ca66abc0dde
