### ISSUE TITLE
Minecraft Market/Buycraft 

### ISSUE THREAD

**Issue by BioticMax** [NamelessMC/Nameless#115]
Is it possible to hook a minecraft market, or buycraft website up to your website?

**Comment by HappyHarm** [comment]
Yes this is possible.

**Comment by samerton** [comment]
As @HappyHarm says, this is possible and you can do this via the AdminCP -> Addons and clicking the settings icon to the right of "Donate". You'll need your Buycraft/Minecraft Market API key which is the you paste into the plugin config file on your server.
