### ISSUE TITLE
Making a new group on v2 gives you an error that it doesn't exist, but works fine afterward

### ISSUE THREAD

**Issue by TheRealPear** [NamelessMC/Nameless#1155]
### Template:
* What kind of issue is it: Bug
* In which version of NamelessMC did it occur: v2.0.0pre4 (Apache)
* How would you describe the issue? When making a new group, a message will appear that the new group doesn't exist, but still creates it.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? [Click here to view image](https://i.imgur.com/wwf3FT1.png)
* Do you have an idea how or where the issue occurs? I think that the software gets confused and it just tries to open the group setting before making a new group.
* What Modules are you using? Users & Group
* What theme are you using? Default

**Comment by samerton** [comment]
Thanks, fixed in a19e0e07f1697dff140e0bea8e834b48b9bdea87
