### ISSUE TITLE
suggestion for post_view.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1161]
Add an option to disable Highlight effect. https://github.com/NamelessMC/Nameless/issues/1128 or to change the color of effect.

**Comment by samerton** [comment]
As of c5aa6cd1e288d294009e8148eb1a322ec5b452c7 it is now down to the template, so it can be removed or modified accordingly (see [here](https://stackoverflow.com/questions/795600/change-highlight-color) for info on changing colour).

**Comment by baxandrei** [comment]
Thanx man!
