### ISSUE TITLE
XAMPP - Bug or magic?

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1169]
Hello, Im running XAMPP on windows 10, at home.
Whats going on? INSTALLER again.
Why in nlmc v1 i can continue in install proccess but in v(21) i can not? Is it magic? I didnt do any different by these two. But i cannot install v1 bcs of mcrypt and v2 bcs of installer? MAGIC BRO

And how much is required curl and mcrypt?

**Comment by samerton** [comment]
As mentioned [here](https://github.com/NamelessMC/Nameless/issues/1166), you do not need mcrypt if you use the latest release (both of v1 and v2). 

Here is the latest v1 release which does not require mcrypt: https://github.com/NamelessMC/Nameless/releases/tag/v1.0.21

cURL is a requirement, but it should be included in XAMPP already.

**Comment by DSArtyFixLife** [comment]
But I used v21 and the sub patch (/install?step=...) isnt working, but in v19 it is working.

**Comment by samerton** [comment]
The screenshot in your image is a v1 404 page.

Version 2 shouldn't have any 404 issues during the installer either, which leads me to believe you might have installed the v2 files in the wrong folder (and not the namelessmcv2 folder from your screenshot).

**Comment by DSArtyFixLife** [comment]
It is. But while im installing v21 i have a access problem.
(i cannot enter /install?step=...)

**Comment by DSArtyFixLife** [comment]
***Can you Samerton send me copy to clipboard script?

**Comment by DSArtyFixLife** [comment]
Here is the error in Namelessmc v21
![404 ultramine eu - google chrome 17 07 2018 14_56_42](https://user-images.githubusercontent.com/33781032/42818655-c5952a26-89d1-11e8-96c8-315986f0394e.png)

**Comment by samerton** [comment]
Ah I understand.

v21 is actually v1.0.21 (note, it is version 1).

The problem is that you have installed Nameless in the **namelessmc** folder. Version 1 of Nameless must be installed in the main folder of your web host, for example directly at **localhost**.

If you are using XAMPP, see [here](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-166#post-1826883) for information on changing XAMPP's root directory.

**Comment by DSArtyFixLife** [comment]
But I have more sites I do want run ;(

**Comment by samerton** [comment]
Unfortunately there is no way around this.

**Comment by DSArtyFixLife** [comment]
Do you have something like Messenger? This is very slow..

**Comment by samerton** [comment]
You can join our Discord at https://discord.gg/QWdS9CB

**Comment by DSArtyFixLife** [comment]
Is it possible to have more localhosts in xampp like localhost:0000

**Comment by samerton** [comment]
I'm not sure, you'd have to research that yourself.

**Comment by DSArtyFixLife** [comment]
I don't like Discord, it's laggy for me, but I will use it

**Comment by DSArtyFixLife** [comment]
Is possible to set in install other charset? It's hard to change it in all

**Comment by samerton** [comment]
It's possible in the version 2 pre-releases.

**Comment by DSArtyFixLife** [comment]
Is it possible to run registrations without curl? Hosting said me, that they will not allow me curl

**Comment by samerton** [comment]
I'm afraid not, cURL is a requirement for Nameless to work.

**Comment by DSArtyFixLife** [comment]
And what does at all curl do???

**Comment by samerton** [comment]
cURL allows Nameless to query other websites/services, for example querying Mojang's API to get a UUID from a username amongst other things.

**Comment by DSArtyFixLife** [comment]
Aaand, how you just make these links like /install, but it is not located at root-dir?

**Comment by samerton** [comment]
The [.htaccess file](https://github.com/NamelessMC/Nameless/blob/master/.htaccess) takes care of that.

**Comment by DSArtyFixLife** [comment]
But there isnt writted anything like I want to know, How? .htaccess will access it, I know, but where is the conf about the pages that will work under link?

**Comment by samerton** [comment]
The .htaccess sends all requests to the [index.php](https://github.com/NamelessMC/Nameless/blob/master/index.php) file, which then checks the URL the user is accessing to see if the corresponding page file exists ([here](https://github.com/NamelessMC/Nameless/blob/master/index.php#L51-L146)).

**Comment by DSArtyFixLife** [comment]
I dont want be sarastic, but very thanks, I removed all my sites, and installer still doesnt work. But I dont like the sites I removed, so its okay, but the nameless still doesnt work
![object not found - google chrome 18 07 2018 8_39_23](https://user-images.githubusercontent.com/33781032/42864345-65ae689e-8a66-11e8-823d-9c632c1884f6.png)

**Comment by DSArtyFixLife** [comment]
Do you mean htaccess?

**Comment by DSArtyFixLife** [comment]
Nothing happened

**Comment by baxandrei** [comment]
yes,

**Comment by DSArtyFixLife** [comment]
But.. Nothing :/

**Comment by DSArtyFixLife** [comment]
Seriosly? Why that htaccess wasnt there before???

**Comment by samerton** [comment]
It is included in the download, some operating systems hide the .htaccess file (although Windows doesn't).

**Comment by DSArtyFixLife** [comment]
![nameless-1 0 21 zip evaluation copy 18 07 2018 11_34_44](https://user-images.githubusercontent.com/33781032/42873062-a3c1ee54-8a7e-11e8-9313-67e19b8a8e02.png)


What do you say now? O_O

**Comment by samerton** [comment]
Winzip might hide .htaccess files, I haven't used it before so I'm not sure to be honest.

**Comment by DSArtyFixLife** [comment]
Samerton? Im completly translating namelessmc. Why if i rename in pages folders, they will not work?

**Comment by DSArtyFixLife** [comment]
But I renamed in pages folder the admin to administracia but content doesnt work

**Comment by samerton** [comment]
Yes, so you also need to change all links (and other includes such as the sidebar) throughout Nameless from admin/... to administracia/... and pages/admin/... to pages/administracia/...

**Comment by DSArtyFixLife** [comment]
![c__xampp_htdocs_pages_admin_addons php - sublime text unregistered 18 07 2018 12_57_50](https://user-images.githubusercontent.com/33781032/42877512-36c36326-8a8a-11e8-91f3-1d57b35b7d7b.png)
 WHERE? :D

**Comment by samerton** [comment]
Several places, including:
- [core/includes/template/navbar.php](https://github.com/NamelessMC/Nameless/blob/master/core/includes/template/navbar.php#L150)
- [pages/admin/sidebar.php](https://github.com/NamelessMC/Nameless/blob/master/pages/admin/sidebar.php#L3-L17)

And also in every other file in the **pages/admin** folder; search for `/admin` in there and replace it with `/administracia`

Unfortunately as this is a customisation to the Nameless core, I can't help much more.

**Comment by DSArtyFixLife** [comment]
Do you know how to fully change navbar colors in Paper? :(((

**Comment by DSArtyFixLife** [comment]
Hi , how i can rename profile pages, and the admin isnt working.

**Comment by samerton** [comment]
You need to change [this code](https://github.com/NamelessMC/Nameless/blob/master/index.php#L85-L90) in index.php to change profile pages.

Unfortunately I can't help any more with the admin pages, as long as you have renamed everything and changed any includes it should work fine. As you are editing the core, I can't help with it.
