### ISSUE TITLE
Emoji?

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1172]
Hi everyone. Is it possible to put in namelessmc emojies? (Comments, wall posts, posts)

**Comment by DSArtyFixLife** [comment]
Also PM and Alerts

**Comment by baxandrei** [comment]
I think you can add only to the following places:

PM: http://prntscr.com/k90fra
Signature: http://prntscr.com/k90g42
New topic/ post reply/ post edit:  http://prntscr.com/k90gea

**Comment by samerton** [comment]
baxandrei is correct, in Nameless version 2 it is possible to add emojis to private messages, signatures, custom page and forum posts.

**Comment by DSArtyFixLife** [comment]
That means it isn't possible in v1?

**Comment by samerton** [comment]
Correct, v1 only has the selection of smileys available in the post editor (again forum posts, signatures, private messages + custom pages).

**Comment by DSArtyFixLife** [comment]
But is possible to add custom emoji?

**Comment by samerton** [comment]
Info on adding custom emojis to CKEditor is [here](https://ckeditor.com/old/forums/Support/Add-more-smileys-CKeditor), the CKEditor path in Nameless is **core/assets/js**.
