### ISSUE TITLE
Plugin messages

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1174]
Hi, is it possible to change messages? My friend (He's developer) said that I need to contact developer of plugin to change the messages... Any other ways are there or someone can do it?

**Comment by samerton** [comment]
In Nameless version 1, messages are returned by the API on the website.

This means that it's not possible to translate them in version 1. Keep an eye out, as Nameless version 2 has a whole new API with language support, and the v2 plugin (still in development) will have language support too. As a teaser, [here](https://github.com/NamelessMC/Nameless-Plugin/blob/master/NamelessSpigot/src/messages.yml) is the messages file for the new v2 plugin which is still in development.

**Comment by Derkades** [comment]
If you are talking about messages from the plugin, you can configure them in version 1 too. Look for messages.yml (https://github.com/NamelessMC/Nameless-Plugin/blob/v1-Pre-1.1/nameless-spigot/src/main/resources/Messages.yml)
