### ISSUE TITLE
problem with page loading.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1175]
Some users reported that the site is loading harder sometimes or everytime.

**Comment by samerton** [comment]
The most likely cause is that Nameless will query your Minecraft server at intervals of at least 60 seconds. If this query is slow, it might take an extra second or so to load the page.

**Comment by baxandrei** [comment]
This page loads very slow sometimes: https://www.hartexcraft.tk/user/settings/

**Comment by samerton** [comment]
I can't see any reasons within Nameless for this, there are no external queries (other than the previously mentioned Minecraft server query).

This page does include the editor though, which loads a large number of files, although this would only be the editor on the page loading slowly.

**Comment by baxandrei** [comment]
http://prntscr.com/kiey8r

**Comment by baxandrei** [comment]
I see that the page itself makes the site load slowly, not the editor;

**Comment by samerton** [comment]
Can you try enabling the page loading option (AdminCP -> Core -> Debugging and Maintenance), then view the page and check what the page load time is in the footer.

**Comment by baxandrei** [comment]
/: http://prntscr.com/kvhf9m
/forum/: http://prntscr.com/kvhe95
/user/settings/: http://prntscr.com/kvheqe

**Comment by samerton** [comment]
That's really strange, I've sent you a message on Discord.

**Comment by baxandrei** [comment]
The problem has been solved. Thank you so much for your help. It seems the problem was that we had many websites on that dedicated server which uses mysql server, so I chose to use remotely mysql from another server.

**Comment by samerton** [comment]
No problem :)
