### ISSUE TITLE
PHP in index.tpl

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1178]
Hi, Im running NamelessMC v1 (1.0.21) and I want to display online users in index.tpl but... The php isnt working with it. Any fix?

**Comment by baxandrei** [comment]
You need to use smarty

**Comment by DSArtyFixLife** [comment]
How???
I tried. The page would not work.

**Comment by samerton** [comment]
Unfortunately it's not possible to use PHP in .tpl files.

You can copy [this code](https://github.com/NamelessMC/Nameless/blob/master/pages/forum/view_forum.php#L285-L297) from pages/forum/view_forum.php to your pages/index.php file, anywhere before [this line](https://github.com/NamelessMC/Nameless/blob/master/pages/index.php#L241).

Then you can use [this code](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/view_forum_table.tpl#L163-L170) in your index.tpl template file.
