### ISSUE TITLE
Mobile suggestion

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1180]
I propose that there be a special mobile theme that is automatically activated only when you use a phone.

**Comment by samerton** [comment]
I don't have any plans to add anything like this myself currently I'm afraid (although pull requests would be appreciated).

Bootstrap is designed mobile up, so the default Nameless template will work just as well on mobile as it will on bigger devices.

**Comment by baxandrei** [comment]
Ok, thanx.
