### ISSUE TITLE
v2 - click to copy IP

### ISSUE THREAD

**Issue by NiklasEi** [NamelessMC/Nameless#1181]
**What kind of issue is it (Question, Bug, etc.)?** Feature request (with possible PR?).  
**In which version of NamelessMC did it occur (1.x.x)?** v2 pre 4.  
**How would you describe the issue?** Click to copy the IP in the home header.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** I implemented the functionality for my test installation (see https://forum.naturamc.com).

I would love to make this a configurable option and make a PR out of it. Is there interest for that feature? I would of course try to improve the look.

**Comment by samerton** [comment]
Thanks for this :)

To be honest I didn't realise it didn't currently do this, it's a simple language file change that I've added in e27b1b6342f5f44a985a328f6db567474ab748d2

If you'd still like to, a PR to make it look a bit neater would be great.

**Comment by Derkades** [comment]
Maybe this is a better solution:

```
'connect_with_ip_x' => 'Connect now using the IP {x}',
'click_to_copy' => 'Click to copy',
```

{x} = `<strong id="ip" onclick="copyToClipboard(\'#ip\')" data-toggle="tooltip" title="[click_to_copy]">{x}</strong>`

**Comment by NiklasEi** [comment]
That's how I did it, plus a button and a favicon wrapped around the ip.

**Comment by samerton** [comment]
#1190 and c568ce6c17ee4f73cd6fd5989d98c05be41da5f4
