### ISSUE TITLE
Allow for hostname config option instead of relying on $_SERVER['SERVER_NAME']

### ISSUE THREAD

**Issue by excham** [NamelessMC/Nameless#1186]
**What kind of issue is it (Question, Bug, etc.)?** Feature request.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.21.  
**How would you describe the issue?** Currently the source relies on $_SERVER['SERVER_NAME'] to generate URLs. This is awkward when running Nameless behind a reverse proxy, as it exposes the back end hostname. Ideally there would be a (optional?) configuration entry to define a constant hostname to be used instead.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Just search this repo for `$_SERVER['SERVER_NAME']`.
**Do you have an idea how or where the issue occurs?** See above.

**Comment by samerton** [comment]
Thanks for the suggestion, it's been added in 7afb93c2ee1e4dd44cae53b4f4d80b42e9a94901 for the upcoming v2 release
