### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by ImCraftDeveloper** [NamelessMC/Nameless#1187]
Hey,

when click on New Installation

Comes up : Not Found
The requested URL /Forums/install was not found on this server.

Apache/2.4.18 (Ubuntu) Server at PRIV Port 80

Sorry for my english :}

**Comment by samerton** [comment]
Hi,

Nameless version 1 can only be installed directly in your web root, so *not* in the /Forums subfolder.

You can either:
- move Nameless directly into the web root (usually /var/www/html)
- set up a subdomain (eg forums.yoursite.com which points to the /Forums subfolder)
- use the Nameless version 2 development code, which can be installed in a subfolder ([link to repository](https://github.com/NamelessMC/Nameless/tree/v2))

Also, if you haven't done so already, Apache will need configuring so the `.htaccess` file will work. To do this:
1. edit the file `/etc/apache2/sites-available/000-default.conf` (or whichever file corresponds to your site)
2. find the bottom `</VirtualHost>`, and **before** it, add
```
<Directory /var/www/html>
    AllowOverride All
</Directory>
```
where `/var/www/html` is the path to your Nameless installation
3. save and exit the file, and then use the commands
```
sudo a2enmod rewrite
sudo service apache2 restart
```
More information can be found [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache).
