### ISSUE TITLE
Forum suggestion

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1191]
I suggest adding a system of mentions like discord system.

**Comment by samerton** [comment]
Nameless already has mentions, you can @ any username and they will be alerted.

**Comment by baxandrei** [comment]
i will try, thanx.

**Comment by baxandrei** [comment]
yep, thanx :D

**Comment by baxandrei** [comment]
The mentions are not working when u edit a topic and add a mention. 

It would be usefull when you write @ and try to mention somebody  to show a list.

**Comment by Marcos03BR** [comment]
> The mentions are not working when u edit a topic and add a mention.
> 
> It would be usefull when you write @ and try to mention somebody to show a list.

It would be quite good

**Comment by Derkades** [comment]
#2350 #2351
