### ISSUE TITLE
sitemap

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1195]
Where I can find sitemap for google developer console?
![screenshot_1](https://user-images.githubusercontent.com/12484505/43891642-818692c6-9bd2-11e8-9adf-bfc167b4b8b2.png)

**Comment by samerton** [comment]
There's no sitemap yet, it's planned for the full v2 release.

**Comment by baxandrei** [comment]
is something else when you have a sitemap that is constantly generated and updated by the site.

**Comment by samerton** [comment]
Added in 9053de5bb1d2c176feaf10597875564ccabfb382
