### ISSUE TITLE
Thread Prefix

### ISSUE THREAD

**Issue by allenlol** [NamelessMC/Nameless#1196]
### Template:
* What kind of issue is it (Question, Bug, etc.) Features Request
* In which version of NamelessMC did it occur (1.x.x)? 2.0.0- Pr4
* How would you describe the issue? The admin can set the prefix of the thread, and the moderator can se the thread prefixes.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Spigot Thread 
* Do you have an idea how or where the issue occurs? No
* What Modules are you using ? NA
* What theme are you using ? nA

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.21.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by samerton** [comment]
It's currently possible to create topic labels, which you can add to any topic.

Currently once a label is added, it is not currently possible to restrict only certain groups (ie moderators) to view them though.

**Comment by allenlol** [comment]
No, I actually mean you can set the thread prefix, only for Moderator or Permissionable MEmber

**Comment by allenlol** [comment]
Because at the currency, you can only set the label when u creating the thread.

**Comment by samerton** [comment]
It's possible for a moderator/admin to edit the first post in a topic and add/change the label there.

**Comment by allenlol** [comment]
I saw it, thank you.
