### ISSUE TITLE
Login using either username/email

### ISSUE THREAD

**Issue by iJustErik** [NamelessMC/Nameless#1197]
Could we have the option to use email AND password for logging in? Maybe it says username/email, but you can login using both, also what is the markdown option vs html do?

**Comment by allenlol** [comment]
Agree, just check if the string contains @ to specify its email or username

**Comment by samerton** [comment]
With the editors, HTML = the fancy HTML editor where you can easily format your posts, and markdown is a simple textarea with support for Markdown (which is the formatting used on Discord or here on Github for example).
