### ISSUE TITLE
Ability to add icons to built in pages

### ISSUE THREAD

**Issue by iJustErik** [NamelessMC/Nameless#1198]
This is for v2. Maybe a config option in the admin cp to change icons for forums/home? Or just in the language file? thx <3

**Comment by samerton** [comment]
This has been added since pre-release 4 and will be included in the next pre-release :) ([commit](https://github.com/NamelessMC/Nameless/commit/5079e8ab38e56abab8e5dc75b20e8d27b6a04850))

**Comment by iJustErik** [comment]
tehee ;)
