### ISSUE TITLE
[suggestion] add custom dropdown menus in menu

### ISSUE THREAD

**Issue by BaxAndrei** [NamelessMC/Nameless#1201]
add custom dropdown menus in menu with permissions too

**Comment by DSArtyFixLife** [comment]
@baxandrei It's very good idea, but it is possible already. In administration is template editor, there you can without problem make your own dropdown.
But I know, everyone cant know HTML &  Bootstrap so I also think it is good idea.
Sorry for my bad English

**Comment by baxandrei** [comment]
You are right, but it is easier because there are users here who do not know how to do this. Although we know how to do this, I think it's a good idea for others and it will help.
