### ISSUE TITLE
[IDEA] Type of Application

### ISSUE THREAD

**Issue by sampuranxd** [NamelessMC/Nameless#1205]
So I was thinking that you could have multiple applications. First there would be a dropdown thats like what you want to type in such as Moderator, Head Moderator, Developer, Discord Manager Etc. Then the questions would be specific that pop up is also customizable. Like first its just 1 dropdown menu but then after you choose, the questions related to that will appear.

**Comment by samerton** [comment]
Thanks for the suggestion! I'm going to link this with #205 with more customisable (and multiple) forms.
