### ISSUE TITLE
Errors on NamelessMC 2

### ISSUE THREAD

**Issue by SGTshan** [NamelessMC/Nameless#1208]
**What kind of issue is it (Question, Bug, etc.)?** Bug, I guess?.  
**In which version of NamelessMC did it occur (1.x.x)?** 2.0.0 pre-release 4
**How would you describe the issue?** When I load up my site it gives me errors in the console and Javascript things, like dropdowns, are not working.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](https://i.imgur.com/BIEJPfe.png)  
**Do you have an idea how or where the issue occurs?** No idea, it just happend, I just created some forums.

**Comment by samerton** [comment]
Can you send me a link to your site?

This is usually caused when the path entered in the installer is not correct (you can check it in the file core/config.php).

**Comment by SGTshan** [comment]
[My site.](https://sgtshan.tk)

Nameless is located at the root dir of my website, so the "path" field in the config is empty.

**Comment by samerton** [comment]
Very strange, for some reason both the `custom/templates/Nextyle/js/bootstrap.min.js` and  `custom/templates/Nextyle/js/jquery.min.js` files have become corrupted; can you try reuploading just those two again?

**Comment by SGTshan** [comment]
After Reuploading and clearing cache it was fixed!

Thanks!
