### ISSUE TITLE
ERROR WHEN THE INSTALLATION HAS ENDED

### ISSUE THREAD

**Issue by ImNacho** [NamelessMC/Nameless#1214]
* What kind of issue is it (Question, Bug, etc.)? Error
* In which version of NamelessMC did it occur (1.x.x)? 1.0.21
* How would you describe the issue? I install version 1.0.21, but when I finish the installation it tells me that the page is not found and is connected to the index.php
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? https://imgur.com/a/bXgweZO
* Do you have an idea how or where the issue occurs? No tengo idea
* What Modules are you using ? No module
* What theme are you using ? Any

**Comment by ImNacho** [comment]
If I download that version, can that error be solved?

**Comment by ImNacho** [comment]
Now i install the version 2 pre-release , but this is the new problem, https://imgur.com/a/GHfOPLT

**Comment by samerton** [comment]
You have enabled "Friendly URLs" without having the .htaccess file present, or the server is not configured to allow the .htaccess file.

To disable friendly URLs, edit the Nameless file `core/config.php` in a text editor, and change `'friendly' => true,` to `'friendly' => false`,

**Comment by ImNacho** [comment]
How can I disable the friendly url without getting that error?

**Comment by samerton** [comment]
The information in my last reply will tell you how to disable friendly URLs, to prevent the error.

If you want to keep friendly URLs enabled, you will have to follow the steps [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache) to configure Apache to allow the use of .htaccess files.

**Comment by ImNacho** [comment]
What happens is that I activate the maintenance mode on the page and it does not let me enter the admin panel because I get maintenance mode, and I do not know what I can do to remove it, could you help me?

https://imgur.com/a/xX8fNEc

**Comment by samerton** [comment]
I'll mark this as close as the initial issue has been resolved :)
