### ISSUE TITLE
Workpost wanted...

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#1216]
Hello, my name is Arty, I love programing (css, js, jquery and php) and I want to work on NamelessMC software, to help you out. I'm from Slovakia, so I can make translates, because actual Slovak language is very bad, mostly it isnt finished. Also I can make CSSs for NamelessMC, or help with PHP... Sorry for my bad English... :)

**Comment by DSArtyFixLife** [comment]
To start... I have a tip for you... Add Favicon uploadment, it will be smarter for people.

**Comment by DSArtyFixLife** [comment]
Check out what I made for example...
![home minicube eu - google chrome 16 09 2018 12_52_02](https://user-images.githubusercontent.com/33781032/45595658-6cc40080-b9af-11e8-8505-2d84da956863.png)

**Comment by samerton** [comment]
Hi,

Nameless is a community project, please feel free to fork the repository and work on anything you like.

You can also publish templates/themes on [our website](https://namelessmc.com/resources/).
