### ISSUE TITLE
Support button/form in AdminCP

### ISSUE THREAD

**Issue by ItzArty** [NamelessMC/Nameless#1219]
Hello, @samerton! I've got great idea. What about making a basic knowledge wiki for NamelessMC on official site, wich will include all most asked questions and their answears? I don't know how did you make the update verification, but isn't possible to make something, like support? I mean, that in admincp will be a button to contact namelessmc support, and with auto-update you can help all your customers with their problems instantly. You do not need to make support center. But you can only use smartsupp, wich can very help you customers.

Sorry for my bad English.

**Comment by baxandrei** [comment]
https://github.com/NamelessMC/Nameless/issues/1162

**Comment by DSArtyFixLife** [comment]
@baxandrei, no. It is module, no module than core is still active, and about wiki, i said on official website, how can someone who has problems with it make wiki, you didn't understand.

**Comment by IsS127** [comment]
We mainly use discord or github for support. When we have our wiki page done and released, we will try to put as many solutions for problems, common q&a and more.

**Comment by Derkades** [comment]
We could add a support page to AdminCP and add https://widgetbot.io/, which allows you to chat in a discord server in a widget, without creating an account. On the other hand, we may want to stay away from using third party widgets in this open source program. It's not much work to create a discord or github account.

**Comment by samerton** [comment]
I think our current support methods are sufficient, I'll close this issue
