### ISSUE TITLE
Rank sync with playerInfo API method

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1220]
Use the serverInfo API method to synchronise ranks between Minecraft server(s) and the website.

- Multiple servers might send conflicting data. How do we handle that?
- People might want to exclude specific ranks from being synced. Create a page in AdminCP where people can blacklist specific ranks or servers. This page should also have a short explanation of how rank sync works and how to enable it in the plugin.
- The interval at which servers send data is configurable. It might vary from several times per second to a few times a day. The website should be able to handle this

**Comment by Derkades** [comment]
Added in v2-pre5

**Comment by ZandercraftGames** [comment]
Where is this?

**Comment by samerton** [comment]
@ZandercraftGames StaffCP -> Configuration -> API -> Rank Sync (v2 only)

**Comment by Derkades** [comment]
Some more info here: https://github.com/NamelessMC/Nameless-Plugin/wiki/v2:-Rank-sync

**Comment by ZandercraftGames** [comment]
Thanks :smile:
