### ISSUE TITLE
Forums table not loading/showing

### ISSUE THREAD

**Issue by craigbdev** [NamelessMC/Nameless#1234]
What kind of issue is it (Question, Bug, etc.)? Bug
Which version of NamelessMC did it occur? Release 1.0.21
How would you describe the issue? The forums table doesn't load up/show.
From error reporting: 
Notice: Constant MQ_SERVER_ADDR already defined in /home/playspir/public_html/core/integration/status/global.php on line 2

Notice: Constant MQ_SERVER_PORT already defined in /home/playspir/public_html/core/integration/status/global.php on line 3

Notice: Constant MQ_TIMEOUT already defined in /home/playspir/public_html/core/integration/status/global.php on line 4

Notice: Constant PRE already defined in /home/playspir/public_html/core/integration/status/global.php on line 5

Fatal error: Cannot declare class MinecraftPingException, because the name is already in use in /home/playspir/public_html/core/integration/status/MinecraftServerPing.php on line 5

Do you have an idea how or where the issue occurs?: I'm sure that it's in the global.php file but I just don't know how to modify it.

**Comment by craigbdev** [comment]
This is also what my global.php file looks like:

<?php
define( 'MQ_SERVER_ADDR', $default_ip );
define( 'MQ_SERVER_PORT', $default_port );
define( 'MQ_TIMEOUT', 1 );
define( 'PRE', $pre17 );

require('core/integration/status/MinecraftServerPing.php');

$Timer = MicroTime( true );

$Info = false;
$Query = null;

try
{
	$Query = new MinecraftPing( MQ_SERVER_ADDR, MQ_SERVER_PORT, MQ_TIMEOUT );
	if(PRE == 0){
		$Info = $Query->Query( );
	} else {
		$Info = $Query->QueryOldPre17( );
	}
}
catch( MinecraftPingException $e )
{
	// Error, insert into database
	$queries->create('query_errors', array(
		'date' => date('U'),
		'error' => htmlspecialchars($e->getMessage()),
		'ip' => $default_ip,
		'port' => $default_port
	));
	//$Exception = $e;
}

if( $Query !== null )
{
	$Query->Close( );
}

$Timer = Number_Format( MicroTime( true ) - $Timer, 4, '.', '' );

?>

**Comment by samerton** [comment]
Are you using a custom Nameless template/theme?

**Comment by craigbdev** [comment]
Oh yeah, forgot to mention I'm using Elixir.

**Comment by craigbdev** [comment]
Thank you so much! It worked!
