### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1253]
SITE: https://www.hartexcraft.tk

When you are not connected, the widget with the latest posts on the forum does not work

Search does not work as well.
`Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null in /var/www/.clienti/hartexcraft/core/classes/DB.php:76 Stack trace: #0 /var/www/.clienti/hartexcraft/core/classes/DB.php(76): PDOStatement->execute() #1 /var/www/.clienti/hartexcraft/core/classes/DB.php(175): DB->createQuery('INSERT INTO nl2...', Array) #2 /var/www/.clienti/hartexcraft/core/classes/Log.php(215): DB->insert('nl2_logs', Array) #3 /var/www/.clienti/hartexcraft/modules/Forum/pages/forum/search.php(77): Log->log('forum_search', '12313') #4 /var/www/.clienti/hartexcraft/index.php(84): require('/var/www/.clien...') #5 {main} thrown in /var/www/.clienti/hartexcraft/core/classes/DB.php on line 76`

**Comment by samerton** [comment]
There's been a behind the scenes change for guest forum permissions. For the latest posts widget:
- visit the AdminCP -> Forums tab
- edit every forum, and simply click "Submit" at the bottom for permissions to update

The guest search issue is fixed in ff1ebac76c72607befb0a3895f436796ebb15b1d

**Comment by baxandrei** [comment]
uh.. ok.. :)))
