### ISSUE TITLE
Debugging & Maintenance problem.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1261]
These 2 pages do not have a log file. 1. http://prntscr.com/l3yfgh 2. http://prntscr.com/l3yfp6

Even if it is empty, should not it look like this? http://prntscr.com/l3yfv8

**Comment by samerton** [comment]
The log files in 1 and 2 haven't been generated yet, they will be automatically generated when a warning or notice is created on your site.

An empty log showing as empty is intended, as the file exists it simply outputs the contents of the file even if it's empty. 
I'm not sure this needs changing to be honest, although any pull requests to change this can be reviewed.
