### ISSUE TITLE
Show file name in editor

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1262]
When editing a file from a template, the file name appears during editing: http://prntscr.com/l3yolg

EDIT1: default: http://prntscr.com/l3yp7k
EDIT2: and the directory you are in

**Comment by IsS127** [comment]
Or just make it similar to forums, showing which directory then file.

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/3132704d2d90c152f9f2e7fee5a6fccdf9445050

**Comment by baxandrei** [comment]
Thanx.
