### ISSUE TITLE
Email Error

### ISSUE THREAD

**Issue by Casb02** [NamelessMC/Nameless#1267]
I have a error http://prntscr.com/l60xvb

How can i fix this Email Error.

Release 1.0.21.

**Comment by samerton** [comment]
Hi,

You can create the file **email.php** in the public_html/core folder, and paste [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/core/email.php) inside.

**Comment by Casb02** [comment]
Thx it worked
