### ISSUE TITLE
Friends System

### ISSUE THREAD

**Issue by claushbang** [NamelessMC/Nameless#127]
Hello,

Firstly, I apologize if this has already been suggested (haven't looked through). Currently the friends system allows anyone to add each other to be friends. Would it be possible to have this system turned into a "friend request" system, so a person would have to accept the incoming request in order for it to be accepted?

Thanks for your continued and hard work on this. Best Forum/CMS out there.

**Comment by samerton** [comment]
I think the way I'll do this (for now, at least) is simply to have the friend system "one way", so if you add a user as a friend, it'll only display on your profile and not theirs until they then add you in return.

**Comment by claushbang** [comment]
I prefer your system better, honestly.

**Comment by samerton** [comment]
This was actually completed back in v1.0.7, I'll close this now.
