### ISSUE TITLE
In UserCP, have an option for "Default" language.

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1275]
Right now, when the default language is set to say English, users that register will have their language set to English. When the site owner changes it to a different language, only users that register afterwards will use the new default language.

In my opinion this should be changed. By default, there should be no language specified for a user (NULL in database). When a web page is loaded and the user language == null, the default website language is used. User can still change their language in UserCP. If the default language is changed in AdminCP, all users who have not explicitly set a language will see the website in the new default language.

**Comment by samerton** [comment]
The new panel has the option to update the default language for all users, the only caveat is it will update the language for users who may have changed their language already.

**Comment by Derkades** [comment]
I guess that's fine. The system I suggested doesn't have enough benefits to be worth implementing imo. Feel free to close the issue or leave it open depending on your opinion.
