### ISSUE TITLE
No install.php?

### ISSUE THREAD

**Issue by Danielh90** [NamelessMC/Nameless#128]
I tryed to install it last night and I looked in the files and there was no install.php?

**Comment by samerton** [comment]
The install.php is located in the **pages** directory, even though the URL points directly to it; this is normal.

If your browser can't find the install.php file, you will need to modify your server configuration to enable the use of .htaccess files and also Apache's mod_rewrite module.

If you're running Ubuntu, [this guide](http://askubuntu.com/a/48363) should help you out.

**Comment by Danielh90** [comment]
Thank you

On Wed, Mar 16, 2016 at 9:24 AM, samerton <notifications@github.com> wrote:

> The install.php is located in the *pages* directory, even though the URL
> points directly to it; this is normal.
>
> If your browser can't find the install.php file, you will need to modify
> your server configuration to enable the use of .htaccess files and also
> Apache's mod_rewrite module.
>
> If you're running Ubuntu, this guide <http://askubuntu.com/a/48363>
> should help you out.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NamelessMC/Nameless/issues/128#issuecomment-197353166>
>



-- 
Thank you
- Daniel
