### ISSUE TITLE
missing icons in acp menu.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1280]
http://prntscr.com/ldq9qp

**Comment by baxandrei** [comment]
http://prntscr.com/ldr20z menu items are also set strange.

**Comment by samerton** [comment]
These issues are to do with the cache; I've been changing entries stored in the cache during panel development with no option to update/reset the cache.

It's possible to do this manually, by deleting the file **f068dd5fa2de0ad75c7380f550e12fbb6d0ac70e.cache**

**Comment by baxandrei** [comment]
Thanx.
