### ISSUE TITLE
E-Mail settings doesn't show.

### ISSUE THREAD

**Issue by EugenioYT** [NamelessMC/Nameless#1281]
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.21.  
**How would you describe the issue?** The E-Mail settings page loads, but it doesn't show up the things to change E-Mail address, etc.. 
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** I have a screenshot of it. https://imgur.com/a/Oa9jp0X
**Do you have an idea how or where the issue occurs?** I think it's something about a file that displays that.

**Comment by ZeroTimez** [comment]
Yea, i also get this issue. I tried to reload the  page but it not working.

**Comment by EugenioYT** [comment]
Yep. :(

**Comment by samerton** [comment]
Unfortunately there's an issue in the latest release to do with the email config file.

To fix, you can manually create the file **core/email.php**, and paste this inside: https://raw.githubusercontent.com/NamelessMC/Nameless/master/core/email.php

**Comment by EugenioYT** [comment]
Thank you, now it's working! 👍

**Comment by EugenioYT** [comment]
close
