### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ryanrox333** [NamelessMC/Nameless#1282]
What kind of issue is it (Question, Bug, etc.)? Error
In which version of NamelessMC did it occur (1.x.x)? Release 1.0.21
How would you describe the issue? I would name it a Connection Issue and a File Error.
Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Yes! They are at the bottom.
Do you have an idea how or where the issue occurs? I was on my website opsb.ml and doing the database setup.
What Modules are you using ? None
What theme are you using ? None

https://gyazo.com/4a0206a6882d86a9c562ee41a8524bcd

**Comment by samerton** [comment]
Resolved via Discord, the issue was with the database details entered.
