### ISSUE TITLE
HELP FORUM 

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#1287]
https://ctrlv.cz/5HAD

HELP 

I have the theme Elixir and I can not write to the forum, thanks for your help

**Comment by samerton** [comment]
Can you press **F12** to open your browser console. Are there any errors in the browser console?

**Comment by PixelNotFound** [comment]
I think one of your extensions is blocking that div of showing up.

**Comment by samerton** [comment]
Were you able to take a look @zikycz?

**Comment by DampfWaffel** [comment]
i kinda have the same "Error" here.

<img src="http://i.epvpimg.com/8JjGeab.png" alt="" title="Hosted by epvpimg.com" />

**Comment by samerton** [comment]
@DampfWaffel it looks like you need the following:

- Create a new forum, and set it as a "Category" and *not* a "Discussion forum"
- Edit the rest of your forums and set their "Parent Forum" option as this new category

Also, make sure you have set permissions for each forum so everyone can view them, and you may want to change "Forum Layout" from "Latest Discussions view" to "Table view" (AdminCP -> Forums, in your second screenshot).

---
As this is template related (and *not* related to NamelessMC itself), and the author hasn't responded, I'll mark this issue as closed.
