### ISSUE TITLE
SMTP Nameless v2-pre4

### ISSUE THREAD

**Issue by Casb02** [NamelessMC/Nameless#1288]
Info:
Nameless V2 pre4

Hello,
Is there a possibility that you can use smtp in version 2?

best regards,
Cas

**Comment by samerton** [comment]
Hi,

Yep, this is indeed possible.

You can configure SMTP details in the AdminCP -> Core -> Email tab (in both v1 and v2).

**Comment by Casb02** [comment]
Sorry, i can not find it. https://prnt.sc/lflm1s

**Comment by Casb02** [comment]
Thx
