### ISSUE TITLE
Apostrophe in forum post is broken.

### ISSUE THREAD

**Issue by digiwiz11** [NamelessMC/Nameless#1290]
If you type an apostrophe in the forums, when you you go back in to edit the forums the rich text editor is blank.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type a message that contains an apostrophe '
2. Save forum post
3. Edit the forum post
4. It will now be blank.

It looks like apostrophe are not being appropriately escaped.

NamelessMC v2 Pre5

**Comment by samerton** [comment]
Thanks, should be fixed in https://github.com/NamelessMC/Nameless/commit/a05e8e2eb64704dae2a9a158ea5c8e8fa9d44623 :)
