### ISSUE TITLE
HELP - THEME - ELIXIR

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#1311]
Hello, please downloaded the theme and templates Elixir, but we do not show up on the forum who posted the last post on the forum .https://ctrlv.cz/JBNj How to fix it to work, and there was a column with the one who added it as the last post. https://ctrlv.cz/4mS0 Thank you very much..

PHOTO: https://ctrlv.cz/JBNj - https://ctrlv.cz/4mS0
THEME: https://www.spigotmc.org/resources/elixir-template-namelessmc-v1-0-21.61081/

**Comment by Tyrelis** [comment]
@zikycz Please join this discord for help on the template directly from the author. https://discord.gg/ZvhDKav

**Comment by samerton** [comment]
Unfortunately as this is not an official NamelessMC template, we can't provide support for it here.

As Tyrelis says, you can join the Discord to get support from the author, or open an issue in the template repository here: https://github.com/xemah/ElixirTemplate
