### ISSUE TITLE
[bug] post-validate

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1313]
Post-Validation group dosen`t work. After the user confirms the account, they are still unconfirmed member.

same problem as here https://github.com/NamelessMC/Nameless/issues/1065

I tested with 2 installations of NL

**Comment by samerton** [comment]
Fixed in c46dedc08c6a96a85a8664902f3d2fc55b002b9e

**Comment by baxandrei** [comment]
thanx
