### ISSUE TITLE
[ACP/Forums Suggestion] Suggestions for the list of forums.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1314]
- [x] Forums to be displayed differently from the categories to make it easier to differentiate. (http://prntscr.com/lkl7dq)~~

- [x] Drag and drop to sort categories and forums more easily.~~

- [x] The ability to change when editing a forum or a category, its type (to be changed from forum to category and vice versa).~~

- [x] When editing a forum, select the parent forum, list of forums to be ordered . Like here: https://github.com/NamelessMC/Nameless/issues/1129~~

- [x] Also, the list here https://github.com/NamelessMC/Nameless/issues/1129 and the one with parent forums (select) needs to show the categories and the forums differently to make it easier to differentiate.
```
Category
 - Forum 1
 - Forum 2

Category 2
 - Forum 1
 - Forum 2
   - Sub Forum 1
```

**Comment by samerton** [comment]
2. added in https://github.com/NamelessMC/Nameless/commit/eff35f84e832b2dc2865054d4890e7d1cbf6240e

**Comment by samerton** [comment]
The problem with 1. is forums will always be shown in the order set by the user. This does *not* take parent forums into account; this would break when you try to change forum order.

For that reason, I can add the indent to show a forum is not a parent, but it would not always be underneath its parent unless the user has set the order that way.

**Comment by baxandrei** [comment]
thanx

**Comment by samerton** [comment]
4. added in https://github.com/NamelessMC/Nameless/commit/4f6264eeda4a11165707197f4d2e1c799a0a9e75

**Comment by samerton** [comment]
3. added in https://github.com/NamelessMC/Nameless/commit/e3dd0ff0bf434964f9ef9944d7a3f4f9a02810a8

**Comment by samerton** [comment]
For 5, the Move Topic dropdown doesn't include categories. Just wondering if you could clarify @baxandrei?

**Comment by baxandrei** [comment]
Order show like here: https://github.com/NamelessMC/Nameless/issues/1129
by user sort order

**Comment by samerton** [comment]
5. added in d4a1e0a02a2c0332a55578646bfd0b630a4e79a0

**Comment by baxandrei** [comment]
thanx
