### ISSUE TITLE
Discord Hook bug.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1316]
If I have space in the message (" "), the discord message will contain `&nbsp;` when posting a topic.

**Comment by samerton** [comment]
Does https://github.com/NamelessMC/Nameless/commit/a644ab732736bba0b07f8c4550e42942f6ce483d help with the issue?

**Comment by favorit5503** [comment]
Hi, i have a similiar problem if i make a topic using hungarian characters for á = &aacute; Is there any fix for this?

**Comment by favorit5503** [comment]
I fixed it here is a possible fix if anyone has this problem
https://pastebin.com/yN00PmUM
