### ISSUE TITLE
Code blocks option in editor

### ISSUE THREAD

**Issue by BaxAndrei-SEC-ACC** [NamelessMC/Nameless#1318]
It would be very useful to add possibility to add codes in posts. (I think a button added to insert code would be very useful in the text editor.)

https://ckeditor.com/cke4/addon/codeTag

```
like
here
```

**Comment by samerton** [comment]
v2 did originally have a code editor, unfortunately it's *really* not easy to get right.

I do want to re-enable it at some point, there are so many issues with it I don't know when it will be.

**Comment by BaxAndrei-SEC-ACC** [comment]
Ok

**Comment by baxandrei** [comment]
I asked because it would have been very useful to me, but I will wait it to be reintroduced when you decide.

**Comment by baxandrei** [comment]
I think an idea would be to have an option if someone wants to activate it and be deactivated initially.

**Comment by samerton** [comment]
Changed editor library in https://github.com/NamelessMC/Nameless/commit/1f4da1306dfac055130974ccf3069ec48b84e34d which now includes code block support.

**Comment by baxandrei** [comment]
thanx.
