### ISSUE TITLE
Cant enable access to .htacces, What to do?!

### ISSUE THREAD

**Issue by TrollStar12345** [NamelessMC/Nameless#132]
Hi,

I keep getting the 404 page not found, and I'm not sure why (Probabaly .htacces file), although I dont know how to turn it on (And I dont use Ubuntu so cant use your guide)

Please could you tell me how I can enable it?

Thanks!

**Comment by samerton** [comment]
Which operating system do you use?

**Comment by TrollStar12345** [comment]
Im not sure, its a hosting company so likley to be linux

**Comment by samerton** [comment]
Have you installed Nameless directly into the root directory (the main folder) of your webserver?

**Comment by TrollStar12345** [comment]
Yes, I have

**Comment by samerton** [comment]
One last thing I can think of is that the .htaccess file might not have been uploaded. Can you check your webserver to see if there is a file in the root directory named ".htaccess" containing [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess)?

If not, unfortunately I can only assume your host is not compatible with the software.

**Comment by TrollStar12345** [comment]
I can only see the file withftp, but will check code later, ty

**Comment by TrollStar12345** [comment]
Yeesss! Thank you very much!! <3
