### ISSUE TITLE
New variables

### ISSUE THREAD

**Issue by RexEtImperator** [NamelessMC/Nameless#1326]
number of registered users, number of users online, number of guests online, number of total online, number of total threads, number of total posts

https://imgur.com/a/gvUJD

**Comment by samerton** [comment]
Topic + post counts added in https://github.com/NamelessMC/Nameless/commit/b64b74c34eedd3c58f2614945ea187ead09384b2

**Comment by samerton** [comment]
Remaining variables added in the Statistics widget (which you **must** have enabled to use these) in this commit: https://github.com/NamelessMC/Nameless/commit/963c1b4c1bd06eedd9f5376edf7bd76fd764f7ab

New variables for the labels (**not** the values):
```
{$TOTAL_THREADS}
{$TOTAL_POSTS}
{$USERS_REGISTERED}
{$USERS_ONLINE}
{$GUESTS_ONLINE}
{$TOTAL_ONLINE}
```
and the values:
```
{$TOTAL_THREADS_VALUE}
{$TOTAL_POSTS_VALUE}
{$USERS_REGISTERED_VALUE}
{$USERS_ONLINE_VALUE}
{$GUESTS_ONLINE_VALUE}
{$TOTAL_ONLINE_VALUE}
```
