### ISSUE TITLE
[Suggestion] Server list

### ISSUE THREAD

**Issue by RexEtImperator** [NamelessMC/Nameless#1330]
Online users on the server shown by the progress bar, server address

**Comment by samerton** [comment]
Ability to display server address added in 64b4794a1ab7c0d8999fad446fc02323945c5cb4

Not sure I'll be adding a progress bar to the default templates as I'm not sure how they would fit in with the designs (plus, with Default Revamp, Semantic UI progress bars are a bit tricky).
