### ISSUE TITLE
Cannot Create Admin Account During Install

### ISSUE THREAD

**Issue by tyguy210** [NamelessMC/Nameless#134]
During the installation, everything goes smoothly until I get to the "account" step. It will not create the admin account, I get this everytime:

Unable to create account. Please check:
- You have entered a username between 4 and 20 characters long
- Your Minecraft username is a valid account
- Your passwords are at between 6 and 64 characters long and they match
- Your email address is between 4 and 64 characters

I have checked all of these multiple times, even tried different emails, valid minecraft usernames, and passwords, nothing works.

**Comment by CitrusFruit** [comment]
Having the same issue, unfortunately.

**Comment by samerton** [comment]
I'll have a look into it.

**Comment by samerton** [comment]
It's probably an issue with file_get_contents on your webserver, I've gone ahead and removed the requirement for the admin account to be a verified premium Minecraft account.

You can apply this change now by replacing the contents of **pages/install.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/pages/install.php).
