### ISSUE TITLE
NamelessMC.com website is down

### ISSUE THREAD

**Issue by Zyrexus** [NamelessMC/Nameless#1345]
(Ignoring the template because it's not with the software itself.)

I don't know if you know but the site has been down for like 14 hours or something like that.

**Comment by samerton** [comment]
Unfortunately this is currently out of my control, I've notified the host.

**Comment by dwilson5817** [comment]
My apologies about this.  There was a disk failure on the server I use to host the site so I've spent the past 24 hours reinstalling the OS and re-configuring the server.  I've restored the website data and thus the access has been restored.

Sorry again.
