### ISSUE TITLE
Can't edit user info

### ISSUE THREAD

**Issue by RobiGames** [NamelessMC/Nameless#1347]
**Can't change or edit user information or group.
I'm using version V2 pre 5.**

1. StaffCP
2. Login
3. User Management
4. Users
5. Action: Edit

**If you change or edit something and then save or hit enter then you get an error:**

_Uncaught Error: Class 'Michelf\Markdown' not found in /home/u193262681/domains/gaming-godz.com/public_html/modules/Core/pages/panel/users_edit.php:186
Stack trace:
#0 /home/u193262681/domains/gaming-godz.com/public_html/index.php(84): require()
#1 {main}
  thrown_

**Comment by samerton** [comment]
This was hopefully fixed in https://github.com/NamelessMC/Nameless/commit/e21cd7e052ef75c5bea3d5aa0e3b982592d5513c, which will be included in the next release.

It's possible to manually apply the changes from the commit to apply the fix now.
