### ISSUE TITLE
GA gtag.js

### ISSUE THREAD

**Issue by CodingWithAdin** [NamelessMC/Nameless#1348]
I have an Question
I need to know where to paste gtag.js tracking code snippet, i didn't find where could I

**Comment by samerton** [comment]
**Nameless v1**
- First, add `?>` to the end of the file **core/includes/template/header.php**
- Second, add your full <script>...</script> tag as provided by Google *after* this newly added `?>`

**Nameless v2**
- Add the full <script>...</script> tag as provided by Google *before* [</head>](https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/header.tpl#L37) within **custom/templates/Default/header.tpl**
- Depending on the formatting of the script, you may need to add `{literal}` before `<script>` and `{/literal}` after `</script>`

**Comment by CodingWithAdin** [comment]
It is yet not working

**Comment by samerton** [comment]
Could you send me a link to your site?

**Comment by CodingWithAdin** [comment]
Here: http://wormprisons.gq/

**Comment by samerton** [comment]
It looks like only the GA tag has been added, could you paste in the full `<script> ...... </script>` tag provided by Google into the module?

**Comment by CodingWithAdin** [comment]
oh I actually removed the scrip't after it not working, I did it now, you can check the site now

I added it like this:
...
>?
GA code

**Comment by samerton** [comment]
The script is there now, it should be working fine.

One side note is that it looks like you also have `UA-121058130-2` *before* your script, you can remove this as it's simply being shown as text.

**Comment by CodingWithAdin** [comment]
I dont have, that is probbably genreted by the GA Module and thanks it works now
