### ISSUE TITLE
Web hooks for Fourms

### ISSUE THREAD

**Issue by Jasondia16** [NamelessMC/Nameless#1358]
**Please describe the feature in as much detail as possible**
When the Player Make a Fourm then the web hook detects it and send it to Discord

**Comment by samerton** [comment]
Just to clarify, are you referring to a topic within the forum, or a new forum created through the AdminCP?

**Comment by samerton** [comment]
I'll mark this as closed, in v2 it's possible to send new topics to Discord using a webhook.
