### ISSUE TITLE
Forums not updating

### ISSUE THREAD

**Issue by serrif** [NamelessMC/Nameless#1361]
**Describe the issue**
When creating a new discussion forum (or even a category) on my site, a category or forum isn't even updated. It shows it exits, but does not display on the forum page.

**To Reproduce**
Steps to reproduce the behaviour:

I don't know how to replicate this. 

**Expected behaviour**
Created forums to show up on the forum page. 

**Screenshots**
https://imgur.com/a/znhS4Gy

**NamelessMC version (from AdminCP -> Overview)** v2.

**Additional information**
I'm using the default Bootstrap theme.

**Comment by samerton** [comment]
Forums need to be set up as follows:

- You must have at least 1 category and at least 1 discussion forum
- Each discussion forum must have its "Parent Forum" option set as a category
- You must have given your groups permission to view the forums
