### ISSUE TITLE
Issues with sending emails

### ISSUE THREAD

**Issue by nathan93** [NamelessMC/Nameless#1363]
**Describe the issue**
I have set up the PHPMailer and when I go to send a test email nothing happens. The page just loads and loads and loads, but never sends me to the confirmation that the email was sent or not. And when I tested user registration when I clicked the register button, the page just kept loading and I never received a verification email. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on PHPMailer
2. Attempt to send test email, presented with page not loading
3. Try to register a new account, presented with page not loading
4. Try to submit email for forgot password, presented with page not loading. After about 3 minutes of buffering, error received "Unable to send forgot password email. Please contact an administrator."

**Expected behaviour**
For a test email to be sent and the page to load in a normal amount of time

**NamelessMC version (from AdminCP -> Overview)** 2.0.0-pr5

**Comment by samerton** [comment]
If the website is taking that long to return an error, it suggests the problem is with the SMTP address/port combination.

In case your SMTP host uses a non standard port, you can modify the port by editing the file **core/email.php**.

**Comment by nathan93** [comment]
Thank you, I got the issue resolved!

**Comment by samerton** [comment]
Glad it's fixed :)
