### ISSUE TITLE
Where to add additional badge colors

### ISSUE THREAD

**Issue by nathan93** [NamelessMC/Nameless#1365]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 2.0.0-pr5
* What theme are you using? Default

* Question: Where would I go to edit/add more class="badge" options/colors? I found the badge css in root/custom/panel_templates/Default/assets/css/adminlte.css but when I add my own variations, they don't work when I try to use them in the label maker. I want to add more variations because I want to have the badge colors match Minecraft's color codes.

**Comment by baxandrei** [comment]
You can use style="" or custom class and personalize it.

**Comment by nathan93** [comment]
Thank you guys for the help. Before making this ticket I did use the custom classes like you said, only I couldn't use it how I wanted because of the character length limit for the fields. Where would I go to change the length limit?

**Comment by samerton** [comment]
You'd have to increase the length of the `group_html` field in the nl2_groups table in the database (you can use a tool like phpMyAdmin for this), and then alter the validation in **modules/Core/pages/panel/groups.php** [here](https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/pages/panel/groups.php#L64) and [here](https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/pages/panel/groups.php#L188)

**Comment by samerton** [comment]
I'll mark this as closed, if you have any more questions please feel free to re-open.
