### ISSUE TITLE
Register bug/bad UX/feature request. v2

### ISSUE THREAD

**Issue by MarkiThePews** [NamelessMC/Nameless#1369]
**Describe the issue**
Error 1:Can't turn off the Minecraft username validation, tried to create account with Minecraft username: mmmmt and failed! (maybe bc it doesn't exists!)
~
Error 2: Getting redirect to home/portal page after register without notice of successful (also happen with login if you click register first and then login {after login it will redirect to history-1 which is register, and then the register script redirect to home/portal because you already logged in, pretty bad UX})

**To Reproduce**
Error 1: Go to register page and fill Minecraft username field with: "mmmmt"
~
Error 2: Just go register!

**Expected behaviour**
Error 1:Minecraft username not valid
~
Error 2: It will redirect you back to home(portal in my case) without any notice of successful and also doesn't log you in, making you (the user who register) confuse if they've done registering or not.

**NamelessMC version (from AdminCP -> Overview)**
Version 2.0.0 Pre-Release 5

**Additional Info**
Error 1 easy fix: Ability to turn off Minecraft name validation (currently I've manually turn it off by adding comments marks before the set var invalid_mcname = true)
Error 2 easy fix FOR LOGIN: Ability to set where to redirect after login/redirect to specified path IF history-1 is register.

**Comment by samerton** [comment]
Hi,

Issue 1:
You can disable the valid Minecraft username requirement in the StaffCP -> Minecraft -> Minecraft Account Verification tab, it's the "Force premium Minecraft accounts?" option.

Issue 2:
v2 doesn't actually use history-1 to redirect after logging in, the redirect to the register page is an error on my part. I've now added the register page as one to ignore for the post-login redirect in 790017da9871d3ead5fb882d14dc4f4d53b1072e

**Comment by MarkiThePews** [comment]
@samerton Ok, so I'm now using the lastest code and notice one issue: Guest user can bypass the rule "Can view other users' topics?" = false, since Guest user doesn't have option to turn it off...

**Comment by MarkiThePews** [comment]
@samerton Damn, was inside discord talking to you and writing a bug report, then Discord go offline (Major outage) as I press Send lol haha.
So I'm gonna post it here, found 2 issues:
Current setting
Minecraft integration ON
Custom nicknames ON

What happened
The register page shows:
Username
Minecraft Username
~> The Minecraft username is the one that will be use to login (login page: Username), and the Username is actually nickname, wrong Placeholder here.
~> The Username field doesn't even do anything, checked the register.php and both nickname and username all takes data from the same input: "username" (minecraft username field).
Line 213,233,261,269
=> $mcname = htmlspecialchars(Input::get('username'));
Line 373,374
=> 'username' => $mcname,
       'nickname' => htmlspecialchars(Input::get('username')),

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/91e461dc5c024913cd89eb408fb8f3fd230ac263 fixes the registration placeholder

https://github.com/NamelessMC/Nameless/commit/ded4bcb21af69c63ba283a6261c4733ee6c0a615 fixes the login placeholder

https://github.com/NamelessMC/Nameless/commit/a937c823b6fb3208a07ca573bbd64cfc9362de54 fixes nicknames not working during registration.

Thanks for spotting these!
