### ISSUE TITLE
Sync with pterodactyl

### ISSUE THREAD

**Issue by PixelNotFound** [NamelessMC/Nameless#1371]
It would be cool if https://pterodactyl.io/ gets synced with namelessmc, so when i log in on nameless mc with my account and i go to pterodactyl and i got permissions to use pterodactyl it will log me in automatically. And passwords and username changes will be synced too.

**Comment by Derkades** [comment]
I think that's pretty much impossible to do due to the way browsers treat cookies.

**Comment by PixelNotFound** [comment]
https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain

**Comment by samerton** [comment]
I'm afraid I don't see this being added on the Nameless side.

To be honest, the way I see it is this would be done on the panel side, since Nameless is the more "general" software. It makes more sense for a panel to hook into Nameless than the other way round.

**Comment by gtaunfairr** [comment]
you can easily fix this using the custom pages and make the button that redirects to your panel and just make the button only visible to staff members and just give them a pterodactyl account to logintoo.  ive done this myself it works no problems
