### ISSUE TITLE
Server Status Page always offline

### ISSUE THREAD

**Issue by ZeldaNerd123** [NamelessMC/Nameless#1372]
**Describe the issue**
My Minecraft server is online but on the status page, it says it's offline, locally the status page says its online. 

**To Reproduce**

- Under Interactions > Minecraft > Minecraft servers I added a new server using the IP.
- I made sure queries are enabled on my server properties files
- 
- Tried using external and internal queries

**Error:** Failed to connect or create a socket: 111 (Connection refused)

**Expected behaviour**
What were you expecting to happen?
To show the accurate server status, wether its offline or online (and amount of players online)
**Screenshots**
![Server Status](https://cdn.discordapp.com/attachments/247865182477484032/532756911095939077/unknown.png)

**NamelessMC version (from AdminCP -> Overview)**
Nameless V2

**Additional information**

**Comment by ZeldaNerd123** [comment]
Thank you for the quick reply. Is there a way to enable that in my host? I'm using Namecheap hosting.

**Comment by samerton** [comment]
Unfortunately I'm not sure if the option will be available, or if you'd have to contact the web host directly.

**Comment by samerton** [comment]
External query API changed in https://github.com/NamelessMC/Nameless/commit/19cf5eb0dc1c6fb56e8adb895bca1b0868f9dae4
