### ISSUE TITLE
change home image

### ISSUE THREAD

**Issue by Boostio90122** [NamelessMC/Nameless#1373]
How do I change this image on my home screen? https://imgur.com/a/YF5WRJs

**Comment by Derkades** [comment]
For v1: `https://github.com/NamelessMC/Nameless/tree/master/core/assets/img`
For v2: `/custom/templates/Default/img`

**Comment by Boostio90122** [comment]
> For v1: `https://github.com/NamelessMC/Nameless/tree/master/core/assets/img`
> For v2: `/custom/templates/Default/img`

Thanks!
