### ISSUE TITLE
Forum wont load properly

### ISSUE THREAD

**Issue by Boostio90122** [NamelessMC/Nameless#1374]
![capture](https://user-images.githubusercontent.com/39418539/51266263-ad11aa80-19b2-11e9-8a25-713723c11d55.PNG)
Forums won't load in after creation from admin cp or take a very long time and seem to disappear randomly
The attached file is what I see when on the forums 

Version: 2.0.0-pr5
Theme: Bootstrap Material 2.0.0-pr5

**Comment by samerton** [comment]
Hopefully [this comment](https://github.com/NamelessMC/Nameless/issues/1361#issuecomment-450129825) might provide some pointers.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any more questions please feel free to re-open.
