### ISSUE TITLE
Remove Title from front page

### ISSUE THREAD

**Issue by Boostio90122** [NamelessMC/Nameless#1375]
Just wondering if there is a way to remove the server name from the main page as the image background i use has the server name on it and i would like to remove the default name that's on the home page

**Comment by samerton** [comment]
Absolutely:

- in Nameless v1 you can remove [this line](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/index.tpl#L4) from **styles/templates/*template*/index.tpl**
- in Nameless v2 you can remove [this line](https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/index.tpl#L8) from **custom/templates/*template*/index.tpl.

Hope that helps :)

**Comment by samerton** [comment]
You can also remove the lines underneath the site name:
- v1: [these lines](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/index.tpl#L5-L6)
- v2: [these lines](https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/index.tpl#L10-L26)
