### ISSUE TITLE
[Error code 500] Template Page V2

### ISSUE THREAD

**Issue by alexvermaning0** [NamelessMC/Nameless#1376]
**Describe the issue**
when i go to the template Page in NMC Panel it juwst gives the error that the page doesen't work and on internet explorer it tell's you that i cant display the website.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Staff Dashboard'
2. Click on 'Layout > Templates'

**Expected behaviour**
to load the theme page normally and able to install my new theme

**Screenshots**
![image](https://user-images.githubusercontent.com/17603899/51566963-3f73eb80-1e96-11e9-95bd-736b3bf43496.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr5
**Additional information**
if i enable "Friendly URLs" the webiste stops working compleatly.

**Comment by samerton** [comment]
@alexvermaning0 Are you still experiencing issues with this?

**Comment by alexvermaning0** [comment]
thanks it worked. there where 3 i removed 2 and now it works
