### ISSUE TITLE
Notice: Undefined variable: label in /var/www/pages/forum/index.php on line 398

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [NamelessMC/Nameless#138]
I'm having a problem when visiting the forum tab.

http://5.196.125.132/forum/

`Notice: Undefined variable: label in /var/www/pages/forum/index.php on line 398`

edit:
```
Notice: Trying to get property of non-object in /var/www/pages/forum/index.php on line 322

Notice: Undefined variable: label in /var/www/pages/forum/index.php on line 398

Notice: Trying to get property of non-object in /var/www/pages/forum/index.php on line 419
```

**Comment by QUIQUELHAPPY** [comment]
Actually the whole forum is buggy.

![25236ea778774e789ff2532f33bb3524](https://cloud.githubusercontent.com/assets/12534357/13906409/b2663808-eed5-11e5-9df2-fb41d721f0a4.png)

I can reinstalls the website, install newer apache version or whatever until tomorrow, please, I need help.

The rest of the software looks amazing and works great ATM.

**Comment by samerton** [comment]
These issues seem to be coming about due to the template, not sure why.

If you head into the AdminCP -> Misc tab, can you check if "Enable error reporting" is checked? If so, unchecking it will suppress these errors.

**Comment by QUIQUELHAPPY** [comment]
It worked, thanks a lot by your help.
