### ISSUE TITLE
Error in code blocks

### ISSUE THREAD

**Issue by Dot-Rar** [NamelessMC/Nameless#1383]
**Describe the issue**
When you write a Java / Kotlin generic in a code tag, then a closing tag will be added at the bottom of the code as if it was a HTML tag. In addition to this, the class name in the tag is made lower case.

**To Reproduce**
Add a code block which makes use of <> (e.g. a Java generic)

**Expected behaviour**
No closing tag to be added

**Screenshots**
![untitled](https://user-images.githubusercontent.com/29165304/51804421-9d1e8400-2258-11e9-9266-32c8e238f6d2.png)

**NamelessMC version (from AdminCP -> Overview)**
1.0.21

**Additional information**
N/A

**Comment by samerton** [comment]
Unfortunately this is an HTML Purifier quirk, and as of yet I've not been able to find a way to fix it.

Code snippets in Nameless have been something that I've been stuck on for years now sadly, the only feasible way I can think of fixing them is to switch everything to BBCode or Markdown, which means losing some editor features sadly.

I'll close this one to merge with #1318, and then I'll try and gather some opinions in the other issue, and also in the Discord to see what people think the best approach is.
