### ISSUE TITLE
Special characters not displaying properly

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#1385]
Hello, someone tells me to not show these in the nickname (mcname) - Al% C3% A1sek - it should be (Alásek) How to fix it so it would not write these characters if it could not, on the profile instead of mcname displayed a username. thank you very much!! Photo: https://ctrlv.cz/iFde

**Comment by zikycz** [comment]
Please help?

**Comment by samerton** [comment]
Hi,

Unfortunately this is not supported in Nameless version 1, currently usernames will only display properly if there are no special characters.
