### ISSUE TITLE
Per-user themes

### ISSUE THREAD

**Issue by MarkiThePews** [NamelessMC/Nameless#1388]
From what I see in MySQL, there's a "theme_id" column for users (nl2_users), Just asking when will it be usable.
If you haven't started working on this, here's my suggestions:
+You don't need to make an actual other theme to release this, instead make a page that you could create new theme like:
https://namelessmc.com/uploads/images/1849/15c54503c4aec8_jhoenfqmlgipk.png

When pressing New Theme, there's gonna be a pop-up(prompt) to enter new theme's name, and what theme it will copy from, then it will copy everything of the choosen theme (if it's the default (stock) theme of the template then it will copy from "/custom/templates/%template_name/" dir (except the "/themes/" folder itself))
and create a new folder in "/themes/" like: "/custom/templates/%template_name%/themes/%new_theme_name%" and paste into it.
So then we can just use template editor to navigate into themes/ and edit the new theme, pretty neat!

**Comment by samerton** [comment]
Per user templates added in https://github.com/NamelessMC/Nameless/commit/8da6c5a7574adc178e3e74fab3bab4a86fffd0f3

Ability to duplicate + create new templates will be planned for a future update
