### ISSUE TITLE
The & char

### ISSUE THREAD

**Issue by mentimjojo** [NamelessMC/Nameless#139]
Hi guys,

When using an & char on the forum as a forum title/description it changes automatic to "&amp;amp;" and stays that way, so on the forum for uses it stands as "News &amp;amp; Announcements". I fixed it for now within the database by editing it Manuel, but it's not ideal.

Greetings.

**Comment by samerton** [comment]
Should be fixed in 71164789e27968fde9abc9d68c39479668b260ef
