### ISSUE TITLE
403 Forbidden cloudflare

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1393]
I enabled the option of Force HTTPS & WWW but now I get the error when trying to go to any page: 403 Forbidden cloudflare.

Is there anyway to fix this?

NamelessMC V2.0.0 preV5

**Comment by samerton** [comment]
Just to see which is causing the problem, can you delete the **cache/033f3da34ae9ec9661072ab0897ddf7ed642de3f.cache** to disable force HTTPS, and also **cache/a48fdb02e34b9602632d13dd91f0536d3b9bb559.cache** to disable force WWW?

**Comment by NPCtom** [comment]
Thanks for the response! I just waited and it went back to normal :)
