### ISSUE TITLE
Remove Ban Punishment from Punishments List

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1395]
Could you add the feature to permanently remove the record of a forum ban? I was using it for testing now it always shows in the punishments list.

**Comment by samerton** [comment]
Thanks for the suggestion, I've added it to #862 with some other moderation related enhancements.

For now, if you have database access, you can delete it manually from the **nl2_infractions** table.

I'll mark this as closed just so that #862 contains the moderation related features :)
