### ISSUE TITLE
Update EmojiOne to 4.5

### ISSUE THREAD

**Issue by Kore-Development** [NamelessMC/Nameless#1396]
**Please describe the feature in as much detail as possible**
Can the EmojiOne emojis be updated please? From what I know for PNG you can use [https://cdn.jsdelivr.net/gh/emojione/emojione-assets@4.5/png/64/1f600.png](https://cdn.jsdelivr.net/gh/emojione/emojione-assets@4.5/png/64/1f600.png) for
![](https://cdn.jsdelivr.net/gh/emojione/emojione-assets@4.5/png/64/1f600.png)

**Comment by Kore-Development** [comment]
The folder on Github is as [https://github.com/emojione/emojione-assets/tree/master/png/64](https://github.com/emojione/emojione-assets/tree/master/png/64)

**Comment by samerton** [comment]
Sadly, after some investigation, EmojiOne's license has become much more restrictive, and as a result we'll have to stick with 2.2.7.
