### ISSUE TITLE
Custom Page V2.0

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1398]
I tried setting up a custom page on NamelessMC V2.0 in the NavBar called 'Rules'. You can find it at [https://www.kraken-network.net/rules/](https://www.kraken-network.net/rules/) But when I click on Rules it redirects to a 404 Not Found error.

How do I fix this? And when will V2.0 be released fully??

**Comment by samerton** [comment]
With custom pages, you need to set the custom page permissions so everyone can view them. You can view the page permissions by editing it in the StaffCP.

I've responded to the v2 release question in #1397

**Comment by NPCtom** [comment]
Everyone has the "view" permission. I can't even access it.

**Comment by samerton** [comment]
Also make sure you don't have a folder named "rules" in your web root (ie public_html or htdocs) as it will conflict.

**Comment by NPCtom** [comment]
I don't

**Comment by samerton** [comment]
What is the value of the "Page path" option for the custom page?

**Comment by NPCtom** [comment]
Sorry I fixed it! Forgot the preceding /
