### ISSUE TITLE
Buy to remove NamelessMC branding

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1400]
Could this be an added feature?

**Comment by Derkades** [comment]
I believe the license already permits removing the branding in the footer, but please read it yourself IANAL. If you want to support the project in another way when the branding is removed, you can donate to samerton for his hard work

**Comment by NPCtom** [comment]
Thanks @Derkades For your reply. I will definitely contribute financially to this project as I think it is a great idea! How do you remove the branding in the footer?

**Comment by samerton** [comment]
Derkades is correct, the MIT license allows you to modify the software, which includes removing the branding in the footer. We do ask for a link back just to spread the word, but it's not necessary.

Branding can be removed in custom/templates/*template*/footer.tpl in v2: https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/footer.tpl#L63
