### ISSUE TITLE
Remove Minecraft Branding

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1403]
I love this forum software! I would like to use it in another project but is there a method to remove anything Minecraft related from it? Like remove the player avatars and username fields and Minecraft integration in the adminCP tab.

Could you make a think like that?

**Comment by samerton** [comment]
Currently you can try the following:
- Disable Minecraft integration in the StaffCP -> Integrations -> Minecraft tab
- Upload a new default avatar in the StaffCP -> Configuration -> Avatars tab

The next pre-release which should be ready in the near future has a fix for "Minecraft Username" still showing on the login/register pages, even with Minecraft integration disabled.

**Comment by TheMinecraftExplorer** [comment]
Hi, this still exists on dark theme, Pleae help

**Comment by Aberdeener** [comment]
Hi, can you join our Discord @ https://discord.gg/nameless?
We can give you better support there! Just let us know you commented on this issue and we can help out. Thanks!

**Comment by TheMinecraftExplorer** [comment]
I don't know why it says I am banned? Could you check? My username is TIM#7107

**Comment by Aberdeener** [comment]
Whats your Discord user ID? :)

**Comment by TheMinecraftExplorer** [comment]
707549304382029845 is my Discord ID

________________________________

**Comment by TheMinecraftExplorer** [comment]
707549304382029845 is my Discord ID

**Comment by Aberdeener** [comment]
Alright, I've unbanned you 🙂

**Comment by TheMinecraftExplorer** [comment]
Still says I am banned. You sure you have unbanned the correct guy? User ID: 707549304382029845
