### ISSUE TITLE
V2 Discord Webhooks Not Working

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1404]
Discord Webhooks do not work.

Version 2

**Comment by PixelNotFound** [comment]
More details please

**Comment by NPCtom** [comment]
@PixelNotFound When I create a post or topic there is no notification in my Discord.

**Comment by samerton** [comment]
The current process for setting up Discord webhooks is as follows:
- Fill out your Discord hook settings, and select events for them to execute on, in the StaffCP -> Configuration -> Social Media tab
- Edit your forums in the StaffCP -> Forums tab, and enable the "Include new topics from this forum in the webhook?" option for any forums you want to show new topics from.

**Comment by NPCtom** [comment]
OK thanks now it works.

Could be some more documentation. Maybe a little '?' that goes to a wiki page?
