### ISSUE TITLE
[V2] Profile "Last seen" incorrect when the user is never online.

### ISSUE THREAD

**Issue by yangyang200** [NamelessMC/Nameless#1411]
**Describe the issue**
A new player registered via /register on the server, and then completed registering. After that, he isn't any more online, when looking at his profile, "over 49 years" last seen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Do /register on the server.
2. Open the link. Continue registration.
3. Once completed, immediately close the browser window.
4. Visit user profile, see the error of "49 years".

**Expected behaviour**
Expecting it to have the registration time of the player.

**Screenshots**
![issue](https://user-images.githubusercontent.com/32196824/53693214-546a6580-3dd8-11e9-9e5a-dd47f53dadc6.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0 Pre-Release 5 

**Additional information**
------

**Comment by samerton** [comment]
Should be fixed in https://github.com/NamelessMC/Nameless/commit/9fd21dde7ea448f9d3f5de5678d1deb821725d92
