### ISSUE TITLE
Support pluraforms for translaters

### ISSUE THREAD

**Issue by kobel169** [NamelessMC/Nameless#1419]
Hi, sorry for my english.

I trying make translate to russian language, and have trouble with plural forms needs to native language seeing.

Example:
1 day => 1 день
2 days => 2 дня
5 days => 5 дней

language file supports only forms for 1 and 2 numerics. 

Can you make the language support  like as look in this document: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms
Or can you add workaround documentation for this case? 

 
@baxandrei may be you also need for this support in #1342 because Romanian also have difference pluraforms

**Comment by samerton** [comment]
Unfortunately this is going to be a tricky one, I'll have to think of the best way of supporting this. 

I'm thinking adding support for a custom plural function in language files.

**Comment by samerton** [comment]
@kobel169 

Does this look like it could work for the Russian translation?
https://gist.github.com/fomigo/2382775

**Comment by kobel169** [comment]
@samerton Yes, this function take needed result. 

example:
```PHP
<?php

function plural_form($n, $forms) {
  return $n%10==1&&$n%100!=11?$forms[0]:($n%10>=2&&$n%10<=4&&($n%100<10||$n%100>=20)?$forms[1]:$forms[2]);
}

echo "1 ".plural_form(1, array('день', 'дня', 'дней'))."\n";
echo "2 ".plural_form(2, array('день', 'дня', 'дней'))."\n";
echo "5 ".plural_form(5, array('день', 'дня', 'дней'))."\n";
echo "42 ".plural_form(42, array('день', 'дня', 'дней'))."\n";

?>
```
Result:
```
$ php 1.php
1 день
2 дня
5 дней
42 дня
```

All resulted forms corrected.

**Comment by samerton** [comment]
Great, thanks for testing that.

Can you add the following code to the end of your language file's `version.php`:
```php
// Plural function
function pluralForm($n, $forms){
	return $n%10==1&&$n%100!=11?$forms[0]:($n%10>=2&&$n%10<=4&&($n%100<10||$n%100>=20)?$forms[1]:$forms[2]);
}
```

Then, if you use the latest code (as of commit f80da7fef4b0f83b07ba1945c19abfeb9af59dbc), you can then specify your (plural only) language variables like this:
```php
'_days' => array('{x} день', '{x} дня', '{x} дней'),
```

Even though the form for 1 day ago won't actually be used since there is already a `1_day` language entry, for now it'll be necessary to supply it as the first array element just so the function works properly.

**Comment by kobel169** [comment]
@samerton i check and it not fully works. Check commit https://github.com/immapltd/Nameless/commit/5a04cd5152cce43d9df04c4f139c4bee57d730f9 for see expected vision of configfile and see next forum post with this commit state http://play.mymc.su:8080/forum/topic/1--/#post-1

Current version not replacing {x} , another behavior works correct

**Comment by samerton** [comment]
I've just applied a fix for this in this commit: 485b8ba4dce3d9d3f29d6ac6db796c546741a952

The time.php language file should look like this:
```php
	'time' => 'time', // Placeholder, no need to translate
	'seconds_short' => 'c', // Shortened "seconds", eg "s"
	'less_than_a_minute' => 'Меньше минуты назад',
	'1_minute' => '1 минуту назад',
	'_minutes' => array('{x} минуту назад','{x} минуты назад','{x} минут назад'),
	'about_1_hour' => 'Около часа назад',
	'_hours' => array('{x} час назад','{x} часа назад','{x} часов назад'),
	'1_day' => '1 день назад',
	'_days' => array('{x} день назад', '{x} дня назад', '{x} дней назад'),
	'about_1_month' => 'Около месяца назад',
	'_months' => array('{x} месяц назад', '{x} месяца назад', '{x} месяцев назад'),
	'about_1_year' => 'Около года назад',
	'_over_x_years' => array('Более {x} года назад', 'Более {x} лет назад', 'Более {x} лет назад')
```
(apologies if I've copied some of the phrases wrong)

**Comment by kobel169** [comment]
Ohhh, okay, Yes, you edits correct. i edit time.php by you recommendation and update v2 branch from you upstream. All seems okay.

**Comment by samerton** [comment]
Closing as hopefully resolved by previously mentioned commit.
