### ISSUE TITLE
[v2] Register Page - "Invalid Token" (Chrome)

### ISSUE THREAD

**Issue by kuchkuch2000** [NamelessMC/Nameless#1436]
**Describe the issue**
A player on one of my client's server is having an issue whilst attempting to register using chrome. I told him to try and delete his cache/cookies but the issue persists. I'm not able to reproduce his issue nor do I know why he's having it.

**Expected behaviour**
User to register successfully

**Screenshots**
Gif of the issue here:
https://gyazo.com/45be019906655d9692ae5cff947c7369

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pre5

**Additional information**
As far as I know, it's only happening to this one user

**Comment by samerton** [comment]
You should be able to update to pre-release 6 which should resolve this issue :)

**Comment by samerton** [comment]
Just to add, if you don't want to upgrade yet due to customisations you may have, you can try the following:

- edit the files **modules/Core/pages/login.php** and **modules/Core/pages/register.php** in a text editor
- replace all instances of `Token::generate()` with `Token::get()`

**Comment by kuchkuch2000** [comment]
Yeah I did try the update to pre6 but the theme broke and I really didn't have the patience to go through fixing that again. Thanks for the alternative to it. I asked the user to try and register again so I'll get back to you once he has tried.

**Comment by kuchkuch2000** [comment]
Issue resolved. Thanks for the help!
