### ISSUE TITLE
Forum edit not working

### ISSUE THREAD

**Issue by kuba2003tv** [NamelessMC/Nameless#1446]
Hello, i have bug... on click "Edit" to forum post, i'm not see text (post), what I saw before clicking "edit", field is clear. Sorry my english is very bad.

**Comment by samerton** [comment]
If you're using version 2 pre-release 6, only the Default and DefaultRevamp templates will work for now. You'll have to wait for other templates to be updated to pre-release 6 to fix the issue if you're using something else.

**Comment by kuba2003tv** [comment]
Yes, im using 2-pre6, thanks for advice 👍

**Comment by samerton** [comment]
No problem, I'll mark this issue as resolved :)
