### ISSUE TITLE
Icon Bug (Small issue)

### ISSUE THREAD

**Issue by MCEpicNation** [NamelessMC/Nameless#1452]
**Describe the issue**
Please describe the issue in as much detail as possible:
It's just that icons seems to attach to the words on the nav bar.

**Screenshots**
http://prntscr.com/mxu8m9

**NamelessMC version (from AdminCP -> Overview)**
2-Pre6

**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
Hi,

You'll need to update the icons in the StaffCP -> Configuration -> Navigation tab to Semantic UI equivalents for that template (from these docs).

Example for home:
```
<i class="home icon"></i>
```

**Comment by MCEpicNation** [comment]
Oh. okay thanks
