### ISSUE TITLE
Website won't load!

### ISSUE THREAD

**Issue by Zacky26** [NamelessMC/Nameless#1454]
**Describe the issue**
So I turned force https:// and www. and it turns out that my website won't load now please help me:
www.slimeskies.ga
Btw I have a www. using cloudflare and a certificate yoo

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'panel'
2. Change the https and www options to true

**Expected behaviour**
What were you expecting to happen?
It works fine
**Screenshots**
Just check it at www.slimeskies.ga
**NamelessMC version (from AdminCP -> Overview)**
Can't but its latest nameless 2
**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
To disable force HTTPS, delete the file `cache/033f3da34ae9ec9661072ab0897ddf7ed642de3f.cache`

To disable force WWW, delete the file `cache/a48fdb02e34b9602632d13dd91f0536d3b9bb559.cache`

**Comment by Zacky26** [comment]
Okay thanks :)

**Comment by samerton** [comment]
No problem, I’ll go ahead and close the issue; if you have any more issues please feel free to re open :)
