### ISSUE TITLE
Server status not loading on mobile.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1455]
http://prntscr.com/mz3fvi

**Comment by samerton** [comment]
Which mobile device are you using?

**Comment by baxandrei** [comment]
Samsung Galaxy A8 2018

**Comment by BaxAndrei-SEC-ACC** [comment]
Problem solved, thanx.
 ```Access to XMLHttpRequest at 'http://www.hartex.tk/queries/server/?id=1' from origin 'http://hartex.tk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Comment by samerton** [comment]
This is an issue with the default revamp template that I’m looking into fixing currently.

**Comment by baxandrei** [comment]
This is my fault, not an template error.
Defined website url is http://www.hartex.tk and I am accesing website from http://hartex.tk

**Comment by samerton** [comment]
Changed in https://github.com/NamelessMC/Nameless/commit/fc8870d88a8b1eda784d716318b776e2c87205af to use relative paths instead of full URLs
