### ISSUE TITLE
ACP hangs up on "updateLanguages" task

### ISSUE THREAD

**Issue by alsoGAMER** [NamelessMC/Nameless#1466]
**Describe the issue**
I created a custom language, but after selecting it and pressing the button to update the languages ​​to all users, nameless stopped working and all pages are loaded empty

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the ACP
2. Select a custom language
3. Press "update to all user" button

**Screenshots**
![image](https://user-images.githubusercontent.com/35269770/54870029-894b5600-4da1-11e9-8063-42f3c8f10577.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0 pr-6

**Comment by samerton** [comment]
This suggests there's an issue with the custom language; can you ensure there are no PHP syntax errors in your files? There are syntax checkers online that you can paste your language files into to do this for you.

**Comment by alsoGAMER** [comment]
Thanks for your reply, i've fixed the files and now all works again.
But i would report to you that the user.php file return: "PHP Warning:  Use of undefined constant SITE_NAME - assumed 'SITE_NAME' (this will throw an Error in a future version of PHP) in /home/me/Desktop/Italian/user.php on line 238" on the syntax check, and also i could not translate the forum, labels and topic areas due to the lack of strings in the original file (EnglishUS)

**Comment by samerton** [comment]
Thanks for the translation! 

It should be safe to ignore the SITE_NAME message; by the time the webhook is sent out to Discord the constant should definitely be set.

As for forum translations, you can find them in **modules/Forum/language** :)
