### ISSUE TITLE
Error when changing things on Core -> General Settings

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#147]
When we click om submit om Core on General Settings we get gray page... Not the whole page but the   General Settings options not loading we need to reload the page to get them bk

Warning: Cannot modify header information - headers already sent by (output started at /var/www/cubedcraft.org/public/core/includes/smarty/sysplugins/smarty_internal_template.php:306) in /var/www/cubedcraft.org/public/core/classes/Redirect.php on line 14

**Comment by samerton** [comment]
This is to do with the redirection class which I'm phasing out.
Fixed in 158a6b74f5207c3b981f416b81b23ca257a3109f
