### ISSUE TITLE
Translate bug with alerts

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#148]
When we using other languages that have translated this
'tagged_in_post' => 'You have been tagged in a post',
If its not stand "You have been tagged in a post" we get this bug http://imgur.com/rAsZsX3 

Languages who have this problem:
German
Norsk
Slovak
Spanish
Dutch

Because we have translated "You have been tagged in a post" The rest of the languages working since them is not translated them use "You have been tagged in a post"

I have not tested Finnish but i see its translated too

**Edit:**
The issuse coming because i got the tag when i used EnglishUK The issuse start if i change language
But when i tested with a new tag with feks Norsk its working but we missing "Click here to view"

**Comment by samerton** [comment]
I've reproduced the issue, I'll take a look now.

**Comment by samerton** [comment]
Should be fixed in the next commit.
It's worth noting that it won't fix existing issues, but will prevent this from happening again.
