### ISSUE TITLE
2FA Broken With  v2 Pre6

### ISSUE THREAD

**Issue by RSL2003** [NamelessMC/Nameless#1480]
**Describe the issue**
As i attempt to use 2fa on my site it fails saying to use the code in the app. I attempted to use 3 diffrent Auth apps including
Microsoft Authenticator
Google Authenticator
and Eset Authentication
All produce a code but the website refuses to accept them.
Note that this was done on an android 9 device. Unsure if that matters
If this is not possible to fix, is there a way to hide the options from the users of my site.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Profile settings
2.  enable 2FA
3. Scan QR code in a 2FA app
4. Enter Code
**Expected behaviour**
I guess for 2fa to work
**Screenshots**
![image](https://user-images.githubusercontent.com/39892040/55373056-4fcdc580-54da-11e9-943b-d079bb2c038c.png)

**NamelessMC version**
2.0.0-pr6

**Comment by Derkades** [comment]
Did other users try this? Did you try it on other phones? Did you set the time manually or is it set automatically on your server and phone? (even a minor difference in time will stop 2FA from working)

**Comment by samerton** [comment]
As Derkades says, you need to make sure your web server clock is exactly up to date (assuming that your device also has the correct time).

**Comment by Derkades** [comment]
@samerton Does NamelessMC allow for a slight time difference? It is common for websites to allow a previous and future code. It doesn't decrease security very much and helps in situations where the time is set manually and is slightly off

**Comment by RSL2003** [comment]
From what I know the clock is set automatically. Would there be any to check if so. The server I am using for the website is only CPanel web hosting not a dedicated server.

**Comment by samerton** [comment]
Can you send me a link to your website so I can try myself?

**Comment by RSL2003** [comment]
Sure. It's https://venomcraft.win

**Comment by samerton** [comment]
Thanks, I've had a look and I'm getting the same issue. This suggests the problem lies with the custom template or web host. 

Could you have a quick test with the Defualt template?

**Comment by Derkades** [comment]
To test if the webserver time is wrong, you can create a `test.php` file in the root directory and put this in the file:
```
<?php
echo time();
?>
```
Then go to https://venomcraft.win/test.php . The number on the page should match the number displayed here: https://time.is/Unix_time_now

**Comment by RSL2003** [comment]
Will have to do it when I'm done work. Will post here when done

**Comment by RSL2003** [comment]
Yes it is an issue with the theme. Sorry for the waste of time. I'll send a msg to the author of it. Thank you for telling me that.

**Comment by SoNotMC** [comment]
I have this same issue all these years later. Exact same error even when the code is correct. And what makes it worse is that I made 2fa a requirement for the Admin group so I am now locked out completely.
