### ISSUE TITLE
Group not getting assigned

### ISSUE THREAD

**Issue by hypertjs** [NamelessMC/Nameless#1481]
When a new user registers and verifies their account, they are not assigned a group.
On my site, I have a "Member" role. When users register, they do not get assigned this role and are stuck without a role. I have to manually assign it.

It is set correctly in the settings.
I am currently on the latest, 2.0.0-pr6.

These are the settings I currently have.
![1](https://rainbow.pizza/fHAvpv.png)
![2](https://rainbow.pizza/dVzee9.png)

**Comment by baxandrei** [comment]
http://prntscr.com/n69aup

http://prntscr.com/n69b13

**Comment by samerton** [comment]
Just to confirm this is what *should* happen:

1. User registers on your site and is added to the default group for new users
2. User must then validate their email by clicking on the link sent via email
3. User should then be promoted to "Member" as this is the post validation group

**Comment by hypertjs** [comment]
Yes, this is what should happen.
Now I am getting this error when you register:
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'group_id' cannot be null`

**Comment by samerton** [comment]
Can you edit your default group and simply click Submit again so it can re-set the cache?

**Comment by hypertjs** [comment]
Thank you!  That has seemed to fix the issue.

Also, users' groups are now getting assigned correctly. Before a user verifies, they are set to be "Unconfirmed." After verifying, they now are promoted to "Member!"

Not sure why it didn't work prior to this issue.

**Comment by samerton** [comment]
Great, glad everything is working! :)

**Comment by sTiKyt** [comment]
Had same error as well, got it fixed, thanks
