### ISSUE TITLE
Missing reCAPTCHA form on contact page

### ISSUE THREAD

**Issue by hypertjs** [NamelessMC/Nameless#1482]
When you try to submit a message on the contact page, all you get is "Invalid reCAPTCHA response." However, the reCAPTCHA seems to be missing.

**To Reproduce**
1. Go to contact page
2. Fill out information
3. Submit message

I am currently on the latest, 2.0.0-pr6.

![1](https://rainbow.pizza/e3VMxa.png)

**Comment by samerton** [comment]
Thanks, fixed in 2c57df76166a7932811ec79ffe3bf9ebaf3719da
