### ISSUE TITLE
Contact message doesn't include email

### ISSUE THREAD

**Issue by hypertjs** [NamelessMC/Nameless#1483]
When someone sends a message via the contact page, it only sends the message and doesn't include the email the user inputs.

![1](https://rainbow.pizza/Rga4dp.png)
![2](https://rainbow.pizza/uoGljE.png)

**Expected behavior**
The email the user enters should be sent with the email. Otherwise, we can't contact them.

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr6

**Comment by baxandrei** [comment]
If you tap by name, does the address appear?

**Comment by hypertjs** [comment]
No, it shows the email I set as the contact email.

**Comment by baxandrei** [comment]
For me it works.
http://prntscr.com/n7yvr0

**Comment by hypertjs** [comment]
Oh I didn't see that it puts it there, my bad.

I just tested it, it works.
