### ISSUE TITLE
PlaceholderAPI placeholders

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1484]
The plugin now sends PlaceholderAPI placeholders to the website. These placeholders can be used by the website in a lot of different ways, some of my ideas include:

- [ ] Allow users to use the placeholders in any text area, such as
- - [ ] Signatures
- - [ ] Custom pages
- - [x] Posts / replies
- [x] Add an option to display a placeholder on a user's profile, next to post count and likes.
- [x] Leaderboard addon

TODO:
- [x] Save placeholders in a table
- [x] Easy "api" methods to get this data for modules (and nameless itself)

**Comment by TwerkRekt** [comment]
how its work?

**Comment by Derkades** [comment]
> how its work?
This feature has not been implemented yet

**Comment by Aberdeener** [comment]
![image](https://user-images.githubusercontent.com/26070412/117590183-f1c13280-b0e2-11eb-8ed9-1ec9b09daa38.png)
Rough idea of how it will look on the user facing settings page
