### ISSUE TITLE
Config unavailable.

### ISSUE THREAD

**Issue by Ondra3211** [NamelessMC/Nameless#1485]
https://i.zerocz.eu/ja/HFT3ijDPno.png

When I try to install namelseemc:
`Config unavailable.`
In datase is nothing created

Version 2.0.0 pre-release 6
nginx/1.14.1
PHP 7.3.3

**Comment by samerton** [comment]
Hi,

Simply refreshing the page with F5 should fix it.

**Comment by Ondra3211** [comment]
https://mc.zerocz.eu/
So clean

**Comment by samerton** [comment]
More content will start to appear on your home page as you start to configure + use the site; news will show when you create topics in a news forum (one which has the option "Display topics as news on front page" enabled), and widgets/social media can show there too.

As for friendly URLs, you need to make sure your `location` block for your Nameless nginx configuration has the try files line from the [example nginx config](https://raw.githubusercontent.com/NamelessMC/Nameless/v2/nginx.example).

**Comment by samerton** [comment]
Were you able to resolve the nginx issue @Ondra3211?

**Comment by Ondra3211** [comment]
Friend urls now works fine.

How can I add post to website and display the post on index page.
What is this? https://i.zerocz.eu/ja/RFUOxc6LVG.png

**Comment by samerton** [comment]
To create posts, you first need to create a forum in the StaffCP -> Forums tab. You must create at least one category and one forum; the forum should have its "Parent Forum" option set as a category.
Then you can create topics and posts in the forum.

Any posts on the index page come from a forum that has the "Display topics as news on front page" option enabled.

As for the box on the homepage, that will show if you have Minecraft integration enabled (StaffCP -> Integrations) but you haven't set a default Minecraft server (StaffCP -> Integrations -> Minecraft -> Servers); the box will then show a server status.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any more questions please feel free to re-open :)
