### ISSUE TITLE
Error on forums

### ISSUE THREAD

**Issue by Rastrian** [NamelessMC/Nameless#1486]
Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ORDER BY topics.topic_reply_date DESC LIMIT 50
	        ) UNION ALL (
	       ' at line 2 in /var/www/html/core/classes/DB.php:51
Stack trace:
#0 /var/www/html/core/classes/DB.php(51): PDOStatement->execute()
#1 /var/www/html/modules/Forum/classes/Forum.php(235): DB->query('(\n\t        SELE...', Array, 2)
#2 /var/www/html/modules/Forum/pages/forum/index.php(71): Forum->getLatestDiscussions('2', Array, '1')
#3 /var/www/html/index.php(84): require('/var/www/html/m...')
#4 {main}
  thrown

**Comment by samerton** [comment]
Hi,

In Nameless v2 you need to have permission to view forum and view other users' topics in at least 1 forum. You can configure permissions in the StaffCP -> Forums tab.

**Comment by Rastrian** [comment]
> Hi,
> 
> In Nameless v2 you need to have permission to view forum and view other users' topics in at least 1 forum. You can configure permissions in the StaffCP -> Forums tab.

Already has been configured, but still doesnt work.

**Comment by samerton** [comment]
Forum permissions are the only (known) cause of this issue.

If it's okay with you, would I be able to sign up on your site and check out the StaffCP?

**Comment by Rastrian** [comment]
> Forum permissions are the only (known) cause of this issue.
> 
> If it's okay with you, would I be able to sign up on your site and check out the StaffCP?

![image](https://user-images.githubusercontent.com/10719452/56076065-9f49a680-5da2-11e9-9993-dd8c40705fd6.png)

**Comment by Rastrian** [comment]
but still doesnt work, same error, i already had tried recreate multiple times.

**Comment by samerton** [comment]
Thanks, note the "Pode ver os topicos de outros usarios" option is disabled too; this permission must be enabled for at least one forum.

**Comment by Rastrian** [comment]
Now works, thanks.

**Comment by samerton** [comment]
No problem :) Hopefully this will be improved in the near future.
