### ISSUE TITLE
SQL injection resistance

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#149]
well people could SQL inject it, & break stuffs so if you could, make a version w/ ruby on rails authentication?

**Comment by samerton** [comment]
I'm not too knowledgeable with Ruby on Rails, I'd like to keep this strictly PHP based.

You mention people could use SQL Injections, are you aware of any ways to do this at the moment? 
As far as I know from the testing I've performed, this isn't possible at the moment, however it's always best to keep an eye out on any potential issues which may come about.

**Comment by Fiiily** [comment]
I've extensively attempted to use XSS and SQL injection to break the site and everything seems solid.s

**Comment by samerton** [comment]
I'm going to go ahead and close this issue, rewriting based on Ruby on Rails is something that likely won't happen.
Thanks for testing @Fiiily
