### ISSUE TITLE
How to set SMTP

### ISSUE THREAD

**Issue by yamagami2211** [NamelessMC/Nameless#1491]
[Nameless Forum Topic](https://namelessmc.com/forum/topic/668-how-to-set-smtp/)

I use Google Translate.

I want to use sendgrid's SMTP, but I can not configure it properly.

The sendgrid username is "apikey" and does not contain a domain after it.

(For example, "apikey@domain")

If you put apikey in place of the user name and execute the send test, you will get "Invalid address: (setFrom) apikey".

Also, referring to "[here](https://namelessmc.com/forum/topic/topic/594-smtp-phpmailer-issues/)", I rewritten Emain.php, but it did not work well.

How can I set it?

**Version 2.0.0 pre-release 6**

**Comment by samerton** [comment]
Can you try the following:

- Edit [this line](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Email.php#L67) within **core/classes/Email.php**
- Change `$GLOBALS['email']['username']` to your API key like so: `$mail->Username = 'API_KEY';`

Then your username in the StaffCP -> Configuration -> Emails tab should be your email address.

**Comment by yamagami2211** [comment]
I use Google Translate.

It did not solve.

apikey will be your username.

So, the form is filled out as follows.  
Username: apikey  
Password: [generated apikey password]  

I changed it a lot, but the error message did not change.
"Invalid address: (setFrom) apikey"

Also, the email address of the administrator (Owner) and the email address to be sent were the same, but they did not change.

It is the same as the Configuration-> Emails email address and the Configuration-> General settings email address.

**Comment by yamagami2211** [comment]
[Integrating with the SMTP API](https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/)SendgridDocs

The document of the Japanese agency which translated this is set as a reference.

**Comment by samerton** [comment]
Okay, in that case:

- Edit [this line](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Email.php#L67) within core/classes/Email.php
- Change $GLOBALS['email']['username'] to your API key like so: $mail->Username = 'apikey';

Your username in the StaffCP -> Configuration -> Emails tab **must** be your email address, and **not** `apikey`. Then your password can be the API key.

**Comment by yamagami2211** [comment]
solved!

I will leave a solution for somebody in the future.

- Rewrite "[here](https://github.com/NamelessMC/Nameless/issues/1491#issuecomment-488022298)" as a reference
- Go to "StaffCP-> Configuration-> Emails" and make the username an email address to send.
(For example, if the email address to be sent is "admin@ nameless-mail-test.com", enter "admin@ nameless-mail-test.com" as the outgoing email address and user name.

This solved me.

Thank you.
