### ISSUE TITLE
Problem please help theme

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#1493]
Hello I have a problem, I want to install a template on the web, but when I click on (Layout / theme), I see this how to fix it? Photo: https://ctrlv.cz/bQLY

**Comment by zikycz** [comment]
Fatal error: require_once(): Failed opening required '/data/web/virtuals/188948/virtual/www/domains/marwland.cz/modules/Nextyle/pages/getvariables.php' (include_path='.:/data/web/virtuals/188948/virtual') in /data/web/virtuals/188948/virtual/www/domains/marwland.cz/custom/templates/DefaultRevamp/template.php on line 12

**Comment by samerton** [comment]
Nextyle has both a template *and* a module; you need to make sure the Nextyle module has also been uploaded to the **modules** folder on your website.
