### ISSUE TITLE
{$API_URL_VALUE} Not being updated with force www, causing problems in the plugin config.

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1498]
**Describe the issue**
Please describe the issue in as much detail as possible

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable force www via StaffCP
2. Go to the API page in the StaffCP
3. The API link has not been updated with the www prefix

**Expected behaviour**
I thought that the www would be added as this can cause problems with the plugin. back in February Sam helped me via Discord to figure this out, but I thought a bug report would help too.

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr6

**More info**
I am assuming the solution to this problem would lie around line 92 on this page; https://github.com/NamelessMC/Nameless/blob/v2/custom/panel_templates/Default/core/api.tpl

**Comment by samerton** [comment]
Should be fixed in ce392f6065fc66b225397771e6fcb2b15b94bf77
