### ISSUE TITLE
Private Messages are not contiguous

### ISSUE THREAD

**Issue by Samistine** [NamelessMC/Nameless#15]
Replying to a private message creates a new conversation making it hard to understand and producing a bunch of unneeded separated pm's.

**Comment by samerton** [comment]
The private messages module is similar to those found in other open source forum software packages, however I can create more of a XenForo/IPB conversation style system in a future release.

**Comment by Samistine** [comment]
Nothing fancy needed, just something basic to keep a single conversation in
one place.
Like most messaging app ;p

I also noticed when you get a new message it notifies you, but doesn't
point to which comversation it is, assuming you have multiple previous
conversations.
