### ISSUE TITLE
Using lighttpd, so cant use .htaccess

### ISSUE THREAD

**Issue by TheDiamondYT1** [NamelessMC/Nameless#150]
Please add support for other web servers. So in config file add an option to enable file exstensions, so /forum would be /forum/index.php or /forum.php

**Comment by samerton** [comment]
In my initial 2.0 dev builds I have added an option to disable the use of .htaccess files, however this is quite a way off completion.

There is a guide on migrating from Apache's .htaccess rewrite rules to lighttpd [here](http://redmine.lighttpd.net/projects/1/wiki/MigratingFromApache#mod_rewrite), however it's not something I've ever used before.

**Comment by samerton** [comment]
I'll mark this as closed, as version 2.0 (currently in development stages) does not have friendly URLs enabled by default.
