### ISSUE TITLE
Adsense code where i need to paste this code?

### ISSUE THREAD

**Issue by Prowco** [NamelessMC/Nameless#1500]
### Template:
*** What kind of issue is it (Question, Bug, etc.)?**
Question

*** In which version of NamelessMC did it occur (1.x.x)?**
2.0

*** How would you describe the issue?**
Hi i have a code i receive in my google adsense website it says:

**Remember, place the code on every page you want ads.
Click “Show code” if you need to copy and paste the code again.
Paste it into the HTML of http://mcrp.ml, between the <head> and </head> tags**

The point is i dont know where i need to paste the code i have bc i try in so many pages but adsense cant found the code some help please?

* Do you have an idea how or where the issue occurs?
--
* What Modules are you using ?
Minebox
* What theme are you using ?
Minebox

**Comment by samerton** [comment]
According to https://namelessmc.com/resources/resource/30-minebox-template-for-v200-pr6-/ Minebox already has Adsense integration; try looking in the Minebox settings in your StaffCP to see if there's somewhere to configure it.

If not, try adding the Adsense <script> to `custom/templates/*template*/header.tpl` before the `</head>`.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any more questions please feel free to re-open.
