### ISSUE TITLE
Website name in StaffCP - Go back to website instead of to /panel

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1504]
Or remove it and put "View Site" in its position

![image](https://user-images.githubusercontent.com/15892014/58121645-31499800-7c08-11e9-926e-9c7e907779d0.png)

**Comment by samerton** [comment]
Might have to open a poll for this one, personally I think the main link when navigating the panel should take you back to the panel index, which is common practice for most website software I've used.

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/58838166-3a9e2000-865e-11e9-8713-ffdf879825cc.png)
