### ISSUE TITLE
Add margin between button and text

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1505]
Add padding between button and text (or alternatively, move them to the right #1503 ) 
![image](https://user-images.githubusercontent.com/15892014/58121957-dd8b7e80-7c08-11e9-8ee7-f409e302aed9.png)
![image](https://user-images.githubusercontent.com/15892014/58122004-f72cc600-7c08-11e9-8a16-57953a88fcac.png)

**Comment by samerton** [comment]
Not sure moving all to the right is the best approach, on wide screens it might be hard to tell which switch is for which label:
<img width="1668" alt="Screenshot 2019-06-23 at 15 06 51" src="https://user-images.githubusercontent.com/1812544/59977411-9ce8a180-95c8-11e9-95dc-1b91ac20c60f.png">

**Comment by Derkades** [comment]
Ideally they would be as far left as possible, but while still being perfectly aligned

**Comment by Derkades** [comment]
Fixed a while ago in https://github.com/NamelessMC/Nameless/commit/da99290d155b0b1358736d4025986ba1eecc5aee
