### ISSUE TITLE
Terms and conditions text missing, and can't register even when checked

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1506]
This only happens when using the plugin to register, registering through the website works fine.

![image](https://user-images.githubusercontent.com/15892014/58122285-8fc34600-7c09-11e9-9ab7-4682e09a449b.png)

In the standard form:
![image](https://user-images.githubusercontent.com/15892014/58122408-dfa20d00-7c09-11e9-9582-c56303038015.png)

**Comment by samerton** [comment]
Should have been fixed in https://github.com/NamelessMC/Nameless/commit/f16badb89143c30e49f4be31438558ee1b9059ae

**Comment by Derkades** [comment]
Does that also explain that the website thinks that the box is unchecked even when it is checked? When checked, it will still say "please accept terms and conditions to continue"

**Comment by samerton** [comment]
Yep exactly, the input name doesn't match what the validation is looking for.
