### ISSUE TITLE
Outdated terms of service

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1507]
The terms of service says the following:
> Cookies are used to store small pieces of non-identifiable information with your consent. In order to consent to the use of cookies, you must either close the cookie notice (as explained within the notice) or register on our website.

Recently, the cookie message was changed to auto close after a certain time, so it's not valid to say that the user has accepted the use of cookies by dismissing the notice.

**Comment by robinriezebos** [comment]
yes i also think this yes. yes.

**Comment by samerton** [comment]
Personally I think stating `you must close the cookie notice` is sufficient as to me it's clear this is something I must do; not sure what the alternative wording could be.

**Comment by Derkades** [comment]
> this is something I must do

False, the cookie notice is dismissed after a few seconds even without user input

**Comment by Derkades** [comment]
I did some further investigation, and it seems that, while the cookie notice is automatically dismissed after a few seconds, the website only thinks that the user has accepted cookies when they manually close the notice. So, on every page you visit, the cookie notice will appear for a couple of seconds until it automatically disappears, until you manually close it.

In my opinion it should be changed so that
- The delay is longer, I'd say about 30 seconds, to give the user time to read it. Then, the cookie notice is automatically dismissed and won't appear again or
- The notice is not automatically dismissed and requires manual input (my preference)

**Comment by samerton** [comment]
Cookie notice no longer auto closes as of https://github.com/NamelessMC/Nameless/commit/817a5a17b52ea06fb9d5f582b9c26f63bf79e838
