### ISSUE TITLE
Odd search bar placement

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1508]
Either add a margin between the search bar and the discord widget or maybe put it on the same height as the "Forums" header
![image](https://user-images.githubusercontent.com/15892014/58126401-2cd6ac80-7c13-11e9-8539-73c08c44f1f9.png)

**Comment by robinriezebos** [comment]
or you might consider putting it in the navbar instead

**Comment by samerton** [comment]
13f59fd1a952af1468fbca000a5b5376f02f5e5e
