### ISSUE TITLE
After Installation blank screen

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#151]
i recently re-installed Nameless, deleted the package from /var/www/
because i was trying to utilize banmanagement and it blank screened on me.
after I run the Installation it blank screens on me could I have some help?

**Comment by samerton** [comment]
Sounds like it could be a permissions issue, could you alter the permissions of the **cache** directory so it's writable?

**Comment by ThemInspectors** [comment]
iy's set to 777 or drwxrwxrwx

**Comment by ThemInspectors** [comment]
does the data inside of it have to be root because I see 4 files non root

**Comment by ThemInspectors** [comment]
Also how would you install BanManager w/ NamelessMC?

**Comment by samerton** [comment]
Was the permission change recursive, ie, all files within the folder were affected by the permission change (using the -R flag)?

BanManager support is currently being worked on, hopefully won't be too long before it's complete.

**Comment by ThemInspectors** [comment]
yes

**Comment by samerton** [comment]
Can you add the following code to the bottom of **core/init.php** and see if any errors display on the page?

`		ini_set('display_startup_errors',1);
		ini_set('display_errors',1);
		error_reporting(-1);`

**Comment by ThemInspectors** [comment]
still all blank, I can't even look at the HTML code ):

**Comment by samerton** [comment]
Can you check your server's Apache logs for errors?

**Comment by ThemInspectors** [comment]
`[Wed Mar 30 07:41:02.609969 2016] [mpm_prefork:notice] [pid 4329] AH00163: Apache/2.4.10 (Ubuntu) configured -- resuming normal operations
[Wed Mar 30 07:41:02.610021 2016] [core:notice] [pid 4329] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 30 16:29:15.760073 2016] [mpm_prefork:notice] [pid 4329] AH00169: caught SIGTERM, shutting down
[Wed Mar 30 16:29:19.745267 2016] [mpm_prefork:notice] [pid 9306] AH00163: Apache/2.4.10 (Ubuntu) configured -- resuming normal operations
[Wed Mar 30 16:29:19.745369 2016] [core:notice] [pid 9306] AH00094: Command line: '/usr/sbin/apache2'


`

**Comment by samerton** [comment]
When you say you reinstalled Nameless, which version did you run before and after?
Did you clear the database before performing the reinstall?

**Comment by ThemInspectors** [comment]
1.0.6 zip > 1.0.6 tar-gz i probably didn't clear the database
