### ISSUE TITLE
Discord widget instructions no longer accurate

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1511]
![image](https://user-images.githubusercontent.com/15892014/58130018-63b0c080-7c1b-11e9-9d6a-64ae5fd241dc.png)

**Comment by IsS127** [comment]
Should've been fixed in https://github.com/NamelessMC/Nameless/commit/b87c4e716b6981dacf678c8bb5301ecb56f6eeae

Will be added & fixed in next release
