### ISSUE TITLE
"More" dropdown missing

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1512]
![image](https://user-images.githubusercontent.com/15892014/58130840-5eed0c00-7c1d-11e9-8257-5bfbae2c9adb.png)

![image](https://user-images.githubusercontent.com/15892014/58130867-6f04eb80-7c1d-11e9-8fc9-9fe9bdd82fb3.png)

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/b953c086fcd44bf791bf6c02f5cefa3b541f3adf
