### ISSUE TITLE
Allow changin hex color code manually in color picker

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1514]
![image](https://user-images.githubusercontent.com/15892014/58132837-a3c77180-7c22-11e9-8e10-075c7e204e3c.png)

**Comment by Xemah** [comment]
You can edit it from the input box

**Comment by Derkades** [comment]
It's kind of hard to do. I assume Nameless uses some sort of library for the color picking that is replacing the color code in the text box on an interval. The only way to enter a color code is to type it somewhere else and copy paste it. When you remove or add single characters one at a time it keeps replacing the color code with whatever is set in the picker.

I understand that it may be hard to allow users to change the field in the color picker, depending on how the color picker is added. However, in my opinion at least entering a color code in the input box should be more user friendly

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/beffe926142bc6ffe679eb297d4598da778d6393
