### ISSUE TITLE
In DefaultRevamp template, add a bit of margin between username and badge, and make badges slightly smaller

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1515]
![image](https://user-images.githubusercontent.com/15892014/58133200-9bbc0180-7c23-11e9-9935-e22e77b032a4.png)

**Comment by Monology** [comment]
![58133200-9bbc0180-7c23-11e9-9935-e22e77b032a4](https://user-images.githubusercontent.com/38674653/59892598-b6f76980-93a7-11e9-8c18-33e77d135f90.png)
This would be better in my opinion

**Comment by Derkades** [comment]
I agree

**Comment by AtomicGaming666** [comment]
hey how you make the site show the staff online ?

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/pull/1535
