### ISSUE TITLE
Feature: Captha When Login

### ISSUE THREAD

**Issue by Reflyansyah** [NamelessMC/Nameless#1517]
This Given that the Website is very easy to hack if the Login Page is not equipped with Captcha!
https://ibb.co/XJMF1XV

**Comment by IsS127** [comment]
This feature is already added, you can activate your recaptcha in StaffCP -> Configuration -> Registration

**Comment by samerton** [comment]
This is currently only a feature on registration; I can look into adding it to login too.

**Comment by samerton** [comment]
Added in e4008daf992a915c5ae42cbb20ca31a66bdc29e9
