### ISSUE TITLE
cancel confirmation button confusing.

### ISSUE THREAD

**Issue by patchtv** [NamelessMC/Nameless#1518]
Change the cancel confirmation button (on creating new topics) to "yes" or "ok"
![afbeelding](https://user-images.githubusercontent.com/42698687/58373884-52c2c080-7f35-11e9-864d-09e2dfe23a9b.png)

**Comment by Derkades** [comment]
The dangerous button should be red, and the safe button green

**Comment by samerton** [comment]
f3bbf84820c9425e2042a02c8619509867852a38
