### ISSUE TITLE
Hi one question where i can post updates?

### ISSUE THREAD

**Issue by Prowco** [NamelessMC/Nameless#1520]
**Describe the issue**
Hi one question i see i some examples pages people post updates or screenshots in the home page where i can found the file or what thing i need edit for add some info and screenshots into my white space in the screenshot?

**Screenshots**
https://gyazo.com/b9ae69ea96d6d927d0c92e4a5368ed34

**Comment by samerton** [comment]
Hi, this should help:

```
News topics are forum topics that were created in a specific forum that has this setting enabled.
To enable news topics go to StaffCP > Forums > (Forum) and in the settings of a forum of your choosing toggle "Display topics as news on front page?".

After you toggle this setting, every topic created in that forum (for example: Announcements) will be displayed on the homepage.
```

**Comment by Prowco** [comment]
Another question how i can remove the page Status? and where i can change or edit the nametags
Guest= Log In
And CPASTAFF = Admin Panel
?

**Comment by Prowco** [comment]
And another question sorry i post now a update and welcome forum and is display in the home page but https://gyazo.com/4c92fe1eb5e943b4a8ebaf46ac1ab761
i dont like bc is small square with an option read full the is not a way for show all the post?

**Comment by samerton** [comment]
You can disable the Status page in the StaffCP -> Integrations -> Minecraft -> Minecraft Servers tab.

You can change any text in the language files, custom/languages/*language* for the core module, and modules/*module*/*language* for any other modules. The items you mention can be renamed in **general.php**.

To display more characters from the news post on the homepage, edit **modules/Forum/classes/Forum.php** in a text editor, find [this line](https://github.com/NamelessMC/Nameless/blob/v2/modules/Forum/classes/Forum.php#L523) and replace it with `"content" => Output::getDecoded($post),`

Can you send me a link to your website? I don't know why the image isn't loading.

**Comment by Prowco** [comment]
www.mcrp.ml 
yeah pictures are not displayed i dont now why
and ok let me make all the changes you say me and i let u know if works. thanks for everything 
and if u register in my website let me know and if give u admin rank so u can see why pictures are not displayed

**Comment by Prowco** [comment]
O sorry buddy now its works i make a new post since 0 and works
https://gyazo.com/16f82661f684b90b002e16e8c3a69c51

**Comment by Prowco** [comment]
You can change any text in the language files, custom/languages/language for the core module, and modules/module/language for any other modules. The items you mention can be renamed in general.php.
I search for the words i need to change there is Guest and CPSTAFF but i dont found this words en the file general.

**Comment by samerton** [comment]
With Craftingstore, full integration is coming in the future, but for now you can use a custom page (StaffCP -> Pages -> Custom Pages) and use an [iFrame](https://www.w3schools.com/tags/tag_iframe.asp). You need to enable the "Unsafe HTML" option for the custom page in order for it to work.

If you just want to remove the page name from Home **only**, find [this line](https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/header.tpl#L13) in **custom/templates/*template*/header.tpl** and replace it with
```
{if "PAGE"|defined && $smarty.const.PAGE eq 'index'}
  <title>{$smarty.const.SITE_NAME}</title>
{else}
  <title>{$TITLE} &bull; {$smarty.const.SITE_NAME}</title>
{/if}
```
I haven't tested that but it should work.

With the language files I can only recommend checking the other files in the folder, maybe user.php and moderator.php.

**Comment by Prowco** [comment]
and the last thing where i can found the forum icons?

**Comment by samerton** [comment]
You need to use HTML, for example an [HTML img tag](https://www.w3schools.com/tags/tag_img.asp) if you want an image, and if you want icons you can find them [here](https://fontawesome.com/icons).

**Comment by Prowco** [comment]
The icons looks very small in comparation with ur example icon some way for fix this or another page for get more biggers icons? 
https://gyazo.com/1dee54a68e9f3c0d322ad9708b7d3cce-

**Comment by samerton** [comment]
If they're Font Awesome icons, you can apply `fa-2x` to the class, for example `<i class="fas fa-exclamation fa-2x"></i>`

**Comment by samerton** [comment]
I'll mark this as closed, if you have any more questions please feel free to re-open.
