### ISSUE TITLE
Cache fallback system

### ISSUE THREAD

**Issue by Fiiily** [NamelessMC/Nameless#153]
I accidentally deleted my cache for my NamelessMC installation. Can anyone help me out here?

**Comment by samerton** [comment]
I'll implement a fallback system in the morning which will allow functionality without the cache.

**Comment by Fiiily** [comment]
Can you please send me a cache folder?

**Comment by samerton** [comment]
I've uploaded a cache folder to [Mediafire](http://www.mediafire.com/download/hgdt11m7vxhdoii/cache.zip)

**Comment by Fiiily** [comment]
When will the patch be coming out?
