### ISSUE TITLE
PDOException on forum addon

### ISSUE THREAD

**Issue by alsoGAMER** [NamelessMC/Nameless#1537]
Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ORDER BY topics.topic_reply_date DESC LIMIT 50
	        ) UNION (
	        SEL' at line 2 in /var/www/flarum/core/classes/DB.php:51
Stack trace:
#0 /var/www/flarum/core/classes/DB.php(51): PDOStatement->execute()
#1 /var/www/flarum/modules/Forum/classes/Forum.php(235): DB->query('(\n\t        SELE...', Array, 2)
#2 /var/www/flarum/modules/Forum/pages/forum/index.php(71): Forum->getLatestDiscussions('2', Array, '1')
#3 /var/www/flarum/index.php(84): require('/var/www/flarum...')
#4 {main}
  thrown in /var/www/nameless/core/classes/DB.php on line 51

**Comment by samerton** [comment]
Check out [this comment](https://github.com/NamelessMC/Nameless/issues/1361#issuecomment-450129825)
