### ISSUE TITLE
Missing Europe/Rome as timezone

### ISSUE THREAD

**Issue by alsoGAMER** [NamelessMC/Nameless#1538]
Europe/Rome is missing on the timezone list in acp

**Comment by samerton** [comment]
I don't believe this is a Nameless issue, we simply use [built-in PHP functionality](https://www.php.net/manual/en/class.datetimezone.php) to list timezones.

**Comment by samerton** [comment]
I've just had a look, and it's there for me.
![Screenshot 2019-06-29 at 10 38 29](https://user-images.githubusercontent.com/1812544/60382377-30ebba80-9a5a-11e9-8359-d4f4236470e2.png)

Maybe the timezones that appear depend on the web host?
