### ISSUE TITLE
"Null" at the top-left side of the page

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#154]
Under the Hotbar at the left side there's a text word saying "null"
https://gyazo.com/dac2df106666939580c581855d6dca7b
I've also enabled the error thingy @ misc and no results

**Comment by mentimjojo** [comment]
Are you getting this on all the pages? At some point I also had this, I fixed it but not sure where to problem was. Also nothing in error logs?

**Comment by samerton** [comment]
Try disabling the "Google Analytics" core module (AdminCP -> Core -> Modules).

**Comment by ThemInspectors** [comment]
Thank you Issue resolved.
