### ISSUE TITLE
Namelessmc down updater failure

### ISSUE THREAD

**Issue by henrik9999** [NamelessMC/Nameless#1542]
**Describe the issue**
Please describe the issue in as much detail as possible

Well right now namelessmc seems to be down and when i try to open my site the following happens

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Your Website'
2. See error

**Expected behaviour**
The Website working

**Nameless-2.0.0-pr6**

**Additional information**
Add more information about the problem if necessary.

on line 478 
`$update_check = curl_exec($ch);`
thats probably the error

there is an curl_error check below but it doesn't seem too work

**Comment by samerton** [comment]
The site is currently down, no ETA until it's back up yet.

**Comment by samerton** [comment]
I'll implement a fix so this doesn't affect the update checker.

**Comment by henrik9999** [comment]
> I'll implement a fix so this doesn't affect the update checker.
yes that what i was trying to say

**Comment by Aberdeener** [comment]
I believe this has been fixed
