### ISSUE TITLE
Changing prefix of database on config.php

### ISSUE THREAD

**Issue by Enz0Z** [NamelessMC/Nameless#1543]
When I was trying to organize my database, I realized that I can change the prefix of the name of the table, and then change the `prefix` line of `mysql` in the config.php. But, some parts of the code don't retrieve this field, so, they are still searching for `nl2_`, for example the Forum.php

**Screenshots**
![Captura1](https://user-images.githubusercontent.com/48935178/60379030-e8081780-9a01-11e9-9847-3b3ec1265a82.PNG)
![Captura2](https://user-images.githubusercontent.com/48935178/60379031-e8081780-9a01-11e9-8078-fe55d6d9f196.PNG)

As you can see below, the settings and other stuff works good with no prefix in my case. But the forum returns this error.
![Captura3](https://user-images.githubusercontent.com/48935178/60379049-2e5d7680-9a02-11e9-9da6-3048ed91d544.PNG)

**Comment by samerton** [comment]
This is correct, unfortunately it's not something that will be changed.

**Comment by Enz0Z** [comment]
Why?

**Comment by samerton** [comment]
There's too much in the v2 core that requires a nl2_ prefix in some more complex queries for a number of reasons. There's a chance I can revisit this after v2 is released, but for now the focus is on getting v2 ready for a full release.

**Comment by Enz0Z** [comment]
Okay then, I will wait for that. Thank you for your replies!
