### ISSUE TITLE
Where is the NamelessMC installation's directory [Help]

### ISSUE THREAD

**Issue by RetroAvenDev** [NamelessMC/Nameless#1544]
Is it in the main folder where all the folders and PHP codes are at or in a different folder. The instructions are very confusing on modules. Upload the contents of the **"upload"** directory straight into your NamelessMC installation's directory.
It the folder name or zip post to be upload like???

**Comment by samerton** [comment]
1. Unzip the resource on your computer
2. Upload all files inside the **upload** folder on your computer to wherever Nameless is installed
    - This is usually **public_html** or **htdocs** on web hosts

**Comment by RetroAvenDev** [comment]
I uploaded the folder that's called uploaded into the uploads folder

**Comment by samerton** [comment]
In the resource **upload** folder, you will probably see two folders; **custom** and **modules**.

In **public_html**, you will also see **custom** and **modules**. You need to upload the folders from your computer so these merge together, ie it goes directly into **public_html** and *not* uploads.

**Comment by RetroAvenDev** [comment]
I deleted the default folder and meant to insert something into there how can I fix this. I understand how to use the modules now.
