### ISSUE TITLE
Edit Post on Forums Bug

### ISSUE THREAD

**Issue by JavaGuy12** [NamelessMC/Nameless#1545]
**Describe the issue**
Press Edit on a forums post, and the text field isn't populated with the post.
**To Reproduce**
Steps to reproduce the behaviour:
Click edit on a forums post

**Expected behaviour**
What were you expecting to happen?

text to fill in

**Screenshots**

**NamelessMC version (from AdminCP -> Overview)** 2.0.0-pre6

**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
Which template are you using? Pre-release 5 templates will have this issue with pre-release 6.

**Comment by JavaGuy12** [comment]
Thanks so much. Yes, I am using a pr5 template, Bootstrap Material. Is there a way I can update it?
Thanks again for all of your help!

**Comment by samerton** [comment]
Until the template is updated, here's a manual fix:

1. Edit **custom/templates/Bootstrap Material/forum/forum_edit_post.tpl**
2. Find the line `<textarea name="content" id="editor" rows="3"></textarea>`
3. Replace with `<textarea name="content" id="editor" rows="3">{$CONTENT}</textarea>`

**Comment by samerton** [comment]
Just to note the template has since been updated, you can pick up the latest update [here](https://namelessmc.com/resources/resource/4-nameless-material-design/).

**Comment by JavaGuy12** [comment]
Oh, awesome. I guess that brings this issue to a close! Thank you, samerton, for all of the time you dedicate into this - it isn't easy!
