### ISSUE TITLE
Using NamelessMC on Nginx

### ISSUE THREAD

**Issue by JordanPlayz158** [NamelessMC/Nameless#1548]
**Describe the issue**
The formatting is broken on my website using namelessmc

**To Reproduce**
1. goto "https://nginx.org/en/download.html"
2. download "nginx/Windows-1.16.0"
3. goto "https://windows.php.net/downloads/releases/archives/"
4. download "php-5.6.0-Win32-VC11-x64.zip"
5. extract nginx to "C:\NGINX_PHP\NGINX\"
6. extract php to "C:\NGINX_PHP\PHP\"
7. goto "https://github.com/NamelessMC/Nameless/releases/tag/v1.0.21"
8. download "Source code (zip)"
9. extract it to C:\NGINX_PHP\NGINX\html\
10. copy my nginx.conf file "https://pastebin.com/USmNCcSt" to the nginx config folder
11. startup nginx
12. startup php-cgi with "php-cgi -b 127.0.0.1:9000"
13. load up the website with either your domain or localhost
14. if you wanna see my domain because you didn't recreate it here: https://fastermc.xyz

**Expected behaviour**
I expected the formatting to not be broken

**Screenshots**
Any screenshots I could provide you can see at https://fastermc.xyz

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC release version 1.0.21

**Additional information**
It appears that nginx or chrome has strict mime checking on and i can't find out how to fix it which is the cause of the formatting issue

**Comment by samerton** [comment]
Everything seems okay when I visit that domain, were you able to solve the issue?

**Comment by JordanPlayz158** [comment]
no I'll send screenshot and I know why it's either chrome or nginx has strict mime checking on which is not allowing, "https://fastermc.xyz/core/assets/css/bootstrap.min.css" to load to format the page "because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled." and the odd thing is with apache this doesn't happen but i want to use nginx cause it's more efficient http://prntscr.com/ofb1ea

**Comment by JordanPlayz158** [comment]
no I'll send screenshot and I know why it's either chrome or nginx has strict mime checking on which is not allowing, "https://fastermc.xyz/core/assets/css/bootstrap.min.css" to load to format the page "`because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`" and the odd thing is with apache this doesn't happen but i want to use nginx cause it's more efficient http://prntscr.com/ofb1ea

RE: OMG I tried in incognito and it worked and ofc chrome cached the broken version so it wouldn't load the working one but I think the original issue was I didn't have `include mime.types`
