### ISSUE TITLE
Features Request Thread v1.0

### ISSUE THREAD

**Issue by Fiiily** [NamelessMC/Nameless#155]
# Features and Request Thread v1.0.
### Comment anything you want added, knowing @samerton he'll make it happen!

I plan to do these a lot as I want Namless to even stand up to the Invision Power suite (I actually prefer Nameless way over IPB at this point!) but the software is a little lacking in some areas....
## **Features and methods for implementation:**

`fix the damn custom avatars` custom avatars are completely broken.

I understand this is a lot to ask for an opensource project- but if you can provide this will really make my day(s) as a server admin.
## **Solved or addressed one way or another:**

`profiles > custom banners` Implemented in v2
`fix the damn alerts` Implemented in v2.
`staff applications text area` Will be worked on.
`profiles > custom banners` Implemented in v2. 
`raw html for admins` Allow administrators to enable RAW html in their posts and other text areas including about pages. (Addressed by @samerton  **Clarification: I'm talking about posts overall, anywhere you see the WYSIWYG and you are an admin the HTML sanitation is disabled and you may use the source button**
`group displaynames` Either display group HTML or display a configurable group display name in the memberslist. The main reason this is an issue is because I have groups made to inject html into profile pages, this would also be fixed with the about page :^) (Addressed by @samerton: HTML now displays in userlist. (992538f) is the relevant commit)
`multiple groups/display groups` Allow multiple groups to be assigned to a user and allow multiple group HTMLs to be displayed. (Addressed by @samerton: This feature will come in to play in much later versions)
`fix the damn installer` You give no prompt to delete the installer file- in the past I didn't even figure that out and I ended up removing the code. #156 (Addressed by @samerton: Installer will be worked on in the future. Permissions are the issue with the installer not auto-deleting its self.)
**please samerton add this** `profiles > about` Below the basic profile information a configurable monospace area would be very nice for an about page for members of the site. This could be relatively easy if handled as if it is a post. (Addressed by @samerton: Will be added sooner or later with more other things.)

**Comment by Fiiily** [comment]
Will provide concepts of all these features in action that are purely front-end relatively soon, good at HTML but not good with PHP.

**Comment by samerton** [comment]
Initial thoughts:
`profiles > about` - Adding more profile fields/allowing custom fields are planned, I'm hoping to get these done before the 1.1 release.
`raw html for admins` - This is possible using the "Source" button in the Custom Pages editor, and it should be easy to implement in other editors too. This may sneak into the 1.1 release.
`group displaynames` - Group HTML now displays on the memberlist (992538f5bebfaa9f8464df4fb294467e21d7d38d)
`multiple groups/display groups` - Planned, unfortunately I probably won't get round to adding this until much further down the line.
`fix the damn installer` - In most cases, the installer will delete itself unless permissions aren't set. Admittedly the installer needs a bit of care, as it's mostly leftovers from the old pre-releases, which I'll get round to eventually.

**Comment by Fiiily** [comment]
Updating post.

**Comment by ThemInspectors** [comment]
How about customizing/adding Topic labels (colours mostly) so I can Add coloured prefixes on the site?

**Comment by ThemInspectors** [comment]
what about IRC? and dynmap?

**Comment by samerton** [comment]
Customised topic labels are a possibility for the future, however I'm not too sure about adding IRC.
Dynmap is already possible, you can insert the iFrame code into the "source" mode of the custom page editor.

**Comment by ThemInspectors** [comment]
How about a permission on the forums to "can read other's threads"
and an option on labels "can always be seen"

**Comment by Wundero** [comment]
Perhaps you could implement Vault group loading and support (when you release the plugin)? It would give server owners the option of different permissions/economy plugins rather than specific ones.

**Comment by samerton** [comment]
@ThemInspectors Sure, I can link this with #3 

@Wundero This is definitely planned, group synchronisation will be possible as long as a Vault based permissions plugin is available. The first statistics plugin which will be supported ([available here](https://www.spigotmc.org/resources/statistics.19016/)) does include Vault support, so a player's balance, no matter which economy plugin is used, will be displayed once the addon's ready.

**Comment by Fiiily** [comment]
Updated post.

**Comment by samerton** [comment]
v2 update:

`profiles > custom banners` - implemented
`fix the damn custom avatars` - still needs work
`fix the damn alerts` - fixed
`staff applications text area` - will be reworked as part of new Forms module

**Comment by Fiiily** [comment]
How about you completely remove custom avatars while they suck? A lot of people lack the DB management tools to recover from the changes made by having a custom avatar.
Updated post.

**Comment by Fiiily** [comment]
Custom banners wasn't quite implemented as desired. I wanted it to be uploadable.
Is this on the roadmap @samerton?

**Comment by samerton** [comment]
Custom banners are taken from the **uploads/profile_images** directory, for now custom upload through FTP is possible however I can add an uploader through the AdminCP at some point.

**Comment by samerton** [comment]
Avatar system hopefully fixed in d8276bb766d35ea31917ecad8929db690618d418 for v2
