### ISSUE TITLE
SMTP Error: Could not connect to SMTP host.

### ISSUE THREAD

**Issue by borps** [NamelessMC/Nameless#1553]
**Describe the issue**
I filled in the fields and the file with my correct login information for smtp.gmail.com, however everytime I try to use it with PHPMailer it says "SMTP Error: Could not connect to SMTP host." and when I try without PHPMailer, it says "mail(): SMTP server response: 553 We do not relay non-local mail, sorry."

**To Reproduce**
Steps to reproduce the behaviour:
1. Open StaffCP 
2. Goto Email
3. Turn on PHPMailer
4. Fill in information for smtp.gmail.com
5. Click Submit
6. Send test email
7. See error

**Expected behaviour**
I was expecting to have been sent an email to my person gmail account

**Screenshots**
https://web.jessicasworld.cf/cdn/zl6shgcx.png
https://web.jessicasworld.cf/cdn/7n5mlpfo.png

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC 2.0.0-pr6

**Comment by samerton** [comment]
To get a full email log with PHPMailer enabled, edit **core/classes/Email.php** in a text editor, delete all code inside and replace with [this code](https://gist.githubusercontent.com/samerton/a26df55561f9735eb2f69af6868f57fb/raw/5f5581c6faa44c596eebccaa32d6c0efa8f79a81/Email.php). Then when you send a test email you will get a full debug log on screen to see what's going on.

**Comment by youruncleron** [comment]
Thank you for getting back to me! Here is the log I was provided with:

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 smtp.gmail.com ESMTP x8sm27686707qka.106 - gsmtp"
SERVER -> CLIENT: 220 smtp.gmail.com ESMTP x8sm27686707qka.106 - gsmtp
CLIENT -> SERVER: EHLO jessicasworld.cf
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-smtp.gmail.com at your service, [myipaddress]"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [myipaddress]"
SMTP -> get_lines(): $str is "250-SIZE 35882577"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [myipaddress]250-SIZE 35882577"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [myipaddress]250-SIZE 35882577250-8BITMIME"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [myipaddress]250-SIZE 35882577250-8BITMIME250-STARTTLS"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [myipaddress]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [myipaddress]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [myipaddress]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 2.0.0 Ready to start TLS"
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is ""
SERVER -> CLIENT: 
SMTP ERROR: QUIT command failed: 
Connection: closed
SMTP Error: Could not connect to SMTP host.

**Comment by xXQuantumSoulXx** [comment]
I have a similar error, I tried the steps suggested by samerton and i get this error, i feel like its something related to nameless not having enough perms in my vm
`
Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Permission denied)
SMTP ERROR: Failed to connect to server: Permission denied (13)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
`

**Comment by samerton** [comment]
Sorry for the delay on this.

@borps 
For the issue with `Could not connect to SMTP host` directly after `Ready to start TLS` (from the logs), try adding this code to [here](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Email.php#L69) in core/classes/Email.php:
```
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```

@xXQuantumSoulXx 
This is one to contact your web host about, I think they are blocking the outgoing connection

**Comment by samerton** [comment]
I'll mark this as closed, but if you're still experiencing issues please feel free to re-open :)
