### ISSUE TITLE
logs shown when mail successfully sent through phpmailer

### ISSUE THREAD

**Issue by xXQuantumSoulXx** [NamelessMC/Nameless#1554]
**Describe the issue**
When registering or sending email, the next page is a log of the connection. debug mode is not enabled

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to staffcp > configuration > email > make sure phpmailer is on. (registration) just register
2. make sure on gmail less secure access is enabled and send a test mail
3. get all the logs

**Expected behaviour**
redirect to a page saying test mail sent successfully or for registration get back to the home page or previous page with a box at the top telling to check inbox/spam

**NamelessMC version (from AdminCP -> Overview)**
V2 pr6

**Additional information**
Im on apache, centos 7 and php 5.4. cant get 7.2 to work if you're wondering

**Comment by samerton** [comment]
Reset the file **core/classes/Email.php** back to [its original code](https://raw.githubusercontent.com/NamelessMC/Nameless/v2/core/classes/Email.php) as it looks like you have applied the debug script in the past.

**Comment by samerton** [comment]
Were you able to resolve this @xXQuantumSoulXx?
