### ISSUE TITLE
SMTP Error: SMTP connect() failed.

### ISSUE THREAD

**Issue by ainomar1000** [NamelessMC/Nameless#1555]
**Describe the issue**
I am having issues with PHPMailer, I have filled in all fields with correct information for smtp.gmail.com however everytime I attempt to use it with PHPMailer it returns `SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`, I have had a look at the page it asks for but no luck. 

**To Reproduce**
Steps to reproduce the behaviour:
Open StaffCP
Go to Email
Turn on PHPMailer
Fill in information for smtp.gmail.com
Click Submit
Send test email

**Expected behaviour**
The email to send and appear on my mail account

**Screenshots**
Not needed as it's just the regular Error screen for the Send Test Email page.

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC 2.0.0-pr6

**Additional information**
I have had a look at [this issue](https://github.com/NamelessMC/Nameless/issues/1553) and added [this code](https://gist.githubusercontent.com/samerton/a26df55561f9735eb2f69af6868f57fb/raw/5f5581c6faa44c596eebccaa32d6c0efa8f79a81/Email.php) to the **core/classes/Email.php** file and the error output is as follows:
`Connection: opening to smtp.gmail.com:587, timeout=300, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ),)
Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Network is unreachable)
SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

**Comment by samerton** [comment]
Are you using a web host or your own VPS/dedicated server? 
PHPMailer is unable to connect to gmail.

**Comment by ainomar1000** [comment]
It's through a web host, How would I fix this?

**Comment by samerton** [comment]
I'd recommend contacting your web host, it looks like they are blocking the connection.

**Comment by samerton** [comment]
Any luck with this @ainomar1000?

**Comment by samerton** [comment]
I'll mark this as closed, if you're still having the problem please feel free to re-open :)
