### ISSUE TITLE
Show login page if URL really exists for 404 page

### ISSUE THREAD

**Issue by redbau** [NamelessMC/Nameless#1561]
Replace/update the 404 page so if the URL/page actually exists you can login and view it, instead of having to second guess every link you click.

This is a nice to have UX improvement that will greatly improve people actually using your product. Right now my mods and players run into the 404 page dozens of times per day and are constantly confused and frustrated that something was moved/deleted, the link was bad (when it was fine but they just needed to be logged in to view it.)

**Comment by samerton** [comment]
This is an interesting one, generally I've always preferred returning a 404 as if the user can't view something they shouldn't know it exists at all.

I can change this though, is this for any feature in particular such as forum topics or custom pages?

**Comment by Derkades** [comment]
I agree that returning a 403 error is better than a 404 error

**Comment by A248** [comment]
I second the motion. (agree)

**Comment by samerton** [comment]
Now shows a different 403 error as of https://github.com/NamelessMC/Nameless/commit/fae0da2c83e9b7fe58251e7ead358b1d45b90171 which includes a login link
