### ISSUE TITLE
In StaffCP, users can see notifications for pages that they do not have permission to see

### ISSUE THREAD

**Issue by justaskarvovskis** [NamelessMC/Nameless#1562]
**Describe the issue**
In StaffCP you can get notifications to parts of StaffCP you don't have permission to see. So when you click on that notification it sends you to a 404 page.

**To Reproduce**
1. Sign in with an account that has limited permissions in StaffCP.
2. Trigger a notification in some way.
(The account with limited permissions will see the notification, even though it doesn't have permissions to view that part of StaffCP.)
3. Click on the notification. (you will be sent to a 404 page.)

**Screenshots**
<img width="330" alt="Screenshot 2019-09-02 at 19 45 36" src="https://user-images.githubusercontent.com/44247810/64129330-b756ac80-cdbb-11e9-94dd-487f154e4423.png">
<img width="995" alt="Screenshot 2019-09-02 at 19 45 41" src="https://user-images.githubusercontent.com/44247810/64129328-b756ac80-cdbb-11e9-8fd3-dba45619e06d.png">

**NamelessMC Version**
v2 pre-release 6

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/78eaadaf929b7bd4d9fb12336e851018c93252af
