### ISSUE TITLE
Web page does not display images nor themes, just plain text

### ISSUE THREAD

**Issue by eirikh1996** [NamelessMC/Nameless#1563]
**Describe the issue**
I installed the latest pre-release of this software and I am utterly disappointed by the resulting pages, which contains no colour, no images (apart from the user avatar), just plain text:

**To Reproduce**
Steps to reproduce the behaviour:
Install the software as you would usually do

**Expected behaviour**
A normal page would appear post-installation that contains more than just plain text

**Screenshots**
219ee19b761a039ec2ccfb22ca2119cc
**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pre6 (Overview was unavailable too)
**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
Hi,

This suggests the installation path in `core/config.php` is incorrect. 

If Nameless is installed in a subfolder, for example `public_html/nameless`, the `path` setting in `core/config.php` needs to be equal to the subfolder name, for example `'nameless'`

Similarly, if Nameless is installed in the root, for example `public_html`, the `path` setting needs to be empty (eg `'path' => '',`)

**Comment by samerton** [comment]
I'll close this as it's a configuration issue, if you're still experiencing the issue please feel free to re-open.
