### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getEditor' of undefined

### ISSUE THREAD

**Issue by Capri205** [NamelessMC/Nameless#1564]
Hi. For a while I have been unable to properly do anything as admin on our site - edit custom pages, view the server list etc. Most times there aren't any errors in the apache logs or in the browser console. Just nothing happens when clicking links, however for some pages I am seeing this error in the browser console:

ckeditor.js:316 Uncaught TypeError: Cannot read property 'getEditor' of undefined
    at a (ckeditor.js:316)
    at Object.CKEDITOR.replace (ckeditor.js:320)
    at ?page=6:220

and sometimes this in the apache log for some pages:

[Fri Sep 06 11:40:59.551510 2019] [php7:warn] [pid 31437] [client 192.168.1.1:47186] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/mc/web/core/queries/private_messages.php on line 18

We are using v1.0.21 on ubuntu 19.04 with PHP 7.2. Probably some of the many system and O/S updates over the years have broken things. No modules. Default theme.

I will try a re-installation though. Been avoiding that in case that means we have to rebuild everything from scratch.

Cheers.

**Comment by samerton** [comment]
Hi,

The getEditor of undefined error isn't something to be worried about, the chances are it's just trying to render an editor (eg the post and custom page editor) on pages where there shouldn't be one.

What exactly happens when you click on a link, does it simply not take you to another page at all?

**Comment by Capri205** [comment]
Thanks for replying so promptly. That's right, I am just put back on the same page. The page refreshes/flickers but ultimately is the same page and not the page where I should be.

As mentioned, I will try a re-installation of v1.0.21 as it's been a while and many system updates have been performed in the interim.

**Comment by Capri205** [comment]
A reinstall worked. Fortunately it doesn't overwrite or clear the database contents so everything is there. Thanks for the replies and apologies for wasting your time. I guess all of the system, php, apache and O/S updates over the years caused things to get messed up.

Thanks again.
