### ISSUE TITLE
Error when try to remove a wall post / reply

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1568]
**Describe the issue**
When I try to delete a comment or a reply from the profile I receive an error in the console, and the message cannot be deleted at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a profile.
2. Add a comment /reply
3. Try to delete
4. Error in console and coment can`t be deleted.

**Expected behaviour**
When you press delete the message will be deleted.

**Screenshots**
http://prntscr.com/padd2k
```
jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #form-delete-{$item.id}
    at Function.ga.error (jquery.min.js:2)
    at ga.tokenize (jquery.min.js:2)
    at ga.select (jquery.min.js:2)
    at Function.ga [as find] (jquery.min.js:2)
    at n.fn.init.find (jquery.min.js:2)
    at new n.fn.init (jquery.min.js:2)
    at n (jquery.min.js:2)
    at HTMLAnchorElement.onclick ((index):217)
```

**NamelessMC version (from AdminCP -> Overview)**
Running NamelessMC version 2.0.0-pr6

**Additional information**
nothing

**Comment by samerton** [comment]
Works fine on my end, have you tried with the default/default revamp template?

**Comment by baxandrei** [comment]
I am using default revamp

**Comment by samerton** [comment]
Still not been able to reproduce this issue unfortunately. Are you still experiencing this @baxandrei?

**Comment by baxandrei** [comment]
It's been a long time and I haven't had time to deal with the forum. You can close this ticket, and if the problem is still present I will add a new reply.
