### ISSUE TITLE
User tooltip is logged in console.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1569]
**Describe the issue**
User tooltip is logged in console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go on homepage
2. Open Console
3. go to console tab
4. Hove a username.

**Expected behaviour**
don`t log it to console.

**Screenshots**
http://prntscr.com/pagmwq

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr6

**Additional information**
no

**Comment by samerton** [comment]
You can disable debugging in the StaffCP -> Configuration -> Maintenance tab to prevent this behaviour.

**Comment by baxandrei** [comment]
Opss. Sorry, I forgot about this.
