### ISSUE TITLE
Embed issue

### ISSUE THREAD

**Issue by TheCynicalKitty** [NamelessMC/Nameless#1572]
Any idea why embed links are adding "topic" into my links ?
https://knightsips.net/forum/topic/view/16-bug-reports/

Should be
https://knightsips.net/forum/view/16-bug-reports/

See here for example :/
http://cruxedkat.live/s/20191048990.gif

**Expected behaviour**
I expect it to direct to the link i posted instead of returning a error (its a category link)

**NamelessMC version (from AdminCP -> Overview)**
Running NamelessMC version 2.0.0-pr6

**Comment by samerton** [comment]
This should have been fixed by https://github.com/NamelessMC/Nameless/commit/3ac0257a89b62070df00bfa17ee12edc305575c1 which will be included in the next update.

**Comment by TheCynicalKitty** [comment]
Any idea when that update will be ?

**Comment by samerton** [comment]
Unfortunately I can't estimate when the update will be available.

**Comment by TheCynicalKitty** [comment]
is this update available to grab now though in its current state to fix this issue ?

**Comment by samerton** [comment]
If you're comfortable with editing the source code yourself, you can apply the change from the commit manually.
To do this, add the new line as highlighted in my above link to `core/classes/Input.php`
