### ISSUE TITLE
Hi excuse me i have a huge problem in my website.

### ISSUE THREAD

**Issue by Prowco** [NamelessMC/Nameless#1576]
The situation is this i have some problems with https option bc i dont have Flexible" SSL but i remove the cache option and everything its ok but now i dont use any page than the home i mean just home page works the other pages like forum store vote and etc display a error 404 not found
[My Website Home](http://www.mcrp.ml/) as you  can see home link works
but
[My Website Forum](http://www.mcrp.ml/forum/) its not work like other pages. also de log in dont work so i cant get into the cpanelstaff

**Comment by samerton** [comment]
Hi,

You'll need to disable `friendly` in `core/config.php` (ie change `'friendly' => true` to `'friendly' => false`) as it looks like either your web server does not support friendly URLs or your htaccess file is missing.
