### ISSUE TITLE
New verification system

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1577]
Email verification and username verification should be two independent toggle switches that can be set to on/on, on/off, off/on, off/off.

Username verification uses the /validate command in the plugin to ensure the user owns the Minecraft account which they used to register. When registering using /register, the username is automatically verified.

Email verification sends an email with a link to ensure that the user owns the email which they used to register. When registering using /register, the email is automatically verified (because the user has to click a link in an email to set a password, which they can only do if they enter an email address that they own)

Only one "unverified" and "verified" role, no more "post-validation group".

**Comment by A248** [comment]
Agree. /validate is much better than MCAssoc. Players don't want to change their skin just to get a web account.

**Comment by Derkades** [comment]
**Universal verification system**
Right now there are two separate verification systems for Minecraft and Discord accounts. Different code, different tables, different API methods, and so on. We should create a new verification system to replace these two and allow more verification types in the future.

Example table layout:
* user id (foreign key to user table)
* timestamp (could be useful for some features, for example forcing re-verification every once in a while)
* type (e.g. "Discord", "Minecraft")
* id (e.g. Discord id, Minecraft UUID)
* username_updated (timestamp: if username old, use API (e.g. Discord API or Mojang API) to update username using id in case user has changed username)
* username (e.g. Discord username, Minecraft username)
* code (null if verified)

New API methods:
Replacing `verifyMinecraft` and `verifyDiscord`, add `verifyService` (?) with the service type (e.g. Discord, Minecraft), id, username and verification code

This system should probably be used for emails as well.

**Control panel configuration**
Users are free to verify as many accounts as they want. These accounts can be displayed on the user's profile. Allow admins to configure some verification types as required for being able to access an account. Something like:

Require verification for:
- [x] Email
- [x] Minecraft
- [ ] Discord
- [ ] Some social media
- [ ] Some video game
