### ISSUE TITLE
Account already activated 

### ISSUE THREAD

**Issue by EchoRapidz** [NamelessMC/Nameless#1578]
When a player registers and they get the /validate (code) to type ingame it just says the accounts already activated 

http://www.rapidzsurvival.xyz

**Comment by Derkades** [comment]
That's how the verification system works right now unfortunately. See #1577

**Comment by Derkades** [comment]
Actually, it is a bug, the plugin should not check whether the account has been activated because it is different from validated. I'll fix this for the next version
