### ISSUE TITLE
Maybe add a "root" user

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#158]
I've just locked myself out of the admin panel. Maybe the first registered person could be "root" and not able to be demoted?
also what would the MySQL command to put me back as an Admin?

**Comment by samerton** [comment]
Your user ID will likely be 1 (presuming you're the user that ran through the installer), so the following **should** work (untested):

UPDATE nl1_users SET group_id = 2 WHERE `nl1_users`.`id` = 1;

**Comment by ThemInspectors** [comment]
where do I put it?

**Comment by ThemInspectors** [comment]
using this command UPDATE Nameless SET group_id = 2 WHERE nl1_users.id = 1;
where "Nameless " is the database username getting Error 1046

**Comment by ThemInspectors** [comment]
Also make sure only the super admin can add & remove the group Admin

**Comment by samerton** [comment]
The command should work as is, don't replace "nl1_users" with "Nameless".
If you need to select a database first, use the command

USE Nameless;

and then type the command

UPDATE nl1_users SET group_id = 2 WHERE nl1_users.id = 1;

**Comment by ThemInspectors** [comment]
Also what's the SQL command for changing your password? I just re-install firefox & lost all of my cookies

**Comment by samerton** [comment]
It's not possible to change passwords with an SQL command, due to the password hashing in place.
You'll need to use the "Forgot Password" functionality if you're logged out.

**Comment by ThemInspectors** [comment]
Yeah the ingoing / outgoing address is the some as my account

**Comment by samerton** [comment]
If you're not able to access the emails, you'd have to register a new account, find out the user ID of your new account (if it's the 6th account registered, it would be ID 6 for example) and then use the following SQL command to make them administrator:

UPDATE nl1_users SET group_id = 2 WHERE nl1_users.id = 6;

replacing 6 with your user ID.

You can then log into the AdminCP, however it's not possible at the moment to change another user's password, even in the AdminCP, so it sounds like your first account is effectively locked out of.

**Comment by ThemInspectors** [comment]
Milestone?
