### ISSUE TITLE
New topic  just show some words in home website

### ISSUE THREAD

**Issue by Prowco** [NamelessMC/Nameless#1582]
**Describe the issue**
In the  home website just show some words and looks very ugly. i want to show all the post
this is how its looks:
https://gyazo.com/109d99cccd61f1fcdaedf63bb53bb2b1
And  this  is how  i want to look:
https://gyazo.com/e1f8d43c82d5684a5f7432dcef014e6e

And this is the website if you wanna look by yourself how its looks:
http://www.mcrp.ml/
**NamelessMC version (from AdminCP -> Overview)**
Minebox

**Comment by samerton** [comment]
You can increase the number of characters that show in the news posts by editing [this line](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Util.php#L374) in core/classes/Util.php and change the 750 value to the value you wish.

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues please feel free to re-open.
