### ISSUE TITLE
Hi can you add github support for wiki?

### ISSUE THREAD

**Issue by Prowco** [NamelessMC/Nameless#1583]
**Please describe the feature in as much detail as possible**
I am making all the [wiki](https://github.com/Prowco/MineCityRP/wiki) for my [server](http://www.mcrp.ml/) in github bc is  the most easy way i know so i want to know if you can add support for nameless so people can see the wiki in the same website not redirect to github

**Comment by samerton** [comment]
Thanks for the suggestion, I'm going to link this with https://github.com/NamelessMC/Nameless/issues/1162 and mark this as closed.
