### ISSUE TITLE
Redirects do not work for guests even if guests are allowed

### ISSUE THREAD

**Issue by Dinoosawruss** [NamelessMC/Nameless#1584]
**Describe the issue**
Redirect pages will not work for guest users (person is not logged in) and will throw up a 404 page. If they are logged in it works fine

**To Reproduce**
Steps to reproduce the behaviour:
1. Create redirect page
2. Allow guests
3. Log out
4. Try to use redirect page
5. See 404

**Expected behaviour**
Redirects like it would for logged in user

**NamelessMC version (from AdminCP -> Overview)**
Can’t find overview but the update section says were up-to-date (Might to be being blind)
Running v2

**Additional information**
Asked on discord was told to use friendly urls to no avail

**Comment by samerton** [comment]
Likely the same problem as #1560, not been able to reproduce on my side using latest dev code but will continue to investigate.

**Comment by samerton** [comment]
Pre-release 7 is now out, I've not been able to reproduce using this version.

**Comment by Dinoosawruss** [comment]
Fixed
