### ISSUE TITLE
Dropdown menu in rank sync settings

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1585]
Allow the user to choose the in-game rank using a drop down menu. To do this, there will need to be an api method to publish a list of ranks, include it in the server data sender json or maybe something else entirely. I'll wait to see if anyone has any ideas about this before implementing it in the plugin

**Comment by Haveyougonemad** [comment]
+1

**Comment by Aberdeener** [comment]
Added this in d6385cb

**Comment by Derkades** [comment]
The downside of this implementation is that it will only show ranks it has seen before, and the plugin will only send ranks for online players. Ideally the plugin would publish a list of all ranks as well, in the existing info endpoint maybe?

**Comment by Aberdeener** [comment]
So like a permanent list?
Each time it send the groups, add to a list stored on the website of all the groups?

**Comment by Derkades** [comment]
No, but I thought that was how it worked right now? Does your current implementation override the list of ranks every time? That won't work at all, The plugin only sends rank information for online players so it will only show ranks in the dropdown used by currently online players.

The only proper solution as far as I can tell is sending a list of all ranks separately and storing that
