### ISSUE TITLE
Fatal DB Error during update. 

### ISSUE THREAD

**Issue by puttydotexe** [NamelessMC/Nameless#1595]
**Describe the issue**
Please describe the issue in as much detail as possible

**To Reproduce**
Steps to reproduce the behaviour:
1. Update Nameless from version `v2.0.0-pr6` to `v2.0.0-pr7`

**Screenshots**
https://imgur.com/a/Ex0F96m

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pr6

**Comment by samerton** [comment]
It looks like you're upgrading from v1 here.

In order to upgrade from pre-release 6 to pre-release 7 you must do so in the StaffCP -> Update tab.

**Comment by puttydotexe** [comment]
Issue resolved. Thank you.

**Comment by samerton** [comment]
No problem, glad it's resolved
