### ISSUE TITLE
[API] Just a question concerning the API.

### ISSUE THREAD

**Issue by puttydotexe** [NamelessMC/Nameless#1596]
Is there a feature in the provided API that would allow for changing and getting the extra strings on a player profile. Such as:

Profile Title and any extra strings that you can add via the settings in Nameless.

- putty

**Comment by Derkades** [comment]
Are you talking about a web API or a PHP api (for modules for example)?

**Comment by puttydotexe** [comment]
The API that the Nameless plugin uses, we have a custom version of it made in house and we're looking to add some more features.

**Comment by samerton** [comment]
Should be nice and easy to add to the API, I'll take a look

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/c3c033ed8fa2c38c286688b1688f308a3f7cb41a

**Comment by samerton** [comment]
These objects can be added to the Java API @Derkades as follows:

`userTitle:` string or null
`profile_fields` (forgive the snake case on this one sorry): array of
- `name`: string
- `type`: integer, 0 = date, 1 = string, 2 = text field
- `public`: integer, 0 = false, 1 = true
- `description`: string or null
- `value`: string or null

**Comment by puttydotexe** [comment]
Seems perfect thank you, amazing support.
