### ISSUE TITLE
Posts in a subcategory are not displayed when viewed on /forum/

### ISSUE THREAD

**Issue by BaxAndrei** [NamelessMC/Nameless#1599]
![image](https://user-images.githubusercontent.com/12484505/72721442-c11f5780-3b84-11ea-84d5-1220c75a87ed.png)
![image](https://user-images.githubusercontent.com/12484505/72721459-ca102900-3b84-11ea-9db4-d8ff796593b6.png)

**Comment by baxandrei** [comment]
Any news?

**Comment by samerton** [comment]
Going to decrease the priority on this one, I think fixing this would be incredibly difficult

What if you have a subforum tree with a depth of 5+? You'd have to calculate the latest post at each level and work your way up

What if the most recent post is in a subforum which only certain groups can view? You'd have to calculate the most recent post per group which adds a lot of complexity and a performance hit.

**Comment by Derkades** [comment]
closing because it is currently not possible in an elegant way
