### ISSUE TITLE
Users can bypass private profile even without permission

### ISSUE THREAD

**Issue by BaxAndrei** [NamelessMC/Nameless#1601]
Visitors can`t bypass private profile setting, but members (without bypass private profile permission) can post on private profiles even with private profile on

**Comment by baxandrei** [comment]
Any news?

**Comment by samerton** [comment]
Can't reproduce this one, I am correctly prevented from viewing a template without the bypass permission.

It's worth mentioning this is actually handled by the template, so make sure you have [this check](https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/profile.tpl#L44) in your template's profile.tpl

**Comment by BaxAndrei** [comment]
You are right, my template (Cesium) is missing this line `{if $CAN_VIEW}`

**Comment by samerton** [comment]
Glad you've found the cause of the issue 👍
