### ISSUE TITLE
Website namelessmc.com is down

### ISSUE THREAD

**Issue by DJIronic** [NamelessMC/Nameless#1602]
* Website namelessmc.com has DB issues, so resources are not accessible
![image](https://user-images.githubusercontent.com/9658012/73661517-7e886f80-469a-11ea-9399-99166d6280f9.png)

**Comment by samerton** [comment]
Unfortunately currently out of my hands, awaiting a host response.

**Comment by DJIronic** [comment]
Understand that, if you have the data and host is not working great, I can
definitely help you out with some hosting power for free :) (I love gr8
open source projects)

Kind regards
Simon

**Comment by DJIronic** [comment]
Looks like the site is still down, is there an issue with too many users accessing the page (= hitting the MySQL limit?). As I said, I can try to help with that, as I have some hosting power available and it's sad to see projects like this down.

You can hit me up at simon(at)c-net.cz :)  No asterisks or requests from you, I just want to help.

**Comment by samerton** [comment]
Thank you for the kind offer! 

I've managed to transfer from the previous host to one of my own machines for now, unfortunately using an older backup but at least the site's up and running for now :)
