### ISSUE TITLE
Users can submit posts with malicious HTML tags

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1605]
My users can use (on latest pre version)  inspect element to modify content of TinyMCE then post it, How I can solve this.?

**Comment by samerton** [comment]
Not sure I understand sorry?

Any malicious content is always removed before the post is displayed in the forum.

**Comment by baxandrei** [comment]
Users can insert for example IFRAMES from what I saw

**Comment by baxandrei** [comment]
It's been a long time and I haven't had time to deal with the forum. You can close this ticket, and if the problem is still present I will add a new reply.
