### ISSUE TITLE
Invalid reCAPTCHA response.

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless#1606]
**Describe the issue**
With recaptcha and 2fa enabled, it gives the following error when logging in: `Invalid reCAPTCHA response.`

**To Reproduce**
Steps to reproduce the behaviour:
1. Use DefaultRevamp theme
2. Enable recaptcha using own site and secret keys
3. Enable 2fa on account
4. Attempt to login using 2fa
5. Error: `Invalid reCAPTCHA response.`

**Expected behaviour**
Properly logs in

**NamelessMC version (from AdminCP -> Overview)**
2.x.x-pre7 - cannot get exact version because I cannot login

**Comment by samerton** [comment]
Fixed in https://github.com/NamelessMC/Nameless/commit/de6423cfd21f8eea7a8cbd5164527f2a444dda9b
