### ISSUE TITLE
[Suggestion] Server shows as online if can receive a valid response from query.

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless#1609]
Make the server status page show the server as online if it can get a valid response from query... Because some servers dont want to expose their game ports to the internet, especially if they are running a bungeecord/waterfall network. Show approval by clicking the like/+1 icon.

**Comment by samerton** [comment]
Not sure I understand, there's an option to hide the server IP when you create/edit your server in the StaffCP.

**Comment by Derkades** [comment]
You can install the [nameless plugin](https://www.spigotmc.org/resources/nameless-plugin-for-v2.59032) on your server which will let the website know the server is online without having to port forward it

**Comment by ZandercraftGames** [comment]
@samerton It isnt about hiding the IP from the site... It is about publically exposing the port which can allow people to create their own proxy and connect to the server through it. Using packet manipulation, they can make themselves look like the server owner.

**Comment by Derkades** [comment]
There are a few options:
* Host the website on the same machine
* Create a firewall rule to only allow queries from the website to the server, not any other connections
* Install the plugin IPWhitelist
* Skip the query thing altogether by using the nameless plugin

**Comment by ZandercraftGames** [comment]
@Derkades I am using the nameless plugin and it is successfully connected to the site... However, it does not display the server as online even though it is properly configured. As for getting a response from query, Minecraft servers run a service on a separate port called "Query". Query provides certain forms of information which include server version, users online, number of users online out of max users online, MOTD, and plugins amoung other things. NamelessMC uses this query service to get the number of users online, what users are online, and a few other things. What my suggestion is, is that if namelessmc is able to get a valid response from query, even if it doesnt get it from the server port (and server itself, not query) that it assume the server is online because it is getting a valid response from an online server (the query service). Currently the way that it determines if it is online is only if it can contact the game server port, query doesnt seem to be involved in that decision.

**Comment by ZandercraftGames** [comment]
![image](https://user-images.githubusercontent.com/28664144/74889521-5150e800-534f-11ea-83bb-d4958199f287.png)

**Comment by ZandercraftGames** [comment]
It seems to be working now... Sorry for the inconvenience, it fixed itself overnight.
