### ISSUE TITLE
[Installation] No next button

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#161]
As the title says (http://prntscr.com/amu3et). I checked my log and I'm getting this error:
`[Fri Apr 01 20:01:36 2016] [error] [client 145.53.93.97] PHP Warning:  require_once(core/classes/DOMDocument.php): failed to open stream: No such file or directory in /var/www/html/core/init.php on line 26, referer: http://gravelcraft.nl/
[Fri Apr 01 20:01:36 2016] [error] [client 145.53.93.97] PHP Fatal error:  require_once(): Failed opening required 'core/classes/DOMDocument.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/core/init.php on line 26, referer: http://gravelcraft.nl/`

**Comment by ThemInspectors** [comment]
have you tried reinstalling the package?

**Comment by HappyHarm** [comment]
@ThemInspectors Yes I did

**Comment by ThemInspectors** [comment]
is .htaccess enabled?

**Comment by HappyHarm** [comment]
Idk can it be disabled xD?

**Comment by ThemInspectors** [comment]
it's suppost to be enabled

**Comment by ThemInspectors** [comment]
You use linux

**Comment by HappyHarm** [comment]
CentOS

**Comment by ThemInspectors** [comment]
Okay do "cd /etc/apache2/sites-enabled/"

**Comment by HappyHarm** [comment]
-bash: cd: /etc/apache2/sites-enabled/: No such file or directory

**Comment by ThemInspectors** [comment]
then do "ls" tell me what files you see

**Comment by samerton** [comment]
Looks like you need to install the PHP-XML library.

Try the following in SSH:
`yum install php-xml`

**Comment by ThemInspectors** [comment]
which webserver software do you use?

**Comment by HappyHarm** [comment]
@samerton That worked thanks!
