### ISSUE TITLE
Disable force HTTPS without using web control panel

### ISSUE THREAD

**Issue by ImPapi** [NamelessMC/Nameless#1611]
Hello,

I recently tried using Cloudflare as a proxy for SSL, but it just broke the website.
I changed the general settings so that it forces https, and www.
Is there any way to change these settings from file, because I get this error while loading the website:
`www.domain.net refused to connect.`

Thanks.

**Comment by Derkades** [comment]
Try deleting the `cache/033f3da34ae9ec9661072ab0897ddf7ed642de3f.cache` file

**Comment by ImPapi** [comment]
No, that didn't work.
Also, I've removed Cloudflare as a proxy so I'm not using it anymore.

**Comment by samerton** [comment]
In case force www is also breaking the site you can delete the file `cache/a48fdb02e34b9602632d13dd91f0536d3b9bb559.cache` too.

**Comment by ImPapi** [comment]
> In case force www is also breaking the site you can delete the file `cache/a48fdb02e34b9602632d13dd91f0536d3b9bb559.cache` too.

Thanks, that worked.
