### ISSUE TITLE
Cant upload avatar

### ISSUE THREAD

**Issue by Alemiz112** [NamelessMC/Nameless#1613]
**Describe the issue**
Users cant upload own avatar. After user choose image and press "Submit" button in profile settings page he is redirected to `/core/includes/image_upload.php` and stucked with `403 Forbidden` error.

**NamelessMC version**
Im using latest version: `2.0.0-pr7`

Thanks!

**Comment by samerton** [comment]
Can you make sure the `uploads` directory on your web server is recursively writable for the PHP process (so all folders inside there are writable too)

**Comment by Alemiz112** [comment]
This are current permissions for `/upload` folder: `drwxrwsrwx  7 www-data www-data 4.0K Jan  5 18:01 uploads`.

Permissions inside folder:
```
drwxrwsrwx 3 www-data www-data 4.0K Feb 21 14:49 avatars
drwxrwsrwx 2 www-data www-data 4.0K Jan  5 18:01 backgrounds
drwxrwsrwx 2 www-data www-data 4.0K Jan  5 18:01 banners
-rwxrwxrwx 1 www-data www-data    0 Feb 20 19:13 placeholder.txt
drwxrwsrwx 2 www-data www-data 4.0K Feb 21 15:19 profile_images
drwxrwsrwx 2 www-data www-data 4.0K Feb 21 15:29 template_banners
-rwxrwxrwx 1 www-data www-data 1.4K Feb 20 19:13 upload_image.php
```

**Comment by samerton** [comment]
Can you try enabling debugging (StaffCP -> Configuration -> Maintenance) just to see if that results in a different page than the 403 forbidden error?

**Comment by Alemiz112** [comment]
It comes with this error: `
[Mon Feb 24 14:17:20.933570 2020] [access_compat:error] [pid 16] [client 192.168.2.100:51608] AH01797: client denied by server configuration: /var/www/html/core/includes/image_upload.php, referer: https://cubedmc.eu/user/settings/`

**Comment by Alemiz112** [comment]
This is my current settings of Apache2 (`php:7.3-apache`) running in docker container:

```
<VirtualHost *:80>
        ServerAdmin alemiz@cubedmc.eu
        DocumentRoot /var/www/html

        <Directory /var/www/html>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/site-a_error.log
        CustomLog ${APACHE_LOG_DIR}/site-a_access.log combined
</VirtualHost>
```

**Comment by samerton** [comment]
Do you have Apache's `mod_security` installed and enabled on the server?

**Comment by Alemiz112** [comment]
No. This is my installed modules:
```
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)
```

**Comment by Alemiz112** [comment]
Htaccess file:
```
Options +FollowSymLinks
  Options -MultiViews
  Options -Indexes
  RewriteEngine on
  IndexIgnore *
  RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
  RewriteRule ^(.*)$ - [E=BASE:%1]

  RewriteCond %{REQUEST_FILENAME} !-d

  # Disabled
  # RewriteRule ^(.+)/$ $1 [R=301,L]

  RewriteRule ^avatar/([^/]+)/([^/]+)/(f|l|r|b|front|left|right|back)/?$ %{ENV:BASE}core/avatar/face.php?u=$1&s=$2&v=$3
  RewriteRule ^avatar/([^/]+)/(f|l|r|b|front|left|right|back)/?$ %{ENV:BASE}core/avatar/face.php?u=$1&v=$2
  RewriteRule ^avatar/([^/]+)/([^/]+)/?$ %{ENV:BASE}core/avatar/face.php?u=$1&s=$2
  RewriteRule ^avatar/([^/]+)/?$ %{ENV:BASE}core/avatar/face.php?u=$1 [L]

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d

  RewriteRule ^(.*)$ %{ENV:BASE}index.php?route=/$1  [NC,L,QSA]
  #RewriteRule ^(.*)$ ./index.php?route=/$1 [NC,L,QSA]

  # Prevent access to template files
  <files "*.tpl">
    Deny from all
  </files>
```

**Comment by samerton** [comment]
What if you navigate directly to `yoursite.com/core/includes/image_upload.php` ?

**Comment by Alemiz112** [comment]
It redirects me to `mysite.comcore/core/includes/image_upload.php` with no slash between `.com` and `core`

**Comment by Alemiz112** [comment]
Any ideas?

**Comment by samerton** [comment]
Not sure at the moment I'm afraid. Do you get errors when a background image (StaffCP -> Layout -> Images)?

Also, are there any files already inside uploads/avatars?

**Comment by Alemiz112** [comment]
Hi, yes I do get errors with background settings too:
![image](https://user-images.githubusercontent.com/45739737/75904573-c1796680-5e43-11ea-9091-dd988382913a.png)

Contents of uploads/avatars:
```
root@23623ff809f0:/var/www/html/uploads/avatars# ls
defaults  placeholder.txt
```

**Comment by samerton** [comment]
All similar questions online point to issues with the directory's permissions or mod_security. I'm afraid I am not sure as this is a server configuration issue.

**Comment by Alemiz112** [comment]
Okay. If I would have bad directory's permissions how can I fix it?

**Comment by Alemiz112** [comment]
I found that in `core/` was `.htaccess`. I removed and small progress can be seen. Now I can access `/core/includes/image_upload.php` but this error comes out:
```
Fatal error: Uncaught Error: Call to undefined function BulletProof\exif_imagetype() in /var/www/html/core/includes/bulletproof/bulletproof.php:105 Stack trace: #0 /var/www/html/core/includes/bulletproof/bulletproof.php(374): BulletProof\Image->getImageMime('/tmp/phpBPNVpa') #1 /var/www/html/core/includes/image_upload.php(65): BulletProof\Image->upload() #2 {main} thrown in /var/www/html/core/includes/bulletproof/bulletproof.php on line 105

Fatal error: require_once(): Failed opening required '../../error.php' (include_path='.:/usr/local/lib/php') in /var/www/html/core/classes/ErrorHandler.php on line 49
```

**Comment by samerton** [comment]
Not sure why you had a `.htaccess` file in the core directory, it doesn't exist in Nameless: <https://github.com/NamelessMC/Nameless/tree/v2/core>

As for the new error, you are missing the PHP `exif` module:
```
sudo apt-get install php-exif
sudo service apache2 restart
```

**Comment by Alemiz112** [comment]
Wired issue. Anyway thanks for help. I think I can close it.
