### ISSUE TITLE
Always says "There are players online" even when there aren't.

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless#1615]
**Describe the issue**
On all pages in the header, it always says "There are players online" even when there aren't. No number counts like it is supposed to either. Meanwhile, the status page displays no users online

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup server connection on the site (using a bungee instance and other servers)
2. See issue on all pages.

**Expected behaviour**
For it to list how many players are online when there are players online and to tell when there arent.

**Screenshots**
![image](https://user-images.githubusercontent.com/28664144/75402545-1d3b7100-58d3-11ea-89ee-1d67ed937099.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Comment by samerton** [comment]
Please update your backend Spigot servers in the StaffCP to have the "Parent server" option set to none, there is a bug in the latest pre-release (since fixed by https://github.com/NamelessMC/Nameless/commit/4c9fa59b9ccf175fb8b1013ba90ff5138cee5034) involving parent servers.

**Comment by ZandercraftGames** [comment]
Ahh. It is fixed and says 0 players online. Thanks :D

**Comment by samerton** [comment]
No problem :)
