### ISSUE TITLE
Custom Profile Fields During Registration

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless#1616]
**Describe the issue**
When setting a field to "Required" in "Custom Profile Fields", it describes the required option as "Required fields must be filled out by the user, and they will appear during registration." The issue, however, is that it does not appear during registration.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use DefaultRevamp theme on Nameless Pre-release 7
2. Go to "Custom Profile Fields?"
3. Create a custom field and set it to "Required"
4. Go to the registration page
5. Fields do not appear on the page

**Expected behaviour**
Fields should appear on the registration page.

**Screenshots**
![image](https://user-images.githubusercontent.com/28664144/75502824-f5ffa500-59a1-11ea-866d-f565417f74f5.png)
![image](https://user-images.githubusercontent.com/28664144/75502844-0748b180-59a2-11ea-8401-15161668b73c.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Comment by samerton** [comment]
The custom profile field system is currently incomplete and should be ready for the full v2 release

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/pull/1660/files

**Comment by samerton** [comment]
12c169a15a494c6c1c961b3a7ac0e6a3a0ab50c4
