### ISSUE TITLE
Email notifications configurable per event

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless#1618]
This feature would add a tab to the Account page that allows the user to configure what they want to receive emails for. Emails would include when a watched topic is posted to and other events like it.

**Comment by ZandercraftGames** [comment]
Another email option would be to get email notifications when messages are received through PMs or when any alerts are received.

**Comment by puttydotexe** [comment]
If a user has multiple emails on the account, they will have to select a verified email as there "primary" email and that will be used to send emails such as password resets. Any additional emails could be used to display on there profile almost like a custom profile field or perhaps as @ZandercraftGames mentioned, a new feature to get email-based notifications to the selected secondary email. 

There would more than likely have to be a lot of safe checking, however;
Making sure users can't log in with an email that isn't selected as there "primary" email,
That password reset requests can't be sent using an email that isn't the user's "primary" email.
And I'm sure there's a load more things however this is all I can think of at a moment's thought.

Just a few additions.

**Comment by Derkades** [comment]
Maybe I'm not reading it correctly, but I think this issue is not about allowing users to add multiple email addresses to their account, but rather about more email notification events. You may want to create a new issue for your idea.

**Comment by ZandercraftGames** [comment]
^

**Comment by puttydotexe** [comment]
"Another email option would be to get email notifications when messages are received through PMs or when any alerts are received."

I simply quoted @ZandercraftGames, and built upon his idea in a manner that would make this feature much more stable so that it could be a feature in the future.

**Comment by Aberdeener** [comment]
0f497117ed17c7a051d02d9306c773d5e7b8ab58 adds a toggle whether to receive email updates for forum topic replies or not. Thanks!
