### ISSUE TITLE
MCASSOC | When enabled/setup displays a blank box upon sign up

### ISSUE THREAD

**Issue by MackenzieMolloy** [NamelessMC/Nameless#1619]
* What kind of issue is it (Question, Bug, etc.)?

Bug

* In which version of NamelessMC did it occur (1.x.x)?

2.0.0-pre7

* How would you describe the issue?

When MCASSOC is enabled, once new users have passed the main registration page, it leads them to a page asking them to follow the instructions but only a blank box is shown, preventing them for signing up

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?

https://craftastrophe.co.uk/ click register, and filling the boxes, and then it will bring you to a page saying something like "Follow these instructions" with a blank box under neath.

* Do you have an idea how or where the issue occurs?

I'm using pebblehost web hosting, and I quote what they told me;

"The [MCASSOC] iframe has no source so it's not being loaded from anywhere, who added the verification system into Namelessmc? https://i.jay.network/X00ole.png?"

"...well that has no src so there's no way for it to work..."

* What Modules are you using ?

None

* What theme are you using ?

None

**Comment by samerton** [comment]
Can you check your browser console (F12) for errors?

**Comment by MackenzieMolloy** [comment]
No errors

**Comment by samerton** [comment]
Can I sign up to take a look at the issue?

**Comment by MackenzieMolloy** [comment]
sure

**Comment by MackenzieMolloy** [comment]
Any updates?

**Comment by alexis-evelyn** [comment]
I can confirm that this issue does exist and that the iframe has no source link.

![Screen Shot 2020-03-19 at 3 37 26 PM](https://user-images.githubusercontent.com/6305346/77107796-9a9c6200-69f7-11ea-997e-607d3f5249f8.png)

**Comment by samerton** [comment]
Thanks, fixed in fb6e85baafb5fba7acfe43f4261395c88a239525
