### ISSUE TITLE
Discord New Topic Hook

### ISSUE THREAD

**Issue by Alemiz112** [NamelessMC/Nameless#1621]
**Describe the issue**
I have set Discord Web-Hook but when new topic is created web-hook is not sent. I have configured it in "Social media menu" to send when new user or topics is created.

![image](https://user-images.githubusercontent.com/45739737/76794078-950c0580-67c6-11ea-9da3-5f8eb8180591.png)

**Comment by samerton** [comment]
You also need to edit each forum you want notifications for and enable the webhook option.

**Comment by Alemiz112** [comment]
Lol. I set as default to have this enabled.
