### ISSUE TITLE
Craftingstore Integration in v2

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless#1622]
Craftingstore had integration built-in to the v1 version of NamelessMC. This would add a similar integration for Craftingstore to the v2 version of NamelessMC. It would be under the integrations section for Minecraft or a new category for "Donations"

**Comment by samerton** [comment]
This is planned as a new separate module, similar to the Tebex module currently available.

**Comment by Aberdeener** [comment]
Completed by the official craftingstore team!
