### ISSUE TITLE
Nickname Profile Settings

### ISSUE THREAD

**Issue by puttydotexe** [NamelessMC/Nameless#1625]
**Describe the issue**
I can remove what's displayed via profile settings through editing settings.tpl, however, cannot remove the "Nickname" field very easily as it's classed and displayed as "$PROFILE_FIELDS" and removing the foreach for this would remove the user's ability to change any custom profile fields I define. 

**To Reproduce**
1. Go to '/user/settings/'
2. Scroll down to 'Nickname'

**Expected behavior**
Being able to disable a users ability to use Nickname's via a module like disabler or via permissions.

**Screenshots**
https://gyazo.com/c53281808278e433ae375e6e684b5464

**NamelessMC version (from AdminCP -> Overview)**
2.0.0 pre-release 7

**Comment by samerton** [comment]
There should be a group permission under "UserCP" for nicknames:
<img width="1666" alt="Screenshot 2020-03-27 at 17 38 55" src="https://user-images.githubusercontent.com/1812544/77784115-e7181b00-7051-11ea-9bff-b30631824b77.png">

Disabling this will remove the nickname field.

**Comment by puttydotexe** [comment]
Ah, I searched high and low for that, even using the GitHub search feature to scout the source for anything related to it. Thanks once again.
