### ISSUE TITLE
Custom widgets 

### ISSUE THREAD

**Issue by MichalPetricek123** [NamelessMC/Nameless#1627]
Hi, I wanna add custom widget into my web. Can you please tell me where are widgets saved ? 

Thanks for help

**Comment by samerton** [comment]
Unfortunately we don't have any docs for this currently.

Widgets can currently only be created with code, the ability to create a HTML widget will be coming in an update soon.

Widget code can be found in the **modules/*module*/widgets** folder typically, so you'd have to create your own module (see [here](https://namelessmc.com/resources/resource/29-example-module/) for an example) and an example widget is [here](https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/widgets/TwitterWidget.php).

**Comment by samerton** [comment]
If you have any more questions, please feel free to re-open
