### ISSUE TITLE
No PHP MySQL Extention

### ISSUE THREAD

**Issue by rissoru1592** [NamelessMC/Nameless#1629]
**Describe the issue**
After I uploaded all NamelessMC files into the website directory, and I tried to install process.  I got an error saying that I don't have PHP MySQL Extention. I am using a hosting website, and don't know what to do.

**Expected behaviour**
Continue to install NamelessMC.

**Screenshots**
https://user-images.githubusercontent.com/61929744/78468101-b5d0d680-7746-11ea-99bd-9e01da394b05.jpg

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0 pre-7

**Comment by rissoru1592** [comment]
I tried installing latest v1, I could intsall it.

**Comment by Derkades** [comment]
Contact your host, ask them to install the PHP MySQL extension

**Comment by samerton** [comment]
Specifically you need either PHP's `mysql` or `mysqlnd` package installed

**Comment by rissoru1592** [comment]
Thank you very much for your prompt reply, I changed my server PHP version from 7.3.14 to 5.6.40 and it worked! Thank you again!
