### ISSUE TITLE
Prefix for ranks

### ISSUE THREAD

**Issue by AlliedCore** [NamelessMC/Nameless#163]
So for instance we have the admin prefix as <span class="label label-danger">Admin</span>. How would I make prefix for other ranks such as staff and donations? What would be the code?

**Comment by samerton** [comment]
The badges next to the rank names use Bootstrap's label component by default, you can find a list of all labels available plus the code to use them [here](http://getbootstrap.com/components/#available-variations).

If you want to make your own code, you'll need to copy the CSS from the Bootstrap labels, rename them and change the `background-color` attribute within your theme's custom.css file. You can then refer to your newly made class in the Group HTML input in the AdminCP's Groups tab.
