### ISSUE TITLE
Image upload error not informative

### ISSUE THREAD

**Issue by Permanently** [NamelessMC/Nameless#1632]
**Describe the issue**
When I go to upload a banner to my profile, I get _"Invalid input"_. I resized my photo down and then got a message saying _"Image height/width should be less than ' 2000 \ 2000 ' pixels"_ which is a lot more clear than the first message I got. However, the first message should still probably be fixed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://example.com/profile/ExampleUsername/
2. Click on [this](https://lucent.host/YlsJap.png)
3. Click 'Browse', and upload a large image (in my case, my image was 11808x2400, no joke)
4. Click 'Upload', see _"Invalid input"_

**Expected behaviour**
To see a more informative warning, such as the "Should be less than 2000x2000 pixels" warning

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC version 2.0.0-pr7

**Additional information**
Would like it if we could also be able to choose what limits are on the images such as our own dimension and size limits. As well, would prefer a more formal popup when getting warnings about images being too big - thanks :D

**Comment by Aberdeener** [comment]
Cannot reproduce :(
Chances are this was fixed since this issue was made.

Seems like the only place where the "Invalid Input" message is returned is if no input is given... 
https://github.com/NamelessMC/Nameless/blob/54e3e3ab31d9da66bd038449c1080be98c9936f7/core/includes/image_upload.php#L167
