### ISSUE TITLE
Google reCaptcha interferes with two-factor authentication on login

### ISSUE THREAD

**Issue by Permanently** [NamelessMC/Nameless#1633]
**Describe the issue**
My site has Google reCaptcha enabled. Whilst registering a dummy user in order to test groups, I discovered that I couldn't log back into my administrator account due to there being an "Invalid reCAPTCHA response." However, logging into the dummy user seems to work perfectly fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup a NamelessMC site with Google reCaptcha fully enabled.
2. Create a dummy account and enable two-factor authentication.
3. Log out, then try to log back in.

**Expected behaviour**
Well, to log in normally. Nothing else I can say.

**Screenshots**
With two-factor authentication: https://i-like-to-be.flirtatio.us/jyQCeh.gif
Without two-factor authentication: https://i-like-to-be.flirtatio.us/7vWzO3.gif

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC version 2.0.0-pr7

**Comment by samerton** [comment]
Fixed in de6423cfd21f8eea7a8cbd5164527f2a444dda9b
