### ISSUE TITLE
hey how i change it from saying Infractions at top

### ISSUE THREAD

**Issue by AtomicGaming666** [NamelessMC/Nameless#1634]
hey in the navbar it say Infractions i want it to say bans

**Comment by samerton** [comment]
If you're using Nameless v1, you can change the text in the file addons/Infractions/language.php, and if you're using v2 you can change it in the file modules/Infractions/language/*language*/infractions.php

**Comment by samerton** [comment]
I'll mark this issue as closed, if you have any other questions please feel free to re-open.
