### ISSUE TITLE
Only show redirect warning when leaving forum

### ISSUE THREAD

**Issue by 1stian** [NamelessMC/Nameless#1638]
Don't show a warning when redirecting on the same website, only when actually leaving the website for a different domain for the forum redirect.

Warning when: domain.com redirects to domain2.com
And no warning when domain.com redirect to domain.com/help

**Comment by Derkades** [comment]
> Why would you want a warning if you are staying on the same website/domain?
You wouldn't, that's why this issue exists. The warning should only be disabled when redirecting away from the forum website. Apparently right now it shows a warning for any link.
