### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Lmmb74** [NamelessMC/Nameless#164]
Hi, I would like nameless to have:
PermissionsEx ranks syncronization,
MyBB users syncronization and
the ability to enable/disable user registration & forums.

Is there any way to make this possible with the actual configurations?

**Comment by ThemInspectors** [comment]
PEX is already plannned I think you should reply to this thread [here](https://github.com/NamelessMC/Nameless/issues/155) for feature requests

**Comment by samerton** [comment]
PermissionsEx: Rank synchronisation is planned for the future, however I'm not sure how long it will take.
MyBB: Unfortunately there are no plans to allow integration with any other forum software, as Nameless is designed as a standalone package, and changing this would render most features useless. You can see [this post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-131#post-1442780) for advice on installing another forum software as an alternative.
Disabling registration + forums: It is already possible to disable registration (AdminCP -> Core -> Modules), however disabling the forums probably won't be possible, and the solution in the post linked above is probably your best option.

**Comment by samerton** [comment]
I'll go ahead and close this issue as the questions have been resolved.
