### ISSUE TITLE
Chinese compatible

### ISSUE THREAD

**Issue by Dmerican** [NamelessMC/Nameless#1640]
**Please describe the feature in as much detail as possible**
Hello, developers!
Could you make this project support Chinese announcement?
In the current version,If I use Chinese as an announcement, it will only show'????'
If I modify '?' to Chinese directly in MySQL database, the announcement on the homepage of the website is still '?'
![QQ截图20200424100452](https://user-images.githubusercontent.com/30787081/80167641-7db90700-8613-11ea-8e25-21f70b9aa3cd.png)
![QQ图片20200424100642](https://user-images.githubusercontent.com/30787081/80167675-95908b00-8613-11ea-84d7-deb9856f9d26.png)

**Comment by samerton** [comment]
Hi,

Unfortunately Nameless version 1 is not compatible with non-Latin characters.

You can try version 2 from here: https://github.com/NamelessMC/Nameless/releases/tag/v2.0.0-pr7
If using version 2, make sure you use the "Unicode" database character set in the installer.

**Comment by samerton** [comment]
I'll mark this as closed as v2 should have support, if you still experience issues with v2 please feel free to re-open.
