### ISSUE TITLE
invalid Token

### ISSUE THREAD

**Issue by kurtkraut2** [NamelessMC/Nameless#1643]
* What kind of issue is it (Question, Bug, etc.)?      **Invalid Token on Register**
* In which version of NamelessMC did it occur (1.x.x)? **1.0.21, merged from your git**
* How would you describe the issue? **When i try to register a new account it shows invalid token**
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? **you can try register at www.powercraft.com.br and here the images http://prntscr.com/s5m6ix**
* Do you have an idea how or where the issue occurs? **dont know, it happens without any change of site**
* What Modules are you using ? **the main modules, which comes with default instalation**
* What theme are you using ? customized theme, made by me

**Comment by samerton** [comment]
This can be a difficult one to debug, usually it's down to one of these two things:
- your web host is not saving sessions
- you are out of space on your web host

**Comment by kurtkraut2** [comment]
it happens with new users, but by example, with my account, i can login normally, but when someone try to register, get token error, is not about space, i've checked that, and about sessions, if my host dont save it, neither i could login too, did you agree? Have you discord o something what i can reach you to take a little chat?

**Comment by Aberdeener** [comment]
@kurtkraut2 Our official Discord is located here: https://discord.gg/QWdS9CB

**Comment by kurtkraut2** [comment]
is getting "invalid invite" already tried to join your discord before

**Comment by samerton** [comment]
The best bet is the Discord, what's your username on there?

You're right, logins would not work either if your web host was not saving sessions. This is a very strange issue, can you try joining the Discord again as it will be easier to diagnose?

**Comment by samerton** [comment]
Were you able to solve this issue @kurtkraut2?

**Comment by kurtkraut2** [comment]
Turned SSL on, it fixed by itself after SSL

 

De: Sam [mailto:notifications@github.com] 
Enviada em: sábado, 9 de maio de 2020 08:50
Para: NamelessMC/Nameless
Cc: kurtkraut2; Mention
Assunto: Re: [NamelessMC/Nameless] invalid Token (#1643)

 

Were you able to solve this issue @kurtkraut2 <https://github.com/kurtkraut2> ?

**Comment by samerton** [comment]
Very strange, I don't know why that happened, but I'm glad it's fixed now!

**Comment by kurtkraut2** [comment]
> https://discord.gg/QWdS9CB

could you please unban Nodio#8790

**Comment by samerton** [comment]
> > https://discord.gg/QWdS9CB
> 
> could you please unban Nodio#8790

Unbanned
