### ISSUE TITLE
Discord webhook line break

### ISSUE THREAD

**Issue by wert** [NamelessMC/Nameless#1646]
**Describe the issue**
Please describe the issue in as much detail as possible
Whenever doing a linebreak <br /> or <br> within a post

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup discord webhook
2. Make a post with a soft break and a hard break
3. Check discord

**Expected behaviour**
What were you expecting to happen? 
Add a linebreak in discord text

**Screenshots**
https://i.imgur.com/KNZKfsp.png - discord output
https://i.imgur.com/mdg2b3l.png - forums output

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/cd4218f56e762dd90f19ff4d415e24e8dd01974a
