### ISSUE TITLE
Log in with special characters

### ISSUE THREAD

**Issue by enno123** [NamelessMC/Nameless#1647]
If you register with special characters and then go to the profile you will only see a white page.

It would be best to block all special characters

**Comment by Aberdeener** [comment]
<img width="1270" alt="Screen Shot 2022-05-11 at 23 20 25" src="https://user-images.githubusercontent.com/26070412/167997455-26bd839c-fcca-4ac3-b1d2-6bd151379b52.png">

I have tried a few different special characters and cannot replicate this issue. I know it's been a long time, but if you recall the characters, please re-open this issue and I can test with those.

Thank you for the report 😄
