### ISSUE TITLE
Email setup

### ISSUE THREAD

**Issue by FunkiestPeak** [NamelessMC/Nameless#165]
Its not that i have an issue I only what to know how to setup the incoming and outgoing email function, and the email.php?

**Comment by samerton** [comment]
If you want to use SMTP, try the steps in [this post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-67#post-1017639), and if you want to use Gmail try [these steps](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-70#post-1036444) instead. After completing either of these, you need to head into the AdminCP -> Core -> Email and disable the "Use PHP mail() function?".

**Comment by samerton** [comment]
I'm going to close this issue for now, if you still have issues with the emails feel free to reopen.
