### ISSUE TITLE
NamelessMC URL Logo Size Won't Change

### ISSUE THREAD

**Issue by zyonyte** [NamelessMC/Nameless#1652]
**Describe the issue**
Please describe the issue in as much detail as possible
I've uploaded my new server logo to the "Logo URL" Section of the Layouts in StaffCP. And when checking my website it looks to have been reduced to 125x125px wide. I'm unsure as to why this has happened and need to make the image bigger.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to www.spiremc.com/forum/
2. Click on StaffCP
3. Scroll down to Layout
4. Upload an image in the "Logo URL" which is 3000x3000px
5. Check https://www.spiremc.com/forum/
6. The logo size is significantly smaller

**Expected behaviour**
What were you expecting to happen?
A much bigger logo, although there's not option to change it

**Screenshots**
https://www.spiremc.com/forum/ <-- The image is very small currently.
**NamelessMC version (from AdminCP -> Overview)**

**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
Hi,

I think the logo upload is a feature of your template, Nameless by default doesn't have a logo upload feature. Could you try contacting the template author?

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues please feel free to re-open
