### ISSUE TITLE
Visitors bypass "Can user see other topics?"

### ISSUE THREAD

**Issue by enno123** [NamelessMC/Nameless#1654]
If u get the permission "Can user see other topics?" in the settings of a forum type of all groups that are not supposed to see this (the ones which aren't logged in) can still see the posts.

**Comment by samerton** [comment]
This was intentional behaviour at the time, but I can change this for the next update.

**Comment by samerton** [comment]
The can view other users' topics permission has been added for guests to solve this issue https://github.com/NamelessMC/Nameless/commit/0ca96ced082e1d03a0e315b11eb8b91144d7a5c7
