### ISSUE TITLE
css is not updating 

### ISSUE THREAD

**Issue by abhiram555** [NamelessMC/Nameless#1655]
when i edit css (footer back ground color etc) my forms page is not updating to color that i set this is the error/bug how can i fix it please respond to me as soon as possible

**Comment by samerton** [comment]
This is probably a cache issue.

You can try clearing your browser cache, or perform a hard refresh with Ctrl+F5 whilst viewing the page, or even try a different browser.

If you use a service like Cloudflare, you will also need to purge the cache on there.

**Comment by abhiram555** [comment]
yea i fixed it

**Comment by samerton** [comment]
Glad the issue is solved

**Comment by abhiram555** [comment]
thank you so much for responding

**Comment by abhiram555** [comment]
still i cant change

**Comment by samerton** [comment]
@abhiram555 can you send me a link to your website, and can you tell me what you are trying to change?

**Comment by abhiram555** [comment]
redcrafts.in

**Comment by samerton** [comment]
@abhiram555 thanks, what is the css you are trying to change on the website?

**Comment by abhiram555** [comment]
i am changeing header clolor in custom.css

**Comment by samerton** [comment]
@abhiram555 if you mean the navbar colour, that is showing up as red for me. Is this correct? If so, the problem is with your browser’s cache.

**Comment by abhiram555** [comment]
yea that what i want but i try  cntrl+f5
then its okey thank you very much

**Comment by abhiram555** [comment]
background i mage is not woking

**Comment by abhiram555** [comment]
can you fix it

**Comment by abhiram555** [comment]
nevermind i will add it in css

**Comment by abhiram555** [comment]
shit still not loading

**Comment by samerton** [comment]
@abhiram555 can you try with a different browser?

**Comment by abhiram555** [comment]
its fixed thank you for helping me thank you so much
