### ISSUE TITLE
Fatal error with "Smarty"

### ISSUE THREAD

**Issue by TerThesz** [NamelessMC/Nameless#1656]
After the last step an error saying "Config unwritable" will pop up and after re-opening the website this will show:
![image](https://user-images.githubusercontent.com/60745997/81709452-2bc90b80-9472-11ea-9bfe-0868f3480c8e.png)

Btw: sorry for my English

**Comment by samerton** [comment]
Hi, your cache and cache/templates_c folders (and all files inside) need permissions changing so PHP can write to them

**Comment by TerThesz** [comment]
How can I do that?

**Comment by samerton** [comment]
If you are using a web host, you should ask them as it depends on what their setup is. 
If they use cPanel, I think you can right click on the files and folders in file manager and change permissions in there, by checking all boxes so the numbers at the bottom equal 777

**Comment by samerton** [comment]
I'll mark this issue as closed, if you have any more questions please feel free to re-open.
