### ISSUE TITLE
Can't edit a topic

### ISSUE THREAD

**Issue by Enz0Z** [NamelessMC/Nameless#1657]
**Describe the issue**
I found that if an admin post a topic, and in that forum permission they don't have "Can create replies?", they can not edit their own topic.
As you can see in the images before, if you have the permission you can edit your own topic, but if you don't have the permission, you got redirected to the topic list of the forum.

**With the permission**
![image](https://user-images.githubusercontent.com/48935178/81758985-c25cf300-9499-11ea-85a6-e0b0da9fe02e.png)
![image](https://user-images.githubusercontent.com/48935178/81759002-d0127880-9499-11ea-85f9-5a79d15e68ba.png)
![image](https://user-images.githubusercontent.com/48935178/81759015-e0c2ee80-9499-11ea-8fb9-44ec0054a125.png)

**Without the permission**
![image](https://user-images.githubusercontent.com/48935178/81759037-f0dace00-9499-11ea-9af3-817515cd4c1e.png)
![image](https://user-images.githubusercontent.com/48935178/81759088-19fb5e80-949a-11ea-9bd4-a7cfea20e6d7.png)
![image](https://user-images.githubusercontent.com/48935178/81759099-21bb0300-949a-11ea-98fa-43e9a788b309.png)

**Comment by samerton** [comment]
Should hopefully be fixed by more specific permissions: https://github.com/NamelessMC/Nameless/pull/1689
