### ISSUE TITLE
Issues: Staff Application & Updating

### ISSUE THREAD

**Issue by SkyPulse** [NamelessMC/Nameless#166]
When I try and add something to the staff app list it just refreshes the page and removes the content that I typed.

Other issue:
I extracted the 107.zip file in the ftp and when I click update it loads a page and says server error 500. 

Thanks,
Kaden.

**Comment by samerton** [comment]
A possible cause for your staff application issue is the "name" field input. I'm actually going to drop this in a future release, for now if you simply call each question "One", "Two" etc you should no longer have issues with the staff applications.

As for the upgrade issue, can you check your server's Apache logs for errors?

**Comment by SkyPulse** [comment]
Hello, this is a different person this time, but with the same issue. The "One, Two..." names seem to work, but there also seems to be a cap on how large a question can be. For example, I want to include a list of points at the beginning of the application, as a bit of an overview. Unfortunately, there is no option for simply writing text on the page. In a future update, could we be relieved from the very strict "Name, Question, Type, Dropdown Options" format?

**Comment by SkyPulse** [comment]
Where do I find the Apache logs? One more thing... I am unable to locate the The "One, Two..." names seem to work, but there also seems to be a cap on how large a question can be. For example, I want to include a list of points at the beginning of the application, as a bit of an overview. Unfortunately, there is no option for simply writing text on the page. In a future update, could we be relieved from the very strict "Name, Question, Type, Dropdown Options" format?

**Comment by samerton** [comment]
The Apache log location varies depending on your server configuration. If you're running Ubuntu/Debian, by default it's located at **/var/log/apache2/error.log**, and if you're running CentOS you'll need to check your **/etc/httpd.conf** file to see where they're stored. If you're simply running a web host, there should be an option in the control panel to view your error logs.

I'll rework staff applications for 1.2, and I can add the ability to insert text onto the page then.

**Comment by SkyPulse** [comment]
Hello again, **Ben** this time. I was able to locate the error logs, however the only error listed is from a bad favicon upload. Am I in the wrong place?

And, much thanks for addressing this. It's a bit inefficient, as we want to know as absolutely much as we can about an applicant's personality, and sometimes it can be hard to convey that simply through questioning.

**Comment by SkyPulse** [comment]
Hi, also I was wondering where I find the nav bar css.

**Comment by samerton** [comment]
Hi,

Unfortunately the error logs don't seem to contain the information we'd need to diagnose the issue, if you could head into the AdminCP -> Misc tab, and check "Enable error reporting?" before trying the upgrade script again, we may either get an error on the page which gave you a 500 error or errors may appear in the error log.

1.2 is most likely at least a month away, for now it'd be best to stick with a forum setup as you say.

The navbar template file is in **styles/templates/*Template*/navbar.tpl**, and any custom css can be placed in **styles/themes/*Theme*/css/custom.css**

**Comment by SkyPulse** [comment]
Okay Thanks! Here is the error. Also thank you for the support. I really appreciate it!


Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'last_username_update'' in /home/vol14_6/byethost24.com/b24_17782476/htdocs/core/classes/DB.php:68 Stack trace: #0 /home/vol14_6/byethost24.com/b24_17782476/htdocs/core/classes/DB.php(68): PDOStatement->execute() #1 /home/vol14_6/byethost24.com/b24_17782476/htdocs/core/classes/DB.php(241): DB->createQuery('ALTER TABLE `nl...') #2 /home/vol14_6/byethost24.com/b24_17782476/htdocs/core/classes/Queries.php(86): DB->alterTable('users', 'last_username_u...', 'int(11) DEFAULT...') #3 /home/vol14_6/byethost24.com/b24_17782476/htdocs/core/includes/updates/106.php(6): Queries->alterTable('users', 'last_username_u...', 'int(11) DEFAULT...') #4 /home/vol14_6/byethost24.com/b24_17782476/htdocs/pages/admin/update_execute.php(44): require('/home/vol14_6/b...') #5 /home/vol14_6/byethost24.com/b24_17782476/htdocs/index.php(76): require('/home/vol14_6/b...') #6 {main} thrown in /home/vol14_6/byethost24.com/b24_17782476/htdocs/core/classes/DB.php on line 68

**Comment by SkyPulse** [comment]
My last question. How do you change the color of the nav bar. Also, could you send me your donate link? I really like your dedicated and support throughout my issues.

**Comment by samerton** [comment]
It looks like, from the errors, you've installed a Nameless version in between 1.0.6 and 1.0.7. What I can do is modify the upgrade script for you which will only upgrade what's necessary. Could you tell me when you roughly installed Nameless?

As for changing the navbar colour, if you add the following to **styles/themes/*Theme*/css/custom.css**:

`.navbar-default {
  background-color: #fff !important;
}
.navbar-default .navbar-nav>.active>a {
  background-color: #000 !important;
}
`

replacing #fff and #000 with the colours you want (hex or css colours). I've pasted that code off the top of my head, hopefully it works.

The donate link for the project is [here](http://namelessmc.com/donate), thanks :)

**Comment by SkyPulse** [comment]
I installed it on April 1st. 

Thanks.

**Comment by SkyPulse** [comment]
I am having a issue when only the active tab button is highlighting. Here is a paste bin of my css. http://pastebin.com/K7Z3QYf8

Here is a link to my website. [http://skypulse.byethost24.com/](url)

**Comment by samerton** [comment]
Can you try disabling the inverse navbar (AdminCP -> Styles)?

I'm working on a customised upgrade script for you now.

**Comment by samerton** [comment]
If you replace the contents of **core/includes/updates/106.php** with [this code](https://gist.githubusercontent.com/samerton/2027ac1aee72844539568c4e48759b83/raw/4f30f9757886a19b2443545b69dab156f6c52de1/106.php), the upgrade process should run smoothly.

**Comment by SkyPulse** [comment]
I forgot my nav bar was on inverse, my bad. Also the code worked as well. Thanks for all of the help Samerton.

**Comment by samerton** [comment]
I'll close this now, and use #205 for further discussion regarding the staff applications module.
