### ISSUE TITLE
Vulnerabilities which require dependency updates

### ISSUE THREAD

**Issue by psharma04** [NamelessMC/Nameless#1662]
**Describe the issue**
NamelessMC uses versions of [JQuery (2.1.4)](https://snyk.io/vuln/npm:jquery?lh=2.1.4&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit) and [Bootstrap (4.0.0)](https://snyk.io/vuln/npm:bootstrap?lh=4.0.0&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit) which are vulnerable to XSS attacks. Updated versions of these libraries (3.5.1 for JQuery and 4.5.0 for Bootstrap) which have patched these issues are available. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a NamelessMC page in any Chromium browser
2. open Developer Tools
3. Open the Audits menu and "generate report"
4. Scroll to "Best Practices"

**Expected behaviour**
No outdated libraries were expected.

**Screenshots**
![Screen Shot 2020-05-16 at 13 15 55](https://user-images.githubusercontent.com/22587474/82109184-620ad180-9777-11ea-8163-99e05e0c751b.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Additional information**
There is also an issue where the call-to-home does not use the safest headers (see screenshot, or view on your own Chromium audit report under "Best Practices"). Solutions are provided by Chromium automagically.
![Screen Shot 2020-05-16 at 13 17 05](https://user-images.githubusercontent.com/22587474/82109207-8c5c8f00-9777-11ea-9512-a101f9d0c732.png)

**Comment by Aberdeener** [comment]
Thanks for pointing this out, hopefully Sam will get to this soon. If needed I can fix these things and PR.

**Comment by samerton** [comment]
46e65e465a20865ca983d1ed3c1ebd6fc636134c
