### ISSUE TITLE
Suggestion for pre8

### ISSUE THREAD

**Issue by Nuckerr** [NamelessMC/Nameless#1663]
Ok a couple of suggestions for pre8.

First off make it so you can make the home page redirect you to another site.
Secondly make the custom page editor a bit better (Maybe like the proboards custom page feature)

**Comment by Aberdeener** [comment]
Thank you for the ideas! Are you able to link an image of the proboards editor?

**Comment by NuckerTheDev** [comment]
Sign up to proboards.com. Its a bit hard to show all the features in a screenshot.

**Comment by Derkades** [comment]
> First off make it so you can make the home page redirect you to another site.

If you mean portal page, see this comment: https://github.com/NamelessMC/Nameless/issues/1035#issuecomment-395179305

**Comment by Nuckerr** [comment]
lol why did you respond to this now. What I want is to be able to redirect my home page to say a separately hosted website.

**Comment by Nuckerr** [comment]
I mean this suggestion was (as it seems to me) to be added in the future version and I just dont understand why almost 6 months later you just remove it

**Comment by Derkades** [comment]
It seems like a very niche feature out of scope for this project

**Comment by Nuckerr** [comment]
And so why did you do this 6 months later after it had already been sorted out

**Comment by Derkades** [comment]
> And so why did you do this 6 months later

I was looking through issues for any already resolved bugs, suggestions with vague titles and issues that are out of scope and will likely never be implemented. This keeps the issue list manageable.

**Comment by Nuckerr** [comment]
Well I feel like this suggestion should be added. Now you've just left a bad impression upon this software and I'l probably never use it again

**Comment by samerton** [comment]
@Nuckerr RE point #1, this is already possible either by editing the template and adding a JavaScript redirect, or creating a custom page with the same path as the homepage (to override it) and setting that up as a redirect page.

As for the custom page editor, this can maybe be improved one day but for now it's only intended as a basic HTML system, anything more complex would require a new module.
