### ISSUE TITLE
Discord Webhook Resets Itself

### ISSUE THREAD

**Issue by A248** [NamelessMC/Nameless#1667]
**Describe the issue**
The discord server ID seems to mysteriously reset itself after a while. When I return to the site after a couple of weeks it is gone. I've found that this often happens after the host machine is restarted. After I re-add the same server ID, the webhook re-appears.

Since this started happening reliably I figured it best to report. None of the other settings revert, however, which is why I find this odd.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable the Discord webhook widget (Layout > Modules)
2. Add server ID
3. ... wait some time / restart host machine
4. Return to the site to find that the server ID is reset. Nameless reports:
```
The widget is disabled for the specified Discord server. Please go to the 'Widget' tab in your Discord server settings, and ensure the Discord widget is enabled and that the ID is correct.
```

**Expected behaviour**
Server ID persists like all other settings.

**Screenshots**

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Additional information**
I searched the existing issues but no one else seemed to have this problem.

**Comment by Govindass** [comment]
I can confirm this, I've noticed it many times

**Comment by Aberdeener** [comment]
I will look at a possible different way at storing the ID and might make a PR

**Comment by Aberdeener** [comment]
This has not happened to me in ages, closing now - but can be reopened if needed.

**Comment by partydragen** [comment]
Believe he talk about the cache issue with is still a issue

**Comment by partydragen** [comment]
It might actually be fixed in pr13, as its no longer cached after the discord part rewrite but it should be cached thought but requery if the data no longer exist
