### ISSUE TITLE
Single file installer

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1668]
One installer php file that downloads and extracts the zip file. Users would only need to upload one file to their webserver, this is way faster than extracting the zip file on a local machine and uploading it over FTP.

![image](https://user-images.githubusercontent.com/15892014/82501204-2b291880-9af5-11ea-835f-6167eca89b34.png)
![image](https://user-images.githubusercontent.com/15892014/82501301-527fe580-9af5-11ea-84cb-d30cef6ece74.png)
![image](https://user-images.githubusercontent.com/15892014/82501507-ab4f7e00-9af5-11ea-934d-75cc03b11cf0.png)
![image](https://user-images.githubusercontent.com/15892014/82501599-cc17d380-9af5-11ea-9a13-3f030bcc4b44.png)

**Comment by Aberdeener** [comment]
Great idea. If Sam doesn't get to this I can probably

**Comment by ConnorOfficial** [comment]
Great

**Comment by StormyIceLeopard** [comment]
Curious, why not upload the .zip file then extract it on the host machine?

**Comment by Aberdeener** [comment]
Because many people who use nameless cannot figure out how to extract a zip
over ftp/ssh, and then complain about the long wait time for 2600+ files :p

**Comment by BaxAndrei** [comment]
I think it's a good idea, I saw this at PrestaShop as well.

**Comment by Derkades** [comment]
:tada: https://github.com/NamelessMC/Nameless-Installer
thanks @Aberdeener
