### ISSUE TITLE
Endless Redirect caused by force ssl

### ISSUE THREAD

**Issue by Destranix** [NamelessMC/Nameless#1669]
Some scripts(core/init.php) try to verify if HTTPS is enabled or not by reading the global $_SERVER["HTTPS"]-variable.

This variable is not set in every case, what leads to an endless redirection when SSL is forced.

This could be solved by a possible more reliable implementation of the HTTPS-check, e.g. by using secure cookies or by checking several $_SERVER-variables for their existence and value.(As seen [here](https://stackoverflow.com/questions/5100189/use-php-to-check-if-page-was-accessed-with-ssl))

(Be aware, that using secure cookies might give the client the possibility to fake the existence of an SSL-encryption.)

**Comment by KermanIsPretty** [comment]
Are you using Cloudflare?

**Comment by Destranix** [comment]
It's not my server. But yes, Cloudflare was used.

Is this relevant? Does Cloudflare, whyever, not connect using SSL?

But even if: There are definitly constallation, in which the $_SERVER["HTTPS"] variable is not set but HTTPS is enabled.

**Comment by samerton** [comment]
The cause of the issue is when Cloudflare's Flexible SSL is used.

This is because the flow of the request works like this:

Browser ---> Cloudflare is https
Cloudflare ---> Web server is not https

so by the time the web server is hit, the request is not https. As a result, `$_SERVER['https']` is not set. I think in this instance it's best to use Cloudflare's page rules to redirect instead, and make it easier within Nameless to disable force HTTPS if it breaks.

**Comment by Destranix** [comment]
> I think in this instance it's best to use Cloudflare's page rules to redirect instead, and make it easier within Nameless to disable force HTTPS if it breaks.

This seems to be a good idea.

**Comment by KermanIsPretty** [comment]
@samerton Maybe should add an error after 100 tries that is displayed, and what to do to fix it. This seems to be a very common issue.

**Comment by NicoGronert** [comment]
I have the same error. How can I fix it? Because I can't even access my panel.

**Comment by NicoGronert** [comment]
By the way, I am using Cloudflare Flexible SSL.

**Comment by Destranix** [comment]
@NicoGronert 

You cann add the following line to your /core/init.php to make the interface accessible again:
`$_SERVER["HTTPS"] = "on";`

After adding, this you are able to access the interface again and disable the "Force SSL"-Option.

After disabling the option, the added line should be removed, cause otherwise some parts might aussume that there is a secure connection event though there isn't.

**Comment by Destranix** [comment]
@KermanIsPretty 

The error should not be recognizable by the server itself. So it might be hard to cound that tries.

Possibly a test in the initialization phase/after changing the "Force SSL"-Option and/or a hint in the FAQ would be a better approach.

A test would possibly look like:
1.) Force SSL-Option ha been enabled
2.) Redirect to http://www.index.php?route=/testpage.php.
3.) If the testpage is not called withintimeout/x calls by an administrator, then the "Force SSL"-Option gets disabled and the administrator is informed about by a error message.

**Comment by A248** [comment]
If you're using flexible SSL just disable Nameless's Force SSL redirect. So long as your DNS record goes through CloudFlare (with the orange cloud) CloudFlare will enable and redirect to SSL and you'll see the green lock.

Of course, flexible SSL does not actually make the full connection SSL. See https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options

**Comment by ANDREI12333** [comment]
@Destranix Thank you! It worked for me.
