### ISSUE TITLE
Search bar for Template Editor

### ISSUE THREAD

**Issue by TheRobLP** [NamelessMC/Nameless#1670]
Basically a search function for the template editor if you want to find a specific code snippet fast. It would include a bunch of functions, for example limiting where to search (folders and/or files). I think this would be awesome to have and a really big Quality of Life improvement for website creation.

**Comment by Aberdeener** [comment]
Decent idea, though not too realistic/needed. I should hope if youre editing or creating a template you would just use an IDE of some sort, as they include features like this plus much more.

**Comment by TheRobLP** [comment]
uh... I am going to be honest, I never thought about that before. I was just using the template editor all the time 🤣
