### ISSUE TITLE
Installer stuck on database step

### ISSUE THREAD

**Issue by psrcek** [NamelessMC/Nameless#1672]
**Describe the issue**
After clicking submit on the database info entry page in the installer the following page is displayed (see screenshots). Reloading the page does not fix the issue. No tables are created in the provided database. Host, user, password and database name is verified to be correct.

**To Reproduce**
Steps to reproduce the behaviour:
1. `docker run -p 8080:80 -d daweedpanic/php-namelessmc:latest`
2. http://localhost:8080/easy-install.php
3. continue -> v2.0.0-pr7 -> proceed
4. New installation -> proceed
5. Enter database information -> Submit
6. See error (see screenshots)

**Expected behaviour**
I was expecting my database to be set up and the installer to continue.

**Screenshots**

![image](https://user-images.githubusercontent.com/13370323/83206839-0e728d80-a152-11ea-9202-5c76e7257ba4.png)

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pr7

**Comment by psrcek** [comment]
So docker containers basically work like virtual machines without actually being virtual machines. instead they use Linux kernel namespacing. Thus any software runs the same and is independent of the Linux distribution you are running and anything else you might have installed on your system that might mess up running software.

On that note, yes you have access to the filesystem.

![image](https://user-images.githubusercontent.com/13370323/83294765-24359080-a1ee-11ea-8eca-f6ce7531cfdd.png)

I get no additional info on that page, the same as the screenshot in the OP.

If you want I can hop on discord or something to debug this.

**Comment by samerton** [comment]
Ah sorry, can you also edit **install.php** in /var/www/html and remove these lines: https://github.com/NamelessMC/Nameless/blob/v2/install.php#L25-L26

**Comment by psrcek** [comment]
![image](https://user-images.githubusercontent.com/13370323/83296095-68299500-a1f0-11ea-9eb7-a758671f8205.png)

you don't list mysqli as a dependency? why is it required then?

![image](https://user-images.githubusercontent.com/13370323/83296150-88595400-a1f0-11ea-95e4-814bc1e0f526.png)

**Comment by samerton** [comment]
Looking at the code, Nameless checks for `mysql` or `mysqlnd`; apparently one of these doesn't contain mysqli so maybe that requirement can be tweaked down a bit.

**Comment by psrcek** [comment]
After installing mysqli it installed correctly, though I can't really see a reason why you'd be using both PDO and mysqli

**Comment by samerton** [comment]
Not sure on that one, I can remove mysqli in the future
