### ISSUE TITLE
[Front-End] Cookie Notice has a tiling notification icon background

### ISSUE THREAD

**Issue by casualinformee** [NamelessMC/Nameless#1676]
**Description**
On dark mode, using any dark mode extension (e.g. Dark Mode, Dark Reader) for Chrome/Firefox, the cookie notice background becomes dark, and the text white, but the image on there is also a white notification icon which is tiled, so the text can't be read unless you highlight it.

**To Reproduce**
1. Enable the Dark Reader browser extension or any other extension which switches the colors of divs, bodies etc. by changing CSS properties
2. Preferably open an Incognito tab/Private Window to make sure the cookie notice is displayed
3. Go to any website powered by NamelessMC with the default cookie notice enabled (example: namelessmc.com or simplecraft.org)
4. See the bug occur

**Expected behaviour**
The notification should've been easy to read, with a plain color background.

**Screenshots**
![normalAspect](https://user-images.githubusercontent.com/57112623/83336859-8ad6af00-a2bf-11ea-9d99-969f50a718a0.png)
![darkModeAspect](https://user-images.githubusercontent.com/57112623/83336858-8a3e1880-a2bf-11ea-9b96-ab1c29b98669.png)

**Additional information**
I found the piece of code which (likely) causes this problem, it's located in `toastr.min.css`, **CTRL+F** for `toast-info{background-image` and you should find that it's marked `!important`, which overrides the later appearance in the same file (**CTRL+F** for `toast-info{background-color`).

**Possible fixes**
Delete `!important` or add `background-repeat: no-repeat`?

**Comment by Derkades** [comment]
This is likely a toastr issue, not a nameless issue: https://github.com/CodeSeven/toastr/issues

**Comment by samerton** [comment]
Thanks for raising, I'll mark this as closed as I don't believe this is a Nameless issue, using Dark Reader you _should_ be able to apply an override to the CSS
