### ISSUE TITLE
ERROR SQLSTATE[22001]

### ISSUE THREAD

**Issue by oRealPadeiro** [NamelessMC/Nameless#1677]
**Describe the issue**
When some people try to acess my website, this appears: **SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1**

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter on my website
**Expected behaviour**
What were you expecting to happen?
work fine

**Screenshots**
https://prnt.sc/squfyf

**NamelessMC version (from AdminCP -> Overview)**
Last Version

**Comment by samerton** [comment]
For some reason, certain proxies seem to increase the length of IP addresses (yet to investigate), so I will increase the IP columns to a bigger length to fix this.

**Comment by samerton** [comment]
Increased for new installations in https://github.com/NamelessMC/Nameless/commit/81fdedcd315b0a859c79f5464c48a85559e81ded

Existing pre-release installations will need to use a tool like phpMyAdmin to modify the database and change the following:
`nl2_logs` table - change the length of `ip` to 128
`nl2_online_guests` table - change the length of `ip` to 128
`nl2_posts` table - change the length of `ip_address` to 128
`nl2_users` table - change the length of `lastip` to 128
`nl2_users_ips` table - change the length of `ip` to 128
