### ISSUE TITLE
SkinsRestorer support for nameless avatars

### ISSUE THREAD

**Issue by kacperleague9** [NamelessMC/Nameless#1678]
Like in topic

**Comment by Derkades** [comment]
So, the option to use player names instead of player UUIDs for displaying skins?

**Comment by kacperleague9** [comment]
dunno you can add a support to connect to skinsrestorer mysql database to get names and skins from here

**Comment by A248** [comment]
Would probably be well-suited to a module/addon

**Comment by kacperleague9** [comment]
Not really

**Comment by Derkades** [comment]
Closing this as it is out of scope for this project. Please create a module request in https://github.com/NamelessMC/Nameless-Modules
