### ISSUE TITLE
When topic title is Japanese, it does not show in the title and URL

### ISSUE THREAD

**Issue by ViaSnake** [NamelessMC/Nameless#1683]
**Describe the issue**
When write a forum topic title in Japanese, friendly URL don't show the title, nor do they show the page title.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create "あいうえお" topic.
2. Post.
3. See the URL and page title.

**Expected behaviour**
If the friendly URL, need to encode the Japanese title
For example, if the topic title is `あいうえお`, the URL should be `%E3%81%82%E3%81%84%E3%81%86%E3%81%88%E3%81%8A`.
The page title must display the topic title.

**Screenshots**
![title](https://user-images.githubusercontent.com/6961187/84492961-f702db00-ace1-11ea-8670-6c9ec82a638d.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Comment by samerton** [comment]
Would you prefer for the URL to be empty (like in your screenshot) or contain the encoded characters? Unless you're using the link somewhere which can decode the URL characters, having an encoded URL wouldn't look too nice

**Comment by Derkades** [comment]
Some browsers (Firefox, at least for spaces) display the decoded URL (unless you select the address bar).

**Comment by ethernetcat** [comment]
From an SEO perspective, I think it's probably a good to include the title in the URL.

You can leave the title empty if you are concerned about the complexity or appearance of the URL. However, it seems to me that all links need to be the same to be consistent

**Comment by Derkades** [comment]
It's common practise to only include latin characters in URLs, Discourse and XenForo do this too. I am not 100% sure how they handle arabic, chinese, japanese, korean, and other alphabets.

Sort of related discussion - How does NamelessMC handle characters with accents like á, â, å, ø? Are they not shown at all or replaced with regular latin characters?

**Comment by ethernetcat** [comment]
I don't know about Discourse, but ZenForo includes Japanese in the URL. However, there are some forum software and websites that do not include Japanese, Korean or Chinese in their URLs. It's true that there are many.
I think it's because those are software that was created when multi-byte characters were considered inappropriate for SEO.

I checked, but the "á, â, å, ø" didn't show all of them.

**Comment by Derkades** [comment]
"fix" for russian by translating to latin characters: https://github.com/NamelessMC/Nameless/pull/1862

Characters like `á, â, å` can be translated as well

**Comment by ethernetcat** [comment]
Japanese can be converted to Latin characters by [the romanization of Japanese](https://en.wikipedia.org/wiki/Romanization_of_Japanese). However, I have not seen any library or software that does this. Also, Japanese romanization is complicated and difficult to read. Probably not suitable for URLs.

Other languages that are difficult to convert to Latin characters are Chinese and Korean([CJK characters](https://en.wikipedia.org/wiki/CJK_characters)).

As an example, Romanize the title of this issue.
EN: `When topic title is Japanese, it does not show in the title and URL.`
JA: `トピックタイトルが日本語の場合、タイトルとURLには表示されません。`
Romanize: `topikkutaitoruganihongonobaai, taitorutoURLnihahyojisaremasen.`

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/103549933-6faccd00-4ea8-11eb-9b35-3531fe5c2ed6.png)
