### ISSUE TITLE
Suggestion | Multiple Webhook Support

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1685]
Allow the use of multiple/different webhooks per forum type Category/Forum.
When you go to domain.com/panel/forums/ and you edit a forum, you see an option "Include new topics from this forum in the webhook" I am thinking here is where you could define the webhook. This will allow for easy setup of multiple webhooks and maximize customizability.

**Comment by StormyIceLeopard** [comment]
So I found this [https://github.com/NamelessMC/Nameless/commit/d6a6fbec5711ddec386ebeaae25e80fe105bb15d](https://github.com/NamelessMC/Nameless/commit/d6a6fbec5711ddec386ebeaae25e80fe105bb15d) and this [https://github.com/NamelessMC/Nameless/issues/1639](https://github.com/NamelessMC/Nameless/issues/1639) but it is missing a critical feature. I downloaded the latest code from github branch v2 to test out this feature, downloaded on 6/15/2020. The use of selecting the webhook to be used. See the linked photo. Also /panel/core/hooks is missing from the menu. You can get their directly but there is no link to be found. I had to reference the code to find that page.
Photo: [https://imgur.com/a/pTy9lbU](https://imgur.com/a/pTy9lbU)

**Comment by samerton** [comment]
@partydragen how much of the multiple webhooks feature was implemented?

**Comment by partydragen** [comment]
Currently you can only create multiple webhooks for events types, Not per forum

But hmm, Cannot be that hard to add

**Comment by partydragen** [comment]
@samerton What about replace"Include new topics from this forum in webhooks?" to be a dropdown to select a webhook, if none is selected then its disabled ¯\_(ツ)_/¯

**Comment by StormyIceLeopard** [comment]
I like that, but then we lose the chance of selecting multiple webhooks. Reference the [photo](https://imgur.com/a/pTy9lbU) for how I thought it would work initially. Take the feature from multiple secondary groups from profiles and apply the same technique to webhooks.

**Comment by partydragen** [comment]
> I like that, but then we lose the chance of selecting multiple webhooks on the same forum topic. Reference the [photo](https://imgur.com/a/pTy9lbU) for how I thought it would work initially. Take the feature from multiple secondary groups from profiles and apply the same technique to webhooks.

Yea that should be easy to do aswell

**Comment by StormyIceLeopard** [comment]
I have determined that these remaining features would have to be implemented within the forum module itself, at least I think based on my understanding of the code.

**Comment by Aberdeener** [comment]
Forgot to assign to myself earlier.
Will be done in approx 9 hours. Thanks for the suggestion and help @StormyIceLeopard !

**Comment by Aberdeener** [comment]
Added
