### ISSUE TITLE
Avatar Service UUID Support

### ISSUE THREAD

**Issue by puttydotexe** [NamelessMC/Nameless#1686]
**Describe the issue**
Please describe the issue in as much detail as possible

**To Reproduce**
Steps to reproduce the behaviour:
1. Change avatar service to surgeplay or craftatar (Just examples, others may have the same issues)
2. Reload any page that pulls from specified avatar service.
3. Check console errors

**Expected behaviour**
Self explanatory 

**Screenshots**
https://gyazo.com/3d8ea37cf6aefe5a0bdfab4924a95ae6
https://gyazo.com/be0d69cc67bc98cfb133dde81d0ae8a4

**NamelessMC version (from AdminCP -> Overview)**
Latest clone from v2 branch.

**Comment by KermanIsPretty** [comment]
[It seems to already do this](https://github.com/NamelessMC/Nameless/blob/61e85bd1d4652446012f005b25edc1381e1c4d6d/core/classes/Util.php#L200), is this your theme?

**Comment by KermanIsPretty** [comment]
It seems that nameless or the template isn't using the UUID and using the username.
![image](https://user-images.githubusercontent.com/46640204/84784825-5dbd1880-afb0-11ea-9c62-c506d1d1d9d1.png)

**Comment by puttydotexe** [comment]
I'll take a look into it, thanks.

**Comment by samerton** [comment]
Nameless should always use UUIDs for avatars, if you edit the user in the StaffCP -> Users tab (assuming premium Minecraft accounts are enabled) does the correct UUID show up in the UUID field?

**Comment by Aberdeener** [comment]
Closing for now, feel free to reopen if you find a way to recreate!
