### ISSUE TITLE
Maintenance page not saving image Height/Width values

### ISSUE THREAD

**Issue by HeavenCrafter** [NamelessMC/Nameless#1691]
**Describe the issue**
I was trying to setup a custom maintenance information page. Wanted to make it look cool by adding some images. While doing so, I set the width to fix the text alignment by making it smaller which can be done simply on the image settings itself. Before submit, everything looked the way I wanted. After submission, it reverts the image size to the original size of the image.

**To Reproduce**
1. Go to StaffCP > Configuration > Maintenance
2. Proceed to the Maintenance Message editor
3. Add an image of your choice, in my case, is from an Imgur image link.
4. Change the size, in my case, 16x11 (16 Width x 11 Height)
5. Submit the changes.

**Expected behavior**
![image](https://user-images.githubusercontent.com/22242534/85913148-c20b9200-b864-11ea-8553-d9fa03be278a.png)

**Behavior that I got instead**
![image](https://user-images.githubusercontent.com/22242534/85913157-d8195280-b864-11ea-84ec-a38b16984e33.png)

**NamelessMC version (from AdminCP -> Overview)**
Latest (v2.0 Pre7)

**Comment by Aberdeener** [comment]
This appears to be fixed with the use of TinyMCE - please feel free to reopen if the problem persists.
