### ISSUE TITLE
Messaging and Alerts pages are misaligned

### ISSUE THREAD

**Issue by 04fsnape** [NamelessMC/Nameless#1692]
**Describe the issue**
The /user/messaging/ and /user/alerts/ pages are not aligned properly. The buttons are in different positions and the margin above the status bar is a different size.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to /user/messaging/
2. Go to /user/alerts/
3. Compare

**Expected behaviour**
They should both be aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/33752988/85923142-33a10b80-b878-11ea-91b3-ed79f922405a.png)
![image](https://user-images.githubusercontent.com/33752988/85923148-3a2f8300-b878-11ea-97b5-bbad6201a6f6.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Additional information**
Using DefaultRevamp

**Comment by Aberdeener** [comment]
Am I missing something? I don't see what you mean

**Comment by 04fsnape** [comment]
> 
> 
> Am I missing something? I don't see what you mean

Open both the images in your browser and click between them. You'll see the "Delete all" button is higher than the "New message" button, same with "You do not have any alerts" and "You do not have any messages".

**Comment by Derkades** [comment]
"You do not have any messages" is ~2px lower than "You do not have any alerts" for some reason

**Comment by Derkades** [comment]
Fixed in 99c77e1652daa5050095e650dc094ae0f1694a81
