### ISSUE TITLE
New Topic Preview/Save Draft

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1696]
How about when you click on `new topic` and you are on the page to put topic subject/title and the post itself. Add some buttons to preview what it will look like and/or save as draft so it does not become public but still saves work.

Features I used a lot when I used Drupal before NamelessMC, but not sure if all the work required is going to be worth enough for one person (not sure if others would even want this).

**Comment by Aberdeener** [comment]
I am not sure what you mean by "preview", but saving drafts is a great idea - but it would be a big addition to make

**Comment by StormyIceLeopard** [comment]
That is why I do not think it will come.
And preview, GitHub (as I am typing this) has a preview tab. I can see what my post will look like before I post it.

**Comment by Derkades** [comment]
Does NamelessMC use a markup language for formatting? I thought it used a WYSIWYG editor where a preview doesn't really make sense

**Comment by StormyIceLeopard** [comment]
I think you are right, but it is not exactly the same from the editor and post I believe.

**Comment by Derkades** [comment]
the markdown editor is probably going to be removed so this won't be very useful
