### ISSUE TITLE
API method for reading and sending private messages

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1697]
Required for https://github.com/NamelessMC/Nameless-Plugin/issues/51

**Comment by samerton** [comment]
Not sure how comfortable I am with showing a user's private messages through a single API key instead of some more serious authentication

**Comment by Derkades** [comment]
Well, as far as I know someone can use the API key to give themselves an owner rank and delete everything

**Comment by Aberdeener** [comment]
How do we feel about this @samerton and @Derkades ?

**Comment by Derkades** [comment]
I think it's fine, uses should consider the API key to be as secret as the database password.
