### ISSUE TITLE
Alerts/Announcements Banners

### ISSUE THREAD

**Issue by HeavenCrafter** [NamelessMC/Nameless#1699]
**Please describe the feature in as much detail as possible**
I feel that this can be helpful for server owners who have an important announcement to show to players and would like to notify them whenever they visit the site. So having an announcement banner functionality would be really neat in my opinion.

Somewhat similar to Google Sites' new announcement banner feature that was released a while ago but instead of strictly just a static bar, has the ability to add more to it by using Bootstrap's Alert Banners.

![image](https://user-images.githubusercontent.com/22242534/86162500-76e1cf80-bb41-11ea-9f96-c30e4a9e15cc.png)
![image](https://user-images.githubusercontent.com/22242534/86162517-7c3f1a00-bb41-11ea-8eb0-a3d9a7ea4392.png)

On Google sites, there are options to change the color of them and add hyperlinks within the text. But I feel that there is a lot more potential if using the alerts from Bootstrap.

**Comment by Aberdeener** [comment]
Some templates such as Cesium have this feature, but I think it would be a great addition to globalize for Nameless.

**Comment by IsS127** [comment]
If I remember correctly, this feature exists for v1 but wasn't converted to v2.
Will come in the future!

**Comment by Aberdeener** [comment]
#1751 Adds this, awaiting reviews

**Comment by Aberdeener** [comment]
#1751 was merged! Closing this now 🚀
