### ISSUE TITLE
Search bar and background

### ISSUE THREAD

**Issue by BoomScoom** [NamelessMC/Nameless#17]
I would be nice to have a Search bar on the page where you an search hrouh oh the forums.  I would also be nice if we could add a background to the page.

**Comment by BoomScoom** [comment]
It would also be nice that when you press "Remember me" that it won't log you out until you log your self out.  I find that if I go on my site every few hours I have to log my self back in even if I clicked "Remember me"

**Comment by BoomScoom** [comment]
Another idea is to add an online now button.  It would show the staff online and a list of names with the players online.

**Comment by samerton** [comment]
I can work on a searchbar for a future release.
Backgrounds can be changed already; you'll need to edit the CSS of the theme you're using in order to do so.
An online module is already planned and should make it into the full 1.0 release.

**Comment by samerton** [comment]
Added online users list and search functionality in ed5b7f273ae9dfa50d90628f9e14edb7e1d1c514
