### ISSUE TITLE
Youtube / Generic Iframe embeds

### ISSUE THREAD

**Issue by MikeHollisJr** [NamelessMC/Nameless#1700]
**Please describe the feature in as much detail as possible**
Coming from v1 I really found code embeds extremely useful and would love to see them added back

**Comment by StormyIceLeopard** [comment]
I would like iframe embeds in general to be possible. I wish to use media from my own website. (It is currently using VideoJS as the player)

**Comment by MikeHollisJr** [comment]
> I would like iframe embeds in general to be possible. I wish to use media from my own website. (It is currently using VideoJS as the player)

I can get behind this as well

**Comment by StormyIceLeopard** [comment]
Not sure how it worked in v1 but I would like to see this work on both custom pages and forum topic posts, for those who have permission.

**Comment by Derkades** [comment]
It's possible to do this
![image](https://user-images.githubusercontent.com/15892014/86174871-b4833000-bb22-11ea-98c1-5d2711557193.png)
![image](https://user-images.githubusercontent.com/15892014/86174836-a3d2ba00-bb22-11ea-9406-166684994633.png)

**Comment by StormyIceLeopard** [comment]
Okay, so it is just my website that is having the issue. Might have set it up wrong.

**Comment by StormyIceLeopard** [comment]
Found how to allow/disallow iframe sources.
Line 46 of this file [https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Output.php](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Output.php)

**Comment by Derkades** [comment]
Closing this in favour of #1709
