### ISSUE TITLE
v3 (Major Changes)

### ISSUE THREAD

**Issue by xarmeetx** [NamelessMC/Nameless#1704]
SUGGESTIONS
I see https://www.veltpvp.com/ and https://lunar.gg/ as the perfect minecraft server websites.

Nameless has most of the features of these websites, but lacks some things. I'm just making these suggestions, so hopefully the staff team can incorporate them into v2 or v3.

I do understand that there are features that do these things, such as forms. However, these are rough solutions.
For example, a tickets/ban appeal module would be much appreciated instead of using forms for tickets. I do understand that it is more work for the devs. I have read many others who agree with some of the following suggestions, and hopefully they will be seen on the full release of v2 or v3. 

Essentially, most of my suggestions are that nameless becomes more like velt's or lunar's website, which are for established servers, whose websites have stood the test of time.

- UI changes https://www.veltpvp.com/ (this is IMO the perfect UI) Add a dark/light mode and you'll have users flocking to Nameless by the thousands.
- ticket/support page: people can make tickets, which staff can respond to or claim
- ban appeals: support for ban appeals, where staff can respond to, and click button to unban, shorten ban, etc. for a player
- forums drag/image support
- add console to staff panel as part of core
- staff page that looks more like this: https://www.lunar.gg/staff or https://www.veltpvp.com/staff
- forums have an upvote feature like this (ranks posts by upvotes)
https://www.lunar.gg/forums/90518/voltage-recruiting-for-map-9-giving-chances-o_o
or like https://www.veltpvp.com/thread/2064/the_summer_update
- a better profile page that shows kills, deaths, and other info that can be configured by the user using placeholder api tags such as %vault_eco_balance% or other custom placeholders (something like https://www.lunar.gg/u/trashcanolives or https://www.veltpvp.com/u/trashcanolives)
- leaderboards for economy, kills, playtime, etc.
- a dynmap integration, so you don't have to use iframes

https://discordapp.com/channels/@me/713828653917536366/727791446996025425
(example tickets system)

https://youtu.be/A2xv9DBZF3I?t=158
(example tickets/ban appeal module)

Thank you for your time.
Hopefully these features will be incorporated into v2 or v3.

**Comment by Derkades** [comment]
> UI changes https://www.veltpvp.com/ (this is IMO the perfect UI) Add a dark/light mode and you'll have users flocking to Nameless by the thousands.

There are a some paid and almost no free templates available right now. Hopefully others will contribute more themes in the future. In my opinion the default theme should be "boring" like DefaultRevamp.

> ticket/support page: people can make tickets, which staff can respond to or claim

I've created issue #1705 for this

> ban appeals: support for ban appeals, where staff can respond to, and click button to unban, shorten ban, etc. for a player

I think this already exists or there is a way to do it. See also #512 and #862

> forums drag/image support
I'm not sure what you mean by this, can you create an issue with a description?

> add console to staff panel as part of core

The Minecraft server console? I think that's out of scope for the core

> forums have an upvote feature like this (ranks posts by upvotes)

Yes! I've created an issue here: #1706

> a better profile page that shows kills, deaths, and other info that can be configured by the user using placeholder api tags

See #1484

> a dynmap integration, so you don't have to use iframes

See #1406

**Comment by Derkades** [comment]
It's hard to keep track of large issues like this, if I've missed something or if you want to make new suggestions please create new issues, with one idea per issue. Thanks!

**Comment by samerton** [comment]
Personally I don't like the designs of the two sites linked, so the default template won't ever look like those I'm afraid, but the template system is designed to allow you to fully customise the visual appearance of your site.

Many of those points would have to be developed as separate modules as opposed to core features, such as a server console, stats integration etc. I want to implement many more integrations but at the moment my focus is on delivering a full v2 release.

RE the staff page, have you tried this module? https://namelessmc.com/resources/resource/65-staff-module/

**Comment by xarmeetx** [comment]
> Personally I don't like the designs of the two sites linked, so the default template won't ever look like those I'm afraid, but the template system is designed to allow you to fully customise the visual appearance of your site.
> 
> Many of those points would have to be developed as separate modules as opposed to core features, such as a server console, stats integration etc. I want to implement many more integrations but at the moment my focus is on delivering a full v2 release.
> 
> RE the staff page, have you tried this module? https://namelessmc.com/resources/resource/65-staff-module/

Would it be possible to make nameless default look more like lunar?
https://lunar.gg 
Its a simple design and looks really clean.

**Comment by Aberdeener** [comment]
Changing the whole default template for nameless will take a lot more than
a GitHub issue :p
You can definantly find a developer in our discord who would commission a
new template for you!
