### ISSUE TITLE
Support tickets system

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1705]

**Comment by IsS127** [comment]
Is this a ticket system for NamelessMC.com?
Because otherwise the forms module could easily be used as a ticket system.
The only thing to make it look like a ticket system is to change the "Submissions" to "Tickets" in the language file.

**Comment by Derkades** [comment]
From the original issue:
> For example, a tickets/ban appeal module would be much appreciated instead of using forms for tickets. I do understand that it is more work for the devs.

> ticket/support page: people can make tickets, which staff can respond to or claim

@xarmeetx can you elaborate what would make a dedicated tickets/ban module better?

**Comment by xarmeetx** [comment]
I think that a dedicated tickets/ban module should look something like this: https://youtu.be/ptAPi0Q1FQQ?t=478

The forms module is good at what it was made to do: collect data like google forms or any other forms application.

What a dedicated ban appeal/tickets module needs. 
- staff can claim tickets or be assigned tickets
- buttons to unban, shorten ban, and preset response buttons

**Comment by Aberdeener** [comment]
Apparently @WhenUHackUNoob is working on this for a publicly available module. Will close this now

**Comment by WhenUHackUNoob** [comment]
Hello and thank you for bringing my attention to this @Aberdeener.

Yes, I am currently working on an advanced ticket module with an ingame api, setting users as "priority support", changing tags and much more! As of now if you need a module Fort rickets ASAP I would probably use the Forms module (check @partydragen 's GiHub) for now.

I am trying to realese the tickets module ASAP but I am trying to make it as enjoyable as possible (I am new to making Modules for NamelessMC).

Yours sincerely,
WhenUHackUNoob

P.S Sorry about any spelling errors, I am replying on GitHub mobile.

**Comment by armeetjatyani** [comment]
Ok cool!
Looking forward to the release.
I have been using @partydragen 's forms module for a while now ;)

**Comment by JosGCS** [comment]
Any fucking Tickets Module? NOT FORMS MODULE
