### ISSUE TITLE
License system to avoid leakage of our paid themes

### ISSUE THREAD

**Issue by SplinterNight1** [NamelessMC/Nameless#1707]
Hi, i have a big suggestion, I propose that you set up a system to avoid the leakage of our paid themes. as a script to be inserted in our theme and which would check in a database the key

**Comment by Derkades** [comment]
In my opinion any license/DRM systems should be handled by themes or modules, not by NamelessMC.

**Comment by SplinterNight1** [comment]
he'd have to propose them to us, wouldn't he?

**Comment by Derkades** [comment]
You can do whatever you want in your modules/templates

**Comment by StormyIceLeopard** [comment]
I agree with Derkades.

**Comment by samerton** [comment]
I'm planning on adding something to the Resource module, how you verify etc them comes down to your template/module as opposed to Nameless itself.
