### ISSUE TITLE
Allow iframes from sources other than youtube or video

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1709]
Allow iframes to load in forum posts if posted by a user with permission.

**Comment by Aberdeener** [comment]
Decent thought, however the text editor is 3rd party so customizing it for this purpose would be difficult if not impossible (as far as I know)

**Comment by StormyIceLeopard** [comment]
I believe how this would work is:
On post load, check the author.
If author has permission, allow the loading of raw code
If author does not have permission, continue as normal; do not load the raw code. (blank iframe)

**Comment by Aberdeener** [comment]
Wait, so if a user does NOT have permission to load Iframes, how will we prevent them from posting Iframes? (See my first comment)

**Comment by StormyIceLeopard** [comment]
iframe code can be posted, but it does not load. "currently iframes are removed from posts for security reasons" -Samerton

**Comment by Aberdeener** [comment]
Sounds kind of janky and inconsistent - and I'm not sure where this could be used in the real world. Do you have a hypothetical scenario?

**Comment by StormyIceLeopard** [comment]
I have videos on my own website, not YouTube, and I wish to embed them into forum posts, instead of just linking them.
But like samerton said "removed for security reasons" I agree with that. So what about a permission so only those with permission can have their code loaded, like me. So no one else is able to embed because of security, but since I trust myself, allow me to embed.

**Comment by StormyIceLeopard** [comment]
So I came up with a solution to allow certain sources of iframes, [https://github.com/NamelessMC/Nameless/issues/1700](https://github.com/NamelessMC/Nameless/issues/1700), but I still think a permission should be needed in order for a iframe to be placed/viewed/loaded etc.

**Comment by Derkades** [comment]
Iframes are definitely a security risk. Iframes can "break out of the iframe", for example it can send javascript alerts or set location.href, redirecting the user.

There can be a permission that allows posting any iframes, but this should be reserved for administrators or moderators only. Users should be able to edit the URL whitelist from the panel.

**Comment by Derkades** [comment]
In my opinion, instead of loading or not loading the iframe in certain scenarios is indeed inconsistent and confusing like @Aberdeener said. When trying to create a post with an iframe that contains a URL that is not whitelisted, the user should get a warning, instead of letting the user post and silently hiding the iframe.

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/discussions/2168
