### ISSUE TITLE
DefaultRevamped: "More" dropdown does not function in vertical mobile browsers

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1711]
**Describe the issue**
The "More" dropdown does not do anything in DefaultRevamped template on a mobile browser. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://kenovamc.xyz/ (or any site with DefaultRevamped theme) on a mobile device in vertical orientation.
2. Tap the hamburger dropdown
3. Tap "more"
4. Try again, thinking you mistapped.
5. Nope, still doesn't work

**Expected behaviour**
That it would work properly

**NamelessMC version (from AdminCP -> Overview)**
v2 pre-7

**Additional information**
Tested on multiple sites with no luck :(

**Comment by StormyIceLeopard** [comment]
bummer, have confirmed this

**Comment by samerton** [comment]
Appears to be a Semantic UI limitation, sidebars can't contain dropdowns

Removed the dropdowns in 0c6d88bd276a0f35b01ec0305d4eaee11f513645
