### ISSUE TITLE
IFRAME html code doesn't work on "Custom Pages"

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1713]
**Describe the issue**
It's pretty simple, no time to lose reading this, you can test it yourself.
If you want try adding site as IFRAME to your custom page and it won't load at all

**To Reproduce**
1. Go to StaffCP.
2. Go to dropdown "Pages" section.
3. Go to "Custom Pages" section.
4. Click "New Page".
5. Add IFRAME html code to "Page Content" field.
6. Save and go to your custom page and you'll see something like this (depends on width and height) - look at screenshots

**Expected behaviour**
It should show site i added withing iframe

**Screenshots**
![image](https://user-images.githubusercontent.com/56804505/86366945-b44a7800-bc7b-11ea-8dae-36eb7c727257.png)

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pre7 (latest)

**Additional information**
/

**Comment by Derkades** [comment]
Is the iframe URL http or https and is your website http or https?

**Comment by StormyIceLeopard** [comment]
Did you toggle the setting "Allow unsafe HTML?" for that custom page?

**Comment by TheJoshue** [comment]
> Is the iframe URL http or https and is your website http or https?
I tried, it didn't work

> Did you toggle the setting "Allow unsafe HTML?" for that custom page?
I tried this also and it worked!
Thank you so much!

**Comment by samerton** [comment]
Glad the issue is solved!
