### ISSUE TITLE
Subforum badge/icon alignment

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1714]
**Please describe the feature in as much detail as possible**
I really don't know if this is by this because it's a lot of work to make icons centered and to align them as they should be in row and column, to have their individual space and to be precisely aligned.
Maybe it's a lot of work so that's why it isn't implemented yet, but for sure it'll be extremely better if it gets aligned, also the titles of subforums to be centered and start from the same place each (in the screenshot below you can clearly see that they aren't precisely aligned and not all titles start from same place in their row)

Screenshot (I am using Cesium template, but this can be reproduces on default/revamped templates too):
http://prntscr.com/takmgq

**Comment by samerton** [comment]
Currently, if you use Font Awesome, you need to use the `fa-fw` class, for example:

`<i class="fas fa-comments fa-fw fa-2x"></i>`

**Comment by TheJoshue** [comment]
Wow!
It actually works pretty decent.
Yes, using font awesome.
http://prntscr.com/taktmc
