### ISSUE TITLE
Statistic for any plugin using MySQL

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1715]
Module where we can add and customize 1 page with multiple tabs for previewing list of statistics about 1/2/3 subservers, just like members module (if you know that module), literally the same as members module with those group tabs, but here it'll be either subserver tabs (for bungeecord network) or tabs for different statistics about 1 certain subserver.

**Comment by Derkades** [comment]
I don't think it's viable to make a generic module that will display statistics for any plugin that uses MySQL as a storage backend

**Comment by samerton** [comment]
I'd agree with Derkades on this one, we'd have to have a module with specific support for a selection of plugins.

**Comment by TheJoshue** [comment]
I recommend looking at custom points system like GemsEconomy (https://www.spigotmc.org/resources/gemseconomy.19655/) as it can be used in MILION of ways, for example you can use it as currency, and you can also use it as a representation of how many times player has donated for a server, or how many hours he has spent on the server, if you understand me; you can create currency and whenever player purchases something on webstore (tebex/craftingstore) it'll give him 1 of (for example:) "DonationPoint" custom currency that is created (and stored over MySQL) with GemsEconomy plugin... it can be used in milions of ways to make milions of statistics.
This is just a suggestion, it'll be very cool if you actually like it, but idk because GemsEconomy isn't globally popular plugin...

**Comment by Aberdeener** [comment]
That... Doesn't really help. In order to make a module like what you want,
we need to add database queries for hundreds of plugins, as well as
language translations, different layouts and more. It's not practical
