### ISSUE TITLE
Properly import/export database with special characters (utf8)

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1716]
**Please describe the feature in as much detail as possible**
I see that some characters like "é" are supported, but there are some characters that are very frequently used, and it would be great if you add those characters supported FOR MYSQL.

Characters: ć, č, ž, š, đ

They're already supported in Nameless, I can make thread with them, everything, just one BIG problem.
Using mysql, if I export database, and import it again (that SAME database), it'll bread every line/text that has any characters that I listed above (ć, č, ž, đ), except "š", which is very strange.
So by knowing all of these, I assume this can be implemented, support for letters/characters "ć, č, ž, đ", because if "š" can be supported, probably those 4 can be supported too, for MYSQL EXPORTING! All of them already ARE supported in Nameless usage.

**Comment by Derkades** [comment]
Make sure to export/import it with the correct encoding. It needs to be set correctly on the table, when exporting, on the exported file, and when importing. If I remember correctly it should be set to utf8-mb4

**Comment by TheJoshue** [comment]
I know that this is not related to Nameless very much, but how can I convert my current files from default MySQL encoding (I assume it's utf8) to utf-mb4, would it break or something?

**Comment by Derkades** [comment]
Leave your current database as it is, export it, make sure the .sql file is UTF-8, then experiment with different settings when importing. I've had some issues with this before and I think I solved it by adding `--default-character-set=utf8` when importing the .sql file

**Comment by TheJoshue** [comment]
Just to let know if anybody else has these issues:

add/edit this in `nano /etc/mysql/my.cnf`
```
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4
```

then add/edit this in `nano /etc/mysql/mysql.conf.d/mysqld.cnf`
```
[mysqld]
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

Reset MySQL and whenever you want to export/import database, use these command

**EXPORT**
`mysqldump -u <user> -p --default-character-set=utf8mb4 <db_name> > <filename>.sql`
*type password*

**IMPORT**
`mysql -u <user> -p --default-character-set=utf8mb4 <db_name> < <filename>.sql`
*type password*

I am sorry if this comment was unnecessary, I just wanted to help others as it took me ~30/40mins to test everything out and it's working perfectly fine. Thanks!

**Comment by Derkades** [comment]
> I am sorry if this comment was unnecessary

Definitely not! Helpful comments like this are much appreciated. It might help someone in the future who finds this through google.
