### ISSUE TITLE
Pagination entries per page configurable in StaffCP

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1719]

**Comment by samerton** [comment]
Can we elaborate on this issue a bit more please?

**Comment by Derkades** [comment]
I'll try to guess what they meant in the original issue. For example, when viewing a forum (https://namelessmc.com/forum/view/6-general-discussion/) it shows 10 posts on each page. This could be configurable to show 10, 25, 50, 100, etc.

**Comment by samerton** [comment]
Makes sense, I'll close in favour of https://github.com/NamelessMC/Nameless/issues/1123 in that case
