### ISSUE TITLE
An option to disable choosing languages 

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1724]
Option in StaffCP that will turn off per-user choosing languages in their account settings... only default language that admins set in StaffCP will be used

**Comment by kacperleague9** [comment]
Delete all languages from languages, easy

**Comment by kacperleague9** [comment]
Only leave your [i dont recommend]

**Comment by Derkades** [comment]
For the very few people who need to do this, removing languages is probably a good enough solution?

**Comment by Derkades** [comment]
kacper provided a good enough solution

**Comment by TheJoshue** [comment]
> kacper provided a good enough solution

Yes, but I already tried that and there are some bugs
i can test it out again on latest Nameless build and let you know what actually happens.
