### ISSUE TITLE
Calendar option doesn't work as expected

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1725]
**Describe the issue**
When you click the blank field that is for inserting date (custom user fields in account>profile settings), it'll pop up something like extremely wide that is supposed to be calendar (please read **Screenshots** section)

Although I am using Cesium template, this can be reproduced withing ANY template, I know this because I tried adding datepicker thing to my site, trying to fix it but I didn't do decent job (look at the screenshot)
The file location I edited was `.../core/assets/plugins/ckeditor/plugins/spoiler/css/spoiler.css`, that's why I know this isn't an issue because of any template.

**To Reproduce**
1. Go to StaffCP
...
3. Add custom user field for DATE
4. Go to Profile Settings in your Account and see window size

**Expected behaviour**

**Screenshots**
On here, I did some changes to .css file and make it more less wider, before it was wide as much as your screen can fit so if you have 1080p resoultion it'll go up to 1920px and you can't even see the date numbers, only blank white field that is supposed to be datepicker.
http://prntscr.com/taomyz

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pre7 (Latest)
This can be also reproduced on v2.0.0-pre6 (I didn't report this, I wasn't using github at all at that time)

**Additional information**
Add more information about the problem if necessary.

**Comment by Aberdeener** [comment]
<img width="555" alt="Screen Shot 2020-07-03 at 12 45 44 AM" src="https://user-images.githubusercontent.com/26070412/86445032-89d1dc80-bcc6-11ea-9f02-3328b9f10e0c.png">

Could not recreate. Fresh install of v2. Have I missed something?

**Comment by Derkades** [comment]
The calendar widget and date field looks completely different on your end, is this an inconsistency between different pages/templates or did some form/calendar library change?

We can consider using the native date picker, all browsers except IE and Safari support it https://caniuse.com/#feat=input-datetime. This makes the experience on mobile a lot better and the date will be displayed in the user's local date format.

**Comment by TheJoshue** [comment]
> <img alt="Screen Shot 2020-07-03 at 12 45 44 AM" width="555" src="https://user-images.githubusercontent.com/26070412/86445032-89d1dc80-bcc6-11ea-9f02-3328b9f10e0c.png">
> 
> Could not recreate. Fresh install of v2. Have I missed something?


> The calendar widget and date field looks completely different on your end, is this an inconsistency between different pages/templates or did some form/calendar library change?
> 
> We can consider using the native date picker, all browsers except IE and Safari support it https://caniuse.com/#feat=input-datetime. This makes the experience on mobile a lot better and the date will be displayed in the user's local date format.

I am not sure really, I use Cesium template all the time so it really might be a mistake by Xemah (author of Cesium template)
I will try with other templates too to see if this is a problem with my nameless instance, but everything besides calendar works perfect.

**Comment by Derkades** [comment]
Yes, it looks like a Cesium issue. The Cesium date picker looks different from the default date picker, so Xemah must've changed it.
