### ISSUE TITLE
Forum BOTS (passive)

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1726]
**Please describe the feature in as much detail as possible**
So this one is a big one and I might not describe it as good as possible.

*By "passive" I mean that they will be only able to used as bots to post forum posts, not to regulate other's post or moderate other's posts.*

Adding "BOTS" tab in the StaffCP right where "forums" and "labels" are placed (which means this can be addon for forum module).
What will this do, it'll make an option to create "BOT", and as many bots as you want, customize their name (all of them has their unique ID / this is likely some technical stuff and I shouldn't talk about this), customize their avatar and they don't have profile so when you make post on the forum as a BOT, users can't click on BOTs name or avatar, also bot doesn't have statistic and all that stuff, only maybe description that will be shown when you post something as BOT, and their posts are regularly counted in forum statistics.

For admins, when trying to post a thread on subforum that has BOT allocated to that subforum/category, there will be an additional option that says "Submit as bot", if clicked, it'll let you select with which bot (if there are more than 1 bots allocated) you want to make your post.

This can be extremely useful if you want to make BOT and name it your `SERVERNAME`, and post something as that, or maybe you want to create bot with an avatar for all of your subservers on your bungeecord network, and post rules, season informations, report format in each subforums that corresponds to BOTs name

**Comment by StormyIceLeopard** [comment]
Interesting idea.

**Comment by Aberdeener** [comment]
I'm not sure I understand. 
If it would be useful for admins to post via a bot, why don't they just post it themselves? Or am I misunderstanding

**Comment by StormyIceLeopard** [comment]
Well there might be some things you want to associate with the network instead of an individual staff member, for example the rules.

**Comment by TheJoshue** [comment]
> I'm not sure I understand.
> If it would be useful for admins to post via a bot, why don't they just post it themselves? Or am I misunderstanding

Well yeah, but bots can have multiple purposes that don't need to be related to forums (which will put that "BOTS" tab from StaffCP to somewhere else in the panel).
First thing that came to my mind is **sending global messages**, so send one same message (using bot) to all registered users... I assume this can be very heavy if your site have for example 5k registered users, but (if possible) it can be made in that way so if you send global user message (in their and bots conversation), it'll first send a message to all users that are online, and whenever other users log on and get online, it'll send them too, so it'll wait for them to get online and just then send a message (idk if date of that message can be the date when global message was actually executed by bot (to all registered users obviously))

**Comment by TheJoshue** [comment]
> Well there might be some things you want to associate with the network instead of an individual staff member, for example the rules.

Also as @StormyIceLeopard said, this can be useful if for example you have staff member who is Moderator, and you are Admin, and you manage staff members, and that Moderator who wrote (for example) rules on one forum thread gets demoted, (s)he can edit/delete his thread etc etc

**Comment by Derkades** [comment]
How about an option to send a message or post as your rank instead of as your user? So send the message from "Moderator" or "Admin". I think that would do what you want without having to introduce a "bots" system that might be confusing to understand for users.

**Comment by StormyIceLeopard** [comment]
That might be best. Then you could just simply create blank groups for that purpose, then on the post have the option to remove the user who posted it so it is just the group. (Too confusing? I am not great at communication.)

**Comment by samerton** [comment]
I like the personal touch of someone's own account posting an update, for example if you look at Hypixel they have one of their admins or developers announcing new features. I think having a generic bot for creating topics is a bit of a niche feature.

**Comment by Aberdeener** [comment]
I 100% agree with Sam on this one. If a mass messaging feature was ever
implemented, the message coming from a member of staff rather than a bot
feel much "cooler" to the recipient

**Comment by TheJoshue** [comment]
Even though I like Darkades idea, samerton's statement is very reasonable and I agree with that too, also disagree with my this feature request post.

**Comment by WhenUHackUNoob** [comment]
I really like Derkades idea but I think that Samerton's status is very reasonable to the topic.
