### ISSUE TITLE
Player heads with skin for Spigot servers list

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1727]
**Please describe the feature in as much detail as possible**
As far as I know, if you head to Minecraft Integration and add MC server with query enabled (spigot/regular server, not bungee/proxy server), you will see how many players are online and you will see their head displayed but WITHOUT skin.

Can this be added? Add support for skin heads there just like when somebody register account on the forum and MC head avatar will be placed - head of his skin name on their avatar.

**Comment by Derkades** [comment]
Are you saying it shows all players as steve/alex?

**Comment by TheJoshue** [comment]
> Are you saying it shows all players as steve/alex right now?

yes it does

**Comment by samerton** [comment]
Make sure bungeecord is set to true in your Spigot config so it's using real UUIDs

**Comment by TheJoshue** [comment]
This is how it is, this is standalone (spigot) MC server, query-port is the same as port (25565) and query is enabled in `server.properties` file. Online mode is `false` (i can test it with online mode true).
http://prntscr.com/tb2nxr

**Comment by Derkades** [comment]
Online mode needs to be on, otherwise UUIDs aren't "real" mojang UUIDs but just random UUIDs

**Comment by TheJoshue** [comment]
> Online mode needs to be on, otherwise UUIDs aren't "real" mojang UUIDs but just random UUIDs

Ok then, but can it see username of player, then grab player head from somewhere like cravatar.eu, just like when user registers on the forum and his automatically generated avatar is player head (if selected "Minecraft avatar" in **Configurarion > Avatars**)

**Comment by Derkades** [comment]
Yes, using the player name (if returned by the server) would be accurate enough. Keep in mind that in general NamelessMC is not really made to handle offline mode servers, for example the API (and Minecraft integration plugin) won't work at all.

**Comment by TheJoshue** [comment]
Well then, you might consider adding an option to disable **Status** page, because it would be better to not use it at all if your server IP/domain is showed on the header of the site with online player counter (not sure for which templates, maybe even for default) and then status page is really not needed.
Should I open another *feature request* for this certain thing? Disabling **status** page (not showing it anywhere).

**Comment by Derkades** [comment]
I'm not sure but it seems it can already be disabled, for example it is not shown on https://cubedcraft.com/ or https://worldscapemc.com/

**Comment by TheJoshue** [comment]
Oh, my mistake.
I really don't know how I didn't see it, maybe it wasn't present in v2pre6, or maybe it was, but I really didn't see it.
Thanks!

I will close this as I understand everything you said.
