### ISSUE TITLE
Permission to toggle gifs as user avatars

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1729]
**Please describe the feature in as much detail as possible**
An option to add gifs as user avatar instead of images

**Comment by StormyIceLeopard** [comment]
Have a permission for this too, so only certain groups can use them. (Can help encourage donations to servers)

**Comment by samerton** [comment]
It's already possible to upload a gif avatar, I'll rename this to add a permission for it.

**Comment by Aberdeener** [comment]
Added in 155ce70 
Thanks!
