### ISSUE TITLE
An option to disable time-zones

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1731]
**Please describe the feature in as much detail as possible**
Someone really doesn't need this feature and occasionally, even if I set Default Timezone in StaffCP, newly registered player will have different timezone (not very rare in my case, same goes to default language) by default.
So it would be great if you just add either an option to disable selecting timezone in Profile Settings or disable it completely and use machine's timezone.

**Comment by Aberdeener** [comment]
Not sure this would be used too much, why force people to see dates and times incorrectly?

**Comment by TheJoshue** [comment]
Maybe it's a little bit buggy for me, because whenever I set default timezone, when someone registers to the site, nameless set its default timezone (default like when you install nameless for the first time)
