### ISSUE TITLE
Cannot update to pre-release 7

### ISSUE THREAD

**Issue by M4T14SG4M3R** [NamelessMC/Nameless#1732]
**Describe the issue**
I have namelessmc pre-release 6 installed on my website but when i go to update in the admin panel, it says that the installed build is the latest (pr6), but it is not the latest, the latest is pr7

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'admin panel'
2. Click on 'update'
3. It says that the current installed version pr6 is the latest

**Expected behaviour**
It should have a button to download the pr7 update like with the old ones

**Screenshots**
![image](https://user-images.githubusercontent.com/16471265/86491292-634c8980-bd38-11ea-813b-3d5cf05762df.png)
![image](https://user-images.githubusercontent.com/16471265/86491334-8b3bed00-bd38-11ea-8a16-2716639f5dd5.png)

**NamelessMC version (from AdminCP -> 2.0.0-pr7?)**

**Additional information**
In the overview page it says 2.0.0-pr7, but in the update button it sats 2.0.0-pr6

**Comment by samerton** [comment]
Hi, when did you install Nameless?

**Comment by M4T14SG4M3R** [comment]
In 2018 and i updated everytime when a update was released using the update button

**Comment by samerton** [comment]
The fact your overview tab already says pre-release 7 suggests the site is indeed running pre-release 7.

Do you have an option named "Enable Google reCAPTCHA on login?" in the StaffCP -> Configuration -> Registration tab?

**Comment by M4T14SG4M3R** [comment]
![image](https://user-images.githubusercontent.com/16471265/86492166-351c7900-bd3b-11ea-8651-cc850506013f.png)

**Comment by samerton** [comment]
Ah right it looks like it's an issue with the Spanish translation, it has pre-release 6 hardcoded into the string: https://github.com/NamelessMC/Nameless/blob/v2/custom/languages/SpanishES/admin.php#L469

You are definitely on pre-release 7 and there's no need to worry.
