### ISSUE TITLE
Forum, per thread author label

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1733]
**Please describe the feature in as much detail as possible**
Some label/indicator that will simply indicate to all users who is the author of the thread they're posting (commenting).

**Comment by samerton** [comment]
Not sure I understand this one sorry, the topic author is already provided as a template author, and it's displayed at the top of each topic with the Default Revamp template at least.

**Comment by TheJoshue** [comment]
> Not sure I understand this one sorry, the topic author is already provided as a template variable, and it's displayed at the top of each topic with the Default Revamp template at least.

It's only supported within Default Revamp template?
Can it be supported by Nameless by itself?

I mean I know there is "Started by {x}" or something like that right when you go to topic, below topic's title there is that message, but would be nice if some label can be added like above/over/below user's avatar or something like that, that when you are reading posts that are far below the title (where "Started by {x}" message is), you will know with who are you talking (this might be useful for big communities and might be useful only if there are let's say 10+ posts per page).

**Comment by samerton** [comment]
It's up to the template what gets shown and where, Nameless supports it by providing the variable to the template. I'm still not sure I understand, if there was a label on every single post telling you who the original author was I think this would get confusing and repetitive.

**Comment by TheJoshue** [comment]
I thought of something like... instead of displaying it with text above "started by {x}", it can be simple rectangle bordering with bottom edge of the user's avatar and below that it's his username, and on that rectangle it'll be for example "Topic Author"

**Comment by IsS127** [comment]
I agree with Samerton, it can be too repetitive by displaying the author's name below each users box if I understand correctly?

However this can easily be achieved by editing your template. If you need help doing this, you can checkout the template's CSS documentation on how to integrate this into your template designwise. We use Semantic UI for "DefaultRevamp" and Bootstrap for the "Default". Then you can use the same variables for the authors name. I am sure any HTML related discord/forum can help you with this as well.

I am closing this as we have no plans of adding it.
