### ISSUE TITLE
Cannot use SMTP on my forum

### ISSUE THREAD

**Issue by M4T14SG4M3R** [NamelessMC/Nameless#1735]
**Describe the issue**
Everytime i try to use SMTP on my forum when i click on send test email, the page gets stuck and keeps loading like for 5 minutes, then i get a message saying "SMTP Error: Could not connect to SMTP host.", i don't know why i get this because i have everything setup correctly as it says in the wiki, and the data is correctly setup including the /core/email.php, the data is the same

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Config - Emails'
2. Click on 'Use phpmailer'
3. Fill the data 
4. Click on send test email

**Expected behaviour**
It should send the test email to my gmail address, i want to use SMTP because without phpmailer the forum is not sending emails to outlook/hotmail address, i tried with a whmcs installation and to fix it i had to add some MX and TXT records, but with the namelessmc installation it isn't working

**Screenshots**
![image](https://user-images.githubusercontent.com/16471265/86496001-6e5be580-bd49-11ea-8d30-a34a37ff8227.png)
This is the error that i get when i send a test email

**NamelessMC version (from AdminCP -> 2.0.0-pr7)**

**Comment by Aberdeener** [comment]
Hey!
Please join our discord for quick support with things like this; https://discord.gg/j2UFTg

This is probably a configuration error, but if it is an issue on our side I will reopen this. Thanks :)

**Comment by M4T14SG4M3R** [comment]
![image](https://user-images.githubusercontent.com/16471265/86496255-87b16180-bd4a-11ea-80f0-b4c7d3305031.png)

**Comment by Aberdeener** [comment]
Strange, try this one https://discord.gg/22xcuUV
