### ISSUE TITLE
"Follow this thread" forum option for threads 

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1738]
**Please describe the feature in as much detail as possible**
Just like on github "subscribe to thread to receive notifications", when someone post something on that thread, you get alert that user {x} posted something on "{title}" thread.

I don't really know how many people will use this, I assume 50 / 50, not very sure.

**Comment by samerton** [comment]
Following topics already exists, there is a button at the top of each topic.

**Comment by StormyIceLeopard** [comment]
Does it send an email samerton?

**Comment by TheJoshue** [comment]
> Following topics already exists, there is a button at the top of each topic.

Oh wow, my mistake, very sorry for opening this.
I was persistently looking at the bottom of the topic and couldn't find it...

**Comment by samerton** [comment]
@StormyIceLeopard Users will be able to choose to receive email notifications in the next release.

**Comment by StormyIceLeopard** [comment]
Okay, cool
