### ISSUE TITLE
Question: How does the "reset Password" button work?

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#174]
It doesn't seem to do anything when you press the reset password button. Could you shed some light on it?

**Comment by samerton** [comment]
Upon clicking the reset password button, an email is sent to the email address associated with that account containing further instructions.
You need to ensure the server is correctly configured to send email messages or else the reset password functionality won't work.

**Comment by WASasquatch** [comment]
There should always be confirmation messages with actions online, its a
standard and in some jurisdictions unlawful to not prompt users or show
confirmations.

Its always always best to assume the end users have no idea how to website
and to explain your system with some sort of tour or help page.

**Comment by samerton** [comment]
There is indeed a confirmation message, along the lines of "Please check your emails for further instructions" if the request was successful.

**Comment by WASasquatch** [comment]
Is this reliant on JS and browser specific? Much like OP described, nothing
happened besides getting the email.

**Comment by samerton** [comment]
Shouldn't do, it simply uses server session variables to display the message to the user.
Just to be sure, are you referring to the "Reset Password" option in the AdminCP's Users tab, or a reset password function elsewhere?

**Comment by WASasquatch** [comment]
I'm speaking of by user.

On Sun, Apr 17, 2016 at 2:03 PM, Sam <notifications@github.com> wrote:

> Shouldn't do, it simply uses server session variables to display the
> message to the user.
> Just to be sure, are you referring to the "Reset Password" option in the
> AdminCP's Users tab, or a reset password function elsewhere?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/NamelessMC/Nameless/issues/174#issuecomment-211116546>
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
