### ISSUE TITLE
Unread content button

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1741]
Title says half of feature description.
If this https://github.com/NamelessMC/Nameless/issues/1695 gets implemented, then this can be added too.

Example (I took a screenshot from https://cubedcraft.com/forum/ and edited it):
![image](https://user-images.githubusercontent.com/56804505/86513343-be01e600-be09-11ea-8d99-8ec092ddd465.png)

**Comment by samerton** [comment]
Merging with #1695
