### ISSUE TITLE
Report Module (for some MC plugin)

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1742]
**Please describe the feature in as much detail as possible**
This can be EXTREMELY useful, if somebody reports a player ingame, this will go through a database and list it on a site so moderators/admins or members (with permission) can see, delete report (with permission), etc...

This will require either good report plugin for MC or making Nameless's own, but that will be a lot of work I know, just a good idea in my opinion.

**Comment by Derkades** [comment]
I'm pretty sure there is a reports system already, the plugin has a /report command

**Comment by TheJoshue** [comment]
If spigotmc plugin does have this function and reports go to site, I didn't know that it exists. On the spigotmc it only says that it has report command, nothing else; by that I assume that it'll show report on the site but I think maybe separate plugin can be made (very much smaller plugin that nameless plugin).
I mean this is just my personal thought on this, I think it should be better to have separated module and plugin for report and show them on the site just like infractions module... but yeah there are a lot more important modules to work on like CraftingStore integration module so this is very redundant

**Comment by Aberdeener** [comment]
Yep, the plugin sends reports to the website! Check your alerts/messages in the top right (on most templates). Thanks
