### ISSUE TITLE
Zoom an image on image click

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1746]
**Please describe the feature in as much detail as possible**
Bigger preview of an image if image is clicked but only if there are no links on image click.
This is for forum posts.

**Comment by Aberdeener** [comment]
This would not be an easy addition by any means. If you want an image to get bigger when it is clicked on, try a new tab imgur link.

**Comment by Derkades** [comment]
You might like the "Imagus" browser extension
