### ISSUE TITLE
Disable switching templates if only 1 is active

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1747]
I don't really know why this will be present.
More better function is for any template developer to add themes to his template (integrated function of switching themes built in certain template) so we can switch from white to dark "mode" of one certain template.

Using more templates is cool, I like that feature but if I will use 1 template and not change it to another at all, I'll activate only that one template, make it default (other templates: not active at all), and not let people have that blank field in their Profile Settings that says "Active Template" where they can't choose any template because there's only 1 active and default.

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/0ee0dfdb13355d25235c592d4e38a6a7facd5f0b
