### ISSUE TITLE
Banned label / tag for user who is banned

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1748]
**Please describe the feature in as much detail as possible**
Title describes 50% of the idea.
Maybe something like ~This~ to be used to indicate that user is banned + when you go to user's profile, there will be *italic message* that will be the exact same text which mod/admin inserted as a reason for banning that user.

**Comment by samerton** [comment]
I'll close in favour of https://github.com/NamelessMC/Nameless/issues/896
