### ISSUE TITLE
Field icons in installer are misaligned

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1753]
![image](https://user-images.githubusercontent.com/15892014/87355829-52362080-c561-11ea-9991-e27c161eca86.png)

**Comment by Aberdeener** [comment]
Yeah, noticed this and a bunch of other stuff with the installer. Not sure why it wasn't tested more first....

**Comment by IsS127** [comment]
According to Xemah, the language selector is not working as well

**Comment by Aberdeener** [comment]
Added in #1630, @itzarty can you please take a look at this?

**Comment by ItzArty** [comment]
I'll take a look at that, haven't encountered that when I was testing the remake

**Comment by Derkades** [comment]
New installer, no longer an issue 5100d0f
