### ISSUE TITLE
Unlisted Forum

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1755]
I wish to have a forum that cannot be viewed/listed under the forum list/page but with direct links, such as create new topic, then you can create topics in the hidden forum.

Think of it as an unlisted YouTube video.

**Comment by Aberdeener** [comment]
I really like this idea! Thank you. Will look at my to-do list and possibly self assign. Thanks dude

**Comment by samerton** [comment]
Is this already possible if you just don't assign the forum a parent?

**Comment by Derkades** [comment]
@StormyIceLeopard is samerton's suggestion a solution to your problem?

**Comment by StormyIceLeopard** [comment]
How do I not set a parent forum? The dropdown forces me to pick a parent forum, no option for none.

**Comment by BaxAndrei** [comment]
Did you try to create it on ROOT like how do you do with categories?
