### ISSUE TITLE
Permission based links

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1756]
So you can create custom pages and have the links in the navbar.
How about adding permissions to that.
Example, Staff only page and I want the link in the navbar but do not want anyone without permission to see the link (makes the navbar cleaner)

I am unsure if this would become a built-in feature or a module.

**Comment by Aberdeener** [comment]
Don't custom pages have group permissions...?

**Comment by StormyIceLeopard** [comment]
Oh, was unaware that if you do not have permission to view page that it would remove the link from the navbar.
Okay, Closing. Thanks.
