### ISSUE TITLE
404 by install.

### ISSUE THREAD

**Issue by QuadDepo** [NamelessMC/Nameless#176]
I know there are a lot of topics about this.
but i just cant get it to work can someone please help me i dont really have any experience with webhosting/server stufff

-QD

**Comment by Schwertspize** [comment]
You are not giving much information, anyway I think the htaccess isn't working properly, I had to fix that in my own installation too

**Comment by QuadDepo** [comment]
What information do you need? Thanks for helping btw

**Comment by samerton** [comment]
You said in the post on the Nameless site that you can't download the .htaccess file; it is included by default in the download, however if you're using a Mac or Linux, these files are hidden and you won't be able to see them. If this is the case, [here is a guide for Mac](http://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/), there are similar guides for Linux based systems.

If you're using Windows, .htaccess files are visible by default, so I can't see why you wouldn't be able to see them. Try creating a file manually in your web server's root directory (alongside the index.php file, and the cache, core, pages etc directories). Name it ".htaccess", and make sure it has [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess) inside.

**Comment by samerton** [comment]
I'm going to close this issue as I believe it's a server configuration issue, or a case of missing files. If you're still experiencing this issue, feel free to re-open.
