### ISSUE TITLE
We need chinese!

### ISSUE THREAD

**Issue by xiaomoy** [NamelessMC/Nameless#1761]
We need chinese!
Thank you

**Comment by samerton** [comment]
Hi,

Nameless version 2 supports Chinese characters (as long as the character set is set to "unicode" in the installer) and also has a Chinese + Chinese Simplified translation, you can find the latest version 2 pre-release here: https://github.com/NamelessMC/Nameless/releases/tag/v2.0.0-pr7

**Comment by xiaomoy** [comment]
This is Traditional Chinese

**Comment by xiaomoy** [comment]
> 你好
> 
> 无名版本 2 支持汉字（只要字符集设置为安装程序中的"unicode"），并且具有中文 + 中文简体翻译，您可以在此处找到最新版本 2 预[发行：https://github.com/NamelessMC/Nameless/releases/tag/v2.0.0-pr7](https://github.com/NamelessMC/Nameless/releases/tag/v2.0.0-pr7)

This is Traditional Chinese

**Comment by Derkades** [comment]
> This is Traditional Chinese

What is? Since Samerton's quote in your post contained Chinese characters, did you mean his message? In that case please know that his message was in English, if it appeared for you in Traditional Chinese that was done by some sort of automated translation program

**Comment by samerton** [comment]
We don't create the translations ourselves (I can only speak English), so the translations within Nameless are provided by members of the community.

**Comment by xiaomoy** [comment]
> > This is Traditional Chinese
> 
> What is? Since Samerton's quote in your post contained Chinese characters, did you mean his message? In that case please know that his message was in English, if it appeared for you in Traditional Chinese that was done by some sort of automated translation program

Oh, there seems to be something wrong with my .htaccess

**Comment by xiaomoy** [comment]
> We don't create the translations ourselves (I can only speak English), so the translations within Nameless are provided by members of the community.

Um thanks
