### ISSUE TITLE
Manual mass email to website users

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1762]
This might already be a feature, if so I apologize.
How about when users sign up their email gets put into a list that can get email alerts about forums of our choosing and custom emails sent from the CP. And users can opt-out via their account and then they are just not included in the list.

Does this make sense?

**Comment by Derkades** [comment]
See #726

**Comment by StormyIceLeopard** [comment]
Yes, except for one key difference.
What if I wish to send an email manually? Like something I wish to say to my users but not post on the website.

**Comment by Aberdeener** [comment]
So basically just a newsletter?

**Comment by StormyIceLeopard** [comment]
Aren't newsletters automated? I am looking for a one-time manual email to send out.
Like one example is to inform all users of a change to some policy for example.

**Comment by Derkades** [comment]
Would a feature that exports all user emails to a semicolon separated list suffice? You can copy it to your mail client's BCC box and send a mass email.

If you need it now and you know PHP you can write a script to do this easily by querying the database

**Comment by StormyIceLeopard** [comment]
That actually would be great.
Sadly I do not know much PHP and I would like it directly in the website StaffCP as well an additional feature/check.
Users can opt-out and those who choose to do so are not included in said list.

But that would work, and it sounds like a module that can be created.

**Comment by Aberdeener** [comment]
🟠 Development started, please wait...
