### ISSUE TITLE
More custom profile fields options

### ISSUE THREAD

**Issue by EatMyHitzz** [NamelessMC/Nameless#1763]
A function to create a full profile - Like with images, description, social media etc.
Something like a image gallery and a description about yourself would be cool

**Comment by EatMyHitzz** [comment]
Hyfallsvandaag om 02:12
Maybe a new custom profile field option using the rich editor? Not sure if it would look good. @Aber [CA-PST]

**Comment by Aberdeener** [comment]
Thanks, I'll self assign and finish this once I am done #1764
