### ISSUE TITLE
Update fontawesome

### ISSUE THREAD

**Issue by nUKEmAN4** [NamelessMC/Nameless#1766]
**Please describe the feature in as much detail as possible**
There are some "new" icons in 5.14 that cannot be used with current version on namelessmc.
https://cdnjs.com/libraries/font-awesome

EDIT: Im not sure will it break current website because they MAY have changed names but I dont think they have changed it. xd

**Comment by Aberdeener** [comment]
@samerton Thoughts? Are we purposely on a more "legacy" version?

**Comment by samerton** [comment]
Upgrading sounds good to me 👍

**Comment by Aberdeener** [comment]
Updated in e3ebd18
