### ISSUE TITLE
Per thread (topic) group permissions 

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#1767]
Permissions for each group only for certain topic in some forum, that has higher priority (if used for any group) than global forum/category permissions

**Comment by Aberdeener** [comment]
This gave me a headache just to read. 
I don't see how this would be used in the real world, and it adds complexity to a simple task as making a topic. Not worth the hassle imo.

**Comment by Derkades** [comment]
Yeah, I would say that this feature is too niche to implement as well. 

In some cases something like this would be useful, for example for locking posts with a lot of spam replies to trusted roles. However, this specific use case can be solved by having a locking feature with a configurable minimum participation level.

@TheJoshue What specific problem are you trying to solve? Maybe there's an easier way to accomplish what you want

**Comment by Derkades** [comment]
not going to happen
