### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Lmmb74** [NamelessMC/Nameless#177]
Hi, I am trying to install nameless on my webserver (php 5.6) but the index page doesn't display anything. Please help me

**Comment by samerton** [comment]
Can you ensure the **cache** directory and its subdirectories are writable for the Apache/PHP process?

**Comment by Lmmb74** [comment]
I don't know how to check it, please tell me where.

**Comment by ThemInspectors** [comment]
cd "/var/www/html" or wherever your directory specified is
then do "ls -la"
and make sure it looks under cache tell me what it looks like supposed to look like -rwxrwxrwx

**Comment by Lmmb74** [comment]
drwxr-xr-x

**Comment by Lmmb74** [comment]
Also, I'm on windows.

**Comment by samerton** [comment]
When you say you're on Windows, is that your computer's OS, or are you hosting the website itself on Windows? If you're hosting the website on Windows, which web server software are you running it on?

If you're running the web server on Linux, is it Debian/Ubuntu/CentOS etc?

**Comment by Lmmb74** [comment]
I am hosting the website on my pc, Windows system, WAMP Server

**Comment by ThemInspectors** [comment]
to should look like drwxrwxrwx

**Comment by ThemInspectors** [comment]
I don't use Windows so I don't know how the permission changing would look like, it may work on windows but try "chmod 777 -R cache"

**Comment by Lmmb74** [comment]
{drwxr-xr-x  3 lauti Administradores    0 Apr 21 21:27 cache}
Nope

**Comment by ThemInspectors** [comment]
I have no idea whatsoever with changing permissions on windows,
though try to use a terminal Emulator like git bash to use chmod command

**Comment by Lmmb74** [comment]
I used git bash but it didn't work

**Comment by ThemInspectors** [comment]
Was the emulator on the client or server?

**Comment by Lmmb74** [comment]
the server is my pc

**Comment by ThemInspectors** [comment]
can't you edit permissions with a very scruffy GUI?

**Comment by Lmmb74** [comment]
no idea, I tried with both built-in windows permissions system and git bash

**Comment by Lmmb74** [comment]
also I installed linux commands on windows console

**Comment by ThemInspectors** [comment]
go into your server root directory
do "chmod -R 777 ." All done?

**Comment by ThemInspectors** [comment]
make sure it's a linux terminal

**Comment by Lmmb74** [comment]
I did (git bash)

**Comment by ThemInspectors** [comment]
does it work?

**Comment by Lmmb74** [comment]
Nope

**Comment by Lmmb74** [comment]
I thought it was a problem with php version

**Comment by Lmmb74** [comment]
Using php 7.0 didn't cause me any error

**Comment by ThemInspectors** [comment]
have you tried doing ls -l again?

**Comment by Lmmb74** [comment]
drwxr-xr-x 1 lauti 197609    0 abr. 21 18:27 cache/

**Comment by Lmmb74** [comment]
Still not working

**Comment by ThemInspectors** [comment]
it's still not read, write, execute on all of the groups

**Comment by Lmmb74** [comment]
I know

**Comment by Lmmb74** [comment]
I will try using git bash as admin

**Comment by ThemInspectors** [comment]
yeah use "sudo chmod -R 777 ."

**Comment by ThemInspectors** [comment]
or admin I forgot windows doesn't have a root user

**Comment by Lmmb74** [comment]
Nope, not working

**Comment by ThemInspectors** [comment]
so what is your username?

**Comment by Lmmb74** [comment]
Where? In console?

**Comment by ThemInspectors** [comment]
yes
do "whoami"

**Comment by Lmmb74** [comment]
desktop-0fmnrqp\lauti

**Comment by ThemInspectors** [comment]
okay so it's not an owning issue

**Comment by Lmmb74** [comment]
.________________.

**Comment by Lmmb74** [comment]
u.u

**Comment by Lmmb74** [comment]
<Directory "F:/Web/Bitnami/apache2/htdocs/cache">
    Options Indexes FollowSymLinks
    AllowOverride All
</Directory>
I am trying that now in httpd.conf

**Comment by Lmmb74** [comment]
```
<Directory "F:/Web/Bitnami/apache2/htdocs/cache">
    Options Indexes FollowSymLinks
    AllowOverride All
</Directory>
```

**Comment by ThemInspectors** [comment]
Well, so it may be a disk permission block out, it's not on the C: drive

**Comment by ThemInspectors** [comment]
Does this work?
![dalek](https://cloud.githubusercontent.com/assets/17802324/14730320/a72b3a60-0802-11e6-9613-751f648a88b7.jpg)

**Comment by ThemInspectors** [comment]
Try moving & recorrecting your webserver files onto the "C:" drive

**Comment by Lmmb74** [comment]
Not working, also I didn't have trouble using the F: drive the last time

**Comment by ThemInspectors** [comment]
maybe fix is: sending the files over I fix the permissions and send it back with drwxrwxrwx permissions

**Comment by Lmmb74** [comment]
Ok, skype?

**Comment by samerton** [comment]
Do you have access to phpMyAdmin, or another method of changing the database? If so, can you enter the **nl1_settings** table, find the row where "name" equals "error_reporting", and change the "value" column from 0 to 1?
Hopefully we'll see an error on the page instead, provided the installation process worked successfully.

**Comment by Lmmb74** [comment]
I don't have access to installation page, it is not installed. When I access to the web, it displays a white screen.

**Comment by samerton** [comment]
Not sure what could be happening, can you try the steps beneath "If the installation process didn't work successfully:" in my previous post?

**Comment by ThemInspectors** [comment]
@samerton I believe it's a permission issue

**Comment by samerton** [comment]
True, however it's best to get the exact error message in case there's another factor in play.

**Comment by Lmmb74** [comment]
`
Warning: require_once(): open_basedir restriction in effect. File(F:\Web\Bitnami\frameworks\smarty\libs\Autoloader.php) is not within the allowed path(s): (F:\Web\Bitnami\apache2\htdocs;F:/Web/Bitnami/php/tmp) in F:\Web\Bitnami\apache2\htdocs\core\includes\smarty\Smarty.class.php on line 82

Warning: require_once(F:\Web\Bitnami\frameworks\smarty\libs\Autoloader.php): failed to open stream: Operation not permitted in F:\Web\Bitnami\apache2\htdocs\core\includes\smarty\Smarty.class.php on line 82

Fatal error: require_once(): Failed opening required 'Autoloader.php' (include_path='.;F:/Web/Bitnami/php/PEAR;F:/Web/Bitnami/frameworks/smarty/libs') in F:\Web\Bitnami\apache2\htdocs\core\includes\smarty\Smarty.class.php on line 82`

**Comment by samerton** [comment]
This could be an issue with Bitnami, as it looks like it's trying to include the wrong Smarty files. Could you possibly switch from Bitnami to different software?

**Comment by Lmmb74** [comment]
Maybe I should take it to F: drive as before, and not a subfolder

**Comment by samerton** [comment]
If Nameless itself is installed in a subfolder (ie yoursite.com/nameless), it will need to be moved into the root directory.

**Comment by talibanes** [comment]
que tal?
 

    On Friday, April 22, 2016 11:09 AM, Lmmb74 <notifications@github.com> wrote:
 

 Maybe I should take it to F: drive as before, and not a subfolder—

**Comment by Lmmb74** [comment]
It is in root folder

**Comment by samerton** [comment]
If it's already in the root folder, it'd be an issue with the web software. For some reason, Bitnami is calling Smarty from within its own installation, rather than the Smarty files within Nameless.
If you're just installing this on your local machine to play around with, can I suggest using XAMPP as the web server software? It will work with Nameless straight out of the box.

**Comment by Lmmb74** [comment]
Maybe I just need to uninstall smarty from wamp, just that

**Comment by samerton** [comment]
Sure, if that's a possibility, could you try that?

**Comment by Lmmb74** [comment]
Ok

**Comment by Lmmb74** [comment]
IT WORKED =D =D =D 
Check this as solved pls

**Comment by samerton** [comment]
Glad it's resolved :)
