### ISSUE TITLE
Change the banner from your profile settings

### ISSUE THREAD

**Issue by EatMyHitzz** [NamelessMC/Nameless#1770]
Suggestion:
Change the banner from your profile settings
![screenshot](https://cdn.discordapp.com/attachments/735294470005850115/735643085735723028/unknown.png)

For example below the function to change the avatar

**Comment by kacperleague9** [comment]
Its working in Mooz template if you need it !

**Comment by Aberdeener** [comment]
^
This seems doable from a template level. closing

**Comment by Derkades** [comment]
Isn't this something that should be included in the default template?

**Comment by Aberdeener** [comment]
Ah yeah. DefaultRevamp has it, i'll see about doing Default now

**Comment by Aberdeener** [comment]
So uhhh, this does exist. @EatMyHitzz are you running pre7?
