### ISSUE TITLE
Support for Package Subscriptions in Tebex Module

### ISSUE THREAD

**Issue by nathan93** [NamelessMC/Nameless#1774]
As the title says, right now the Tebex integration module does not support packages that are subscriptions, only on-off purchases. Would it be possible to have the Tebex integration have support for packages that can be purchased as subscriptions as well?

Thank you

**Comment by samerton** [comment]
Hi,

Thanks for the report, could you please open this in https://github.com/samerton/Nameless-Tebex instead? Thanks

**Comment by Derkades** [comment]
@samerton note that GitHub has a feature that lets you do this now, see "Transfer Issue" on the right

**Comment by samerton** [comment]
@Derkades exactly, because the module isn't part of the organisation it's not possible to transfer the issue
