### ISSUE TITLE
New (5.14) Font Awesome icons not displaying when SemUI `icon` class is applied

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1776]
See image (using announcements): ![alt](https://i.imgur.com/FnhBNJT.png)

-**The purple announcement has the `icon` class applied (`<i class="fas fa-disease icon"></i>`), and does not work.**
-The green announcement does not have the `icon` class applied (`<i class="fas fa-disease"></i>`), and works (but not the right size - see red one below it).
-The red one has the `icon` class (`<i class="fas fa-edit icon"></i>`) and works exactly how i want the purple one to work. this seems to be the case for all fontawesome icons, except the ones added in 5.14...

The `icon` class adds padding and other important styles to icons in announcements which makes them look bigger and centred (the same size and location of the broken empty box in the purple announcement).
I'm not certain why this is only happening with new FA icons.
@samerton Any ideas?

**Comment by samerton** [comment]
Since these are two separate libraries, I don't think this is supported at all by either of them so I don't think there's anything we can/should do about this.

Maybe try using a combination of Font Awesome classes? eg `fa-fw fa-2x` to make the icon a fixed width + give it 2x size

**Comment by Aberdeener** [comment]
Yeah, I'll look into a custom class

**Comment by samerton** [comment]
I'll mark this as closed as I don't think it's really something we should support - Font Awesome and Semantic UI icons are two separate libraries that we allow users to use
