### ISSUE TITLE
Retire old "Default" template

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1785]
The "DefaultRevamp" template looks much better than the old "Default" template, I don't think anyone still uses the old theme (maybe do a poll in discord?).

I propose removing the "Default" template and renaming "DefaultRevamp" to "Default". This saves time during development because there is no longer the need to add every feature to two templates.

**Comment by Aberdeener** [comment]
Cannot agree more. 🙌

**Comment by samerton** [comment]
How do we handle the transition for existing sites? 

If we rename Default Revamp to Default, if you have a site with Default Revamp active then they'll have an orphaned active template which won't be updated when they upgrade.

**Comment by Derkades** [comment]
That is indeed a difficult decision. Is it possible to change the active template before upgrading?

Right now with v2 still being a pre-release this is the only good opportunity to make a large breaking change like this. Otherwise, I'm afraid it'll stay for a long time and require updates for every new feature.

**Comment by StormyIceLeopard** [comment]
I agree, we need to start the transition now or it will never go away.

**Comment by Aberdeener** [comment]
@Derkades yeah, that's possible by just adding a query in the upgrade script, but I'm sure it would shock some people who have used it for a long time. I agree about the pre release, if we don't do it now it'll never happen *cough* v1 *cough*

**Comment by CqldFire** [comment]
Yes please remove default, default revamp is so much better

**Comment by WhenUHackUNoob** [comment]
Much agreed with @CqldFire

**Comment by Aberdeener** [comment]
Bump.
The more I think about how to handle this, the harder it becomes to come to a solid decision.
However we handle this, users will be thrown off.
> Right now with v2 still being a pre-release this is the only good opportunity to make a large breaking change like this. 

As Derk said, this is a fine time to do it.

A possible solution:
- Delete Default template and **do not** ship  pre8 with it.
    - This causes the root issue of not needing to maintain an older template.
- **Do not** rename DefaultRevamped.
    - This fixes any possible issues with overlapping template names
- **Do not** add any more support to Default template for pre8 features.
    - Saves me time when adding new features for pre8
- Add a warning message to any sites still using Default template that support for it has been dropped.
   - Warns users they should change templates before pre9/v2 as no new features will work on it, and that pre8 features may be missing as we dropped support for it.

Let me know what you guys think! -Tadhg

**Comment by CqldFire** [comment]
@Aberdeener Yep sounds good, totally agree with you
