### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1786]
I'll edit this issue description with any conclusions drawn in the comments, when it seems like we have defined everything it can be put in a markdown file in the repo or on the wiki.

Default phpcs settings with the following differences:

- Use keywords like functions (e.g. `echo("Something")`)
- 120 character line limit instead of 85

How to use on vscode on ubuntu:
```
apt install php-fpm php-codesniffer
```
Install `phpcs` extension in vscode

**Comment by Derkades** [comment]
Most important right now: tabs or spaces? how many spaces? possibly different number of spaces for HTML and PHP? Should code in `<?php` blocks be indented? How about css in `<style>`?

**Comment by Xemah** [comment]
I personally use tabs, and I don't indent the code in `<?php` block

**Comment by samerton** [comment]
I'd say 2 space indentations, like so:

```php
<!doctype html>
<html>
  <head>
    <title>Test</title>
    <style>
      body {
        background-color: #000;
        color: #fff;
      }
    </style>
  </head>

  <body>
    <?php
    foreach($var as $item){
      echo $item;
    }
    ?>
  </body>
</html>
```

**Comment by Derkades** [comment]
phpcs suggests no parentheses for statements (so `require 'file.php'` not `require('file.php')`, what do you think?

**Comment by partydragen** [comment]
well require('file.php') looks nicer xD

**Comment by samerton** [comment]
Agree with partydragen, for me require() looks nicer

RE https://github.com/NamelessMC/Nameless/commit/7e0e98862a6fa95a2219313a83834df06790bca6#diff-59736aecc611cda3c8a10fbb4681b15045c56f8c2a786bd3c154dacdcb03abbb

Because HTML can end up with some deep indents, can we keep HTML as 2 space indentations, also indent <head> after <html>

**Comment by Derkades** [comment]
> Because HTML can end up with some deep indents, can we keep HTML as 2 space indentations

I would do this for HTML templates that are separated from PHP code, but in this case one file had both and IDEs only support one indentation type per file. It can be done manually if you really want to though.
