### ISSUE TITLE
Confusing usage of carets in profile 'About' page

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1787]
In the About page, it uses carets like a `<ul>` unordered list:
![image](https://user-images.githubusercontent.com/15892014/88893931-62c7e580-d247-11ea-8575-473e3064e911.png)
Carets are usually used for collapsable content so this is confusing in my opinion

**Comment by Xemah** [comment]
What about this?
![image](https://i.xemah.com/kpEJ.png)

**Comment by Derkades** [comment]
That looks good. Can the icons be centered vertically across both lines?

**Comment by Xemah** [comment]
![image](https://i.xemah.com/OcFx.png)

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/pull/1822
