### ISSUE TITLE
Fatal error Uncaught  --> Smarty: Unable to load template 

### ISSUE THREAD

**Issue by PineAppleGrits** [NamelessMC/Nameless#1788]
**Describe the issue**
When i try to enter in the panel a error message happens:

![image](https://user-images.githubusercontent.com/66481194/89054272-ea3c5400-d32e-11ea-94e2-9bdf41299123.png)

`Uncaught  --> Smarty: Unable to load template 'file:collections/dashboard_stats/total_users.tpl' <-- 
  thrown`

**NamelessMC version (from AdminCP -> Overview)**
I cant see that* but i think 2.0.7
**Additional information**
I cant solve it and i dont understand how to solve it, lmao.

**Comment by BaxAndrei** [comment]
Do you use custom template?

**Comment by PineAppleGrits** [comment]
yes

**Comment by Aberdeener** [comment]
The custom template does not support this module/page. Contact the developer

**Comment by PineAppleGrits** [comment]
In panel im using default template 
![image](https://user-images.githubusercontent.com/66481194/89058437-adc02680-d335-11ea-96b2-126fb281a702.png)
And in the global i use aether template but i tried to change it to default doing this 
![image](https://user-images.githubusercontent.com/66481194/89058504-c6c8d780-d335-11ea-8a7f-b3af7139826a.png)

That 1 was on aether and i changed to DefaultRevamp but the template still

**Comment by PineAppleGrits** [comment]
why do u close the thread so fast? im asking for help and u just close this.

**Comment by samerton** [comment]
The panel template on your website (custom/panel_templates/Default) is missing some files. Please can you reupload from the Nameless files on your computer

**Comment by samerton** [comment]
I'll mark this as closed as it's not a Nameless issue
