### ISSUE TITLE
Cant change template

### ISSUE THREAD

**Issue by PineAppleGrits** [NamelessMC/Nameless#1789]
My issue is that i cant change the template again, so i cant return to default instance, that means i cant enter my panel so i cant change that from panel, i need help to go back to default template without delete my data. Can you all help me with that? please.
The error is this: 
![image](https://user-images.githubusercontent.com/66481194/89059533-be719c00-d337-11ea-8425-9293c26b6747.png)
I dont care about this template, i just want to enter the panel and change the template to default one.

**Comment by Derkades** [comment]
If you were able to solve your problem it might be useful to post the solution here in case someone with a similar problem finds this issue in the future
