### ISSUE TITLE
Advertenzia

### ISSUE THREAD

**Issue by talibanes** [NamelessMC/Nameless#179]
Ya llego?

**Comment by Lmmb74** [comment]
?

**Comment by samerton** [comment]
Hi,

Could you try and translate your issue into English? 
I've tried to translate it myself using Google Translate but I'm not able to understand your issue.

**Comment by Lmmb74** [comment]
He only posted Warning as Title, and the text says:
Has it arrived?

**Comment by Lmmb74** [comment]
idk why he posted this

**Comment by samerton** [comment]
If you're referring to Nameless being released, you can find the releases [here](https://github.com/NamelessMC/Nameless/releases).

I'm going to mark this issue as closed.
