### ISSUE TITLE
Plugin Dev role

### ISSUE THREAD

**Issue by WhenUHackUNoob** [NamelessMC/Nameless#1793]
It would be nice if you could ping Plugin Dev on discord so the Support role belongs to the support channel and the Plugin Dev role belongs to the plugin support channel.

**Comment by Aberdeener** [comment]
Except derkades is the only plugin dev now. It even says in the channel description to tag him.
@Derkades what do you think

**Comment by Derkades** [comment]
Good idea, I've added it

**Comment by WhenUHackUNoob** [comment]
Yeah I suggested it as @IsS127 does also have the plugin dev role..
