### ISSUE TITLE
Enabling Staff Apps causes 500 server error

### ISSUE THREAD

**Issue by smishcraft** [NamelessMC/Nameless#18]
When Ever I enable the staff apps module it causes a 500 Server error. This is on shared hosting and no other websites are effected by it so we know its not the server. Any help?

**Comment by samerton** [comment]
Hopefully fixed in the [latest commit](https://github.com/NamelessMC/Nameless/commit/9aa54698e56134f4164baa727b60827c063d7adb); it appears I missed out an important file with the initial commit. 
Can you try to add the file in the latest commit to see if it helps?

**Comment by smishcraft** [comment]
It works now thank you.
