### ISSUE TITLE
MySQL table not generating

### ISSUE THREAD

**Issue by winnipeg21** [NamelessMC/Nameless#1806]
**Describe the issue**
Getting a `Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_forums.nl2_panel_templates'` after installing my forums. Tried reinstalling, same issue.

**To Reproduce**
Steps to reproduce the behaviour:
Legit just installing the latest pre-release (v2 7) 

**Expected behaviour**
Everything should work!

**Screenshots**
https://s.pingu.ga/f3Isc

**NamelessMC version (from AdminCP -> Overview)**
https://s.pingu.ga/48eYQ

**Comment by Aberdeener** [comment]
Hey - sorry about the issue. Never heard of this before.
Using either the MySQL command line or PhpMyAdmin, you can run this query:
```sql
CREATE TABLE nl2_panel_templates (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(64) NOT NULL, `enabled` tinyint(1) NOT NULL DEFAULT '0', `is_default` tinyint(1) NOT NULL DEFAULT '0', PRIMARY KEY (`id`))
```
to manually make the table.
Reopen the issue if you need anymore help with this!
