### ISSUE TITLE
AuthMe Integration turned on (Cant login)

### ISSUE THREAD

**Issue by IcEeM** [NamelessMC/Nameless#1808]
Hello,

I installed namelessmc 2.0 pr7 today and I setted up authme intergration. I setted the database up and everything like in my AuthMe config (SHA256, password etc everything same) After that, It logged me out and now i cant connect with my e-mail adress or with my name + password. I tried to reset my password but didnt helped.

**Comment by samerton** [comment]
Hi,

A quick fix is to log into the database using a tool like phpMyAdmin and find the entry where `name` is `authme` in the table `nl2_settings`, then update the `value` to `false`

**Comment by Aberdeener** [comment]
Hey!
I'll close this now, but if you still need help, feel free to reopen it. 
Cheers.
