### ISSUE TITLE
Everything is missing from my website except index.php

### ISSUE THREAD

**Issue by xBreaksx** [NamelessMC/Nameless#181]
Continuing from the title, every time I click on any button in the navbar, it says "Not Found", "The requested URL /forum was not found on this server.", and "Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request." Please help with this issue. I'm currently using a Web Hosted website that has Unix (I believe) on it.

**Comment by Schwertspize** [comment]
You got a problem with your htaccess. Try removing the first line and reload the page (I myself had that problem a few times)

**Comment by samerton** [comment]
Have you installed Nameless in a subfolder? If so, can you move it into the root directory, or alternatively point a subdomain to said subfolder.
Otherwise, as it's a hosted site, I'm not sure what the problem could be (if @Schwertspize's suggestion doesn't work).

**Comment by xBreaksx** [comment]
Hi samerton, fortunately we got our website to work after deleting the first line in our htaccess. Thanks!

**Comment by samerton** [comment]
Hi,

Glad it's working!
