### ISSUE TITLE
editing a forum post breaks all formatting when set to markdown editor

### ISSUE THREAD

**Issue by emkirsh** [NamelessMC/Nameless#1823]
**Describe the issue**
So, I was copying (and subsequently, reformatting) a post from my old forum. This post had a lot of links. I realized I forgot one line after posting it, and went to edit it. I saw that a bunch of stuff got changed and re-formatted. However, all the links broke. It went from a nice `[discord](https://discord.atomicmc.net)` to `[<a>https://discord.atomicmc.net]</a>(a href=)">join the Discord server`, which looks like going from [discord](https://discord.atomicmc.net) to <https://discord.atomicmc.net>">discord
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'forum'
2. Click on 'new thread'
3. put a lot of markdown in it
4. post it
5. Click 'edit post'
6. change the first line to be a header 4 (`####`) (also not sure if this part is relevant at all but thats the change I happened to make)
7. watch it all break

**Expected behaviour**
It works properly and edits like it should

**Screenshots**
https://gyazo.com/d07b7cb83d159abb602576d0681f69a4

**NamelessMC version (from AdminCP -> Overview)**
it *says* 2.0.0-pr7 but it's actually the latest dev build.

**Additional information**
I don't think there's much else to add.

**Comment by samerton** [comment]
Unfortunately I'm still inclined to remove Markdown altogether for v2's release so we can focus on maintaining just one format method. Markdown's been neglected for a while now and would need a lot of work to bring it up to scratch.

**Comment by emkirsh** [comment]
But, these are regular Minecrafters. Some of them are less than 10 years old. They're not going to know how to write HTML.

**Comment by emkirsh** [comment]
Perhaps you could add something like this? https://gyazo.com/013c3c047a182b23303dcde67d64499c

**Comment by Derkades** [comment]
@samerton Can you explain why you prefer HTML over Markdown? Markdown seems more suitable for this purpose to me. People who use discourse, github, discord, are already somewhat familiar with markdown.

**Comment by emkirsh** [comment]
+1

--Eli Kirshenbaum

________________________________

**Comment by emkirsh** [comment]
Also, I feel like if you remove it, someone will just fork the forum module and add the markup themselves, then everyone would be using an unofficial namelessMC forum module.

--Eli Kirshenbaum

________________________________

**Comment by samerton** [comment]
HTML input already has a visual editor with many more features than an existing Markdown editor. As a forum software, it's important to offer room for expansion too with new input types, and Markdown is more limited. It'll also allow admins to insert any HTML directly into forum posts, such as Javascript or similar (coming soon).

From what I know, the vast majority of websites use the HTML editor, only a small few use Markdown, and it's hard to maintain two different syntaxes.

Also I've not been able to find a Markdown editor that I like, I've spent hours searching and playing around with options but there's nothing that I feel is ready to add straight away with no additional customisations required.

**Comment by samerton** [comment]
I ran a poll at the start of 2019 and the general opinion was in favour of switching to bbcode if anything - rfgg3

**Comment by Derkades** [comment]
You do make some good points, HTML is good for stuff like iframes in custom pages. Would it make sense to use HTML for custom pages and markdown for forum posts? I guess not

**Comment by emkirsh** [comment]
Embedding videos _would_ be great. I have one more question, though: will the editor add things in a raw format, like `[b]bold[/b]` or will it look like **bold** in the editor?

**Comment by Derkades** [comment]
I think some markdown editors support basic HTML as well

**Comment by emkirsh** [comment]
Update: breaks using pure html as well. I coped pure html code into the editor and it works (breaks) just like markdown. It posts properly then breaks upon editing, even if you don't change a single character. [I recorded this to show you what happens.](https://i.gyazo.com/99d5a3e850dbda2da8113244df8cb5af.mp4) So, whether or not you ditch markdown, there's a severe editing bug that needs to be fixed before the v2 release. @samerton @Derkades

**Comment by emkirsh** [comment]
Also, I'm unable to embed videos, again using html not markdown.

**Comment by samerton** [comment]
Thanks for the video @emkirsh, you need to change the post formatting option in the StaffCP -> Configuration -> General Settings tab to use the HTML editor.

**Comment by emkirsh** [comment]
Ok! Hopefully that works!

**Comment by emkirsh** [comment]
That worked, thank you. I still can't embed video, though.

**Comment by emkirsh** [comment]
@samerton is there a way to embed video? Because other HTML editors have that feature but this one seems to break. From inspect element, it seems the issue could be related to the inability to change the source code so from what I can tell (and I'm not an HTML expert) it's all within a `<p></p>`

It's funny, the video works in the editor after posting and clicking edit, but not in the actual post.

**Comment by Derkades** [comment]
I have opened an issue for editor discussion: #1904

I'll change this issue back to bug instead of discussion since that's what it was originally about. However, I'll close this since the bug won't be fixed in the current editor.
