### ISSUE TITLE
Pages sometimes take 7 seconds to load(completely random times)

### ISSUE THREAD

**Issue by daronhudson** [NamelessMC/Nameless#1824]
**Describe the issue**
Usually when loading the website for the first time after about 30 seconds or so it decides to take up to 7 seconds to display any page(not just a group of specific pages).

**To Reproduce**
Steps to reproduce the behaviour:
1. Don't touch website for a moment
2. Touch website for a moment

**Expected behaviour**
It should just load up instantly like it does AFTER the time when it takes forever to load up.

**Screenshots**
https://media.discordapp.net/attachments/683444634579632174/752241912941117531/unknown.png

**NamelessMC version (from AdminCP -> Overview)**
2.0 latest release

**Additional information**
I get these in Other logs whenever I do anything:

/public_html/core/classes/ErrorHandler.php(43) 8: Trying to access array offset on value of type null

Just comes up over and over again. There's some other stuff too but not as common in there:

/public_html/cache/templates_c/58d429ff0f0b3a1f1acfac40a30bc2354f7793fd_0.file.footer.tpl.php(166) 8: Undefined index: PARTICLESJS
/public_html/cache/templates_c/58d429ff0f0b3a1f1acfac40a30bc2354f7793fd_0.file.footer.tpl.php(166) 8: Trying to get property 'value' of non-object

Just strange that it happens even after I reinstalled everything from the ground up. Everything is local the only outbound connection is the minecraft server query at half an hour intervals.

**Comment by Derkades** [comment]
Do you get this with a specific page or just any page? What kind of hosting service are you using?
