### ISSUE TITLE
Cannot switch webpage language to simplified Chinese

### ISSUE THREAD

**Issue by CanNian2002** [NamelessMC/Nameless#1825]
**Describe the issue**
Cannot switch webpage language to simplified Chinese

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Configuration'
2. Go to 'General Settings'
3. Click on 'Default Language'
4. Simplified Chinese option does not appear in the list after clicking the "+" button

**Expected behaviour**
What were you expecting to happen?

**Screenshots**
Show Simplified Chinese option, click to switch to Simplified Chinese language

**NamelessMC version (from AdminCP -> Overview)**
2.0.0 pre-release 7

**Additional information**
I hope to fix this issue as soon as possible. I wrote this issue with Google Translate because I don't understand English. Some places may not mean too right. I apologize to you here.

**Comment by CanNian2002** [comment]
But there is no simplified Chinese folder in the custom/languages folder.

**Comment by samerton** [comment]
It looks like the Simplified Chinese translation was added more recently than pre-release 7.

You can either wait for the next update, or download https://github.com/NamelessMC/Nameless/archive/219fe86be22c8b1d181c7ff43066c644f4eac6aa.zip and upload the **custom/languages/Chinese(Simplified)** folder to your website, and then download https://github.com/NamelessMC/Nameless/archive/2b8d20a1fb15faf315766aea0cf81b020786183f.zip and upload the **modules/Forum/language/Chinese(Simplified)** folder to your website.

**Comment by CanNian2002** [comment]
Okay, the language is switched normally.

**Comment by Aberdeener** [comment]
Thanks for your patience while solving this issue, CanNian!
I will close this now, but if you have anymore issues feel free to ask for help in our Discord.
