### ISSUE TITLE
can i help contribute to Nameless translation in Chinese Simplified

### ISSUE THREAD

**Issue by GamerNoTitle** [NamelessMC/Nameless#1837]
nameless is a pretty good forum system that i've ever used. and i want to translate it into Chinese(Simplified) since there's only traditional version of Chinese in the language folder
so how can i contribute to this?

**Comment by Aberdeener** [comment]
Hello!
Chinese Simplified has been added recently and is on the v2 branch.
[Located here](https://www.github.com/NamelessMC/Nameless/tree/v2/custom%2Flanguages%2FChinese(Simplified))
If you'd like to contribute, just make a pull request and we can merge it. Thank you
