### ISSUE TITLE
Filters for listUsers API

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1839]
One more change for #1836. Add filters for the [listUsers API method](https://github.com/NamelessMC/Nameless/wiki/v2-API#listusers-get)
- [ ] Verified yes/no
- [ ] Banned yes/no

For example: `GET /listUsers?verified=true&banned=false`

**Comment by Aberdeener** [comment]
🟠 `Development started... Please wait.`

**Comment by Aberdeener** [comment]
Added in 7d6176

**Comment by samerton** [comment]
@Derkades by this do you mean specifying verified=true would only return verified users?

**Comment by Derkades** [comment]
Yes, and `verified=false` will only return unverified users.

**Comment by samerton** [comment]
I'll reopen as this commit only hides/shows the fields in the response

**Comment by Aberdeener** [comment]
My bad, I misunderstood what was asked for.

**Comment by Derkades** [comment]
Didn't samerton mean it was better to use a filter in SQL instead of getting all data and filtering it later?
