### ISSUE TITLE
Mailjet does not use email address as SMTP Username

### ISSUE THREAD

**Issue by kubo6472** [NamelessMC/Nameless#1840]
When trying to test mail through mailjet smtp, it displays the following error: "Invalid address: (setFrom) censored"
I think it is because it expects something in an email form, not every service provides it that way.
Running NamelessMC version 2.0.0-pr7

**Comment by Aberdeener** [comment]
I'm not sure i understand your problem. 
Can you show us your email config? 
Please censor any private information!

**Comment by kubo6472** [comment]
![Screenshot_20200928-071319_Samsung Internet](https://user-images.githubusercontent.com/26146502/94392973-26870780-015a-11eb-8762-61c734ef5f09.jpg)
As I said, the username is a long string of characters. And for some reason I think nameless is expecting an email address, since the error it gives me.

**Comment by samerton** [comment]
Should hopefully be fixed in the next update (https://github.com/NamelessMC/Nameless/commit/5b8fabb79362e82ac6c2cd47d5882b71b69e5e17)
