### ISSUE TITLE
Fatal error when going to Templates in AdminCP

### ISSUE THREAD

**Issue by ItzPeto** [NamelessMC/Nameless#1845]
When trying to go to Templates in AdminCP it throws out this error:
Fatal error: Cannot declare class Default_Template, because the name is already in use in /var/www/html/custom/templates/Default/template.php on line 0

Running NamelessMC version 2.0.0-pr7

**Comment by Aberdeener** [comment]
Hello!

To fix this issue, open the nl2_templates table in your PHPMyAdmin, and delete any duplicate entries. Keep only 1 of each. If you want clairification, send a screenshot of the page here and I can tell you exactly which ones to delete.

This bug has been fixed for pre release 8.

Thanks!

**Comment by ItzPeto** [comment]
That fixed it! Thank you so much. <3
