### ISSUE TITLE
Add Post Prefill

### ISSUE THREAD

**Issue by JazzBroMC** [NamelessMC/Nameless#1846]
**Please describe the feature in as much detail as possible**

Add post prefill

This can be used for player reports, bug reports and suggestions on the forums

Just like github's post prefill would be fine

**Comment by Aberdeener** [comment]
This already exists, its called Topic Placeholder

**Comment by Derkades** [comment]
Go to yourdomain.com/panel/forms, select your forum and edit 'topic placeholder'
