### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by tricky538** [NamelessMC/Nameless#185]
When starting the install getting apache error

"The requested URL /install.php was not found on this server."

**Comment by samerton** [comment]
[This FAQ](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) will help you out.

**Comment by tricky538** [comment]
Thnx for the heads up the error now occurs on some debian installs and didnt install in an subdirectory

**Comment by samerton** [comment]
Enabling the use of Apache's mod_rewrite, along with .htaccess files as described in the FAQ should work.
If not, ensure there is a file named ".htaccess" included in your Nameless files containing [these rules](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess).

**Comment by samerton** [comment]
I'm going to mark this issue as closed as I believe it's a server configuration issue.
