### ISSUE TITLE
Topic placeholder does not work

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1858]
Using v2-pre7. Set topic placeholder on `website/panel/forums/?forum=id` but when I create a topic in this forum the text box is empty.

**Comment by Aberdeener** [comment]
Fixed a few commits ago. Missing variable in template file

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/commit/59f74278654494a502df9a8eb0f7428265cb1d5f
