### ISSUE TITLE
Global e-mails

### ISSUE THREAD

**Issue by Mubeen142** [NamelessMC/Nameless#1859]
**Please describe the feature in as much detail as possible**
Perhaps for the next update something like a global emailer would be cool.
What do I mean with global emailer? Well that all users get an email something like a discount code for the store or letting users know for upcoming server events.

The email layout could be uploaded in templates > defaultrevamp > emails folder and sent from the email tab in the staff panel

**Comment by Aberdeener** [comment]
Added this about 2 weeks ago! :)

**Comment by Derkades** [comment]
#949
