### ISSUE TITLE
Add reset profile picture button

### ISSUE THREAD

**Issue by StrikersGamingTV** [NamelessMC/Nameless#1863]
Add a reset profile button and possibly move both these settings so the reset profile banner and profile picture to the user section user management > users > click the person > punishment > add it there, and then add a custom message so like a warning that goes in there alerts

**Comment by Aberdeener** [comment]
Thanks, good idea.
Why would you like to see this in the punishments section? I think it would be better suited for the general User Management edit page, as well as the user's profile settings page.

**Comment by StrikersGamingTV** [comment]
I would like it there because that is where all the punishments are and you should be able to shoot them a little warning like "No innapropriate profile pictures or backgrounds, Thank you, 
Forum Moderation Team."
And if it's there it will be easy to find

**Comment by Derkades** [comment]
That's probably too specific for your use case. I think most people expect it next to the set profile picture button.

**Comment by StrikersGamingTV** [comment]
It's a permissions thing, meaning it's staff so how is it not a punishment?

**Comment by Derkades** [comment]
> It's a permissions thing, meaning it's staff so how is it not a punishment?

Permissions? Do you want a button to reset the profile picture or a permission to be able to set profile pictures?

**Comment by StrikersGamingTV** [comment]
Both, just like the profile banner thing, but it is a staff thing that is why I think they should be moved here: 
![image](https://user-images.githubusercontent.com/72888419/96948746-55bc3a80-14b4-11eb-9fa9-b82734986054.png)

**Comment by Aberdeener** [comment]
Added in c368afa, thanks for the idea!
