### ISSUE TITLE
make label types edittable

### ISSUE THREAD

**Issue by StrikersGamingTV** [NamelessMC/Nameless#1864]
in label types make it were you can add more, makes life a lot easier cause we can use the special badge code the < span 
class="badge" style="color: #fff; background-color: #FF004C;">Founder</span >

**Comment by Aberdeener** [comment]
You seem to be talking about different things in the title and text.
1. There is an edit button beside all labels, so what do you mean by your title?
2. I dont understand what you are talking about in the main text area. Group HTML?

**Comment by StrikersGamingTV** [comment]
No I am talking about label types, not labels

**Comment by samerton** [comment]
The label types available by default depend on your theme - templates using Semantic UI (eg Default Revamp) have [these colours](https://semantic-ui.com/elements/label.html#colored) available and templates using Bootstrap (eg Default) have [these colours](https://getbootstrap.com/docs/4.5/components/badge/#contextual-variations) available.

Any extra colours can be added by either using inline CSS as in your example, or by adding CSS to `custom/templates/_template_/css/custom.css` - there are no plans to add further colours available by default.

**Comment by StrikersGamingTV** [comment]
I am asking for you to make it possible to add a label type with code like this < span class="badge" style="color: #fff; background-color: #FF004C;">Head Of Server</span >

**Comment by samerton** [comment]
This is already possible:
![Screenshot 2020-10-16 at 13 45 51](https://user-images.githubusercontent.com/1812544/96259748-f347d380-0fb5-11eb-904f-42f727a45e65.png)

**Comment by StrikersGamingTV** [comment]
you cannot add new ones, you can edit old ones

**Comment by samerton** [comment]
There's a button to add a new label type at the top of the page:
![Screenshot 2020-10-16 at 16 52 57](https://user-images.githubusercontent.com/1812544/96280636-1a130380-0fd0-11eb-9f50-c3ec4ec8002c.png)

**Comment by StrikersGamingTV** [comment]
wtf
when did that get added

**Comment by StrikersGamingTV** [comment]
🤦 that wasn't there for me, thank you for telling me I just looked it's there. sorry for wasting y'alls time

**Comment by samerton** [comment]
No problem 👍
