### ISSUE TITLE
fix the chat color picker

### ISSUE THREAD

**Issue by StrikersGamingTV** [NamelessMC/Nameless#1866]
your color picker doesn't work when pasting stuff like #f3024b as a color, it goes grey

**Comment by samerton** [comment]
Could you please provide more info? This seems to work fine for me

**Comment by StrikersGamingTV** [comment]
https://gyazo.com/2e9a05d2d653a6e8f847d623ac33b60f

**Comment by Aberdeener** [comment]
I am guessing this is because of the `#` you pasted in. The colour picker is not made by us, so we cannot change too much. Can you confirm or deny that removing the `#` before pasting solves the issue?

**Comment by StrikersGamingTV** [comment]
The issue is that pasting the number won't work, I should be able to pick a number via hex code.

**Comment by Aberdeener** [comment]
Obviously I can see that, please answer the question in my previous comment

**Comment by StrikersGamingTV** [comment]
I don't understand your question, the issue is I cannot paste it, I want to use custom hex colors, it's not that it breaks normal colors cause I can pick normal colors, but hex codes it breaks.

**Comment by Aberdeener** [comment]
I mean, can you please try to paste it *without* the leading hashtag

**Comment by StrikersGamingTV** [comment]
Resolved thanks, I didn't know that's why.
