### ISSUE TITLE
sub forums lose organization

### ISSUE THREAD

**Issue by StrikersGamingTV** [NamelessMC/Nameless#1868]
so sub forums lose organization and it makes OCD go through the roof,

**Comment by Aberdeener** [comment]
Please provide more information.
Subforms would only lose order (assuming that is what you mean by "organization") if you manually drag them in StaffCP - Forum or edit their order in the database.
Can you please screenrecord when this issue happens so I can recreate it?

**Comment by StrikersGamingTV** [comment]
Yes, and sadly you are actually wrong, anytime I open my [Minecraft] Ban Appeals & Reports, the order is Denied > Member Reports > Accepted It should be Accepted > Denied > Member Reports 
![image](https://user-images.githubusercontent.com/72888419/96119563-29ecf380-0ebb-11eb-9eb1-3ed3bf2bf2a8.png)
![image](https://user-images.githubusercontent.com/72888419/96119581-31140180-0ebb-11eb-8de4-33c1b86a1289.png)
thats a random example here is an example of what I just said,

![image](https://user-images.githubusercontent.com/72888419/96119623-4426d180-0ebb-11eb-81e1-7077a869e874.png)
![image](https://user-images.githubusercontent.com/72888419/96119657-4f79fd00-0ebb-11eb-880b-696c3cb3109b.png)

**Comment by StrikersGamingTV** [comment]
Please fix this, it makes stuff look completely terrible.

**Comment by StrikersGamingTV** [comment]
I think the issue is that the subforums are made to place the organization to when you made them and which you made first, so moving them at all takes no effect and it is impossible.

**Comment by Aberdeener** [comment]
Fixed for next update, thank you Partydragen
