### ISSUE TITLE
Multiple DB types support

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1869]
Continuing from @Derkades and I conversation. 

Idea of how it might work:
```php
class MySQL implements DBConnector {
  public function listUsers(): array {
    return $query->prepareAndExecute("SELECT * FROM nl2_users");
  }
}
// lol mongo
class MongoDB implements DBConnector {
  public function listUsers(): array {
    return $query->execute("dont remember how mongo syntax works");
  }
}
```

and all nameless would do is
```php
class DB {
  public function listUsers(): array {
    return $_dbConnector->listUsers();
  }
}
```
This is a super long term idea, and may never be implemented.
We will support mysql out of the box, and maybe the community can add support for other databases

**Comment by Derkades** [comment]
Use an existing framework such as https://thecodingmachine.github.io/tdbm/

**Comment by Derkades** [comment]
There are some major differences between sqlite and mysql query syntax though
