### ISSUE TITLE
Remove character limits

### ISSUE THREAD

**Issue by StrikersGamingTV** [NamelessMC/Nameless#1870]
![image](https://user-images.githubusercontent.com/72888419/96131846-b4d3eb00-0ec7-11eb-860e-ee3827d35872.png)
I want to have a staff blacklist and I want to paste maybe 50 blank spaces, but I cannot because a Character limit, I suggest removing character limits for everything to a sizable reason obviously like if you think it will destroy the look of the website do not, but on posts I think remove it.

**Comment by Derkades** [comment]
I would say 50000 characters is pretty reasonable. The average English word length is 4.7 characters. An A4 page contains on average 500 words depending on font size and spacing. This means that 50000 characters will span over 20 A4 pages!
