### ISSUE TITLE
New Panel Template

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1874]
**Please describe the feature in as much detail as possible**

Hey, was wondering if the dev team would be interested in a new default panel template for pre-8? This would be made by me, using sb admin 2. I would keep it very similar to sb admin 2's design, only add a few small things such as maybe a dark/light switch.

[SB Admin 2 Link](https://startbootstrap.com/themes/sb-admin-2/)

Let me know what you guys think, so I can get started on development if it's wanted!

**Comment by Aberdeener** [comment]
Looks sleek and a little more modern. Sounds good to me, ultimately up to Sam though. Thanks!

**Comment by CqldFire** [comment]
Awesome!
I DMed him on discord about it yesterday but still no response, hopefully he sees this issue.

**Comment by Derkades** [comment]
I agree, the panel could use some design work. Many people will appreciate a light/dark theme switch.

> for pre-8

It will be for pr9 or later, pr8 is basically in feature freeze at this point.

**Comment by CqldFire** [comment]
Small preview!

Barely started working on the theme, but here is a preview of the home page! Let me know what you guys think!

![Screenshot (55)](https://user-images.githubusercontent.com/57230688/96639731-f228e600-12d6-11eb-9bea-681478f17bd4.png)

**Comment by Derkades** [comment]
To keep issues manageable I'll close this issue. Feel free to open a draft pull request even if it isn't finished yet, pull requests are better suited for progress reports and discussions since developers can look at and review the code
