### ISSUE TITLE
API method for getting user language

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1876]

**Comment by samerton** [comment]
Could this be added to the userInfo endpoint?
Also worth noting languages aren't stored in any standard formats, just the name of the folder, and users could have custom languages.

**Comment by Derkades** [comment]
`GET`
`getLang`
Optional parameter `user_id`
```
if user_id and user has specified language:
  return user lang
else:
  return site lang
```

**Comment by Derkades** [comment]
> languages aren't stored in any standard formats, just the name of the folder

Maybe it's a good idea to switch to a standard format for langauges? https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes . I don't specifically need it in my case but it's always a good idea to stick to standards.

**Comment by samerton** [comment]
I'd rather the language was returned from the existing user info, seems excessive to have an endpoint just returning someone's language?

The problem with using ISO for example is that it'll prevent custom user languages, they might modify the English translation for example specifically for their site.

**Comment by Derkades** [comment]
> The problem with using ISO for example is that it'll prevent custom user languages, they might modify the English translation for example specifically for their site.

Good point

> I'd rather the language was returned from the existing user info, seems excessive to have an endpoint just returning someone's language?

This is a difficult decision. In cases where the client only needs a single value, having separate endpoints is faster. The userInfo api method returns quite a lot of information, I imagine it takes a non-trivial amount of time for php get values from the database and produce the json. On the other hand, if the client needs multiple values, doing multiple HTTP requests will have a huge overhead.

I'd say your right, putting it in the userInfo api method is a better idea. Something like this?

```json
"language": {
  "set": false,
  "value": "EnglishUK"
}
```
```
if  user has specified language:
  set = true
  value = user lang
else:
  set = false
  value = site lang (default lang)
```

**Comment by Aberdeener** [comment]
Added in bfff00b.
"set" is not possible, since `nl2_users.language_id` is never null - it will be automatically the site default.

**Comment by Derkades** [comment]
Added in java API https://github.com/NamelessMC/Nameless-Java-API/commit/965f2857f807aec334692f3482e7675d778393b5

**Comment by Derkades** [comment]
I still need a method for getting the site language, since in case of Nameless Link users are more often not registered or known (messages before the user is linked). In these cases I want to use the site default language.

**Comment by samerton** [comment]
@Derkades 
`/info` endpoint now returns `language`
5206a8468d1fbb68d646702aef27a74775938dad
