### ISSUE TITLE
New installer does not work with nginx

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1877]
To reproduce:
1. Clone `v2` branch
2. `export UID=$UID; export GID=$GID; docker-compose up`
3. Go to `http://localhost` and install
4. Observe that after database initialization the user is directed to `undefined`

Redirect happens here: https://github.com/NamelessMC/Nameless/blob/v2/core/installation/views/steps/database_initialization.php#L72

```js
$.post(window.location.href, {perform: 'true'}, function(response) {
	if (!response.message) {
		window.location.replace(response.redirect_url);
```

When I echoed `response` to the console it contained a bunch of HTML (installation header) with the expected json at the end. Presumably this HTML causes javascript to not be able to parse `response` as json and returns undefined for `response.redirect_url`

What could cause this HTML to appear? My first thought was an htaccess rewrite rule that would not be present on nginx but I did not find any.

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/54f71887fbe160da92224c631e57415b3eb57881

**Comment by Derkades** [comment]
turned out to likely be an issue with php_fpm, not nginx specifically
