### ISSUE TITLE
Change Module Order

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1878]
**Please describe the feature in as much detail as possible**

We all know that the module order value controls where the module links are on the sidebar in staffcp, and if two modules have the same module order value, the links get all messed up.

I propose that module order becomes no longer built into each module as a value in module.php, but is instead the module's id in nl2_modules. This would completely eliminate the module order issue, as two MySQL rows cannot have the same id.

**Comment by Aberdeener** [comment]
Yeah I agree with this. Especially since module orders are configurable by the user I don't see the point in using them. @samerton ?

**Comment by samerton** [comment]
The links in the StaffCP sidebar are unrelated to module order - there will soon be a configuration page to modify the StaffCP navigation, the same as the StaffCP -> Configuration -> Navigation tab but for the StaffCP instead.
