### ISSUE TITLE
Theme Question

### ISSUE THREAD

**Issue by FunkiestPeak** [NamelessMC/Nameless#188]
Is there anyway that I can take the style of this static html site and make it a theme for this software?
[landed.zip](https://github.com/NamelessMC/Nameless/files/262368/landed.zip)

**Comment by samerton** [comment]
Only Bootstrap based themes/templates can be used (unless heavily modified to include core Bootstrap functionality). The template you've linked seems to be non-Bootstrap based, as a result unfortunately it can't be used.

**Comment by MuhsinunCool** [comment]
@samerton I was planning on making a custom template to use Materialize-CSS and then also a theme with Materialize-CSS's CSS files. Wud that not be possible?

**Comment by samerton** [comment]
@MuhsinunCool it's possible in version 2, however version 1 must have a Bootstrap based CSS framework.

**Comment by MuhsinunCool** [comment]
If I were to make my template using the given default template in NMC 1.0.15's templates directory, wud that work on NMC 2.0? Or is NMC 2.0's default template completely different?

**Comment by samerton** [comment]
@MuhsinunCool v2 templates are totally different, if you'd like to you can start developing a template using the first [v2 pre-release](https://github.com/NamelessMC/Nameless/tree/v2) (not recommended for use on a public site due to potential bugs and missing features)

**Comment by MuhsinunCool** [comment]
Ummm... ty, but where exactly r the custom templates stored... Probably a dumb question... Can't seem to find it in NMC 2.0...

**Comment by samerton** [comment]
@MuhsinunCool you can find templates in the **custom/templates** directory

**Comment by MuhsinunCool** [comment]
Yep ty literally JUST found that haha!

**Comment by Fellings1** [comment]
Im guessing this was solved.
