### ISSUE TITLE
PHP Mailer  error

### ISSUE THREAD

**Issue by MViper** [NamelessMC/Nameless#1880]
Hello,

I can't send emails, I always get an error

![Unbenannt](https://user-images.githubusercontent.com/70104096/96726245-0ee61c00-13b2-11eb-8866-e35a32d67c45.PNG)

How can I fix the error?

**Comment by samerton** [comment]
I don't think I've ever seen this before, and it would suggest you have a customisation, a module or a template interfering.

Have you made any customisations to the PHP files?

If not, can you disable all modules and try again.

**Comment by MViper** [comment]
I tried it Breits without modules and there comes the same error The php file was not changed

**Comment by samerton** [comment]
Is PHPMailer enabled or disabled?

**Comment by Aberdeener** [comment]
Closing this now as we haven't heard from you in a while. Hopefully that means the problem is solved. Take care!
