### ISSUE TITLE
PhPMailer Error

### ISSUE THREAD

**Issue by Hckekick** [NamelessMC/Nameless#1881]
Hello, I've been trying this for days with the email at Namelessmc. I try to send a test email all the time. and it comes this message here:                   
 The following From address failed: totiacraft@outlook.com : MAIL FROM command failed,5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR04CA0003.eurprd04.prod.outlook.com] ,530,SMTP server error: MAIL FROM command failed Detail: 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR04CA0003.eurprd04.prod.outlook.com] SMTP code: 530

**Comment by Derkades** [comment]
Did you enter a username?

**Comment by Hckekick** [comment]
@Derkades  

I put my normal e-mail address in there. I don't know that. I apologize for my poor English.

**Comment by samerton** [comment]
Could you edit the file core/classes/Email.php in a text editor, delete all code inside then replace with [this new code](https://gist.githubusercontent.com/samerton/a26df55561f9735eb2f69af6868f57fb/raw/5f5581c6faa44c596eebccaa32d6c0efa8f79a81/Email.php)

Then try sending another test email and you should get further debug info on screen

**Comment by Hckekick** [comment]
I did it. This one was shown to me

@samerton 







outlook.com:587, timeout=300, options=array ()
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 AM0PR01CA0097.outlook.office365.com Microsoft ESMTP MAIL Service ready at Wed, 21 Oct 2020 16:38:12 +0000"
SERVER -> CLIENT: 220 AM0PR01CA0097.outlook.office365.com Microsoft ESMTP MAIL Service ready at Wed, 21 Oct 2020 16:38:12 +0000
CLIENT -> SERVER: EHLO totiacraft.ga
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]"
SMTP -> get_lines(): $str is "250-SIZE 157286400"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING"
SMTP -> get_lines(): $str is "250-DSN"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME"
SMTP -> get_lines(): $str is "250-BINARYMIME"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME"
SMTP -> get_lines(): $str is "250-CHUNKING"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME250-CHUNKING"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 2.0.0 SMTP server ready"
SERVER -> CLIENT: 220 2.0.0 SMTP server ready
CLIENT -> SERVER: EHLO totiacraft.ga
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]"
SMTP -> get_lines(): $str is "250-SIZE 157286400"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING"
SMTP -> get_lines(): $str is "250-DSN"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-AUTH LOGIN XOAUTH2"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-AUTH LOGIN XOAUTH2"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-AUTH LOGIN XOAUTH2250-8BITMIME"
SMTP -> get_lines(): $str is "250-BINARYMIME"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-AUTH LOGIN XOAUTH2250-8BITMIME250-BINARYMIME"
SMTP -> get_lines(): $str is "250-CHUNKING"
SMTP -> get_lines(): $data is "250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-AUTH LOGIN XOAUTH2250-8BITMIME250-BINARYMIME250-CHUNKING"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-AM0PR01CA0097.outlook.office365.com Hello [2a00:ccc1:4::46]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-AUTH LOGIN XOAUTH2250-8BITMIME250-BINARYMIME250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: MAIL FROM:<totiacraft@outlook.com>
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR01CA0097.eurprd01.prod.exchangelabs.com]"
SERVER -> CLIENT: 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR01CA0097.eurprd01.prod.exchangelabs.com]
SMTP ERROR: MAIL FROM command failed: 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR01CA0097.eurprd01.prod.exchangelabs.com]
The following From address failed: totiacraft@outlook.com : MAIL FROM command failed,5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR01CA0097.eurprd01.prod.exchangelabs.com],530,SMTP server error: MAIL FROM command failed Detail: 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR01CA0097.eurprd01.prod.exchangelabs.com] SMTP code: 530
CLIENT -> SERVER: QUIT

**Comment by MViper** [comment]
What you have there is a clear SMTP error .. Try a different port (25/465/587)

The 587 & 465 are SSL ports

**Comment by Hckekick** [comment]
@MViper 
I still get the same bug

**Comment by MViper** [comment]
you can send us a screenshot of what you entered there

**Comment by MViper** [comment]
Is access to Outlook even active? The default is deactivated

IMAP-Servername Outlook.office365.com

IMAP-Port 993

IMAP-VerschlüsselungsmethodeTLS

Pop-Servername Outlook.office365.com

POP-Port 995

POP-Verschlüsselungsmethode TLS

SMTP-Servername SMTP.office365.com

SMTP-Port 587

SMTP-Verschlüsselungsmethode STARTTLS


https://support.microsoft.com/de-de/office/pop-imap-und-smtp-einstellungen-f%C3%BCr-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040#bkmk_enablepop_beta

**Comment by Hckekick** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/73239996/96755212-b6734680-13d2-11eb-9a6a-adbe22dd2a57.png)

Here's a screenshot.

**Comment by MViper** [comment]
Port 25 is wrong
Please 465 or 587

**Comment by Hckekick** [comment]
Now the forum is no longer responding. so it loads.. I have taken the port 465

**Comment by Hckekick** [comment]
As soon as I click Send it loads continuously .. have already tried another browser. exactly the same

**Comment by Hckekick** [comment]
It has loaded. But I still get the same mistake. I'm slowly baffled.

@MViper

**Comment by MViper** [comment]
Have you released the ports in the firewall?

**Comment by Hckekick** [comment]
What do I do?

**Comment by samerton** [comment]
Can you try reading the answer to this issue? https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_winother-mso_o365b/client-was-not-authenticated-to-send-anonymous/d405bcb0-f40c-42fa-b1b2-477597100123

**Comment by Aberdeener** [comment]
Closing this now as it is not necessarily NamelessMC related, and we haven't heard from you in a while. Hopefully that means the problem is solved. Take care!
