### ISSUE TITLE
Include php version in metrics

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1882]

**Comment by Aberdeener** [comment]
Unless i'm being stupid, I think the only place "metrics" are sent is [here](https://github.com/NamelessMC/Nameless/blob/c5552642502c7649d18fb6a809946085f6d74885/modules/Core/pages/panel/update.php#L88).
What do you think @samerton ?

**Comment by samerton** [comment]
[Here](https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Util.php#L499) too, should be an easy thing to add the PHP version

**Comment by Aberdeener** [comment]
Added in 1111f03
