### ISSUE TITLE
Announcement Edit Issue

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1883]
**Describe the issue**
When you go to the announcements page and click edit on the announcement, then it takes you to the edit page, the back button has the wrong link.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the announcements page
2. Create an announcement
3. Click edit

**Expected behaviour**
I was expecting the link to lead back to the announcements page, but instead it just reloads the page (if you use inspect you can see that there is a href attribute but no link).

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC v2 pre-7 latest dev code.

**Comment by Aberdeener** [comment]
Fixed in 5236772, thank you for testing the dev code!
