### ISSUE TITLE
Get stale bot for [question] and [bug] issues?

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1884]
It will encourage replies and further feedback (e.g. answer questions or reproduce bug on a newer version). Issues where the author has disappeared will be closed automatically.

Not for feature requests for obvious reasons, only for bug and question issues since they are intended to be solved in a short time frame.

**Comment by samerton** [comment]
I think the issue tracker here is too quiet for this to reach its full potential. I also like having control on closing issues just in case it's a bug which may be a low priority so gets put into the backlog, but still needs fixing.
