### ISSUE TITLE
Update phpmailer to 6.x series

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1885]
Fixes #2101

**Comment by Derkades** [comment]
In php 8:
```
Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /data/core/includes/phpmailer/PHPMailerAutoload.php on line 45
```

**Comment by samerton** [comment]
Pushing back to 2.1.0 to maintain 5.4 support in 2.0.0

**Comment by Derkades** [comment]
You'd rather have php 5.4 support than php 8 support?

**Comment by samerton** [comment]
Is 5.x not PHP 8 compatible at all?

**Comment by Derkades** [comment]
It's a fatal error, emails are broken in PHP 8 (at least as reported by someone in #support).

**Comment by samerton** [comment]
Ah ok, will do some testing - if it's just the autoload file it's easy enough to change. If there's more then we'll have to drop 5.4.

The problem is, we need a code change to the StaffCP updater to prevent upgrades from 5.4 - how do we get this out without an update beforehand?

**Comment by Derkades** [comment]
I don't think it's an issue since according to statistics no one uses php 5.4 anymore. You could mention it in the release notes, but not everyone reads those

**Comment by partydragen** [comment]
Temp fix for php 8, https://github.com/NamelessMC/Nameless/commit/6e965650bca7eaeaf86645b14d07e0fbe178f948

**Comment by Aberdeener** [comment]
Updated + tested with composer
