### ISSUE TITLE
Announcements Error Alert Bug

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1888]
When you edit an announcement and cause an error (like having no title), the error alert pops up when you press submit, but the title doesn't display.

Steps to produce:
1. Go to announcements page in staffcp
2. Create an alert
3. Leave the title blank
4. Press submit
5. See error

NamelessMC Version: v2 pre-7 latest dev code

**Comment by Derkades** [comment]
> i fixed it and forgot that i fixed it

\- @Aberdeener
