### ISSUE TITLE
Supporting avatars from nicknames, not only UUIDs

### ISSUE THREAD

**Issue by dexasz** [NamelessMC/Nameless#1889]
Hello, would be pretty cool if you could get skins from their nicknames, as minotar.net supports avatars from nicknames

Example: https://minotar.net/avatar/dexasz / https://cravatar.eu/avatar/dexasz

**Comment by Aberdeener** [comment]
Where would this be used?
By nickname do you mean Minecraft username?

**Comment by dexasz** [comment]
> Where would this be used?
> By nickname do you mean Minecraft username?

Yep, Minecraft username, basically I have more of a shared type of a server between premium and cracked, meaning that premium players can disable their premium status and let cracked players join the server using their name. As a result of this, I have to use offline uuids, which means that skins aren't showing up properly, I myself own a legitimate minecraft account, but my players want to see their own skins on voting and infraction tabs, so it would help me out a lot :)

**Comment by Derkades** [comment]
This would also be a nice half-solution for #1678

**Comment by Aberdeener** [comment]
The issue with this is that *eventually*, due to Mojang API changes, most skin services will not allow/support usernames and force using UUIDs. Might be a waste of our time to add this only for it to be removed later

**Comment by Derkades** [comment]
there are modules that allow this, look for "warez" on namelessmc.com/resources
