### ISSUE TITLE
Cookies / Sessions expire too fast!

### ISSUE THREAD

**Issue by xBreaksx** [NamelessMC/Nameless#189]
I love to create big threads for people to view to get the best information out of what I'm saying, but I always have to back it up into a "quick reply" text area to grab it before the next session expires.

Please fix this!

**Comment by samerton** [comment]
The problem with form tokens isn't time related at the moment, but occurs if you open a new tab and browse the site in a different tab. I'll fix this in the future (it's do to with the token names being the same), but for now as long as you don't browse the site in any other tabs at the same time you'll be able to get around this.

**Comment by samerton** [comment]
Fixed in 82f52858956f8ec9837189eb843046e71e55b64d (although sessions will still expire after 24 minutes)
