### ISSUE TITLE
Sync one in-game group to multiple NamelessMC groups

### ISSUE THREAD

**Issue by Noxillio** [NamelessMC/Nameless#1894]
As it says in the title since by default you can only map 1 to 1

**Comment by Aberdeener** [comment]
Eh dont think this would be a hard addition. Too tired tonight to add this, but possibly tomorrow. Thanks for the idea

**Comment by partydragen** [comment]
Added in https://github.com/NamelessMC/Nameless/commit/5b69ef5a29f69175d3d236432bf0294d11770b1d
