### ISSUE TITLE
Use poedit for translations

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1901]
https://poedit.net/

Works with PHP, used by many open source projects such as https://joplinapp.org/. It has built-in support for language-specific details like plurals. Like Transifex but without needing an account on some website. The workflow remains the same (fork repository, edit file (now with poedit program), submit PR).

Advantages for translators:
 - Translators can mark translation phrases as 'needs work' if they feel like their translation could be better.
 - New and updated translations are automatically highlighted
 - No potential of making PHP syntax errors

Advantages for developers:
 - No need to edit 20 files when adding a simple feature
 - did I mention not needing to edit 20 files every time

Proudly supported by:
- Xemah
- Partydragen
- Aberdeener

**Comment by Aberdeener** [comment]
So all translators need to have this software installed?

**Comment by Derkades** [comment]
There are alternatives like editing the file directly or using an onlin .po editor. The format is standardised, people can use any editor. Poedit is the most popular open source editor and is available for many platforms, even included in most linux package repositories

**Comment by Derkades** [comment]
#1968
