### ISSUE TITLE
[Suggestion] Change the text editor

### ISSUE THREAD

**Issue by Marckos200** [NamelessMC/Nameless#1902]
From my point of view the text editor that Nameless has is quite simple, it has few options, sometimes when making too long posts they lose their aesthetic and look bad, etc. But the feature that I miss the most is the spell checker, and that is that, when you even want to underline in red, users get to write really badly, and even when you activate the red underline, the suggestions still do not appear when you right click, something that facilitates a readable writing. Would it be possible to put a better text editor?

**Comment by Derkades** [comment]
I've created a new discussion issue here: #1904
