### ISSUE TITLE
Nameless's Discord embed transforms "Š" symbol into "&scaron;"

### ISSUE THREAD

**Issue by dexasz** [NamelessMC/Nameless#1906]
![embed](https://user-images.githubusercontent.com/37642364/98431591-7d6bef00-20bf-11eb-9a8d-9fb01a0ae6db.png)

**Comment by Derkades** [comment]
Possibly duplicate of #1628

**Comment by Aberdeener** [comment]
Closing this issue as it has been fixed in the commit Derkades linked. Feel free to reopen if your issue is not resolved still.
