### ISSUE TITLE
Remove translation support for API error messages

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1907]

**Comment by samerton** [comment]
Just wondering why this is necessary? The error codes are intended to be read by clients, the message shouldn't matter.

**Comment by Derkades** [comment]
Not necessary but following a recent conversation in discord, it in my opinion adds unnecessary work for translators and developers. I'll add a discussion label and wait for others to weigh in

**Comment by Aberdeener** [comment]
Yeah I dont really mind translating these
