### ISSUE TITLE
Terms and conditions checkbox text not correct

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1909]
Either remove the checkbox or remove "by clicking Register"

![image](https://user-images.githubusercontent.com/15892014/98441648-fd19ae00-20ff-11eb-92be-679e1287c7cd.png)

Which one should I do?

Removing the checkbox is better UX but might not be legal

**Comment by samerton** [comment]
Not much wrong with this to be honest, you're confirming that by registering you agree the terms. It _could_ be changed to just "I agree with the terms & conditions" but shouldn't be necessary.

**Comment by Derkades** [comment]
Normally you'd see either
a) by performing this action you automatically agree to the terms of service
b) I agree

It seemed confusing but that might just be me

**Comment by Marckos200** [comment]
There are usually 2 ways to do that.

1. Only warning that in case of proceeding everything is accepted automatically.
Examples: 
- "Choosing Register means that you agree to our Terms and Conditions and privacy and cookies statement."

- "By creating an account, you agree to the Terms of Service/Conditions. For more information about our privacy practices, see the Privacy Statement."

2. Placing a checkbox and warning that in case of clicking it is understood that they have read and accepted all.
Examples: 
- "(checkbox) I agree with the Terms and Privacy policy"

- "(checkbox) I have read and accept/agree the Terms and Privacy policy" 

Both are legal, at least in Europe. **(The privacy policy should also be added to be accepted in the sign up).**
