### ISSUE TITLE
Issue with PHPMailer.

### ISSUE THREAD

**Issue by ThePlay3r** [NamelessMC/Nameless#1913]
Hello,

so I'm trying to enable PHPMailer on my NamelessMC website, so this is what I did and what happened:
- Filled the details in the E-Mail section in AdminPanel.
- Tried to send test email; an error showed up.
- I went to look at the wiki and according to it, configured `core/email.php`
- Only thing I changed was the secure, from tls to ssl, like this: `'secure' => 'ssl',`.
- Tried to send the test email again; page with a bunch of random nonsense showed up, I ignored it as I got the E-Mail and thought everything is working right.
- Tried to create a new test user, the same page showed up again and I have no idea what is causing it.
[Here](https://ctrlv.cz/ZTic) is the page I see after hiting register.

After setting the `$mail->Debugoutput` to `error_log` in `core/classes/Email.php`, the message is gone, but the user is still not redirected.
However, he receives the E-Mail and is able to confirm his account without any problem.

I believe this is not intedned and would like to resolve this issue as fast as possible.
I'm sorry if anything sounds confusing, if needed, I can provide any details necessary.

**Comment by samerton** [comment]
Hi,

It looks like you have the debug script for your core/classes/Email.php file.

If you revert the contents of this file back to its original code (https://raw.githubusercontent.com/NamelessMC/Nameless/c53fdaa8d4dcc2e0229456330863eaa9ec16a336/core/classes/Email.php) the problem should be resolved.

**Comment by ThePlay3r** [comment]
That resolved the issue, thanks.
