### ISSUE TITLE
 Many errors

### ISSUE THREAD

**Issue by ichbinkevin1** [NamelessMC/Nameless#1919]
1. Error: I get the error: "Unable to enable incompatible module." when I want to activate the Chatbox module. Why?
The problem I don't understand is that the chatbox module is still activated although it should be deactivated 
and when I deactivate it it is still displayed
2. Error: [2020-11-20, 21:08:04] /var/www/html/core/init.php(85) 8: Undefined index: HTTPS
[2020-11-20, 21:08:04] /var/www/html/core/classes/ErrorHandler.php(43) 8: Attempt to access the array offset for the value of type zero
3. Error: I also noticed that some functions no longer work, for example I can no longer change the page type to Portal
Or I can no longer put the forum in maintenance mode. The setting is then reset when you save.

I use the V2 pre7 version

Please help me :(

**Comment by samerton** [comment]
Have you recently switched web hosts?

Can you ensure the `cache` folder and all files inside are writable

**Comment by ichbinkevin1** [comment]
Yes, I recently changed the web host and I made the cache folder writable.

**Comment by samerton** [comment]
Did you apply the permission change recursively? So all files inside are writable too? That will resolve the 3rd issue at least.

**Comment by ichbinkevin1** [comment]
Unfortunately I do not know it. Do you have a list of which files have to be made writable?

**Comment by samerton** [comment]
How are you managing the permissions? Are you using an FTP client, or the command line?

**Comment by ichbinkevin1** [comment]
I am using an FTP client

**Comment by samerton** [comment]
Using Filezilla you be able to right click the "cache" folder -> File Permissions, tick all the boxes and then select these options at the bottom:

<img width="262" alt="Screenshot 2020-11-24 at 17 11 22" src="https://user-images.githubusercontent.com/1812544/100128373-1b113d80-2e78-11eb-8302-372ef5388080.png">

**Comment by ichbinkevin1** [comment]
I am using the WinSCP program

**Comment by ichbinkevin1** [comment]
> Using Filezilla you be able to right click the "cache" folder -> File Permissions, tick all the boxes and then select these options at the bottom:
> 
> <img alt="Screenshot 2020-11-24 at 17 11 22" width="262" src="https://user-images.githubusercontent.com/1812544/100128373-1b113d80-2e78-11eb-8302-372ef5388080.png">

I've done this now

**Comment by samerton** [comment]
Your settings in the StaffCP should now save correctly - can you try them?

**Comment by ichbinkevin1** [comment]
Yes it works now. Errors 1 and 3 have thus been eliminated, but not yet 2

**Comment by ichbinkevin1** [comment]
Now the errors still occur: https://hastebin.com/serotocuta.yaml

**Comment by samerton** [comment]
Those messages are Staff module related - can you please contact the module author

**Comment by ichbinkevin1** [comment]
Yes i can do it. Can you still help me with the 2 mistake?

**Comment by samerton** [comment]
The second point is nothing to worry about and will be hidden if you disable debugging (StaffCP -> Configuration -> Maintenance)

**Comment by ichbinkevin1** [comment]
Ok. Then I thank you for your help
