### ISSUE TITLE
Problem with Litebans

### ISSUE THREAD

**Issue by dgateles** [NamelessMC/Nameless#192]
My litebans have a prefix on tables and because this the page does not work. How to fix this?

**Comment by samerton** [comment]
Unfortunately there's no way to set the prefix yet from within Nameless, for the time being the table names within **addons/Infractions/Infractions.php** would need modifying. Simply running a search within that file for "litebans_" will display all possible results, they're on line 450 onwards.

**Comment by dgateles** [comment]
Ok, working but with some erros: [http://craftalizar.com/infractions](http://craftalizar.com/infractions)
On line 576 i have 
`$username = $username[0]->name;`
On line 610 i have
`$username = $username[0]->name;`

**Comment by samerton** [comment]
Interesting, this should be fixed in 59eeb4433af9fdb2d453bbf9bed82cc950fa0a9d

**Comment by dgateles** [comment]
Fixed! Thanks man!
Error reporting disabled.
But pagination still broken.

**Comment by samerton** [comment]
Pagination should have been fixed in a previous commit which will be included in 1.0.9.
