### ISSUE TITLE
Add the ability to set default labels on forums

### ISSUE THREAD

**Issue by DrakePork** [NamelessMC/Nameless#1923]
As the title says, add the ability to set so anytime someone posts a topic on a specific forum that topic automatically has a specified label on it regardless of if the person has the ability to add that label or not.

**Comment by Aberdeener** [comment]
why not!

**Comment by kacperleague9** [comment]
TRUE

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/0749a00ec509fb16f6cb1ed9abde6425e20c20de
