### ISSUE TITLE
SMTP connect() failed.

### ISSUE THREAD

**Issue by Bubzhome** [NamelessMC/Nameless#1928]
Describe the issue
I am having issues with PHPMailer, I have filled in all fields with correct information for smtp.gmail.com however everytime I attempt to use it with PHPMailer it returns SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, I have had a look at the page it asks for but no luck.

To Reproduce
Steps to reproduce the behaviour:
Open StaffCP
Go to Email
Turn on PHPMailer
Fill in information for smtp.gmail.com
Click Submit
Send test email

Expected behaviour
The email to send and appear on my mail account

Screenshots
Not needed as it's just the regular Error screen for the Send Test Email page.

NamelessMC version (from AdminCP -> Overview)
NamelessMC 2.0.0-pr6

Additional information
I have had a look at this issue and added this code to the core/classes/Email.php file and the error output is as follows:

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Network is unreachable)
SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by samerton** [comment]
Hi,

It sounds like your web host is blocking the outgoing traffic to smtp.gmail.com (hence the `Network is unreachable (101)` error)

I'd open a ticket with them to see if they know what's going on.

**Comment by Aberdeener** [comment]
Havent heard anything on this - hope this means it has been resolved! Feel free to reopen this if the issue continues.
