### ISSUE TITLE
Feature to transfer topic ownership

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1929]
![image](https://user-images.githubusercontent.com/15892014/101053211-cb252b80-3587-11eb-9864-070970a86c65.png)

**Comment by Aberdeener** [comment]
Yeah, not sure how it'll work tho. I suppose just a button on the root post around the moderation section...

**Comment by Derkades** [comment]
I'm not sure if this should even be implemented, generally software does not allow writing text as other users (transferring messages, editing messages, etc)

**Comment by Aberdeener** [comment]
On second thought of this, it seems like a very niche case. Going to close unless we think of:
1. A good reason to add this
2. A good way to implement it w/ Logging

**Comment by partydragen** [comment]
i still mean about adding a root colum in users table like i did on namelesshosting then everything to depend on that

Also hasPermission will check if user is root then always return true then we can also remove the admin id 2 restrictions and limits those limits are pointless like pointless that root user is forced into a root if it may want to be hidden example

@samerton ?

**Comment by samerton** [comment]
@partydragen what's the advantage of a root column against a user, versus just using the user with ID 1?
