### ISSUE TITLE
"Index of /forum"

### ISSUE THREAD

**Issue by Liphius** [NamelessMC/Nameless#193]
Hi,

I'm having an issue where I cannot access the forum's main page. I tried switching the layouts which did not work. I thought that the pages > forum was missing a few files, which it wasn't. It was working fine yesterday and there were no changes to the FTP directory for a while. Anyway, here's the link;

http://oxencraft.co.uk/forum/

**Comment by samerton** [comment]
Do you have a folder on your web server named "forum" (even if it's empty)?

**Comment by Liphius** [comment]
Ah, sorry for the dumb question then. I deleted it and it worked fine.

**Comment by samerton** [comment]
Glad it's working, don't worry, it's not a dumb question at all.
