### ISSUE TITLE
Remove discord id requirement from discord link procedure

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1932]
![image](https://user-images.githubusercontent.com/15892014/101258160-e4151480-3720-11eb-93ee-0ceb1ceaace6.png)
Remove "discord id" field and rename "submit" to "link" or "connect"

**Comment by Aberdeener** [comment]
If we remove the field what's the point of having a button at all?

**Comment by Derkades** [comment]
I'm not familiar with the workflow, but don't users need to click a button to generate a discord verification code?

**Comment by Aberdeener** [comment]
Right good point haha.
If they're not linked, the button will display "Link", and if they are linked the button will display "Unlink".
When they click to unlink it, a confirmation modal will appear.
