### ISSUE TITLE
API error 16 when calling VERIFY_DISCORD endpoint

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1933]
Website said `Please send this message: "!verify 776921071953772615:5fcbbb9a4ef3f6.20034006"`
the bot sent verify token `5fcbbb9a4ef3f6.20034006`
website replied with error code 16 (can't find user)

**Comment by Aberdeener** [comment]
Please pull this change 8923008 and tell me which error it produces now. Previously there were 3 breakpoints where error 16 could have been thrown, now they're all unique

**Comment by Derkades** [comment]
fixed after short debugging session in discord
