### ISSUE TITLE
Show discord username in user info

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1934]
Here
![image](https://user-images.githubusercontent.com/15892014/101296404-9fbe6d00-3823-11eb-9760-f081e0c94677.png)
maybe here
![image](https://user-images.githubusercontent.com/15892014/101296410-ad73f280-3823-11eb-8857-446554c9a768.png)

**Comment by Aberdeener** [comment]
added in 6dd52ef
