### ISSUE TITLE
Don't display API key when API is disabled

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1936]
![image](https://user-images.githubusercontent.com/15892014/101544592-3c107d00-39a6-11eb-8e9b-0a649bd103e6.png)

Instead, gray out API URL and API key and put placeholder text "API is disabled" in the fields.

It is a common mistake that people forget to enable the API. This way they'll know to enable it before copying the URL.

**Comment by Aberdeener** [comment]
🟠 `Development started. Please wait...`

**Comment by Derkades** [comment]
It hides the API URL but still shows the API key, was this intentional?

**Comment by Aberdeener** [comment]
Thank you for clarifying. done.
