### ISSUE TITLE
Store discord bot username so language phrases arent hard coded

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1937]

**Comment by Derkades** [comment]
Add `bot_username` to `updateDiscordBotSettings` endpoint

**Comment by Derkades** [comment]
:heavy_check_mark: Added to Java API https://github.com/NamelessMC/Nameless-Java-API/commit/22cd17d60795280df84840b55dada3fc988e2680

**Comment by Derkades** [comment]
@Aberdeener Can this be closed?
