### ISSUE TITLE
Discord role dropdown

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1939]
Similar to dropdown for in-game ranks.

Proposing new API method:

### `POST` `submitDiscordRoleList`
post body:
* `roles`
    * `id` Role id
    * `name` Role display name

**Comment by Derkades** [comment]
:heavy_check_mark: Added in Java API https://github.com/NamelessMC/Nameless-Java-API/commit/00b73b463bfc4014c47d3ea369222bb6f7bc9b39

**Comment by Aberdeener** [comment]
Okay, complete - along with redo of group sync page.
Expected API Endpoint request:
```json
{
    "roles": [
        {
            "name": "Admin",
            "id": 737292579380396104
        },
        {
            "name": "Moderator",
            "id": 691533703045709894
        }
    ]
}
```
![img](https://i.imgur.com/SmpoS8i.png)

**Comment by Aberdeener** [comment]
Added in f2d7bb0
Let me know if you find any issues I may have not noticed
