### ISSUE TITLE
[Sugestion] Addons

### ISSUE THREAD

**Issue by dgateles** [NamelessMC/Nameless#194]
Hello!
I have some suggestions to add addons:
-Complete statistics; (like blue stats)
-MCMMO statistics;
-Realtime map;
-Advanced Login; (integration with this plugin if possible) [link to plugin](https://www.spigotmc.org/resources/advancedlogin.10510/)

Thanks :+1:

**Comment by samerton** [comment]
Hi,

Thanks for the suggestions.

- Complete statistics: these are currently being worked on, to begin with only one plugin will be supported [link]() but more will be added afterwards.
- McMMO statistics: sure, these can come with the additional statistics
- Realtime map: You can currently embed Dynmap/any other realtime map using the custom pages system
- Advanced login: It's a possibility for the future, but as it's premium I'd probably stick with something like AuthMe which could be modified in the future for other plugins.

**Comment by Derkades** [comment]
Statistics will be in a new module: https://github.com/NamelessMC/Nameless/issues/738
