### ISSUE TITLE
Please read before creating an issue

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1940]
* For questions and support, use the discord server or [Discussions Q&A](https://github.com/NamelessMC/Nameless/discussions?discussions_q=category%3AQ%26A)
* If you have found a bug, file a [bug report issue](https://github.com/NamelessMC/Nameless/issues/new?template=bug-report.md)
* For ideas and feature requests that need further discussion, use [Discussions Ideas](https://github.com/NamelessMC/Nameless/discussions?discussions_q=category%3AIdeas) 
* For small enhancement that you are sure many people would want, create a [feature request issue](https://github.com/NamelessMC/Nameless/issues/new?template=feature-request.md)
* For module requests use [Nameless module requests](https://github.com/NamelessMC/Nameless-Modules)
* For showcases use [Discussions Show and tell](https://github.com/NamelessMC/Nameless/discussions?discussions_q=category%3A%22Show+and+tell%22)
* Other general discussion can go in the discord server or [Discussions general](https://github.com/NamelessMC/Nameless/discussions?discussions_q=category%3AGeneral)

Pleade add :+1: reactions to vote on issues (avoid commenting if you don't have anything useful to add)

**Comment by PadowYT2** [comment]
why not close it & keep it pinned?
