### ISSUE TITLE
Google Analytics Setting

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1941]
Add a google analytics option that is built into NamelessMC. Users would add their google analytics ID and to the setting and google analytics would be enabled. Not sure exactly where this setting would go, maybe in the general settings page. Lots of people use google analytics so I think this would be a good setting to add, and very easy to add.

**Comment by partydragen** [comment]
It will be added in a new upcoming SEO section but no ETA when

**Comment by partydragen** [comment]
Google Analytics have been added in latest build

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/commit/082c1cae3d60dbc665ba9b131b7681f14230b681
