### ISSUE TITLE
Web UI favicon uploader

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1942]
NMC's default favicon system isn't currently very good and is unsupported by many templates. I think in the layout -> images tab you should be able to upload a favicon, to make it much easier and more convenient.

**Comment by Derkades** [comment]
And automatically generate icon files: https://github.com/chrisbliss18/php-ico

**Comment by PikaMug** [comment]
Has this been done yet? I see 6e1d2601a6da907a28e90f2a9f7ebe5943334631 but no uploader.

**Comment by samerton** [comment]
@PikaMug Yep, it looks like it - it should be in the next release (pre-release 10)
