### ISSUE TITLE
Language inconsistency in group sync tab between existing and new rules

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1945]
"disabled" and "not setup"

![image](https://user-images.githubusercontent.com/15892014/101769252-fad3b680-3ae6-11eb-8448-cb0f8cc3efc4.png)

**Comment by Derkades** [comment]
Correct term is "not set up", the integration is enabled but the website doesn't have a role list yet.

**Comment by Aberdeener** [comment]
Thanks, not sure how I didnt notice. Fixed in  1c4326f
