### ISSUE TITLE
removeDiscordRoles doesn't do anything

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1949]
post body
```
{"user":1,"roles":[785970326030778408]}
```
response
```
{
    "message": "Group updated successfully",
    "error": false
}
```

but group is not removed (I still see 'moderator' on profile). It could be related to this:
![image](https://user-images.githubusercontent.com/15892014/101961289-b1c85300-3c09-11eb-9012-19d7c4e64772.png)
but I don't think so. I set it up before the dropdown feature was introduced and have not touched it since.

**Comment by Aberdeener** [comment]
In your StaffCP - Security - Discord Logs, can you screenshot the entry which starts with `Roles removed: ....`?
It *should* list all the groups removed in that api call.

**Comment by Derkades** [comment]
It does say `roles removed: `
![image](https://user-images.githubusercontent.com/15892014/101981390-cbe74d00-3c6c-11eb-8d44-6adb782492d6.png)

**Comment by Aberdeener** [comment]
Cannot reproduce.
Body: 
```json
{   
    "user":1,
    "roles": [
        2, 
        3
    ]
}
```
Group Sync table + Logs [here](https://imgur.com/a/DQUJv94)

**Comment by Derkades** [comment]
Your discord IDs and website IDs are the same, what if it accidentally uses the wrong one somewhere and you don't notice?

**Comment by Derkades** [comment]
Your discord IDs and website IDs are the same, what if it accidentally uses the wrong one somewhere and you don't notice?

**Comment by Aberdeener** [comment]
solution: dont use this endpoint
