### ISSUE TITLE
Problem with forum table

### ISSUE THREAD

**Issue by dgateles** [NamelessMC/Nameless#195]
I have an problem with forum table: [http://craftalizar.com/forum/view_forum/?fid=2](http://craftalizar.com/forum/view_forum/?fid=2)
Statistics table and Last Post table have a width problem

**Comment by samerton** [comment]
This can be fixed with a small template adjustment; lines 15-17 of **styles/templates/Active Template/view_forum_table.tpl** are the widths of the columns, simply tweaking these values so the second value is bigger should resolve your issue.
