### ISSUE TITLE
Maintenance mode does not work

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1951]
After turning on maintenance mode
![image](https://user-images.githubusercontent.com/15892014/101961726-9c075d80-3c0a-11eb-8194-cc877fa87869.png)
I can still visit the homepage, profile, forums, etc. normally.

**Comment by partydragen** [comment]
Because your group is a staff group

**Comment by Derkades** [comment]
ah, I was not used to maintenance mode working this way (e.g. compared to nextcloud where it is meant to stop all database operations)
