### ISSUE TITLE
Day/Night switcher css/json

### ISSUE THREAD

**Issue by jiri240899** [NamelessMC/Nameless#1955]
Hi!
recently I got an idea of ​​what if I used the Day / Night switch on the page, I mean it would be 23:00 and the page would switch to Night mode and at 7:00 it would be light again.
I am currently using CESIUM and so I would like it to be added, I think people would appreciate it.

Greets Hello.

**Comment by Aberdeener** [comment]
If you want this to be added to Cesium, contact the Cesium author. Thanks
