### ISSUE TITLE
Modules Page Additions

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1956]
I think it would be great if at the top of the modules page, or below the modules table, there was a table with some popular modules and install buttons, where users could simply click the button and the files would be downloaded and the module would be installed. This could also be just some buttons, or some other design, to save space if there is a lot of popular modules.

Requirements could be that a module has to have a certain amount of downloads, such as 500 or 1000, before it can be added to the table. Some good modules to add could be staff, friends, vote, forms, rules, members, tebex, crafting store, or others.

For free modules, we could also check updates for those modules by getting the latest version from the nmc website and comparing it to the local version (on your website). If the versions were found to be different, there could then be an update button that users could click, which would download and install the new files automatically.

I think these features would be very nice and cool, and I know for a fact they could be made, so let me know what u guys think!

**Comment by Aberdeener** [comment]
Definantly good potential here, but I think the main thing holding me back from exploring this idea is the security aspect. The idea of needing a minimum # of downloads is a good buffer - but you never know. We can't take responsibility if a module happens to contain malicious code and they install it by accident.

**Comment by Derkades** [comment]
There were discussions of a "package manager" system for Nameless modules and themes in the development or staff channel in discord a while ago. I think @BrightSkyz even implemented something?

**Comment by samerton** [comment]
With security in mind I'd rather this was a module that was distributed separately at first.

As Derkades mentions, BrightSkyz was working on a module named ModuleRepo a couple of years back which overrode the built-in module page to add a one-click install button.

**Comment by Aberdeener** [comment]
Closing as it seems the general consensus is not to support this natively. Too big of a security risk we cannot take responsibility for.
