### ISSUE TITLE
Change Cant Edit User's group logic

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1958]
![current](https://i.imgur.com/Evj4AkB.png)

With the new system, we need to think of a  new way to not let them edit their own groups.

1. They can edit their groups, but just not remove their highest group (?)
2. They cant edit their groups at all
3. We dont care and let them edit their own groups
4. ?

I am sure theres a more logical solution to this. Input appreciated!

**Comment by Derkades** [comment]
I vote option 1, that's how discord does it as well. You can edit groups as long as you don't demote yourself (remove highest group)

**Comment by partydragen** [comment]
Option 1 is the plan

**Comment by Aberdeener** [comment]
![image](https://user-images.githubusercontent.com/26070412/103062299-9c84ea00-4562-11eb-8fc2-63e58fd7f57c.png)

When they cant edit the main group,
1. only groups which are not their main group are displayed in the selection
2. only groups whose order is higher than their main group are shown (a main group means their group with the lowest order)

**Comment by Derkades** [comment]
Looks good. Nitpick: instead of a large obnoxious warning that makes it look like something is seriously wrong, maybe put it as regular text after the main group?

> Main group: Admin (you can't modify this user's main group)

**Comment by partydragen** [comment]
Work like discord 

Can only give roles with have lower priority than yours but main root user must be able to have full access
