### ISSUE TITLE
Problem with play page

### ISSUE THREAD

**Issue by dgateles** [NamelessMC/Nameless#196]
Play page does not show minecraft avatar. Probably have a problem with this line of **core/integration/status/server.php**
`for($row = 0; $row < $max; $row++){
                        $return .= '<span rel="tooltip" data-trigger="hover" data-original-title="'.$Info['players']['sample'][$row]['name'].'"><a href="/profile/' . $Info['players']['sample'][$row]['name'] . '"><img src="https://cravatar.eu/avatar/' .$Info['players']['sample'][$row]['name'] . '/50.png" style="width: 40px; height: 40px; margin-bottom: 5px; margin-left: 5px; border-radius: 3px;" /></a></span>&nbsp;';
                    }`

**Comment by samerton** [comment]
I've taken a look but I can't reproduce any issues. I'm guessing the images are showing up broken? 
If so, can you right click on them -> Inspect Element to view the image URL it's trying to load?

**Comment by dgateles** [comment]
The URL it's trying to load https://cravatar.eu/avatar/server-description and /profile/server-description also

**Comment by samerton** [comment]
@dgateles 
Are you still experiencing this issue? If so, are you using any Bungee/Spigot plugins which might edit the MOTD/server player count?

**Comment by dgateles** [comment]
Yeah, i'm using ServerListPlus

**Comment by samerton** [comment]
@dgateles 
This might be causing a conflict, can you (as a temporary test) disable the plugin to see if it might be the cause?

**Comment by aycgit** [comment]
I didnt even know this was a feature, same problem here, also with slp ill test it when i have time

**Comment by samerton** [comment]
@dgateles @aycgit 
Were you able to resolve the issue, and did removing SLP help at all?

**Comment by samerton** [comment]
I'll mark this issue as closed, as I think this is caused by server-side plugins.
