### ISSUE TITLE
Add download link for v2 plugin to plugin.namelessmc.com

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1962]
https://plugin.namelessmc.com/

https://www.spigotmc.org/resources/nameless-plugin-for-v2.59032/

**Comment by partydragen** [comment]
Then it must be a own button atleast as v2 is not released

**Comment by Derkades** [comment]
Yep, 'add', not 'replace'.

**Comment by samerton** [comment]
https://plugin.namelessmc.com/
