### ISSUE TITLE
Remove unused Pagination class

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1967]
`core/classes/Pagination.php` appears to never be used.

Searches of the while codebase yield no initiations of it.

Can we remove this to remove any confusion?

Making this issue incase it is being used somewhere, but I am guessing its just legacy code leaking in

**Comment by Derkades** [comment]
The only result for "Pagination" in the code was a couple comments and the Pagination.php file itself, so I guess it can be removed. We'll see what happens!

**Comment by Aberdeener** [comment]
*We'll see what happens!*
Famous last words
