### ISSUE TITLE
Migrate languages to GNU gettext

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1968]
* No need to edit 20+ files when making small changes
* Users will be able to edit translations using a web ui (weblate) or software such as poedit to edit the files directly.
* Built-in support for plurals and other language-specific details people might run into

**Comment by samerton** [comment]
Is this universally supported across a range of web hosts and web servers, eg Windows Server + IIS?

**Comment by Derkades** [comment]
Good point. It works on windows, but no one uses IIS anyway. What's maybe more concerning is the requirement to have locale packages installed on the host system, which may break compatibility with some shared web hosting providers.

https://www.php.net/manual/en/book.gettext.php

**Comment by samerton** [comment]
Unfortunately that's why custom functionality like the language system in Nameless is usually easier.
I want to look into ways to make it easier to generate the language files and for people to submit custom translations, that should save some of the difficulty with adding a new term currently.

**Comment by Derkades** [comment]
I think weblate supports generating json files as well, it's not as portable as the GNU gettext format which can also be edited by other programs but I think it's the best solution.
