### ISSUE TITLE
Discord Register

### ISSUE THREAD

**Issue by MicroBotCodes** [NamelessMC/Nameless#1970]
So I think like you can register with your discord account but it will autofill your email but not your password and on your profile, it auto puts your discord.

**Comment by Derkades** [comment]
Social logins?
https://github.com/NamelessMC/Nameless/issues/451
https://github.com/NamelessMC/Nameless-Modules/issues/15

**Comment by MicroBotCodes** [comment]
Yeah did not see that one let me close this.
