### ISSUE TITLE
Some CSS/JS templating upgrades

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1974]
Hello, developers are currently very limited using `$this->addCSSFiles` and `$this->addJSFiles`. I propose that the ability to add the defer and async attributes to js scripts is added, to help with optimization, and we are able to do something like this in CSS:

`<link rel="preload" href="styles.css" as="style" onload="this.onload=null;this.rel='stylesheet'">`

So, we could add/change onload, as, and rel attributes for CSS. This would be extremely easy to implement and would make it easier for devs to optimize templates.

**Comment by samerton** [comment]
52dc45e167042199bf4854f5814c9b81774bfd0a

Examples:
```php
$this->addCSSFiles(array(
  'css/example.min.css' => array('rel' => 'preload', 'as' => 'style', 'onload' => 'this.onload=null')
));

$this->addJSFiles(array(
  'js/example.min.js' => array('defer' => true, 'async' => true),
));
```
