### ISSUE TITLE
Latest repository changes had broken the site after install

### ISSUE THREAD

**Issue by favorit5503** [NamelessMC/Nameless#1979]
**Describe the issue**
Latest repository changes had broken the site after install

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the repository
2. Proceed with install
3. After install you get this error
4. Uncaught Error: Class ':\VPS_Data\UwAmp\www\modules\Core\includes\endpoints\AddGroupsEndpoint' not found in D:\VPS_Data\UwAmp\www\core\classes\Util.php:538
Stack trace:
#0 D:\VPS_Data\UwAmp\www\modules\Core\module.php(268): Util::loadEndpoints('D:\\VPS_Data\\UwA...', Object(Endpoints))
#1 D:\VPS_Data\UwAmp\www\modules\Core\init.php(22): Core_Module->__construct(Object(Language), Object(Pages), Object(User), Object(Queries), Object(Navigation), Object(Cache), Object(Endpoints))
#2 D:\VPS_Data\UwAmp\www\core\init.php(484): require('D:\\VPS_Data\\UwA...')
#3 D:\VPS_Data\UwAmp\www\index.php(54): require('D:\\VPS_Data\\UwA...')
#4 {main}
  thrown

**Expected behaviour**
No error.

**Screenshots**

**NamelessMC version (from AdminCP -> Overview)**
Latest commit 25bc137

**Additional information**
It was done on a new DB and empty folder.

**Comment by Derkades** [comment]
I cannot reproduce this issue, after installing I am redirected to StaffCP and it seems to work just fine. Make sure all files are uploaded properly. Are you visiting any specific page after installing?

**Comment by favorit5503** [comment]
For the info i am using it on a Windows 2019 server and hosting it myself. The page with the error is the next one after hitting finish on install page. If you need i can give a link and an FTP for testing purposes.
