### ISSUE TITLE
Additional Server for the Play page or Server Status

### ISSUE THREAD

**Issue by Liphius** [NamelessMC/Nameless#198]
Hey,

Would it be possible to have 2 active servers on the server status in the home page header and the forum server status? I don't use the play page, but if need be for this - I could.

It's not urgent as I currently do not own an additional server, but we have plans on having 2 servers and It would be nice to display the server status of both on the website.

Many thanks

**Comment by samerton** [comment]
In the upcoming version 2 release, you can set a "parent server" for the homepage query (so it basically accumulates the total player count), however for the foreseeable future this is the only way of having more than 1 server on the homepage.
