### ISSUE TITLE
Infinite login 

### ISSUE THREAD

**Issue by Bubzhome** [NamelessMC/Nameless#1981]
I was trying to login into my admin account which have 2fa enabled 

But when I enter my login details correctly , It redirects me into a page where it tells me to enter my 2fa auth code, after that. The site simply redirect me back to the login page and gave 2 msg

You must input a username.
You must input a password.

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on Auto Http and simple url
2. Use 2fa
3. Login

**Expected behaviour**
To let me login to my admin account

**Comment by Aberdeener** [comment]
Are you using pre7 from our website or the latest code from GitHub?

One way to know is if in your staffcp there is an Announcements tab on the left hand side.

**Comment by Bubzhome** [comment]
Yes , I am using pre7 . I just made this site

**Comment by Aberdeener** [comment]
Is there an Announcements tab in staffcp? Just need to make sure where you
downloaded it from.

**Comment by Derkades** [comment]
Enabling 2FA on pr8 results in the following error (after setup):
```
Uncaught Error: Call to undefined method User::getTopGroup() in /data/modules/Core/pages/user/settings.php:817
Stack trace:
#0 /data/index.php(84): require()
#1 {main}
 ```

**Comment by partydragen** [comment]
Thanks for reporting the issue, It have been fixed

**Comment by Derkades** [comment]
To be clear, the error I sent was different from the original issue. However, since the original issue was in pr7 it might already be fixed.

**Comment by Derkades** [comment]
Update: Logging in with 2FA works fine as well. No "You must input a username.", "You must input a password." errors.
