### ISSUE TITLE
HTML in Announcements Not Work - Pre8

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#1988]
**Describe the issue**
Announcements do not use HTML.

**To Reproduce**
Make an announcement with RAW HTML and the text will show instead of loading actual HTML.

**Expected behaviour**
HTML to load instead of print.

**Screenshots**
![image](https://user-images.githubusercontent.com/10292779/103158613-84dd7980-478d-11eb-93d3-052baabe2241.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr8

**Additional information**
Add more information about the problem if necessary.

**Comment by Aberdeener** [comment]
Thanks for reporting this.
This can be controlled per template. To fix it in your template (as youre using a custom template), change the following in `custom/templates/(template)/navbar.tpl`:
- Where it currently says `{$ANNOUNCEMENT->message}` (in DefaultRevamp it's around line 151), change this to: `{$ANNOUNCEMENT->message|htmlspecialchars_decode}`

You will need to inform your template author of this change as well so they can edit it and fix it. 
Thank you again
