### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by Siyrenz** [NamelessMC/Nameless#1992]
Hey! One of my members tried registering today and they sent me this screenshot. I hope I can fix this asap :) Thank you 

https://cdn.discordapp.com/attachments/780976374822993931/792581867542806539/https___www.ppcraft.icu_register__-_Google_Chrome_27_12_2020_1_37_04_PM.png

**Comment by Aberdeener** [comment]
Hello,
So sorry about that. To fix it, please delete the `group_id` column in the `nl2_users` table in MySQL. You can use PHPMyAdmin to delete the column, or you can run the following MySQL query:
```sql
ALTER TABLE `nl2_users` DROP COLUMN `group_id`
```
