### ISSUE TITLE
API URL sometimes adds two "http://"

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1993]
![img](https://i.imgur.com/zvjxNDx.png)
Not familiar with how this would occur. I assume some strange config with their host's (000webhost, shock) vhost config....

**Comment by Aberdeener** [comment]
Think this is because `$_SERVER['SERVER_NAME']` could contain `http(s)://` in it. 
[Here](https://github.com/NamelessMC/Nameless/blob/0634a459ef6be368ad90047ec59860df9dfa79dd/core/classes/Util.php#L245) and then [here](https://github.com/NamelessMC/Nameless/blob/0634a459ef6be368ad90047ec59860df9dfa79dd/core/classes/Util.php#L255) we use `$_SERVER['SERVER_NAME']` right after setting http or https, so the `$hostname` variable must contain it as well.
Adding a trim to remove this if it exists should solve the issue. Will do tomorrow.

**Comment by Derkades** [comment]
I think this is because they entered the domain with https:// during the installer. What's in config.php?

**Comment by samerton** [comment]
As @Derkades mentions, can you please ensure there is no `http://` or `https://` in the file core/config.php

**Comment by Derkades** [comment]
Maybe it's a good idea to check if the hostname contains http:// or https:// in the installer and throw an error if it does?

**Comment by Derkades** [comment]
The person who had this problem is not responding to further questions (just saying they got the API working) so I'll close this issue
