### ISSUE TITLE
Can't edit Group after verification

### ISSUE THREAD

**Issue by xHelloC** [NamelessMC/Nameless#1994]
If i try edit it get error. "Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in "

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/4ad4c2aabcf5036d0bf27dc9b6d0dd1e8a75bacb
