### ISSUE TITLE
Webhooks are buggy :D

### ISSUE THREAD

**Issue by xHelloC** [NamelessMC/Nameless#1995]
I don't know but i have duplicates those setting :D 
**https://ibb.co/Bqys3Ym**

**Comment by samerton** [comment]
@partydragen any ideas on this one?

**Comment by partydragen** [comment]
That must be a custom panel template issue

**Comment by xHelloC** [comment]
Mhmm its not i change template panel to default and this same
**https://ibb.co/1JmK2Tc**

**Comment by partydragen** [comment]
Ah looks like someone changed the template, I have fixed it now on https://github.com/NamelessMC/Nameless/commit/b1f5eafbc33c67180ef2cf4a86a9ca69587ced25
