### ISSUE TITLE
Nameless Installation: Stuck on Account

### ISSUE THREAD

**Issue by CzEMC** [NamelessMC/Nameless#2]
NamelessMC 0.4.0

Once I enter the Admin account information at http://control.cheshiremc.us/install/?step=account and click Submit, it loads a blank page with only the Step Indicators at the top.

Blank page:
https://gyazo.com/b7dcd0f1bb85d9c40e844fc02155c636

**Comment by samerton** [comment]
Do you have the PHP cURL extension installed on your web server? If not, try the command sudo apt-get install php5-curl.

If it's already installed, I'll update the installer to always display errors so we can diagnose the issue.

**Comment by CzEMC** [comment]
I have already did that. I installed the 1.0 version (From Here) and it seemed to work.
