### ISSUE TITLE
Latest Profile Posts Widget bug

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#2000]
**Describe the issue**
Please describe the issue in as much detail as possible

When using the latest profile posts widget, the link to the post has two slashes instead of one in a certain location. For example:
https://skyfall.coldfiredzn.com/profile/Cqldfire//#post-6

should be https://skyfall.coldfiredzn.com/profile/Cqldfire/#post-6

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a profile post
2. Enable the profile posts widget
3. See error

**Expected behaviour**
What were you expecting to happen?

Expecting the correct number of slashes.

**NamelessMC version (from AdminCP -> Overview)**

v2 pre-8

**Comment by CqldFire** [comment]
I also found an issue where no matter what profile the message is posted on, the link is always to my profile.

For example, exampleuser posted on their profile, so the link should be https://skyfall.coldfiredzn.com/profile/exampleuser/#post-6

However, it is https://skyfall.coldfiredzn.com/profile/Cqldfire/#post-6 instead

**Comment by Derkades** [comment]
Issue 2000 fixed :tada:
