### ISSUE TITLE
'You must select a user's group' when changing groups

### ISSUE THREAD

**Issue by IDKB0x** [NamelessMC/Nameless#2004]
When I try to change someones group it just shows this when i selected a group.

![image](https://user-images.githubusercontent.com/71957022/103182418-b2e7ba00-4870-11eb-9c2b-d3f567fd8ff5.png)

**Comment by Aberdeener** [comment]
Are you using the Default panel template?

**Comment by IDKB0x** [comment]
no

**Comment by Aberdeener** [comment]
Please change to the Default panel template and try again, let me know if it works with the Default template.

**Comment by IDKB0x** [comment]
ok

**Comment by IDKB0x** [comment]
whoops

**Comment by IDKB0x** [comment]
it still didnt work

**Comment by Aberdeener** [comment]
Please send a screenshot of the whole page before you click submit and the error occurs.

**Comment by IDKB0x** [comment]
![image](https://user-images.githubusercontent.com/71957022/103182845-29d28200-4874-11eb-8938-bee81b44af91.png)

**Comment by Aberdeener** [comment]
That is not what it should look like... Here is pre8 user editing page: 
<img width="2287" alt="Screen Shot 2020-12-27 at 4 52 00 PM" src="https://user-images.githubusercontent.com/26070412/103182913-e6701780-4863-11eb-80d5-62e3363444f8.png">

Are you running version pre7 or pre8? Check in StaffCP - Dashboard

**Comment by IDKB0x** [comment]
pre 8

**Comment by IDKB0x** [comment]
![image](https://user-images.githubusercontent.com/71957022/103182951-e9bfcf00-4874-11eb-9ce7-eadec244f3a9.png)

**Comment by Aberdeener** [comment]
Please edit the file `custom/panel_templates/Default/core/users_edit.tpl` and set it's contents to: [this](https://raw.githubusercontent.com/NamelessMC/Nameless/v2/custom/panel_templates/Default/core/users_edit.tpl). Let me know if it works then

**Comment by IDKB0x** [comment]
ok

**Comment by IDKB0x** [comment]
ty it worked
