### ISSUE TITLE
Cannot register on nameless

### ISSUE THREAD

**Issue by Tyyppipvp** [NamelessMC/Nameless#2009]
So I work on a server and it is my task to get the forum registration up and running however when I attempt to register a random error pops up https://gyazo.com/31f8205f8ee5503d8d162849fdaff830 I contacted the host and they said it would be the theme but didnt help further at least yet

**Comment by jordi2010** [comment]
If I'm not wrong there is already a solution in the Discord server present for this bug with registration.
![image](https://user-images.githubusercontent.com/37302148/103203123-8a090880-48f4-11eb-918d-3873c2699f29.png)

**Comment by Aberdeener** [comment]
Yes, attempt the fix in the announcements channel. Feel free to reopen this if that doesn't fix it. Thanks

**Comment by samerton** [comment]
If this doesn't fix the issue, please switch to the Default Revamp template to see what happens there.
