### ISSUE TITLE
Error translating

### ISSUE THREAD

**Issue by Legomix13** [NamelessMC/Nameless#201]
![captura](https://cloud.githubusercontent.com/assets/13416327/15541613/940942a6-228d-11e6-99c5-cabd7421ad9d.PNG)
Its not "Camcelar" its "Cancelar"
If you need help translating from english to spanish I can help

**Comment by dgateles** [comment]
You can translate it opening the folder **styles/language/Spanish**

**Comment by samerton** [comment]
Fixing now, thanks for spotting this.

**Comment by Legomix13** [comment]
I translated all to spanish:
https://mega.nz/#!UMRCAIwa!6RAKVPkJFBWWa4GLnXwXKliQOzm3sDEjA75izxUzmos

**Comment by samerton** [comment]
Thanks! I've included the changes in the latest commit.
