### ISSUE TITLE
Announcement HTML support

### ISSUE THREAD

**Issue by jordi2010** [NamelessMC/Nameless#2010]
Like in the cesium template for 2.0.0-pr7. Give people the chance to write HTML code inside the announcement. This will give much more flexibility for creating announcements.

![image](https://user-images.githubusercontent.com/37302148/103202861-de5fb880-48f3-11eb-8f39-ee7c438e871e.png)

**Comment by Aberdeener** [comment]
This was added for pre9, and I think @Xemah has added it to cesium now?

**Comment by Derkades** [comment]
Duplicate of #1988
