### ISSUE TITLE
Toggle showing of certain group in group bar for members module (member list page)

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2013]
So when creating/editing group in StaffCP, if members module is installed, there would be an option "**Hide this group on member list page**" that can be toggled as enabled/disabled...

*If enabled*:
That group will not be shown on members page bar.

*If disabled*:
That group will be shown on members page bar, with every other enabled groups.

---

This can be extremely useful if you have big network, and have subservers like:
-Survival
-Factions
-SkyBlock
-...

You want to have 1 user to be Administrator only on SURVIVAL subserver, so you can create groups named "Administrator" and "SURVIVAL" and give to them "Administrator" group as primary group and "SURVIVAL" as secondary group and later if they get promoted, you can just create another group named the same as subserver name where they got promoted to staff member, for example "FACTIONS", and give them that additional secondary group called "FACTIONS".

*I hope I am not confusing anyone, this is pretty simple but yet very useful thing to have implemented on Nameless software.

**Comment by samerton** [comment]
I think this is more for the Members module - could you amend https://github.com/partydragen/Members/issues/14 if necessary?

**Comment by TheJoshue** [comment]
@samerton the main problem is that if I post it there, as I did in July (the one you mentioned), it isn't even commented as you can se, nothing.
That's why i posted it here and I hope it'll be done...

**Comment by partydragen** [comment]
@TheJoshue it is on the to do list and i plan to add it in the coming days
