### ISSUE TITLE
Contact Email

### ISSUE THREAD

**Issue by WhenUHackUNoob** [NamelessMC/Nameless#2016]
Add the option where instead of using a contact email, you can supply a Webhook Link for those who do not have an active email and such, would also be really helpful for me :smile:

**Comment by Derkades** [comment]
@partydragen webhooks in forms module?

**Comment by Aberdeener** [comment]
I think this is about the built in contact page? Can you confirm?

**Comment by WhenUHackUNoob** [comment]
Yes it is @Aberdeener
