### ISSUE TITLE
Plugin Based Status Page

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#2017]
I really want my status page to be like this
https://tensa.co.ua/status/ (also see attached image)
But I cannot do that the way my network is setup

Is it possible that a feature could be added that makes the ping work with the nameless plugin?
I am thinking of a system similar to push notifications.
When the status page is visited it sends a request to the plugin, and the plugin responds with online players. If no response is received then the site says the server is offline.

Link to other github issue: https://github.com/NamelessMC/Nameless-Plugin/issues/101

![image](https://user-images.githubusercontent.com/10292779/103243244-42e83b00-4927-11eb-91db-9b66fb16a04a.png)

**Comment by Derkades** [comment]
Unless I'm missing something this is already possible, with the current status page and some css changes

**Comment by StormyIceLeopard** [comment]
how? see attached
![image](https://user-images.githubusercontent.com/10292779/103250052-0c6aea00-4940-11eb-8ba2-af89a32a6533.png)

**Comment by Derkades** [comment]
@samerton Does the website use the player list provided by the plugin, when status query is disabled? Or does it only use online/offline status provided by the plugin

**Comment by samerton** [comment]
> @samerton Does the website use the player list provided by the plugin, when status query is disabled? Or does it only use online/offline status provided by the plugin

I don't believe the plugin is used at all for the status page

**Comment by Derkades** [comment]
I thought you made it so it only falls back on pinging if the plugin hasn't sent data for a while, was that a different page?

**Comment by samerton** [comment]
> I thought you made it so it only falls back to pinging if the plugin hasn't sent data for a while, was that a different page?

That's just for the small server status information box that shows in each page's header currently

**Comment by supercrafter100** [comment]
This feature has been added in #3244
