### ISSUE TITLE
Widgets on all pages

### ISSUE THREAD

**Issue by Fjuro** [NamelessMC/Nameless#2022]
**Describe the issue**
Please describe the issue in as much detail as possible
When I set some widgets to appear only on the Index page, they still appear on all pages where is at least one widget

**To Reproduce**
Steps to reproduce the behaviour:
1. Set a widget to appear only on the Index page
2. Set another widget to appear only on ex. Forum
3. Open Forum, both widgets will be there

**Expected behaviour**
What were you expecting to happen?
The widgets should only appear on the selected page(s) (Index in this case)

**Screenshots**
https://cdn.fjuro.eu/public/zYcS_cN8gO.png
https://cdn.fjuro.eu/public/TzjeAMccRG.png

**NamelessMC version (from AdminCP -> Overview)**
pre8 

**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
This will be fixed in pre-release 9 😃
