### ISSUE TITLE
Panel navbar too narrow

### ISSUE THREAD

**Issue by jordi2010** [NamelessMC/Nameless#2023]
**Describe the issue**
When a menu item text is too long (panel), it's not displayed as it supposed to be

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'panel NamelessMC'
2. When dutch language is used, click on 'configuration' and your menu item text not proper handled when too long.
3. OR change a menu item text so it's long enough to display like here.

**Expected behaviour**
What were you expecting to happen?
Break the sentence when to long.

**Screenshots**
![image](https://user-images.githubusercontent.com/37302148/103359348-07c94180-4ab8-11eb-8622-98f128b824b0.png)

** Possible fix **
Remove white-space: nowrap; on .collapse-item

**NamelessMC version pre9**

**Comment by Derkades** [comment]
The navbar could be a bit bigger, but this translation is quite long. I'll update it to be just "Profielvelden" instead.

**Comment by Derkades** [comment]
Also in other languages
![image](https://user-images.githubusercontent.com/15892014/103482960-40cd2300-4de4-11eb-84c6-1b1284378934.png)
