### ISSUE TITLE
Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by HexDubbers** [NamelessMC/Nameless#2026]
**Describe the issue**
This is a self XSS vulnerability that can also be used against admin users.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new topic or reply.
2. enter in the following text:
`<TABLE>
&lt;UL&gt;&lt;LI&gt;XSS
&lt;META HTTP-EQUIV=&quot;refresh&quot; CONTENT=&quot;0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K&quot;&gt;`
3. Post it
4. Find post or reply and hit edit.
5. See result.

**Screenshots**
![xss](https://user-images.githubusercontent.com/76656985/103389788-fe9f9b00-4ade-11eb-9004-768f32dd1af2.PNG)

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC version 2.0.0-pr8

**Additional information**
I used PHP5.6 during testing but can test in PHP7 if needed. 
The link to edit the post can be sent to administrative users and will automatically run the javascript.

**Comment by Aberdeener** [comment]
Can reproduce, however I dont know a good solution to this.
If we use Output::getPurified on the edit page, it seems to mess up the post alot.

**Comment by HexDubbers** [comment]
> 
> 
> Can reproduce, however I dont know a good solution to this.
> If we use Output::getPurified on the edit page, it seems to mess up the post alot.

Ill see if I can figure out a fix for it tonight.

**Comment by BaxAndrei** [comment]
If it hasn't already been resolved, a few months ago, my users could inspect the source and add anything they wanted to the posts.

**Comment by samerton** [comment]
We already parse the content before passing it into the editor - looks like the editor itself is then decoding the content

**Comment by samerton** [comment]
0b0e2f11cc2ec0bc93348dd49e83bb8806ce8c2c should do it, hopefully there won't be any knock-on effects as a result

**Comment by HexDubbers** [comment]
> 
> 
> [0b0e2f1](https://github.com/NamelessMC/Nameless/commit/0b0e2f11cc2ec0bc93348dd49e83bb8806ce8c2c) should do it, hopefully there won't be any knock-on effects as a result

I'll try it out and see if can get anything else.
