### ISSUE TITLE
Invalid reCAPTCHA response

### ISSUE THREAD

**Issue by NorgePlayz** [NamelessMC/Nameless#2027]
**Describe the issue**
It's showing **Invalid reCAPTCHA response.** if Captcha Type set as **hCaptcha**

**Expected behaviour**
Passing the reCAPTCHA response

**Screenshots**
https://prnt.sc/wdh5nv

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr9

**Comment by samerton** [comment]
Does the issue happen if you use the Default Revamp template?

**Comment by NorgePlayz** [comment]
> Does the issue happen if you use the Default Revamp template?

Yes

**Comment by Aberdeener** [comment]
Cannot replicate, this could have been fixed with Sam's captcha rewrite. Tried both captcha methods and on multiple pages (login, register, contact, etc). Never occurred. (I used the test secret key and site key from the Google developer portal)
