### ISSUE TITLE
Minecraft->web group sync does not trigger web->discord sync

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2032]
Reported by Govindas in Discord, have not tried to reproduce myself.

Adding a group in StaffCP syncs to Discord sucessfully. Adding a group in-game syncs to the website sucessfully, but does not cascade to Discord.

**Comment by Aberdeener** [comment]
Weird, assuming the plugin uses the `addGroups` endpoint, I dont see why it wouldnt work.
See [here](https://github.com/NamelessMC/Nameless/blob/e277fa2da073c8631cabe4431de19735563486a4/modules/Core/includes/endpoints/AddGroupsEndpoint.php#L37)

**Comment by Aberdeener** [comment]
Closing in favour of #2036
As per derk and I conversation today with Box, the bot is now receiving the request when the plugin sends the serverInfo request, but does not seem to be adding the role.
