### ISSUE TITLE
Show others players DM / reporting button

### ISSUE THREAD

**Issue by NorgePlayz** [NamelessMC/Nameless#2035]
If someone advertising other Minecraft Server, we should access to see others players DM and report button

**Comment by Aberdeener** [comment]
Not sure I understand.
You want a button for other website users to report a specific DM from another user?
And you want site staff to be able to read DM?
Please confirm

**Comment by NorgePlayz** [comment]
Not other website. Like a report button on DM like as forum posting.

(sorry for my bad english)

**Comment by Derkades** [comment]
@Aberdeener Allow users to report DMs and moderators to look at DMs.

Not sure if this is going to happen, @samerton expressed understandable concerns over privacy when I asked to expose DMs through the API.

**Comment by Aberdeener** [comment]
Yeah im not in favour of adding this
