### ISSUE TITLE
Many issues with ingame group sync

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2036]

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/103467432-4fb5c600-4d4f-11eb-981c-eb3c39172d40.png)
![image](https://user-images.githubusercontent.com/15892014/103467427-46c4f480-4d4f-11eb-9264-97b2ed1a81ce.png)

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/103484061-272fd980-4dec-11eb-94c0-4112b43ad8b2.png)

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/103634894-02e90f80-4f48-11eb-86e1-116efe111040.png)

**Comment by Aberdeener** [comment]
I cannot find any sort of theme to all of these mentioned situations... They all use different parts of code. 
Works for some people and doesn't for others.
Not too sure how to start debugging this

**Comment by Aberdeener** [comment]
https://discord.com/channels/246705793066467328/247865182477484032/796971266925527091

**Comment by Derkades** [comment]
@Aberdeener You've modified the addgroups and removegroups endpoints which are not used by ingame group sync (not used by anything actually). The spigot plugin group sync happens in the serverinfo endpoint

**Comment by Derkades** [comment]
:warning: :warning: :warning: 
![image](https://user-images.githubusercontent.com/15892014/104106122-86da2900-52b3-11eb-8736-cab25e6d9b40.png)

**Comment by Aberdeener** [comment]
that was fake news.
Anyways, I'll spend time today and take a look. Finally finished the
chaotic week

**Comment by Aberdeener** [comment]
https://github.com/NamelessMC/Nameless/commit/5880e065b4d35c150e766318ebb1aa026beb8b9e
If anyone here would like to test on their "real life" scenario, that would be great. 99% sure this fixed it

**Comment by IDKB0x** [comment]
Hi, I am willing to test this. :)

**Comment by IDKB0x** [comment]
But what do you want me to do.

**Comment by Derkades** [comment]
To test this, follow the installation instructions of the plugin again to update the API endpoints and enter server-id in config.yml

**Comment by IDKB0x** [comment]
ok im starting my server

**Comment by IDKB0x** [comment]
It doesn't seem to be working. Here are the steps I did: I installed the latest version of the plugin on ci.derkad.es. then I entered the server id and api url in the config, lastly I gave myself the admin group on the server and I have not received it on the web

**Comment by Derkades** [comment]
Are you in the discord server? It's easier to have a quick back and forth conversation there without sending everyone a notification and/or email.

**Comment by IDKB0x** [comment]
yes i am my username is B0x 2.1.1.2#2112

**Comment by Aberdeener** [comment]
Closing with that commit for now.
Everything worked for our testers. If you have issues, please comment so we can look into it.

**Comment by PikaMug** [comment]
https://github.com/NamelessMC/Nameless-Link/issues/117
