### ISSUE TITLE
pluralForm() redeclaration error in Russian language

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2038]
```
Fatal error: Cannot redeclare pluralForm() (previously declared in /custom/languages/Russian/version.php:20) in /custom/languages/Russian/version.php on line 20
```
When doing this:
![image](https://user-images.githubusercontent.com/15892014/103535539-2dc45c80-4e91-11eb-8046-eb09a3b03f17.png)

**Comment by Aberdeener** [comment]
This is confusing, during a search of the whole codebase, `pluralForm()` function is only defined in the language's `version.php` file.
I also double checked that the `version.php` file is not `require()`d multiple times. 
Maybe they added another function into their `version.php` file? Hard to say

**Comment by Aberdeener** [comment]
<img width="576" alt="Screen Shot 2021-01-25 at 2 31 05 PM" src="https://user-images.githubusercontent.com/26070412/105774330-03a70d00-5f1a-11eb-99a5-b2fc946dbf6c.png">

**Comment by Derkades** [comment]
Temporary workaround: replace all files in `/custom/languages/Russian` with https://cloud.derkad.es/s/MowxJJmHR29tw4f

This zip contains updated translations and has the plural function disabled. Some translations that require the plural function won't work, but that's better than the website being broken entirely.

**Comment by Derkades** [comment]
Another report today:
![image](https://user-images.githubusercontent.com/15892014/109538372-48e1d000-7ac0-11eb-8e32-b166686e8a2b.png)
it does seem related to the email page somehow

**Comment by Derkades** [comment]
lol, nice workaround

**Comment by Aberdeener** [comment]
if it works it works
