### ISSUE TITLE
Server Status Widget shows server as offline

### ISSUE THREAD

**Issue by PauerBanane** [NamelessMC/Nameless#2040]
**Describe the issue**
I just installed a fresh nameless v2 pre9 installation, but the server status widget is not showing the server as online.
The Status page therefore does.

**Screenshots**
![image](https://user-images.githubusercontent.com/58947823/103553241-7984ff00-4ead-11eb-82da-1b0d8d2b4ab2.png)
![image](https://user-images.githubusercontent.com/58947823/103553271-843f9400-4ead-11eb-8f70-bcdde7670ca1.png)

**NamelessMC version (from AdminCP -> Overview)**
v2 pre9

**Comment by PauerBanane** [comment]
Seems like there's a json decoding error:
`if ($server != null) {
                $server_array = json_decode(Util::curlGetContents(Util::getSelfURL() . URL::build('/queries/server/', 'id=' . $server->id)), true);
				echo json_last_error_msg(); // Print out the error if any
                $server_array['name'] = $server->name;
                $server_array['join_at'] = $server->ip;
				$server_array['version'] = "1.16.4 höhö";
				
                $this->_cache->store('server_status', $server_array, 1);
            }`
The last json error message is "Syntax error", but the json input is this:
`{ "status_value": 1, "status": "Online", "player_count": "1", "player_count_max": "50", "player_list": [ { "name": "PauerBanane", "id": "d79f6fac-08c4-419b-920f-2115b0d5bbd3" } ], "x_players_online": "Derzeit sind 1<\/strong> Spieler online.", "motd": "H\u00e4\n\u00a7rtest", "version": "Wartung \u00a771\u00a78\/\u00a7750" }`

**Comment by PauerBanane** [comment]
So after all:
My Server failed to get the contents from itself, but it worked for json data on another host.

My solution was to edit `/etc/hosts` file and replaced the dns entries for the server-ip to `localhost`

**Comment by Aberdeener** [comment]
I really appreciate your debugging efforts!
I will reopen this to see about an alternate way to make this work.

**Comment by samerton** [comment]
Looks like HTML from the MOTD needs escaping when building the JSON response

**Comment by Aberdeener** [comment]
@PauerBanane Hi, if you want to verify this works, please apply the changes in 84b1725 to your codebase. I tested using your server's url you linked above, but better to be safe than sorry. Thanks again for your detailed debugging.
