### ISSUE TITLE
Configuration installer

### ISSUE THREAD

**Issue by dcjgeek** [NamelessMC/Nameless#2041]
When installing the latest pre-release 9 I receive this error.

_SQLSTATE[42S02]: Base table or view not found: 1146 Table 'slabgq_namelesshome.nl2_widgets' doesn't exist_

**Comment by samerton** [comment]
Your database failed to initialise correctly, can you please clear the database and reinstall?

**Comment by Aberdeener** [comment]
Closing this now, hope you were able to get it installed :)
If not, please reopen this.
