### ISSUE TITLE
Error message when users click on link to verify email 

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2042]
Reported by multiple people in the guild. A message saying it failed pops up on the screen, but apparently next time they login they are verified anyways.

**Comment by StormyIceLeopard** [comment]
My players are still unverified, even after they receive that error. So, I do not know who is claiming that their users are verified later but mine are not.

**Comment by Aberdeener** [comment]
Thanks for the clairification. Someone else told me that

**Comment by Aberdeener** [comment]
*time to go down the rabbit hole*

**Stormy's series of events**
1. His user registered with the `/register <email>` command.
2. They did not receive the email with the normal link (see `Problem 1`) (No email errors were in StaffCP)
3. Stormy manually resent the email using the Resend Email Verification (6206b0c) button in StaffCP
4. When they clicked on the link sent to them, they get the error which says "Unknown Error while validating your account" (this error is only thrown when there is no user in the DB with a `reset_code` matching the `c` param in the email link. See the attached photo, in the email link there is no `c` value. It is blank, causing this error.) 
![image](https://user-images.githubusercontent.com/26070412/104413165-ae82f880-5522-11eb-8951-6b7e9bb5b9cb.png)

**Other user's series of events**
1. User registered on website. 
2. Received verification email, but it had the broken `&c=` link as well.

**We have 3 root issues:**
1. The `/register <email>` command does not appear to send a verification email.
2. Resending a verification email from the StaffCP seems to not attach the `reset_code` in the link (See below image) (This is  not always the case, just seems to happen for some users and not for others).
3. Registration email seems to not attach the `reset_code` in the link (See below image) (This is  not always the case, just seems to happen for some users and not for others).

**Additional info:**
- Stormy has API verification and email verification enabled.

**My debugging so far:**
Problem 1:
- The plugin uses the RegisterEndpoint file and determines whether to send an email or not here (In Stormy's case, this returned true as he had email verification enabled): https://github.com/NamelessMC/Nameless/blob/4da1b92b5f25d89361be5629d08bcf1a906de675/modules/Core/includes/endpoints/RegisterEndpoint.php#L67
- The `sendRegistrationEmail` function is then called: https://github.com/NamelessMC/Nameless/blob/4da1b92b5f25d89361be5629d08bcf1a906de675/modules/Core/includes/emails/register.php#L12
- As far as I can see, I dont know how the email would not be sent. Everything seems fine.

Problem 2:
- When an admin resends a validation email, the code is not provided (the link in the email ends in `&c=`).
- The same `sendRegistrationEmail` function is then called: https://github.com/NamelessMC/Nameless/blob/4da1b92b5f25d89361be5629d08bcf1a906de675/modules/Core/includes/emails/register.php#L12
- The `$code` variable is from a direct query from the database, specifically the `nl2_users.reset_code` column. It being empty means for some reason it was wiped...
- This worked fine for me, as I tested right now, but I need to experiment with the settings Stormy and other people have given me.
- [Happened here](https://discord.com/channels/246705793066467328/247865182477484032/798805094048989204) (this user says they registered on the website. API validation is disabled, and email validation is enabled. Their users' email link was empty as well, but they didnt resend the validation email), [and here](https://discord.com/channels/246705793066467328/247865182477484032/795781415832518706) (still waiting for more info)

Problem 3:
- When an email validation email is sent, sometimes the code is not provided.
- The `$code` variable passed to the emailer is created here: https://github.com/NamelessMC/Nameless/blob/4da1b92b5f25d89361be5629d08bcf1a906de675/modules/Core/pages/register.php#L346
- There seems to be no reason for the `$code` to be blank... 

Take everything here with a grain of salt, this could have all been some SUPER WEIRD edge case (which would still be good to stomp out).
I will be testing this thoroughly in the coming days, as none of this makes any sense to me.
I will update this comment when I have more clarity about what is actually happening.
Reasonable time to link #1577, as things like this prove we need a rewrite of registration, validation and everything. Too confusing in it's current state.

**Comment by StormyIceLeopard** [comment]
To add to this:
Further testing, 3 new users were able to register and the link would have codes. So the issue where the links are not having the codes has yet to repeat itself.
But I am still encountering 2 rather large issues:

1. The email is not sent automatically after running the `/register` command. Someone has to go to the `User Management` page in `StaffCP` and click `Resend Activation Email` on that user for the email to be sent out.
2. This other issue noted here: https://github.com/NamelessMC/Nameless/issues/2074

**Comment by StormyIceLeopard** [comment]
HUGE DEVELOPMENT!
After much messing around I have determined the issue, or a issue.
When /register is ran and the email is, in our testing, an aol email account the auto email is sent immediately to spam. If the email is a gmail email, the email is not received at all.

Not sure what this means, but hey its something.

**Comment by samerton** [comment]
Empty code fixed by 90563f62f0055b10f92443a909d50071f2e2ef18

This happened when a reset password email was sent out before the account was validated

**Comment by partydragen** [comment]
> Empty code fixed by [90563f6](https://github.com/NamelessMC/Nameless/commit/90563f62f0055b10f92443a909d50071f2e2ef18)
> 
> This happened when a reset password email was sent out before the account was validated

How does that make sense? the code should still had displayed there is nothing there telling user to need to be active to generate the code

**Comment by Aberdeener** [comment]
Closing as we got a fix for the empty code, and I have not seen this issue happen since pre11 :)
