### ISSUE TITLE
Improve the functionality and style of Group select

### ISSUE THREAD

**Issue by DrakePork** [NamelessMC/Nameless#2043]
At the moment the Groups section of user edit is quite bland and due to it being just a select list can easily be messed up due to you clicking on a new group without holding ctrl will remove all other groups from the player, and since the group box is quite small if you have a lot of groups it can be hard to find any of them. 

It would be nice if the group selection area could basically be made bigger and  more visually pleasing & that clicking and then clicking on a group is how you select/deselect them without having to hold ctrl.

One idea could be to make the entire group area just two list, one which is like "User Groups" and then another one with "Available Groups", like this:
![nvnvbnvbn](https://user-images.githubusercontent.com/29175884/103720555-83008b00-4fc3-11eb-8207-c00874cc3392.PNG)
and then you can just drag a group to the other side:
![gsfjhfgkfgk](https://user-images.githubusercontent.com/29175884/103720563-8a279900-4fc3-11eb-9825-f71b3773645a.PNG)

**Comment by Aberdeener** [comment]
Thank you for the idea - the example is also great so we know what to aim for.
I made the current group select thing quite fast in order to get pre8 out.
I'll mark this for 2.0.0 and see how it goes!

**Comment by partydragen** [comment]
yea i completly agree, i did comment it to dev team when we switched to new group system as its way to messy but need someone who know a good design for it
