### ISSUE TITLE
Applications / Forms Suggestion.

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless#205]
Hello.

I am not 100% sure where suggestions go but I am going to put it here as this seems to be the right place.

Anyways..

Would the ability to create custom applications / forms be something you add in the future. I know you have the "/apply" application however being able to create more would be nice!

Thanks for reading :+1:

**Comment by Liphius** [comment]
Would definitely be a nice feature. Looking forward to it!

**Comment by aycgit** [comment]
Looking forward to this

**Comment by samerton** [comment]
https://namelessmc.com/resources/resource/43-forms-module/
