### ISSUE TITLE
Validate banner appears for already validated users

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2052]
![image](https://user-images.githubusercontent.com/15892014/104583444-6a4a4200-5661-11eb-9f5f-35f957035024.png)

Unfortunately I don't have details why this happens at the moment. Sometimes, message is even displayed to root users. The API returns 'account is already validated' when trying to validate.

**Comment by samerton** [comment]
Currently, this will show if:
- API validation is enabled (StaffCP -> Configuration -> API)
- You are in the default group

I don't think there's a bug here, just not the best way of doing things which is due a rework.

**Comment by Derkades** [comment]
Would an easy fix be to add a third condition that checks if the user is validated (the same way the API does)?

**Comment by samerton** [comment]
Not sure this fix is what we need - when you register with API verification enabled and email verification disabled, we automatically validate the account.

This is so the user is able to log in and view the command in the first place - this change means they won't be able to see the command.

**Comment by Aberdeener** [comment]
Fair, thanks for the explanation

**Comment by chrlew082** [comment]
What if you added a second layer of verification. This second layer would only exist if you have api verification on, it verifies you when you register so you can see the command correct? So what if we added the second layer which is the api verification, while still keeping them in the unconfirmed group?

or we could just remove requiring verification to login.

**Comment by Derkades** [comment]
> What if you added a second layer of verification. This second layer would only exist if you have api verification on, it verifies you when you register so you can see the command correct? So what if we added the second layer which is the api verification, while still keeping them in the unconfirmed group? Then once they’ve verified in game, it puts them in member.
> 
> or we could just remove requiring verification to login.
> 
> /!\ 

See https://github.com/NamelessMC/Nameless/issues/1577

**Comment by partydragen** [comment]
it got displayed when user have default group + reset code, Example simple as requesting password reset and never finish it

Did not listen if API Verification was enabled or not, Always got displayed when default group + reset code condition meet

In thery validate system works as along user setting up post validation group as another group and not default one then it all works, But may better to add a new validated colum to user table to ignore group check incase user using same validate group as default group
