### ISSUE TITLE
Weird webhook behaivour 

### ISSUE THREAD

**Issue by FiveEYZ** [NamelessMC/Nameless#2053]
**Describe the issue**
Please describe the issue in as much detail as possible
Im trying to use multiple webhooks that are both using the trigger "new topic", they both work for the forum they are selected for. 

Issue is when i make an additional forum that has no webhook selected new topics are posted to both webhooks.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add 2 discord webhooks with trigger "new topic" (they post to their own channel).
2. Make 3 forums.
3. Add first webhook to first forum.
4. Add second webhook to second forum.
5. Make sure 3rd forum does not have a webhook selected in settings.
6. Make a new topic in the 3rd forum.

**Expected behaviour**
What were you expecting to happen?
Topics posted to a forum that has no webhook selected should not be pushed to webhooks that is configured with "new topic".

**Screenshots**

**NamelessMC version (from AdminCP -> Overview)**
Running NamelessMC version 2.0.0-pr9

**Additional information**
Add more information about the problem if necessary.
I have tested posting in only forum 1 and 2, only one of the webhooks get triggered in both cases

**Comment by Aberdeener** [comment]
Thank you for the detailed report. I will attempt to recreate this and look into it tomorrow!
