### ISSUE TITLE
Config Unavailable - pre-9 installer

### ISSUE THREAD

**Issue by Mubeen142** [NamelessMC/Nameless#2054]
The latest installer is causing a strange bug to happen, when you go through the nameless installer follow the steps after entering your database information the installer gives a “config unavailable” error. Even after refreshing the error stays.

However after initiating and entering the database information there is a config.php file created but this file is empty.

The user is however able to install NamelessMC-pre7 perfectly fine the the old installer.

**Comment by Aberdeener** [comment]
Should have been fixed with d7e50c0, thanks Sam
