### ISSUE TITLE
Make NamelessMC more neutral

### ISSUE THREAD

**Issue by Mubeen142** [NamelessMC/Nameless#2056]
I believe we should make NamelessMC a bit more neutral to encourage  other communities to use the Software more.

NamelessMC is mainly built for Minecraft but we should promote it being used for other forum pages. That’s why we need to make certain things more neutral.

for example, when registering the default language says “Minecraft Username” this should be “Username” instead. Also with some other language phrases.

**Comment by Derkades** [comment]
I believe this is the direction we are slowly going towards right now. For example, the v2 API has recently been rewritten no longer use UUIDs and instead use NamelessMC user ids and NamelessMC usernames.

The full v2 release will have an option to disable Minecraft integration in the installer: #1592

**Comment by partydragen** [comment]
Minecraft parts will also be moved into its own module

**Comment by Derkades** [comment]
Closing in favour of more specific issues
