### ISSUE TITLE
Big performance upgrade on most of tasks due to missing index on database table (solution ! )

### ISSUE THREAD

**Issue by deltaflyer4747** [NamelessMC/Nameless#2057]
**version:** pr7
_(please note that in this, nl2_ stands for $prefix)_
**issue:** database heavy actions suffer from very long loading time on bigger datasets, even plain page loading takes quite long (several seconds)
**cause:** missing index on nl2_posts, column topic_id
**solution:** `alter table nl2_posts add index(topic_id);`
**impact:** without this index, thread move between forums takes for me 5 minutes (40k records in nl2_posts), with this modification around 1s.

**Comment by Derkades** [comment]
I've been wanting to look into this for some time, interesting to see how it makes an actual difference for large sites like yours

**Comment by deltaflyer4747** [comment]
well, instead of digging through all 40k records to find proper one, sql just reaches out for index and reads proper record(s) ID(s) which is incomparatively faster.

**Comment by Aberdeener** [comment]
Thanks for looking into this.
Would be good to make a draft PR with this change, along with any other tables which could benefit from similar changes.

**Comment by deltaflyer4747** [comment]
Second part is quite simple. Any column of any table you use as "WHERE" clause in any SQL statement (for example this issue is related to `SELECT from nl2_post WHERE topic_id = %s ORDER BY post_date DESC;`) should have appropriate form of index. Adding index for post_date might get even better results, but of that i am not sure.
As for first part, sorry, never did pullreq :(

**Comment by samerton** [comment]
nl2_posts topic_id index added in 5aa650957bd5b5b6f76bedaf034c372f88113f7a

Will continue to review and add more in the future

**Comment by Derkades** [comment]
If anyone experiences a specific slow page or query please create a new issue
