### ISSUE TITLE
Invalid Token Please Try Again.

### ISSUE THREAD

**Issue by oisin1973** [NamelessMC/Nameless#2059]
**Describe the issue**
Please describe the issue in as much detail as possible

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'forums.dusknetwork.net'
2. Click on 'register'
3. Scroll down to 'And enter your details'

**Expected behaviour**
What were you expecting to happen?
For it to register
**Screenshots**

**NamelessMC version (from AdminCP -> Overview)**
2.0.0 PR 7
**Additional information**
Add more information about the problem if necessary.

**Comment by Derkades** [comment]
Are you using a custom template, or default(revamp)?

**Comment by BaxAndrei** [comment]
Maybe have something to do with IP in iframe?

**Comment by samerton** [comment]
As @BaxAndrei says, it could possibly be related to using an iFrame - does the issue happen if you access your website directly, not using the iFrame?

Also, make sure sessions are saving correctly on the host.

**Comment by Derkades** [comment]
Closing due to lack of response, please reply if you have more information and we'll reopen.
