### ISSUE TITLE
Forum Labels

### ISSUE THREAD

**Issue by frendlyZ** [NamelessMC/Nameless#2060]
Hello, 

After updating to NamelessMC v2.0.0 pre-release 9 I can't use my forum labels. It shows them on the right side when creating a new post, but it doesn't show it after creating a post. I heard it is a known bug, just making sure it is reported. Let me know if there is any solution, thanks :)

**Comment by samerton** [comment]
Hi,

Can you please make sure your template is up to date - there were some changes to labels in pre-release 9 which require a template update

**Comment by Aberdeener** [comment]
Closing this as we havent heard back. Feel free to reopen if you have confirmed your template is up to date + you are using DefaultRevamp and it is still not workin' :)
