### ISSUE TITLE
mcassoc not updated to new group user system

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2061]
**Describe the issue**
Error during mcassoc due to it not being updated to new group user system

**Expected behaviour**
for it to have been updated

**Screenshots**
![image](https://user-images.githubusercontent.com/26070412/105069678-224b6680-5a37-11eb-9f90-3186fd7b98a8.png)

**NamelessMC version (from AdminCP -> Overview)**
pre9

**Additional information**
https://github.com/NamelessMC/Nameless/blob/a96e228f7da8e82a13d2d7ccfc45937099b84689/core/integration/run_mcassoc.php#L97

**Comment by Derkades** [comment]
solution: remove mcassoc

**Comment by Aberdeener** [comment]
Agreed

**Comment by samerton** [comment]
No harm in keeping it, it's an extra feature that does get used

**Comment by incopeable** [comment]
GodBless 
On martes, enero 19, 2021 Sam <reply@reply.github.com> wrote:



No harm in keeping it, it's an extra feature that does get used
