### ISSUE TITLE
Updater: Download and extract update package programmatically

### ISSUE THREAD

**Issue by zaourzag** [NamelessMC/Nameless#2062]
a way to let nameless updater
download the update into dir x and then update it from there

**Comment by Aberdeener** [comment]
This is how it works already... What do you mean?

**Comment by Derkades** [comment]
They probably mean automatically download and extract files instead of requiring manual upload, similar to how the easy installer works

**Comment by samerton** [comment]
Personally not a fan of automatically updating/installing modules/templates etc

There's a _lot_ of security risk with automatic file management, plus having to cater for different file systems, handling permissions etc

**Comment by Aberdeener** [comment]
Yeah, agreed. Closing for now.
