### ISSUE TITLE
Brute force attack protection

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#2063]
Hello, I noticed nmc doesn't have much protection against brute force attacks on login (at least I think). I suggest that a feature be added to help prevent these attacks. What you could do is only allow x login attempts in x amount of time from a certain IP address, and if all login attempts are used up, they have to wait x amount of time before attempting to log in again.

**Comment by Coookei** [comment]
Looks like the latest version has this which is a v nice feature :D
https://github.com/NamelessMC/Nameless/blob/v2.0.2/modules/Core/pages/login.php#L57

**Comment by Derkades** [comment]
Yes indeed, this issue can be closed
