### ISSUE TITLE
Users are unconfirmed after registering through the API

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2067]
when API validation is enabled, users should automatically be confirmed, right?

**Comment by Aberdeener** [comment]
I tried looking at the code for this, but its too confusing.
Just a thought, even if the *api* is enabled, *api verification* might not be [as its all about verifying they own the email]. Is this report that you made confirmed to have *api verification* enabled?

**Comment by StormyIceLeopard** [comment]
This seems similar to this: https://github.com/NamelessMC/Nameless/issues/2042

**Comment by Aberdeener** [comment]
@Derkades @StormyIceLeopard either of you available to try using the latest commit and see if that works?
