### ISSUE TITLE
MC Server edit page: Data too long for column 'name'

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2068]
Occurs when you type ~~2 or more single quotes~~ an odd number of single quotes. Example: `''mineplex`.

**Comment by PadowYT2** [comment]
Just got to reproduce

https://user-images.githubusercontent.com/71085027/148013544-ad6f9aa9-0439-4847-8755-470bfabf75d5.mp4

**Comment by PadowYT2** [comment]
> Just got to reproduce
> 
>  2022-01-04_08-28-00.mp4

This only works with 3/5/7/9 quotes

**Comment by supercrafter100** [comment]
Though I can't reproduce the same error. Some weird behavior seems to occur when having single quotes in the name. ![gif of the error](https://i.gyazo.com/c4613dd237c90226e10dfc843fd27865.gif)

**Comment by Derkades** [comment]
Looked into this, it has nothing to do with odd numbers of quotes or quotes at all. The `name` field is only a `VARCHAR(20)`. The server name is thrown into `htmlspecialchars` which turns `'''example` into `&#039;&#039;&#039;example`, way too long. I think we can safely bump the length to `VARCHAR(128)`.
