### ISSUE TITLE
Unknown Sender

### ISSUE THREAD

**Issue by Samistine** [NamelessMC/Nameless#207]
When using a smtp relay no sender is added so it ends up being unkown sender.

We need a setFrom parameter.
$mail->setFrom('from@example.com', 'Mailer');

**Comment by samerton** [comment]
setFrom is already in use ([example](https://github.com/NamelessMC/Nameless/blob/master/pages/admin/reset_password.php#L57)), along with just the alternative (From and FromName).
I can't reproduce any unknown sender issues, nor is this an issue I've seen occur in the past. I'd need to do a bit more investigating to see if I can reproduce the issue.

**Comment by Samistine** [comment]
I used phpmailer and it works perfectly by itself but not the way nameless
is using it.

[image: Inline image 1]

**Comment by Samistine** [comment]
![image](https://cloud.githubusercontent.com/assets/7032358/15688621/f256c40e-2748-11e6-80a7-6d1a18def7f0.png)

**Comment by samerton** [comment]
I've only seen this occur once before, I'm not sure if the cause is the exact same but the solution in that situation was ([from this post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-46#post-870147)):

>  This field is shown by clients when your mail is signed by DKIM for another domain
> you need to run your own mail server or use a service like SES or Mandrill for mail sending where you setup DKIM for your own domain.

**Comment by Samistine** [comment]
I am back to using google's smtp server. I believe it was indeed caused by
what you are mentioning. Thanks this issue is closed.

**Comment by Samistine** [comment]
Actually it was caused by SPF
Received-SPF: fail (google.com: domain of noreply@samistine.com does not designate 205.185.112.53 as permitted sender) client-ip=205.185.112.53;

**Comment by samerton** [comment]
Unfortunately SPF isn't something I've ever had to look into before, however [this guide](https://www.x-pose.org/2013/10/22/how-to-designate-an-ip-address-as-permitted-sender/) may be of use.
