### ISSUE TITLE
Update recommended version on namelessmc.com

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2070]
Now that the v2 pre-releases are published to spigotmc.org, I think it is time to update namelessmc.com as well.

Anyone who tries to get support for v1 in Discord is told to download v2, so it can't really be called the "supported" or "recommended" version.

**Comment by TeemoCell** [comment]
Yeah pls xD

**Comment by AToska21** [comment]
This was opened a year ago, is there a reason why it is still not done?

**Comment by PadowYT2** [comment]
This is going to be done when pr13 is going to be released

**Comment by AToska21** [comment]
> This is going to be done when pr13 is going to be released

alright

**Comment by Aberdeener** [comment]
FYI the website downloads page could use a small amount of JS magic and use the new `https://namelessmc.com/api/v2/latestUpdate` endpoint to *automatically* update the version number and download link!

With our plan being to release updates quite often, needing someone with access to the webserver to manually update the page every time seems silly :D
