### ISSUE TITLE
Allow users to delete their account

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2071]
second issue: how do we treat content posted by deleted accounts, delete the content or set the author to a deleted user like discord or reddit?

**Comment by samerton** [comment]
Personally I think the delete button in the StaffCP is all that's needed, from experience allowing users to delete their own account isn't common practice.

This obviously means the user needs to put in a request for the staff to delete the account, which is fully compatible with GDPR (as long as the staff then act on this in good time).

There's an event that gets called when a user gets deleted, which modules can hook into to delete user - see https://github.com/NamelessMC/Nameless/blob/v2/modules/Forum/module.php#L243 for an example

**Comment by Baaasty** [comment]
How about if you make the function optional so that you can add it to the groups as a permission. So every website admin can decide for themselves.
