### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by Sunni05** [NamelessMC/Nameless#2072]
So this is just an example, but still applies, so like you can setup a schedule so if the application has the [Closed] tag, after one hour of no responses, set it to [ThisTag] or whatever.

**Comment by Aberdeener** [comment]
Hi,
Thanks for the idea. Please make an issue here https://github.com/partydragen/Nameless-Forms/issues, as this request is for a third party module.

**Comment by chrlew082** [comment]
?

**Comment by chrlew082** [comment]
I meant like in general, not only that forums module, but other things to, like when a user registers or something, just general events.
