### ISSUE TITLE
More email placeholders

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#2075]
Use them in all aspects of emails.
- [ ] NamelessMC username
- [ ] website name
- [ ] server date
- [ ] server time

![image](https://user-images.githubusercontent.com/10292779/106330311-f909b200-6250-11eb-9751-ad0f2906e143.png)

**Comment by Aberdeener** [comment]
More detail please... "More placeholders" doesnt help much.
What do you want?

**Comment by Derkades** [comment]
I have edited your issue description with a task list, please complete it with any placeholders you think would be useful

**Comment by Aberdeener** [comment]
#2567 Lets modules add custom placeholders to email templates!
