### ISSUE TITLE
Api error 20 when creating report

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2077]
Getting API error 20 ("User creating report does not have a website account") when creating a report using the API. However, the user does in fact have a website account. The plugin's user info command does retrieve user info (using the userInfo API method)

**Comment by chrlew082** [comment]
Maybe try enabling api verification? Then it knows they have an account via stored ID?

**Comment by Vladimir-Urik** [comment]
Hello,
This api endpoint is working fine for me.

[Screenshot](https://i.imgur.com/UftzU86.png)

**Comment by Derkades** [comment]
that explains why it works for you, you put a username for `reporter` but according to [the documentation](https://github.com/NamelessMC/Nameless/wiki/v2-API#createreport-post) it should be the user id

**Comment by Vladimir-Urik** [comment]
This is a documentation error because the code controls the user by username.

```php
        $user_reporting = $api->getDb()->get('users', array('username', '=', Output::getClean($_POST['reporter'])));
        if (!$user_reporting->count()) {
            $api->throwError(20, $api->getLanguage()->get('api', 'you_must_register_to_report'));
        }
```

**Comment by Derkades** [comment]
we likely forgot to update this API method during the API rewrite, since all other API methods use the user ID it makes sense to use the ID for this method as well.

**Comment by Vladimir-Urik** [comment]
> We likely forgot to update this API method during the API rewrite. Since all other API methods use the user ID it makes sense to use the ID for this method as well.
> 
> Also, error 20 can be removed and replaced with error 16 (user not found)

Okey. Fixed according to [documentation](https://github.com/NamelessMC/Nameless/wiki/v2-API#createreport-post) in [Pull request](https://github.com/NamelessMC/Nameless/pull/2104)

**Comment by Derkades** [comment]
Apparently the reported user must also exist so I'll change that one as well
