### ISSUE TITLE
Recaptcha improvements

### ISSUE THREAD

**Issue by Mubeen142** [NamelessMC/Nameless#2078]
I have seen numerous complaints regarding spam in “contact us” forms adding Captcha  on these pages would solve it.

Add compatibility for Recaptcha v3 (current version: v2)

**Comment by chrlew082** [comment]
> I have seen numerous complaints regarding spam in “contact us” forms adding Captcha on these pages would solve it.
> 
> Add compatibility for Recaptcha v3 (current version: v2)

Or just make it so you can only press the contact me button if your logged in.

**Comment by Derkades** [comment]
I have created three new issues: #2079 #2080 #2081
