### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by cmbaron** [NamelessMC/Nameless#208]
I want to run this software in docker container in production.  So. I started working toward that, with the **totally not production ready** scripts at https://github.com/cmbaron/Nameless-docker. If you have docker installed and running the build.sh script will:
- create a mysql env file to persist a new random password
- create a mysql data directory to persist mysql data across containers
- start a new mysql instance, mounting the mysql data directory
- build an image with nameless master preloaded
- start a nameless container exposing the app on port loaclhost:8080 (or your docker-machine ip) 
- List the mysql details to use during installation

You can do the installation steps and zoom right into a fully working setup in no time at all.

Unfortunately, "install" changes the filesystem so the next time I run build.sh I cannot access the instance I configured after the previous run.  The DB is preserved across runs, but I cannot get through the installation procedure successfully again.

For this to work properly in a docker container, the app should be stateless.  The only configuration needed should be the database configuration, which can be extracted from environment variables, everything else should be stored in the DB.

**Comment by samerton** [comment]
Firstly, thanks for this! I've personally not used Docker before, but it looks really useful.

Am I right in saying that external configuration files (such as external database details, for example a Minecraft plugins database) must be stored in the database instead?
Also, would cache files (generated by Nameless) not be permitted, as they'd change the filesystem?

**Comment by thomas15v** [comment]
````Dockerfile
FROM php:5.6-apache

RUN docker-php-source extract \
	&& apt-get update \
	&& apt-get install libmcrypt-dev libldap2-dev nano libpng12-dev libjpeg62-turbo-dev libfreetype6-dev -y \
	&& rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-install pdo pdo_mysql mysqli \
        && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
        && docker-php-ext-install -j$(nproc) gd mcrypt \
	&& a2enmod rewrite \
	&& docker-php-source delete

COPY . /var/www/html/
RUN chmod 777 -R /var/www/html
````

Pretty sure you guys know better than me what is going on here, I copied coded all around until I had something that worked XD.

**Comment by BirkhoffLee** [comment]
I'll take this over! :)

**Comment by rodymol123** [comment]
@samerton I think one general Cache directory should be allowed. I think Nameless currently has lots of different places where we put caches and other files, maybe centralizing those helps?

**Comment by BirkhoffLee** [comment]
It's live! Using php 7.0 and `docker-compose` which is the officially-recommended way to quick deploy containers: https://github.com/BirkhoffLee/NamelessMC-docker

**Comment by BirkhoffLee** [comment]
It's okay if you wanna merge it into your repository. :p

**Comment by BirkhoffLee** [comment]
@samerton You can still store them in files, but please tell me where the files are. Cache files are of course allowed, you can see a Docker container as a VM simply (it's not, actually), it just work like normal servers.

**Comment by samerton** [comment]
@BirkhoffLee 
Fantastic, thanks so much!

All cache files are stored in the **cache** directory and the **cache/templates_c** directory.

**Comment by BirkhoffLee** [comment]
@samerton Alright I'll check it out. I'll follow up on this thread when done.

**Comment by BirkhoffLee** [comment]
@samerton Sorry, I mean the path of "external configuration files" you mentioned about. Is it necessary for cache directories to be accessible to users?

**Comment by thomas15v** [comment]
@BirkhoffLee I don't think that matters really. I would just define that folder as a volume so that if compose recreates the container you don't lose the cache. I don't know how critical the cache is for Nameless, but I could think of some applications that simply don't work anymore if they lost their cache/filestore.

**Comment by BirkhoffLee** [comment]
@thomas15v Yeah I think so too.

BTW I can confirm that https://github.com/BirkhoffLee/NamelessMC-docker is running without any errors.

**Comment by samerton** [comment]
The configuration files are core/config.php, core/email.php, and also some config files in the addons directory. 
These files are changed by Nameless itself, such as when the user inputs their database details within the installer, or whilst changing email configuration settings through the AdminCP.

**Comment by BirkhoffLee** [comment]
Oh this is terrible, they are not centralized. Instead of mounting them individually, I'd rather mount the whole /var/www/html. What do you think?

**Comment by Headhunterzpw** [comment]
@BirkhoffLee No. Some people do host other things on that directory...

**Comment by BirkhoffLee** [comment]
@Headhunterzpw Why would someone host other thing on the /var/www/html directory when it's in Docker container which is only for running a certain application?

**Comment by BirkhoffLee** [comment]
Ummm, @samerton you're not closing this issue?

**Comment by samerton** [comment]
@BirkhoffLee I'll close it now, thanks :)
