### ISSUE TITLE
Add reCAPTCHA to contact form to prevent spam

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2081]
Optional of course. See also #2079

**Comment by partydragen** [comment]
There is already by enable reCAPTCHA

**Comment by Derkades** [comment]
Where is this option located?

**Comment by partydragen** [comment]
Just checked and it require to enable "Enable Google reCAPTCHA on registration?"

Anyways it only support reCAPTCHA not hCAPTCHA

**Comment by Derkades** [comment]
#2116
