### ISSUE TITLE
Many SUGGESTIONS

### ISSUE THREAD

**Issue by MinecraftHDKIll** [NamelessMC/Nameless#2084]
As you know,there is discord link feature on profile.
You should add youtube/twitch link feature to profiles.
In Infraction modules you should add path change for site like /punishments or something.
One more suggest for Infraction is to change Tags when someone is unbanned. When Staff unbanned someone it says "Expired". You should change that to "Unban/Unbanned" With name who unbanned that person.
Make option to remove profile banners from profiles.
Suggestion should have feature to set page to "no link"
Fix issue when some is going to login/register there is black text "Already have an account" and "Register". That should be white. (Theme is DefaultRevamp)
Make option to edit Home page without forums posts.

**Comment by Derkades** [comment]
Please create one issue per bug report or feature request and post infractions issues on the [infractions github repository](https://github.com/samerton/Nameless-Infractions/issues)
