### ISSUE TITLE
Black Text in Login and Register

### ISSUE THREAD

**Issue by MinecraftHDKIll** [NamelessMC/Nameless#2087]
![Screenshot_20210205-212644_Chrome](https://user-images.githubusercontent.com/42026909/107085587-fbdc4800-67f8-11eb-84d1-b83fc2e595a1.jpg)
![Screenshot_20210205-212632_Chrome](https://user-images.githubusercontent.com/42026909/107085594-fda60b80-67f8-11eb-91b2-ebbd0f530b41.jpg)

When you are going to login/register in DefaultRevamp theme,there is black text that should be white.
Fix issue with black text that should be white.

**Comment by PikaMug** [comment]
Imo it should be gray, not white, since it's not interactable.
