### ISSUE TITLE
Suggestion No-Link feature

### ISSUE THREAD

**Issue by MinecraftHDKIll** [NamelessMC/Nameless#2088]
Suggestion should have feature to set page to "no link"

**Comment by Aberdeener** [comment]
Gonna need more information.
I have no idea what you're talking about.
Can you give more detail?

**Comment by StormyIceLeopard** [comment]
Custom Pages already have "no link"
unless you are not regarding Custom Pages

**Comment by MinecraftHDKIll** [comment]
I'm using Suggestions module,not custom pages. In every other modules there is option to set module to no link,because I want it gone from Navbar

**Comment by samerton** [comment]
Can you please request this with the module author, thanks!
