### ISSUE TITLE
Login Problems

### ISSUE THREAD

**Issue by MinecraftHDKIll** [NamelessMC/Nameless#2093]
When someone is registering,if verification is enabled,when they enter their username,email and password they get "Invalid email" message and after 1 minute verification email comes to their email. You should set message if verification is enabled to give them message to check their email for verification.

**Comment by samerton** [comment]
Sorry I don't understand this one - are you saying, when you submit the register form, it says "Invalid email"? Could you please send a screenshot?

**Comment by MinecraftHDKIll** [comment]
Fixed nvm.
