### ISSUE TITLE
Editor center align does not work for images

### ISSUE THREAD

**Issue by papaya1488** [NamelessMC/Nameless#2096]
**Describe the issue**
Hello today i was installing a new Namelessmc 2 0 0 pr9 just totaly new it works fine but if i go to Forum, in normal Forum page, and then i wann make a post its okay but i wan in the post image with is in Center not right or left but in the Edit mode if i click CENTER on the tab is in the edit mode in the CENTER but if i apply the suggestions its not its on left i dont know why

**Expected behaviour**
I except that the image will be in the Middle aka Center if i click on Center not right or left :-D

**Screenshots**
https://ctrlv.cz/kMSc

PS: Sorry for my bad ENG...

**Comment by TeemoCell** [comment]
Properly fix #2629

**Comment by Aberdeener** [comment]
This was fixed when we swapped to TinyMCE recently!
