### ISSUE TITLE
New filter parameter for listUsers API: discord_linked

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2097]
required for https://github.com/NamelessMC/Nameless-Plugin/issues/116 (or at least to do it efficiently)

**Comment by Aberdeener** [comment]
I used the same behavior as the other filters. Let me know if this is right, or if you wanted opposite effect.

**Comment by Derkades** [comment]
discord_linked=true
Only show linked users
discord_linked=false
Only show not linked users
<nothing>
Show all users

**Comment by Derkades** [comment]
You said you used the same behavior as other filters, if you reopened this because the discord filter behavior is incorrect, that also means the other filters are wrong since they should behave the way I described above as well

**Comment by Aberdeener** [comment]
Thanks for the clarity, fixed
