### ISSUE TITLE
Help Text Line

### ISSUE THREAD

**Issue by MinecraftHDKIll** [NamelessMC/Nameless#2098]
Help Text line at DefaultRevamp theme becomes black. (Forms module)
![image](https://user-images.githubusercontent.com/42026909/107552734-2f8de800-6bd4-11eb-8c6d-8c70bd98ae63.png)

**Comment by BaxAndrei** [comment]
I think this is related to https://github.com/partydragen/Nameless-Forms. Might be caused by CSS.

**Comment by MinecraftHDKIll** [comment]
> I think this is related to https://github.com/partydragen/Nameless-Forms. Might be caused by CSS.

Im using namelessmc,can't do anything about that

**Comment by BaxAndrei** [comment]
Can you please provide me your forum url?

**Comment by MinecraftHDKIll** [comment]
> Can you please provide me your forum url?

Any specified reason for that?

**Comment by BaxAndrei** [comment]
As you can see, you have not received any other answer so far. I wanted the address to check and maybe I offered you a solution.

**Comment by MinecraftHDKIll** [comment]
If you are interested in that,there is website lightningnetwork.gq but i removed help text line

**Comment by BaxAndrei** [comment]
Oh, ok. You can try to fix it with custom css style,

**Comment by Aberdeener** [comment]
Closing as this is irrelevant to this repo

**Comment by Derkades** [comment]
Please open an issue in https://github.com/partydragen/Nameless-Forms
