### ISSUE TITLE
Install File Not Found

### ISSUE THREAD

**Issue by SpencerHiltbrand** [NamelessMC/Nameless#210]
My server is returning an error that the file Install.php was not found. :(

**Comment by SpencerHiltbrand** [comment]
Now, it finds it but the Configuration is blank except for the menu at the top.

**Comment by samerton** [comment]
[This] should help you out, but make sure the install.php file is within the pages folder or else it won't be able to find the correct files.

**Comment by samerton** [comment]
I'm going to close this as it's down to server configuration, if you're still having issues feel free to re-open or send me a private message on [Spigot](https://www.spigotmc.org/members/samerton.10676/) and I can set up Nameless for you.
