### ISSUE TITLE
Allow reporting user that does not have an account (by username or UUID)

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2106]

**Comment by samerton** [comment]
This used to be possible, I'm assuming the API rework in pre-8 lost this feature

Old code for reference: https://github.com/NamelessMC/Nameless/blob/v2.0.0-pr7/modules/Core/pages/api/v2/index.php#L635

**Comment by Derkades** [comment]
Weirdly enough report was still by username and the documentation said the user didn't have to be registered, but the code checked for a user with that username

**Comment by Aberdeener** [comment]
Thanks!

**Comment by Derkades** [comment]
uuhh.. are you sure about this? Doesn't this just create a report with user id 0 when the specified user id doesn't exist?

**Comment by Aberdeener** [comment]
Yeah, that was the old behaviour

**Comment by Aberdeener** [comment]
Why was it reopened?

**Comment by Derkades** [comment]
Because the issue is not fixed, the api does not allow reporting an unregistered user by username or UUID.

Allowing the user id to be set to an invalid value makes no sense and is not a valid solution, in this case there is no way to know who the report is for
