### ISSUE TITLE
Add forum leveling

### ISSUE THREAD

**Issue by Vladimir-Urik** [NamelessMC/Nameless#2107]
Please add forum leveling

Examples screenshots:
[screen#1](https://imgur.com/SIUBZsv)
[screen#2](https://imgur.com/Akoz18M)
[screen#3](https://imgur.com/FXWTCYK)
[screen#4](https://imgur.com/p2xn0As)

**Comment by Derkades** [comment]
Similar to https://github.com/NamelessMC/Nameless/issues/2094

**Comment by samerton** [comment]
Possibly related to https://github.com/NamelessMC/Nameless/issues/708

**Comment by Derkades** [comment]
Also #173
