### ISSUE TITLE
Error on uploading custom avatars and banners with craftingstore module.

### ISSUE THREAD

**Issue by Nuckerr** [NamelessMC/Nameless#2110]
**Describe the issue**
When I upload a custom banner or module, after pressing the upload button I am sent to an error page with this error
```
Fatal error: Uncaught Exception: Unable to create cache directory cache/ in /var/www/Nameless/core/classes/Cache.php:272
Stack trace: 
#0 /var/www/Nameless/core/classes/Cache.php(233): Cache->_checkCacheDir() 
#1 /var/www/Nameless/core/classes/Cache.php(219): Cache->getCacheDir() 
#2 /var/www/Nameless/core/classes/Cache.php(77): Cache->_loadCache() 
#3 /var/www/Nameless/modules/CraftingStore/src/Common/Retriever/CachedSettingRetriever.php(24): Cache->isCached() 
#4 /var/www/Nameless/modules/CraftingStore/module.php(66): CachedSettingRetriever->retrieve() 
#5 /var/www/Nameless/modules/CraftingStore/init.php(45): CraftingStoreModule->__construct() 
#6 /var/www/Nameless/core/init.php(494): require('/var/www/Namele...') 
#7 /var/www/Nameless/core/includes/image_upload.php(20): require('/var/www/Namele...') 
#8 {main} thrown in /var/www/Nameless/core/classes/Cache.php on line 272
```

Warning: file_put_contents(../../cache/logs/other-log.log): failed to open stream: No such file or directory in /var/www/Nameless/core/classes/ErrorHandler.php on line 70

Fatal error: require_once(): Failed opening required '../../error.php' (include_path='.:/usr/share/php') in /var/www/Nameless/core/classes/ErrorHandler.php on line 53`

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure you have the craftingstore module enabled
2. enable custom avatars or banners
3. Go to user settings and at the bottem, upload a custom avatar or go to your profile and press the picture icon on the banner
4. Upload a custom image and press Submit
5. See error

**Expected behaviour**
That the image is uploaded and is set as the avatar/banner

**Screenshots**
http://i.nucker.me/jkrCD.png

**NamelessMC version (from AdminCP -> Overview)**
Running NamelessMC version 2.0.0-pr9

**Additional information**
I was told in your discord server to submit an issue here instead of the craftingtore github

**Comment by samerton** [comment]
This is a CraftingStore error, can you please raise it with them

**Comment by Nuckerr** [comment]
I got this reply from craftingstore http://i.nucker.me/hEWJD.png

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/108215409-9873e380-7131-11eb-9940-556246f5e61e.png)
