### ISSUE TITLE
No paginate.php

### ISSUE THREAD

**Issue by j3r00** [NamelessMC/Nameless#2111]
**Describe the issue**
There is no paginate.php file

**To Reproduce**
Steps to reproduce the behaviour:
1. I go on https://YOUR-DOMAIN.lolz/profile/YOUR-USERNAME/

**Expected behaviour**
That I can see a profilepage of other user...

**Screenshots**
![image](https://user-images.githubusercontent.com/45767339/108064092-78bebb80-705c-11eb-9cc0-0e5bcb96a4f2.png)

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr9

**Additional information**
I don't know why this is happening.. the file does't exist..

**Comment by Derkades** [comment]
Are you sure you are running pr9? This bug was fixed in ed0dc04c5094499f1668960ef9f3c41db70174f6 which I believe was before the release of pr9

**Comment by j3r00** [comment]
Sure, I downloaded this version from this link: https://github.com/NamelessMC/Nameless/archive/v2.0.0-pr9.tar.gz

Or is this not the latest version?

**Comment by Derkades** [comment]
Could you send the contents of your modules/Core/pages/profile.php file using a paste site

**Comment by j3r00** [comment]
That directory is not existing.. I think that is a problem with the rewrite rule... but I'm not sure

**Comment by Derkades** [comment]
to clarify, don't go to this using a web browser but using a file manager

**Comment by j3r00** [comment]
![image](https://user-images.githubusercontent.com/45767339/108065940-fbe11100-705e-11eb-9dda-fdb14175c4d4.png)

**Comment by j3r00** [comment]
nvm wrong file 

https://pastebin.com/MMCMjcFe

**Comment by Derkades** [comment]
Can you take a screenshot of your panel (yoursite.com/panel)

**Comment by j3r00** [comment]
![image](https://user-images.githubusercontent.com/45767339/108069301-7f046600-7063-11eb-9bc4-8bb9ec59e69f.png)

**Comment by j3r00** [comment]
For some reasons I'm getting now a 404 if I go to /profile/MYUSERNAME/

Because: 
![image](https://user-images.githubusercontent.com/45767339/108069578-cf7bc380-7063-11eb-824b-5a1fee203471.png)

**Comment by Derkades** [comment]
Yeah it's definitely pr9 but for some reason your modules/Core/pages/profile.php is old (from pr7 I think?)

> For some reasons I'm getting now a 404 if I go to /profile/MYUSERNAME/
> 
> Because:
> ![image](https://user-images.githubusercontent.com/45767339/108069578-cf7bc380-7063-11eb-824b-5a1fee203471.png)

check that path is set correctly in core/config.php, it should be blank

**Comment by j3r00** [comment]
Hmmmmm 
![image](https://user-images.githubusercontent.com/45767339/108069788-0b168d80-7064-11eb-8143-6a09d688b629.png)

**Comment by Derkades** [comment]
Could it be possible that you have 2 sites installed?

**Comment by j3r00** [comment]
You mean, because there are functions from pr7 ?

**Comment by j3r00** [comment]
I don't know.... I downloaded it and placed into the normal html folder..

**Comment by Derkades** [comment]
Yes, when I download pr9 using the link you sent above I see the correct file, so not sure what you did. If this is a fresh website I'd recommend reinstalling, who knows what else went wrong.

**Comment by j3r00** [comment]
Ok.. sure

**Comment by j3r00** [comment]
After a fresh install.... again.. this damn url.. do you think it would work if I deactivate Friendly URLs ?

**Comment by j3r00** [comment]
I even changed the amin directory 

![image](https://user-images.githubusercontent.com/45767339/108075124-487e1980-706a-11eb-8a15-8e298e0bb657.png)

![image](https://user-images.githubusercontent.com/45767339/108075169-56cc3580-706a-11eb-9cff-2e06b79ac973.png)

**Comment by j3r00** [comment]
lol... I deactivated Friendly URLs... and I see my profile page...

**Comment by j3r00** [comment]
I think I know now what the problem was...

**Comment by j3r00** [comment]
It was the TechniTheme I used....

**Comment by Derkades** [comment]
I'll keep that in mind if someone else has this issue in the future

**Comment by j3r00** [comment]
Sure.. but anyways thanks for the help
