### ISSUE TITLE
groupInfo api method does not exist

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2118]

**Comment by Aberdeener** [comment]
<img width="534" alt="Screen Shot 2021-02-21 at 4 03 30 PM" src="https://user-images.githubusercontent.com/26070412/108643200-58c53880-745e-11eb-8c81-e6fc69d03c94.png">
<img width="1450" alt="Screen Shot 2021-02-21 at 4 03 38 PM" src="https://user-images.githubusercontent.com/26070412/108643203-5e228300-745e-11eb-8cbc-4ddb9d547454.png">

Seems to be there for me 🤔

**Comment by Derkades** [comment]
Sorry I forgot to close, some person reported this issue but I could reproduce either
