### ISSUE TITLE
Move phpmailer switch

### ISSUE THREAD

**Issue by Mubeen142** [NamelessMC/Nameless#2119]
I think we should move the phpmailer switch down to where the smtp inputs are. It currently gives the vibe that the switch is meant for the input below

https://cdn.resourcemc.net/zAsa7/XIGIWaVi28.jpeg

**Comment by StormyIceLeopard** [comment]
I actually agree with this.

**Comment by Aberdeener** [comment]
Thanks for the suggestion, this was something I always thought about but never remembered to do.
