### ISSUE TITLE
Make announcements?

### ISSUE THREAD

**Issue by xBreaksx** [NamelessMC/Nameless#213]
Hi, can you add something like announcements using something like the picture below that admins can address through AdminCP? These announcements could possibly be configured so admins can toggle whether they are closeable announcements, or choose where they can be seen. If you can, that would be awesome! Thanks!

![announcement](https://cloud.githubusercontent.com/assets/11200616/15916141/c3e0b9ee-2dac-11e6-841c-cf55ecdedc64.PNG)

**Comment by IonLogic** [comment]
Would these be per user, per group or just global announcements?

**Comment by samerton** [comment]
Added in 709584f6edab285cf5fbaaad4718a5f75e8396fc
