### ISSUE TITLE
install file not found

### ISSUE THREAD

**Issue by Ggamer55** [NamelessMC/Nameless#215]
the install file of the namelessmc don`t found :c
PD: yes the install.php is on the page directory

**Comment by Schwertspize** [comment]
Check your htaccess and try to remove the first line. 

And **use Google and read the 100 other issues**

**Comment by samerton** [comment]
[This](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) should help you out.

If that doesn't work, as @Schwertspize says, the top line of the .htaccess file (in the web root directory) may cause issues.

**Comment by Ggamer55** [comment]
same, in the root of the webserver? mmm if in apache the directory is /var/www and i install in this directory which can be
sorry for my bad english i dont speak english

**Comment by Ggamer55** [comment]
PD: i use apache 2 with ubuntu 15.04

**Comment by Schwertspize** [comment]
Install it instead of /var/www so /var/www contains the individual files lime cache and so on :)

**Comment by Ggamer55** [comment]
i dont understand

**Comment by samerton** [comment]
If your files are already in /var/www, try following every step in [this guide](http://askubuntu.com/a/48363) carefully.

**Comment by samerton** [comment]
I'm going to close this as I believe it's a server configuration issue, if you're still having issues feel free to re-open or you can send me a private message over on [Spigot](https://www.spigotmc.org/members/samerton.10676/) and I can set it up for you.
