### ISSUE TITLE
Getting stuck at installation

### ISSUE THREAD

**Issue by TheHtaccess** [NamelessMC/Nameless#216]
Whenever I try to install it, it always gets stuck at "The installer is now attempting to create the necessary tables in the database." 
Please help.

**Comment by samerton** [comment]
There's a problem with the latest zip download, try the latest release ([version 1.0.9](https://github.com/NamelessMC/Nameless/releases/tag/v1.0.9)).

**Comment by jesseke55** [comment]
And with the 404`s that you get try then these instructions: https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-152#post-1649790

**Comment by samerton** [comment]
Should be fixed in e6c51a00c1286817f1c806233d6cb43592e75474, will be included in 1.0.10.
