### ISSUE TITLE
Multiple Groups/Sub Groups

### ISSUE THREAD

**Issue by ConnorLinfoot** [NamelessMC/Nameless#217]
Starting to setup and move onto Nameless and something that would be nice to have is multiple groups/sub groups.

If this has already been done and I'm missing it let me know :P

**Comment by HappyHarm** [comment]
Don't know what you mean exactly but you can have a look under Users & Groups and then Groups
![](http://image.prntscr.com/image/5d81a3e31d284d8abcef3eda1090709f.png)

**Comment by ConnorLinfoot** [comment]
I've got that but I want multiple groups per user. So I can give a user Admin + Owner.

**Comment by HappyHarm** [comment]
I'm afraid that's not possible (yet) :S

**Comment by aycgit** [comment]
Wouldnt it be better to just give the highest rank of both and use that?

**Comment by BlackBeltPanda** [comment]
Would love to see this. =)
Since I run a network with multiple servers, each server having it's own groups, it'd be great to display all the groups a user is part of on the website.

**Comment by samerton** [comment]
Added in 7289744c7ba1aebae3c334b5217554e77aaabd39 (v2)
