### ISSUE TITLE
Discord/MC server disappear off banner randomly then reappear

### ISSUE THREAD

**Issue by frankfalkenburry** [NamelessMC/Nameless#2178]
**Describe the issue**
Discord server/MC server will disappear off the banner randomly then reappear after some time. (Usually the discord, most the time they do show its completely random when they disappear)

**To Reproduce**
Random after refresh

**Screenshots**
https://i.imgur.com/Opy5ubE.png (disappeared on the left)

**NamelessMC version (from AdminCP -> Overview)**
v2.0.0-pr9

**Additional info**
Unsure if its my host or a namelessmc bug. Using Contabo VPS

**Comment by Derkades** [comment]
Have you tried to reproduce on the DefaultRevamp template?

**Comment by samerton** [comment]
Discord and Minecraft statuses in the banner are Cesium features, please can you contact the template author for support
