### ISSUE TITLE
Accessing StaffCP after v2 easy install

### ISSUE THREAD

**Issue by timurko-uwu** [NamelessMC/Nameless#2180]
Hello, i get this error when accessing StaffCP after succesful install:
```
Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column '2021-02-19 10:23:01' in 'where clause' in /var/www/html/core/classes/DB.php:52
Stack trace:
#0 /var/www/html/core/classes/DB.php(52): PDOStatement->execute()
#1 /var/www/html/core/classes/DB.php(267): DB->query()
#2 /var/www/html/core/classes/Queries.php(34): DB->orderWhere()
#3 /var/www/html/modules/Forum/module.php(172): Queries->orderWhere()
#4 /var/www/html/core/classes/Module.php(62): Forum_Module->onPageLoad()
#5 /var/www/html/modules/Core/pages/panel/index.php(20): Module::loadPage()
#6 /var/www/html/index.php(86): require('/var/www/html/m...')
#7 {main}
```

I use MySQL database on other server

**Comment by partydragen** [comment]
That does not make sense and the code looks fine
$latest_posts = $queries->orderWhere('posts', 'post_date > "' . date('Y-m-d G:i:s', strtotime("-1 week")) . '"', 'post_date', 'ASC');

and its been unchanged for a VERY long time

**Comment by timurko-uwu** [comment]
like, i know, but i just reinstalled it, and it shows it again 
![image](https://user-images.githubusercontent.com/59578738/109431847-cba75400-7a08-11eb-92ef-11452b6fb4f1.png) 
and it only shows after login to StaffCP

**Comment by timurko-uwu** [comment]
Just made MySQL database locally, and it is working
