### ISSUE TITLE
Trigger discord role sync after linking

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2187]
After a user links their discord account to the website, use the `/roleChange` bot endpoint to send the website user's current roles to discord

**Comment by Derkades** [comment]
If anyone wants to test this, apply this change to your site:
https://github.com/NamelessMC/Nameless/pull/2203/commits/11a1623c12a5003ef7609af7f3d566d37975e92e#diff-1c8271a6dc98f7181bdc159e28b523713f0fbaae7ff584e6d7f69cdbb349aa31R41-R60

**Comment by Derkades** [comment]
Possible bug: the bot also sends a list of roles to the website as soon as the user links their account. I assume this means that the website will remove roles from users when it shouldn't?

**Comment by PikaMug** [comment]
As mentioned in #2203 I'm unable to test this (am using NamelessHosting), but in their environment without this change, the user completing verification still retains their website role. Only the Discord role is unchanged, which this attempts to fix.

If you're saying website role removal happens _as a result of this change_, then perhaps a toggle switch is necessary for whether to prioritize `Discord -> Site` versus `Site -> Discord`?

**Comment by Derkades** [comment]
I think the solution is for the bot to always send the role list *after* the initial web->discord sync

**Comment by Derkades** [comment]
The bot has protection against sync loops so it's fine for the website to send a list of groups as part of the /verifyDiscord endpoint (the same way it does when changing a user's groups in StaffCP)
