### ISSUE TITLE
Automatically set user language

### ISSUE THREAD

**Issue by zJerino** [NamelessMC/Nameless#2196]
I was thinking that we could implement a dynamic language system in NamelessMC, let me explain:
When the user (Anonymous) enters the page, the language that is selected as the default in their browser is identified.
and when the user who is registered enters the page, the language that she has selected is selected, in case she has done so

🤔 I think I know how to do it

**Comment by zJerino** [comment]
My English is very bad, excuse me

**Comment by Aberdeener** [comment]
Your English is fine!

Can you share your idea on how to get their language?

**Comment by Derkades** [comment]
Browsers send a preferred language as part of HTTP requests, many sites use this

**Comment by zJerino** [comment]
> Browsers send a preferred language as part of HTTP requests, many sites use this.
> 
> Examples: https://stackoverflow.com/questions/3770513/detect-browser-language-in-php

yes

**Comment by Aberdeener** [comment]
Alright, this is super easy to add by using `Locale::acceptFromHttp($_SERVER['HTTP_ACCEPT_LANGUAGE'])`, however we should decide on the rules of when this automatic language should apply.

Should we add a language selector to the footer of all sites for guests? This would override the automatic language if they've selected one.

What do you think?
