### ISSUE TITLE
Issues New Install Error With Admin Register

### ISSUE THREAD

**Issue by dexstar007** [NamelessMC/Nameless#22]
Hello, I have a issues using this script at the install point when i will create the Admin User put all the details and when i press to continue appear this error:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

It´s a New DB and appear to being doing the register twice then. I can't continue the install.

here is a img: 
![error](https://cloud.githubusercontent.com/assets/3060470/10891179/0b3c8c66-8162-11e5-8ce9-b8f4a12e340a.png)

Thx for the help and the awsome script :+1:

**Comment by samerton** [comment]
You say it's a new DB; have you tried emptying out the database again and re-installing?

**Comment by dexstar007** [comment]
yes already made that and the problem still continues

**Comment by samerton** [comment]
Unfortunately I can't see any way this could occur. If anything this would be down to the groups, however they're only inputted once.

As a precaution I've added a check which will prevent this from happening in 2c12e5bfc9a5da0f8df5197cdecc7abf382a67d6
