### ISSUE TITLE
Options for heads with helmets

### ISSUE THREAD

**Issue by ConnorLinfoot** [NamelessMC/Nameless#220]
I personally hate that heads dont show skins with helmets, could add an option for this to be switched?

**Comment by HappyHarm** [comment]
I think you can change that yourself by changing the links from 311 & 314 https://github.com/NamelessMC/Nameless/blob/master/pages/profile.php to something like http://cravatar.eu/helmavatar/<nickname|uuid>

**Comment by HappyHarm** [comment]
Nvm, seeing much more cravatar links for the user profile picture. Would be a lot of work to edit 'em all.

**Comment by samerton** [comment]
This was added back in 1.0.11 (commit 90b49e7d0a89bf77f7f89ecd026f36bad67d83ae)
