### ISSUE TITLE
"Always on Top" Announcements

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#2201]
If you have multiple announcements you might want to be able to control the order in which they appear.
And let's say you created some announcements and you are needing to create another one and you want the one you are creating above all other announcements. Be the first listed.
I can think of a couple of ways this can be implemented:

1. Sticky Announcements
     - Similar to how there are Sticky Forums. Make an announcement sticky. Issues can arise if you have a very specific order.
2. Order Priority
     - Use integers to control the order, the higher/lower the number the higher in the list it shows. This works well but not very convenient for the user as numbers can be a little tricky to move things around.
3. Click and Drag
     - Similar to how the StaffCP -> Groups page has that drag button to move the groups around, this can be used to easily determine the order of announcements. This is probably the best option for the end-user but also probably the hardest to implement for the developer.

**Comment by Aberdeener** [comment]
Great idea, thanks as always. 
I'll get to this when I can *tm*

**Comment by Derkades** [comment]
Related: #1547

**Comment by Aberdeener** [comment]
Replacing with #2272, which was added.
