### ISSUE TITLE
Forum Post Stats do not get updates upon Deletion

### ISSUE THREAD

**Issue by JustJP2K** [NamelessMC/Nameless#2202]
If you create a forum post and users comment on it it will change the post count on the thread as it should.

However once players delete their comment or it gets deleted for other reasons the post count will not go down but stay the same.

**Comment by JustJP2K** [comment]
Sorry, Duplicate. Just noticed i posted this before :P

**Comment by Derkades** [comment]
for reference, #2181

**Comment by JustJP2K** [comment]
> 
> 
> for reference, duplicate of #2181

Yes but you also closed the other issue? why?

**Comment by Derkades** [comment]
I did not, the other issue is still open

**Comment by JustJP2K** [comment]
oh yeah. im blind. sorry
