### ISSUE TITLE
StaffCP and Forums use 2 different editors

### ISSUE THREAD

**Issue by JustJP2K** [NamelessMC/Nameless#2204]
Why does the Forum StaffCP use a different editor than the actual Forums?

Its a pain setting up placeholders when they are using 2 different editors so it looks completely wrong. 
Not only does the font size not match up, the default color also doesn't match, and same goes for the font.

Is there a reason for this? Could the StaffCP please get the same editor as the Forums?

**Comment by Derkades** [comment]
please see https://github.com/NamelessMC/Nameless/discussions/1904

**Comment by JustJP2K** [comment]
but im not asking what editor nameless uses, since i know that. but why are the editors different from the staffcp and the actual forums?

**Comment by Derkades** [comment]
the linked discussion is about changing editors (possibly to the same editor for both)

**Comment by samerton** [comment]
I agree that the placeholder editor in the StaffCP -> Forum tab should use the same as the frontend, I'll reopen this as something to be changed.

Any other editors in the StaffCP, such as the custom page editor, will continue to use the different editor.

**Comment by Derkades** [comment]
Panel now uses TinyMCE
