### ISSUE TITLE
Users can preview hidden posts in forums by using search

### ISSUE THREAD

**Issue by JustJP2K** [NamelessMC/Nameless#2209]
Users can view sensitive information from hidden posts in the forums by simply searching for it in the searchbar.

It will give them a title and the first few lines of the post containing information that should be not be viewable. 

This is a major issue, could we please get a patch for this?

**Comment by Aberdeener** [comment]
Can you please provide screenshots of all relevent forum + parent category permission pages, as well as a screenshot of the search screen and highlight the options they should not be able to see?

**Comment by JustJP2K** [comment]
Searched for Ban Appeal. They shouldnt get any results as the title and the preview of the thread shows personal information and should be hidden.
![image](https://user-images.githubusercontent.com/74447960/111291689-bb69b880-8647-11eb-8792-4d5d3641fc9c.png)
Category Permissions: 
![image](https://user-images.githubusercontent.com/74447960/111292105-22876d00-8648-11eb-9686-4ed705d90748.png)

**Comment by JustJP2K** [comment]
This is just an example but every forum has this issue even when setting "view other users topics" to false, that users can simply search for it and will find information regarding those threads.

**Comment by JustJP2K** [comment]
Also it gets displayed in the latest posts module, which is an issue. 
![image](https://user-images.githubusercontent.com/74447960/111293381-7fcfee00-8649-11eb-9df8-836ba23a95f3.png)

**Comment by JustJP2K** [comment]
Another problem i found is it also updates the post counter of the forum. meaning players can easily figure out, for example if you have a bug reports, or staff applications forum, how many applicants or how many bugs etc there are.

**Comment by samerton** [comment]
Looks like search only takes the "view" permission into account, and not "view other topics" so this will need fixing

I can't reproduce the issue with the latest posts widget, that's working as it should on my end and the query all seems correct - could you please provide more information on your group setup for this one?

Post/topic counts showing deleted posts/topics and those in forums which the logged in user can't view is a known issue but it's a lower priority for the time being, since it doesn't lead to any hidden topics being viewed for example

**Comment by JustJP2K** [comment]
![image](https://user-images.githubusercontent.com/74447960/111311904-09d68180-865f-11eb-9d28-34af004a70bc.png)
These are the only permissions the users have

**Comment by JustJP2K** [comment]
i do not know what you mean with other information on the group setup.
could you explain more please.. sorry..

**Comment by samerton** [comment]
No problem @JustJP2K, could you please show me which groups the users are in (all of them if they are in multiple groups), and also the permissions for the forum which should not be showing in the latest posts widget

**Comment by JustJP2K** [comment]
that would be the member group. which is the one you see the permissions of above. 
and i thought i send the permissions for the forum? the screenshot with the viewing permission? sorry.. i have no clue what you mean with that

**Comment by samerton** [comment]
I've tested with those exact permissions and it works fine for me. Are you using the latest release, pre-release 9?

**Comment by JustJP2K** [comment]
yes

**Comment by JustJP2K** [comment]
oh wait. i might have viewed the widget with an admin account.

**Comment by JustJP2K** [comment]
Yeah, the widget works fine. that was on me. i forgot i was on an admin account when viewing it
