### ISSUE TITLE
User delete their own account

### ISSUE THREAD

**Issue by Baaasty** [NamelessMC/Nameless#2216]
I think it would be good if you could delete your own account as a user.
Because there are users who no longer want that the website admin have their personal data.

In addition, if you register with the Minecraft plugin and enter a wrong email, you won't get the verification email and you have to ask an admin first, who then manually deletes his account. So such a function should also be included in the Nameless Java API.

~ Baaasty • Bastian M.

**Comment by Derkades** [comment]
See discussion in https://github.com/NamelessMC/Nameless/issues/2071
