### ISSUE TITLE
Pre-Install Class not found issue

### ISSUE THREAD

**Issue by puttydotexe** [NamelessMC/Nameless#2219]
**Describe the issue**
On fresh copy of NamelessMC (Post Install), error that classes can not be found.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download repo as current,
2. Install to webserver,
3. See error

**Expected behaviour**
Installation page,

**Screenshots**
https://gyazo.com/ffa6fe387d19466d12ab102c5551806d

**NamelessMC version (from AdminCP -> Overview)**
Repo current

**Additional information**
Error can be fixed by including the classes it fails to find, obviously this isn't the required fix.

**Comment by puttydotexe** [comment]
I tried reverting the commit to see if it was a recent thing and it seems that the error ocurs only after [5a6e1528cb6a5fdc2788d6e28ac4d327c269ee88](https://github.com/NamelessMC/Nameless/tree/5fd51148f1bf6e7e40785e703ac986bc257f7c2c).

**Comment by puttydotexe** [comment]
Reverting the following classes back to any previous commit from [5a6e1528cb6a5fdc2788d6e28ac4d327c269ee88.](https://github.com/NamelessMC/Nameless/tree/5fd51148f1bf6e7e40785e703ac986bc257f7c2c), fixes the issue until this issue is fixed.

/core/init.php
/core/classes/ErrorHandler.php

init.php only requires the registering of error and exception lines to be changed and ErrorHandler.php is where the issue lays, to my knowledge.

**Comment by Aberdeener** [comment]
Hi, thanks for the report.
This confuses a bit as I am running the exact same code locally with no
issues.

- does this error happen on every single page you visit, or only when you
preform a specific action?
- can you look in /cache/logs/ and attach links to pastebins of each of the
error logs there?

And yes you're right about those files :)
The confusing part is that the error handler class shouldn't be registered
to be used as the error handler until *after* the other classes (Output,
User, etc) are loaded.

**Comment by Derkades** [comment]
Looks like it's a php 8 issue, I reset both my sites and the php 7.4 site showed the installer while the php 8 site displayed the error:
```
Fatal error: Uncaught Error: Class "Output" not found in /data/core/classes/ErrorHandler.php:90 Stack trace: #0 /data/core/classes/ErrorHandler.php(70): ErrorHandler::parseFile(Array, 17) #1 /data/core/classes/ErrorHandler.php(39): ErrorHandler::parseFrame(Object(TypeError), '/data/core/init...', 17) #2 [internal function]: ErrorHandler::catchException(Object(TypeError)) #3 {main} thrown in /data/core/classes/ErrorHandler.php on line 90
```

**Comment by puttydotexe** [comment]
Awnsers for Aberdeener

- I would assume every page, but due to the fact I can't access the install page, I wouldn't know.
- https://pastebin.com/S5ZmNStj
- It exists, I've checked.
- It's before the install, so pre install. That's my bad.

As Derkades said, installing on PHP 7.4 provides the correct behaviour. I'm not sure if Nameless is designed to be PHP 8 compatible but everything so far has ran on PHP 8 fine so far. Not sure if this is something you would want to be taking time to fix rather than work on new features however I'm sure when the next release of Nameless drops, it'll become an issue for many users that are already on PHP 8 and lack the knowledge/are unable to downgrade.

**Comment by Aberdeener** [comment]
Thanks for the report. Stupid mistake on my end - weird how PHP 7.4 didnt care about that.
