### ISSUE TITLE
Third party cookies are set before user consent

### ISSUE THREAD

**Issue by kallemarc** [NamelessMC/Nameless#2224]
The cookie banner in the latest version is not conform The user must actively agree to the cookie use before he can use the site.

Therefore, it would make sense if a user the first time uses the site must first confirm that he agrees to the cookie use, and then the page reloads and there all functions are usable.

Der Cookie Banner in der neuesten Version ist nicht Konform Der User muss der Cookie Nutzung aktiv zustimmen bevor er die Seite nutzen kann.

Daher wäre es Sinnvoll wenn ein User das erstemal die Seite nutzt erst bestätigen muss das er mit der Cookie  Nutzung einverstanden ist, und sich die Seite dann  neu lädt und dort dann alle Funktionen nutzbar sind.

**Comment by samerton** [comment]
Which cookies are you referring to as being non-compliant?

With the PHP session ID cookie, I'm not sure there's anything we can do due to the nature of PHP.
I don't believe it's considered to be an issue though - although if someone knows more on this than I do please do let me know.

The other cookies Nameless sets are compliant - no cookies are stored unless the user has consented to them.

Third party cookies are another question, for example Google Analytics if you've added that to your site. In that case, we could maybe offer easy integration with Cookiebot which can cover these cookies.

**Comment by Derkades** [comment]
As far as I know the cookie banner can be removed entirely (or disabled by default). NamelessMC only sets functional cookies (like the PHP session id).

> To comply [...] you must: [...] Receive users’ consent before you use any cookies **except strictly necessary cookies**.

> Strictly necessary cookies — These cookies are essential for you to browse the website and use its features, such as accessing secure areas of the site. Cookies that allow web shops to hold your items in your cart while you are shopping online are an example of strictly necessary cookies. These cookies will generally be first-party session cookies. While **it is not required to obtain consent for these cookies**, what they do and why they are necessary should be explained to the user.

https://gdpr.eu/cookies/

**Comment by kallemarc** [comment]
Integration with Cookiebot would be great, otherwise Funkstionen would have to be removed from NamelessMC.

**Comment by samerton** [comment]
Which functions are you referring to, could you please share the cookie names you have noticed?

There should be no cookies other than PHPSESSID created by Nameless.

**Comment by kallemarc** [comment]
__cfduid | .discord.com
-- | --
(NamelessMC Integration)

__cfduid | .discordapp.com
-- | --
(NamelessMC Integration)

__cfduid | .surgeplay.com 
-- | --
(NamelessMC Integration) (Avatar)

lang | cdn.syndication.twimg.com
-- | --
(NamelessMC Integration)

YouTube cookie by inserting a link in the editor, the video is embedded and sets a cookie when opened.

**Comment by Derkades** [comment]
Information about __cfduid: https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies

**Comment by kallemarc** [comment]
If I turn off Discord in StaffCP, the cookie is not set.
Discord itself uses Cloudflare.

Cookies are set that the user has not agreed to.

I would have to disable almost all the features that NameLessMC offers so that it would be compliant.
But in the state unfortunately not.

That's right with Twitter, I just checked it again...

Discord and the avatar service but unfortunately not.

In Germany, the risk of receiving a warning is unfortunately very high.

**Comment by MViper** [comment]
The user thinks that we have a worse cookie law in Germany and therefore have to obtain consent for each cookie.
https://www.e-recht24.de/artikel/datenschutz/8451-hinweispflicht-fuer-cookies.html
https://cookieinformation.com/de/wie-lautet-das-eu-cookie-gesetz/

**Comment by Fjuro** [comment]
Cloudflare has removed the `__cfuid` cookie so this is should be solved, shouldn't it?

**Comment by Derkades** [comment]
yes I think so, the `lang` cookie set by twitter is purely functional so doesn't require consent

**Comment by samerton** [comment]
I'll keep this open, Cookiebot integration will be a nice feature to offer

**Comment by samerton** [comment]
06b97b7b8624db46f068461ec7a44500f7c8cc4c

New functionality added with the new Cookie Consent module will disable any widgets which could set 3rd party cookies
