### ISSUE TITLE
Member Page Groups Order

### ISSUE THREAD

**Issue by kallemarc** [NamelessMC/Nameless#2225]
If the forum has several groups it is no longer nice to look at on the members page.

**Screenshots**
https://kallemarc.de/Screens/2021/image-vAkyKLCkqM.png
Live Link: https://varoxcraft.de/members/

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr9

**Comment by samerton** [comment]
Hi,

Can you please create this issue in the Members module repository? https://github.com/partydragen/Members

As this is a third party module that is not developed as part of the Nameless core, there's nothing we can do on our side.
