### ISSUE TITLE
Forgot password link does not work

### ISSUE THREAD

**Issue by Magnum97** [NamelessMC/Nameless#2231]
**Describe the issue**
When a player registers via api it does not set a password (as in #2074) so they have to use forgot password to get a link to set one. The problem comes with the email - it arrives with an invalid link. The link provided is very long and funky. The linked text is what is needed but it does not have my domain inserted. Example from a test account:
```
Hi,
To reset your password, please click the following link. If you did not request this yourself, you can safely delete this email.

http://_/forgot_password/?c=AnGU1ylLCBMhatcI9F2j4mgfev3O7PwSrpDiHYk8QbERVuXKz6oJ5d0NWsxq
```

I had to replace the _ to get it to work. However this goes deeper because the link that I am directed to when I click on above text is 
```
http://x8uy2.mjt.lu/lnk/AUYAACsO__4AAAAAAAAAAAM7huoAAAAAXTIAAAAAABesuwBgeSmBda3Jb-hZQPydcAj9aRhBsQAXMwo/1/SJWTOO-DbKWYNXM17ZDrTw/aHR0cDovL18vZm9yZ290X3Bhc3N3b3JkLz9jPUFuR1UxeWxMQ0JNaGF0Y0k5RjJqNG1nZmV2M083UHdTcnBEaUhZazhRYkVSVnVYS3o2b0o1ZDBOV3N4cQ
```
which does not direct me to my domain.

**To Reproduce**
Steps to reproduce the behaviour:
1. Register an account either via API or via website
2. Click on forgot password on login page
3. Click or copy the link provided in the email.

**Expected behaviour**
I would directly be sent to my domain to reset password.

**Screenshots**

**NamelessMC version (from AdminCP -> Overview)**
Running NamelessMC version 2.0.0-pr9

**Comment by Derkades** [comment]
For the underscore issue, can you check if `host` is set  properly (to your domain) in `core/config.php`

**Comment by Magnum97** [comment]
Thank you for the response. The result of `grep host core/config.php`:
```
    'host' => 'mariadb',
    'hostname' => 'redacted.domain',
```
And yes, it is the correct domain for the site.

**Comment by samerton** [comment]
If you register using the website, and not the plugin/API, do you still get the invalid link in the email?

Also, which template are you using?

**Comment by Magnum97** [comment]
I registered an account via website and the validation email came through. That link worked correctly. Then I did a forgot password request and the link that came on that one was not valid. 

My template is currently the DevaultRevamp 2.0.0-pr9 by Xemah

**Comment by TheIntelloBox** [comment]
Can confirm that.

**Comment by Aberdeener** [comment]
> I registered an account via website and the validation email came through. That link worked correctly. Then I did a forgot password request and the link that came on that one was not valid.

@Magnum97 Hi, if you still have the reset password link which did not work, can you share it here?
Feel free to censor your url.
