### ISSUE TITLE
Lock session cookies to IP address

### ISSUE THREAD

**Issue by Jochyoua** [NamelessMC/Nameless#2236]
Is it possible to make it so that account identifiable cookies require the same IP they were initiated with to be valid?
Currently if you set your nl2 cookie on another browser/computer it logs you right into the account the cookie was associated with.
I would love to see this feature added for security

This doesn't apply for staff panel though, I guess you still need to re-authenticate which would be a great addon for the regular login as well.

**Comment by samerton** [comment]
The issue then is the "remember me" functionality would be useless for people with dynamic IP addresses like myself

If someone gains access to your cookies, I think you have bigger problems... 😄

**Comment by Derkades** [comment]
I agree, it is annoying for example for laptop or mobile users who move between networks regularly. I don't think it's standard practice to do this.
