### ISSUE TITLE
Configuration --> Mail gives a HTTP 500 error.

### ISSUE THREAD

**Issue by TheIntelloBox** [NamelessMC/Nameless#2237]
**Describe the issue**
Go in Admin Panel --> configuration --> mail: there is a HTTP 500 error (see screen)
Moreover, when I click on "password forgotten" for my account, it gives me this error too.

**Screenshots**
https://zupimages.net/up/21/17/elbg.jpg

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr9

**Comment by Jochyoua** [comment]
Have you edited any php files recently? Could you check the errors of nginx / apache2 or php-fpm?

**Comment by samerton** [comment]
Can you please enable debugging (StaffCP -> Configuration -> Maintenance) and try viewing the page again, to see if a more descriptive error message appears on screen

**Comment by TheIntelloBox** [comment]
Parse error: in /var/www/vhosts/speedcraft.fr/forum.speedcraft.fr/custom/languages/French/emails.php on line 24

**Comment by samerton** [comment]
The issue is with the text `l''avez`

Can you please replace this with `l\'\'avez` to escape each quote

**Comment by TheIntelloBox** [comment]
Thanks a lot ! :D
