### ISSUE TITLE
Registration email is broken

### ISSUE THREAD

**Issue by KolpixTV** [NamelessMC/Nameless#2240]
Hey,

we have a Problem with the Registration Email. If someone want to register this comes in the Email:

![image](https://user-images.githubusercontent.com/68741965/116205024-a0599080-a73d-11eb-9d9e-f594565a22d8.png)

i think something is wrong with the variables.

With friendly regards
Kolpix

**Comment by KolpixTV** [comment]
oh and it was not broken earlier

**Comment by Derkades** [comment]
Does the same issue occur when language is set to English UK?

**Comment by KolpixTV** [comment]
Yes if i set it to English UK the same thing appears but on english

**Comment by samerton** [comment]
Looks like a template issue - can you please try with the Default Revamp template and see if the same issue occurs?

**Comment by KolpixTV** [comment]
ok i try it now

**Comment by KolpixTV** [comment]
Thank you! With the Default Template its working :D

**Comment by samerton** [comment]
No problem 😄
