### ISSUE TITLE
Add option for Forum Category to disable creating category-topics

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2245]
Since i started using Nameless, I don't understand why forum category even have option for posting topics in it?
I suggest adding an option to, if we are creating forum category, be able to disable category topic posting
This would be nice

**Comment by samerton** [comment]
You can do this by disabling the "create topic" permission for the category

Categories are effectively still forums and I think it's nice to keep the option to create topics.

**Comment by TheJoshue** [comment]
> You can do this by disabling the "create topic" permission for the category
> 
> Categories are effectively still forums and I think it's nice to keep the option to create topics.

Alright, yeah that makes sense (to disable create topic permission for the category) and it's logical solution.
Although I never saw on any other forum that category that contain subforums has ability to create topic in it. Yes it is cool, and it is flexible thing because that feature is present, however I am happy this is togglable, didn't think of this practical solution for disabling create topic permission.

Thanks
