### ISSUE TITLE
If using AuthMe Integration with Synchronise AuthMe password option, "forgot password" is useless

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2249]
**Describe the issue**
i think title says it all - basically you type new password that will forever be forgotten because your ingame password is always used and can be only changed ingame

**To Reproduce**
1. Enable AuthMe Integration with "Synchronise AuthMe password" option enabled.
2. Register ingame account with /register command from AuthMe.
3. Register account on website using ingame nickname and ingame password, adding your email address.
4. Hit "Forgot Password", insert email and send link.
5. Click forgot password link to set new password
6. Enter new password and submit
7. Test new password - doesn't work

**Expected behaviour**
Should change password on site or sync new password with ingame password (if that's possible)

**Screenshots**

**NamelessMC version (from AdminCP -> Overview)**
![image](https://user-images.githubusercontent.com/56804505/116792710-a4c9d480-aac2-11eb-82ae-37634787135f.png)

**Additional information**
Add more information about the problem if necessary.

**Comment by samerton** [comment]
Personally I don't think it's right for Nameless to modify the ingame AuthMe password - I think the correct behaviour is to disable password resetting on the website when AuthMe password sync is enabled.

**Comment by samerton** [comment]
I'll close this in favour of #2251

**Comment by TheJoshue** [comment]
> Personally I don't think it's right for Nameless to modify the ingame AuthMe password - I think the correct behaviour is to disable password resetting on the website when AuthMe password sync is enabled.

Yeah, i thought of this but didn't know you will even think of accepting it so didn't mention it.
