### ISSUE TITLE
Language support.

### ISSUE THREAD

**Issue by Azoraqua** [NamelessMC/Nameless#225]
@samerton I had a question about the support of languages.
Are the languages extensive, like can I add a random language, let's say Portuguese? 

If not, how can I/we add it?

**Comment by samerton** [comment]
You can add any language you like, all you need to do is copy/paste any existing language (within the styles/language folder), rename the folder and edit the language.php file within.

**Comment by Azoraqua** [comment]
@samerton Thank you Sam, You have an extra contributor with u :)
