### ISSUE TITLE
Adding "Username" instead of "Nickname" and bad displaying of it after registration using AuthMe

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2253]
**Describe the issue**

If this option is enabled
![image](https://user-images.githubusercontent.com/56804505/116791829-2f0f3a00-aabd-11eb-8944-5057b2af0d82.png)
*screenshot_1*

After registering ingame using AuthMe plugin, going on website and using Minecraft Username (IGN) Login method + Password, you get this screen:
![image](https://user-images.githubusercontent.com/56804505/116791834-3898a200-aabd-11eb-9ec3-e6ea07ef6df0.png)
*screenshot_2*

Now here, this USERNAME is actually that "Nickname" from the first image.
You can set this to anything but I think it should by default tell "Nickname" or "Name on website"

**To Reproduce**
1. Enable "AuthMe Integration" from "Integrations"
2. Enable "Synchronise AuthMe password?" in "AuthMe Integration".
3. Set "nable nicknames for registering users?" from "General Settings" to "Enabled".
4. Go on MC server, regiseter an account using AuthMe /register command.
5. Go on website, hit "Register" button, enter Minecraft Username + Password (from ingame).
6. Here is when the *screenshot_2* appears.

**Expected behaviour**
When we get to the point just like on *screenshot_2*, it should say "Nickname" instead of "Username".

**Screenshots**
above

**NamelessMC version (from AdminCP -> Overview)**
![image](https://user-images.githubusercontent.com/56804505/116792122-06883f80-aabf-11eb-9766-509b3c163b66.png)

**Additional information**
/

**Comment by samerton** [comment]
This can be modified in the language files if you prefer to use nickname - the current idea is that you have a website username (hence "username"), and a linked Minecraft username.

**Comment by TheJoshue** [comment]
> This can be modified in the language files if you prefer to use nickname - the current idea is that you have a website username (hence "username"), and a linked Minecraft username.

Alright, yes this is a good solution for us who have same Website Username as Minecraft Username, understandable,
thanks Sam.
