### ISSUE TITLE
Changing "Nickname" and "Username"/"Minecraft Username" WORDS

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2254]
I really think this is necessary, especially if this project want to go forward and advance, we need to get organized about this.

I think that ALL "Username"/"Minecraft Username" explaination words need to be called "IGN" and nothing else than that, it's 2021. and everybody knows what IGN is. if this isn't proper because it's acronym, we can use "In-Game Nickname".

Besides "IGN", we have "Nickname", that can stay the same but make it togglable so we can use StaffCP to either allow setting nicknames or not setting them (which will simply remove them from "Account Settings" of a user)

**Comment by samerton** [comment]
At some point in the future, there will be better support for different games. Until then, Nameless is primarily for Minecraft so the Minecraft username field makes sense.

The language files offer a valid method of renaming this field if you're unhappy with the wording.

**Comment by TheJoshue** [comment]
> At some point in the future, there will be better support for different games. Until then, Nameless is primarily for Minecraft so the Minecraft username field makes sense.
> 
> The language files offer a valid method of renaming this field if you're unhappy with the wording.

Fair enough
