### ISSUE TITLE
Add option to send verification email even if AuthMe integration is enabled

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2255]
Adding option to send verification email after guest uses "Register" tab, puts his ingame MC nickname and password (that he previously registered on server with AuthMe) and when the website asks him to put email address there, send verification email so he can verify himself just like regular site system without AuthMe integration

**Comment by Derkades** [comment]
will probably be possible with https://github.com/NamelessMC/Nameless/issues/1577
