### ISSUE TITLE
Namless is loading very slow and not complete

### ISSUE THREAD

**Issue by EnglischLehrer** [NamelessMC/Nameless#2257]
**Describe the issue**
When I go to the website (forum.rushgamez.net) it loads quite slowly and not completely.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go on the website forum.rushgamez.net
2. Then you see the slow and not complete website.

**Expected behaviour**
What were you expecting to happen?
I expect, that the website is loading complete and fast/normal.

**Screenshots**
![Screenshot_2021-05-04 Startseite • RushGamez Forum](https://user-images.githubusercontent.com/83634972/116975172-7fee8080-acbf-11eb-9268-85c512eadf37.png)

**NamelessMC version (from AdminCP -> Overview)**
I am using Version 2.0.0 Pre-Release 9.

**Additional information**
We are using a webspace is this a problem?

**Comment by Derkades** [comment]
Make sure to set `path` to an empty string in `core/config.php`. This happens when path is entered incorrectly during the installer.

**Comment by EnglischLehrer** [comment]
Now it is working. Thank you good work!
