### ISSUE TITLE
For SMTP, allow choosing between TLS and STARTTLS

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2258]
Default to STARTTLS for ports 25 and 587, default to immediate TLS for port 465

**Comment by samerton** [comment]
Changing `secure` to `ssl` in `core/config.php` will allow you to use port 465

**Comment by samerton** [comment]
Apologies, please disregard my earlier comment - it's port 587 which will work with `ssl`

We'll have to add a config option to `core/email.php` to allow the TLS method to be modified

**Comment by Derkades** [comment]
only STARTTLS is relevant anyway
