### ISSUE TITLE
Incorrect group listed as main group in StaffCP users ajax list

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2263]
<img width="2529" alt="Screen Shot 2021-05-09 at 3 16 45 PM" src="https://user-images.githubusercontent.com/26070412/117588647-92aaf000-b0d9-11eb-904b-07c206265c61.png">
It should say "Admin" but says member.

**Comment by partydragen** [comment]
Um it working fine

But how is your groups ordered? as it get the top group, Well the group with lowest order id

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/117663750-4cb95f00-b1a1-11eb-9633-1c23c7176edc.png)
![image](https://user-images.githubusercontent.com/15892014/117663791-593db780-b1a1-11eb-9f3b-3a33e5cee64c.png)

**Comment by Aberdeener** [comment]
This can be fixed by replacing the query in admin_users.php line 76 with this:
```sql
SELECT `name` FROM nl2_groups g JOIN nl2_users_groups ug ON g.id = ug.group_id WHERE ug.user_id = ? ORDER BY g.order ASC LIMIT 1
```
Not sure how this compared when it comes down to performance, though.
@partydragen @samerton thoughts?
