### ISSUE TITLE
No permission to access Integrations > Discord page on fresh install

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2266]
![image](https://user-images.githubusercontent.com/15892014/117642195-4f0ebf80-b187-11eb-8048-c5ebe436d38e.png)
![image](https://user-images.githubusercontent.com/15892014/117642235-57ff9100-b187-11eb-81e0-225b59878a31.png)
url is `/panel/discord/`

**Comment by partydragen** [comment]
sorry xD
