### ISSUE TITLE
Support for bedrock server status and avatars

### ISSUE THREAD

**Issue by RealBJsingh** [NamelessMC/Nameless#2269]
Status don't work for bedrock edition servers so it would be good to add it. 
And player avatar image/head should also work for bedrock edition players. Currently only java players heads show.

**Comment by Derkades** [comment]
Please see #2153 and #2140

**Comment by RealBJsingh** [comment]
That's a year old and still no updates?

**Comment by samerton** [comment]
Current status is the query does support Bedrock servers, just needs an option when adding a Minecraft server to create it as Bedrock and query accordingly.

Avatar support using Pocketmine plugins might be better off as separate modules instead of core functionality.
