### ISSUE TITLE
Administrator created by installer is missing its UUID

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2270]
causes a very frequent question in support: "why does the plugin say I'm not registered?"

**Comment by samerton** [comment]
This was intentional at the time, I think because some web hosts are unable to communicate with Mojang's APIs for whatever reason so it was blocking the installer progressing.

If failure to retrieve UUID is handled gracefully then should be fine to reimplement.

**Comment by Aberdeener** [comment]
Added this function.
Tested the following:
- internet connection + valid MC username. Works as expected with my MC uuid.
- internet connection + invalid MC username. Works as expected w/ "none" as uuid.
- no internet connection + valid MC username. Works as expected w/ "none" as uuid.

**Comment by partydragen** [comment]
i believe the issue is more related to have internet but being unreachable / timeouts
