### ISSUE TITLE
Add drag to sort to announcements

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#2272]
~~An error occurs when editing an announcement~~

Able to drag announcements around to change the order.

**Comment by Aberdeener** [comment]
Fixed sql error: 21864a79c4815f3af0d3c2583f58fee36cbcd14b

Will do dragging soon:tm:

**Comment by StormyIceLeopard** [comment]
> Fixed sql error: [21864a7](https://github.com/NamelessMC/Nameless/commit/21864a79c4815f3af0d3c2583f58fee36cbcd14b)
my `core/classes/Announcements.php` does not have 118 lines. It has 75 lines.

**Comment by Aberdeener** [comment]
Then find the equivalent function in your class

**Comment by Aberdeener** [comment]
Added in 0980e61 
Thanks for the suggestion :)
