### ISSUE TITLE
PHP error on Maintenance page

### ISSUE THREAD

**Issue by RobiNN1** [NamelessMC/Nameless#2279]
If you enable maintenance and someone visits your site, in error log you will see this error

C:\laragon\www\nameless\core\classes\AvatarSource.php(54): Call to a member function getUrlToFormat() on null

Nameless 2.0.0-pr9 (Today downloaded from Github)
PHP 7.4.16

**Comment by Aberdeener** [comment]
Thanks, good catch. This happens because the maintenance page is loaded and sent to the user *before* the modules are loaded, so before the avatar sources are setup... Will look into a nice way to fix this soon.

**Comment by RobiNN1** [comment]
Hi thanks for reply. Also I found another problem with avatars.
In Server status page & widget it doesn't show Minecraft heads (just default Steve head). It works only for registered users on website and it doesn't matter what source of the avatar I choose.

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/6db1cd82c64aa7e71aadefd89c4c72797f5cc703
