### ISSUE TITLE
Click Jacking Vulnerability

### ISSUE THREAD

**Issue by HexDubbers** [NamelessMC/Nameless#2282]
**Describe the issue**
Nameless is vulnerable to click-jacking which can be used to delete posts, disable modules, read messages.

If you're logged into the nameless forum and click on a link provided by another person, the attacker could make the victim click on something they don't intend to and retrieve the information from the window. If the attacker is advanced they could make it auto click for the victim. (Iframes which would contain the logged in person can then be made invisible. They can then put a fake button over the disable module button so when they click the fake button they're really clicking the disable module button).

If you need a better explanation of this please let me know or please take a look at this link:
https://owasp.org/www-community/attacks/Clickjacking

**Expected behaviour**
Not still be logged in the iframe.

**Screenshots**
still logged into website on nameless forum when I navigated to attacker link:
![Capture](https://user-images.githubusercontent.com/76656985/119190120-ece97080-ba4a-11eb-9b9e-135868aa6bb6.PNG)

Still logged in on another website via iframe:
![2](https://user-images.githubusercontent.com/76656985/119190171-fffc4080-ba4a-11eb-87c5-7223215d1b8d.PNG)

**NamelessMC version (from AdminCP -> Overview)**
v2.0-pr9

**Additional information**
If you need me to make a video or need more details please let me know! This can be fixed by adding a CSP.

**Comment by Derkades** [comment]
Isn't the content security policy a header that is usually configured on the web server or terminating proxy?

We could create a wiki page with recommended webserver settings though

**Comment by HexDubbers** [comment]
> 
> 
> Thank you for looking into vulnerabilities.
> 
> Isn't the content security policy a header that is usually configured on the web server or terminating proxy?
> 
> We could create a wiki page with recommended webserver settings though

No problem! So I believe in the headers that the program sends you could include a "X-Frame-Options: deny" or "X-Frame-Options: SAMEORIGIN".  which would stop anybody from using iframes to a nameless site from a different website. Or like you said you could make a wiki page that includes something like this:
https://www.ryadel.com/en/apache-setup-httpd-conf-file-send-http-security-headers-web-site/

**Comment by samerton** [comment]
Thanks for this - I've added the header to the htaccess file, we could still do with wiki documentation if using nginx

**Comment by samerton** [comment]
In fact - I've added it to the sample nginx config in 259484b80c510b8d2128c806ca74514dce4eebd6

**Comment by Derkades** [comment]
we should also consider other headers like Referrer-Policy, X-Content-Type-Options, X-Download-Options, X-XSS-Protection, Access-Control-Allow-*
