### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by HexDubbers** [NamelessMC/Nameless#2285]
**Describe the issue**
This is a self XSS vulnerability that can also be used against admin users.

**To Reproduce**

1. Create new topic or reply.
2. enter in the following text:
   `<EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAwIiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoJ3hzcycpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>`
3. Post it
4. Find post or reply and hit edit.
5. See result.

**Screenshots**
![image](https://user-images.githubusercontent.com/76656985/119371384-6029f700-bc84-11eb-9f3e-64d60f919993.png)

**NamelessMC version (from AdminCP -> Overview)**
v2.0-pr9

**Comment by samerton** [comment]
Thanks - up until this point, Nameless will show an escaped version of any disallowed tags so they show up as plain-text in topic view.

However, the editor's picking up these escaped tags and is parsing them - 81bd793baeeb21416bead67b6668cfec4e28ddc0 changes this behaviour so the escaping is opt-in, and by default the script is outright removed.
