### ISSUE TITLE
Template Sandbox Bypass

### ISSUE THREAD

**Issue by HexDubbers** [NamelessMC/Nameless#2286]
**Describe the issue**
As admin, when editing templates its possible to bypass the sandbox and achieve code execution. 

**To Reproduce**
1. Go to admin panel.
2. Click Layout and then Templates
3. Click edit next to DefaultRevamp
4. Edit header.tpl
5. add `string:{$smarty.template_object->smarty->disableSecurity()->display('string:{system(\'id\')}')}` anywhere and save.
6. go to index page and look at the top of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/76656985/119383281-21e70480-bc91-11eb-8a19-122062d85ce8.png)

**NamelessMC version (from AdminCP -> Overview)**
 v2.0-pr9

**Additional information**
I don't know if this causes much concern for you guys since an admin account is required but I thought it would be good to bring up just in case.

an example of a fix for this is below:

$my_security_policy = new Smarty_Security($smarty);
$my_security_policy->disabled_special_smarty_vars = array("template_object");
$smarty->enableSecurity($my_security_policy);

**Comment by samerton** [comment]
Thanks, updated Smarty version + enabled security mode in a173d2d5b433b04be20d229f433accaf0b9f62fe

**Comment by samerton** [comment]
Just to note - the `cache/templates_c` folder will need to be cleared to update any affected template files.
