### ISSUE TITLE
Deprecated error

### ISSUE THREAD

**Issue by Fishycraft** [NamelessMC/Nameless#2289]
![image](https://user-images.githubusercontent.com/83877191/120827900-38784000-c55c-11eb-899a-2f1bf2395145.png)

I really need help on this, I don't know what is wrong

**Comment by Fishycraft** [comment]
![image](https://user-images.githubusercontent.com/83877191/120829308-8b062c00-c55d-11eb-8c74-a598bc2cdd1c.png)
This is the home page :/

**Comment by Derkades** [comment]
Did you enable debugging?

**Comment by Fishycraft** [comment]
> Did you enable debugging?

nope, I just got it started an hour ago

**Comment by Fishycraft** [comment]
![image](https://user-images.githubusercontent.com/83877191/120845907-ba269880-c571-11eb-8f5b-8e98495db2b0.png)
And more
![image](https://user-images.githubusercontent.com/83877191/120846224-1c7f9900-c572-11eb-89b9-068e3365851d.png)

**Comment by samerton** [comment]
Please ensure debugging is disabled (StaffCP -> Configuration -> Maintenance)

Also ensure this line is commented (ie, it starts with `//`) in index.php: https://github.com/NamelessMC/Nameless/blob/v2/index.php#L13
