### ISSUE TITLE
Registration emails don't work with subdomain

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless#2291]
**Describe the issue**
Emails received use the base domain instead of subdomain.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Nameless on subdomain, i.e. `nameless.example.org`
2. Register with acceptable email address.
3. Validation email link will use `example.org/validate...` and doesn't work.

**Expected behaviour**
Validation email should use `nameless.example.org/validate...` and should work.

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr9

**Additional information**
I've tried disabling and re-enabling registration to no avail.

**Comment by samerton** [comment]
What is the value of `hostname` in `core/config.php`?

**Comment by PikaMug** [comment]
It was `example.org` and changing it to `nameless.example.org` seems to have resolved the issue. Thank you!
