### ISSUE TITLE
Problem with reCAPTCHA v3

### ISSUE THREAD

**Issue by poqdavid** [NamelessMC/Nameless#2294]
**Describe the issue**
When trying to use the reCAPTCHA v3 option it keeps saying `Invalid reCAPTCHA response.`

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to panel/core/registration/
2. Enter Your reCAPTCHA v3 info and press submit
3. Open login page and try to login

**Expected behaviour**
It should have not given an invalid response cause I am 100% sure the info I added was correct.

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC version 2.0.0-pr10

**Comment by samerton** [comment]
I can't reproduce any issues, reCaptcha v3 is in use on namelessmc.com

Does reCaptcha v2 or hCaptcha work?

**Comment by poqdavid** [comment]
It seems like it won't switch to hCaptcha at all can this be a template problem?

**Comment by poqdavid** [comment]
Sorry update the problem was with the template I will try to fix it

**Comment by poqdavid** [comment]
The problem was solved by changing the `login.tpl`, `register.tpl` and `contact.tpl` as you said.
Adding ids to form tag `id="form-login"`, `id="form-register"` and `id="form-contact"`

Also changing
```
{if isset($RECAPTCHA)}
  <div class="form-group">
    <div class="g-recaptcha" data-sitekey="{$RECAPTCHA}"></div>
  </div>
{/if}
```
to
```
{if $CAPTCHA}
  <div class="field">
    {$CAPTCHA}
  </div>
{/if}
```
