### ISSUE TITLE
Some translations missing in en-US

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2295]
so far the following have been reported:
- `group_sync_logs` admin.php
- `no_placeholders` user.php

**Comment by RobiNN1** [comment]
Another missing term in en-us `Term announcement_order not set (file: admin.php)`

**Comment by Derkades** [comment]
We already use [weblate](https://translate.namelessmc.com/) for all projects except for the website. The website will be moved over soon.

**Comment by itsmemac** [comment]
#2319 pull request created

**Comment by itsmemac** [comment]
#2320 Fix for user.php with placeholder
