### ISSUE TITLE
Specified key was too long during installation

### ISSUE THREAD

**Issue by Kydaix** [NamelessMC/Nameless#2298]
**Describe the issue**
I have a problem that prevents me from installing the new version of NamelessTM (V2 Pre-10).
This problem occurs when connecting to my MySQL database. My database is InnoDB compatible.
When I was using the V2 Pre-9 version, I had no problem.

Moreover, I noticed that only some of us have this problem.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the V2 Pre-10 version of Nameless.
2. Choose a new installation.
3. Continue to the step of connecting to the MySQL database.
4. Enter your login information and log in.

**Expected behaviour**
What were you expecting to happen?
The process should work and continue the installation program.

**Screenshots**
![The error in question.](https://cdn.discordapp.com/attachments/247865182477484032/858741584672849950/Capture.PNG)
- [Another error if I click on "Reload".](https://cdn.discordapp.com/attachments/247865182477484032/858741648087580692/Capture2.PNG)
- [The configuration of my MySQL database.](https://cdn.discordapp.com/attachments/247865182477484032/858742062642626590/unknown.png)

**NamelessMC version (from AdminCP -> Overview)**
I don't have access to this page... But the NamelessMC version is the V2 Pre-10.

**Comment by samerton** [comment]
Thanks for the detailed report.

Do you know which MySQL/MariaDB version your web host is using?

**Comment by samerton** [comment]
Regardless I think the fix here is to change the `nl2_placeholders_settings` and `nl2_users_placeholders` tables so they have a numeric auto increment primary key to ensure compatibility with older database software

**Comment by Kydaix** [comment]
Of course, I have given this information in the image linked to the post.

**MariaDB:** 5.5.63

**Comment by Kydaix** [comment]
> Regardless I think the fix here is to change the `nl2_placeholders_settings` and `nl2_users_placeholders` tables so they have a numeric auto increment primary key to ensure compatibility with older database software

Okay, I guess I can't change that myself!
So, I would wait for a fix!

Thanks for taking this problem into account!

**Comment by samerton** [comment]
Something you can try as a workaround is installing v2 pre-release 9, then updating in the StaffCP -> Update tab. This should allow you to use pre-release 10 without any issues

**Comment by Kydaix** [comment]
Nice, I'll try this in a few days, as I have exams tomorrow.

Thanks again for your help!

**Comment by samerton** [comment]
A fix should be included in pre-release 11, until then the pre-release 9 -> upgrade to pre-10 should work 👍

**Comment by Derkades** [comment]
currently the key is made up of:
`server_id`, int, 4 bytes (?)
`uuid`, varchar(32), 32-96 bytes
`name`, varchar(256), 256-768 bytes

I propose
- storing UUID as bytes instead of hex text, uses only 16 bytes instead of 96 bytes for the key (so varbinary(16))
- reducing name to varchar(200)
that way everything fits in 767 bytes easily

Doing this instead of just adding a new primary key field also solves #2322

**Comment by Derkades** [comment]
Correction: while utf8 uses up to 3 bytes per character, utf8mb4 actually uses 4 bytes per character.

`server_id`, int, 4 bytes
`uuid`, varchar(32), up to 128 bytes
`name`, varchar(256), up to 1024 bytes

fixed layout:
`server_id`, int, 4 bytes
`uuid`, varbinary(16), 16 bytes
`name`, varchar(186), up to 744 bytes

In total up to 764 bytes which fits within the 767 byte maximum. Limits are 767, 1000 or 3072 depending on the database software and settings, so by targeting 767 bytes no one will have problems.

**Comment by samerton** [comment]
Attempt 2... 7e02f734b59c141735c720b18816346d6712cb3e
