### ISSUE TITLE
Issue with mobile forum display, question, request

### ISSUE THREAD

**Issue by fenix12585** [NamelessMC/Nameless#23]
Hello, Thank you for help with my previous issue. It has been resolved and is working great.

-----Issue-----
Now, I notice that i get errors at the top of the forum page. they only show when loaded through my cellphone. They do not display when viewed on the pc.
http://tester.thecraftersguild.net/forum
Notice: Trying to get property of non-object in /home/thecraftersguild/public_html/tester/pages.php/forum/index.php on line 54
Notice: Trying to get property of non-object in /home/thecraftersguild/public_html/tester/pages.php/forum/index.php on line 137

-----Question-----
I would like to display my dynmap on a custom page of my site. Typically this is done through an iframe. How can I add custom html to a custom page. I can not find a way to currently. If this is not currently possible, Can that be added to the next version? Also, on the forums page i listed above, if you use a darker style, the text "overview" on the box on the right does not display correctly. Where is this reference? is it in the theme or style? I would like to change the color to make it display properly.

-----Request-----
I love the style and template system. Currently nameless comes with a bunch of styles and only 1 template. Can you include different templates?

Thanks Again for everything.

**Comment by samerton** [comment]
Hi,

Glad things are working well!

Issue:
Unfortunately, due to the way things work, I'm not planning on fixing those messages just yet as they don't affect the site functionality at all. In order to hide the messages, try heading into your AdminCP's "Misc" tab and if "Enable error reporting" is enabled, disable it.
If not, your web host will be set up to display PHP errors. There might be a setting in your webhost's control panel which hides PHP errors, this would depend on their setup.

Question:
I can add a Dynmap page for the full 1.0 release, and the ability to insert HTML into custom pages will hopefully make it into 1.1.
As for the black text, that's down to the theme. The forum sidebar has been converted from a previous version of Bootstrap, so you can find the css in question within **styles/themes/Darkly/css/custom.css**, and the class that needs changing is **.nav-header**

Request:
I don't plan on adding any more templates in the near future as I'm not too good with web design unfortunately, hopefully if users are willing to contribute their own designs, I can set up a place for them to do so.

**Comment by fenix12585** [comment]
well again, thank you for your quick response!



I turned off error reporting and that resolved my issue.



Please add the dynmap support, it is a very nifty feature of my server.



As for the theme, I was able to change that color, thank you! Bootstrap is new to me, Can I use any bootstap theme for this? If so, what is the best way to find them? I did a google search for them, and most seem more than I need, due to your template system. Is there a way a novice like me could convert them?



Also, where can i find the header image and text formatting on the front page? I would like to change that to a picture from my server and change the text color to show up if i need to. Will there ever be a language file so change the default text around? for example if i wanted to add a : to connect to the server.



Lastly, That sounds great about a user contributed area for themes. I think you might be able to get some designer support probably for free from mc-market.org forums. A lot of people will make things like that for a vouch. Plus you have an amazingly unique and awesome creation, so i bet many people will want to be a part of it.





 ---- On Wed, 04 Nov 2015 15:55:30 -0500 samerton &lt;notifications@github.com&gt; wrote ----




Hi,

Glad things are working well!

Issue:

 Unfortunately, due to the way things work, I'm not planning on fixing those messages just yet as they don't affect the site functionality at all. In order to hide the messages, try heading into your AdminCP's "Misc" tab and if "Enable error reporting" is enabled, disable it.

 If not, your web host will be set up to display PHP errors. There might be a setting in your webhost's control panel which hides PHP errors, this would depend on their setup.


Question:

 I can add a Dynmap page for the full 1.0 release, and the ability to insert HTML into custom pages will hopefully make it into 1.1.

 As for the black text, that's down to the theme. The forum sidebar has been converted from a previous version of Bootstrap, so you can find the css in question within styles/themes/Darkly/css/custom.css, and the class that needs changing is .nav-header


Request:

 I don't plan on adding any more templates in the near future as I'm not too good with web design unfortunately, hopefully if users are willing to contribute their own designs, I can set up a place for them to do so.

**Comment by samerton** [comment]
I've had a look into allowing custom HTML into pages, and it's something I can do now so I'll try and get that done, so Dynmap can be embedded in there.

You can use any Bootstrap 3 theme; NamelessMC won't work with Bootstrap 2 or 4 currently.
You can simply duplicate and rename an existing theme within the **styles/themes** folder, and replace the **bootstrap.min.css** file with the new one you want to install.

To replace the homepage image, simply replace **core/assets/img/background-1920x828.jpg** with the image of your choice; try to keep the dimensions the same (1920x828).
You can change the text displayed by editing **styles/language/EnglishUK/language.php**; the line you'll want to change is line 442.

**Comment by fenix12585** [comment]
Seriously i have been around the community and on many message boards. the support you are giving me is amazing. I think this should be my last 2 questions.



1) how can I donate to this project? I dont have much, but i want to help out however i can.



2) Am i missing something with the forums? I have created several in the admin section, and made sure to check all the boxes for viewing and stuff... but they never show up in the front end, or on the main page under news if i check the box to display it there.





 ---- On Wed, 04 Nov 2015 16:27:18 -0500 samerton &lt;notifications@github.com&gt; wrote ----




I've had a look into allowing custom HTML into pages, and it's something I can do now so I'll try and get that done, so Dynmap can be embedded in there.

You can use any Bootstrap 3 theme; NamelessMC won't work with Bootstrap 2 or 4 currently.

 You can simply duplicate and rename an existing theme within the styles/themes folder, and replace the bootstrap.min.css file with the new one you want to install.


To replace the homepage image, simply replace core/assets/img/background-1920x828.jpg with the image of your choice; try to keep the dimensions the same (1920x828).

 You can change the text displayed by editing styles/language/EnglishUK/language.php; the line you'll want to change is line 442.

**Comment by samerton** [comment]
I've pushed a commit to allow iFrames to be embedded into custom pages. Can you replace the contents of **pages/admin/pages.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/81221554b6c96b75bcaaaffda077091fc15ce9c2/pages/admin/pages.php), and the contents of **pages/extra.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/81221554b6c96b75bcaaaffda077091fc15ce9c2/pages/extra.php). Then, head into your custom page within the AdminCP, and there should be a new "Source" button in the toolbar of the text editor. Click on this, and then paste your iFrame code into there, and it should work.

1) There's currently no donate button, I may add one in the future though.

2) First, you need to create a "parent forum"; this is just an ordinary forum which will contain the forums you want to display.
Then, edit the forums you've already made, and set their parent forum to the one you've just created.

Hopefully that makes sense.

**Comment by fenix12585** [comment]
ok, all of my issues are resolved! The beta is working out very well for me, If I go live with it, when 1.0 is officially released, will updating be easy to do?





 ---- On Wed, 04 Nov 2015 18:03:56 -0500 samerton &lt;notifications@github.com&gt; wrote ----




I've pushed a commit to allow iFrames to be embedded into custom pages. Can you replace the contents of pages/admin/pages.php with this code, and the contents of pages/extra.php with this code. Then, head into your custom page within the AdminCP, and there should be a new "Source" button in the toolbar of the text editor. Click on this, and then paste your iFrame code into there, and it should work.

1) There's currently no donate button, I may add one in the future though.

2) First, you need to create a "parent forum"; this is just an ordinary forum which will contain the forums you want to display.

 Then, edit the forums you've already made, and set their parent forum to the one you've just created.


Hopefully that makes sense.

**Comment by samerton** [comment]
Yes, there will be instructions on how to upgrade when the full 1.0 release comes out; it's best to keep an eye on the Spigot thread for when that happens. After the 1.0 release, upgrading will be even easier.

**Comment by fenix12585** [comment]
Awesome! Thank you so much for all your help! If you need any testing for anything or I can ever help out just let me know! I'll help in any way that I can. I especially can't wait for the plugin and trouble tickets... ---- On Wed, 04 Nov 2015 18:30:16 -0500  samerton<notifications@github.com> wrote ----Yes, there will be instructions on how to upgrade when the full 1.0 release comes out; it's best to keep an eye on the Spigot thread for when that happens. After the 1.0 release, upgrading will be even easier.—Reply to this email directly or view it on GitHub.

**Comment by samerton** [comment]
No problem at all, thanks for the offer!

**Comment by fenix12585** [comment]
Hey can I also put in a request for a wiki add on? I know you have a lot to do, but in the future it would be very helpful. Many of us have custom recipes and mechanics and stuff... Also if we could add custom pages not on the menu or footer, that could help a lot too. Lastly, in the future can you add a box in the donator shop with minecraft marketplace for the monthly goal it would be amazing.---- On Wed, 04 Nov 2015 18:33:44 -0500  samerton<notifications@github.com> wrote ----No problem at all, thanks for the offer!—Reply to this email directly or view it on GitHub.

**Comment by samerton** [comment]
Sure, I can add a wiki addon in a future release.

As for the link to a custom page not displaying, that's planned for a future update.

I don't think a box for a monthly goal is possible, as this is down to the API for each donor store not giving that information to be used.
