### ISSUE TITLE
Invalid token - token field blank

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2312]
![image](https://user-images.githubusercontent.com/15892014/123708161-3a87a300-d86b-11eb-94cd-cb79e2fe6e06.png)
![image](https://user-images.githubusercontent.com/15892014/123708178-3f4c5700-d86b-11eb-8f71-a70ab46adaeb.png)
![image](https://user-images.githubusercontent.com/15892014/123708200-48d5bf00-d86b-11eb-80c6-a3c29c587711.png)

**Comment by partydragen** [comment]
This issue is happning for websites that don't use SSL, 

The invalid token happning when using http:// protocol instead of https://

**Comment by Derkades** [comment]
`ini_set('session.cookie_secure', 'On');` was added to index.php, this needs an if statement so it is only set for HTTPS websites

**Comment by samerton** [comment]
c83b85108a938d3fda022721659e362ec046d622
