### ISSUE TITLE
[Suggestion] Forum Ranks by Vault Permissions

### ISSUE THREAD

**Issue by ServerCrashes** [NamelessMC/Nameless#232]
I know that ranks by Vault **Groups** are planned, but could a way to have ranks chosen by permissions be possible?

On my server, purchased ranks are separated using permissions, since the main group is taken up by the in-game rank. 

Would it be possible, for example, to make it so that if a user has the permission "ranks.demigod" in game, they'll get the Demigod rank on the forum?

**Comment by jesseke55** [comment]
You`ll need then a addon of the website to use it otherwise it won`t work.

**Comment by samerton** [comment]
Sure, this is something that can be looked into. Once the web-side API is complete, plugin authors will be able to implement such features within the plugin itself, and this _could_ be added into the official plugin.

**Comment by samerton** [comment]
This is now possible using the [official plugin](https://github.com/NamelessMC/Nameless-Plugin) :)
