### ISSUE TITLE
Favicon broken

### ISSUE THREAD

**Issue by LordVorT** [NamelessMC/Nameless#2321]
Website: https://attrox-zones.eu/
Hello, after updating to Nameless pr.10 i have broken favicon.
Please help me.

**Comment by Derkades** [comment]
What does "broken" mean? It shows a favicon for me

**Comment by BaxAndrei** [comment]
Try CTRL + F5, might help.

**Comment by itsmemac** [comment]
> Website: https://attrox-zones.eu/
> Hello, after updating to Nameless pr.10 i have broken favicon.
> Please help me.

We are able to see the favicon of your website without any issues
seems to be cache issue with browser

[Favicon working](https://i.postimg.cc/qMVnVSbS/8.jpg)

try forcing a browser cache refresh by viewing your site and pressing Ctrl + F5 on windows or Cmd + Shift + R on macos.
And if you're using Cloudflare, don't forget to purge cache there as well
