### ISSUE TITLE
Error fatal - "Uncaught PDOException | SQLSTATE[42000]"

### ISSUE THREAD

**Issue by Marcos03BR** [NamelessMC/Nameless#2323]
**Issue**
I get an error every time I try to change any settings in "general settings". However, it allows me to change any settings that are not in "general settings", for example; enable maintenance, API settings, logging... 

_I get the following error:_ 
_"Uncaught PDOException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
(File: .../core/classes/DB.php).

Frame # 6
.../core/classes/DB.php:81

Frame # 5
.../core/classes/Queries.php:46

Frame # 4
.../modules/Core/pages/panel/general_settings.php:111

Frame # 3
.../index.php:86"_

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'panel'
2. Click on 'configuration'
3. Click on 'general settings'
3. Change any setting

**Expected behaviour**
I was hoping to be able to change the general settings; language, time zone, https, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/45741056/124645199-70441180-de93-11eb-979a-4749b0523f29.png)

**NamelessMC version (from AdminCP -> Overview)**
NamelessMC version 2.0.0-pr10

**Additional information**
It is a fresh installation, select "SpanishES" as language in the installation and also activate "Pretty URL" (it appeared to me that it was compatible), the rest of the options are the default ones, except for the database information.

Server specifications:
* PHP 7.4.20 
* PHP GD 7.4.20 
* PHP mbstring 7.4.20 
* PHP PDO 7.4.20 
* PHP cURL 7.4.20 
* PHP XML 7.4.20 
* PHP EXIF 7.4.20 
* PHP MySQL 
* Escritura del core/config.php 
* Caché grabable 
* Caché de plantillas 

**All specifications have a positive check**

**Comment by Derkades** [comment]
related: #2229
thank you for providing extensive information, hopefully this will help one of the website developers find the cause of this issue

**Comment by partydragen** [comment]
It looks like you don't have a default language set for some reasons

What exactly did you do?
Is this a fresh installation? did you upgrade from v1 or did you upgrade from any v2 pre releases

**Comment by partydragen** [comment]
Have a felling its the language selection during the installer

**Comment by Marcos03BR** [comment]
I have updated the main message with the extra information.

It is a fresh installation, select "SpansihES" as language in the installation and also activate "Pretty URL" (it appeared to me that it was compatible), the rest of the options are the default ones, except for the database information.

**Comment by Marcos03BR** [comment]
I have managed to fix the error.

The error came from the fact that no language was selected in the database, specifically in "nl2_languages".

This is when the error I mentioned in the main message appears. At this moment it won't let you change any of the settings in "general settings" - I can't even set any of the languages, the same error always appears.
![image](https://user-images.githubusercontent.com/45741056/124752640-65878c00-df28-11eb-9dad-2d6ec9158f98.png)

But when in the database, in "nl2_languages" you change the value of one of the languages to "1", then the changes take effect on the website and the error no longer appears.
![image](https://user-images.githubusercontent.com/45741056/124753229-0118fc80-df29-11eb-9825-2e260b0b6c75.png)

Here you can see how the error no longer appears, and the changes are saved.
![image](https://user-images.githubusercontent.com/45741056/124753389-37ef1280-df29-11eb-9f30-427bf7ea0e54.png)

**Comment by partydragen** [comment]
Yea the issue happned because it was no default language set, but i talked about how it happned and i found the issue now and fixed it
