### ISSUE TITLE
Wrong page title

### ISSUE THREAD

**Issue by skyrowl** [NamelessMC/Nameless#2325]
**Describe the issue**
The page title is set to "test" instead of what it's supposed to be

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to AdminCP
2. Click on "Security"

**Expected behaviour**
A real page title instead of "test"

**Screenshots**
![image](https://user-images.githubusercontent.com/66191586/124672348-29681300-deb7-11eb-8328-a6b6301367dd.png)

**NamelessMC version (from AdminCP -> Overview)**
v2-pr10

**Comment by partydragen** [comment]
Works fine for me, So test must be your site name but then its on all pages

**Comment by Derkades** [comment]
Ah yes, the site name is shown after the dot so that must be it
