### ISSUE TITLE
Provide translations for terms of service

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2326]
The ToS section that's added by NamlessMC, not the user provided section:
![image](https://user-images.githubusercontent.com/15892014/124890431-552eea00-dfd8-11eb-9c2f-b97b32c134c9.png)

**Comment by samerton** [comment]
This is stored in the database (it's not meant to be easily available to edit, ie within language files).

I'm considering removing it from this screen, rephrasing slightly and showing it at the start of the installer, need to check any potential legal implications first though

**Comment by samerton** [comment]
The Nameless terms were removed from this page in https://github.com/NamelessMC/Nameless/commit/b4718ba2670fa9aeb6acddf995a22a203229465f
