### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#2334]
**Describe the issue**
Please describe the issue in as much detail as possible

When I try to go to the login page an error occurs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://skyfall.coldfiredzn.com/login

**Screenshots**

![download](https://user-images.githubusercontent.com/57230688/124991681-d39a8480-dff6-11eb-9324-356b8af47464.jpg)

**NamelessMC version (from StaffCP -> Overview)**
v2 pre-10 (and yes the template is updated to support this version)

**Additional information**
Add more information about the problem if necessary.

**Comment by partydragen** [comment]
Thats weird, Only thing i can think of is there is no captcha type set maybe, atleast you can disable captcha  from /core/config.php then get to StaffCP to check if captcha type is set well save then try again

**Comment by CqldFire** [comment]
I had captcha enabled before the update, would that affect it?

**Comment by partydragen** [comment]
did you run the update button to update the db

**Comment by CqldFire** [comment]
yes

**Comment by samerton** [comment]
Can you change `captcha` to `false` in `core/config.php`, then log into your website and re-enable captcha via the StaffCP -> Configuration -> Registration tab

**Comment by CqldFire** [comment]
thanks, fixed. However, you should investigate this issue so it can be fixed for other users

**Comment by Derkades** [comment]
Related issue: #2371
