### ISSUE TITLE
Unable to disable force HTTPS in V2 Pre10

### ISSUE THREAD

**Issue by lilZoey** [NamelessMC/Nameless#2337]
I recently made the regretable choice of enabling force HTTPS without doing research, turns out I dont have the stuff required to make it work but I also use cloudflare flexible, and I know its reported that flexible doesnt work with force HTTPS I know that now, but I dont feel like changing this and it works for what I need right now. So I read to delete `cache/033f3da34ae9ec9661072ab0897ddf7ed642de3f.cache` so I go to check and delete it I press CTRL+F and paste the cache in, and nothing shows up, there's nothing to delete. And now I cant fix it. and I cant access adminCP to dissable it from there. Please help. I dont know if its because the newer versions change it or not, as all the posts where from back in 2020

**Comment by samerton** [comment]
Hi,

Please change `force_https` to `false` in the file `core/config.php`
