### ISSUE TITLE
Contact bug.

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2341]
If you try to contact (https://www.soff.ml/contact) it won't show the email address

1. Go to https://www.soff.ml/contact (or some other domain).
2. Paste the email and the message.
3. Click send.
4. And the admins will only get the message.

I thought I would get the email AND the message

https://padow.why-am-i-he.re/54pIVWC7Q - What I pasted.

https://padow.why-am-i-he.re/54pILyqfW - What I got.

Nameless V2 pre-10

**Comment by partydragen** [comment]
The email is already added to "Reply to" Don't know what email viewer you use but should normaly work to click on something to see it

Anyways if you reply to the email the user will get replyed back to that email

**Comment by PadowYT2** [comment]
I use yandex mail

**Comment by PadowYT2** [comment]
Oh..... I got it, thx
