### ISSUE TITLE
Custom Page Bug..?

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2344]
Somehow, when I created a custom page it kinda bugged..? Now I have the name of the page at the right side
https://padow.why-am-i-he.re/54NsvIi1C (screenshot)

**Comment by PadowYT2** [comment]
Or is it a browser bug?

**Comment by Derkades** [comment]
Accidentally used an RTL character?

**Comment by PadowYT2** [comment]
M, yes my mod did it for some reason thx for telling that
