### ISSUE TITLE
Test email works but register and verify emails don't (PHPMailer)

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless#2345]
Pre10
![image](https://user-images.githubusercontent.com/10292779/126378541-55b08a6a-c87e-4360-a391-be36beee1407.png)

**Comment by StormyIceLeopard** [comment]
Well, I am using an SMTP server, and at the time of the first notice Test Emails were working.
Just tested Test Emails again and it is unable to connect to SMTP server. Will make a new comment when I resolve the SMTP issue and if auto `/register` emails work or not.

**Comment by relavis** [comment]
I'm not even getting registration emails at all on pre-10, even with ```Enable Email Verification``` enabled. No email errors and no email logs at all.

**Comment by Derkades** [comment]
Possibly related to #1885, are you all using php 8?

**Comment by skrevt** [comment]
in StaffCP this is what is displayed to me **PHP 7.4.22**

**Comment by StormyIceLeopard** [comment]
![Screenshot_20210816-065542_Brave](https://user-images.githubusercontent.com/10292779/129553464-a418c015-65f8-41c3-89c9-0f8ebf94446d.jpg)

**Comment by skrevt** [comment]
Still does not work, please help

**Comment by samerton** [comment]
If PHPMailer is enabled, edit the file **core/classes/Email.php** in a text editor.

Delete all code inside and replace with [this new code](https://gist.githubusercontent.com/samerton/a26df55561f9735eb2f69af6868f57fb/raw/39600339f889e35546daa8a7f9b89788cfa73261/Email.php).

Then, each time an email gets sent, a full debug log of what happened will appear on screen.

To reiterate - this will only show a debug log if PHPMailer is enabled and SMTP is configured (StaffCP -> Configuration -> Emails)

**Comment by StormyIceLeopard** [comment]
SMTP server is working again, that took way too long to sort out. Currently on pre 11. `/register <valid_email>` does create an account, but no email is sent. Test Email does work. Looking at Database, a password is in the column, and a reset_code is in the column. So I am unsure why an email is not sent out to verify the account.

**Comment by Derkades** [comment]
Results of testing with phpmailer + my own mailserver:
* Test email works
* Registration validate email works
* "Resend activation email" button in StaffCP works

**Comment by Aberdeener** [comment]
Let's test this again once #2606 is complete

**Comment by partydragen** [comment]
Atleast all mail() is bruken in pr13 unless @Derkades blocked it or something on NamedHosting

The multiple email errors i sendt on discord a while ago, but pretty sure those broke recently and effecting all emails including test emails

**Comment by Derkades** [comment]
Yes, mail() won't work on named hosting, third party SMTP servers only.

**Comment by Aberdeener** [comment]
Closing since the whole system has been redone and Party has tested it
