### ISSUE TITLE
Adding shared reports

### ISSUE THREAD

**Issue by ItzFire-source** [NamelessMC/Nameless#2346]
The idea is simple, adding a report command on the Namelessmc plugin where every report goes to the website in a new section named "Minecraft Reports", where you can see report details like:

 - User sending the report (if linked, Discord and/or forums name)
 - Report used( if linked, Discord and/or Forums name)
 - Report Reason
 - Report date( DD-MM | hh:mm)

This would be a lot useful as it would help staff members reorganizing everything on the website, instead of using hundreds of commands in-game.

**Comment by IDKB0x** [comment]
That's not really an issue, also there already is a command for that.

**Comment by Derkades** [comment]
The plugin does have a /report command but I have no idea what the website does with received reports

**Comment by IDKB0x** [comment]
I’m pretty sure it’s something similiar to what @ItzFire-source said.

**Comment by Aberdeener** [comment]
The report "origin" is now displayed on the Reports page in StaffCP
