### ISSUE TITLE
Error 500 when sending a test email

### ISSUE THREAD

**Issue by tommywxd** [NamelessMC/Nameless#2348]
**Describe the issue**
Please describe the issue in as much detail as possible

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on configuration
2. Click on emails
3. Enable phpmailer + fill in credentials
4. Click send test email

**Expected behaviour**
It sends an email

**Screenshots**
![image](https://user-images.githubusercontent.com/62763456/126877951-86ea5aa3-37cc-45a3-86b1-f9c764da3ae9.png)

**NamelessMC version (from StaffCP -> Overview)**
2.0.0-pre10

**Additional information**
n/a

**Comment by tommywxd** [comment]
Disabling PHPMailer also shows this
![image](https://user-images.githubusercontent.com/62763456/126878072-d46c5622-b015-4c2f-8d80-7acc2c6b57d7.png)

**Comment by samerton** [comment]
Can you keep PHPMailer enabled, enable debugging (StaffCP -> Maintenance) and try sending a test email again. Hopefully a more descriptive message will appear on screen.n

**Comment by tommywxd** [comment]
> Can you keep PHPMailer enabled, enable debugging (StaffCP -> Maintenance) and try sending a test email again. Hopefully a more descriptive message will appear on screen.n

Just did that, it's still saying "Unknown".

**Comment by samerton** [comment]
If PHPMailer is disabled, it will say "Unknown" - this is because your web host has not configured PHP's `mail` function.

If PHPMailer is enabled (which resulted in a 500 earlier), it should show a more descriptive error message on screen.

**Comment by tommywxd** [comment]
> If PHPMailer is disabled, it will say "Unknown" - this is because your web host has not configured PHP's `mail` function.
> 
> If PHPMailer is enabled (which resulted in a 500 earlier), it should show a more descriptive error message on screen.

Oh, okay.

I also managed to find the fix for the 500 error.
In "core/includes/phpmailer/PHPMailerAutoload.php", I changed the function name "__autoload" to "spl_autoload_register".

**Comment by samerton** [comment]
Glad you were able to resolve the issue - there are currently a couple of compatibility issues with PHP 8 (this being one of them) - #1885 is the issue tracking this
