### ISSUE TITLE
Error with Tebex Addon in 2.0.0-pr10

### ISSUE THREAD

**Issue by WaffleCodez** [NamelessMC/Nameless#2349]
**Describe the issue**
When you set up Tebex and force sync and go to the store page, you recieve this error:
Uncaught TypeError
count(): Argument #1 ($var) must be of type Countable|array, string given
(File: /data/modules/Tebex/pages/store/category.php)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the Nameless-Tebex module
2. Enter your server key
3. Sync the store
4. Go to the store page
5. Click a category

**Expected behaviour**
Shows the packages in the category

**Screenshots**
![Screenshot from 2021-07-26 12-57-28](https://user-images.githubusercontent.com/73138329/126985139-2768977e-7ff3-4c9b-b9fa-fd6524c19e28.png)
![Screenshot from 2021-07-26 12-57-16](https://user-images.githubusercontent.com/73138329/126985140-f192f35c-8f6b-44f9-a3dd-97bf35691c55.png)

**NamelessMC version (from StaffCP -> Overview)**
Version: 2.0.0-pr10

**Comment by samerton** [comment]
Hi,

Issues with modules belong in the relevant module repository, https://github.com/samerton/Nameless-Tebex is for Tebex

In this case though, you'll need to downgrade to PHP 7.4, as PHP 8 isn't yet fully supported.
