### ISSUE TITLE
@mention username suggestions

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2351]
![image](https://user-images.githubusercontent.com/15892014/131325802-ab8cb316-7bbb-40dc-bf0c-a120f8ef52a2.png)

**Comment by Aberdeener** [comment]
The official TinyMCE plugin for Mentions is paid, however this guide seems great for letting us make our own plugin:
https://www.martyfriedel.com/blog/tinymce-5-creating-an-autocomplete-plugin
