### ISSUE TITLE
MCAssoc

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2353]
When trying to disable MCAssoc, it doesn't let me

https://user-images.githubusercontent.com/71085027/127476993-77d75186-ea0b-44ad-beaf-4a36c3d424f3.mp4

V2-Pre10

**Comment by samerton** [comment]
Hi,

Can you please try the instructions in Partydragen's comment here: https://github.com/NamelessMC/Nameless/issues/2311#issuecomment-877642446

**Comment by PadowYT2** [comment]
Ok thx
