### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by oRIOnTx** [NamelessMC/Nameless#2354]
Steps how to get error:
1. Go admin panel and click Integrations. Select server integration and click off and on.
2. After that you get

![image](https://user-images.githubusercontent.com/40061096/127652890-17749c87-5ef8-4eb3-b6fd-9cb196acf80b.png)

**Comment by PadowYT2** [comment]
Maybe you were too fast and the database couldn't catch up? I cannot get the error
