### ISSUE TITLE
Register form occasionally displays empty error list

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#2355]
Issue is potentially caused by https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Validate.php#L201

If browser returns null for timezone, this check will fail since null is not a valid timezone.

**Comment by Aberdeener** [comment]
Let's test this again when #2606 is complete

**Comment by partydragen** [comment]
> Let's test this again when #2606 is complete

registration timezone is disabled with makes this work, so timezone is commented out with todo for this issue

**Comment by Aberdeener** [comment]
Alrighty, that should do it! Works on my end w/ different scenarios
