### ISSUE TITLE
Way to change Store labels

### ISSUE THREAD

**Issue by ServerCrashes** [NamelessMC/Nameless#236]
I want to change the "Donate" tab to "Store", and have the url be mydomain.com/store, rather than /donate. Is there any current way to do this?

**Comment by Schwertspize** [comment]
For changing donate to store you can edit your translation. 

However, pointing donate to store is a bit more difficult because you would need to move the file and edit every file referring to it. (and probably fix some more stuff)

**Comment by samerton** [comment]
As @Schwertspize says, the translation file (addons/Donate/language.php) can be changed for this.

As for changing the link, try renaming the **pages/donate.php** file to **pages/store.php**, and change line 16 of addons/Donate/initialisation.php to

`$navbar_array[] = array('store' => $donate_language['donate_icon'] . $donate_language['donate']);`

I've not tested this, it's off the top of my head, but hopefully it should work without issue.

**Comment by ServerCrashes** [comment]
That worked!
Thanks!
