### ISSUE TITLE
Add unique constraint to module name to solve duplicate modules issue

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2360]

**Comment by partydragen** [comment]
well then it pretty much being for everything as it happning because them run the installer multiple times somehow since everything being duplicated

**Comment by Aberdeener** [comment]
> well then it pretty much being for everything as it happning because them run the installer multiple times somehow since everything being duplicated

Sorry can you explain again? I dont understand what you mean

**Comment by samerton** [comment]
> > well then it pretty much being for everything as it happning because them run the installer multiple times somehow since everything being duplicated
> 
> Sorry can you explain again? I dont understand what you mean

The way modules get duplicated in the database is if the installer gets refreshed as it initialises data.

This means that it's not only modules which get duplicated - settings are another example of rows which will be duplicated in the database when this happens.

So adding a unique constraint to the name column in nl2_modules is only a partial solution.

**Comment by supercrafter100** [comment]
Would saving the fact that the database is being initialized and not allowing it to be initialized again not completely prevent this issue?
