### ISSUE TITLE
Add per-group frame to user's avatar who has that group

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2361]
i think everything is understandable from reading the title, just want to point out that would be cool (if this gets added) that the priority is followed, for example if Staff & MVP has their own frames for user avatar, and Staff group has higher priority than MVP group, and user has both groups, it will display Staff group's frame for user avatar because it has higher priority.
Direct example: 
![image](https://user-images.githubusercontent.com/56804505/128436410-b6de9cb7-dcdf-4d5e-a88e-395a8789c9e6.png)

**Comment by samerton** [comment]
If this is something you'd like us to prioritise when we get round to the feature backlog, please upvote this discussion: https://github.com/NamelessMC/Nameless/discussions/2142 - thanks!
