### ISSUE TITLE
Allow users to link their MC premium account

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2362]
title says

Direct example (that "Gogeta"):
![image](https://user-images.githubusercontent.com/56804505/128436673-4225b5ea-a222-434d-97ac-2ab00a814cc3.png)

**Comment by Derkades** [comment]
This exists but is a bit broken, see #1577

**Comment by samerton** [comment]
This is already possible if Minecraft integration is enabled - the user's ingame username is the "Username" field (with the Nickname field being the other).

In the view_topic template file, the variables that can be used to do this are `{$reply.mcname}` and `{$reply.uuid}` (the UUID variable can be used to build the avatar URL).

If you're looking for optional verification (ie users link their accounts at a later date) then this isn't possible yet.

**Comment by TheJoshue** [comment]
> If you're looking for optional verification (ie users link their accounts at a later date) then this isn't possible yet.
yes i wanted to ask about this

**Comment by Derkades** [comment]
That should be implemented as part of the verification system rework
