### ISSUE TITLE
Custom page bug

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2363]
I have a page for credits and for some reason it is bugged.
How it needs to look:
![image](https://user-images.githubusercontent.com/71085027/128621719-5b2b346c-e639-4ac6-b9b0-a5b5b138f520.png)
![image](https://user-images.githubusercontent.com/71085027/128621745-af44766b-1805-4cbf-b592-80b1f8a78f66.png)
How it looks:
![image](https://user-images.githubusercontent.com/71085027/128621732-017d7e42-7382-4b77-823a-e706156c7a7c.png)

**Comment by PadowYT2** [comment]
The problem is the text is not in the middle

**Comment by samerton** [comment]
Could you please send me a link to your custom page, or alternatively some example HTML (from the custom page editor's Source tab) so I can reproduce the issue?

**Comment by PadowYT2** [comment]
https://www.soff.ml/credits

**Comment by Derkades** [comment]
This makes sense if you insert inline images, it'll add to the text width. Maybe add a newline after each image, that way all images and the text are centered separately?
