### ISSUE TITLE
Site config not working

### ISSUE THREAD

**Issue by ReefSalty** [NamelessMC/Nameless#2364]
This is only happening on V2 but i dont know how to fix. i HAVE tried refreshing page.
<img width="1397" alt="Screenshot 2021-08-10 at 9 04 44 am" src="https://user-images.githubusercontent.com/74215798/128831360-5b366b62-20f8-4454-9026-ddb5aa97ccd8.png">

**Comment by samerton** [comment]
Does the file `core/config.php` exist? Does it contain any details inside?

**Comment by ReefSalty** [comment]
it exists however does contain anything

**Comment by samerton** [comment]
Apologies for the delay - if this occurs again you can try deleting the file `core/config.php` and running through the installer again.

Also, ensure the `core` directory is writeable for the PHP process so it can create the file itself.

If this still doesn't work and you're still experiencing issues, please feel free to re-open the issue.
