### ISSUE TITLE
Missing assets prevent 2FA login

### ISSUE THREAD

**Issue by relavis** [NamelessMC/Nameless#2366]
**Describe the issue**
If you attempt to log into your Nameless account that has 2FA enabled WHILE registration is disabled, you will be redirected to the login page with a notice that says the following:
<img width="421" alt="Screen Shot 2021-08-11 at 23 37 36" src="https://user-images.githubusercontent.com/25561419/129149485-db347d84-43cf-4ee1-9854-590fbd6c1a6f.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an account and enable 2-Factor Authentication on that account
2. Enter the StaffCP and disable registration
3. Log out of your 2FA-enabled account
4. Attempt to log back in

**Expected behaviour**
What were you expecting to happen?

I expect to be able to log in even though new registration is disabled.

**Screenshots**

**NamelessMC version (from StaffCP -> Overview)**
Running NamelessMC version 2.0.0-pr10

**Additional information**
Add more information about the problem if necessary.
PHP 7.4.9
PHP GD 7.4.9
PHP mbstring 7.4.9
PHP PDO 7.4.9
PHP cURL 7.4.9
PHP XML 7.4.9
PHP EXIF 7.4.9
PHP MySQL
core/config.php Writable
Cache Writable
Template Cache Writable

**Comment by relavis** [comment]
May be related to #1981

**Comment by Derkades** [comment]
You might have finally found an explanation for #2055

**Comment by Aberdeener** [comment]
Took a look at the codebase and can't see where this bug could be. Super confused

**Comment by samerton** [comment]
Might sound an unrelated question, but can you check your browser console (F12) to see if any assets are failing to load?

**Comment by relavis** [comment]
> Might sound an unrelated question, but can you check your browser console (F12) to see if any assets are failing to load during the 2fa process?

GET https://www.WEBSITEURL.com/custom/templates/Futurium/css/custom.css
[HTTP/3 404 Not Found 672ms]
GET https://www.WEBSITEURL.com/favicon.ico
[HTTP/3 404 Not Found 0ms]

**Comment by samerton** [comment]
There is currently an issue where 404 assets will clear the session required for 2fa - as a result it loses track of your login progress.

If these files can be added to prevent the 404, it should hopefully resolve the issue.

**Comment by relavis** [comment]
I added a blank file at https://www.WEBSITEURL.com/custom/templates/Futurium/css/custom.css and it solved the 2fa issue. Now running pre11 which fixed the favicon and I can log in!

**Comment by Aberdeener** [comment]
Not sure where to go from here..

**Comment by Derkades** [comment]
Ideally a 404 wouldn't break OTP login, I don't understand why it does anyway
