### ISSUE TITLE
Invalid POST contents, but why?

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2369]
request
```
{
  "tps": 20,
  "time": 1629086413890,
  "free-memory": 1503761216,
  "max-memory": 2139095040,
  "allocated-memory": 2139095040,
  "server-id": 1,
  "groups": [
    "youtube",
    "administrador",
    "twitch",
    "dueño",
    "magico",
    "mistico",
    "default",
    "cosmico",
    "tiktok",
    "moderador",
    "builder",
    "soporte"
  ],
  "placeholders": {},
  "players": {}
}
```
response
```
{
    "error": true,
    "code": 6,
    "message": "Contenido POST no v\u00e1lido.",
    "meta": null
}
```
From a discord support conversation. I don't see why it returns error code 6. I have verified their ServerInfoEndpoint.php file is up to date. So far only 1 person reported this issue, it seems to work fine for everyone else. 

Reportedly, a server with id 1 exists in StaffCP:
![staffcp screenshot](https://media.discordapp.net/attachments/471036966276825098/876817779104288799/unknown.png)

**Comment by Aberdeener** [comment]
Cannot recreate. Works fine for me 😕

**Comment by Derkades** [comment]
It is only a problem for this one user so I assume something went wrong with the upgrade (some files skipped during upload). It seems to be a common issue where users click "skip" instead of "retry" when a file fails to upload.
