### ISSUE TITLE
No PM Alerts for PM replies

### ISSUE THREAD

**Issue by Liphius** [NamelessMC/Nameless#237]
* What kind of issue is it (Question, Bug, etc.)  Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.9
* How would you describe the issue?  Whenever I receive a reply to a private message, there is no pop-up or the red '!' icon indicating that someone has replied to a private message. 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No as the message pop-up or the red ! icon does not come up.

**Comment by samerton** [comment]
Thanks for spotting this, it _should_ be fixed in c4d2563e30ae55453d5fbded4eb7a6b0c2015307
