### ISSUE TITLE
Call to a member function getHtml() on null

### ISSUE THREAD

**Issue by russianpeanut** [NamelessMC/Nameless#2371]
**Describe the issue**
Hello i got some errors when i click some things or i try to login, i cant login to staff cp or to the website

**To Reproduce**
Steps to reproduce the behaviour:
I cant login to staffCP, to the website
and also before i was unregistered i cant click on the forms module 

**Expected behaviour**
that i can login and click on things?

**Screenshots**
![fuckingCapture](https://user-images.githubusercontent.com/70594719/129926048-4e066f95-67a9-47ac-ab56-1e536f2e08af.PNG)

**NamelessMC version (from StaffCP -> Overview)**
I cant login to staffCP but it started after i updated to version 10 namelessMC

**Additional information**

**Comment by partydragen** [comment]
Don't know how you have managed to do that, Anyways its caused by you have captcha enabled without have a selected captcha type, You can disable it in /core/config.php then configurate it again on staffcp
