### ISSUE TITLE
Friendly URL and force https settings are broken

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#2373]
Friendly URL and Force HTTPS is broken

Caused by config file being updated 3 seperate times so only last value is being updated, file write is very slow so even adding a delay is not a solution

A solution that i did with my module is to change the set function to array instead

`$settings = array();
$settings['paypal_business/client_id'] = $_POST['client_id'];
$settings['paypal_business/client_secret'] = $_POST['client_secret'];

Config::set($settings);`

in Config class we can simply just foreach the array where key is the setting name

```
public static function set($settings) {
  ...
  foreach ($settings as $key => $value) {
  ...
  }

  return static::write($conf);
}
```

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/285ffecc2ad84ac8815c90209e291d892b689997
