### ISSUE TITLE
Profile face issue

### ISSUE THREAD

**Issue by russianpeanut** [NamelessMC/Nameless#2374]
**Describe the issue**
Peoples faces on profiles look weird

**To Reproduce**
Steps to reproduce the behaviour:
www.diamondlands.net and go on stafflist [tym] its only for some people

**Expected behaviour**
to be good

**Screenshots**
![facveCapture](https://user-images.githubusercontent.com/70594719/130263756-4c820e9a-0f01-4ccf-8840-5e9fe63e63f0.PNG)

**NamelessMC version (from StaffCP -> Overview)**
2.0.0-pr10

**Additional information**

**Comment by samerton** [comment]
It looks like these users might not have UUIDs set - can you edit the user in the StaffCP -> User Management -> Users tab and ensure the UUID is valid

**Comment by russianpeanut** [comment]
but its for like 50% of people and alot of people have cracked MC. it worked, its happend when i allowed and tunred off players onw avatar feature

**Comment by samerton** [comment]
The problem is that it's impossible to retrieve avatars for cracked accounts since there's no API for that - you can try changing the avatar provider (StaffCP -> Configuration -> Avatars) but unfortunately that's all that's available.

**Comment by partydragen** [comment]
it also happens if you have Custom avatars selected without having a default avatar set,

**Comment by russianpeanut** [comment]
its still happneing

**Comment by Derkades** [comment]
There are third party modules that allow retrieving avatars by name instead of uuid

**Comment by russianpeanut** [comment]
but why it worked and now it doesnt?

**Comment by samerton** [comment]
Nothing has changed within Nameless in this area - it might be the third party avatar provider which has changed
