### ISSUE TITLE
API error 0 when calling setDiscordRoles with empty role list

### ISSUE THREAD

**Issue by Sylensky** [NamelessMC/Nameless#2375]
**Describe the issue**
I have a very specific case of an group sync issue within the latest version.
On my ingame server i run discordsrv which syncs my ranks to my discord and from there nameless link fowards the role changes to my v2pr10 nameless homepage.
Thing is role remove and add requests are happening so fast that i think the homepage drops one event and returns the api error 0. For example: mc -> discord: role has been set, dc removes old role and adds new role. discord -> homepage: notices role remove event - executes it and drops the newly assigned role change. Interestingly manual(slow) reassigning a role on discord makes the syncing work properly.
Atleast thats what i observed down below on the logs of nameless link. Furthermore i didn't noticed any logs related to an issue with assigning the role.

**To Reproduce**
Steps to reproduce the behaviour:
1. setup group sync on nameless
2. setup the nameless link bot
3. setup discordsrv on the mc server
4. assign a new role to a player ingame and check discord logs and nameless-link logs
5. observe the role not getting assigned instead the default role is shown for that player

**Expected behaviour**
properly synced group

**Screenshots**
![image](https://user-images.githubusercontent.com/57076968/130334749-79a92918-e5ac-46a6-a8df-7c3b38c5b121.png)

**NamelessMC version (from StaffCP -> Overview)**
Running NamelessMC version 2.0.0-pr10
PHP 7.4.21 
PHP GD 7.4.21 
PHP mbstring 7.4.21 
PHP PDO 7.4.21 
PHP cURL 7.4.21 
PHP XML 7.4.21 
PHP EXIF 7.4.21 
PHP MySQL 
core/config.php Writable 
Cache Writable 
Template Cache Writable 

**Additional information**
Previously i was talking to derkades to embed a queue like system for role changes to improve race condition handling. Maybe this would also help in this particular case.

**Comment by Aberdeener** [comment]
@Derkades

**Comment by Derkades** [comment]
> Previously i was talking to derkades to embed a queue like system for role changes to improve race condition handling. Maybe this would also help in this particular case.

This has already been implemented: https://github.com/NamelessMC/Nameless-Link/issues/207. Weren't you already using the queue system? You should see the "checking user {} guild {} with {} items left in queue" at most once every two seconds.

**Comment by Sylensky** [comment]
Yes i waa using the queue system already but you told me to create a ticket on nameless itself as the issue in the screenshot seems to be a homepage issue rather then a nameless link issue.

**Comment by Derkades** [comment]
Yes, but since you are using the queue system I don't think this is a "race condition" or in any way related to role changes in quick succession. What happens if you only cause one change role event?

**Comment by Sylensky** [comment]
If i remove a role from a user on discord and assign a new one it works. That made me think it works when executed slowly enough.

**Comment by Derkades** [comment]
Can you check if the queue works, so if the "checking user" messages are at least 2 seconds apart?

**Comment by Sylensky** [comment]
Ok i did check if they are apart and that does look fine. Apparently during testing i noticed the API error 0 is actually occuring when the role of the user on discord got removed - so he has no roles at all. Below is what the link logs say:
![image](https://user-images.githubusercontent.com/57076968/130363735-c40948a3-fc4e-40b8-9b71-87605bdb54c9.png)

The logs when i assign him a new role look like this:
![image](https://user-images.githubusercontent.com/57076968/130363781-73828a5a-14f8-4c88-866e-e8fabe6cb8e9.png)

**Comment by Sylensky** [comment]
Additionally to provide more information i did some further testing. I did add a role to a player ingame via luckperms editor which triggers discordsrv to update the users role in discord which also triggers nameless link to update the users group on the homepage:
![image](https://user-images.githubusercontent.com/57076968/130371710-bc7ac1be-1d8b-4fe5-a09c-b27747c512e9.png)

From the logs it looks fine that the rank got assigned but on the group sync logs there is only the remove event listed:
![image](https://user-images.githubusercontent.com/57076968/130371731-e5f80b97-a6af-41b0-9799-25634732253c.png)
Unfortunately i couldnt find anything else in the logs.

**Comment by Derkades** [comment]
It works for me

**Comment by Sylensky** [comment]
I can confirm that this issue is resolved with the revamp of the endpoint.
