### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [NamelessMC/Nameless#2376]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by samerton** [comment]
Hi!

Thanks for creating this issue - I've quickly whipped up an initial security policy in 640bfbbd4b26acb7cc1c67f392408ae2539dc17a at https://github.com/NamelessMC/Nameless/blob/v2/SECURITY.md

The email is currently subject to change until we set something more official up, but I'll continue to monitor it until that happens

**Comment by zidingz** [comment]
Thanks!
