### ISSUE TITLE
Impossible to remove a group from myself.

### ISSUE THREAD

**Issue by Kydaix** [NamelessMC/Nameless#2377]
**Describe the issue**
Problem done on a new and clean installation of Nameless.
When I remove a group, from myself, an error occurs and the group is not removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the user manager and edit your profile.
2. Add any group to yourself and save.
3. Go back and edit your profile again.
4. Remove the previously added group and save.
5. See error.

**Expected behaviour**
The group should have been removed from the user.

**Screenshots**
https://user-images.githubusercontent.com/73427208/130448551-1ad13d6e-1406-420d-ac49-c1f2997bea5d.png
https://user-images.githubusercontent.com/73427208/130448563-d9122242-33b9-4b61-8d1d-492171bb3828.png

**NamelessMC version (from StaffCP -> Overview)**
NamelessMC 2.0.0-pr10

**Additional information**
I used Named Hosting, PHP 8.

**Comment by Derkades** [comment]
See #2296
