### ISSUE TITLE
Sorry, the placeholder has been configured successfully, but why don't my parameters

### ISSUE THREAD

**Issue by 56025192** [NamelessMC/Nameless#2387]
![image](https://user-images.githubusercontent.com/39239064/131146539-470f7c73-dbc7-47b2-b3cc-d13f939683f0.png)

**Comment by 56025192** [comment]
![image](https://user-images.githubusercontent.com/39239064/131204323-8a01cd87-d6cd-4daa-9392-778459d80baa.png)
The placeholder API is already installed

**Comment by Derkades** [comment]
But the player expansion probably isn't

**Comment by 56025192** [comment]
The plug-in was successfully updated

**Comment by Derkades** [comment]
You ran the ecloud command to install the *expansion* (not the same as plugin)?

**Comment by 56025192** [comment]
I don't know. After I updated the plug-in, there were no errors

**Comment by Derkades** [comment]
I didn't know there were errors before, are you saying this issue is resolved?

**Comment by 56025192** [comment]
是的，我已经解决了该问题，

**Comment by 56025192** [comment]
Yes, I have solved the problem
