### ISSUE TITLE
Allow disabling placeholders feature entirely

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2390]
This will hide the 'Placeholder' page in user settings for example, solving the FAQ "how do I remove this page?"

**Comment by samerton** [comment]
IMO this should be an on/off toggle switch instead

**Comment by partydragen** [comment]
Added in https://github.com/NamelessMC/Nameless/commit/060c497f921918d4d7abcf0675adabbbab4111d7
