### ISSUE TITLE
I hope the following features can be added in the new version

### ISSUE THREAD

**Issue by 56025192** [NamelessMC/Nameless#2393]
First, I want to visually edit + call placeholders on the new page I create

Secondly, I hope to call the UUID of offline players directly, otherwise the UUID of genuine users will be automatically obtained at this stage. If the forum cannot correctly obtain player information, the placeholder cannot be called

Third I hope to join the well-known payment platform (such as PayPal, Alipay, WeChat payment, etc.), and then open API so that developers can directly call.

Finally, you can add placeholders on the information page of the forum. In this way, by adding the guild plug-in, you can add the number of people, level and task completion number to each sub category

**Comment by 56025192** [comment]
Oh, by the way, I forgot to say that the integrated authme plug-in can change the game registration mechanism so that he can register his account through the web page

**Comment by Derkades** [comment]
Issues with many different suggestions are hard to manage so I'll split it up into multiple

> First, I want to visually edit + call placeholders on the new page I create
#2394 

> Secondly, I hope to call the UUID of offline players directly, otherwise the UUID of genuine users will be automatically obtained at this stage. If the forum cannot correctly obtain player information, the placeholder cannot be called
Do you mean offline player support for placeholders? Sorry, the plugin will not ever support servers not using Mojang UUIDs.

> Third I hope to join the well-known payment platform (such as PayPal, Alipay, WeChat payment, etc.), and then open API so that developers can directly call.
I don't think this is something NamelessMC should handle, are you talking about the resources module, a buycraft/craftingstore like platform or something else entirely?

> Finally, you can add placeholders on the information page of the forum. In this way, by adding the guild plug-in, you can add the number of people, level and task completion number to each sub category
Can you explain in more detail what you mean here? I don't understand what you mean with "information page of the forum" and "each subcategory"
