### ISSUE TITLE
Add tinygraphs integration

### ISSUE THREAD

**Issue by itzJOHv** [NamelessMC/Nameless#2401]
I suggest adding [tinygraphs](https://www.tinygraphs.com/) integration for default random profile pictures

**Comment by samerton** [comment]
Their website seems to be down for me, but random default profile pictures sounds like a nice idea

**Comment by Derkades** [comment]
Alternatively: https://en.wikipedia.org/wiki/Identicon https://sourceforge.net/projects/identicons/
