### ISSUE TITLE
Profile settings tab

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2403]
Make a feature to change the bot, I have a self hosted Nameless Link version
![Screenshot_20210909_083505](https://user-images.githubusercontent.com/71085027/132603469-1bb3fc73-bc59-44b6-b660-d1e0f28c576e.jpg)

**Comment by Derkades** [comment]
It should automatically change this, the bot sends its current username to the website on startup. If you are using the latest bot and website version this is a bug

**Comment by Aberdeener** [comment]
As well, please verify that it is not hard coded in your language file

**Comment by PadowYT2** [comment]
ok, it changed but another one (bug ig), the prefix doesnt change, i have # prefix and it is telling the ! prefix

**Comment by Derkades** [comment]
yep that is a known issue but we won't fix it, we'll migrate to slash commands very soon anyway

**Comment by Derkades** [comment]
nameless-link will use slash commands after the pr12 release

**Comment by PadowYT2** [comment]
kk
