### ISSUE TITLE
Bug in maintenance

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2405]
I found a bug in ```StaffCP > Configuration > Maintenance > Logs```, if you F12, in the console u can see some errors - using pre11

![screenshot](https://cdn.discordapp.com/attachments/765928327113867295/885828822166016030/unknown.png)

**Comment by samerton** [comment]
This won't cause any issues and the console messages can be safely ignored

**Comment by PadowYT2** [comment]
Then how about this? In notice logs/Warning logs it says that there is no logs
https://cdn.discordapp.com/attachments/765928327113867295/886133966791397396/unknown.png
But in Fatal logs/Other logs, it is blank
https://cdn.discordapp.com/attachments/765928327113867295/886134069480550421/unknown.png
