### ISSUE TITLE
Emoji design

### ISSUE THREAD

**Issue by BrayaanPS** [NamelessMC/Nameless#2413]
Could there be a possibility to add these emoji designs?
https://mutant.revolt.chat/

**Comment by Derkades** [comment]
Is this "fork" by revolt.chat any different from the original project? https://mutant.tech/demo/

**Comment by Derkades** [comment]
We switched to twemoji https://github.com/NamelessMC/Nameless/commit/3bf7267f57c85470015f6e8f34eb5bc74c73c44d
