### ISSUE TITLE
Server Status doesn't work with SRV records.

### ISSUE THREAD

**Issue by Slddev** [NamelessMC/Nameless#2424]
### Describe the issue

The server status always says offline when I leave the server port blank. According to the little tip box that to make it work with SRV records I have to leave it blank. I tried it and it didn't work. I also tried using the Query feature but still didn't work. Then I tried placing the port in to the Server Port box, and it worked. Problem is, it looks a bit ugly with the port. That's why I wanted to use an SRV record.

### NamelessMC Version

2.0.0-pr11

### To Reproduce

1. Link a Minecraft Server with the integration. (Make sure that the SRV record is properly working, use mcsrvstat to check if it is working)
2. Leave the server port blank.
3. Check the status.
(If it isn't working, try placing the port. Check if it works.)

### Expected Behaviour

It is supposed to show that the server is online with player count and list. 

### Screenshots

With the port:
![image](https://user-images.githubusercontent.com/74999267/134832492-01d415b0-658d-4b9d-b926-4522cfd1b2d5.png)

Without the port:
![image](https://user-images.githubusercontent.com/74999267/134832562-9e2daba3-21d7-460b-acf2-b9bdd9a74ce3.png)

### Additional Information

No errors are shown on query errors.

**Comment by PadowYT2** [comment]
i cant reproduce it, can you show how did you create the srv record

**Comment by Derkades** [comment]
The SRV record seems fine, other ping APIs work: https://api.minetools.eu/ping/smp.sapmc.ga (and as expected, https://api.minetools.eu/ping/smp.sapmc.ga/25565 doesn't work)

**Comment by Slddev** [comment]
> i cant reproduce it, can you show how did you create the srv record

Through Cloudflare:
![image](https://user-images.githubusercontent.com/74999267/134995822-a49bd451-8014-4f22-bae0-542c443b386a.png)
(The target is an A record to my server host)

**Comment by PadowYT2** [comment]
wait, why do you need an a record

**Comment by PadowYT2** [comment]
oh welp nvm, it is a feature bug...?

**Comment by Derkades** [comment]
Does this happen with both the internal and external query system?

**Comment by Slddev** [comment]
> Does this happen with both the internal and external query system?

Both. 

But it doesn't work at all in internal.

**Comment by Slddev** [comment]
Fixed. Something was wrong with Nameless hosting. Switched to NamedHosting and it was fixed.
