### ISSUE TITLE
Broken CSS on exception page

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2429]
### Describe the issue

1. When the directory is too long, it would just ignore the box
2. For some reason `{$item.icon} {$item.title}` makes a link

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1.
1) Make the directory big
2) Make an error somewhere in the template
2.
1) Make an error with `{$item.icon} {$item.title}`

### Expected Behaviour

1. It wouldn't ignore the box outline and will moved down
2. It wouldn't be a link

### Screenshots

![image](https://user-images.githubusercontent.com/71085027/135245195-59b99b3f-5a09-4597-964f-2e93d414c206.png)
![image](https://user-images.githubusercontent.com/71085027/143552358-9b7b24d1-721f-4990-b061-26df29ae7592.png)

**Comment by Aberdeener** [comment]
The overflowing text was solved a while ago when I made the container wider, that commit will escape any HTML.
I couldn't get the exact same error as you, but I was able to recreate it close enough. Thanks!
