### ISSUE TITLE
Status banner

### ISSUE THREAD

**Issue by jesseke55** [NamelessMC/Nameless#243]
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.9.  
**How would you describe the issue?** The minecraft status banner won`t load
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have a .mp4 to view it: https://drive.google.com/file/d/0Bzi7TczKmNTucHloYTJXam8xSG8/view?usp=drivesdk
**Do you have an idea how or where the issue occurs?** I think that it has to do something with my https or the file is not benig created.

**Comment by samerton** [comment]
Are you using the internal or external Minecraft server query?

**Comment by jesseke55** [comment]
Internal

**Comment by jesseke55** [comment]
?

**Comment by samerton** [comment]
I haven't had much chance to look into your issue at the moment sorry, I'll let you know about any updates :)

**Comment by jesseke55** [comment]
Since reinstalling it it says now on the homepage there are players online without a number

**Comment by samerton** [comment]
Should be fixed in 6b96c8d721a8d2a0d363c4cc68197a2200516a85, thanks for spotting this.
