### ISSUE TITLE
Add report_origin field to reports

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#2440]
### Describe the feature

Add origin field to createReport API query

This would allow distinguishing between report origin, ie Minecraft via the plugin, Discord via the bot

**Comment by Derkades** [comment]
Wasn't the original goal of this issue to have more origins, like 

- Website
- API
- API, minecraft
- API, discord

Where an API client would supply the origin (but not allowed to set origin to "website").

> This would allow distinguishing between report origin, ie Minecraft via the plugin, Discord via the bot

Currently it's not possible to distinguish between Minecraft reports and Discord reports
