### ISSUE TITLE
404 After Installing

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#246]
* After installing the website, I get a 404 error.
* 1.0.9
* 404 or website bug.
* No.
* I have no idea.
* Running Ubuntu 14.04 on a VPS.

**Comment by samerton** [comment]
Is Nameless installed in the web root (ie /var/www/html, or a subfolder)?

If it's in a subfolder, it will need moving to the web root.

If it's already in the web root, [this](http://askubuntu.com/a/48363) should help.

**Comment by ThomasIO** [comment]
It's installed on the web root.

**Comment by ThomasIO** [comment]
I re-installed the forums, and now it's just a blank page after the installation.

**Comment by samerton** [comment]
You'll need to make sure the **cache** directory within the web root is writable, eg:

`sudo chown -R www-data:www-data /var/www/html/cache`

(depends on whether your web root is /var/www/html or /var/www, you'll need to change the path accordingly)

**Comment by ThomasIO** [comment]
Now the page is very distorted.

http://endertime.com

**Comment by samerton** [comment]
Looks like your CSS is missing, can you reupload all themes (from the styles/themes folder) to see if it helps?

**Comment by ThomasIO** [comment]
Still distorted.

http://endertime.com

**Comment by samerton** [comment]
I'm not sure what could be happening, this isn't something I've seen before. If you check the [main css file](http://endertime.com/styles/themes/Bootstrap/css/bootstrap.min.css), it doesn't seem to exist.

Can you take a screenshot of your **styles/themes/Bootstrap** folder for me?

**Comment by ThomasIO** [comment]
http://imgur.com/ody8hdN > bootstrap folder
http://imgur.com/bxxE750 > js folder
http://imgur.com/hhMgU3W > fonts folder
http://imgur.com/5XwE4zX > css folder

**Comment by samerton** [comment]
Everything seems to be in order, and for some reason the core CSS is loaded without issues. Can you check the www-data user/group has permission to read the subfolders of the styles/themes folder?

If you head straight to admin/styles in your web browser, and change the theme (might be tricky without CSS), does it help at all?

**Comment by ThomasIO** [comment]
I did all of that.The website is still distorted.

http://endertime.com

**Comment by samerton** [comment]
I'll have to take a look at some point tomorrow, unfortunately at the moment I don't know what could be happening, this isn't something I've experienced with Apache + Ubuntu 14.04.

Can you paste the contents of /var/www/html/.htaccess?

**Comment by ThomasIO** [comment]
Options +FollowSymLinks
  RewriteEngine On

  RewriteCond %{SCRIPT_FILENAME} !-d
  RewriteCond %{SCRIPT_FILENAME} !-f

  RewriteRule ^.*$ ./index.php

RewriteEngine On

RewriteCond %{REQUEST_URI} [A-Z]
RewriteRule ^(.*)$ ${tolower:$1}

**Comment by samerton** [comment]
It looks like the second half of the file could be causing the issue. It's trying to redirect the css call to the Bootstrap directory to a bootstrap directory (all lowercase), which doesn't exist.

It's not part of the default .htaccess file, has it been added manually, and can it be removed so the file looks like [this](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess)?

**Comment by ThomasIO** [comment]
You fixed it! Thanks!
