### ISSUE TITLE
Option to disable cookie consent popups

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2463]
### Describe the feature

Websites that do not use tracking/non-essential cookies should be able to disable the annoying popup, it is not legally required.

**Comment by Aberdeener** [comment]
And whether they’ve closed an announcement

**Comment by samerton** [comment]
Cookie consent moved to new module in 06b97b7b8624db46f068461ec7a44500f7c8cc4c

It's now possible to disable the module to disable cookie consent
