### ISSUE TITLE
Resend Activation E-Mail error

### ISSUE THREAD

**Issue by PanetiX** [NamelessMC/Nameless#2464]
### Describe the issue

Hey, i get this error when i want to resend a email verification mail:

Call to undefined method Email::formatEmail()
(File:/modules/Core/includes/emails/register.php)

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Go to Edit User Profile
2. Click on Edit
3. Click on Resend User Acivation Email

### Expected Behaviour

That a Activation Email will be send 

### Screenshots

https://imgur.com/K6jBJqA

**Comment by samerton** [comment]
Hi,

Can you please ensure the file `core/classes/Email.php` is up to date (pre-12) https://raw.githubusercontent.com/NamelessMC/Nameless/v2.0.0-pr12/core/classes/Email.php
