### ISSUE TITLE
Template Dark Mode only works for unregistered Users

### ISSUE THREAD

**Issue by NotJanLive** [NamelessMC/Nameless#2466]
Hello,
im currently working on my forum and it seems like the dark mode only works for user, which are not registered. I enabled the Dark Mode through StaffCP>Layout>DefaultRevamp>Settings. In the Profile Settings of the Users you also cant enable the Dark Mode? How can i fix this so that everyone sees the Dark Mode?

**Comment by Derkades** [comment]
Seems to work as intended now, am I missing anything?

**Comment by partydragen** [comment]
Misunderstanding of the issue, Issue reopened
