### ISSUE TITLE
Donor store

### ISSUE THREAD

**Issue by jesseke55** [NamelessMC/Nameless#247]
**What kind of issue is it (Question, Bug, etc.)?** Question.
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.9.  
**How would you describe the issue?** Why doesn't display the product description not completly
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](https://drive.google.com/file/d/0Bzi7TczKmNTuZVNsYUYzSEd0VGc/view?usp=drivesdk)  
**Do you have an idea how or where the issue occurs?** I don`t know.
I'm using minecraftmarket btw

**Comment by Schwertspize** [comment]
Have you pressed the sync store button after you changed your minecraftmarket settings?

**Comment by jesseke55** [comment]
Yes but it shows all the time one line of the description whilst the description of the package is bigger and I have autosync set to every 5 mins

**Comment by samerton** [comment]
If you navigate to http://www.minecraftmarket.com/api/1.5/API_KEY/gui (replacing API_KEY with your key), do the package descriptions show up in full?

**Comment by jesseke55** [comment]
No...

**Comment by samerton** [comment]
Sounds like an issue with the Minecraft Market API instead of Nameless itself, it might be worth contacting the Minecraft Market devs.

**Comment by samerton** [comment]
I'm going to mark this as closed, as it's a Minecraft Market API issue as opposed to a Nameless issue.
