### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by LeonusDH** [NamelessMC/Nameless#2476]
Is this creation able to generate UUIDs, in Hyphenated hexadecimal format, or just Hexadecimal?

**Comment by Derkades** [comment]
Is this a question about the API? The API accepts both trimmed and full UUIDs, but always returns trimmed UUIDs (no dashes)

**Comment by LeonusDH** [comment]
It's a pity. The fact is that there is a minecraft launcher that does not accept Hexadecimal. Doubt the developer of that launcher, add support, UUID without a dash. Therefore, I hoped that it might be possible, instead of Hexadecimal, to use Hyphenated hexadecimal. It's not meant to be.

**Comment by Derkades** [comment]
It's trivial to add dashes to UUIDs returned by the API, the [Nameless Java API](https://github.com/NamelessMC/Nameless-Java-API) does this too.

**Comment by LeonusDH** [comment]
I didn't say anything about the API. I was wondering if Nameless could generate a UUID, no dash.

**Comment by Derkades** [comment]
If I understand you correctly, you want this for compatibility with a third party application. How does that third party application interact with NamelessMC if it's not through the API?

**Comment by LeonusDH** [comment]
Third party app, not affiliated with NamelessMC ... Almost. It's about the database. The launcher refers to it, with a request to the table, with data, among which is the UUID. I personally, did not use NamelessMC, and decided to ask a question based on the error that a user using NamelessMC approached and decided to bind a launcher to it (a third-party application, if you like).
Thank you for your reply.
