### ISSUE TITLE
getAnnouncements API returns raw HTML, not announcements .JSON

### ISSUE THREAD

**Issue by CatkinFox** [NamelessMC/Nameless#2477]
### Describe the issue

When using the API it is not possible to fetch a list of the latest announcements.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Enable API
2. Visit the getAnnouncements endpoint (domain.com/api/v2/  API KEY  /getAnnouncements
3. Raw HTML is displayed, not the JSON of announcements

### Expected Behaviour

A json to be returned [like shown in the docs](https://docs.namelessmc.com/en/api-documentation#:~:text=returns%20all%20announcements%20in%20json.)

### Additional Information

I tested this on namelesshosting.com after I attempted to solve this issue myself to see if it could have been my hosting, however this does not seem to be the case.

**Comment by Aberdeener** [comment]
Thanks for the issue report.
This has been fixed since pre12!

However, can you please send the HTML that is returned to you instead in a pastebin link? (removing any sensitive info as needed)

**Comment by CatkinFox** [comment]
If has been fixed since pre12, why is it an issue for me since that is the version I am running? This issue is also present on your own hosting managed hosting namelesshosting.com.

I have saved the [RAW HTML that is shown in my browser here](https://blackcloud.blackfox.it/s/6nME85bkFRrgDPR)

My server settings:
- PHP 7.4.24 ✔
- PHP GD 7.4.24 ✔
- PHP mbstring 7.4.24 ✔
- PHP PDO 7.4.24 ✔
- PHP cURL 7.4.24 ✔
- PHP XML 7.4.24 ✔
- PHP EXIF 7.4.24 ✔
- PHP MySQL ✔
- core/config.php Writable ✔
- Cache Writable ✔
- Template Cache Writable ✔

**Comment by Aberdeener** [comment]
I said “since pre12”, meaning it has been fixed after pre12 was released :)
Note: Namelesshosting is not affiliated with namelessmc directly.

Thanks for the html link, I’ll take a look soon

**Comment by Aberdeener** [comment]
Can you send the contents of the file core/classes/Announcements.php ?

**Comment by CatkinFox** [comment]
[Here is that file here](https://blackcloud.blackfox.it/s/JWnrbi2Txsz6CwC)

Thanks for looking into this. So the latest update was pre12, which I beleve I just updated to correctly, this issue shall be solved in pre13? Or am I not getting that right?
