### ISSUE TITLE
How do I setup SMTP email?

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#248]
### Template:
* Question
* 1.0.9
* Must have for professionals.
* No.
* Not an issue.

**Comment by jesseke55** [comment]
There is a guide in core/email.php

**Comment by samerton** [comment]
If it's an SMTP email server you're looking to set up, the steps laid out in [this post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-67#post-1017639) should help you out. 
If you want to use Gmail, the steps [here](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-70#post-1036444) will help.

Once you've done that, you can disable the built in mail function (which will then use SMTP) in the AdminCP -> Core -> Email tab.

**Comment by samerton** [comment]
I'll mark this as closed as hopefully the documentation in the previous reply helps, if you still have a question feel free to re-open.
