### ISSUE TITLE
Follower System

### ISSUE THREAD

**Issue by DrizzyySP** [NamelessMC/Nameless#2480]
### Describe the feature

**He could add a follower system**, meaning (logged in) users could **click on a button that would be on another user's profile** to start following him. You can also add the **count of followers** the user has to their profile and in the information that appears when viewing a topic. Visual example:

- **Button:** https://i.imgur.com/prQcoHm.png
- **Profile:** https://i.imgur.com/mRgb48W.png

**Comment by Aberdeener** [comment]
What would the actual functionality look like in your vision?

**Comment by DrizzyySP** [comment]
As in other media, this can be a very useful tool to engage the forum... Providing a certain "competitiveness" in relation to the number of followers of each user.

**Comment by Derkades** [comment]
See also https://github.com/NamelessMC/Nameless/discussions/2146

**Comment by DrizzyySP** [comment]
In my case it's a little different, it could be what you sent and more what I said. A combination of the two suggestions.
