### ISSUE TITLE
Updating name of a template

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2487]
### Describe the issue

Updating name of a template doesn't change, but other things does

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Open `template.php` in any template
2. Change 'name'

### Expected Behaviour

It should rename

### Additional Information

Not a hosting issue (tried localhost and namedhosting)
Video - https://cdn.padow.ru/Jf3U.mp4

**Comment by partydragen** [comment]
it using the folder name, renaming templates are not really supported as then it will also generate it as a new template in database

**Comment by PadowYT2** [comment]
So, you can't put any <img> tags in there, when you try to do that, it breaks the whole template

**Comment by Derkades** [comment]
An image in the template name? I don't think you should try to do that

**Comment by PadowYT2** [comment]
welp ok, thanks for answers
