### ISSUE TITLE
PHP errors when sending announcements to the MC

### ISSUE THREAD

**Issue by RobiNN1** [NamelessMC/Nameless#2491]
### Describe the issue

C:\laragon\www\nameless\modules\Core\includes\endpoints\ServerInfoEndpoint.php(114): Return value of ServerInfoEndpoint::updateGroups() must be of the type array, null returned

C:\laragon\www\nameless\core\classes\Database\QueryRecorder.php(85) 8: Undefined offset: 1

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Use the latest version of plugin and Nameless from Github and create any announcement. 

PHP 7.4.21

### Expected Behaviour

There should be no errors.

**Comment by Aberdeener** [comment]
Thanks so much for the report, I've fixed it in 5933939.
Apply the changes in that commit to your files and you should be good to go 🚀

**Comment by RobiNN1** [comment]
The second error is not fixed.

**Comment by RobiNN1** [comment]
Another errors that occurs when sending data to the plugin

C:\laragon\www\nameless\core\init.php(588) 8: Undefined index: checked
C:\laragon\www\nameless\modules\Cookie Consent\classes\CookieConsent.php(29) 8: Undefined index: colours
C:\laragon\www\nameless\modules\Cookie Consent\classes\CookieConsent.php(47) 8: Undefined index: theme
C:\laragon\www\nameless\core\classes\Core\Cookie.php(30) 8: Undefined index: cookieconsent_status

**Comment by Derkades** [comment]
> Another errors that occurs when sending data to the plugin
> 
> C:\laragon\www\nameless\core\init.php(588) 8: Undefined index: checked C:\laragon\www\nameless\modules\Cookie Consent\classes\CookieConsent.php(29) 8: Undefined index: colours C:\laragon\www\nameless\modules\Cookie Consent\classes\CookieConsent.php(47) 8: Undefined index: theme C:\laragon\www\nameless\core\classes\Core\Cookie.php(30) 8: Undefined index: cookieconsent_status
> 
> C:\laragon\www\nameless\modules\Core\pages\api\v2\index.php(141): Argument 1 passed to Nameless2API::validateParams() must be of the type array, null given, called in C:\laragon\www\nameless\modules\Core\includes\endpoints\ServerInfoEndpoint.php on line 13

#2492 #2493 #2494
