### ISSUE TITLE
API type error

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2494]
```
modules\Core\pages\api\v2\index.php(141): Argument 1 passed to Nameless2API::validateParams() must be of the type array, null given, called in C:\laragon\www\nameless\modules\Core\includes\endpoints\ServerInfoEndpoint.php on line 13
```

**Comment by Aberdeener** [comment]
Interesting? Not sure how `$_POST`  could ever be null. Never had this issue myself.

**Comment by RobiNN1** [comment]
Just open `http://site.host/index.php?route=/api/v2/CXho4l8mYZputPRFUfSeszTQDK32nAMO/serverInfo`

**Comment by Aberdeener** [comment]
Oh you're viewing a `POST` endpoint in a browser.
Not exactly the intentional use case...

I'll add a check that the request methods match to fix this. Thanks

**Comment by Derkades** [comment]
Maybe return HTTP status code 405 to be somewhat compliant?

**Comment by Aberdeener** [comment]
Thanks, added here: 6746b2fa305682aef65897db64c1075ec540485e
