### ISSUE TITLE
Forums without a parent don't show up.

### ISSUE THREAD

**Issue by kukelekuuk00** [NamelessMC/Nameless#25]
http://i.imgur.com/qrsE3iQ.png
http://i.imgur.com/GZUIlsF.png

In my setup it's:
General, which contains General Discussion and Announcements. And General Discussion containing Test.

General has no parent, yet it doesn't show up in the forum page.

**Comment by samerton** [comment]
This system will be changed in 1.1 when "proper" forum categories are implemented.

**Comment by TheMeq** [comment]
Is there a work around for this, because this is the deal breaker. If forums don't work, this is like, half the website missing.
