### ISSUE TITLE
Setting up Buycraft.

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#250]
How do I setup Buycraft?

**Comment by ThomasIO** [comment]
Also, how do I rename the donations tab? For example, renaming it to "Shop".

**Comment by Schwertspize** [comment]
Please, look in already closed issues. Hell, why are they public, so Somerton has to answer every question again and again?

**Comment by samerton** [comment]
You can setup Buycraft by configuring the "Donate" addon (AdminCP -> Donate, if none appear simply click "Install Addon" and then "Scan"). You'll need your server key to input into the API key field, which you can obtain in the Webstore -> Servers tab of the Buycraft control panel.

You can rename the donate tab by replacing the language values in the file addons/Donate/language.php

**Comment by ThomasIO** [comment]
How can I change the link from "/donate" to "/shop".

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/issues/236#issuecomment-226881641 should help with that.

**Comment by ThomasIO** [comment]
Thanks.

**Comment by ThomasIO** [comment]
The page is blank.

**Comment by ThomasIO** [comment]
http://endertime.com/shop

**Comment by ThomasIO** [comment]
Well, it doesn't show everything it's supposed to. For example, items in the shop.

**Comment by samerton** [comment]
Have you run the synchronisation script for the first time? You can do so by visiting yoursite.com/admin/addons/?action=edit&addon=Donate&do=sync

**Comment by ThomasIO** [comment]
I got it. Never mind, thanks.
