### ISSUE TITLE
Remove always present cookie thing

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2502]
![image](https://user-images.githubusercontent.com/15892014/142873490-7469d9d0-5246-4da6-a3bc-0b02c18b8889.png)
![image](https://user-images.githubusercontent.com/15892014/142873560-1cc7cefc-78f5-42b8-9fd4-b7cad7290d63.png)
In my opinion this is unnecessary, the footer already contains a link to open cookie settings if accidentally dismissed.

**Comment by samerton** [comment]
This can be done by adding `display: none` to the element `.cc-revoke`

**Comment by supercrafter100** [comment]
Newest cookie system doesn't have this issue anymore.
