### ISSUE TITLE
Status about what's happening in a post!

### ISSUE THREAD

**Issue by Aadi-mone** [NamelessMC/Nameless#2504]
### Describe the feature

Just adding a status to the forums and making the theme and things simple for free users :)
here is an example:
![454444](https://user-images.githubusercontent.com/87631878/142906960-6d94da8d-48cc-4b9d-b3d6-53114e760c41.PNG)

**Comment by Derkades** [comment]
Are you requesting open/closed status for topics, like GitHub issues? If so, maybe you can achieve this using labels, for example by creating a 'Solved' or 'Closed' label.

**Comment by Aadi-mone** [comment]
well that's not, idk how to say it.
but when we have a message at the bottom of the post, it wud be more "CLEAN"

**Comment by Aberdeener** [comment]
Why couldn't whoever is closing the thread just make a comment that the thread is closed, and then close it?

**Comment by Aadi-mone** [comment]
you here and there?!?!

**Comment by Aadi-mone** [comment]
> Why couldn't whoever is closing the thread just make a comment that the thread is closed, and then close it?

Yes, but it doesn't have a label bruh.... 
and look at the image that i've attached

**Comment by Aberdeener** [comment]
I don't see any labels on your screenshot

**Comment by Aadi-mone** [comment]
well let me zoom it for you

![789465](https://user-images.githubusercontent.com/87631878/143278551-0412b1b2-d381-4eef-9363-6dfd0e4025c7.PNG)

now don't say that i don't see the red line xD

**Comment by partydragen** [comment]
Forum only have ability to Lock the thread, staff can even still reply  and people may just private thread
