### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by enno123** [NamelessMC/Nameless#2505]
### Describe the feature

How about implementing several Webook events? 

Like when someone registers or when someone is reported/warned/banned.

Or that when you create an announcement it is also sent via webhook.

**Comment by Derkades** [comment]
Registration webhook already exists I think, it's what we use in our Discord server:
![image](https://user-images.githubusercontent.com/15892014/143140168-85fc427f-7a9c-4118-8df4-63cd9aa02e54.png)

Don't know about the other types.

**Comment by Aberdeener** [comment]
Thanks for the suggestions!

> registered

As Derk said, this is already implemented.

> reported

This was added in #2467 

Warns, bans and announcement creation are great ideas!
I will add these before the next update.

**Comment by Aberdeener** [comment]
Thanks! All three of your suggestions have been added.
