### ISSUE TITLE
Drop jQuery dependancy in the Forum module

### ISSUE THREAD

**Issue by graphiteisaac** [NamelessMC/Nameless#2507]
### Describe the feature

Have recently been developing a theme for Nameless and I've been aiming to drop jQuery entirely but it's built into some modules so I've gone in and removed it, thought it would be useful to suggest and try to contribute to.

First time trying to contribute to open source so I apologize if I'm doing anything wrong!

**Comment by Derkades** [comment]
Did you accidentally open an issue instead of PR?

**Comment by graphiteisaac** [comment]
Indeed I did, sorry lol I am a bit of an idiot.
