### ISSUE TITLE
Editing fields doesn't redirect to the right page

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2509]
### Describe the issue

When you edit a custom field in staffcp, it will redirect to `/panel/` instead

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Go to `StaffCP > Configuration > Custom Profile Fields`
2. Create a field
3. Edit the field

### Expected Behaviour

It should redirect to `/panel/core/profile_fields/` instead

### Additional Information
https://user-images.githubusercontent.com/71085027/143685672-4546e660-736c-466f-984d-40fe7a10c97a.mp4

**Comment by Aberdeener** [comment]
Thank you for the bug report :)
