### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by Aadi-mone** [NamelessMC/Nameless#2510]
### Describe the feature

@Aberdeener yoo cool boi

can you do one more thing?
the warning system in punishments does nothing, please add a feature like if he's warned he can't create or reply to a topic.

**Comment by Aadi-mone** [comment]
and i don't know why @Aberdeener  is too cool ¯\_(ツ)_/¯

**Comment by PadowYT2** [comment]
Warning is a warning tho, too many warns, ban/ban ip (manually)
"please add a feature like if he's warned he can't create or reply to a topic.", create a role, go to forums in staffcp, and deny the role to reply/create

**Comment by Aadi-mone** [comment]
well, then why am I requestion it for the ban?
in real its easier on other platforms, but they are not for Minecraft, and going to staff cp itself is a hard task where other systems can just warn them with the reason by just a click **`¯\_(ツ)_/¯`**
