### ISSUE TITLE
Set email sender to website name

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2511]
So email clients show `My Website <noreply@mywebsite.com` instead of `noreply@mywebsite.com`

**Comment by samerton** [comment]
Is this using PHPMailer? This should already be the case: https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Core/Email.php#L92-L93

**Comment by Derkades** [comment]
I don't think the website used phpmailer, the email had a header `X-Mailer: PHP/7.4.26`. The 'From' header didn't contain a name.

**Comment by Aberdeener** [comment]
Currently the "from name" is set to whatever the user sets it as in the email configuration page.
