### ISSUE TITLE
Uncaught SmartyException

### ISSUE THREAD

**Issue by MC3TITAN** [NamelessMC/Nameless#2514]
![Screenshot 2021-11-28 142659](https://user-images.githubusercontent.com/75459343/143784677-ba0c4b01-6f2d-4a5e-a0c9-b961ee07b091.png)

**Comment by supercrafter100** [comment]
Please provide the full stacktrace. We can't do much with this information...

**Comment by MC3TITAN** [comment]
![Screenshot 2021-11-28 143226](https://user-images.githubusercontent.com/75459343/143784872-395f7641-483b-42d2-8191-892c7e381674.png)

**Comment by supercrafter100** [comment]
@MC3TITAN do you have a discord account by any chance? Its a lot easier than having to help you via github issues. You can find the namelessm discord server here: https://discord.gg/jpVZ2MAwqq

**Comment by MC3TITAN** [comment]
okay ill post it there

**Comment by PadowYT2** [comment]
Maybe mind closing this?
