### ISSUE TITLE
Remove UUID field from register endpoint

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2516]
### Describe the feature

Currently, the `uuid` field is required but only if Minecraft integration is enabled. With the new integration system, I think the following post body makes more sense:

* `username` (same as before)
* `email` (same as before)
* ~~`uuid` removed~~
* integrations (json object, may contain none, one, or multiple integrations)
  * <integration name> (like "minecraft" or "discord"):
    * `id` (uuid / discord id / something else)
    * `name` (minecraft username / discord username / something else)
    
Example, registering from Discord:
```json
{
  "username": "Derkades",
  "email": "me@example.com",
  "integrations": {
    "discord": {
      "id": "183954832485253121",
      "name": "Derkades#9976"
    }
  }
}
```
Example, registering from Minecraft:
```json
{
  "username": "Derkades",
  "email": "me@example.com",
  "integrations": {
    "minecraft": {
      "id": "09948878-fe20-44e3-a072-42c39869dd1f",
      "name": "Derkades"
    }
  }
}
```

**Comment by partydragen** [comment]
Complete

i named it id and username

**Comment by Derkades** [comment]
Documentation, Java API and spigot plugin have been updated
