### ISSUE TITLE
How do I edit the homepage?

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#253]
How do I edit the homepage picture and make blog posts?

**Comment by samerton** [comment]
You can replace **core/assets/img/background-1920x828.jpg** with an image of your choice to change the background image.

As for blog posts, you need to create a news forum and then edit it so the "Display threads as news on front page" option is true. Any topics you create in this new news forum will then appear on the front page.

**Comment by ThomasIO** [comment]
How do I change the "Staff Applications" to have a different name?

**Comment by ThomasIO** [comment]
(Not the link. The name.)

**Comment by samerton** [comment]
You can change line 338 of **styles/language/EnglishUK/language.php** to text of your choice.
