### ISSUE TITLE
Two people can not have the same Nickname.

### ISSUE THREAD

**Issue by Skizzles** [NamelessMC/Nameless#2531]
### Describe the issue

When creating an account two people can not be nicknamed the same. For example "Sami" can only be used by one person.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Have a user registered with the current nickname
Attempt to register a second user with the same Nickname
States "Your username or email address already exists"

### Expected Behaviour

Ideally people should be able to use the same nickname as its common for people to use their first name and plenty of people have the same first name.

### Screenshots

![image](https://user-images.githubusercontent.com/30563757/145684890-3a60ce99-7729-4c39-b72b-039e173ebb97.png)

### Additional Information

No further information

**Comment by samerton** [comment]
Unfortunately I don't think this will be changing - since nicknames are displayed across the forum I think it would get confusing if multiple people are posting with the same nickname

**Comment by Skizzles** [comment]
> Unfortunately I don't think this will be changing - since nicknames are displayed across the forum I think it would get confusing if multiple people are posting with the same nickname

Ah that's understandable, maybe a way to state that the nickname is already in use?

**Comment by BaxAndrei** [comment]
Minecraft does not allow multiple users to have the same username. And it would also be confusing. I'm sure these cases are rare, most users have their own nicknames. (In my oppinion it is bad to use real information on web).
