### ISSUE TITLE
Domain redirect. 

### ISSUE THREAD

**Issue by Aadi-mone** [NamelessMC/Nameless#2538]
### Describe the feature

I am going to change my page to a custom domain, so if many people know and will go to the old domain which was:
https://sami-logam.nhforums.net/ and I'm going to change that to a custom domain, I've tried it, so when I do it the subdomain isn't accessible and says "404" instead of it, make it redirect to the custom domain which we have linked?
is that possible?

~ Kind Regards.

**Comment by partydragen** [comment]
This is not NamelessHosting, Anyways i answered your ticket and i close this issue
