### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by AarushKiller** [NamelessMC/Nameless#2539]
### Describe the issue

Hi I am running centos 7 

[ERROR]: allow_url_fopen is blocked in your php.ini file. Please set this to 1 to continue with the Easy Installer. This error pops up when I try to use easy-installer. Where is the php.ini file? I am in etc/php.d but no files are in there

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Going to webserver

### Expected Behaviour

It should just load but didnt

### Screenshots

![image](https://user-images.githubusercontent.com/67967009/147031738-18fb0faa-8912-422e-8ad8-79dc31974f8c.png)
![image](https://user-images.githubusercontent.com/67967009/147031767-59b5f821-5655-4dc9-bf4c-180560c3943b.png)

**Comment by Derkades** [comment]
If you can't figure out the location of php.ini you could use the regular install method instead
