### ISSUE TITLE
Contents of message removed if summiting with error / refresh

### ISSUE THREAD

**Issue by C41vn** [NamelessMC/Nameless#2540]
### Describe the issue

The title really describes the issue.

If you write a reply, make a thread and if it goes past the default limit or if there's an error, all of what you wrote goes away without anyway to get it back.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Make a thread, or reply
Write some stuff,
Sit around for a second or few if you want,
Refresh or summit under any conditions that may cause an error 

### Expected Behaviour

It should save the message with the formatting and such so you don't lose a lot of work.

**Comment by PadowYT2** [comment]
This is not a bug, but rather an enchanment

**Comment by Derkades** [comment]
I would disagree, other forms do keep their contents when submission returns a validation error

**Comment by partydragen** [comment]
Content is already being added back, If you have this issue then the problem is with your template not support it

**Comment by Derkades** [comment]
@C41vn Were you using a third party template? Can you reproduce this issue with the default template?

**Comment by samerton** [comment]
I am able to reproduce the issue on pre-12 using Default Revamp

1. Create a new topic
2. Enter a valid topic title and content
3. Inspect element on the form and delete the token field (just to break validation)
4. Submit form - invalid token error is received and topic title/content is wiped

**Comment by Derkades** [comment]
Closing due to lack of response
