### ISSUE TITLE
Make mc-usernames a choice

### ISSUE THREAD

**Issue by C41vn** [NamelessMC/Nameless#2541]
### Describe the feature

I use this for my Minecraft community personally, but sometimes it's better just to have a username and email option instead of their Minecraft username.

Basically, make it where you can have a choice to remove Minecraft-usernames as an option.

**Comment by Derkades** [comment]
Disabling the Minecraft integration will turn the "Minecraft username" field into a regular username field.

**Comment by C41vn** [comment]
Ah, I see, my bad I wasn't aware, thanks
