### ISSUE TITLE
Option to not use toastr for devs with forum post quotes

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#2542]
### Describe the feature

Currently I have to use toastr on the forum topic page because toastr code is baked into the backend js that powers forum quotes. I removed toastr from my themes for a reason and would like not to use it, so was wondering if that JS could be added inline to the view_topic.tpl file, so I could change that code to use sweet alert.

**Comment by Aberdeener** [comment]
Would be open to a PR for this
