### ISSUE TITLE
WYSIWYG: add headings to editor

### ISSUE THREAD

**Issue by SupaYoshi** [NamelessMC/Nameless#2552]
### Describe the feature

Dear NamelessMC developer team,

Please add header tags to the WYSIWYG editor on the backend, so we can create SEO optimised pages with the H2 header tag and H3, H4 etc. as they were meant to be used. Converting between HTML and source code right now for custom pages is annoying and time consuming, this feature would be much appricated!

**Comment by Jochyoua** [comment]
With some manual modifications to tinymce you can make it so you can insert headers with a click
![](https://i.imgur.com/ti8I0dh.png)
here are some links that might help you
https://www.tiny.cloud/docs
https://github.com/NamelessMC/Nameless/blob/v2/core/classes/Core/Input.php#L131

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/155893386-2db60136-6618-405b-8ba4-8f607f1b6610.png)

**Comment by Derkades** [comment]
Should we remove the old font size option, so users don't accidentally use that instead of proper headers?
