### ISSUE TITLE
TEBEX link broken in staff cp panel

### ISSUE THREAD

**Issue by SupaYoshi** [NamelessMC/Nameless#2553]
### Describe the issue

1. Go to settings -> tebex -> Server Key [?] icon
2. Press [?] icon next to Server Key, suggestion "This is the secret key shown when editing your server here" URL leads to 404.
3. Please update in next release.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Go to settings -> tebex -> Server Key [?] icon
2. Press [?] icon next to Server Key, suggestion "This is the secret key shown when editing your server here" URL leads to 404 on Tebex website!

### Expected Behaviour

Lead to server key on Tebex website

**Comment by PadowYT2** [comment]
This is not the right repository..... Samerton/Nameless-Tebex

**Comment by samerton** [comment]
Hi,

Nice spot, could you please open this in the https://github.com/samerton/Nameless-Tebex repository as mentioned by @PadowYT2?

Thanks!

**Comment by PadowYT2** [comment]
> Hi,
> 
> Nice spot, could you please open this in the https://github.com/samerton/Nameless-Tebex repository as mentioned by @PadowYT2?
> 
> Thanks!

#Samerton/Nameless-Tebex/23
