### ISSUE TITLE
Database deleted

### ISSUE THREAD

**Issue by Andrei12333** [NamelessMC/Nameless#2554]
### Describe the issue

So my database gets randomly deleted by my host and my website is no longer acessible how can i change my database information within an file?

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Delete your mysql database (the one that was used for your website)
2. go on your website
3. See error

### Expected Behaviour

The website to load normally

### Additional Information

Error:
SQLSTATE[HY000] [2002] Connection refused
Please check your database connection settings.

**Comment by Andrei12333** [comment]
**Please note that i reinstalled namelessmc becuse of this issue**

**Comment by Andrei12333** [comment]
**My database got randomly reinstated**

**Comment by Derkades** [comment]
Your error doesn't mean your database has been deleted, it means the database server is not running.

You can change database details in `core/config.php`

**Comment by Andrei12333** [comment]
It didn't show up in my host for 2 minutes

**Comment by Andrei12333** [comment]
So yea it wasn't deleted
