### ISSUE TITLE
PHP error in CaptchaBase.php before installation

### ISSUE THREAD

**Issue by RobiNN1** [NamelessMC/Nameless#2558]
### Describe the issue

I got this error right after the clean install, so I'm not sure how to reproduce it.

C:\laragon\www\nameless\core\classes\Misc\CaptchaBase.php(45): Argument 1 passed to CaptchaBase::setActiveProvider() must be of the type string, null given, called in C:\laragon\www\nameless\modules\Core\module.php on line 348

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Use the latest version of Nameless from Github.
PHP 7.4.26

### Expected Behaviour

There should be no errors.

**Comment by Derkades** [comment]
If I remember correctly this happens when visiting `/` when the website is not installed yet

**Comment by Derkades** [comment]
This seems to be fixed now
