### ISSUE TITLE
Two Step Authentication - Major Bug

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#256]
* Bug.
* 1.0.9.
* Needs to be fixed asap!
* Yes. Below the format.
* It occurs when the person has two step authentication enabled (email) and they try to login. (Yes, they get the email, and it works when they type the code and login, but it displays the logs of when the email was sent above where you put the code to login). For example it would say, something like (1) "SERVER -> CLIENT: 220 mail.website.com SMTP Server ready" (2) "CLIENT -> SERVER: EHLO endertime.com".
* I'm loggin in with my account. I'm not sure if other people are getting this error.

**Comment by samerton** [comment]
I've not been able to reproduce your issue, but can you try the following?

- Edit **pages/signin.php** with an editor of your choice
- Find line 66 (which currently reads `$mail->SMTPDebug = 2;`)
- Change this line to `$mail->SMTPDebug = 0;`

Does that help?

**Comment by ThomasIO** [comment]
Yes, thanks!
