### ISSUE TITLE
Wrong Avatar 

### ISSUE THREAD

**Issue by TeemoCell** [NamelessMC/Nameless#2562]
### Describe the issue

All avatars are wrong besides the avatar on the top nav.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Click on "Allow custom user avatars?"
2. Change your Avatar 

### Expected Behaviour

Same avatar on all pages

### Screenshots

![dd](https://user-images.githubusercontent.com/11705513/149146296-e85cd9af-93b6-4e79-8fcd-8e714c84f08e.png)

![unknown](https://user-images.githubusercontent.com/11705513/149146307-35f5d63f-5537-4cad-bef6-b3d509fc76c9.png)

![image](https://user-images.githubusercontent.com/11705513/149146458-cd60f02b-2e40-4002-ae18-1d16ade824bd.png)

**Comment by TeemoCell** [comment]
The Avatar is a .gif

**Comment by Aberdeener** [comment]
This has already been fixed for the next release
