### ISSUE TITLE
How do I update my server to 1.0.10?

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#257]
Help, please!

**Comment by samerton** [comment]
You can find instructions in the AdminCP -> Update tab, where there is a special download package that needs installing.

**Comment by ThomasIO** [comment]
I don't fully understand the instructions. I downloaded the files that it told me, now what? Where do I uzip the required files?

**Comment by samerton** [comment]
You simply need to download the file, unzip it, and then upload the unzipped files to your website.

Once that's done (you'll need to overwrite a few files already on the website), click the "Update" button in the AdminCP -> Update tab.

**Comment by ThomasIO** [comment]
Do I upload the folder or the files?

**Comment by ThomasIO** [comment]
(The files in the folder that is.)

**Comment by samerton** [comment]
The following files/folders need uploading directly onto your web server:
http://i.imgur.com/WnpF3R7.png

**Comment by ThomasIO** [comment]
Thanks, and also. What did you fix/update in the new version?

**Comment by samerton** [comment]
There were mostly fixes in this version, including an issue with the Minecraft server banner and also private message reply alerts not working, but new features such as a staff list within the Members addon and also translation updates have been added.
