### ISSUE TITLE
Disabling Registration for new users doesn't work if AuthMe Integration is enabled

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2587]
### Describe the issue

Title says it all.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Enable AuthMe Integration and setup it correctly (with database connected)
2. Navigate to StaffCP > Configuration > Registration
3. Disable registration
4. Open incognito tab / logout from your current account fully / open different browser that don't have any logins to your namelessMC site
5. Hit button to register ("Register")
6. You will be able to register using MC ingame account and ingame account password even though **registration is disabled**.

### Expected Behaviour

Should not allow anyone to register.
Because of this, alternative is to use Maintenance but it's not practical as disabling registration.

**Comment by Aberdeener** [comment]
Good catch, thank you
