### ISSUE TITLE
Question about registration date

### ISSUE THREAD

**Issue by fer112233** [NamelessMC/Nameless#259]
Question
1.0.10
I want to disable the date of birth on the user registration

**Comment by samerton** [comment]
It's currently not necessary that the field is filled in, so it can be left empty.
In the future, custom profile fields will be possible, so this could be part of those updates.

**Comment by fer112233** [comment]
But, i don´t want it on the register page, can i donate something to do it for my web?

**Comment by samerton** [comment]
I haven't had much chance to test, but try replacing the contents of **pages/register.php** with [this code](https://gist.githubusercontent.com/samerton/a6d8bae7cd3121ab491dd73ecea10889/raw/892b3c2fb8eaffd2a16cbef45e5f1d4d119fbf03/register.php).

**Comment by fer112233** [comment]
Thanks, i will try it

**Comment by fer112233** [comment]
When a cracked user try to register, he cant´t, how can i fix it?

**Comment by jesseke55** [comment]
You can register the account manually and you are set

**Comment by fer112233** [comment]
It happens with all the users so, no, créate each account manyally it´s not an option...

**Comment by samerton** [comment]
Sorry for the late reply. The code changes shouldn't have affected the ability for users to register, try reverting the contents of the registration page back to normal to see if that helps at all.

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues feel free to re-open.
