### ISSUE TITLE
Cannot access post with "/" in title

### ISSUE THREAD

**Issue by Grafnus** [NamelessMC/Nameless#2591]
### Describe the issue

I am currently running an instance of NamelessMC for testing and development. I created a post where I used a "/" in the title. After creating I got the error that the page I am looking for is missing. I got back to the home screen and tried to access it from the forum list but to no avail. It looks like the / char ist not parsed to an url friendly string.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Create a new Post
2. Enter a string like "Good/Bad things my happen"
3. Submit the post creation
4. try accessing the post

### Expected Behaviour

I would expect to be able to access the post

### Screenshots

There would only be the error page.

**Comment by Derkades** [comment]
This has been fixed for pr13, see #2461
