### ISSUE TITLE
Profile Banner and New Resources Icon suggestions

### ISSUE THREAD

**Issue by 32AE** [NamelessMC/Nameless#2596]
### Describe the feature

I think namelessmc should have the option to set the default profile banner & the default resources icons to match the user's server & theme. And i think it should be in the "Images" category,

It only makes sense because some people probably don't want the default stuff to be there, and i get most of the time it can be annoying + the only way to get it out there is if Party & or the other owner sets it via the files, which we don't have access to.

This would be a really helpful tool to use and id really appreciate it if we got these features!

**Comment by PadowYT2** [comment]
Please refer Resource Icons to [Samerton/Nameless-Resources](https://github.com/Samerton/Nameless-Resources)

**Comment by Derkades** [comment]
Also see https://github.com/NamelessMC/Nameless/issues/2550
