### ISSUE TITLE
Invalid Token when pinning Topic

### ISSUE THREAD

**Issue by Grafnus** [NamelessMC/Nameless#2597]
### Describe the issue

When I try to pin a topic, I get the error message "Invalid Token". I looked at this Issue #2446 but could not get it fixed. I am not in the StaffCP. As far as I am aware of, I cannot clear the cache of the regular Theme on the webpage, can I?

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Create Topic
2. Open Moderation DropDown
3. Click "Pin Topic"

### Expected Behaviour

The topic is pinned in the forum.

**Comment by PadowYT2** [comment]
This is a non bug, if you can talk on discord, talk [there](https://discord.gg/nameless)

**Comment by Derkades** [comment]
Clearing cookies doesn't help and they're already using default templates so it might be a bug. I am unable to reproduce on a pr13 test site, haven't tried pr12. Any suggestions?

**Comment by Grafnus** [comment]
Another Error in the Console:
The Version of jQuery you are using does no longer support .offset() (Or you have removed a jQuery plugin)

![Err](https://user-images.githubusercontent.com/29014281/152774509-2e695917-797b-4fa1-9256-15838f55ab9c.PNG)

**Comment by Grafnus** [comment]
> Clearing cookies doesn't help and they're already using default templates so it might be a bug. I am unable to reproduce on a pr13 test site, haven't tried pr12. Any suggestions?

Could it already be fixed with some #2446 issues?

**Comment by Grafnus** [comment]
I found the line in the source where it checks the token [https://github.com/NamelessMC/Nameless/blob/e348be48c2556ceae9a37af85f8adff702f93d2c/modules/Forum/pages/forum/stick.php#L42](https://github.com/NamelessMC/Nameless/blob/e348be48c2556ceae9a37af85f8adff702f93d2c/modules/Forum/pages/forum/stick.php#L42). I isolated the two conditions and this `!isset($_POST['token'])` is failing. So the problem should be on my end.

Any Idea how I could fix this?

**Comment by samerton** [comment]
Can you please ensure that lines 70 -> 87 of `custom/templates/DefaultRevamp/forum/view_topic.tpl` match the v2 pre-release 12 code: https://github.com/NamelessMC/Nameless/blob/v2.0.0-pr12/custom/templates/DefaultRevamp/forum/view_topic.tpl#L70-L87

This is responsible for setting the token input field

**Comment by Grafnus** [comment]
Well they didn't match, so I replaced the content and now it works. Thx!
