### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by termanator1128** [NamelessMC/Nameless#260]
Help
1.0.10
I am getting the 404 page
Its just the 404 page
Nope just the 404 page
I have everything enabled and allowed that needs to be

**Comment by samerton** [comment]
Has this happened just after updating, or is this a new install?

**Comment by termanator1128** [comment]
New Install

**Comment by samerton** [comment]
Can you double check a file named ".htaccess" exists within the web root (usually /var/www, or /var/www/html), containing [these rules](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess)?

**Comment by termanator1128** [comment]
I don't have a var or www file

**Comment by termanator1128** [comment]
I'm using xampp

**Comment by samerton** [comment]
Which folder is Nameless installed in?

**Comment by termanator1128** [comment]
htdocs

**Comment by samerton** [comment]
Is it directly in htdocs, or in a subfolder eg localhost/nameless?

**Comment by termanator1128** [comment]
here is the directory D:\xampp\htdocs\nameless

**Comment by samerton** [comment]
Can you edit **D:\xampp\apache\conf\httpd.conf**, and find the line:

`DocumentRoot "D:/XAMPP/htdocs"`

replace with 

`DocumentRoot "D:/XAMPP/htdocs/nameless"`

and then find the line

`<Directory "D:/XAMPP/htdocs">`

and replace it with

`<Directory "D:/XAMPP/htdocs/nameless">`

If you ever need to change it back (eg to access another site), simply revert the changes

**Comment by termanator1128** [comment]
ok that worked thanks
