### ISSUE TITLE
Punish dosen't know where it takes

### ISSUE THREAD

**Issue by NorgePlayz** [NamelessMC/Nameless#2608]
### Describe the issue

So if I warn someone, and user clicking "Acknowledge" the webpage dosen't know where it takes. Making also showing the message every time if they clicking outside

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Go on StaffCP
2. Click "User Management"
3. Click "Users" and select someone
4. Click "Punish"
5. Click "Warn" and type something
6. When you receive an message, click "Acknowledge"

Voilá

### Expected Behaviour

Should closing the message and never showing message again

### Screenshots

Only 1 screenshot need
https://prnt.sc/8P9eOSTE-G-e

**Comment by samerton** [comment]
Can you please check the fatal error log (StaffCP -> Configuration -> Maintenance -> Error Logs) to retrieve the full error message
