### ISSUE TITLE
SQL error after updating to 1.0.10

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#261]
After updating to 1.0.10 and clicking the "Update" button, the page redirected to this error: https://i.gyazo.com/98b827cdfb0d5f89d5ac7fdda5a79876.png

Every page on the site now redirects to that.

http://www.pandacraft.org

**Comment by BlackBeltPanda** [comment]
Found the issue; my config.php was overwritten. Restored from a backup and the site's working again. =)

**Comment by samerton** [comment]
Glad it's working! :)
