### ISSUE TITLE
Forcing 2FA on staff, causes fatal error

### ISSUE THREAD

**Issue by TechnicallyCoded** [NamelessMC/Nameless#2611]
### Describe the issue

I since corrected this by reverting the force_tfa flag in the database so I don't have the full error anymore but the general gist of things was that one of the php scripts were using `$_SERVER[REQUEST_URI]` instead of `$_SERVER['REQUEST_URI']` leading to a undefined constant error. 

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Fresh install
2. Do not enable 2fa on user
3. Force 2FA on admin group
4. Reload a page and there will be a fatal error

### Expected Behaviour

No fatal error + redirect to setup 2FA page

### Additional Information
Using PHP 8

**Comment by Derkades** [comment]
Thanks for the report, a global search for `$_SERVER[REQUEST_URI]` in the code doesn't yield any results so it seems like it's already fixed for pr13

**Comment by TechnicallyCoded** [comment]
That definitely seems like the line in question @Derkades . Ty for your quick reply :)
