### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function each() in /var/www/html/core/includes/smarty/sysplugins/smarty_internal_compilebase.php:75 Stack trace: #0

### ISSUE THREAD

**Issue by AToska21** [NamelessMC/Nameless#2614]
After installing, I get a white screen and this error:
```Fatal error: Uncaught Error: Call to undefined function each() in /var/www/html/core/includes/smarty/sysplugins/smarty_internal_compilebase.php:75 Stack trace: #0```

What does this mean?

**Comment by PadowYT2** [comment]
1) If you have discord, go [there](https://discord.gg/nameless)
2) We need a full page screenshot

**Comment by AToska21** [comment]
![image](https://user-images.githubusercontent.com/58345270/156779510-ee3a1eeb-4b4b-4c7c-b58d-ff1dcfdff403.png)

**Comment by Derkades** [comment]
each() was removed in php 8.0, for now you can work around this issue by downgrading your PHP version to 7.4. @Aberdeener you updated smarty for pr13, right?

**Comment by AToska21** [comment]
I am on 7.4, nginx, NOT on 2.0

**Comment by Derkades** [comment]
That's probably not true, can you confirm by creating a new php file (e.g. `test.php`) with contents `<?php phpinfo();` and visiting it in your browser?

**Comment by Aberdeener** [comment]
Correct! Smarty has updated to support 8.0, and we are using that version
for the next update

**Comment by PadowYT2** [comment]
Mind closing if it is fixed?
