### ISSUE TITLE
Teamspeak does not work

### ISSUE THREAD

**Issue by itisjori** [NamelessMC/Nameless#262]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? I have teamspeak enabled in the admincp, but if i go to start page, it says: Connection Refused
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Nope
* Do you have an idea how or where the issue occurs? Nope

**Comment by samerton** [comment]
I can't reproduce any issues with Teamspeak, sounds like an issue with your connection details.

**Comment by itisjori** [comment]
But with what?

**Comment by samerton** [comment]
It's probably down to the IP or ports, similar threads on the internet suggest firewall issues so ensure the ports are open on both your web server and your TeamSpeak server.

**Comment by itisjori** [comment]
How to find out virtual port then?

**Comment by samerton** [comment]
This depends, are you hosting the TeamSpeak server yourself, or are you using a shared host?

**Comment by itisjori** [comment]
Shared

**Comment by samerton** [comment]
I'm not too sure sorry, as I don't use TeamSpeak myself, but can you try setting the virtual port as the actual port your server runs on?

**Comment by samerton** [comment]
I'm going to mark this as closed, as it's due to the TeamSpeak connection details inputted. If you're still having issues, feel free to re-open.
