### ISSUE TITLE
Custom Widgets (like Custom Pages)

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless#2632]
### Describe the feature

Literally the title says it all!
here is one example (source: spigotmc.org)
![image](https://user-images.githubusercontent.com/56804505/158205080-cfa3a556-bab6-4611-a8d5-8611e52f60dd.png)

**Comment by PadowYT2** [comment]
Widget is coming soon, it is 90% done

**Comment by PadowYT2** [comment]
[Module](https://namelessmc.com/resources/resource/194/) is published
