### ISSUE TITLE
Update to Font Awesome v6

### ISSUE THREAD

**Issue by S4MON1X** [NamelessMC/Nameless#2635]
### Describe the feature

Font Aweasome v6 adds a lot of new icons and its styles.

**Comment by WavingCatDevs** [comment]
I'll open a pr with this soon

**Comment by WavingCatDevs** [comment]
Hmm, they seem to have changed the font awesome file things, ill let one of the developers sort this out.

**Comment by samerton** [comment]
We need to do this whilst maintaining compatibility for version 5 so existing website icons don't break

**Comment by S4MON1X** [comment]
This might help: https://fontawesome.com/docs/web/setup/upgrade/whats-changed#backward-compatibility

**Comment by WavingCatDevs** [comment]
> We need to do this whilst maintaining compatibility for version 5 so existing website icons don't break

Yeah

**Comment by TeemoCell** [comment]
Check #2651

**Comment by samerton** [comment]
Removing the link since we still need to update Default Revamp

**Comment by Aberdeener** [comment]
Fixed in 937c518d94a8df3ac4df8d9928392d4562abd872

**Comment by Derkades** [comment]
Nice, with this commit the last bit of third party css/js was removed!

**Comment by Aberdeener** [comment]
Ha, what do you mean? There is still so much

**Comment by Derkades** [comment]
I meant js/css served from third party CDNs instead of locally
