### ISSUE TITLE
Default Panel template

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2639]
### Describe the issue

1. Teemo forgot about the color
2. Table is wider and it causes a scrollbar appear

_see screenshots_

### NamelessMC Version

2.0.0-pr13 (dev)

### To Reproduce

1. StaffCP > User Management > Users > {user}
2. StaffCP > Security > Group Sync Changes

### Expected Behaviour

1. Should be a right color
2. Should be the right size

### Screenshots
1.  
![https://cdn.padow.ru/IzcE](https://cdn.padow.ru/IzcE)
2.  
![https://cdn.padow.ru/0HuD](https://cdn.padow.ru/0HuD)

**Comment by TeemoCell** [comment]
Should be fixed in #2650
