### ISSUE TITLE
TinyMCE theme does not follow panel light/dark theme

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2649]

**Comment by Aberdeener** [comment]
Not sure of a nice way to get/pass the status of dark mode on the StaffCP to the `Input::create...` method, since it is handled by JavaScript...

**Comment by Derkades** [comment]
maybe it could use cookies instead of local storage

**Comment by TeemoCell** [comment]
You can override the TinyMCE style with custom style.

**Comment by TeemoCell** [comment]
![image](https://user-images.githubusercontent.com/11705513/160292858-f2b11697-975a-4b4b-80c1-6058420aee7f.png)
