### ISSUE TITLE
Can Not update

### ISSUE THREAD

**Issue by Ula492** [NamelessMC/Nameless#265]
### Template:
* What kind of issue is it (Question, Bug, etc.)? 
Can Not update site.
* In which version of NamelessMC did it occur
(1.0.8)
* How would you describe the issue?
 I can not update
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
http://imgur.com/k33LsGk
* Do you have an idea how or where the issue occurs? 
After I click update, yes the update files were dragged and dropped into the server and replaced.

**Comment by samerton** [comment]
This may have happened if you installed a development version between version 1.0.8 and 1.0.9. 

Can you check your server's error logs (by default **/var/log/apache2/error.log** on Ubuntu, and might be in the **/var/log/httpd** directory on CentOS) to see what the most recent entries are?

**Comment by Ula492** [comment]
Apache Log:

[Mon Jun 20 06:30:39.022185 2016] [:notice] [pid 3677] mod_bw : Memory Allocated 0 bytes (each conf takes 48 bytes)
[Mon Jun 20 06:30:39.022204 2016] [:notice] [pid 3677] mod_bw : Version 0.92 - Initialized [0 Confs]
[Mon Jun 20 06:30:39.054527 2016] [mpm_prefork:notice] [pid 3677] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Mon Jun 20 06:30:39.054537 2016] [core:notice] [pid 3677] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 22 21:29:50.831059 2016] [mpm_prefork:notice] [pid 3677] AH00169: caught SIGTERM, shutting down
[Wed Jun 22 21:29:51.792763 2016] [:notice] [pid 15482] mod_bw : Memory Allocated 0 bytes (each conf takes 48 bytes)
[Wed Jun 22 21:29:51.792814 2016] [:notice] [pid 15482] mod_bw : Version 0.92 - Initialized [0 Confs]
[Wed Jun 22 21:29:51.875600 2016] [mpm_prefork:notice] [pid 15482] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed Jun 22 21:29:51.875623 2016] [core:notice] [pid 15482] AH00094: Command line: '/usr/sbin/apache2'

**Comment by samerton** [comment]
Unfortunately the contents of the log don't seem to help.

I will create a new upgrade file which will help with your issue, are you upgrading from 1.0.7 -> 1.0.8, or 1.0.8 -> 1.0.9?

**Comment by Ula492** [comment]
1.0.8 -> 1.0.9

**Comment by jesseke55** [comment]
@samerton You need the error.log files

**Comment by samerton** [comment]
Try replacing the contents of **core/includes/updates/108.php** with [this code](https://gist.githubusercontent.com/samerton/44a1da0d8a47cd7a13fc6b0f53be61b9/raw/b6c69a92d06aa42ff079e05365d0a0cf3931d6d2/108.php), and try again.

**Comment by Ula492** [comment]
@samerton It still does not work.

**Comment by samerton** [comment]
Can you search for a different Apache error log file? 
The previous log appears doesn't appear to be the error log, unfortunately I can't give you an exact path to check because it varies depending on your installation.

**Comment by Ula492** [comment]
@samerton I lied, it did update to 1.0.9 but now the samething is happening to update to 1.0.10

**Comment by samerton** [comment]
Something strange is happening there, the upgrade script to 1.0.10 shouldn't cause any issues.
Once the upgrade script to 1.0.10 has given a white screen, when you check the AdminCP's Overview page, does it still say you're running version 1.0.9?

**Comment by Ula492** [comment]
Says:
Your version: 1.0.9
New version: 1.0.10

Update instructions: Version 1.0.9 -> 1.0.10


So I click update then it says this:

The thevoidmc.net page isn’t working

thevoidmc.net is currently unable to handle this request.
500

Just like the Imgur

**Comment by samerton** [comment]
Unfortunately we can't diagnose the issue without locating the error logs, which will tell us exactly what's going on. 
Which OS are you running?

**Comment by Ula492** [comment]
ubuntu

**Comment by samerton** [comment]
Can you enable error reporting (AdminCP -> Misc), try upgrading again, and then check **/var/log/apache2/error.log** only for the errors which are most recent.

**Comment by Ula492** [comment]
Question. What perms do i need for each file? Cus I think that is what is wrong. Thats why it wont update.

**Comment by samerton** [comment]
The permissions shouldn't be the issue, as they won't cause a 500 error.

Unfortunately I can't help without the errors from the log, as I don't know what the cause could be.

Do you have a lot of data on your site? I can only recommend you install the [latest version](https://github.com/NamelessMC/Nameless/releases/tag/v1.0.10) anew.

**Comment by Ula492** [comment]
@samerton Sorry its been a little while, but my hoster (immortalnetwork) is a bad hoster and they never respond to support stuff, so im waiting for them to respond so i can try and update while and they can get the log at the same time.

**Comment by Ula492** [comment]
the only error that i see that updates is the following

 `Jul  1 11:53:52 ip-xxxxxxx postfix/qmgr[1146]: 8037C81E7B: from=<root@ip-xxxxxxx.ipxxxxxxx>, size=852, nrcpt=1 (queue active)
Jul  1 11:53:52 ip-172-31-33-197 postfix/smtp[18554]: 8037C81E7B: to=<root@ip-xxxxxxxxx.ip-xxxxxxxxx>, orig_to=<root>, relay=none, delay=105353, delays=105353/0.01/0/0, dsn=4.4.4, status=SOFTBOUNCE (Host or domain name not found. Name service error for name=ip-xxxxxxxxx.ip-xxxxxxxtype=AAAA: Host not found)`

Im also just gonna include the error log:
`[Fri Jul 01 01:10:01.638128 2016] [mpm_prefork:notice] [pid 15482] AH00171: Graceful restart requested, doing restart
[Fri Jul 01 01:10:01.748067 2016] [:notice] [pid 15482] mod_bw : Memory Allocated 0 bytes (each conf takes 48 bytes)
[Fri Jul 01 01:10:01.748082 2016] [:notice] [pid 15482] mod_bw : Version 0.92 - Initialized [0 Confs]
[Fri Jul 01 01:10:01.776242 2016] [mpm_prefork:notice] [pid 15482] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Fri Jul 01 01:10:01.776254 2016] [core:notice] [pid 15482] AH00094: Command line: '/usr/sbin/apache2'
 `

**Comment by Ula492** [comment]
also, my website is wayyy to slow. any ideas?

**Comment by samerton** [comment]
@Ula492 

Unfortunately those errors don't appear to be from the correct Apache error log. Do you have error reporting enabled (AdminCP -> Misc)? If not, can you try enabling it, and checking those logs again?

As for your site being slow, is it on any page in particular, or the whole site?

**Comment by Ula492** [comment]
@samerton the entire site is just slow it self. & for the AdmindCP logs ill enable and post an udpate here, also sorry for the late af reply. I just got back from vacation.

**Comment by Ula492** [comment]
@samerton I get the following right now, 
Warning: require(/var/sentora/hostdata/chris/public_html/thevoidmc_net/core/includes/updates/109.php): failed to open stream: Permission denied in /var/sentora/hostdata/chris/public_html/thevoidmc_net/pages/admin/update_execute.php on line 44
Fatal error: require(): Failed opening required 'core/includes/updates/109.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/sentora/hostdata/chris/public_html/thevoidmc_net/pages/admin/update_execute.php on line 44

Ive contacted my hoster and see if he will do something about it.

**Comment by samerton** [comment]
@Ula492 
Were you able to contact your host?

**Comment by Ula492** [comment]
@samerton yes it was all update now. But the site is still slower then a turtle

**Comment by samerton** [comment]
@Ula492 
The tests I've run on Nameless suggest it shouldn't slow your site down, is your forum database on the same machine as the forum files themselves?

**Comment by Ula492** [comment]
@samerton no the database is in a completely dif database then my website.

**Comment by samerton** [comment]
@Ula492 
That will be the cause of your issue, the site is slow as it has to connect to an external database.
