### ISSUE TITLE
TinyMCE theme from Default got to DefaultRevamp

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2661]
### Describe the issue

Default's panel template TinyMCE theme is in DefaultRevamp's inputs

### NamelessMC Version

From commit 76713ba

### To Reproduce

1. Enable dark mode
2. Go to Account
3. Go to Profile settings
4. Find Signature

### Expected Behaviour

Should be DefaultRevamp's color style

### Screenshots

![https://cdn.padow.ru/avo5](https://cdn.padow.ru/avo5)

**Comment by Derkades** [comment]
Seems like this has nothing to do with the panel's styling. It looks like it's the default color scheme for the `oxide-dark` TinyMCE skin.

Maybe I've missed some menus, but at least it's better now.
![image](https://user-images.githubusercontent.com/15892014/169408105-e834c0d5-7cc0-4009-b304-6c6a3ecbf000.png)
