### ISSUE TITLE
StaffCP Template issues

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2664]
### Describe the issue

1. When you enable dark mode and go to an another page, it disables dark mode???
2. No edits on items

### NamelessMC Version

From commit b9f52ea

### To Reproduce

1.
1) Go to User Management > Users
2) Turn on Dark Mode
3) Go to IP Lookup or other pages (in dropdown afaik)
2.
1) Go to Configuration > API
2) See Notifications & Tooltip

### Expected Behaviour

1. Should be always on that mode
2. Should be blue-ish

### Screenshots

2. 
![https://cdn.padow.ru/cRfE](https://cdn.padow.ru/cRfE)
![https://cdn.padow.ru/KdhE](https://cdn.padow.ru/KdhE)

### Additional Information

1. https://user-images.githubusercontent.com/71085027/161703212-ea3d13b2-afdf-4956-b454-fbede53d8f69.mp4

**Comment by Derkades** [comment]
Dark mode is remembered per page because the cookie has `Path` set to the specific StaffCP page

**Comment by Derkades** [comment]
Multiple issues in one issue is hard to track so I've created two new issues #2665 #2666
