### ISSUE TITLE
Tooltips don't have the same blue tint as rest of StaffCP

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2665]
![image](https://user-images.githubusercontent.com/15892014/161729602-194104ca-e098-4c49-b2e3-651c904aae68.png)
![image](https://user-images.githubusercontent.com/15892014/161729635-35346ded-fbee-4a53-aaee-049f843d192b.png)

**Comment by PadowYT2** [comment]
Inputs have a wrong color too
![https://cdn.padow.ru/Q4c9](https://cdn.padow.ru/Q4c9)

**Comment by TeemoCell** [comment]
Fixed in #2678 2678
