### ISSUE TITLE
StaffCP dark mode cookie now has path set

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2666]
It's set to a specific page meaning dark mode is per-page now
![image](https://user-images.githubusercontent.com/15892014/161729983-08c24bad-c36d-4f02-9db7-f5a99e51b606.png)

**Comment by samerton** [comment]
Are you able to test this on the same website but with friendly URLs disabled?

**Comment by Derkades** [comment]
Works fine with friendly urls disabled
