### ISSUE TITLE
Custom pages

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2671]
### Describe the issue

By going to a custom page it adds an another `/` means you can't go from pages (excluding /) to that page

### NamelessMC Version

Development version

### To Reproduce

1. Make a custom page
2. Go to an another page
3. Go to the custom page

### Expected Behaviour

Should not be adding an another `/`

### Additional Information

https://user-images.githubusercontent.com/71085027/162174895-4fc6696a-69ad-4cec-9a9f-d21ab0460f58.mp4

**Comment by samerton** [comment]
This is caused by a `urlencode` which was recently added: https://github.com/NamelessMC/Nameless/blob/v2/modules/Core/module.php#L178

**Comment by partydragen** [comment]
Yea and we should keep the / not remove it as some sites want multiple of those like /wiki/page1 and /wiki/page2 etc

**Comment by Derkades** [comment]
Yes if the link contains slashes it shouldn't be urlencoded. I'll revert the urlencoded changes for custom page urls
