### ISSUE TITLE
Turning off registration

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2675]
### Describe the issue

You cannot turn off registration

### NamelessMC Version

Development version

### Additional Information

https://user-images.githubusercontent.com/71085027/162680303-51cde7a2-3ac9-4d9c-8345-5f1a767b2f9f.mp4

**Comment by TeemoCell** [comment]
Might be the same problem as in 
https://github.com/NamelessMC/Nameless/pull/2633#issuecomment-1070505903
