### ISSUE TITLE
MentionParser breaks if user don't exist

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#2677]
The new way of loading tagged users breaks if user no longer exists causes fatal error

Solution: Check if user exists and if it no longer exist it should display @DeletedUser instead, text from language system so its translatable

**Comment by Aberdeener** [comment]
Fixed in [32e92e3](https://github.com/NamelessMC/Nameless/commit/32e92e3ab75f51a57e3aab3a20ee1f6983fe4bea)
