### ISSUE TITLE
Broken pages

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2680]
### Describe the issue

1. When there's a 403 problem with pinging NamelessMC find modules, templates the template breaks
2. The color of the error on the panel template & modules pages is danger

### NamelessMC Version

Development version

### Expected Behaviour

1. Footer should be sticked to bottom & normal container
2. Panel template & modules error should be warning color and not danger

### Screenshots
![https://cdn.padow.ru/M2Ly](https://cdn.padow.ru/M2Ly)
---
![https://cdn.padow.ru/B6Cj](https://cdn.padow.ru/B6Cj)

**Comment by Aberdeener** [comment]
Thanks Padow, good catch.
