### ISSUE TITLE
Paginate ListUsers endpoint

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#2683]
### Describe the feature

ListUsers endpoint should use a pagination system to avoid sending all users at once

**Comment by Aberdeener** [comment]
Let me know if you think we should do:
- default limit of 15 (if they don't provide a limit param it has no limit right now)
- "next" and "previous" links in the response json

**Comment by Derkades** [comment]
I think the current implementation is good (enough) and we can close this issue

**Comment by samerton** [comment]
This is something I would definitely like to get done to improve performance on large sites.

I like the idea of defaulting to 15 - I think there is already a `limit` and `offset` parameter so it's just a case of defaulting `limit` to 15 if not provided.
