### ISSUE TITLE
Navbar Colour are hard coded

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2692]
### Describe the issue

Navbar Colour text are hard coded with no translations

### NamelessMC Version

Development version

**Comment by samerton** [comment]
This was intentional to match the Semantic terminology, I'll convert this to an enhancement and we can decide if it is something we want to change

**Comment by PadowYT2** [comment]
But why? It is just language,
```html
<option>changing this</option>
``` is just backend viewable
