### ISSUE TITLE
Show Cookie Popup doesn't work

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2696]
### Describe the issue

When you click `Show Cookie Popup`, it reloads the page and does nothing

### NamelessMC Version

Development version

**Comment by samerton** [comment]
This works as intended for me - is there any information in your browser console?

**Comment by PadowYT2** [comment]
Nope,

https://user-images.githubusercontent.com/71085027/165535662-986ed526-05e3-4870-99ae-09457e44268a.mp4
