### ISSUE TITLE
Automatically enable Discord integration when linking bot

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2711]
The switch is easy to miss and I think everyone who successfully links the Discord bot wants the Discord integration to be enabled.

**Comment by Derkades** [comment]
Thanks, is the check whether the bot url was unset before necessary? Shouldn't it also re-enable the discord integration if someone re-invites the bot?

**Comment by partydragen** [comment]
> Thanks, is the check whether the bot url was unset before necessary? Shouldn't it also re-enable the discord integration if someone re-invites the bot?

Well the check is to avoid it to enable if the user disabled it on purpose,  and if they re-invite the bot the option is already enabled unless they disabled it

**Comment by Derkades** [comment]
Good point, the bot also sends bot settings at every startup which would mean the integration gets reactivated every time
