### ISSUE TITLE
Debug link success toastr is empty

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2720]
### Describe the issue

After making a debug link in staffcp, the toastr that displays is empty

### NamelessMC Version

Development version

### Screenshots

<img width="384" alt="Screen Shot 2022-04-26 at 21 02 20" src="https://user-images.githubusercontent.com/26070412/165438052-6743b489-d8a7-4d42-a705-4a1d7d618e7a.png">

**Comment by PadowYT2** [comment]
That's strange, I'll look into this
