### ISSUE TITLE
BUG text box

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#2722]
### Describe the issue

I don't know if you have seen but there is a bug in the boxes a p appears when you click on the box for the text ( https://namelessmc.com/user/messaging/?action=new )

### NamelessMC Version

2.0.0-pr12

### Screenshots

![image](https://user-images.githubusercontent.com/12797827/165625534-81fb8cd7-edb4-4037-a3d4-34a69ceada82.png)

**Comment by samerton** [comment]
Hi,

This is normal - it refers to the HTML element which is currently active within the editor. `p` means paragraph.

If you add a link and select it, you will see it changes to `p >> a` - `a` means anchor which is used to insert links in HTML, so it is an anchor inside a paragraph.

It's just to give you some information on the HTML which will be contained within your post.

**Comment by CreaCloudz** [comment]
Is not possible to remove this ?

**Comment by samerton** [comment]
There is no option to remove it currently I'm afraid
