### ISSUE TITLE
BUG User following topics

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#2726]
### Describe the issue

Hello, here is the problem in followed topics we see his nickname and this photo of progile and not that of the creator of the topics. and for unfollow always the token error message. 

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Go to a topics
Follow a topic
Go to https://namelessmc.com/user/following_topics/

**Comment by partydragen** [comment]
Thx for reporting these, I have fixed the issues in https://github.com/NamelessMC/Nameless/commit/d31105d757b92564204fd5dfe2d79f6994348e92 and https://github.com/NamelessMC/Nameless/commit/f8097d8130d49f22cd4254bd2f3fad350c4f326f
