### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2735]
### Describe the issue

When you setup Dark mode in StaffCP for **DefaultRevamp** and go to the website with all cache & cookies cleared, it is dark.
https://github.com/NamelessMC/Nameless/blob/fc5eeee07ac08c2938f14b42d1472057be8b06ee/core/init.php#L626-L637
https://github.com/NamelessMC/Nameless/blob/fc5eeee07ac08c2938f14b42d1472057be8b06ee/custom/templates/DefaultRevamp/template_settings/settings.php#L120
But when doing the same method in Nexus, it doesn't, meaning only DefaultRevamp gets recongized. *(this is not an only function file, there are more, this is just an example)*

https://github.com/GIGABAIT-Official/nexus/blob/4ce0f7d4fcdcb50e30fa607452dd24c4669ec322/custom/templates/Nexus/template_settings/includes/caches.php#L24-L30

**And yes, $darkMode is defined in Nexus frontend**

### NamelessMC Version

Development version

**Comment by samerton** [comment]
The following assumes you are working against the latest v2 development code, and **not** pre-release 12.

Are you able to use the constant `DARK_MODE` instead?

**Comment by PadowYT2** [comment]
1. Yes I know
2. I'm but same result
