### ISSUE TITLE
Stand Friend when using Followers system in Profile

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#274]
When we using Followers system right its still Stand Add Friend/Remove Friend

**Comment by IsS127** [comment]
i can help you with that, happend same with me. If you are going to use friend again use the same way im gonna tell you to do now. go to styles/language then go to you're language then open the .php file. im guessing u are using english language so go find this line : 'add_friend' exact how it says with the '. then it should say Add friend then above it it should say remove friend. only change the text beside the 'add_friend'/ 'remove_friend' Np!
