### ISSUE TITLE
On some pages assets are wrong

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2742]
### Describe the issue

When #2670 was merged, there are issues.
1. Dropdown on Installation
2. `jQuery is not defined` on Installation
3. CSS is completly broken if you go to / on Installation (may be when installed it could be broken)

### NamelessMC Version

Development version

### Screenshots

![https://cdn.padow.ru/Mb80](https://cdn.padow.ru/Mb80)
![https://cdn.padow.ru/1ysT](https://cdn.padow.ru/1ysT)
![https://cdn.padow.ru/8hYI](https://cdn.padow.ru/8hYI)

### Additional Information

This is probably not all, because of second error, I cannot say all the issues

**Comment by Aberdeener** [comment]
Cannot replicate 1 or 2 - both work fine for me with no issues in styling or errors in console.

3 already has an open issue.

Can you replicate this issue and then send the HTML of the installation page which has the 1 and 2 issues? Thanks

**Comment by PadowYT2** [comment]
Video: https://canary.discord.com/channels/246705793066467328/434751012428054530/973837282341683240
HTML: literally all pages, I'll send the first one https://haste.padow.ru/lehejaheno.xml

**Comment by Aberdeener** [comment]
Fixed in discord; they didn’t run “yarn install”
