### ISSUE TITLE
BUG User like posts

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#2744]
### Describe the issue

Hello, when a person likes a post on the forum, strange things happen.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

Go to on the forum
like a posts

**Comment by Derkades** [comment]
Would you mind elaborating on "strange things"? I tried reproduce myself but ran into another bug

**Comment by CreaCloudz** [comment]
it does not return to the top of the post with a url with a # at the end.

**Comment by Derkades** [comment]
It refreshes the page and jumps back to the correct post, while adding a like. I'm not sure if it's supposed to be an async http request without refresh

**Comment by Aberdeener** [comment]
Yeah this is not a bug - this is intended behaviour, though I'll admit it is certainly clunky. Worth revisiting in the future.
