### ISSUE TITLE
Error when viewing user detail page

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2745]
![image](https://user-images.githubusercontent.com/15892014/167950750-90185bbb-7774-4967-8a88-e820b744f4fe.png)

Query:
```sql
SELECT pf.*, upf.id as upf_id, upf.value, upf.updated FROM nl2_profile_fields pf LEFT JOIN nl2_users_profile_fields upf ON (pf.id = upf.field_id AND upf.user_id = '2');
```

**Comment by Aberdeener** [comment]
`updated` column was added a couple days ago in a commit. Can you make sure your DB is fully up to date? AFAIK initialization and upgrade scripts both add this column, so I assume you've just pulled :p

**Comment by Derkades** [comment]
yes my mistake, thanks
