### ISSUE TITLE
im having trouble loading css/js files

### ISSUE THREAD

**Issue by kingmaj0r** [NamelessMC/Nameless#2765]
### Describe the issue

im trying to install namelessMC, and its not loading css/js.

please contact me if you need logs/config files.

### NamelessMC Version

2.0.0-pr12

### Screenshots

![image](https://user-images.githubusercontent.com/49806509/169291930-5e925056-2e06-4649-9a85-c1608cfa1d21.png)

**Comment by PadowYT2** [comment]
on what url are you accessing it on?

**Comment by PadowYT2** [comment]
Thats a local ip

**Comment by samerton** [comment]
Pressing F12 to open your browser console should yield errors and provide more information as to why the CSS/JS isn't loading

**Comment by kingmaj0r** [comment]
![image](https://user-images.githubusercontent.com/49806509/169304734-0dd13903-01dc-49c7-b938-99317c2c9cb7.png)

**Comment by PadowYT2** [comment]
Click on "Network"

**Comment by Derkades** [comment]
Your hostname looks like an IP address assigned by docker, what is your server setup?

**Comment by kingmaj0r** [comment]
im not using docker

**Comment by kingmaj0r** [comment]
im using apache, but i might move to nginx depending on witch is better
