### ISSUE TITLE
Discord connection is available even if Discord bot is not setup

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2769]
### Describe the issue

title

### NamelessMC Version

Development version

### To Reproduce

- Enable discord integration module
- Go to user settings -> Connections
- See that Discord is listed and available to click "Connect", even though we aren't sure if the bot is setup yet

### Additional Information

We could fix this by adding a method to each Integration class to check "shouldEnable" (similar to GroupSync classes), or only call "registerIntegration" on it if the bot is setup

**Comment by samerton** [comment]
Possibly fixed by the linked commit, needs testing before closing issue

**Comment by Derkades** [comment]
You said someone should test it who has set up the bot, but isn't it the opposite?

**Comment by samerton** [comment]
> You said someone should test it who has set up the bot, but isn't it the opposite?

I've tested without configuring the bot and the issue is resolved - just want to ensure it still shows with the bot set up 😄

**Comment by Derkades** [comment]
Alright, yes it does
