### ISSUE TITLE
Infractions

### ISSUE THREAD

**Issue by dasilvaj4** [NamelessMC/Nameless#277]
Please fix Infractions addon!
When player not registered in website not display in table list.
Screenshot [http://prntscr.com/bln4uh](http://prntscr.com/bln4uh)

**Comment by samerton** [comment]
Which Infractions plugin are you using?

This is probably caused by your website not being able to communicate with Mojang's servers, to obtain the username from the UUID.

**Comment by dasilvaj4** [comment]
But when join for more details show correctly, see [http://prntscr.com/blncb4](http://prntscr.com/blncb4)

**Comment by dasilvaj4** [comment]
I use BanManager

**Comment by samerton** [comment]
Sometimes this is caused by too many request to Mojang's servers, has the issue resolved itself since then?

**Comment by dasilvaj4** [comment]
I solved the error was almost mine, I manually enter in the database

**Comment by samerton** [comment]
Good to hear you have solved the error, I will mark this as closed :)
