### ISSUE TITLE
Dashboard statistics graph bugged

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#2772]
The dashboard statistics graph is showing several years of empty data when its supposed to be the last 14 days
![Skjermbilde](https://user-images.githubusercontent.com/9625439/169535873-4567b7a8-783f-4d7d-b332-a5b524607cd1.PNG)

**Comment by samerton** [comment]
Should be resolved with the removal of the average player count graph (23053813125febf687ed19840a56db9fb0a2ad4f)
