### ISSUE TITLE
Replace API error codes with namespaced strings

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2779]
Same format as Minecraft, `<key>:<value>` where `key` would be the module name and `value` a short description of the error. Namespaced values allow modules to add new API errors without worrying about conflicts with error codes added by the core or other modules.

This also seems like a good time to remove the user friendly and even localized message, in my opinion it adds unnecessary work and I'm not aware of anyone using it.

Example, before:
```json
{
  "error": true,
  "error_code": 3,
  "message": "Something something invalid api method maar dit kan ook in een andere taal zijn"
}
```
After:
```json
{
  "error": "nameless:invalid_api_method"
}
```

Errors under the `nameless` namespace can be used by other modules and shouldn't be removed even if NamelessMC stops using them. Other errors (even under the `core` namespace for example) shouldn't be used by modules.

**Comment by Aberdeener** [comment]
Couple things I'd like input on:
- `CoreApiErrors` & `DiscordApiErrors` class names, doesn't seem totally right...
- Should the `Nameless2API` class be in the Core module? I'm not totally sure it fits there
- Should `nameless:<message>` errors be inside the `Nameless2API` class like right now, or should there be another class to match the module specific classes I mentioned in my first point?

**Comment by Derkades** [comment]
Thanks, I have time to update the documentation and Java API in the next few days.

> CoreApiErrors & DiscordApiErrors class names, doesn't seem totally right...

Seems fine to me

> Should the Nameless2API class be in the Core module?

You're right, maybe it should be in /core/classes/Endpoints instead

> Should nameless:<message> errors be inside the Nameless2API class like right now

I think that's fine

**Comment by Derkades** [comment]
What happened to error codes 38 and 39, for invalid integration username and invalid integration identifier?

**Comment by partydragen** [comment]
> What happened to error codes 38 and 39, for invalid integration username and invalid integration identifier?

Hm he only removed the numbers, believe we could name it integration_error then display the message as meta
