### ISSUE TITLE
Leaderboard doesn't display player names.

### ISSUE THREAD

**Issue by CarbonDiox** [NamelessMC/Nameless#2783]
Some names do not display on leaderboard.

https://gyazo.com/07accfe1744f33598c693e4f7a21203f

https://feudal.gg/leaderboards/

Version: 2.0.0-pr12

**Comment by partydragen** [comment]
Have you deleted any accounts

**Comment by CarbonDiox** [comment]
I have not, website is brand new

**Comment by Aberdeener** [comment]
Hi there,
Are you able to switch your template to Default Revamp and see if the issue
persists? Just want to make sure this isn’t the issue. Thanks!

**Comment by CarbonDiox** [comment]
It does indeed - https://gyazo.com/5853e9c542b059c46e3bfc0cb0bd4416

**Comment by partydragen** [comment]
Current investigation show that there uuid problems as you run the website without uuid linking so none of the registered users has a uuid, but its weird how it find the 2 users who are there as they don't have a registered uuid either

pr12 does not properly support offline mode but i believe your server is online mode but having the website uuid linking disabled?

**Comment by CarbonDiox** [comment]
Yeah, I turned off UUIDs because I use Geyser/Floodgate and assumed it would have problems with registration if I had it on.

**Comment by CarbonDiox** [comment]
By the way, this is what you mean, right? https://gyazo.com/475cfea31b6685ec037205a96f647c02

**Comment by CarbonDiox** [comment]
Got it. Seems fine now. I'll just let Bedrock users know they won't be able to track their stats on the website. Small price to pay. Thank you!

**Comment by partydragen** [comment]
I have also updated the current registered users to have a uuid, but that only works for registered users

Your solution is to disable web registration then only allow ingame registration i guess

**Comment by CarbonDiox** [comment]
And that makes it so you can only register in-game?

**Comment by partydragen** [comment]
Yea with the /register command

**Comment by CarbonDiox** [comment]
Perfect, thank you very much :)
