### ISSUE TITLE
Make spaces for widgets

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2785]
### Describe the feature

![https://cdn.padow.ru/tR6N](https://cdn.padow.ru/tR6N)
As `Последний Пользователь` is long, the right of the widget is moved down. `Последний Пользователь` must be for example like 
```
Последний
Пользователь
```
On german, it is completly bad afaik

**Comment by Aberdeener** [comment]
<img width="323" alt="Screen Shot 2022-06-11 at 22 37 21" src="https://user-images.githubusercontent.com/26070412/173214650-71d0f776-e639-4e87-9144-836fb400f42f.png">
Fixed, thanks for the report
