### ISSUE TITLE
Wrong color for TinyMCE on StaffCP

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2789]
### Describe the issue

On DefaultRevamp's Settings page, TinyMCE is white even when dark mode is enabled

### NamelessMC Version

Development version

### Screenshots

![https://cdn.padow.ru/XHv7](https://cdn.padow.ru/XHv7)

**Comment by Derkades** [comment]
Seems to work fine for me

![image](https://user-images.githubusercontent.com/15892014/170878343-1b9e15b2-5401-4476-a8bc-5f9f474633ac.png)

**Comment by PadowYT2** [comment]
No, this only happens on DefaultRevamp's settings, please read
