### ISSUE TITLE
Avatars dont use 'hat' layer

### ISSUE THREAD

**Issue by PugaBear** [NamelessMC/Nameless#279]
Execute this from the root of the project

```
find ./ -type f -exec sed -i -e 's/.eu\/avatar/.eu\/helmavatar/g' {} \;
```

all done :)

**Comment by samerton** [comment]
Very useful script! I'm currently working on making this an option, it will hopefully be ready shortly.

**Comment by IsS127** [comment]
is this for linux?

**Comment by PugaBear** [comment]
@IsS127 Yes its a linux command. Run it in terminal at the root of the project.

**Comment by IsS127** [comment]
@PugaBear i tried but what is it suppose to do? i have headphones as a hat when i go to my profile i dont really see the headphones..

**Comment by PugaBear** [comment]
That might be because they are on the side of your head. It changes the picture from, for example, this http://cravatar.eu/avatar/Noahkiq/30.png to this http://cravatar.eu/helmavatar/Noahkiq/30.png.

**Comment by IsS127** [comment]
ahh ok ty well then it works
