### ISSUE TITLE
Wrong color on TinyMCE for DefaultRevamp

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2792]
### Describe the issue

#2661 is completed but Derk forgot to do with emotions

### NamelessMC Version

Development version

### Screenshots

![https://cdn.padow.ru/DYCd](https://cdn.padow.ru/DYCd)

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/170878157-16c610cd-3b83-476b-b69e-f0fb7e066a23.png)
