### ISSUE TITLE
Show warning to user when saving groups and group sync fails

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2796]
pr12 used to show a warning in case of misconfiguration (especially the hierarchy error), pr13 no longer does. This means that besides the Nameless-Link log (which is inaccessible to those who do not self-host) there's no indication of what's wrong.

**Comment by Aberdeener** [comment]
I think we can do this by checking the output of `GroupSyncManager::broadcastChange(...)`, and showing them a warning if the logs returned are empty.

**Comment by Aberdeener** [comment]
Fixed:
<img width="1454" alt="Screen Shot 2022-06-10 at 22 24 28" src="https://user-images.githubusercontent.com/26070412/173172347-ce02b921-c776-4e9f-8bd6-f6578ab250a4.png">

**Comment by Derkades** [comment]
Nice, thanks
