### ISSUE TITLE
Broken hover on links in StaffCP footer

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2799]
https://user-images.githubusercontent.com/26070412/171320160-04e1ffa6-9eb7-42d7-8846-ee4b91eccb95.mov

No idea where this could have come from, possibly the sidebar change by Padow, usage of Yarn by me..?

**Comment by samerton** [comment]
Can't reproduce on latest dev code

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/commit/eba881731a3b4f03458f94d2f1f9798ef3ced9a1
