### ISSUE TITLE
[Request] Account Association to Verify Players

### ISSUE THREAD

**Issue by kohle** [NamelessMC/Nameless#28]
Using http://mcassoc.lukegb.com/ this would make sure that when a player signs up on the website they are entering their real user details.

So for signups, the player would associate their account and that will become their website login; they would just need to enter a password that they can choose.

I'm not sure how up to date the mcassoc is, but since it just uses skin data I imagine it would be fine?

**Comment by samerton** [comment]
Thanks for the suggestion!

I've been thinking of adding the following three options:
- Ingame /register command (in progress with the official Nameless server plugin)
- mcassoc 
- Authenticating with Mojang servers with the user's credentials (obviously the user details would only be passed on to authenticate, they would not be stored in any way)

Obviously it would then be up to the user as to which they choose, if any.

**Comment by Kohle** [comment]
The first two methods are definitely the best/safest, with the authenticating on Mojang's servers being the easiest. The issue is now that you're asking players to trust their credentials to a third party... something that would probably be best avoided.

**Comment by samerton** [comment]
That's true, however I'd like to add the option just in case people would like to use such a method.

**Comment by JayBreeze** [comment]
I wouldn't recommend the third option, server owners could just as easily add a method to save the username/password to a txt file

**Comment by kohle** [comment]
Woo! :grinning:

**Comment by BlackBeltPanda** [comment]
How do I enable the mcassoc option?

**Comment by samerton** [comment]
@BlackBeltPanda Oops, looks like the file which allows for the configuration of mcassoc was left out of the commit for some reason, and as a result it's not in the upgrade files. 
I've updated the release and the upgrade files, and the file in question will also be in 1.0.13. If you'd like to configure mcassoc now, you can reinstall the upgrade file (it will have to be a manual download from [here](https://worldscapemc.co.uk/nl_core/nl1/updates/1012.zip), simply reuploading the files will work as no upgrade script is required) and a link will then appear in the AdminCP -> Minecraft tab. Sorry!
