### ISSUE TITLE
I can add a Swedish Language [UNDER PROGRESS]

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#281]
I can add a Swedish language for you!
im working on it, tell me if you need it or not!

**Comment by partydragen** [comment]
We want every language we can get :D

**Comment by IsS127** [comment]
ok :D im working on swedish

**Comment by samerton** [comment]
A Swedish translation would be great, thanks!

**Comment by IsS127** [comment]
np

**Comment by IsS127** [comment]
Sorry.. i totally forgot about this.
Ill do this sometime later for v2
