### ISSUE TITLE
Captcha theme

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2816]
### Describe the feature

Make in registration tab (staffcp) a switch that you can toggle dark/white mode. [reCaptcha2](https://developers.google.com/recaptcha/docs/display#render_param) & [hCaptcha](https://docs.hcaptcha.com/configuration/#hcaptcha-container-configuration). **You can assign me to the issue.** *this is for the next release and not pr13.*

**Comment by partydragen** [comment]
We was not supposed to do any new features or reworks after pr13 thought, only bug fixes to make sure v2 being table and modules and templates to be same so they update for pr13 with then also works for v2

**Comment by samerton** [comment]
I've added this to the v2 milestone as it's a nice small change we can squeeze in
