### ISSUE TITLE
Installer is broken

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless#2817]
### Describe the issue

New installation on Pebblehost with Jenkins build 544, issue since at least build 501. An existing installation exists under separate directory and database.

Everything works until Database Configuration. In build 501 the progress wheel would hang, but it completed this time with build 544. However, in both builds the database has missing content; only 7 tables were generated. Proceeding to Site Configuration, filling out the fields and hitting proceed results in a red error stating:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_nameless_test.nl2_settings' doesn't exist`

### NamelessMC Version

2.0.0-pr13

### To Reproduce

PHP 7.4+
PHP MySQL
PHP PDO
PHP XML
PHP MBString
PHP GD
PHP cURL
PHP Exif
PHP JSON
Core Writable /core
Core Config Writable /core/config.php
Core Email Writable /core/email.php
Cache Writable /cache
Template Cache Writable /cache/templates_c

### Additional Information

Friendly URLs enabled

**Comment by Aberdeener** [comment]
Thanks for the report,
Earlier today a commit was done to show a more detailed message during database creation during installation.

Can you get a fresh zip, and in index.php on line 13, remove the `//` so that `'DEBUGGING'` is defined.
Then, try to load the installation page and complete the steps until you should get a massive message after the database configuration part, send a screenshot/paste of this whole message here!

**Comment by PikaMug** [comment]
Deleted directory, database, and browser cookies - starting from scratch. Uploaded build 546.

There was no message after database configuration. Went straight to completion:

![db](https://user-images.githubusercontent.com/2267126/171788100-732a31b7-68e5-4c00-9a8e-306e97aae29c.png)

Same error after site configuration:

![site](https://user-images.githubusercontent.com/2267126/171788118-50e17bb2-7dc8-4378-8c7c-6fdc8181350e.png)

**Comment by Aberdeener** [comment]
Can you screenshot all of the contents of the nl2_phinxlog table?

**Comment by PikaMug** [comment]
Message supplied via Discord.

**Comment by Aberdeener** [comment]
Fixed with https://github.com/NamelessMC/Nameless/commit/f40c53050b60db5d532b14109f3d0724eac5b0d5
