### ISSUE TITLE
Strange behavior from visiting URL with corresponding folder

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless#2819]
### Describe the issue

Using Jenkins build 555 (commit 3d87090cec74f6c21c0069b5aa7e18c6a85aaacf). ~~It seems using a Page Path of `/custom` breaks functionality, as changing it to `/customs` or any other path works fine.~~

### NamelessMC Version

2.0.0-pr13

### To Reproduce

~~1. Go to Admin control panel
2. Custom Pages
3. Create a page with Page Path `/custom` with full page permissions~~
4. Visit `example.com/subdirectory/custom` page in browser

### Expected Behaviour

Page should probably return a 403, or load using custom Page Content field if applicable, instead of (seemingly) the root directory's index.php file.

### Additional Information

Nameless is installed in a subdirectory. Also occurs on pr12.

**Comment by PikaMug** [comment]
Actually, it seems like this is not related to custom pages. Going to any URL that has a corresponding Nameless directory just tries to load the root index.php file instead (I say "tries" because elements like images don't load). To clarify, the following paths are affected:

- example.com/subdirectory/cache
- example.com/subdirectory/core
- example.com/subdirectory/custom
- example.com/subdirectory/modules
- example.com/subdirectory/scripts
- example.com/subdirectory/uploads
- example.com/subdirectory/vendor

**Comment by partydragen** [comment]
It return 403 forbidden, as you visit a folder path that i no longer controlled my NamelessMC and something we can't handle other than those htaccess file

I know there is possible to make custom 403 forbidden pages but that not within namelessmc itself

**Comment by PikaMug** [comment]
Resolved, .htaccess file was unknowingly altered.
