### ISSUE TITLE
The Staff Application

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#282]
Could you make so the Staff Application sends mail to the staff when someone has submitted a application?

**Comment by partydragen** [comment]
Staff get a alert so its no point to use mail? If you don't get alert some things is wrong with your website

**Comment by IsS127** [comment]
i know but sometimes im not active on my website.

**Comment by samerton** [comment]
In the future (possibly version 2.0), it's planned to have the ability to decide whether you want to receive emails for alerts or not.
