### ISSUE TITLE
Cant install Cobalt Theme on new Version

### ISSUE THREAD

**Issue by ZeroOneVBS** [NamelessMC/Nameless#2825]
### Describe the issue

Hey, I cant install the Cobalt theme on the new Version,
when I go to the Templates Site and Click Install, it goes to an Error Page

Thats what it says:
Uncaught Exception
Translation file not found
(File: /var/www/vhosts/nightcraftmc.com/httpdocs/vendor/samerton/i18next/src/i18next.php)

Need help here

### NamelessMC Version

2.0.0-pr13

### To Reproduce

Go to the Admin Control Panel
Click on Templates
Press "Install" button

### Expected Behaviour

The cobald theme shows up as it got installed

**Comment by partydragen** [comment]
The reason is because the template is not updated to support pr13, only install modules & templates that support pr13
