### ISSUE TITLE
Use Util::getProtocol in index.php

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2828]
In index.php
```php
if ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')) {
    ini_set('session.cookie_secure', 'On');
}
```
should be replaced with
```php
if (Util::getProtocol() === 'https') {
    ini_set('session.cookie_secure', 'On');
}
```

but Util is not available here. Does anyone have suggestions? I imagine ini_set needs to be called quite early, before anything sets cookies.

**Comment by Aberdeener** [comment]
I think technically there is no reason for the composer autoloading to be done within init.php...

We could move the vendor autoload require line to the top of index.php so we can use classes earlier on like this
