### ISSUE TITLE
Top banner doesn't change

### ISSUE THREAD

**Issue by abhisantos** [NamelessMC/Nameless#2836]
### Describe the issue

I am using the latest version, after going to Layouts > Images and uploading new banner image, it does not change on the site.
I also replaced the image file in  /uploads/template_banners/homepage_bg_trimmed.jpg

But no success, site banner stays the same.

https://prnt.sc/Ft_cVdJm5KYQ

https://prnt.sc/ROBbTRQ_Pqgd 

### NamelessMC Version

2.0.0-pr13

### To Reproduce

Layouts > Images

### Screenshots

https://prnt.sc/Ft_cVdJm5KYQ

https://prnt.sc/ROBbTRQ_Pqgd

**Comment by PadowYT2** [comment]
Mind sending your website's url?

**Comment by abhisantos** [comment]
Sure, https://minecraftpc.com.br

Em ter., 7 de jun. de 2022 às 01:33, PadowYT2 ***@***.***>
escreveu:

**Comment by PadowYT2** [comment]
The sidebar changed for me, that was cache. Ctrl+shift+r

**Comment by abhisantos** [comment]
> The sidebar changed for me, that was cache. Ctrl+shift+r

It worked now! 
I am using opera and even with hard refresh is not changing, but in Chrome it changed.

Thank you for the help!

**Comment by partydragen** [comment]
The images page is broken in pr13, i fixed it with 2 different commits yesterday and day before
