### ISSUE TITLE
Database Issues

### ISSUE THREAD

**Issue by HyperfireRS** [NamelessMC/Nameless#2838]
### Describe the issue

When I set up my database, it just hangs at the setting up database screen.

### NamelessMC Version

2.0.0-pr13

### To Reproduce

1. Install namelessmc
2. Enter DB Details
3. watch it happen

### Expected Behaviour

it to work

**Comment by supercrafter100** [comment]
Could you share a bit more details about what the error actually is? I cannot encounter any errors. A screenshot of the error itself would be useful and some other context like database software and version, operating system, etc.

**Comment by HyperfireRS** [comment]
I'm hosting on profreehost, i have no idea of any of those details. I'm using mysql.

**Comment by Aberdeener** [comment]
Can you send a screenshot of the page hanging at the DB screen? 😄

**Comment by HyperfireRS** [comment]
> Can you send a screenshot of the page hanging at the DB screen? 😄

it just hangs there, it doesnt throw anything, just the initializing database screen.

**Comment by PadowYT2** [comment]
> > Can you send a screenshot of the page hanging at the DB screen? smile
> 
> it just hangs there, it doesnt throw anything, just the initializing database screen.

Anything in browser console?

**Comment by Aberdeener** [comment]
> > Can you send a screenshot of the page hanging at the DB screen? 😄
> 
> it just hangs there, it doesnt throw anything, just the initializing database screen.

Yep, that is what I asked for a screenshot of.

**Comment by HyperfireRS** [comment]
its just giving me a fatal error now, here's the site.
http://hcforums.ezyro.com/

ill get it reinstalling and setting it up again so i can get the ss

ok here ya go, weird error
![image](https://user-images.githubusercontent.com/76081146/172873178-f7f24eed-d472-4cb6-8a99-f34c1c783494.png)
![image](https://user-images.githubusercontent.com/76081146/172873177-30e77a47-795c-40b4-a16d-46e6893286a7.png)

**Comment by BaxAndrei** [comment]
Do you have any log/error.log/error_log? That might help. Also what PHP version do you have?

**Comment by HyperfireRS** [comment]
> Do you have any log/error.log/error_log? That might help. Also what PHP version do you have?

php version is 7.4.8

i do not have an error_log

**Comment by Derkades** [comment]
Please check for files in `/cache/logs` (in the NamelessMC directory). Status code 500 could be sent by namelessmc or it could be caused by a websever configuration

**Comment by HyperfireRS** [comment]
> Please check for files in `/cache/logs` (in the NamelessMC directory). Status code 500 could be sent by namelessmc or it could be caused by a websever configuration
[fatal-log.log](https://github.com/NamelessMC/Nameless/files/8879911/fatal-log.log)

yeah i've got a few files there, i'll send my fatal.log

**Comment by PadowYT2** [comment]
This was fixed see #2822

**Comment by Aberdeener** [comment]
> This was fixed see #2822

We aren't certain this is the same problem, or else we would have referred them there

**Comment by HyperfireRS** [comment]
I've tried this commit fix, let's see if it works.

**Comment by HyperfireRS** [comment]
it did not work

**Comment by Aberdeener** [comment]
Can you please send the logs...?

**Comment by HyperfireRS** [comment]
i did?
> > [fatal-log.log](https://github.com/NamelessMC/Nameless/files/8879911/fatal-log.log)

**Comment by HyperfireRS** [comment]
sorry i could have made it more obvious

**Comment by samerton** [comment]
The error states that the `phinxlog` table doesn't exist - I've experienced something like this previously and it turned out I was using incorrect database details.

cc developers - we could do with checking to make sure the database connection check to ensure username/password/database combination is valid still works

**Comment by supercrafter100** [comment]
> using incorrect database details

Wouldn't it throw an error during the connecting to the database in that case?

**Comment by Derkades** [comment]
The phinx migration system didn't do anything with the output, hiding any connection errors. This has been fixed for the next release.

There was a database connection check using mysqli, this has now been rewritten using DB::getCustomInstance in #2850 . If I remember correctly I tested it for the PR and it worked.

**Comment by HyperfireRS** [comment]
ok so how do i fix this

**Comment by HyperfireRS** [comment]
hello?

**Comment by supercrafter100** [comment]
Have you tried clearing your browser cookies, clearing your database, removing `core/config.php` (if it exists) and then attempting to re-install?

**Comment by Derkades** [comment]
The "Config unavailable" issue that affected some hosting providers seems to be fixed for 2.0.0 now (someone who got the issue every time in support no longer got it with the upcoming version).

Hopefully you have enough patience to wait for the next version

**Comment by HyperfireRS** [comment]
> The "Config unavailable" issue that affected some hosting providers seems to be fixed for 2.0.0 now (someone who got the issue every time in support no longer got it with the upcoming version).
> 
> Hopefully you have enough patience to wait for the next version

Can do. Thanks for the help, best of luck to you and the team.
