### ISSUE TITLE
Need help with Infractions

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#284]
Hey can you help me with infractions? i want it to view which server it got punished on, im using bungeeadmintools, ive added which server it is but when you click and it shows the ban idk how to get it.. lets call the ban page server show the ''first function'' and the ban id page server showing thing ''second function''. the first file is from the addons infractions.php and the second one is from the pages  folder. In the first function it works fine for me i figured that out. Ive added in the second function to say server: but idk how to get it it from the database. what code should i put for it to show?
[Infractions.zip](https://github.com/NamelessMC/Nameless/files/337581/Infractions.zip)

**Comment by samerton** [comment]
Can you try replacing **pages/infractions.php** with [this code](https://gist.githubusercontent.com/samerton/86ba8c46d405ff761a0fa1f479c5b5b6/raw/258528bc17e4a538afd01df44e49b12c7ac3c3f8/infractions.php)? It's untested, so please back up the file first.

**Comment by IsS127** [comment]
Works really fine! i recommend this code for bungeadmintools beacuse its bungeecord xD you should add it when people choose bungeeadmintools it changes to this script.

**Comment by IsS127** [comment]
Also could you maybe do like the webinterface? it could search for users? and possibly when the plugin is out, make it unban/unmute/untempban

**Comment by IsS127** [comment]
is there any way to do that? the search thing?

**Comment by samerton** [comment]
This is a possibility for the future, probably a bit further down the line (closer to version 1.2 instead of 1.1).

**Comment by IsS127** [comment]
Cant u make a simple way? It would view the page Its in like the browser page, anything that could show it, would be alot easier to view beacuse of My staff apps, Its a question that includes punishments
