### ISSUE TITLE
Option to disable cookie consent popup

### ISSUE THREAD

**Issue by J4C0B3Y** [NamelessMC/Nameless#2840]
### Describe the feature

Add the option to disable this popup on the bottom of the screen:

![image](https://user-images.githubusercontent.com/69947689/172552687-601a2b33-7ba0-409a-91d5-2d1c42954112.png)

I want to keep the cookie notice page and this popup though:

<img src="https://user-images.githubusercontent.com/69947689/172553099-e0b2f904-5fe7-4d7f-83e0-d321f3f006fd.png" width="300px" />

**Comment by Derkades** [comment]
I agree: https://github.com/NamelessMC/Nameless/issues/2502
