### ISSUE TITLE
LANGUAGE null during API request

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2842]
Reported by someone in Discord. The website was sending the following API response:
```
{"nameless_version":"2.0.0-pr13","locale":null,"modules":["Core","Forum"]}
```
which means LANGUAGE is null, even though it shouldn't ever be?

**Comment by Derkades** [comment]
This happened after an upgrade from pr12, changing languages fixed it. Could it be a migration issue?

**Comment by partydragen** [comment]
NamelessMc website had empty/null language cache with i reset a few days ago

**Comment by Aberdeener** [comment]
Is there anything we can do for existing sites to "fix" this? Doesn't seem like it.

**Comment by partydragen** [comment]
bigger question is how did it fail to regenerate the cache in first place?

**Comment by Aberdeener** [comment]
That is very deep indeed, but I don't see how we can backport anything here. Going to close for the meantime.

**Comment by Derkades** [comment]
The workaround of switching languages should be easy enough
