### ISSUE TITLE
Error when Creating  / Cloning a Group (v2-13)

### ISSUE THREAD

**Issue by 1day2die** [NamelessMC/Nameless#2843]
### Describe the issue

![image](https://user-images.githubusercontent.com/8725848/173033843-4a56a6f1-e9f2-46e4-9542-7e13f057e338.png)

Whenever creating / cloning a group.
Even if all fields have a value

### NamelessMC Version

2.0.0-pr13

### To Reproduce

Go to admin CP
Groups
create / clone a group
click on save

### Expected Behaviour

create / clone a group

### Screenshots

uuh
![image](https://user-images.githubusercontent.com/8725848/173033962-10abd19c-2912-4d73-bd87-a60c351b88fc.png)

**Comment by partydragen** [comment]
Its a bug with existing websites that upgrade to pr13, The column was removed in pr13 but still exist in older installations

**Comment by Aberdeener** [comment]
Hi there, to fix this use a tool like PHPMyAdmin to edit the `nl2_groups` table and remove the `group_html_lg` column.
Let me know if you have more questions 😄
