### ISSUE TITLE
`Util::getProtocol()` returns null on a normal webserver config

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2846]
When accessing my local site with http; `http://localhost/index.php....`, `Util::getProtocol()` is returning null.
When I access the same site with https, it returns `'https'` as expected.

Could this be something with Laravel Valet? What can I share that makes this debugging process easier?

**Comment by Derkades** [comment]
Instead of returning null, would it make sense to just return `http` if the protocol is unknown?

**Comment by Aberdeener** [comment]
Thanks!
