### ISSUE TITLE
Changing captcha

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2847]
### Describe the issue

When you put `Captcha Site Key` & `Captcha Secret Key` that are both reCaptcha2 and change to reCaptcha3 it will show an `Uncaught Error`

### NamelessMC Version

Development version

### Expected Behaviour

It should show an error and not a `Uncaught Error`

### Screenshots

![https://cdn.padow.ru/P3jt](https://cdn.padow.ru/P3jt)
![https://cdn.padow.ru/pnDs](https://cdn.padow.ru/pnDs)

**Comment by Aberdeener** [comment]
👋🏼 Can't duplicate this at all.

Can you send a screen recording of you doing the actions which lead to breakage?

**Comment by PadowYT2** [comment]
edited

**Comment by Aberdeener** [comment]
Cannot replicate:

https://user-images.githubusercontent.com/26070412/174948349-32b3f3fd-ef07-4233-a2e2-5592f45b3e98.mov

Am I doing something differently here?

**Comment by Aberdeener** [comment]
I have seen a few people face this issue, even when their credentials are 100% correct. As a compromise, I think we should change this to an orange *warning* message - but still update their credentials anyways. This way if the request fails for some reason they are still able to update the credentials

**Comment by samerton** [comment]
> I have seen a few people face this issue, even when their credentials are 100% correct. As a compromise, I think we should change this to an orange _warning_ message - but still update their credentials anyways. This way if the request fails for some reason they are still able to update the credentials

Sounds good to me -updated as follows:
<img width="2258" alt="Screenshot 2022-08-05 at 19 12 36" src="https://user-images.githubusercontent.com/1812544/183136742-eb5bb51a-f875-4574-8133-7441619f3eba.png">
