### ISSUE TITLE
Forum broken with latest commits

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#285]
forums is broken after latest commit by Root3287
We can't check topics

Parse error: syntax error, unexpected '.' in /home/lesstest/public_html/pages/forum/view_topic.php on line 304

EDIT: After i fixed the problem in my file the whole page is broken.... See http://test3.namelesshosting.com/forum/view_topic/?tid=3

**Comment by IsS127** [comment]
np for telling you

**Comment by IsS127** [comment]
should we add <span>?

**Comment by IsS127** [comment]
found how to fix, in the facebook sharing in view_topic.php at .$tid'> add a dot beside the .$tid should look like this .$tid'>
