### ISSUE TITLE
Discord Integration not syncing roles

### ISSUE THREAD

**Issue by HarmHoog** [NamelessMC/Nameless#2857]
### Describe the issue

When I change a user's role in Discord it is not processed in the website. In the Discord I addressed this issue and it was confirmed in the logs that the Discord bot does send the roles correctly to the website (log below) and the group syncing setup was correct as well.

`link_1      | 2022-06-14T10:27:48.046108657Z [pool-1-thread-6] INFO Group sync discord->website - Sending user roles to website: guildid=985874233659908096 userid=985993876714168360 roles=[985994710755708979]
link_1      | 2022-06-14T10:27:48.537337193Z [pool-1-thread-6] INFO Group sync discord->website - Sucessfully sent roles to website: guildid=985874233659908096 userid=985993876714168360`

The website is not producing any errors.

### NamelessMC Version

2.0.0-pr13

### To Reproduce

1. In the Discord set a user's role
2. The website should sync the role correctly

### Expected Behaviour

The Discord group should sync with the website group.

### Additional Information

For if it matters: The pr13 installation was obtained by upgrading from pr12.

**Comment by HarmHoog** [comment]
Just found something that might be related. When I remove a user's group in the staffcp it gives the following error `[2022-06-14, 15:24:17] /var/www/particle-forge.com/core/classes/Core/User.php(647): Cannot assign null to property User::$_main_group of type Group
`. Seems that it has difficulty changing a group.

**Comment by HarmHoog** [comment]
Some more testing: When adding a role via Discord it gets processed. However removing the role doesn't work. The other way around doesn't work at all (trying to add or remove groups to a user in the staffcp is not processed at all in Discord).

**Comment by supercrafter100** [comment]
Perhaps fixed with #2920 ?

**Comment by Aberdeener** [comment]
Assuming so, it's been fixed for everyone else. Feel free to reopen if that fix doesn't solve it for you
