### ISSUE TITLE
Avatar service bug! 

### ISSUE THREAD

**Issue by PiglinPlayz** [NamelessMC/Nameless#2858]
### Describe the issue

getting an error after changing my website avatar service. 

I cant get in to my site or staff cp so what do i do 

https://playpiglin.net/

`Uncaught TypeError
Return value of AvatarSourceBase::getRelativePerspective() must be of the type string, null returned
(File: /home/piglin/public_html/core/classes/Avatars/AvatarSourceBase.php)`

### NamelessMC Version

2.0.0-pr13

### To Reproduce

GO to staff cp
The go to avatar configuration 
then click CravatarAvatarSource or any other source 
then save 
then reload the page and your locked out of your site and cnat change it back unless you change it in the DB

### Expected Behaviour

Should get minecraft avatar or full body as what i set it to.

### Screenshots

<img width="1189" alt="Screen Shot 2022-06-14 at 7 41 55 AM" src="https://user-images.githubusercontent.com/84807134/173579591-d44a49db-db92-4db6-ae63-d72955885479.png">
<img width="1189" alt="Screen Shot 2022-06-14 at 7 41 41 AM" src="https://user-images.githubusercontent.com/84807134/173579592-c5fa4e93-c724-46ad-8792-d5b163decc3b.png">

**Comment by Aberdeener** [comment]
Hi there, thanks for the report.
I am unable to duplicate this issue, but I have added better logging for when this happens.

Can you implement the changes in this file: https://github.com/NamelessMC/Nameless/commit/e769c28996fa91a55c28aeed75fbd3353b5cee66#diff-1eadc09c640b6b7465e2fbf12b549c21b30b2dbd9670b2d97beb480c0fd3e213, and then try to replicate the issue again?
It should give a more descriptive error message to help with debugging.

**Comment by PiglinPlayz** [comment]
[Avatar source:](https://www.toptal.com/developers/hastebin/nuyobokiqa.php)
[Avatar Source Base:](https://www.toptal.com/developers/hastebin/javomaqowe.php)
[after following this github link:](https://github.com/NamelessMC/Nameless/commit/e769c28996fa91a55c28aeed75fbd3353b5cee66#diff-1eadc09c640b6b7465e2fbf12b549c21b30b2dbd9670b2d97beb480c0fd3e213)
i was not able to solve the issue. there was just more of an issue. 

[website:](playpiglin.net)

**Comment by Aberdeener** [comment]
Can you screenshot the exception that happens when you visit your site now? It should be different

**Comment by PiglinPlayz** [comment]
<img width="1440" alt="Screen Shot 2022-06-18 at 4 38 22 PM" src="https://user-images.githubusercontent.com/84807134/174457760-f4bac96d-9953-4d36-9d3b-8fd2bc940ca6.png">

**Comment by Aberdeener** [comment]
Hmm, did you make only the exact changes in the change I linked you?
An error like that would suggest some sort of low-level syntax error

**Comment by PiglinPlayz** [comment]
New error( i think).
[https://playpiglin.net/](https://playpiglin.net/)
<img width="1197" alt="Screen Shot 2022-06-23 at 9 14 52 AM" src="https://user-images.githubusercontent.com/84807134/175307401-27608b45-c540-4751-bd8d-e87aab241d00.png">
<img width="1197" alt="Screen Shot 2022-06-23 at 9 15 18 AM" src="https://user-images.githubusercontent.com/84807134/175307489-60b3b5ae-9f48-4476-8268-63e500f57c16.png">

**Comment by PiglinPlayz** [comment]
After wiping and re installing the db and files the same error popped up. This may be an error that happens upon fresh install. im gonna probs head back to pr-12 since i know it work.

**Comment by Aberdeener** [comment]
This has been fixed with https://github.com/NamelessMC/Nameless/commit/3cb6ecaa69bd6bf902a930a54019ea8b1fd3c032

This happened because we try to assign a global URL for MC avatars *before* the modules were loaded on the maintenance page.

**Comment by PiglinPlayz** [comment]
after doing the changes made in 
https://github.com/NamelessMC/Nameless/commit/3cb6ecaa69bd6bf902a930a54019ea8b1fd3c032
i now get a 500 error 
<img width="882" alt="Screen Shot 2022-06-28 at 10 34 06 AM" src="https://user-images.githubusercontent.com/84807134/176220485-72ebe60d-942b-4821-8f0b-42e602be7703.png">

i have my init file and my error log in the in a [paste.gg](https://paste.gg/p/anonymous/48c2f9e0c20e4248b205964cc15a2828)
