### ISSUE TITLE
Messages page wrong date (Not sure if this is a bug)

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#286]
### Template:
* What kind of issue is it (Question, Bug, etc.)?  Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? Messages page has a wrong date
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://prntscr.com/bmabjf
* Do you have an idea how or where the issue occurs? I am not sure

**Comment by IsS127** [comment]
i am not sure but i think it might be you're os.

**Comment by samerton** [comment]
Are these new private messages, or were they created before upgrading your site?

**Comment by Ariuw** [comment]
They are new private messages

**Comment by TiTo-418** [comment]
This is happening with infractions too

**Comment by samerton** [comment]
A commit a few days ago altered the way dates are displayed on the messages page, hopefully the upcoming version 1.0.11 might help with your issue.

**Comment by samerton** [comment]
I'll mark this as closed, as it should be fixed in 1.0.11.
If the issue persists after 1.0.11 is released, please feel free to re-open.

**Comment by Ariuw** [comment]
This as been fixed ^^
