### ISSUE TITLE
Unable to set site configuration

### ISSUE THREAD

**Issue by xiaobao4909** [NamelessMC/Nameless#2863]
### Describe the issue

Unable to set site configuration

### NamelessMC Version

2.0.0-pr13

### To Reproduce

1.Error during installation to site configuration

### Expected Behaviour

normal setup

### Screenshots

![image](https://user-images.githubusercontent.com/92622663/173824805-d38bf2b3-a12b-4aca-a761-50565bc9b0f1.png)

### Additional Information

nothing

**Comment by PadowYT2** [comment]
See #2822
