### ISSUE TITLE
Automatically skip database configuration

### ISSUE THREAD

**Issue by xiaobao4909** [NamelessMC/Nameless#2864]
### Describe the issue

Automatically skip database configuration

### NamelessMC Version

2.0.0-pr13

### To Reproduce

Unable to enter the database configuration page after installing the basic configuration

### Expected Behaviour

Normal configuration database

### Screenshots

nothing

### Additional Information

WinServer2019

**Comment by PadowYT2** [comment]
There's no skip, any videos?

**Comment by supercrafter100** [comment]
If you are attempting to re-install after a previous attempt, please make sure that you do the following:

1. Clear the database if you haven't already
2. Clear your browser cookies so it starts back from step 1 (likely you forgot this)
3. Start back from step 1
