### ISSUE TITLE
Website->Discord group sync issues

### ISSUE THREAD

**Issue by MakeItReaal** [NamelessMC/Nameless#2865]
Dear Aberdeener,

The group sync on the discord roles currently has some issues when you change your rank in the game.
Your roles get set on the forums to the correct rank but on discord  it only removes rank and doesn't add them.

I had contact with Derkades he said i should create an issue for this on github.
Can you look in to this?

Kind regards!

**Comment by Aberdeener** [comment]
Possible fix:tm: in https://github.com/NamelessMC/Nameless/commit/27fcb265a2140857357d3e1ef1d2b3550649e045

Waiting to hear back from users. If they are not successful I will setup an MC server and Discord server this weekend to do more extensive testing. I really want to banish all issues with group sync so we can forget about it for a while 😄

**Comment by HarmHoog** [comment]
For me, these changes don't seem to fix it (pre-13 with these changes). However, I also have the issue that removing a role via Discord also doesn't get synced with the website whilst the other way around does.

**Comment by DominikSLK** [comment]
> For me, these changes don't seem to fix it (pre-13 with these changes). However, I also have the issue that removing a role via Discord doesn't get synced with the website whilst the other way around does.

same

**Comment by Gyztor** [comment]
> Possible fixtm in [27fcb26](https://github.com/NamelessMC/Nameless/commit/27fcb265a2140857357d3e1ef1d2b3550649e045)
> 
> Waiting to hear back from users. If they are not successful I will setup an MC server and Discord server this weekend to do more extensive testing. I really want to banish all issues with group sync so we can forget about it for a while smile

tested and seems to work stably when changing roles on discord, they reflect properly on the website now but changing on the website does not reflect properly to discord whether its removing or adding roles. so discord->website seems to be doing good website->discord is just ded this is also on latest pull from github at time of writing ( for reference: 5eb5db163ed59a5a5a2ac61bc8c2e3977b9f62c8 )

**Comment by DominikSLK** [comment]
#2920 fixes it for me :D 🎉

**Comment by Aberdeener** [comment]
> #2920 fixed it for me :D 🎉 

Thank you so much for letting us know! Great to hear!

**Comment by Aberdeener** [comment]
> The website keeps sending /roleChange requests repeatedly: https://paste.rkslot.nl/asefipoyoc.txt
> 
> 
> 
> A few issues with this:
> 
> - The website keeps sending role remove requests, even though it has already send those requests before.
> 
> - The website makes a request to /roleChange individually for every role, instead of making a request with all roles to add or remove. This makes it very slow.

The first issue is solved with new PR

Unfortunately the second issue is unfixable I believe, due to how group sync works, it sends 1 request per change to the discord bot...
If we didn't have this dynamic system and we could hardcode some stuff then it would be much easier to do. There might be some super hacky ways using PHP __destruct magic method on the Discord class to batch them - this is something I can look at later on for sure
