### ISSUE TITLE
Language class throwing "File not found" for modules when they don't support a language yet

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2870]
Reported by Drew;
- Make a new language instance for a module
  - ```php
     $language = new Language('path/to/module/language/json/files', 'short_code_the_module_doesnt_have_language_for');
    ```
- Use that instance to attempt to get a string
  -  ```php
      $language->get('foo', 'bar');
      ``` 
- Ooo and Ahh at the exception

**Comment by Aberdeener** [comment]
@CqldFire I cannot duplicate this:
```php
$language = new Language(ROOT_PATH . '/modules/Forum/language', 'baz');
dd($language->get('foo', 'bar'));
```
`"foo/bar"` is correctly printed on the screen.

Is there any additional context you can provide that might be different than this example above? Are you doing anything fancy for your module/template languages?

**Comment by CqldFire** [comment]
```
$cobalt_language = new Language(ROOT_PATH . '/custom/templates/Cobalt/template_settings/language', LANGUAGE);
$cobalt_language->get('cobalt', 'news_button');
```

Using this syntax. Should this be changed?

**Comment by Aberdeener** [comment]
Hmm that looks fine - you don’t have to pass LANGUAGE as the second param
though.

Can you screenshot the exception that happens when you do that? As well as
each of the frames

**Comment by CqldFire** [comment]
I added all of the language files and am now unable to reproduce the issue. Updating cobalt today or tomorrow, will report if buyers still experience the issue.
