### ISSUE TITLE
This is a suggestion for a future security update

### ISSUE THREAD

**Issue by WheatenCactus** [NamelessMC/Nameless#2871]
### Describe the feature

Hello i was thinking we need to make an update that increases security first of all staffcp should have a seperate account from the website itself. Like maybe a seperate database. Setting the option of login with username and email, instead of email should make it so you can have it as that in the website itself but in the panel you can choose if the login for that is only email not username.

Registring to the staff panel should be somewhat harder for example they must add a verification code that only the owner group/role can generate from staffcp and its one-time usable

**Comment by WheatenCactus** [comment]
To clear up the email and username part to avoid any confusion i meant this:

There is a setting in staff cp that allows you to make it so when users login they can 
1. Use thier minecraft username and password
2. Use thier email and password
3. Use either the email or the username and password.

Now what i mean here with making staffcp and website itself seperate is that lets say members can login with both email or username. But in staffcp instead of it showing the same thing as site. You can make it so staff cp is email only for example

**Comment by IsS127** [comment]
Hello,

You're suggesting quite a several ideas in one post... Could you be more clear about what it is you think is a "security" feature?

A separate login method for the username/email for StaffCP would cause more confusion for the user, considering they would be faced with two different methods. It is less confusing having the same option website-side instead. Also, it would not make a massive difference regarding security. The email/username is still visible in the Account Settings.

From what I understand, you want separate accounts for the StaffCP. Same here, I can't see a more efficient security feature having this feature. It would also cause too much internal change.

Regarding a verification code for StaffCP, 2FA has been suggested in #2408.
