### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'short_code' in 'field list'

### ISSUE THREAD

**Issue by ElMrPotato** [NamelessMC/Nameless#2874]
![image](https://user-images.githubusercontent.com/81596929/174419220-88070be1-979b-4eed-806e-1fd81eba843d.png)

**Comment by PikaMug** [comment]
Try adding the column to your database with 'ALTER TABLE nl2_languages ADD `short_code` VARCHAR(64) NOT NULL'

**Comment by Derkades** [comment]
I would recommend clearing your database, deleting core/config.php and running the installer again in a private/incognito browser session
