### ISSUE TITLE
Catch exceptions in modules tab

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless#2875]
### Describe the issue

When updating Nameless, some or all modules are bound to become outdated. An uncaught exception is thrown.

### NamelessMC Version

2.0.0-pr13

### To Reproduce

1. Install pr12 with compatible modules
2. Update to pr13
3. Click on 'Modules' in admin control panel

### Expected Behaviour

Rather than show exception, catch any in this tab and show a more user-friendly message.

### Screenshots

![translation](https://user-images.githubusercontent.com/2267126/174490016-d3f3c4bc-a424-4952-b2ff-49412a2a38f9.png)

### Additional Information

Example of a good message could be like the Discord bot says, "Translation file not found - Ensure that you don't have any modules/templates installed that are not compatible with pr13. You can remove modules by going to the /modules directory and deleting (or moving) any outdated modules. For templates you can delete them in the /custom/templates directory."

**Comment by PadowYT2** [comment]
How is it a bug? It is an enchanment

**Comment by partydragen** [comment]
Catch exceptions wont work due after that file is fixed then a another issue will popup with is not able to catch due of a missing debug info function

**Comment by PikaMug** [comment]
> How is it a bug? It is an enchanment

I agree, feel free to change the label.

> Catch exceptions wont work due after that language issue then a another issue will popup with is not able to catch due of a missing debug info function

Surely a link to the exception could still be provided? Or instead of a blanket solution, only catch common exceptions with known solutions such as this.

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/pull/3143

Note this will only apply to disabled modules, or when installing a new incompatible module
