### ISSUE TITLE
Sorting on members/users table

### ISSUE THREAD

**Issue by PugaBear** [NamelessMC/Nameless#288]
I'd like to be able to sort the members table by group ID (currently it sorts by group name, alphabetically.  http://i.imgur.com/Jn5gfYL.png). by default, when you load the page- but I cant figure out exactly where any of the sorting is defined. I looked in core/assets/js/tables/dataTables.bootstrap.js and pages/members.php, but couldn't find anything, except maybe [this](https://github.com/NamelessMC/Nameless/blob/master/pages/members.php#L85), but I don't know how i'd build off of that.

If you could just point out where exactly it orders them, or how to, that'd be wonderful c:

**Comment by samerton** [comment]
You'd need to add a new column to the table, containing the group ID (`$group->id`), and the DataTables Javascript file (which is an external library) does the sorting automatically.

**Comment by PugaBear** [comment]
Ah I see! And display:none tags are always my friend :3 Thank you!
