### ISSUE TITLE
TimeAgo problem

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2888]
### Describe the issue

When a user unregistered on the website and his language is Russian/Spanish/Anything else. Will result his language to be shown for everyone

### NamelessMC Version

2.0.0-pr13

### Screenshots

![https://cdn.padow.ru/Nwkq](https://cdn.padow.ru/Nwkq)

**Comment by partydragen** [comment]
Those are cache bugs

**Comment by PadowYT2** [comment]
If you meant browser cache, no. Derkades had the same problem

**Comment by partydragen** [comment]
> If you meant browser cache, no. Derkades had the same problem

Its the NamelessMC cache, its cache the translated text
