### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by PugaBear** [NamelessMC/Nameless#289]
The email option works, but the authentication app one does not- it produces an invalid code every time. ![Image](http://i.imgur.com/ycfcUYL.png)

I can then log in without confirming with two factor. In fact, I (okay some noob) noticed this a few days ago but forgot to report it, and have been logging in via password only ever since with two factor on.

**Comment by Noahkiq** [comment]
no I noticed it >:(

**Comment by samerton** [comment]
I can't reproduce any issues, which authentication app are you using?

> I can then log in without confirming with two factor
Which steps do you take to log in anyway? Everything I've tried refuses to let me log in, provided the code is incorrect.

**Comment by PugaBear** [comment]
Google Authenticator for myself. 

Normal signin process, just as you would without 2FA

**Comment by Noahkiq** [comment]
I'm using the Google Authenticator. I also tried the QR code and text code method, neither worked.

**Comment by PugaBear** [comment]
(Noahkiq is helping me with my website)

**Comment by Noahkiq** [comment]
(I am)

**Comment by PugaBear** [comment]
A little more info: I go to my settings and turn it on, then it takes me to the 2fa login page (screenshot above). I try to enter a code a few times, then give up and return to the home page. At the home page, I am not logged in automatically, but I can simply log in using my username and password.

**Comment by samerton** [comment]
I've just tested with Google Authenticator, and it seems to work fine. Unfortunately I'm really not sure what could be happening, I'm also unable to reproduce issues with being able to log in without inputting a correct code.

**Comment by PugaBear** [comment]
Is there anything I could do to diagnose the error?

**Comment by samerton** [comment]
Would I be able to register on your site to take a look?

**Comment by PugaBear** [comment]
[Go right ahead](https://beta.bn-mc.net/ )

**Comment by samerton** [comment]
I'm thinking this could be a cURL issue, can you replace the contents of **TwoFactorAuth/lib/Providers/Qr/BaseHTTPQRCodeProvider.php** with [this code](https://gist.githubusercontent.com/samerton/c8409f2ab097957cf72379660dc0f521/raw/2198f5d15692fca212260c07614f0a7d89386214/BaseHTTPQRCodeProvider.php), and let me know once you've done that?

**Comment by PugaBear** [comment]
@samerton done

**Comment by Noahkiq** [comment]
can confirm it's still broken

**Comment by samerton** [comment]
Which version of PHP are you running?

**Comment by PugaBear** [comment]
![Image](http://i.imgur.com/axUJohE.png)

**Comment by samerton** [comment]
I'm going to keep trying on my test machines to see if I'm able to reproduce your issue.

**Comment by PugaBear** [comment]
Okay, thank you :)

**Comment by samerton** [comment]
I've taken a look, but I still can't reproduce your issue, and I honestly don't know what could be going on. 
Can you create a new file (anywhere on your webserver) named "test.php", containing [this code](https://gist.githubusercontent.com/samerton/64c3efedd13d62cb94ed3a7d6c65ff19/raw/09154becf924689ac19759c552d063a367ebd6f7/test.php), and then visit the page in your browser and tell me the output?

**Comment by PugaBear** [comment]
@samerton [True](https://beta.bn-mc.net/a)

**Comment by samerton** [comment]
@PugaBear 
Unfortunately I'm totally out of ideas. It's probably best to simply disable the authentication app, which I can work on adding an option for in the near future.

**Comment by PugaBear** [comment]
That's alright, Its not a huge deal, thank you very much for trying :) I'll just remove the 2fa section from the usercp, dont put a rush on it.

**Comment by dasilvaj4** [comment]
In my website i tested and work perfectly.

**Comment by BlackBeltPanda** [comment]
Just had a user report that their Google Authenticator codes stopped working on my site, as well.
