### ISSUE TITLE
White text in text editor when dark mode is enabled

### ISSUE THREAD

**Issue by DevLeven** [NamelessMC/Nameless#2891]
### Describe the issue

In light mode the text in the text editor is black (Which makes sense since everything is white), but in dark mode its white (which makes sense since everything is black). This would be fine if the text editor background wasn't white, since the text is white and the text editor background is white you can't see what your typing, making it harder to make changes.

Video: https://gyazo.com/6437436c4baa9f91a7bb74ad492262f7

### NamelessMC Version

2.0.0-pr13

### To Reproduce

1. Use Default Template for Panel Template
2. Use Dark Mode
3. Go to staffcp
4. Try and use the text editor

**Comment by PadowYT2** [comment]
I cannot reproduce this, the text is dark for me, maybe you have an extension?

**Comment by DevLeven** [comment]
I don't have any extension, im using the default template and don't mess with the files often if at all. This problem only occurs in staffcp so I don't think the template im using is to blame.

> I cannot reproduce this, the text is dark for me, maybe you have an extension?

**Comment by PadowYT2** [comment]
> I don't have any extension, im using the default template and don't mess with the files often if at all. This problem only occurs in staffcp so I don't think the template im using is to blame either.
> 
> > I cannot reproduce this, the text is dark for me, maybe you have an extension?

Can you go to incognito and try to see?

**Comment by Derkades** [comment]
Are you using a browser extension like dark reader?

**Comment by DevLeven** [comment]
> > I don't have any extension, im using the default template and don't mess with the files often if at all. This problem only occurs in staffcp so I don't think the template im using is to blame either.
> > > I cannot reproduce this, the text is dark for me, maybe you have an extension?
> 
> Can you go to incognito and try to see?

Same issue in Incognito, and I don't have any browser extensions.

Video: https://gyazo.com/94b93f2d6d4624aac3af97d88a8f13f9

**Comment by PadowYT2** [comment]
Anything in browser console?

**Comment by Derkades** [comment]
I can only reproduce this if I deliberately set the text color to white. I don't think that's something you have done?
![image](https://user-images.githubusercontent.com/15892014/175778748-7be58ecb-1c7f-4d4b-9d47-d1f1388e6a01.png)

**Comment by DevLeven** [comment]
No I didn't do it myself but it seems someone im working with did. It was to solve the same issue happening when trying to make a post on the forums, since the text is black and the background is black. It's not as bad as the one above, but is still hard to see for some.


![image](https://user-images.githubusercontent.com/43507866/175790212-9dbbf3de-ae7d-4b26-81a9-30a636c73c06.png)

**Comment by Derkades** [comment]
The background shouldn't be dark, where is this? Are you using a custom template?

**Comment by DevLeven** [comment]
> The background shouldn't be dark for exactly this reason, on what page did you take the screenshot? Are you using a custom template?

I took the picture when trying to make a post on the forums tab. I am using a custom template, Cobalt.

**Comment by Derkades** [comment]
Could you double check that the default template has the same issue? If not, please report it to the cobalt developer

**Comment by DevLeven** [comment]
> Could you double check that the default template has the same issue? If not, please report it to the cobalt developer
No it does seem to be a problem only with the template im using, ill message the developer right away. Sorry for the false alarm.
