### ISSUE TITLE
Database Problem / No tables are created

### ISSUE THREAD

**Issue by Lewcon17** [NamelessMC/Nameless#2893]
### Describe the issue

Hello, I have a problem with the databases. I installed Namelessmc version 2 / pre release 13 and wanted to set it up. Even if I then have to provide my database details and click next, it tells me it was configured successfully, although no tables were created. Then when I want to go one step further, it tells me that table X doesn't exist. What can that be? I configured everything correctly. I use MySQL and phpmyadmin for administration. Can someone help me?

### NamelessMC Version

2.0.0-pr13

**Comment by PadowYT2** [comment]
See #2822

**Comment by Lewcon17** [comment]
@PadowYT2 
Hey, so I'm not getting smart with this post. I'm not doing an upgrade, I'm doing a fresh install. When entering the database data, he tells me that he has successfully configured it and I press continue. Then I am asked to enter the website name and e-mail address. If I want to go to the next step, it tells me the following:
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nameless.nl2_settings' doesn't exist"

Or did I miss something in the post? I have stated everything correctly. Please help!

**Comment by PadowYT2** [comment]
![https://cdn.padow.ru/bNDQ](https://cdn.padow.ru/bNDQ) on #2822 (click on the numbers)
