### ISSUE TITLE
Debug modal shows on exception page if no permission

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2895]
![image](https://user-images.githubusercontent.com/26070412/175854110-c43ac5b7-41ae-4d09-a5fa-b62defeae5ad.png)

**Comment by samerton** [comment]
Does clicking the button actually work, or error due to the lack of permission?

**Comment by Aberdeener** [comment]
It didn't work since the JS is only included if they have permission, the modal did not have a permission check so it showed up still - fixed now tho :D

**Comment by samerton** [comment]
> It didn't work since the JS is only included if they have permission, the modal did not have a permission check so it showed up still - fixed now tho :D

Basically what I was getting to was, is there a sufficient PHP check in the backend preventing people without permission from generating a link 😄

**Comment by Aberdeener** [comment]
Ah my bad, yeah:
https://github.com/NamelessMC/Nameless/blob/642a03f8b234dda04683e118aeadcbc20ae744a1/modules/Core/queries/debug_link.php#L4-L6
