### ISSUE TITLE
Use strings for discord ids

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2896]
PHP integers can't store discord ids on 32 bit Linux or on 32/64 bit Windows. Since we don't perform any mathematical operations, the identifiers can simply be stored as strings internally. I can implement a backwards compatible check in the java API client to accept both strings and integers.

**Comment by Aberdeener** [comment]
This applies for any sort of discord ID?
- guild id
- user integration discord id
- user oauth discord id

Very good catch btw, this has probably caused us headaches before 😄

**Comment by Derkades** [comment]
Yes, it applies to all "Snowflake" ids

**Comment by Aberdeener** [comment]
I could not find any other places where we cast the snowflake ID to integers - could have missed something

**Comment by favorit5503** [comment]
> I could not find any other places where we cast the snowflake ID to integers - could have missed something

Yes indeed there is one miss. modules\Discord Integration\widgets\DiscordWidget.php row 17. There is also an int thats need to be changed to string after that it works as intended.
