### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Gamer101233** [NamelessMC/Nameless#2898]
### Describe the issue

Every time i go to install the new update for pre13 i get the error stating (core email writable /core/email.php) is not installing or does not have set permissions im not sure whats going on but, i need help on this.

### NamelessMC Version

2.0.0-pr13

### Expected Behaviour

I was expecting to have everything done by now but, this is getting me stuck.

### Screenshots

![bandicam 2022-06-28 13-41-30-895](https://user-images.githubusercontent.com/83934629/176248011-d105f653-d3ab-4ae6-b322-2c8671095a43.jpg)

**Comment by Derkades** [comment]
Are you trying to upgrade from pr12, or do a fresh pr13 install? This can show up if you're trying to perform a fresh install using the upgrade package, since the upgrade package does not contain /core/config.php

**Comment by Gamer101233** [comment]
im upgrading from pr12

**Comment by Derkades** [comment]
If you're upgrading, you should not run the installer. If you got redirected to the installer, it means you have accidentally deleted some of your previous files. Please restore from backup.

**Comment by Gamer101233** [comment]
ok thank you

**Comment by PadowYT2** [comment]
Close the issue
