### ISSUE TITLE
/install/ not found

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#29]
Hi,

I'm getting this error: http://prntscr.com/96xaw6
Anyone knows how to solve it?

Thanks!

**Comment by samerton** [comment]
You'll need to enable Apache's mod_rewrite. Unfortunately I'm not sure how to do this on CentOS, but [this guide](http://www.ewhathow.com/2013/09/how-to-enable-mod_rewrite-on-apache/) should help you out.

**Comment by HappyHarm** [comment]
Thought I already enabled that ;S. But will try it out, thanks!

**Comment by HappyHarm** [comment]
Checked it and mod_write is enabled but still not working.

**Comment by samerton** [comment]
The only other thing I can think of is .htaccess files not being enabled; did you try the last two steps in the guide above?
If that still doesn't work, unfortunately I'm out of ideas.

**Comment by HappyHarm** [comment]
http://prntscr.com/978496 I'm getting this, do I have to set more "None' to all?

**Comment by HappyHarm** [comment]
Btw I downloaded version 0.4. Didn't see there were too repos.

**Comment by samerton** [comment]
Yes, "None" will nee changing to "All" to allow the htaccess file to work.

**Comment by HappyHarm** [comment]
Woops. Thank you very much it works now :)
