### ISSUE TITLE
mass email

### ISSUE THREAD

**Issue by Infinity271** [NamelessMC/Nameless#2908]
### Describe the issue

When i send a mass email the content is code in pre12 you used be able to see the full email without code

### NamelessMC Version

2.0.0-pr13

### To Reproduce

staffcp
click configuration
click emails
email mass email
i did a test and i got this in the end (<p>HEllo Admin<br /><br /><br />HIII</p>)

### Expected Behaviour

Hi Admin,

HII

**Comment by Aberdeener** [comment]
Hi there 👋🏼 

This has been fixed for 2.0.0.
You can manually apply this fix by changing line 49 of `modules/Core/pages/panel/emails_mass_message.php` to
```php
Input::get('subject'),
```

See the full commit for details if you need: https://github.com/NamelessMC/Nameless/commit/142a3fb307404791e0935a955d74366e28cf0fcf#diff-662ce32a635ba7c32e774db91c7883f8b25191312975fe863d008a6dff6286c3
