### ISSUE TITLE
getting an error with namelessmc pr13, something to do with the database

### ISSUE THREAD

**Issue by kingmaj0r** [NamelessMC/Nameless#2909]
### Describe the issue

im having some trouble installing namelessmc pr13 its not creating the tables in the database, im not sure if its a but or im doing something wrong.

### NamelessMC Version

2.0.0-pr13

### Screenshots

![image](https://user-images.githubusercontent.com/49806509/177036955-b7528076-b1d5-46b8-a155-44a9253a87e2.png)

**Comment by PadowYT2** [comment]
See #2822
