### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#291]
Remove the Social Text and add into that section a login and Register button and right under that in the same box add a how many people are browsing in the website. add a server status under that, then the social stuff should be there. And this should be a option to do in the settings if u want to, doesnt matter to me.

**Comment by PugaBear** [comment]
I think this stuff is really up to personal preference and should be done by editing the source code to your liking. Sam supplies a 'skeleton' of sorts- a base layout, a starting point. It's your job to customize it to your liking. It's one of those 'Its impossible to please everyone' situations.

**Comment by samerton** [comment]
Version 2.0 (still in early development) will allow for this, as I'm hoping to add the ability to choose which modules you'd like to have on each page, although this would still require template changes from the user.

**Comment by IsS127** [comment]
I can do that but idk how to show how many people are browsing, guests + members

**Comment by samerton** [comment]
If you're familiar with PHP, you can query the `nl1_users` table to retrieve a list of users who have a `last_online` column of within the last 5 minutes, or however recent you want the list to be.
As for listing guests, there isn't a way of doing that at the moment unfortunately.

**Comment by samerton** [comment]
I'll mark this as closed, if you'd like more information on this feel free to re-open.
