### ISSUE TITLE
Support Bot (Discord) & Maintenance

### ISSUE THREAD

**Issue by majklfild** [NamelessMC/Nameless#2913]
### Describe the feature

Hello, I came up with an idea. I think it would be a good idea to add a connection type to the php mailer settings. It is basically tls and can only be switched in the config. Or at least add a new column like php-mailer-ssl to the bot or something similar that would guide the user to the config to switch to ssl. Also, I would like to suggest that it would be easier to change the main big first maintenance text in center as well as text under. Now I have to rewrite it in language. There could also be a box to quickly overwrite this text when the text under this heading is already editable.

**Comment by Derkades** [comment]
> I think it would be a good idea to add a connection type to the php mailer settings. It is basically tls and can only be switched in the config. 

This option already exists in the config, though you should always be using STARTTLS (which nameless calls "tls").
