### ISSUE TITLE
502 Bad Gateway appears when updating from v2-pre12 to v2-pre13

### ISSUE THREAD

**Issue by tesfduwen** [NamelessMC/Nameless#2918]
### Describe the issue

I downloaded the update file and overwritten the old one, then clicked the "Update"  on the update page. Then there is 502 Bad Gateway.
Using Nginx 1.22.0 and PHP-8.0.
I hope I can get a solution, my English is not good, so I used Google translation, there may be some incomprehensible places, please forgive me, thank you.

### NamelessMC Version

2.0.0-pr13

### Expected Behaviour

I don't think it's a problem with NamelessMC, but I've tried many times with the same result. I searched online for a long time and couldn't find a solution, so I came here for help, I hope someone can teach me how to solve it, thank you very much.

### Screenshots

![屏幕截图 2022-07-08 223948](https://user-images.githubusercontent.com/101510287/178014486-b432514c-3a5c-456b-ab0d-e9f952d143b8.png)

**Comment by Derkades** [comment]
It is very likely that either the php-fpm service is stopped or the php-fpm address (path to socket) in your nginx config is invalid. Did you perhaps shut down php-fpm before doing the upgrade?

**Comment by tesfduwen** [comment]
> This is not NamelessMC fault, are you on a webhost or vps?

on vps

**Comment by tesfduwen** [comment]
> It is very likely that either the php-fpm service is stopped or the php-fpm address (path to socket) in your nginx config is invalid. Did you perhaps shut down php-fpm before doing the upgrade?

The update was successful, thank you.
![屏幕截图 2022-07-09 230739](https://user-images.githubusercontent.com/101510287/178111589-ee9dce23-73bc-46d3-b1c8-6c66f14ec513.png)

Trouble you again: how to solve this problem after the update is completed, or is it necessary to solve this?

**Comment by Derkades** [comment]
I'm not sure why the version number has a `-log` suffix. In any case, please update to MySQL 5.7 or newer, or MariaDB 10.3 or newer. The easiest way to do this is to run the version provided by your distribution. If you are already doing that you might be on an older distro version, in which case you should follow your operating system's manual to upgrade to a newer version.

**Comment by tesfduwen** [comment]
> I'm not sure why the version number has a `-log` suffix. In any case, please update to MySQL 5.7 or newer, or MariaDB 10.3 or newer. The easiest way to do this is to run the version provided by your distribution. If you are already doing that you might be on an older distro version, in which case you should follow your operating system's manual to upgrade to a newer version.
I see,thank you very much
