### ISSUE TITLE
Alert bug

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#292]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.1.0
* How would you describe the issue? Its a alert bug for standard users, it alerts them when someone has sent in a apply
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
![test](https://cloud.githubusercontent.com/assets/8834158/16468376/e0e4f9b0-3e4b-11e6-88d5-c0b1d8024834.png)

* Do you have an idea how or where the issue occurs? nope the user is standard.

**Comment by samerton** [comment]
In the AdminCP -> Core -> Modules -> Staff Applications, does your standard group have the "View Applications?" permission?

If so, you'll need to uncheck it, as this is whether they can view submitted applications.

**Comment by IsS127** [comment]
ahh ye, for some reason it was set by default.
