### ISSUE TITLE
i got a abstract error

### ISSUE THREAD

**Issue by kingmaj0r** [NamelessMC/Nameless#2927]
### Describe the issue

im having issues updating to pr13

everytime i keep getting 
Class VerifyMinecraftEndpoint contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (EndpointBase::isAuthorised)

### NamelessMC Version

2.0.0-pr13

**Comment by PadowYT2** [comment]
Remove that file, also please stop reporting this as bugs, ask this in [nameless discord](https://discord.gg/nameless)

**Comment by kingmaj0r** [comment]
sorry

**Comment by kingmaj0r** [comment]
what file though
![image](https://user-images.githubusercontent.com/49806509/179183035-85ee9186-0b1c-418e-b6c2-4f7b3458b240.png)

**Comment by samerton** [comment]
The fix for anyone coming back to the issue is to delete any of the following files if they exist:

```
            'modules/Core/includes/endpoints/discord/SetDiscordRolesEndpoint.php',
            'modules/Core/includes/endpoints/discord/SubmitDiscordRoleListEndpoint.php',
            'modules/Core/includes/endpoints/discord/UpdateDiscordBotSettingsEndpoint.php',
            'modules/Core/includes/endpoints/discord/UpdateDiscordUsernames.php',
            'modules/Core/includes/endpoints/discord/VerifyDiscordEndpoint.php',
            'modules/Core/includes/endpoints/ListGroupsEndpoint.php',
            'modules/Core/includes/endpoints/VerifyMinecraftEndpoint.php',
```

**Comment by PadowYT2** [comment]
> > Remove that file, also please stop reporting this as bugs, ask this in [nameless discord](https://discord.gg/nameless)
> 
> > close
> 
> Is it really necessary to treat people like that? I remember that in the beginning when you appeared on the project you were worse, and no one treated you like that ;)

How am I treating like that,
1. This is just a heads up that it is not a bug
2. It was already solved
And I'm marking this as off-topic
