### ISSUE TITLE
database installer error

### ISSUE THREAD

**Issue by Gamer101233** [NamelessMC/Nameless#2932]
### Describe the issue

im not sure whats going on right now but, every installation i use i get the same issue over and over again.

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'testsite'@'localhost' (using password: NO) in I:\webserver\htdocs\pages\install.php:775 Stack trace: #0 I:\webserver\htdocs\pages\install.php(775): mysqli->__construct('localhost', 'testsite', '', 'testsite', '3306') #1 I:\webserver\htdocs\index.php(43): require('I:\\webserver\\ht...') #2 {main} thrown in I:\webserver\htdocs\pages\install.php on line 775

thats all i get after i enter my database info iv tried different ways and nothing worked please fix this.

### NamelessMC Version

1.0.21

### Expected Behaviour

I was expecting it work and not having any errors like this.

**Comment by supercrafter100** [comment]
This happens because the credentials entered during installation are not accepted by your database server. Please ensure that the user has actual permissions to the database

**Comment by supercrafter100** [comment]
I'd also recommend using our latest v2 pre release 13 and not v1. V1 is not really supported anymore by any module or template so I highly recommend you install pre release 13. You can find this [here](https://github.com/NamelessMC/Nameless/releases/tag/v2.0.0-pr13)

**Comment by Gamer101233** [comment]
the mysql is running off of localhost and im not trying to run it outside my connection

**Comment by Gamer101233** [comment]
also would port forwarding the database make any chnage?

**Comment by supercrafter100** [comment]
> Can you try installing v2pre13? Even though it says its not meant for production by our site it has a lot more features and is a lot more user friendly to use. This should also give a clearer error message normally

Gonna quote this one again since as I've mentioned previously, v1 isn't supported anymore and I didn't get a confirmation that you've tried on v2pre13. We don't really push updates for v1 anymore so I'd kindly ask to try on that version :D

**Comment by Gamer101233** [comment]
alright ill go head and give it a try

**Comment by supercrafter100** [comment]
And I'd also like to suggest to create an account **with** a password in your database. This isn't an issue on our end as its your database server rejecting the connection attempt.

**Comment by Gamer101233** [comment]
when i started the one you gave me i got this error.

Your installation is missing the 'vendor' or 'core/assets/vendor' directory. These directories are included in releases, but not in the git repository. For regular installations, please make sure to download a release from the GitHub releases page, not from the button on the home page to download the latest source code. If you do want to run the latest version from source control for development versions, please run 'composer install' and 'yarnpkg'/'yarn install'.

**Comment by supercrafter100** [comment]
Use the `nameless-deps-dist.zip` file. This one includes all the neccesary libraries

**Comment by Gamer101233** [comment]
still am getting this same error message 

Access denied for user 'hosting'@'localhost' (using password: NO)

**Comment by supercrafter100** [comment]
you still aren't using a password. Can you try creating an account with one?

**Comment by Gamer101233** [comment]
in my database i dont see anything to create a account

**Comment by Gamer101233** [comment]
wait nevermind i see it if im correct

**Comment by supercrafter100** [comment]
If you keep experiencing issues, could you join our discord by any chance and open a thread in there? Its a lot easier to help you via that platform than via github. We have all our devs in there as well that can help you out.

**Comment by Gamer101233** [comment]
fixed it the database was causing errors with the connection i had to reset my whole database to fix it
