### ISSUE TITLE
Quotes in email/db password break config file

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2933]
### Describe the issue

For example:
```php
'password' => ",9nav\G8j:@,Wf7CFQ7-?|vNIQ>_OHo$Y&b+~6rq[\."gvz'54M%Elh%'|I[*9]>",
```
The `"` before `gvz` makes PHP think the password ends there.
This can be solved by using `addslashes` and `stripslashes` when writing/reading their password from the config file.

### NamelessMC Version

2.0.0-pr13

**Comment by Derkades** [comment]
stripslashes shouldn't be necessary when reading
