### ISSUE TITLE
Wrong MariaDB version in newest dev version

### ISSUE THREAD

**Issue by DominikSLK** [NamelessMC/Nameless#2937]
### Describe the issue

In the newest dev version of namelessmc in StaffCP it is showing wrong version of MariaDB

### NamelessMC Version

Development version

### Screenshots

dev version:
![dev version](https://user-images.githubusercontent.com/74055080/180267630-1fd68d76-8407-45ad-a146-fd3823904699.png)
pr13:
![pr13](https://user-images.githubusercontent.com/74055080/180267734-5021e048-7420-4a71-b4e0-0288f23122ba.png)
terminal:
![terminal](https://user-images.githubusercontent.com/74055080/180267845-01cfc1a3-e6b8-4286-b599-d808262bde05.png)

**Comment by Aberdeener** [comment]
Hi there, can you apply the changes in this PR https://github.com/NamelessMC/Nameless/pull/2938 and let us know if that fixes it?

**Comment by DominikSLK** [comment]
> Hi there, can you apply the changes in this PR #2938 and let us know if that fixes it?

#2938 fixed it for me :D
