### ISSUE TITLE
Can i block pages from being cached!

### ISSUE THREAD

**Issue by melerpe** [NamelessMC/Nameless#294]
A simple question, can i block pages from being cached (My code doesnt like the caching part!

**Comment by samerton** [comment]
I presume you're referring to the template caching, in which case you'll need to add the following just below `$smarty 	= new Smarty();` within **core/init.php**:

`$smarty->setCaching(Smarty::CACHING_OFF);`

**Comment by samerton** [comment]
I'll mark this as resolved, if you're still having issues feel free to re-open.
