### ISSUE TITLE
Update to new Nameless-Link role sync endpoint

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2945]
Continuing the discussion in https://github.com/NamelessMC/Nameless/pull/2920

A new `applyRoleChanges` endpoint is available, replacing the previous `roleChange` endpoint. This new endpoint has better error reporting and lets the website know which roles were *actually* changed.

The old endpoint will remain available, allowing pr13 websites to continue to (not) work. It does also mean that the transition to this new endpoint can happen later in a point release, since it is not a breaking change.

Documentation is available here: https://github.com/NamelessMC/Nameless-Link/wiki/API

**Comment by Derkades** [comment]
Documentation for the endpoint is now finalized, and implemented in Nameless-Link. 

The old endpoint has already been disabled for the official bot because the load got too high. As a result, website-to-Discord group sync will not work until the new the new endpoint is used by NamelessMC.

**Comment by joshwenke** [comment]
Hello! Just curious how progress on this is coming along. Would love to have group sync from website->bot <3

**Comment by tadhgboyle** [comment]
> Hello! Just curious how progress on this is coming along. Would love to have group sync from website->bot <3

We have rewritten parts of the website and plugin to implement these changes.
The website PR will be merged soon, hopefully @ https://github.com/NamelessMC/Nameless/pull/3222

These changes will be released with 2.1.0, which is hopefully within the next month or so - we can never guarantee a timeline.
