### ISSUE TITLE
Config unavailable. Please refresh the page.

### ISSUE THREAD

**Issue by SoNotMC** [NamelessMC/Nameless#2948]
### Describe the issue

I am trying to install a new version of pre release 13 however after entering my database details once they worked and it went to the next step of Site configuration. However it gave me the error "Config unavailable. Please refresh the page.".
So I decided to start fresh and delete all nameless files and drop the database then recreate it. However now when I go to set it up it skips the database configuration and still give me the "Config unavailable. Please refresh the page." error.

Please help!

### NamelessMC Version

2.0.0-pr13

**Comment by SoNotMC** [comment]
I would also like to add my core/config.php is completely empty (0kb)

**Comment by PadowYT2** [comment]
This is not a bug, and get support on the [discord server](discord.gg/nameless), and you tried refreshing the page with the button reload?

**Comment by samerton** [comment]
Does the file core/config.php exist? Is there anything inside?

**Comment by SoNotMC** [comment]
Yes it exists however is empty

**Comment by samerton** [comment]
Can you clear your browser cookies (or try an incognito window) and and try the installer again?

**Comment by SoNotMC** [comment]
All fixed now. No worries, thanks for the help!

**Comment by samerton** [comment]
Glad to hear! If you have any more questions please feel free to ask

**Comment by Derkades** [comment]
this should no longer happen in the v2 release
