### ISSUE TITLE
Accept discord role ids up to 20 characters long

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2949]
A snowflake identifier is a 64 bit integer. When stored as base 10 text, it uses up to 20 characters. Currently NamelessMC accepts a maximum of 18, for example when it needs to be entered for group sync.

```py
>>> math.ceil(math.log(2**64, 10))
20
```

**Comment by samerton** [comment]
Also to consider:
- server ID
- user ID
