### ISSUE TITLE
[Question] Update Files via Web

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#295]
Hey,

Is there anyway to change the update file and make it update to the github files?

**Comment by samerton** [comment]
I'm not aware of a method of doing this, you'd be able to create a script which automatically downloads and extracts the files however I'd advise against this due to database changes which could break your site.

**Comment by IsS127** [comment]
well i was just to ''lazy'' to update the files thats updated in the github xD

**Comment by samerton** [comment]
Version 1.0.11 shouldn't be too far away, it's probably just worth waiting until that's released.

**Comment by IsS127** [comment]
ok.

**Comment by IsS127** [comment]
well i should work on the swedish language before the 1.0.11 is released
