### ISSUE TITLE
Config unavailable. Please refresh the page. 

### ISSUE THREAD

**Issue by luckyoi** [NamelessMC/Nameless#2952]
### Describe the issue

I get Config unavailable. Please refresh the page. message when submitting site name and email address

### NamelessMC Version

2.0.0-pr13

**Comment by samerton** [comment]
Does the file core/config.php exist? If so, is there anything inside?

**Comment by luckyoi** [comment]
yes it exists and it's empty.

**Comment by samerton** [comment]
Please delete the file, clear the database, clear your browser's cookies and start the installation process again

**Comment by PVPMaster0001** [comment]
Fixed

**Comment by samerton** [comment]
Improvements to config creation came in version 2.0.0 which was released last week.

I'll close this issue, if you are still experiencing the same problem please feel free to comment on #2996
