### ISSUE TITLE
Some errors have been detected on the server! Phpmyadmin

### ISSUE THREAD

**Issue by luckyoi** [NamelessMC/Nameless#2953]
### Describe the issue

I'm getting this message every time accessing some table and im getting this code shown up.
![image](https://user-images.githubusercontent.com/106918177/181926256-4c3f421e-b25f-4e85-91d6-b37a45870ac5.png)

![image](https://user-images.githubusercontent.com/106918177/181926325-f876d991-0275-41c8-9fa0-16c7c35badd1.png)

### NamelessMC Version

2.0.0-pr13

**Comment by luckyoi** [comment]
by the way, I tried to install Greedy even tho it's not supported for version im using (i think it's not? it said something about that.) and now im getting error

Uncaught TypeError
Argument 1 passed to AssetResolver::gatherAsset() must be of the type string, null given, called in /var/www/html/core/classes/Templates/AssetResolver.php on line 55
(File: /var/www/html/core/classes/Templates/AssetResolver.php)

when accessing panel. How can i revert these changes and go back at default template?

**Comment by supercrafter100** [comment]
Replace `core/classes/Core/Util.php` with this https://paste.rkslot.nl/raw/uqacohaqip

**Comment by samerton** [comment]
This is an issue with phpMyAdmin so I will mark this issue as closed.
