### ISSUE TITLE
2FA Issues on pr13

### ISSUE THREAD

**Issue by SoNotMC** [NamelessMC/Nameless#2955]
#1480

I am having the exact same issue from this post.

**Comment by samerton** [comment]
Hi, which template are you using?

**Comment by SoNotMC** [comment]
Also i have checked the clock is up to date and it is (https://www.tidalmc.net/time.php)

**Comment by SoNotMC** [comment]
I am using the Cobalt template

**Comment by samerton** [comment]
Do you have access to a tool such as phpMyAdmin? If so, please log into there, find the nl2_groups table and set `force_tfa` to 0 - this will disable the force two factor requirement.

Then can you switch to the DefaultRevamp template to see if the same issue occurs there?

**Comment by SoNotMC** [comment]
No i dont sadly. Is there a MySQL command I could run to remove that? Its the "Owner" group

**Comment by samerton** [comment]
If your Owner group is the default admin group, it will have ID 2 which means you can run the following command:
```mysql
UPDATE nl2_groups SET force_tfa = 0 WHERE id = 2;
```

You will need to select your database using `USE <name>;` first.

**Comment by SoNotMC** [comment]
Perfect, thank you very much.
