### ISSUE TITLE
Wrong password length

### ISSUE THREAD

**Issue by MinecollYT** [NamelessMC/Nameless#2956]
### Describe the issue

"Please ensure your username is a maximum of 20 characters, and your email address and password are a maximum of 64 characters."

core/installation/steps/admin_account_setup.php
```
        'password' => [
            Validate::REQUIRED => true,
            Validate::MIN => 6,
            Validate::MAX => 30,
        ],
```

`Validate::MAX => 30,` should be increased to `Validate::MAX => 64,`

### NamelessMC Version

2.0.0-pr13

### To Reproduce

1.  Run installer
2. Choose a password longer than 30 characters

### Expected Behaviour

Allow passwords up to 64 characters instead of 30

**Comment by Derkades** [comment]
Thank you for the report, we have fixed this for the next release some time ago
