### ISSUE TITLE
NamelessMC is not compatible with PHP versions older than 7.4

### ISSUE THREAD

**Issue by Krypto7494** [NamelessMC/Nameless#2957]
### Describe the issue

I have php 8.1.8 and when i go to the website it gives me this: NamelessMC is not compatible with PHP versions older than 7.4

**BUT I HAVE PHP 8.1.8**

### NamelessMC Version

2.0.0-pr13

### To Reproduce

Only open the website

### Expected Behaviour

Nothing

### Screenshots

![image](https://user-images.githubusercontent.com/101934462/182221624-80d3b23d-c44f-482b-a6f3-5ac4bec292cc.png)

**Comment by Krypto7494** [comment]
Pls help

**Comment by Krypto7494** [comment]
@partydragen i think you are the owner of namelessmc

**Comment by Krypto7494** [comment]
I fix all bye

**Comment by samerton** [comment]
In case anyone finds this issue in the future, this is not a Nameless issue as the web server will likely be using a different PHP version to the command line - there are guides available online to resolve this.
