### ISSUE TITLE
HCaptcha error

### ISSUE THREAD

**Issue by ElitePusher** [NamelessMC/Nameless#2959]
### Describe the issue

When I put the secret key and the site key to the StaffCP/Configuration/Registration it says that it's invalid when it's not.

### NamelessMC Version

2.0.0-pr13

### To Reproduce

Go to the official HCaptcha site https://dashboard.hcaptcha.com/settings
Copy the secret key and create a site key.
Go to the NamelessMC StaffCP/Configuration/Registration place there these details and it says you, that's invalid.

### Screenshots

![image](https://user-images.githubusercontent.com/80160541/182426631-ddd0fa2a-1fda-4ebf-8461-b466eb8b087d.png)

**Comment by PadowYT2** [comment]
Fixed in #2849

**Comment by ElitePusher** [comment]
> Fixed in #2849

Fixed, thank you very much!
