### ISSUE TITLE
nl2 installation error

### ISSUE THREAD

**Issue by PVPMaster0001** [NamelessMC/Nameless#2960]
In the end Step come this Message
``SQLSTATE[42S02]: Base table or view not found: 1146 Table 'namelessmc.nl2_settings' doesn't exist``

Please Help me.

**Comment by supercrafter100** [comment]
Please see https://github.com/NamelessMC/Nameless/issues/2822 and follow the steps mentioned in the `nl2_settings` not found during installation section

**Comment by PVPMaster0001** [comment]
> Please see #2822 and follow the steps mentioned in the `nl2_settings` not found during installation section

Okay, I testing this.

**Comment by PVPMaster0001** [comment]
No it's not working

**Comment by supercrafter100** [comment]
Well you've just leaked your database credentials so probably want to change those. If it's not working then you've likely done something wrong. If you are able to, could you join our Discord server so we can help you out easier? The url is https://discord.gg/nameless

**Comment by PVPMaster0001** [comment]
I can change it, I have Plesk as Webhosting Interface.

**Comment by PVPMaster0001** [comment]
Worked the bug is fixed
