### ISSUE TITLE
Template sending error

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#2962]
### Describe the issue

When we make a modification on a model and we come back to it, it does not update directly.

### NamelessMC Version

Development version

### To Reproduce

Go to models I use cobalt.
I go to settings.
Then general.
I change the color to red when it was blue and I send the modification.
I come back in general and I still have blue.
I have to leave the page every time I edit.

### Screenshots

![1](https://user-images.githubusercontent.com/12797827/182594527-388f1158-e71b-45be-9f7e-e59ef7cce792.PNG)
![2](https://user-images.githubusercontent.com/12797827/182594530-cf753e3d-78dc-47df-81c8-ecb0c3f8a709.PNG)
![3](https://user-images.githubusercontent.com/12797827/182594531-27fb1702-c540-484d-b32d-a3637d8dd39c.PNG)

**Comment by PadowYT2** [comment]
This is not related to NamelessMC, report at drew's server

**Comment by samerton** [comment]
Please contact the template author for support - this is not built-in Nameless functionality so unfortunately we cannot help as we do not know how it works.

I believe the template author has a Discord server for support, there should be a link in the template's readme file.

**Comment by PadowYT2** [comment]
https://discord.gg/rjkVHNEn

**Comment by CreaCloudz** [comment]
Ok thanks

**Comment by CreaCloudz** [comment]
Same error on the social media
