### ISSUE TITLE
Twitter widget

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#2963]
### Describe the issue

I no longer have the twitter widget in the widgets when I saw that there is still the file in nameless

### NamelessMC Version

Development version

### To Reproduce

Go to widgets

### Screenshots

![Capture](https://user-images.githubusercontent.com/12797827/182596393-8ff53fcd-ae42-4c14-9641-a7f5a3bdfb93.PNG)

**Comment by PadowYT2** [comment]
Because you set it in Social Media

**Comment by CreaCloudz** [comment]
![image](https://user-images.githubusercontent.com/12797827/182597479-ae71ea80-48c0-4cbc-a3e2-eb1df1300b37.png)

There are no widgets

**Comment by supercrafter100** [comment]
> Because you set it in StaffCP > Configuration > Social Media

That will add it in the footer. They are talking about the widget

**Comment by CreaCloudz** [comment]
> > Because you set it in StaffCP > Configuration > Social Media
> 
> That will add it in the footer. They are talking about the widget

Yes

**Comment by PadowYT2** [comment]
> > Because you set it in StaffCP > Configuration > Social Media
> 
> That will add it in the footer. They are talking about the widget

Oh, thought it was going to be the same as Facebook, you add there & widget is there

**Comment by samerton** [comment]
I believe the widget should show as an option if a Twitter URL is provided, at least that was the case in pre-12. We will have to investigate this one further.

**Comment by CreaCloudz** [comment]
> I believe the widget should show as an option if a Twitter URL is provided, at least that was the case in pre-12. We will have to investigate this one further.

I have a url but nothing about this product and each time I update an id with the url is added for twitter youtube etc I think there is a problem with social media

**Comment by partydragen** [comment]
@CreaCloudz It been fixed in https://github.com/NamelessMC/Nameless/commit/4e46290b5f7adf1c9e398debb3f9c2b228086f99 
Thanks for reporting the issue :)
