### ISSUE TITLE
All tables are changed from mediumtext to text

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#2965]
All tables are changed from mediumtext to text after switching to phinx

This need to be switched back to mediumtext and update all websites back to mediumtext

**Comment by Derkades** [comment]
What is the advantage of using mediumtext? Is there a difference?

**Comment by partydragen** [comment]
text 65,535 characters
mediumtext 16,777,215 characters
longtext 4,294,967,295 characters

AlOT of people have reached reached the limit of 50k, so people have always modified the code to allow alot more, you see the discussion in our discord channel
