### ISSUE TITLE
[Need Help]

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#298]
So.. i got a new hosting that runs with cpanel and i had plesk before, it worked nice and everything, ik how to move and get database working it got working but.. everytime i go to another page this comes up 
![image](https://cloud.githubusercontent.com/assets/8834158/16529940/c0149ddc-3fc5-11e6-90f8-9d371286ee89.png)
, and i have updated the htaccess and added the code lines in. Can u guys help me.. the database works but not this..

**Comment by partydragen** [comment]
Are you sure you transfered htaccess too? in root and pages folder? Because i think this is a htaccess problem :/ or have you uploaded it in a subfolder?

I know when we transfer files its can happen htaccess not being transfered but if you have updated or what you did :/

**Comment by IsS127** [comment]
yes ive done that.. ive transfered everything.

**Comment by IsS127** [comment]
nvm fixed problem ty anyways
