### ISSUE TITLE
No CSS support for custom pages?

### ISSUE THREAD

**Issue by luckyoi** [NamelessMC/Nameless#2982]
### Describe the issue

I've made a custom page (basic page) with CSS (I didn't even use external urls, i put the css inside <style> html code) and when I load the page, it doesn't load with css, then I go back to custom pages in staff panel to check the source and I see that CSS code isn't there. Same thing when adding `<link rel="stylesheet" href="css/stylesheet.css">` in my HTML code.
I'm using the latest version

### NamelessMC Version

2.0.0

**Comment by PadowYT2** [comment]
Enable Unsafe HTML

**Comment by luckyoi** [comment]
I already did

**Comment by PadowYT2** [comment]
And did you put the code in Source HTML?

**Comment by luckyoi** [comment]
yes of course, I tried putting css in <style>mycssCode0</style> and <link rel="stylesheet" href="css/stylesheet.css"> but after I confirm the update and go back to see the source, it is no longer there, neither <link> nor <style> part of code

**Comment by partydragen** [comment]
I have confirmed there is multiple problems with custom pages, looking into it

**Comment by luckyoi** [comment]
alright, let me know, thanks

**Comment by supercrafter100** [comment]
@partydragen have you figured out a solution to this problem yet?

**Comment by partydragen** [comment]
> @partydragen have you figured out a solution to this problem yet?

No, This being @Aberdeener task xD He broke it

**Comment by samerton** [comment]
Potentially fixed by https://github.com/NamelessMC/Nameless/commit/b6948b6181d54b492fe73fb42303822e74bebb26 - needs verifying
