### ISSUE TITLE
Better module and template version comparing

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2993]
We need to change how we determine if a module/template is compatible with their namelessmc install. 

With the new versioning system in place, we can change it to check if it’s on the same major version instead of comparing the strings. This way it won’t show a warning if the module/template is 2.0.1 and their site is 2.0.2

**Comment by Derkades** [comment]
The plugin checks first and second number (ignores the third), I think the website should do the same

**Comment by partydragen** [comment]
Also need to consider the version might contain pr{number} so replace it away or whatever as there will most likey be pre releases before major versions idk ¯\_(ツ)_/¯
