### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by Gamer101233** [NamelessMC/Nameless#2996]
### Describe the issue

Getting a error config file does not exist when installing and yes i did download the correct file for new installations

### NamelessMC Version

2.0.0

### Expected Behaviour

To get my site name and outgoing email setup 

### Screenshots

![bandicam 2022-08-07 02-11-18-141](https://user-images.githubusercontent.com/83934629/183277822-cdbfc4ea-7d52-4723-bbd8-0fdd3b5d39bc.jpg)

**Comment by samerton** [comment]
Are you using version 2.0.0, or 2.0.1 (from [here](https://github.com/NamelessMC/Nameless/releases/tag/v2.0.1))?

Does the file `core/config.php` exist?

Is the `core` directory writeable so PHP can create the `config.php` file?

**Comment by Gamer101233** [comment]
2.0.1 

config does exist ans yes the core directory is writable

**Comment by samerton** [comment]
Is there anything inside the file `core/config.php`?

**Comment by Derkades** [comment]
Previously this error has been reported when the installer skips a step (when reinstalling without clearing cookies). Please try the install in a private/incognito browser window if this is the case

**Comment by Gamer101233** [comment]
there is nothing in the config.php file and i did try clearning the cookies nothing worked for me and my friend is also having the same issue as me.

**Comment by samerton** [comment]
Unfortunately I have not been able to reproduce this so I do not understand what the cause of the issue is here.

Maybe the permissions of the folder `core` or the file `core/config.php` are not correct, ie the installer is unable to insert the database details into the file?

**Comment by supercrafter100** [comment]
Delete the core/config.php file, clear your database, clear your browser cookies and start the installation again from step 1.
