### ISSUE TITLE
Default labels go away on edit if user doesnt have access to change labels.

### ISSUE THREAD

**Issue by DrakePork** [NamelessMC/Nameless#2999]
### Describe the issue

If you've put a default label on a forum and a user makes a topic in that forum, the label will be applied to the post. However if that user then edits their own post the label will go away as the user doesnt have access to change labels.

### NamelessMC Version

2.0.0

### To Reproduce

1. Set default label on a forum
2. Have user without permission to change labels create a topic
3. Have that user then edit the topic afterwards, doesnt even need to change anything just click "edit" and "submit".
4. Label goes away

### Expected Behaviour

For the label to not go away.

### Screenshots

Created new post with default label:
![image](https://user-images.githubusercontent.com/29175884/183290804-fa54e5e8-50bf-444c-b317-b94df0246a81.png)

Editing the post:
![image](https://user-images.githubusercontent.com/29175884/183290818-ee677edb-7ee2-43c5-89ad-f8699eb7039b.png)

Label gone:
![image](https://user-images.githubusercontent.com/29175884/183290824-dd66a6d8-ec45-480a-b68d-5ab3e443054c.png)

**Comment by intersecato** [comment]
I confirm this bug.
