### ISSUE TITLE
[Request] Moderator Log? More Customizable Permissions?

### ISSUE THREAD

**Issue by CzEMC** [NamelessMC/Nameless#3]
I suggest adding a Moderator Log that includes Edit history & Banning/Warning logs. Moderator Logs are not deletable by the interface and can only be removed if deleted from the MySQL Database.

I also suggest adding a Better Permissions System for Admins. Add a option to View Threads (If View & post is selected, Users in group can post but not view others posts.)

**Comment by samerton** [comment]
Thanks for the suggestions, I'll work on them for a future release, most likely 1.1 as opposed to 1.0.

**Comment by ThemInspectors** [comment]
what about permissions for topic labels?

**Comment by samerton** [comment]
Permissions planned for 1.1:

- View other users' threads (eg, prevent users viewing other users' threads in a support forum)
- Topic labels
- Moderation permissions, eg locking and moving threads
