### ISSUE TITLE
Signin bug

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#300]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? When I click on signin it redirects me correctly to the signin page, but when on the "Sign In" button it just say that the page is not working (It redirects me to a white page)
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?  No
* Do you have an idea how or where the issue occurs? No

**Comment by samerton** [comment]
Can you enable error reporting (if you have access to the AdminCP, it's in the "Misc" tab, otherwise you'll need to edit the "`error_reporting`" entry in the "nl1_settings" table so that `value` = 1 using something like phpMyAdmin), and try signing in again? An error should display on the page.

**Comment by Ariuw** [comment]
I don't have any acces to the AdminCP, so what I can do?

**Comment by samerton** [comment]
You'll have to follow the other option (editing the database) outlined in my last reply :)

**Comment by Ariuw** [comment]
Can you show me a screenshot? please

**Comment by samerton** [comment]
Do you have phpMyAdmin?

**Comment by Ariuw** [comment]
Yeah I use phpmyadmin

**Comment by Ariuw** [comment]
What I've do was just change the error_reporting from 0 to 1 and when I use signin page it says:

"Parse error: syntax error, unexpected ')' in /var/www/html/core/email.php on line 10"

**Comment by samerton** [comment]
Sounds like a problem with your email config, can you change the line containing `'smtp_auth' =>` so that it reads `'smtp_auth' => true`

**Comment by Ariuw** [comment]
I have the config like this:

<?php
$GLOBALS['email'] = array(
    'username' => '****',
    'password' => '****',
    'name' => '****',
    'host' => 'smtp.gmail.com',
    'port' => 587,
    'secure' => 'tls',
    'smtp_auth' => true
);

**Comment by samerton** [comment]
Sounds like [this issue](https://namelessmc.com/forum/view_topic/?tid=90), do you have an inverted comma ' in either your username, password or name fields?

**Comment by Ariuw** [comment]
Yeah I have an inverted comma in username, password and things like that

**Comment by Ariuw** [comment]
I've copied and paste what you tell me to do and now when I use the Sig In button it redirects me to and say this:

Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by samerton** [comment]
That sounds like a problem connecting to Gmail, I think they've changed their security settings recently so I can only recommend you try the following:

- Open https://accounts.google.com/DisplayUnlockCaptcha and click "Continue"
- Open https://myaccount.google.com/security#connectedapps and enable "Allow less secure apps" near the bottom of the page

Then, try again.

**Comment by Ariuw** [comment]
It just don't work but there's something I've used "http://phpcodechecker.com" and it says that there's a problem in line 10 "http://prntscr.com/bopkq9" <

**Comment by Ariuw** [comment]
I got it working! but I don't know what this means:

http://prntscr.com/bopmov

**Comment by Ariuw** [comment]
This has been fixed. Thanks for the help!!!!
