### ISSUE TITLE
Avatar image upload not  working

### ISSUE THREAD

**Issue by ZeusSeinGrossopa** [NamelessMC/Nameless#3002]
### Describe the issue

An error occurs when I want to set an avatar in the account settings

### NamelessMC Version

2.0.0

### To Reproduce

1. Go on your account settings 
2. Scroll down to "upload a new avatar"
3. Go on browse and choose your avatar picture file 
4. Press the button "submit"

### Expected Behaviour

That the avatar picture gets uploaded and set in the account 

### Screenshots

![image](https://user-images.githubusercontent.com/80217114/183368084-c4502ff1-3ce9-46ad-9c24-38b0bf506aa6.png)
![image](https://user-images.githubusercontent.com/80217114/183368170-5a71d4b6-8f93-41a2-9073-5749e260f4c0.png)

**Comment by samerton** [comment]
Hi,

This will be fixed in the upcoming 2.0.2 update (#2984), thanks for the report!
