### ISSUE TITLE
Error message not showing up in the banner uploading

### ISSUE THREAD

**Issue by ZeusSeinGrossopa** [NamelessMC/Nameless#3003]
### Describe the issue

If the banner you can set in the user profile does not have the correct image size, this error message will not be displayed. So you do not know what is wrong with the image. 

### NamelessMC Version

2.0.0

### To Reproduce

1. Go on your account and under profile 
2. Click on the right picture at the banner 
3. Browse your banner and press upload 

### Expected Behaviour

That the profileBanner gets uploaded correctly

**Comment by partydragen** [comment]
I have confirmed the bug and is not releated to file size, as file size is working for me

I keep investigate it

**Comment by partydragen** [comment]
Fixed https://github.com/NamelessMC/Nameless/pull/3006
