### ISSUE TITLE
SMTP doesnt work

### ISSUE THREAD

**Issue by ElusiveXGames** [NamelessMC/Nameless#3007]
### Describe the issue

SMTP errors for some reason when trying to send test emails. 

No error is created. It just times out. I am using all the information provided by my cpanel. 

### NamelessMC Version

2.0.0

### To Reproduce

panel/core/emails/mass_message/

Send email. Timeout's

### Expected Behaviour

It to send an email

### Screenshots

https://ss.elusivedev.com/YoCU6/QATOsuDe90.png

**Comment by supercrafter100** [comment]
Try using port 587

**Comment by supercrafter100** [comment]
You are mostlikely using 465. The timeout is occurring because nameless cannot connect to your smtp provider. Because nameless used StartTls (I believe?) port 587 should work
