### ISSUE TITLE
[Question] How do i use Querries

### ISSUE THREAD

**Issue by melerpe** [NamelessMC/Nameless#301]
Beforehand:
I'm changing many things, and introducing a sort of server->website communication using skript ).(Mostly because our server uses the free service of hostinger.nl)
So i have added something to the users table, saldo (Your money). I got part 1 working, getting the data from the mysql database.

```
$saldo = $queries->getWhere("users", array("mcname", "=", $user)); // Is it their username?
  	if(!count($saldo)){
      echo 'Notfound';
    }else{
        echo $saldo[0]->saldo;



    } 
```
And now i want to set it (other file)
This is what i got: (The important parts)
```
   $saldo = $queries->getWhere("users", array("mcname", "=", $user)); // Is it their username?
  	if(!count($saldo)){
      echo 'Notfound';
    }else{


      echo 'LOL';

      try {
        $queries->update('users', $_GET["user"], array(
          'saldo' => htmlspecialchars($_GET["saldo"])
        ));
        echo 'Happy!';
      } catch(Exception $e) {
        die($e->getMessage());
      }
```
It only displays LOL and then a error, whats wrong with my code!

- Melerpe

**Comment by samerton** [comment]
Everything looks to be in order, what's the error message you get?

**Comment by melerpe** [comment]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Viskroket' in 'where clause'

**Comment by samerton** [comment]
What is the value of `$_GET["user"]`?

**Comment by melerpe** [comment]
Viskroket (The user/mcname (It should not matter which one i use, because both are the mc names!))
And saldo is the new money value of the user!

**Comment by melerpe** [comment]
http://funtasiapark.nl/api/setSaldo/?user=Viskroket&saldo=1000
(Please remove this when viewed, so no spam (API key system is not written yet!))

**Comment by samerton** [comment]
The $_GET['user'] variable should refer to the user's ID, so try replacing it within the update query to `$saldo[0]->id`

**Comment by melerpe** [comment]
I'll try when I come home

**Comment by samerton** [comment]
Were you able to resolve the issue?

**Comment by melerpe** [comment]
Yes it works! I have it in near synchronized. It still needs some tinkering on the MC side
Op 8 jul. 2016 1:15 a.m. schreef Sam <notifications@github.com>:Were you able to resolve the issue?

**Comment by samerton** [comment]
Glad to hear the issue is resolved :)
