### ISSUE TITLE
Nameless oAuth Provider

### ISSUE THREAD

**Issue by AshlynDev** [NamelessMC/Nameless#3013]
### Describe the feature

I've spoken to @Aberdeener in Discord about using Nameless as a oAuth Provider, they stated that it might be something that could be done in the long term. Main reason for me having this is so that users don't have to make separate accounts for everything and rather have everything in one place. Seeing how nameless is progressing with oAuth I think this would be great feature!

**Comment by partydragen** [comment]
Im already working on a OAuth2 module with allows Nameless to be a OAuth provider

You can watch this progress at https://github.com/partydragen/Nameless-OAuth2
