### ISSUE TITLE
forum does not work

### ISSUE THREAD

**Issue by aycgit** [NamelessMC/Nameless#302]
**Bug
**nameless version: 1.0.10.  
**The topics on the forum dont show
**I dont know how it occoured, its really strange and i dont know why it happens

![image](https://cloud.githubusercontent.com/assets/13834197/16559882/34c5b982-41f0-11e6-8965-d1ec892ec49c.png)

at the left u see the empty forum and at the right my settings

do u know what makes this problem? i would really want my players to be able to use the forum

**Comment by IsS127** [comment]
This is not a bug, In the forums you will see at you're right it says ''latest discussion'' go into ur settings > forums > scroll down and you will see forum layout ''latest discussion view'' change it to Table View. That should fix you're problem :)

**Comment by aycgit** [comment]
thanks

**Comment by IsS127** [comment]
np
