### ISSUE TITLE
critical 202 update left this

### ISSUE THREAD

**Issue by festation2003** [NamelessMC/Nameless#3024]
### Describe the issue

There are 2 migrations files which have not been executed:
- 20220807142446_AddUserSessionActivityColumns
- 20220807153708_DeleteAdminSessionTable

### NamelessMC Version

2.0.0

### Additional Information

I did the usual update download -> extract -> push update but have been left with this and unable to access anything, any ideas on how i can fix or rollback?

**Comment by partydragen** [comment]
@festation2003 Did you run the upgrader after uploading the files, if not go to /panel/upgrade

**Comment by festation2003** [comment]
yes i hit the update button after extracting, but after there was no page that would let me load the site to access anything,  /panel/upgrade actually worked when  /panel/update wouldn't, thankyou very much :)
