### ISSUE TITLE
play page does not show port

### ISSUE THREAD

**Issue by aycgit** [NamelessMC/Nameless#303]
this is a bug
what the title says, i have set a port in my admin cp but on the play page it doesnt show, it only shows the ip without the port
photo:
https://i.snag.gy/RCtAfX.jpg

**Comment by IsS127** [comment]
Is the port 25565?

**Comment by aycgit** [comment]
@IsS127 no to port is 25737 and thats also what i set the settings to

**Comment by IsS127** [comment]
hmm im gonna see if i have this bug.
