### ISSUE TITLE
Punishment Issue

### ISSUE THREAD

**Issue by intersecato** [NamelessMC/Nameless#3039]
### Describe the issue

After banning or warning a user, if you refresh the page it will send another ban/warn punishment.

### NamelessMC Version

2.0.0

### To Reproduce

1. Ban/warn a user
2. Refresh the page

### Expected Behaviour

See only one punishment and not a spam of that.

**Comment by BaxAndrei** [comment]
Is there anything that pop-up when you refresh the page? Something like re-submiting the form?

**Comment by intersecato** [comment]
Nothing, just another punishment which is added to the list, and obv also to the db, so is not a visual bug.

**Comment by Derkades** [comment]
This is likely because the data returned is a result of a POST request. When refreshing the page, the browser will make an identical POST request. Your browser should prompt you with a warning when doing this.

Instead of immediately returning a page, we could return a redirect.
