### ISSUE TITLE
Custom group badages not showing up on profiles and forums

### ISSUE THREAD

**Issue by TiTo-418** [NamelessMC/Nameless#304]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 5dd40e01c70cc51552e4702900ea002d995bd269
* How would you describe the issue? Title
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 

![](http://image.prntscr.com/image/b493b0e015224e8f8e1dc38a7402aa3d.png)

![](http://image.prntscr.com/image/cd087ce121d34a5299fe069413529c34.png)

* Do you have an idea how or where the issue occurs? Forums and profile

**Comment by Ariuw** [comment]
Are you sure that the "Group HTML" and "Group HTML Large" is working?

"/admin/groups/"

**Comment by TiTo-418** [comment]
Oh, I thought it would be set automatically, sorry
