### ISSUE TITLE
Disable Minecraft username requirement without disabling Minecraft integration

### ISSUE THREAD

**Issue by DevLeven** [NamelessMC/Nameless#3043]
### Describe the feature

I don't know if this is already a feature or if there is another way to do it but when Minecraft Integration is enabled it makes the user sign up with a Minecraft Username. Though you can make it so it doesn't check the validity of the account, wouldn't it be better to have an option where they can create a regular account and link there Minecraft account to it? This way they have an option to link or not and it's easier to verify.

I have three ideas for this:
1. When they create an account, just like how they would link there Discord to the account maybe they can request a code from the website and use it to verify on the server. 

2. When they type /link on the server, a link would popup and when they click on said link it would redirect them to the website, where if they are signed in it would verify there account, or give them an option to sign in.

3. I dont know if this one is possible but maybe use the Microsoft account popup(The way people sign into there Minecraft accounts), and link/verify that way.

**Comment by Derkades** [comment]
I agree. The NamelessMC username being the same as the user's Minecraft username was a legacy thing before the integrations system. Now, there should probably be an option to disable it (maybe even by default).

Linking Minecraft accounts is already implemented like your "1." suggestion, in profile settings > connections with a verify command.

**Comment by DevLeven** [comment]
Yeah your right, must have over looked that. It would be good to have the Minecraft username separate from the NamelessMC username when verifying, since it asks for you to verify the NamelessMC username which might be different from your Minecraft username.

**Comment by intersecato** [comment]
I agree with you. A user maybe wants to sign up to the site / forum for the pleasure of actively participating in the community, maybe it is not premium or maybe it doesn't even have Minecraft.

**Comment by SenPr** [comment]
I don't know if this suggestion belong in this ticket, but it would also help people with Minecraft Integration to give a group after linking a Minecraft account.
Similar to email validation when it assign a player to a group after validating.

**Comment by Derkades** [comment]
> I don't know if this suggestion belong in this ticket, but it would also help people with Minecraft Integration to give a group after linking a Minecraft account. Similar to email validation when it assign a player to a group after validating.

I have opened a new issue for your suggestion: #3048
