### ISSUE TITLE
Sync frontend + StaffCP night mode toggle

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#3049]
### Describe the issue

Night mode not save in data user.

### NamelessMC Version

2.0.0

### To Reproduce

1. Go to the StaffCP
2. Activate the night mode staff panel
3. Check database user and night mode is not activate.

**Comment by PadowYT2** [comment]
It should not be stored in the database, but cookies

**Comment by samerton** [comment]
@PadowYT2 is correct - this is a separate system to the frontend dark mode setting - the frontend setting uses the database and the StaffCP uses cookies.

I have been thinking of changing this so they are both in sync - I will update this ticket and use it to track.
