### ISSUE TITLE
TinyMCE Spoiler

### ISSUE THREAD

**Issue by CreaCloudz** [NamelessMC/Nameless#3058]
### Describe the issue

I noticed that before we had the spoilers and they are still in the current code but no longer work.

### NamelessMC Version

2.0.0

### To Reproduce

1. Go to forum
2. Select a post or reply
3. check the write area and no spoilers are available.

### Screenshots

![image](https://user-images.githubusercontent.com/12797827/187066858-fc866478-8ab1-4a41-9600-367a3a0154b4.png)

**Comment by PadowYT2** [comment]
Seems #2944 broke it

**Comment by samerton** [comment]
Appears to be resolved in the latest dev code (which will be v2.0.3)
