### ISSUE TITLE
Twitter no longer using Widget ids

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#306]
Just so u remember it:
Twitter no longer using Widget ids you need to update to work with the new changes

**Comment by Root3287** [comment]
I think its already in there.... as the link [ https://twitter.com/intent/tweet?text=link to the post... ] should work.... last time I'd check... 
It doesn't look like it has any widget ids.

**Comment by PugaBear** [comment]
Its still possible to get a widget ID, I just had a hell of a time finding out how. [Got mine here.](https://twitter.com/settings/widgets/new)

**Comment by Root3287** [comment]
I was talking about the link I had.. The link didn't need a widget id because it's mostly handled by Twitter not by the api

**Comment by PugaBear** [comment]
I was responding to the original post. I didnt understand your comment :p

**Comment by samerton** [comment]
@Root3287 The issue here is referring to the latest Twitter post stream on the front page, as opposed to the Share link ;)

**Comment by Root3287** [comment]
Oh okay, my bad...

**Comment by Headhunterzpw** [comment]
I`m just editing the index.tpl in styles/templates/Default/index.tpl with the following code: https://gist.github.com/Headhunterzpw/c405762454760b3fe7d2d73918ce91e3

**Comment by samerton** [comment]
Fixed in 11a3be771d08663e86642aceed754adcfa4f5ddd (thanks to @godleydemon), the option to insert a widget ID was added in 810dc3ae341a65ccfc0e539763de1d9606196c14
