### ISSUE TITLE
Bedrock skins

### ISSUE THREAD

**Issue by Creeperz653** [NamelessMC/Nameless#3064]
### Describe the feature

Alright so I have 2 ideas they go to their nameless  config  enable bedrock support and when a player registers they put their edition and it says if their bedrock or Java and when nameless gets the skin and it’s bedrock it requests to my api like https://api.creepernation.xyz/skin/(bedrock username)/bedrock. option two have nameless gets the uuid from the mc server using nameless plugin and send it to the api selected and if they have my api selected bedrock skins work api link: https://api.creepernation.xyz/skin/(uuid) if you need a size option I’ll show you how to do it if this isn’t accept I’ll work on a module soon

**Comment by Creeperz653** [comment]
Or I’ll code it in nameless my self and make a pull request

**Comment by supercrafter100** [comment]
May I ask how your api requests the skin? I feel like it makes more sense to implement that functionality instead of relying on an additional external service

**Comment by PadowYT2** [comment]
Also it is redirecting straight to https://mc-heads.net

**Comment by Creeperz653** [comment]
> Also it is redirecting straight to https://mc-heads.net

The api works as a bedrock support not a skin api as it’s own same with the other skin api the api uses mcheads to texture a texture Id into a skin soon I’ll remove mc heads as a dependent

**Comment by Creeperz653** [comment]
> May I ask how your api requests the skin? I feel like it makes more sense to implement that functionality instead of relying on an additional external service

Since mojang does not have a reliable bedrock skin database I have to use geysers api as I’ve said before I’m planning to go self reliant and open source soon

**Comment by Creeperz653** [comment]
> Also it is redirecting straight to https://mc-heads.net

Mc heads doesn’t support bedrock we just use it’s texture id feature soon I’ll make it run on its own only problem is I have to add Java support mainly why I’m taking a bit

**Comment by abyssxd** [comment]
Idk what this is about, skins or geysermc in general but you can't use usernames with default geysermc/floodgate prefix to register, the prefix is "." and obviously it detects it as an invalid username.

**Comment by supercrafter100** [comment]
I don't get what the point is of using your api right now. Wouldn't it make way more sense to use mc-heads their bedrock skin api then in the first place? Seeing as the only thing your api does is just show the image which is generated by them 🤔

**Comment by supercrafter100** [comment]
> Mc heads doesn’t support bedrock we just use it’s texture id feature soon I’ll make it run on its own

So you are implying that both mc-heads and your api are currently not working as intended? I'm really confused haha

EDIT: I see that both of the services do not return the correct skin. The only difference is that your api seems to currently just verify if the username is a valid bedrock username, but the skins are not correct?

**Comment by Creeperz653** [comment]
> > Mc heads doesn’t support bedrock we just use it’s texture id feature soon I’ll make it run on its own
> 
> 
> 
> So you are implying that both mc-heads and your api are currently not working as intended? I'm really confused haha
> 
> 
> 
> EDIT: I see that both of the services do not return the correct skin. The only difference is that your api seems to currently just verify if the username is a valid bedrock username, but the skins are not correct?

You didn't get it lol I meant I use mc heads texture id a texture id is like a mc skin but since mc heads can't get bedrock skins I send the info mc heads needs to generate bedrock skins can we move to discord to discuss it more

**Comment by Creeperz653** [comment]
> I don't get what the point is of using your api right now. Wouldn't it make way more sense to use mc-heads their bedrock skin api then in the first place? Seeing as the only thing your api does is just show the image which is generated by them 🤔

Mc heads can't get the bedrock skin by its self it needs my api to send the info of the bedrock user

**Comment by Creeperz653** [comment]
> Idk what this is about, skins or geysermc in general but you can't use usernames with default geysermc/floodgate prefix to register, the prefix is "." and obviously it detects it as an invalid username.

My api adds username support using /(username)/bedrock  also when your adding a username you need to ignore the prefix also I have a end point for ignoring the prefix

**Comment by Creeperz653** [comment]
I’m making a module
