### ISSUE TITLE
Forums bug when using mobile

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#307]
1. The Text box not loading correct it just a small text box and no editor
2. When editing a post its same problem and text not loading

**Comment by samerton** [comment]
I remember looking into this a while back, unfortunately this is out of my control until the developers of the editor support all mobile devices (currently it supports mobile versions of Safari and Chrome).

**Comment by samerton** [comment]
I'll add the wontfix label to this and mark it as closed, as this is something I won't be able to fix myself. As soon as the mobile-friendly version of the editor is released I'll update Nameless.
