### ISSUE TITLE
Debug link does not copy on MacOS Safari

### ISSUE THREAD

**Issue by Timtendo12** [NamelessMC/Nameless#3072]
### Describe the issue

When clicking the debug link button the StaffCP says it copied the debug link but it never does. I haven't tested it on another browser but on Safari it does not work.

Safari Version: **15.6.1 (17613.3.9.1.16)**
MacOS Version: **MacOs Monterey 12.5.1**

### NamelessMC Version

2.0.0

### To Reproduce

1. Click on "debug link" in Maintenance.
2. Click on the  "debug link" button in the modal.
3. press paste somewhere you can type and nothing appears/the last thing you copied appears.

### Expected Behaviour

I expect a debug link.

### Additional Information

Safari Version: **15.6.1 (17613.3.9.1.16)**
MacOS Version: **MacOs Monterey 12.5.1**

**Comment by PadowYT2** [comment]
Do you use HTTPS?

**Comment by Timtendo12** [comment]
Yes, With a "Lets Encrypt" SSL

**Comment by PadowYT2** [comment]
And it says Copied when it's not? Also anything in Browser Console?

**Comment by Timtendo12** [comment]
![ScreenShot](https://user-images.githubusercontent.com/41442518/189723808-647bf94f-f3e0-4487-8aa8-765e26eb60e5.png)

**Comment by Timtendo12** [comment]
Seems like a permission issue. Im logged into the website admin account.

**Comment by Derkades** [comment]
It's not a nameless permission issue but a browser permission issue, it looks to me like your browser is preventing NamelessMC from copying to the clipboard

**Comment by tadhgboyle** [comment]
We can add another check to make sure the navigator exists and can be used
👍

**Comment by Derkades** [comment]
Was this fixed by #3086?

**Comment by tadhgboyle** [comment]
> Was this fixed by #3086?

I believe so!
