### ISSUE TITLE
Discord Bot - Verify Command Issue

### ISSUE THREAD

**Issue by burg5204** [NamelessMC/Nameless#3074]
### Describe the issue

When linking discord account on NamelessMC 2.0.2 Profile Settings (Integrations) it prompts you to enter /verify ############, but discord bot requirement is /verify token ###############

### NamelessMC Version

Development version

**Comment by supercrafter100** [comment]
This is not a bug, token is just the name of the slash command field that needs to be inputted. Its not a separate argument. Technically you are writing `/verify token:#################` in discord but for clarity, its just `/verify ############` on the website, you just copy the code over and execute the slash command in discord.

**Comment by Derkades** [comment]
It should probably be `/verify token:#################` on the website as well because this is easy to copy paste (discord will automatically recognize `token` is a parameter)

**Comment by partydragen** [comment]
Or completly swap to OAuth for linking as Aber suggested ¯\_(ツ)_/¯
