### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by CutieAshlynn** [NamelessMC/Nameless#3082]
### Describe the issue

SMTP ERROR: Could not authenticate 

i keep getting this for some reason and i cant figure it out

### NamelessMC Version

2.0.0

### Expected Behaviour

To get a email from this website

### Screenshots

![bandicam 2022-09-22 23-08-43-343](https://user-images.githubusercontent.com/83934629/191885292-1218b955-9e5b-4741-8b1e-1414ffd75852.jpg)

**Comment by Derkades** [comment]
The password is invalid. Perhaps the email service you are using does not simply allow logging in using just a password. Please see our wiki for more information: https://docs.namelessmc.com/en/smtp
