### ISSUE TITLE
Mail server error

### ISSUE THREAD

**Issue by CutieAshlynn** [NamelessMC/Nameless#3083]
### Describe the issue

I got my mail server working but, now for some reason when i send a test email i get this error on my mail server console i have Temporary error 249 (temporary MX resolution error) resolving .gmail.com

im not sure whats going on

### NamelessMC Version

2.0.0

### Expected Behaviour

for the email to come in without any issues or errors

**Comment by supercrafter100** [comment]
Your question has been answered in #3082 already?

**Comment by CutieAshlynn** [comment]
i found the password but, now im getting a MX error

**Comment by supercrafter100** [comment]
This is not a bug or issue with NamelessMC or anything related to it. Please contact the support team of your mail server software as we cannot provide you with any help regarding that.
