### ISSUE TITLE
[Suggestion] Alert profile owner when user comments on their profile

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#309]
**What kind of issue is it (Question, Bug, etc.)?** Suggestion.  

Would be awesome if you could get an alert when someone comments on your profile.

**Comment by PugaBear** [comment]
I've gotten this working, but before I submit a pull request, do you think it should also alert all the users who have 'friended' or 'followed' the profile owner?

**Comment by BlackBeltPanda** [comment]
I don't think followers should get alerted in that case.
Maybe when you create a new forum post they should get alerts, though.

**Comment by PugaBear** [comment]
I think that sounds reasonable. @samerton thoughts? I'll get this done for you if you like it.

**Comment by samerton** [comment]
This has been planned for a while, unfortunately I've not had the chance to implement it as of yet. @PugaBear Thanks for the offer, I'd really appreciate it :)

**Comment by PugaBear** [comment]
@samerton While I'm at it, I should ask, should the friend system be one-way? As in, when you add a friend, it only shows up on your account, you are not automatically a friend of the other person. I think a friend system should require the other person to accept the friend request. Maybe this was also planned but not implemented yet.

**Comment by PugaBear** [comment]
@samerton ?

**Comment by aycgit** [comment]
@PugaBear i love that idea but i wasnt the friend system made into a follow system?

**Comment by PugaBear** [comment]
@aycgit Both work, you can switch which one you want to use in the Admin panel (core page)

**Comment by samerton** [comment]
@PugaBear 
The system was changed (per request) a while back to be one-way only. In the future friend requests are planned, although I'm not sure when exactly.

@aycgit 
As PugaBear mentions, there's an option to switch between followers and friends in the AdminCP, the idea is that if you use the follower system you'll receive alerts based on activity by the person you follow (not yet implemented) and the friends system is just something if you don't want the alerts.
