### ISSUE TITLE
Change the discord command text

### ISSUE THREAD

**Issue by Timtendo12** [NamelessMC/Nameless#3091]
### Describe the feature

Right now when people copy over the /verify {{token}} command over to discord it does not format the right way. To fix this simply change it to:

/verify token:{{token}}

Now it formats it the right way and people won't face an error in the discord client when copying over the command.

[Correct format when copying]
![image](https://user-images.githubusercontent.com/41442518/193325675-a86e2b20-13b7-41bd-97ae-2b8ceec17111.png)

[Current format when copying]
![image](https://user-images.githubusercontent.com/41442518/193325936-bb0ae8e5-dee4-4df9-886a-ea0d40e6bff3.png)

I know this is something small but I've had multiple users contact me because of this. See it as making it a little bit more user-friendly :)

**Comment by tadhgboyle** [comment]
PR already open for this https://github.com/NamelessMC/Nameless/pull/3087
