### ISSUE TITLE
Translation file not found

### ISSUE THREAD

**Issue by PankKRB** [NamelessMC/Nameless#3094]
### Describe the issue

![image](https://user-images.githubusercontent.com/87706843/193796102-300f8d29-360d-407a-9773-79fbdd3377ec.png)

### NamelessMC Version

2.0.2

**Comment by PadowYT2** [comment]
This is not a bug, you should've contacted on the Discord Server. Anyways the template you are trying to install is not up to date

**Comment by Derkades** [comment]
Padow is correct, please delete the files for the template or module you attempted to install and your website will become operational again.
