### ISSUE TITLE
Database Configuration Error

### ISSUE THREAD

**Issue by alazeprt** [NamelessMC/Nameless#3099]
### Describe the issue

An error occurred during the installation of the database configuration of NameLessMC, which prevents the installation from continuing

### NamelessMC Version

2.0.2

### To Reproduce

Phinx by CakePHP - https://phinx.org. using config file core/migrations/phinx.php using config parser php using migration paths - /www/wwwroot/beta.forum.xn1326.top/core/migrations warning no environment specified, defaulting to: nameless using adapter mysql using database nameless ordering by creation time == 20220519023748 CreateOauthTable: migrating PDOException: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. in /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:193 Stack trace: #0 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(193): PDO->exec() #1 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(350): Phinx\Db\Adapter\PdoAdapter->execute() #2 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable() #3 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable() #4 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->createTable() #5 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute() #6 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions() #7 /www/wwwroot/beta.forum.xn1326.top/core/migrations/20220519023748_create_oauth_table.php(18): Phinx\Db\Table->create() #8 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): CreateOauthTable->change() #9 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(385): Phinx\Migration\Manager\Environment->executeMigration() #10 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration() #11 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate() #12 /www/wwwroot/beta.forum.xn1326.top/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute() #13 /www/wwwroot/beta.forum.xn1326.top/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run() #14 /www/wwwroot/beta.forum.xn1326.top/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand() #15 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun() #16 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(240): Phinx\Console\PhinxApplication->doRun() #17 /www/wwwroot/beta.forum.xn1326.top/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(124): Phinx\Wrapper\TextWrapper->executeRun() #18 /www/wwwroot/beta.forum.xn1326.top/core/classes/Database/PhinxAdapter.php(68): Phinx\Wrapper\TextWrapper->getMigrate() #19 /www/wwwroot/beta.forum.xn1326.top/core/installation/steps/ajax_initialise.php(5): PhinxAdapter::migrate() #20 /www/wwwroot/beta.forum.xn1326.top/core/installation/installer.php(27): require('/www/wwwroot/be...') #21 /www/wwwroot/beta.forum.xn1326.top/install.php(65): require('/www/wwwroot/be...') #22 {main}

### Expected Behaviour

Successfully configured database

### Screenshots

![image](https://user-images.githubusercontent.com/92018941/194463390-268b55b6-1ffa-433f-a192-f500e894cf85.png)

### Additional Information

Use PHP - 7.4.30, MySQL 5.6.50

**Comment by PadowYT2** [comment]
This is not a bug, you should've contacted on the Discord Server. Anyways the problem is not solved yet, see https://discord.com/channels/246705793066467328/995515741505867806

**Comment by supercrafter100** [comment]
Please update to a more recent version of MariaDB (10.3+) or MySQL (5.7+) with support for longer indexes. If you use a webhost, please contact them or move to a different web hosting provider. If you configured a server yourself, make sure it is upgraded to the newest release of your Linux distribution. Most Linux distributions include a new enough MariaDB version, so you don't need to install it from third party sources.
