### ISSUE TITLE
Questions - forum text color change, populate forum text box

### ISSUE THREAD

**Issue by PugaBear** [NamelessMC/Nameless#310]
1) How would I change the default color of forum (and news) text?

2) Is there a way to pre-populate the forum post text box with text, and formatting?

Thank you!

**Comment by samerton** [comment]
Really sorry it's taken such a long time to reply.

To change the colour of text on the site, you can add the following CSS to your **styles/themes/Active Theme/css/custom.css** file:

`body {`
`  color: #000;`
`}`

replacing `#000` with the hex colour of your choice.

As for pre-populating the text box, this would only be possible (although it wouldn't be easy specifying the forums it applies to) by inserting the HTML into the editor, check out lines 242-244 of **pages/forum/create_post.php** for an example of this. The Javascript would need to go beneath the CKEditor script on the pages in question.

**Comment by samerton** [comment]
I'll mark this as closed :)
