### ISSUE TITLE
News char. limit.

### ISSUE THREAD

**Issue by majklfild** [NamelessMC/Nameless#3114]
### Describe the issue

Hi! 

I'm reporting an error where the length of the post on the main page cannot be adjusted in the Util.php file.

(/core/classes/Core/Util.php)
`public static function truncate(string $text, int $length = 750, array $options = []): string {.`

I have confirmation from several people that the problem is not on my site. 

Thanks for the feedback.

### NamelessMC Version

2.0.2

**Comment by partydragen** [comment]
You need to edit it in `/core/classes/Misc/Text.php` on line 34

**Comment by majklfild** [comment]
Thanks <3
