### ISSUE TITLE
Preventing too many messages being sent simultaneously by the same person.

### ISSUE THREAD

**Issue by frafol** [NamelessMC/Nameless#3116]
### Describe the issue

Somehow it is possible to make the forum slow down/crash due to too many messages being posted at once. Many people abuse this to make the forum go down. It would be better to add a cooldown or to stop the user after too many messages sent in a given time frame.

### NamelessMC Version

2.0.0

### Screenshots

https://i.imgur.com/iqTxi8y.png

All these messages were sent within seconds, I think with an external programme.

**Comment by supercrafter100** [comment]
Are these forum topic replies or from the messaging section on a user their profile?

**Comment by frafol** [comment]
Posts under a user's profile

**Comment by frafol** [comment]
In addition, having public API has meant that many people have made external programmes for e.g. dm spam or message board spam to stress the forum

**Comment by supercrafter100** [comment]
Well there isn't exactly a way to make it "private". Though I do agree that rate limits should be added in public places to prevent spam
