### ISSUE TITLE
Way to limit new user ability to wall post

### ISSUE THREAD

**Issue by AutismFather** [NamelessMC/Nameless#3121]
### Describe the feature

I approve people to play on my server and use my website, but the way that NameslessMC works right now, anyone can register and immediately post to their wall or private message anybody. I've seen a few trolls take advantage of this.

I propose 2 features to help with this:

1. An option to restrict access to wall posts and private messaging to new users until approved, or given a "group" which has access to those things.

2. Sections in the Staff Panel where selected staff can monitor the activity for any inappropriate, illegal, troll, etc. behaviour.

**Comment by samerton** [comment]
Sounds good, completely agree that further measures in this area are needed - I think permissions are probably the best approach here which can be granted to groups accordingly.

As for monitoring, perhaps private messages should only be viewed by staff if reported by a user? ie a "report" button added to a private message which sends the conversation over to staff for review

**Comment by AutismFather** [comment]
Yeah, a way to report private messages would be ideal. That ensures privacy but also gives users a way to quickly let us know when there's a troll in the system.

**Comment by samerton** [comment]
Splitting this up into smaller tickets

Reporting private messages: https://github.com/NamelessMC/Nameless/issues/3528
Reporting profile wall posts: https://github.com/NamelessMC/Nameless/issues/2593

I will repurpose this ticket into adding a permission to be able to post on user profile walls
