### ISSUE TITLE
Invalid command 'php_value'

### ISSUE THREAD

**Issue by Esterze** [NamelessMC/Nameless#3126]
### Describe the issue

I'm trying to get the friendly URLs to work,
but this error always comes out as a result of adding `nameless.conf` to the enabled sites.

`Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration`

### NamelessMC Version

2.0.2

### To Reproduce

1. Follow [this](https://docs.namelessmc.com/en/webserver) guide
2. Use the commands from the **Enabling Configuration**
3. See the error

### Additional Information

I'm on Ubuntu 20.04.5
[This](https://pastebin.com/wz8zkG6f) is what popped up when visiting the website after removing the `php_value` command

```
root@v67467:~# apt install php-fpm
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-fpm is already the newest version (2:7.4+75).
```

**Comment by Esterze** [comment]
I tried to make it work multiple times, while making sure I did everything from the guide.

**Comment by Esterze** [comment]
Okay, so the issue is that the commands in the guide are either outdated,
or I messed up something on my server. I can't tell what it is since Linux OS isn't my main OS,
but following [this](https://www.digitalocean.com/community/tutorials/how-to-install-php-7-4-and-set-up-a-local-development-environment-on-ubuntu-20-04) guide helped me fix my issue and now even friendly urls are working.

**Comment by tadhgboyle** [comment]
Looks like PHP was not yet installed when you did this.
When PHP code displays in the browser but does not execute this is how we know it is the problem!
Glad it is all solved now.

**Comment by Derkades** [comment]
You were using php-fpm, but used the configuration example for apache with mod-php (that's the only config to use php_value). I suspect you installed mod-php now, which made it work?

**Comment by Esterze** [comment]
I had PHP installed. Yet apache2 wasn't feeling it. 😁 I don't really know what went wrong.
It was 5AM when I got it to work, so I remember just parts of the process.

**Comment by Esterze** [comment]
This happens again after following the guide, different machine, same OS.

**Comment by Esterze** [comment]
Seems like the guide really needs to be updated.

**Comment by Esterze** [comment]
The guide should explain the different between mod_php and php-fpm,
especially since the third command (mod_php) does not come with installing apache.

**Comment by Derkades** [comment]
"mod_php" is not a command. Neither mod_php nor php-fpm "come with" apache. Mod-php is installed using the `php` package on debian, php-fpm is installed using the `php-fpm` package.
