### ISSUE TITLE
Convert Screen Doesn't Appear At All - Reloads the Admin Create An Account Panel

### ISSUE THREAD

**Issue by Gonfonix** [NamelessMC/Nameless#313]
#### Issue:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  

**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.10  

**How would you describe the issue?** When installing Nameless, everything goes fine until I setup the admin account and click continue, it takes me back to the same page. When I type in "http://www.gonfonix.com/install/?step=convert" in my browser, it takes me back to the "create an admin account" screen? Since of this, I went to "www.gonfonix.com/install/?step=finish" and I finished the install.  When I clicked to finish the install, it didn't load to screen where it would ask you to travel to the Admin panel. Instead, it gave me a 404 error code. So, I went to my website to sign in and tried logging in that way, but when I try logging into the Admin account, it saids "Invalid token, please try again.". I then tried even making an account as a test, but still get the same error message.

**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** No, unfornately. I can reinstall the whole service again if you would like me to regenerate the error. However, it did not give me any error or anything. It just won't load the page.

**Do you have an idea how or where the issue occurs?** Not very sure, maybe the "install.php" file? Not to sure.

**Comment by samerton** [comment]
Unfortunately it looks as though your web hosting is not compatible with Nameless, may I ask how your website is hosted?

**Comment by EuroTheDev** [comment]
I host a VPS from Creeperhost.net. On the VPS, I am running an NGINIX server with NamelessMC installed.

**Comment by samerton** [comment]
It should work fine on a VPS, unfortunately I've not used nginx before so I'm not sure exactly how the configuration would be, but can you check the process running PHP has permission to write session variables (you can find the directory PHP writes them to in your php.ini file).

**Comment by EuroTheDev** [comment]
Ok, I will take a look at that. Thanks for the response.

**Comment by Gonfonix** [comment]
BTW, I figured if anyone else is having this error, then this is how you fix it. Go to your server console or terminal (the VPS console), and type this is in: "chown -R nobody:nogroup /var/lib/php/session". That should fix it. If that doesn't work, then also try doing "sudo chmod -R ug+rw /var/lib/php/sessions". Hope this helps :D

**Comment by samerton** [comment]
@Gonfonix Glad your issue is resolved! I'll mark this issue as closed, if you have any other questions feel free to reopen :)

As for the MySQL message during the installer, sounds like something to do with sockets although I'm not sure why that would happen exactly.
