### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by ThomasIO** [NamelessMC/Nameless#315]
Expand NamelessMC to work with other things other than just minecraft.

**Comment by ThomasIO** [comment]
Like, Garry's Mod for example.

**Comment by samerton** [comment]
Thanks for the suggestion, but unfortunately Nameless is likely to remain Minecraft related. version 2.0 will allow for addons to be created for theoretically any game, but the core Nameless system will require Minecraft integration.
