### ISSUE TITLE
Discord panel page no longer displays invite link

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#3152]
Didn't this page use to show an invite link and short instructions?
 
![image](https://user-images.githubusercontent.com/15892014/210274076-5c039856-0c30-47f1-a2da-20a92c63bfc6.png)

The `INVITE_LINK` smarty placeholder seems to be unused:

https://github.com/NamelessMC/Nameless/blob/5f71f1c1e8efba9bb5c401b1664964d3a9a58ce7/modules/Discord%20Integration/pages/panel/discord.php#L119-L125

**Comment by partydragen** [comment]
Your friend @PadowYT2 removed it https://github.com/NamelessMC/Nameless/commit/4213920902169215da37dcb4a13f4c15bcbc0b0f#diff-d7018d14b00758dad408ecec6a84672303f89ae15af7eea244a108929484dfcdL45

**Comment by PadowYT2** [comment]
> Your friend @PadowYT2 removed it https://github.com/NamelessMC/Nameless/commit/4213920902169215da37dcb4a13f4c15bcbc0b0f#diff-d7018d14b00758dad408ecec6a84672303f89ae15af7eea244a108929484dfcdL45

I don't think so

**Comment by tadhgboyle** [comment]
> > Your friend @PadowYT2 removed it https://github.com/NamelessMC/Nameless/commit/4213920902169215da37dcb4a13f4c15bcbc0b0f#diff-d7018d14b00758dad408ecec6a84672303f89ae15af7eea244a108929484dfcdL45
> 
> I don't think so

Git diff doesn't lie :p 
The ${INVITE} variable is removed in that commit.

**Comment by PadowYT2** [comment]
> > > Your friend @PadowYT2 removed it [4213920#diff-d7018d14b00758dad408ecec6a84672303f89ae15af7eea244a108929484dfcdL45](https://github.com/NamelessMC/Nameless/commit/4213920902169215da37dcb4a13f4c15bcbc0b0f#diff-d7018d14b00758dad408ecec6a84672303f89ae15af7eea244a108929484dfcdL45)
> > 
> > 
> > I don't think so
> 
> Git diff doesn't lie :p The ${INVITE} variable is removed in that commit.

Means somehow conflict resolver did not keep it

**Comment by Derkades** [comment]
Fixed with #3195
