### ISSUE TITLE
Uncaught Error: Class 'KeyAuthEndpoint' not found

### ISSUE THREAD

**Issue by VictimOfPing** [NamelessMC/Nameless#3155]
### Describe the issue

Uncaught Error
Class 'KeyAuthEndpoint' not found
(File: /var/www/html/modules/Core/includes/endpoints/VerifyIntegrationEndpoint.php)
[http://www.puritycube.it/](https://www.puritycube.it/)

### NamelessMC Version

2.0.0

### To Reproduce

After the installation I got this error

### Expected Behaviour

That I would go into the forum control panel

### Screenshots

![image](https://user-images.githubusercontent.com/120317607/210632887-cc2b4819-bc63-4c5c-a7c4-55c98a2dde10.png)

**Comment by samerton** [comment]
Hi,

This suggests some files are missing from your web host.

Can you please ensure the file **core/classes/Endpoints/KeyAuthEndpoint.php** exists, and if not it'll need to be created and the following code needs adding inside: https://raw.githubusercontent.com/NamelessMC/Nameless/v2.0.2/core/classes/Endpoints/KeyAuthEndpoint.php (version 2.0.2)

This may mean other files are missing from your web host - it might be worth uploading all files again from the [latest release](https://github.com/NamelessMC/Nameless/releases/latest) - note you need the `nameless-deps-dist` file and not the source code.
