### ISSUE TITLE
" Integrity constraint violation: 1062 Duplicate entry 'Core' for key 'name' " during the installation

### ISSUE THREAD

**Issue by VictimOfPing** [NamelessMC/Nameless#3156]
### Describe the issue

during installation, at site configuration it gives me this error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Core' for key 'name'

### NamelessMC Version

2.0.2

### To Reproduce

While doing the installation of nameless

### Expected Behaviour

It should keep me going I don't understand the problem

### Screenshots

![image](https://user-images.githubusercontent.com/120317607/210784671-990d2e33-18f7-48d1-9516-2d9b99728e77.png)

**Comment by Derkades** [comment]
This happens when you attempt to install to a database that already contains tables from an existing Nameless installation. Please empty the database and try again (in a private/incognito browser window so the installation starts from step 1).

**Comment by VictimOfPing** [comment]
> This happens when you attempt to install to a database that already contains tables from an existing Nameless installation. Please empty the database and try again (in a private/incognito browser window so the installation starts from step 1).

How do I empty the database?

**Comment by supercrafter100** [comment]
Easiest way is to just drop it and recreate the database. A bit of googling on your end can't hurt

**Comment by VictimOfPing** [comment]
Now it tells me this: Base table or view not found: 1146 Table 'nameless.nl2_groups' doesn't exist
