### ISSUE TITLE
Central Password Handling

### ISSUE THREAD

**Issue by Ste3et** [NamelessMC/Nameless#3158]
### Describe the feature

I want to enhanced my handwritten Homepage via NamelessMC.
My hompage already contains ~200 Users with several informations, i use an own way to hash the User passwords.
Can be the php#password_hash and php#password_verify moved to a central location inside the "Core"?
That should be very usefull for me because if i change that for my self and NamelessMC get an upgrade i need to migrate that again.

Greatings
Ste3et_C0st

**Comment by supercrafter100** [comment]
Won’t you always have to change it after an update? No matter where it’s moved to?

**Comment by Ste3et** [comment]
The [Core/User.php](https://github.com/NamelessMC/Nameless/blob/1c4cfaf8152b53dfa79696bd8e2b6c23d7c70d84/core/classes/Core/User.php#L364) includes an checkCredentials there already an central place for password_verify but for password_hash you need to change several files like this [one](https://github.com/NamelessMC/Nameless/blob/develop/core/installation/steps/admin_account_setup.php#L70 )
I know the NameLessMC Core Folder isn't updatet as mutch bin if i update the website in the futute i need to rework it again ^^

**Comment by Derkades** [comment]
Perhaps you are interested in making this change and opening a PR?

**Comment by Ste3et** [comment]
I can saure add an pr for this, but atm i work on the phillippines 11.000km away from home and i didnˋt have access to the Code Right Not for the next 2 weeks.

**Comment by Derkades** [comment]
Looks like Aberdeener has similar plans: #3210 

I'll close this issue as duplicate to avoid confusion

**Comment by tadhgboyle** [comment]
Ah sorry about that! Would still be totally open to you PRing your ideas on this though
