### ISSUE TITLE
NamelessMC Plugin [QUESTION]

### ISSUE THREAD

**Issue by Stijnz** [NamelessMC/Nameless#316]
- What kind of issue is it (Question, Bug, etc.)?
  Where can I download the NamelessMC.
- In which version of NamelessMC did it occur (1.x.x)?
  I got the newest.
- How would you describe the issue? 
  I can get my API key for the NamelessMC plugin, but not the plugin download.
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
  No, sorry.
- Do you have an idea how or where the issue occurs?
  Send me the plugin.

**Comment by samerton** [comment]
Hi,

The plugin isn't ready for release at the moment, unfortunately there's no estimated completion date yet.

**Comment by Stijnz** [comment]
Do you have an idea how long it takes for the release, just what you thinking.

**Comment by samerton** [comment]
I don't sorry, I'm not developing the plugin myself.

**Comment by xBreaksx** [comment]
To be honest I don't think your developer of the plugin is even developing it...

**Comment by Headhunterzpw** [comment]
@xBreaksx The developer @SystemUpdate is working on it but I think that he is busy with some other stuff?

**Comment by xBreaksx** [comment]
@Headhunterzpw You know this for sure or are you making guesses?

**Comment by samerton** [comment]
I'll mark this as closed, as we now have a repository for the plugin [here](https://github.com/NamelessMC/Nameless-Plugin) (which is still in development stages), where you can also find a link to development builds.
