### ISSUE TITLE
Can't clear the alerts

### ISSUE THREAD

**Issue by NorgePlayz** [NamelessMC/Nameless#3207]
### Describe the issue

I got alot of alerts on my account, but I can't click "Delete all" button. It won't delete it

### NamelessMC Version

2.0.2

### To Reproduce

1. Go to Account
2. Alert
3. Delete all

### Expected Behaviour

Clearing all the alerts

**Comment by PadowYT2** [comment]
Works fine for me, any error? Atleast in Browser Console?

**Comment by Derkades** [comment]
Are you using a custom template? If you are, can you try switching to the default template temporarily to see if the same issue occurs?

**Comment by NorgePlayz** [comment]
> Are you using a custom template? If you are, can you try switching to the default template temporarily to see if the same issue occurs?

Yes. I switched back and now it works

**Comment by PadowYT2** [comment]
Then it is the template issue, contact the author
