### ISSUE TITLE
Event system DX improvements

### ISSUE THREAD

**Issue by tadhgboyle** [NamelessMC/Nameless#3212]
*[Inspiration](https://laravel.com/docs/9.x/events)*

# Problems
Currently our `EventHandler` system works well, but has one main caveat; it is very hard to know what params to pass for each event.
For example, when executing an event:
```php
EventHandler::executeEvent('userBanned', [
	'banned_user_id' => $user->id,
	'banned_by_id' => $staff_user->id,
	// Anything else??
]);
```
When listening to an event:
```php
class UserBannedListener {
	public static function execute(array $params = []) {
		$banned_user = $params['banned_user']; // Typo
		$banned_by = $params['banned_by_id'];
		$reason = $params['reason']; // Doesn't exist!
	}
}
```

To make matters worse, most event hooks will silently ignore missing params:
https://github.com/NamelessMC/Nameless/blob/4cc529be04be6816a00e49546711061756a89bdd/core/classes/Events/HookBase.php#L20-L31
https://github.com/NamelessMC/Nameless/blob/4cc529be04be6816a00e49546711061756a89bdd/modules/Core/hooks/DeleteUserHook.php#L13

# Solutions
One way of solving these problems is to introduce classes for each type of event.
Define the event class:
```php
class UserBannedEvent extends AbstractEvent {
	public User $banned;
	public User $banned_by;
	public string $reason;	

	public function __construct(User $banned, User $banned_by, string $reason) {
		$this->banned = $banned;
		$this->banned_by = $banned;
		$this->reason = $reason; // oh, so we did forget a param in the first example! :p
	}
}
```

Register the event
```php
EventHandler::registerEvent(UserBannedEvent::class);
```
The event class will contain `description()`, `return()` and `internal()` methods, instead of needing to pass them here.

Register some listeners for the `UserBannedEvent`
```php
EventHandler::registerListener(UserBannedEvent::class, UserBannedListener::class);
EventHandler::registerListener(UserBannedEvent::class, UserBannedForumListener::class);
```

Execute the `UserBannedEvent`
```php
EventHandler::executeEvent(new UserBannedEvent(
	$user,
	$staff_user,
	$reason,
));
```

Handle the `UserBannedEvent` within a listener
```php
class UserBannedListener extends AbstractListener {
	public function handle(UserBannedEvent $event) {
		// Do stuff with all of the params, and get type safety!
	}
}

class UserBannedForumListener extends AbstractListener {
	public function handle(UserBannedEvent $event) {
		// Do stuff with all of the params, and get type safety!
	}
}
```

# Backwards compatibility
Since these changes would be quite drastic for event heavy modules, we should provide backwards compatibility for at least 1 major release.
Thanks to the power of PHP reflection:tm:, we can implement a fairly simple backwards compatibility strategy (assuming we keep the behind the scenes the same system until we stop supporting the old way of doing things):

## Registering events
When registering an event, there are two things that can happen for the first parameter (event name (or class name)):
1. They pass some string; `’user_banned’`
	- No conversion has to be done here, we will assume this is what event they want to listen to.
2. They pass a class name; `UserBannedEvent::class`
	- If they pass a class name, no other params will be required, as they will be accessible via the class (`description()`, `internal()`, `return()` methods)
	- We have two options on how to convert it to the equivalent string:
		1. Allow `AbstractEvent`s to define a `name()` method
			```php
		  	class UserWasBannedForSomeReasonEvent extends AbstractEvent {
				public function name() {
					return 'user_banned';
				}
			
				// ...
			}
			```
		2. If `name()` method was not defined, we can attempt to convert the class name - something like this:
			```php
			$class_name = UserBannedEvent::class;
			$parts = preg_split('/(?=[A-Z])/', $class_name); // ['User', 'Banned', 'Event']
			if (end($parts) === 'Event') {
				array_pop($parts); // ['User', 'Banned']
			}

			$string = lcfirst(implode('', $parts)); // 'userBanned'
			```
*These same conversion rules will apply to executing events, so `EventHandler::registerListener($event, ...)` can take in a string or class name as well.*
We can store the event with the string or converted class name so it can be executed using either.

## Registering listeners
Minimal changes will need to occur here.
We will convert the first parameter (string or class name) to determine which event to execute, but the second param will remain the same.

## Executing events
When executing an event, there are two possibilities of how they call `EventHandler::executeEvent`:
1. They pass 2 parameters: `$event` (name of event to execute) + `$params` (array of params to pass to listeners)
	- No changes needed
2. They pass 1 parameter: `$event` (an instance of `AbstractEvent`)
	- If this is the case, we can pull out the `$params` from the `$event` instance, doing something like this:
	```php
	abstract class AbstractEvent {
		public function params(): array {
			return get_object_vars($this); // ['banned' => User, 'banned_by' => User, 'reason' => string]
		}
	}

	class UserBannedEvent extends AbstractEvent {
		public User $banned;
		public User $banned_by;
		public string $reason;	
	
		public function __construct(User $banned, User $banned_by, string $reason) {
			$this->banned = $banned;
			$this->banned_by = $banned;
			$this->reason = $reason;
		}
	}
	```
Actually passing the `$params` array to the listeners may vary, depending on how their `handle` method is defined. See the next section on how we can do it.

## Handling events within listeners
If a listener is defined like so:
```php
class UserBannedListener extends AbstractListener {
	public function handle(UserBannedEvent $event) {
		// Do cool stuff
	}
}
```
When iterating the listeners and we come across a listener which has a param of type `AbstractEvent`, then we can pass an `$event` object (created from `$params` if not passed as an object to `executeEvent`)

Otherwise if a listener is wanting an `array` for its param, we can pass the `$params` array we made in the step above directly.
```php
class UserBannedListener {
	public function handle(array $params) {
		// Do cool stuff, but not as cool as using the new event syntax... :(
	}
}
```

# Bonuses
- Allowing events to be represented as classes could let us do stuff like this:
	```php
	abstract class AbstractEvent {
		public static function dispatch() {
			EventHander::executeEvent(new static(...func_get_args()));
		}
	}

	UserBannedEvent::dispatch($banned, $banned_by, $reason);
	```
- Once we remove the backwards compatibility layer, I think we can remove the idea of "registering events"
- We can create our own [PHP Debugbar collector](http://phpdebugbar.com/docs/data-collectors.html#creating-collectors) to display events executed during page load

# Conclusion
Overall, I am looking to add support for strongly typed and easier to work with events.
By keeping backwards compatibility using the strategy I explained above, I think there are very few (if any) downsides to this nicer system.
If you made it this far, thank you! Please let me know what you think, or if you have suggestions! ❤️

**Comment by partydragen** [comment]
👀

**Comment by tadhgboyle** [comment]
cc @NamelessMC/developer
