### ISSUE TITLE
Make phinx support modules

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#3213]
Allow modules to use the phinx system 

Example as @Aberdeener mentioned
```php
class Module {
	public static function migrationDirs() {
	  $dirs = [];
	  $modules = Module::getModules();
	  foreach ($module as $module) {
	    if (dir_exists($migration_path = '/path/to/$module/migrations') {
	      $dirs[] = $migration_path;
	    }
	  }
	
	  return $dirs;
	}
}

// then in phinx.php
'paths' => [
  'migrations' => [__DIR__, ...Module::migrationDirs()],
],
```

**Comment by samerton** [comment]
We need to consider what to do when a module's folder is deleted - there may be migration history in the database but there will be no matching migration files, will this cause phinx to report there is a mismatch between migrations?

**Comment by Derkades** [comment]
I guess every module would need its own phinx migrations table, operating completely independently from core

**Comment by partydragen** [comment]
What you think about it @Aberdeener ^^ ?
