### ISSUE TITLE
PHP Extensions not detected

### ISSUE THREAD

**Issue by benzyYT** [NamelessMC/Nameless#3253]
So I'm trying to install the latest version of namelessmc. 
When I'm running the install.php it tells me that mbstring and xml are not installed, although they ARE installed.

When I do php -m the output is:
![Screenshot 2023-02-11 145442](https://user-images.githubusercontent.com/70480686/218261700-6d67fdd7-c19d-49a9-ba38-cfbac0f37195.png)

So both are installed. What can I do?

**Comment by supercrafter100** [comment]
They're mostlikely not installed for the php version your webserver is using

**Comment by benzyYT** [comment]
> They're mostlikely not installed for the php version your webserver is using

Yes, they are. I tried all php versions I have installed. When you do php -m you only see the activated ones for that version. So I don't know why they aren't being detected. But thank you.

**Comment by samerton** [comment]
Firstly, don't forget to restart your web server after installing new PHP extensions.

If you have already restarted, then the web server is likely using a different PHP version than the command line.

You can create a new file in your web directory (i.e. the same place Nameless is installed) named `info.php` and add in the following:
```php
<?php
phpinfo();
```

Then, if you visit `yoursite.com/info.php` it will inform you of the PHP version used by the web server  and the extensions installed. If the version is different to the command line, let's say it's PHP 8.0 on the web server, then you can install the relevant extensions in the form of `php8.0-<extension>`, e.g. `php8.0-mbstring`

**Comment by benzyYT** [comment]
> Firstly, don't forget to restart your web server after installing new PHP extensions.
> 
> If you have already restarted, then the web server is likely using a different PHP version than the command line.
> 
> You can create a new file in your web directory (i.e. the same place Nameless is installed) named `info.php` and add in the following:
> 
> ```
> <?php
> phpinfo();
> ```
> 
> Then, if you visit `yoursite.com/info.php` it will inform you of the PHP version used by the web server and the extensions installed. If the version is different to the command line, let's say it's PHP 8.0 on the web server, then you can install the relevant extensions in the form of `php8.0-<extension>`, e.g. `php8.0-mbstring`

Thank you that fixed it!
