### ISSUE TITLE
Outdated custom.css file in release?

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless#3261]
### Describe the issue

It seems the /custom/templates/DefaultRevamp/css/custom.css file in the 2.0.3 release is missing information. Specifically, _at least_ the following lines are missing:

https://github.com/NamelessMC/Nameless/blob/develop/custom/templates/DefaultRevamp/css/custom.css#L981-L1023

That only affects the dark mode toggle in footer, but thought it's worth mentioning.

### NamelessMC Version

2.0.3

### To Reproduce

1. Download 203.zip
2. Witness missing information

### Expected Behaviour

File should be comparable to that on Github.

**Comment by PadowYT2** [comment]
I believe because it is a feature for 2.1.x

**Comment by Derkades** [comment]
Indeed, the `develop` branch is for 2.1.x, and not all changes are backported to `v2.0.x`. This is the latest custom.css file for `v2.0.x`: https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/DefaultRevamp/css/custom.css
