### ISSUE TITLE
Recaptcha v3 validation not working

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#3276]
Changes made in [<https://github.com/NamelessMC/Nameless/pull/3175/files>](https://github.com/NamelessMC/Nameless/pull/3175/files) completly disabled the captcha validation on frontend, This temporially fix was just to disable the validation checking on backend it was never supposed to disable it on frontend

validateToken function is not even used for backend validation on StaffCP i believe

**Comment by tadhgboyle** [comment]
Closing, I believe this was fixed with this PR https://github.com/NamelessMC/Nameless/pull/3307!
