### ISSUE TITLE
I tried setting up the database in the setup and got this error pls help me

### ISSUE THREAD

**Issue by MackenzieGB** [NamelessMC/Nameless#3279]
### Describe the issue

Phinx by CakePHP - https://phinx.org/. using config file core/migrations/phinx.php using config parser php using migration paths - /home/webhosting/w4530/files/web/smazenejpes.eu/core/migrations warning no environment specified, defaulting to: nameless using adapter mysql using database sql_6248 ordering by creation time == 20220519023748 CreateOauthTable: migrating PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:193 Stack trace: #0 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(193): PDO->exec() #1 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(350): Phinx\Db\Adapter\PdoAdapter->execute() #2 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable() #3 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable() #4 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->createTable() #5 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute() #6 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions() #7 /home/webhosting/w4530/files/web/smazenejpes.eu/core/migrations/20220519023748_create_oauth_table.php(18): Phinx\Db\Table->create() #8 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): CreateOauthTable->change() #9 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(385): Phinx\Migration\Manager\Environment->executeMigration() #10 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration() #11 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(124): Phinx\Migration\Manager->migrate() #12 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute() #13 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run() #14 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand() #15 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun() #16 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(240): Phinx\Console\PhinxApplication->doRun() #17 /home/webhosting/w4530/files/web/smazenejpes.eu/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(124): Phinx\Wrapper\TextWrapper->executeRun() #18 /home/webhosting/w4530/files/web/smazenejpes.eu/core/classes/Database/PhinxAdapter.php(68): Phinx\Wrapper\TextWrapper->getMigrate() #19 /home/webhosting/w4530/files/web/smazenejpes.eu/core/installation/steps/ajax_initialise.php(5): PhinxAdapter::migrate() #20 /home/webhosting/w4530/files/web/smazenejpes.eu/core/installation/installer.php(27): require('/home/webhostin...') #21 /home/webhosting/w4530/files/web/smazenejpes.eu/install.php(65): require('/home/webhostin...') #22 {main}

### NamelessMC Version

2.0.0

### To Reproduce

well set up the database 
I put in an alphabetical ip port was normal custom username and the right database name
and it gave me this error

### Expected Behaviour

FIX IT JUST LOAD THE DATABASE

### Screenshots

<img width="1218" alt="Screenshot 2023-03-15 at 18 39 49" src="https://user-images.githubusercontent.com/117526140/225396281-7133f855-050a-4a43-a9b3-558d6bb8242a.png">

### Additional Information

I can give you the exact same information I put in (my database) and access to my ftp so you can reproduce the bug just tell me if you want

**Comment by PadowYT2** [comment]
This is not a bug, you need to update your DB version, also before making issues get help on the [Discord  server](https://discord.gg/nameless)
