### ISSUE TITLE
Hope to support user data of blessing-skin-server

### ISSUE THREAD

**Issue by Baikele** [NamelessMC/Nameless#3280]
### Describe the feature

This is a skin station program, which is about the same as supporting authme.
I hope to add content such as obtaining the avatar and skin of the skin station. This skin station also provides api and oauth, but oauth is not very easy to use.

**Comment by Baikele** [comment]
Oh, yes, or you can modify https://github.com/bs-community/blessing-skin-plugins/tree/master/plugins/forum-integration this plugin for a long time, I am not familiar with php development, so no way to modify

**Comment by Derkades** [comment]
Thank you for the feature request. Anyone is free to create a module for this (you could pay someone to if you really wanted). However, I don't think any core developer is interested in working on this, so I will close the issue.

Perhaps it can be re-opened if there is a wider interest.
