### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#330]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? I can't change the favicon
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No
* Do you have an idea how or where the issue occurs? No :(

Hello, I am here to ask if it is possible to change the favicon because I've updated everything to see my new favicon but it just doesn't work. I am not 100% sure if this is a Nameless bug but I need help, greetings.

**Comment by samerton** [comment]
Hi,

This won't be a bug with Nameless itself as it's simply HTML. Once you've uploaded your favicon (named favicon.ico) to the **core/assets** folder, your favicon will be changed.

Sometimes browsers cache the favicon, so forcing a refresh in your browser (ctrl-F5) should help.

**Comment by Ariuw** [comment]
I've tried to force a refresh in my browser but it just don't work

**Comment by Ariuw** [comment]
Lol I restarted my browser and then it worked, Thanks anyways
