### ISSUE TITLE
Update TinyMCE

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#3312]
### Describe the feature

Currently TinyMCE is running on v5.1.7 and there's an issue, you cannot create a link that opens in current window ([issue reporter](https://canary.discord.com/channels/246705793066467328/247865182477484032/1095232483420811354)), that was fixed in newer versions ([comment about it](https://github.com/tinymce/tinymce/issues/5221#issuecomment-561466816))

**Comment by Derkades** [comment]
Your linked comment says the bug was fixed in 5.1.3, we are using 5.10.7 (latest version).
