### ISSUE TITLE
moz-extension in a default installation

### ISSUE THREAD

**Issue by TonyMontero** [NamelessMC/Nameless#3320]
### Describe the issue

When I create a new page (with no addons, no widgets, no themes, just all the default stuff), something appears under the text. In the template, it's the {$CONTENT} and has no issues with the default theme itself I think.

This is the code:
```
<script src="moz-extension://cd4199ad-ca95-4007-a197-f9dd2f0e8e1b/js/app.js" type="text/javascript" />
<script src="moz-extension://cd4199ad-ca95-4007-a197-f9dd2f0e8e1b/js/app.js" type="text/javascript" /> 
```

I tried with different browsers, in different computers and even in different web connections with no luck.
Internet didn't help me either as I tried without addons as Moz seems to be an extension of my computer, but I tried with computers without extensions and without connections with mine and still happens.

Any idea?

### NamelessMC Version

2.0.3

### To Reproduce

1. Create a new website with a default installation.
2. Text anything.
3. Profit

### Screenshots

![imagen](https://user-images.githubusercontent.com/4236855/233302079-c8c0d33a-d043-40cc-b4d0-34e92ad79dbb.png)

**Comment by PadowYT2** [comment]
1. Please before making issues refer to the [Discord server](https://discord.gg/nameless)
2. This is not a problem with NamelessMC at all. `moz-extension` is a url for extensions you have installed. You totally installed some extension that uses JS like that, you could disable some extensions and see what it is:
![https://devopedia.org/images/article/28/2951.1490520804.gif](https://devopedia.org/images/article/28/2951.1490520804.gif)

Could you share your website link also?

**Comment by samerton** [comment]
Hi,

As Padow says, the browser which created the post in the first place had an extension which inserted this code.

When you view the post in the future, regardless of which browser/computer you are using, you will see the same code.

If you have set a signature in your user settings, it may need clearing from there too.
