### ISSUE TITLE
Failed to connect to the database: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by ehte89** [NamelessMC/Nameless#3328]
### Describe the issue

i am getting
Failed to connect to the database:
SQLSTATE[HY000] [2002] No such file or directory

even if i use root it still throws the same error or any other user that has all perms on the database

### NamelessMC Version

Development version

**Comment by supercrafter100** [comment]
Not a nameless issue, rather one with your database installation. Please see https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory
