### ISSUE TITLE
Plugin repository

### ISSUE THREAD

**Issue by sergivb01** [NamelessMC/Nameless#333]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? Lastest
* How would you describe the issue? Why did the plugin repository disappeared? (https://github.com/NamelessMC/Nameless/wiki) - https://github.com/NamelessMC/Plugin
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No
* Do you have an idea how or where the issue occurs? Add the plugin repository again or I would like to know if it is continuing developing.

**Comment by PugaBear** [comment]
#316

**Comment by sergivb01** [comment]
What I mean is that in the wiki page of Github, there is a link to the plugin repository. If you click it it goes to 404.

**Comment by aycgit** [comment]
@sergivb01 ill just edit that out then

**Comment by sergivb01** [comment]
Thanks - Close the issue

**Comment by samerton** [comment]
Just to add onto this, when the plugin is ready it will be open source and found in a new repository.
