### ISSUE TITLE
Stop users from putting tags on their own posts.

### ISSUE THREAD

**Issue by DataPools** [NamelessMC/Nameless#335]
How would I stop users from putting tags on their own threads?

**Comment by samerton** [comment]
This isn't possible in 1.0.10 unfortunately, however it's planned for some point in the near future (https://github.com/NamelessMC/Nameless/issues/3#issuecomment-216003471)

**Comment by samerton** [comment]
I'll mark this as closed so #3 can be used for permissions discussion.
