### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by NicoDevv** [NamelessMC/Nameless#3357]
### Describe the issue

I installed nameless but when trying to login or verify from the site this error is given:

 

There was an error loading this menu. The website owner needs to follow these steps to fix it:

1. Make sure the hostname value in core/config.php in FTP matches your site url.

2. If you are using the www. prefix make sure the force www option is enabled in StaffCP -> Configuration -> General Settings.

 

I tried everything, I put all possible hostnames:

sitename .it

www. sitename .it

https://www/. sitename .it/

https:// sitename .it/

 

and I have already tried to force both the www and the https but nothing, how can I fix it? Maybe it's a CloudeFlare problem?

### NamelessMC Version

< 2.1.0

### Screenshots

![Immagine 2023-05-07 021204](https://user-images.githubusercontent.com/117598398/236674307-9c6dd74b-8d98-4638-8c66-f1a72961cb24.png)

**Comment by supercrafter100** [comment]
This is an issue with the custom template you are using. We do not have this functionality in our core system. Please contact the template author.
