### ISSUE TITLE
Placeholder bug on browser desktop notification

### ISSUE THREAD

**Issue by mja00** [NamelessMC/Nameless#3364]
### Describe the issue

When getting a desktop notification from my browser it contains the text `{{count}}` instead of being filled in. 

Happens on both Edge and Firefox on both Windows and macOS. Most likely happens on all browsers.

### NamelessMC Version

2.1.0

### To Reproduce

1. Have desktop notifications enabled
2. Get a new message.
3. See the notification has `{{count}}` in it.

### Expected Behaviour

The `{{count}}` value to be filled in.

### Screenshots

![image](https://github.com/NamelessMC/Nameless/assets/11252574/9ce2fb25-e72e-443f-ab67-a2b27c3c4d93)
<img width="355" alt="CleanShot 2023-05-09 at 13 58 26@2x" src="https://github.com/NamelessMC/Nameless/assets/11252574/45f952c6-3636-46eb-b9eb-4e7fa7621e95">

**Comment by Derkades** [comment]
thanks for the bug report!
