### ISSUE TITLE
Not sending mails

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#338]
* What kind of issue is it (Question, Bug, etc.)?
Bug
* In which version of NamelessMC did it occur (1.x.x)?
1.0.10
* How would you describe the issue? 
Well the bouth email php functions doesnt work. Im trying to register and i dont get a mail.. the smtp one is not working and the other one used to work on my other web host but not since i moved to cpanel...
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No.. i dont think it needs pics
* Do you have an idea how or where the issue occurs?
I think its cus of the new host.. cpanel related? i only use the PHP mail() function, i do not use smtp, tried that ones it takes f4 to load the register page..

**Comment by samerton** [comment]
[This](https://github.com/NamelessMC/Nameless/wiki/FAQs#nameless-wont-send-emails-to-users) and [this](https://github.com/NamelessMC/Nameless/wiki/Setting-up-Gmail-or-SMTP-with-Nameless) should help you out, unfortunately this just comes down to configuration.

**Comment by IsS127** [comment]
well i have cpanel not self hosted :( i do have ssh access but cant seem to install anything..

**Comment by IsS127** [comment]
Woops accidently closed

**Comment by samerton** [comment]
If you're using cPanel, it's worth contacting your host letting them know the PHP mail function isn't configured, this will be an issue on their side.

**Comment by IsS127** [comment]
Ok ty :)
