### ISSUE TITLE
`bootstrap-colorpicker` deprecated/unmaintained - find alternative

### ISSUE THREAD

**Issue by Justman10000** [NamelessMC/Nameless#3381]
[bootstrap-colorpicker](/itsjavi/bootstrap-colorpicker) is depraced! It is recommended to replace it with [React Color](https://casesandberg.github.io/react-color)

**Comment by Aberdeener** [comment]
Thanks for bringing this up, however the alternative will not work for Nameless as it's a React component and we do not use React. Will keep this open until we find something else that we can use

**Comment by Derkades** [comment]
There are active forks like [this one](https://github.com/lesjoursfr/colorpicker) but I'm not sure if it's worth switching. As long as the color picker works, I don't think it's an issue that it's deprecated.

**Comment by Aberdeener** [comment]
Yeah, that's true actually. Even that fork just played around with the dependencies 🤣
