### ISSUE TITLE
When I enter in my website (with Cobalt) with no user account I receive a "Fatal Error"

### ISSUE THREAD

**Issue by Prozoon700** [NamelessMC/Nameless#3385]
### Describe the issue

The other day I install Cobalt v1.6.7 and I while I was setting all I saw that when you enter in the website with no account it shows you this page (is in spanish) with the title of Fatal Error.
![image](https://github.com/NamelessMC/Nameless/assets/65341326/0c877a8d-2353-4fe9-a03b-fdbdec49419a)

I have tested a lot of things but I don't know whats the problem, can someone help?
I know Cobalt v1.6.7 is not for NamelessMC v2.1.0, but if I reinstall an old version I could have some problems?

Thanks for the help and I'll be waiting response.

### NamelessMC Version

2.1.0

### To Reproduce

1. Go to your website.
2. Wait until the Goverment takes out the electricity of your house.

### Additional Information

Chrome Console Log: 
```
jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of null (reading 'classList') TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDocument.<anonymous> (https://foro.faircraft.online/:131:39)
    at e (https://foro.faircraft.online/core/assets/vendor/jquery/dist/jquery.min.js:2:30310)
    at t (https://foro.faircraft.online/core/assets/vendor/jquery/dist/jquery.min.js:2:30612) undefined
E.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDocument.<anonymous> ((índice):131:39)
    at e (jquery.min.js:2:30310)
    at t (jquery.min.js:2:30612)
```

**Comment by PadowYT2** [comment]
This isn't an issue with NamelessMC, please refer to the [Coldfire Design](https://discord.gg/jjGQEYyA) server and I'll help you there

**Comment by Prozoon700** [comment]
Ok, sorry
