### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by epicskymi** [NamelessMC/Nameless#339]
### Template:
* What kind of issue is it (Question, Bug, etc.)? bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? I click admincp it asks me to "Please re-authenticate" and every time I click something like misc, forums, style or anything other then overview and then it just brings me back to the home screen/ start page 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? ^
* Do you have an idea how or where the issue occurs? nope everything installed find only I saw red text about uuids or something at the end

**Comment by samerton** [comment]
How are you hosting your website?

Some web hosts aren't compatible with Nameless, and until 2.0 no fixes for this will be available.

**Comment by epicskymi** [comment]
I switched hosts now it works thanks mate was using a free host so I could figure out how to set things up but I just bought one to see if that was the issue and ye it worked :)

**Comment by samerton** [comment]
Glad it works :)
