### ISSUE TITLE
Modules having problems supporting eachother

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#3392]
Like registering listeners for modules with are not yet loaded cases listeners to not be made correctly with throws fatal error when event is called

This can be a issue for several features and future features

Modules should have a pre load system so classes being preloaded before the module actually being loaded or perhaps make a new onEnable with being called after all modules are pre loaded or just call the constructer

The module load_before and load_after only supporting full dependencies, But even this wont be a properly solution for modules that making listeners etc both ways of need any classes from another module during construction or something

**Comment by samerton** [comment]
https://github.com/NamelessMC/Nameless/pull/3397
