### ISSUE TITLE
error Failed to connect or create a socket: 110 (Connection timed out)

### ISSUE THREAD

**Issue by epicskymi** [NamelessMC/Nameless#340]
### Template:
* What kind of issue is it (Question, Bug, etc.)?Query
* In which version of NamelessMC did it occur (1.x.x)?1.0.10
* How would you describe the issue?Its says my server is offline and gives me this error Failed to connect or create a socket: 110 (Connection timed out)
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? When I tick the external query method it works 
* Do you have an idea how or where the issue occurs? nope

**Comment by samerton** [comment]
Unfortunately some web hosts block the use of PHP sockets, you'll need to use the external query instead.

**Comment by epicskymi** [comment]
ah that sucks but at least something works however even with show players online which I would assume would show player heads it doesn't. unless im wrong about what it does

**Comment by samerton** [comment]
The external query doesn't support a list of player heads at the moment. The query used is a third party so I have no control over what's returned, but hopefully in the future this can be changed.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any other questions feel free to reopen.
