### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#341]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue?  I've installed my website really good but when the instalation is finished I just can't log in my page it means that when I use: mywebsite.com I get a message that says something like this: "mywebsite isn't working" (It is in spanish so I don't know how to translate it into the english language)
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Nop
* Do you have an idea how or where the issue occurs? No :(

**Comment by sergivb01** [comment]
Just comment the message and I could translate (I am Spanish)

**Comment by Ariuw** [comment]
La página mywebsite.web no funciona

La página mywebsite.web no puede procesar esta solicitud ahora.

**Comment by sergivb01** [comment]
Hmmm which software are you using? Can you make a screenshot or something? Paste your apache log?

**Comment by Ariuw** [comment]
I don't know what do you mean saying software and apache log

**Comment by sergivb01** [comment]
Xampp, wamp, manually installed...?¿

**Comment by Ariuw** [comment]
It has been manually installed

**Comment by samerton** [comment]
Which operating system are you running?

**Comment by Ariuw** [comment]
I am using Ubuntu 14.04

**Comment by sergivb01** [comment]
Which hostname are you using (localhost,domain, ...?

**Comment by Ariuw** [comment]
domain

**Comment by samerton** [comment]
Try checking **/var/log/apache2/error.log** to see if there are any errors related to Nameless in there.

**Comment by Ariuw** [comment]
This has been fixed. I forgot to add a database number
