### ISSUE TITLE
Navbar Spelling Issue

### ISSUE THREAD

**Issue by laserjet25** [NamelessMC/Nameless#3415]
### Describe the issue

Member is misspelled on the navbar in American English. It is currently "menber".

I tried searching the code but could not find where this spelling error was located.

### NamelessMC Version

2.1.0

### To Reproduce

1) Fresh install of NamelessMC.
2) Finish setup.
3) Go to main webpage.

### Expected Behaviour

Correct spelling of Member.

### Screenshots

![image](https://github.com/NamelessMC/Nameless/assets/7650139/0783924a-fa8a-4c4d-88c7-b98567128707)

**Comment by partydragen** [comment]
This issue is already fixed in https://github.com/NamelessMC/Nameless/commit/ffed2681b1f59c167587bc9e3de64a7e23b3f54e

**Comment by laserjet25** [comment]
That must have been why I couldn't find it :)

Thanks for fixing this!
