### ISSUE TITLE
Web.de mail

### ISSUE THREAD

**Issue by TobiCB11** [NamelessMC/Nameless#3418]
### Describe the issue

Hello,
If you register with a Web Mail from Web.de you didnt get any Verify Mail.

### NamelessMC Version

2.1.0

### To Reproduce

Register
Use a Mail from Web.de

**Comment by PadowYT2** [comment]
What settings did you put in? This isn't a problem with NamelessMC nor phpMailer, but probably the configuration

**Comment by TobiCB11** [comment]
We have use a SMTP Server.
We have test it and it send to Web mails.
But in the Forum it didnt send a Mail.

**Comment by PadowYT2** [comment]
> We have use a SMTP Server. We have test it and it send to Web mails. But in the Forum it didnt send a Mail.

Does the test button work?

**Comment by TobiCB11** [comment]
No

**Comment by PadowYT2** [comment]
> No

Ok, well what's the error?

**Comment by TobiCB11** [comment]
Unfortunately there is no error.
Unfortunately, the e-mails are not sent or do not arrive

**Comment by PadowYT2** [comment]
> Unfortunately there is no error. Unfortunately, the e-mails are not sent or do not arrive

Show how you did setup your mail configuration

**Comment by TobiCB11** [comment]
![Screenshot 2023-07-19 134820](https://github.com/NamelessMC/Nameless/assets/81191521/af295ac6-5e7a-4b57-82a7-ccbeec5d3748)

**Comment by PadowYT2** [comment]
Follow https://docs.namelessmc.com/en/smtp#debugging-phpmailer-only

**Comment by samerton** [comment]
I will mark this as closed - if you are still experiencing issues feel free to re-open
