### ISSUE TITLE
New view_topic index

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#342]
* What kind of issue is it (Question, Bug, etc.)? Question

Hello, I am here to ask if it possible to create something like this:

<img src="http://image.prntscr.com/image/ae23595f9f1f4266a53e5897cb730163.png">

I've already moved the Forum Sidebar to the left and the topic content and replies to the right the only problem is that the Forum sidebar when you're on a topic is just don't work. It looks like this:

<img src="http://image.prntscr.com/image/88f8870f46be4d26b05db6e459e58db6.png">

**Comment by sergivb01** [comment]
If you can provide the code would be better to determine where is the problem.

**Comment by Ariuw** [comment]
What I use is:

E.x:     <div class="col-md-9 pull-right">
and then it moves to the right

**Comment by Ariuw** [comment]
Ok so... I think that this can't never happen lol

**Comment by samerton** [comment]
Should the forum sidebar display a list of forums?

**Comment by Ariuw** [comment]
Yeah, that's the point having a forum sidebar on the left of the topic, is that possible?

**Comment by sergivb01** [comment]
I think it would be better to add an option to move it. Am I right??

**Comment by Ariuw** [comment]
What does it means?

**Comment by samerton** [comment]
This isn't actually possible at the moment as a list of forums isn't generated within the view topic page.

**Comment by Ariuw** [comment]
Oooh okey, its fine thanks anyways ^^
