### ISSUE TITLE
I can't install namelessmc, I need your help.

### ISSUE THREAD

**Issue by Huisto** [NamelessMC/Nameless#3429]
### Describe the issue

Phinx by CakePHP - https://phinx.org. using config file core/migrations/phinx.php using config parser php using migration paths - /home/ftp/3/3kenctf27i223/web/core/migrations warning no environment specified, defaulting to: nameless using adapter mysql using database 3kenctf27i223 ordering by creation time == 20220519023748 CreateOauthTable: migrating PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:193 Stack trace: #0 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(193): PDO->exec() #1 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(350): Phinx\Db\Adapter\PdoAdapter->execute() #2 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable() #3 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable() #4 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->createTable() #5 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute() #6 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions() #7 /home/ftp/3/3kenctf27i223/web/core/migrations/20220519023748_create_oauth_table.php(18): Phinx\Db\Table->create() #8 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): CreateOauthTable->change() #9 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(385): Phinx\Migration\Manager\Environment->executeMigration() #10 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration() #11 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate() #12 /home/ftp/3/3kenctf27i223/web/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute() #13 /home/ftp/3/3kenctf27i223/web/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run() #14 /home/ftp/3/3kenctf27i223/web/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand() #15 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun() #16 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(240): Phinx\Console\PhinxApplication->doRun() #17 /home/ftp/3/3kenctf27i223/web/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(124): Phinx\Wrapper\TextWrapper->executeRun() #18 /home/ftp/3/3kenctf27i223/web/core/classes/Database/PhinxAdapter.php(42): Phinx\Wrapper\TextWrapper->getMigrate() #19 /home/ftp/3/3kenctf27i223/web/core/installation/steps/ajax_initialise.php(5): PhinxAdapter::migrate() #20 /home/ftp/3/3kenctf27i223/web/core/installation/installer.php(19): require('...') #21 /home/ftp/3/3kenctf27i223/web/install.php(65): require('...') #22 {main}

### NamelessMC Version

2.1.0

### Screenshots

![image](https://github.com/NamelessMC/Nameless/assets/141564885/0f3105b4-5ea4-47ef-9891-0c1363994056)

### Additional Information

What makes me unable to install namelessmc, I need your help.

**Comment by PadowYT2** [comment]
There's no need to make an issue on GitHub, you could've gotten help on [discord.gg/nameless](https://discord.gg/nameless). Anyways:
![https://cdn.padow.ru/DT3GL](https://cdn.padow.ru/DT3GL)

**Comment by supercrafter100** [comment]
Nothing wrong with posting it here. Not everyone has a Discord account. As Padow already posted, the database version you are using is very outdated, causing the error.
