### ISSUE TITLE
No one can login the forums after update to 1.0.10

### ISSUE THREAD

**Issue by KillerAntMC** [NamelessMC/Nameless#343]
* What kind of issue is it (Question, Bug, etc.)? Once I updated my forums to 1.0.10, players and I couldn't log into the forums. I tried logging into the admin cp and it wouldn't work as well. It worked when I was on 1.0.9.
* In which version of NamelessMC did it occur (1.x.x)? Update from 1.0.9 to 1.0.10
* How would you describe the issue?  I can't login to the forums. 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://prntscr.com/bwgv40, i'm not sure where error logs are stored in namelessmc.
* Do you have an idea how or where the issue occurs? I'm not sure on what could be causing it.

**Comment by samerton** [comment]
Looking over the commits for the 1.0.10 update, there aren't any changes which would affect the login files or the users database table.

How did you upgrade your site?

**Comment by IsS127** [comment]
Check you're database is there still users? Try to make a new acc and see if it works

**Comment by KillerAntMC** [comment]
@samerton I dropped all the files in the zip folder that comes with the update into the pre existing files. Then I clicked the update button and it updated.

@IsS127 All the users are still in the databases. When I make a new account and login it works.

**Comment by KillerAntMC** [comment]
Issue seems to be fixed now.

**Comment by samerton** [comment]
Glad to hear
