### ISSUE TITLE
Cannot assign null to property User::$_main_group of type Group

### ISSUE THREAD

**Issue by DexterSK** [NamelessMC/Nameless#3435]
### Describe the issue

When registering got following error on:
https://xxxxx/validate/?c=ckj39dRWaMTD71gx2caGBWt9fvbHeMVxxfisTHI3O4

### NamelessMC Version

Development version

### To Reproduce

1. Register account

### Expected Behaviour

No error

### Screenshots

![ddd](https://github.com/NamelessMC/Nameless/assets/4334671/d259737e-d7b7-4190-acf2-3fc47205dbd8)

### Additional Information

[2023-09-01, 15:42:45] /data/web/virtuals/311905/virtual/www/core/classes/Core/User.php(649): Cannot assign null to property User::$_main_group of type Group

**Comment by PadowYT2** [comment]
Please enable debug via removing `//` in index.php on line 13. Also on what version are you on?

**Comment by DexterSK** [comment]
![ddd](https://github.com/NamelessMC/Nameless/assets/4334671/beb3e3f1-bf55-49cd-bd1e-ad73b878b1c0)
i'm on latest 2.1.1

**Comment by DexterSK** [comment]
Tried to debug it and found

public function getMainGroup(): Group {
		die( var_dump( $this->getGroups() ) ); //this returns null array on registration

        return $this->_main_group ??= array_reduce($this->getGroups(), static function (?Group $carry, Group $group) {
            return $carry === null || $carry->order > $group->order ? $group : $carry;
        });
    }

**Comment by samerton** [comment]
I believe this will be fixed in the next update which will hopefully be available soon.

Edit: sorry didn't see this is using the development version, we'll have to look into it, thanks for the report

**Comment by samerton** [comment]
Should be fixed in https://github.com/NamelessMC/Nameless/releases/tag/v2.1.2
