### ISSUE TITLE
Unable to specify MySQL Server address

### ISSUE THREAD

**Issue by TheMeq** [NamelessMC/Nameless#3439]
### Describe the issue

When installing NamelessMC for the first time, I specify my databases IP address (which is hosted on a different server to the web server). But when I click "Proceed" to move to the next step, it gives me the following error: 

Failed to connect to the database:
SQLSTATE[28000] [1045] Access denied for user 'username'@'domain' (using password: YES)

Of which 'domain' is the name of the web server, not the IP address I specified. 

### NamelessMC Version

2.1.0

### To Reproduce

Go to install.php as if installing
Click Proceed until you get to the database section. 

Specify an IP address that is not 127.0.0.1 or localhost 

Fill in username and password for this external database and click Proceed. 

Error occurs. 

### Expected Behaviour

NamelessMC should allow me to specify the external IP address or domain of my mysql instance.

**Comment by PadowYT2** [comment]
This is not a bug, solutions:
- Is the password valid?
- Is the user you're trying to connect with authorized to access the given database from this IP address?
- Did you correctly give that user permission to even access that database?
- Do you have a Firewall that is blocking connections?
- Is your MySQL instance bound to `127.0.0.1` or `localhost` and you're trying to connect from outside the server?
- Does the user have `GRANT` permissions if you're trying to use them to create a new database for a server?

## If using a VPS/VDS/Dedicated
An another solution: Is your MySQL instance running? `systemctl status mysql`

**Comment by TheMeq** [comment]
Is the password valid?
   Yes
   
Is the user you're trying to connect with authorized to access the given database from this IP address?
   Yes
   
Did you correctly give that user permission to even access that database?
   Yes
   
Do you have a Firewall that is blocking connections?
   No 
   
Is your MySQL instance bound to 127.0.0.1 or localhost and you're trying to connect from outside the server?
   No, as specified in my post, my mysql server is on a different server. I entered the address for that server. 
   
Does the user have GRANT permissions if you're trying to use them to create a new database for a server?
   Yes

**Comment by TheMeq** [comment]
Sorted
