### ISSUE TITLE
letters

### ISSUE THREAD

**Issue by zikyales** [NamelessMC/Nameless#344]
EN : Hello, what should I do if I want to write the word player and when I save so to me there's one letter is displayed, and instead displays (?) What should I do so I wrote that word.  https://ctrlv.cz/tbRE

CZ : Dobrý den, co mam dělat když chci napsat slovo hráč a když to uložím tak se mi tam to jedno písmeno nezobrazí a místo něj se zobrazí (?) Co mam udělat aby se mi napsalo to slovo. https://ctrlv.cz/tbRE

Application: Translate

**Comment by samerton** [comment]
What is the letter that sahould be displayed instead of "?"

**Comment by zikyales** [comment]
č

**Comment by samerton** [comment]
Is this a custom page (created in the AdminCP)?

**Comment by zikyales** [comment]
Yes

**Comment by samerton** [comment]
I've taken a look, and I can't reproduce any issues.

I can only assume this is down to the MySQL table configuration on the "nl1_custom_pages" table. If you have something like phpMyAdmin to manage your database, head to the "Operations" tab for the "nl1_custom_pages" database table, and change the Collation setting to "utf8-bin".

**Comment by zikyales** [comment]
Hello , I'm a little you understand what should I do ?

https://ctrlv.cz/CKFA

I am Czech

translators

**Comment by zikyales** [comment]
I did it according to what you wrote to me , but it keeps saying ( ? ) When I write (č )

**Comment by aycgit** [comment]
@zikyales ik dont know how those languages work but could it be just your keyboard?

**Comment by zikyales** [comment]
No

**Comment by samerton** [comment]
Unfortunately I've not been able to reproduce issues, I'll keep looking into it though.

**Comment by samerton** [comment]
I still haven't been able to reproduce your issue, it works fine on my end.
Can you edit your custom page, click the "Source" tab in the editor, and replace the letter with `&#269;` to see if that helps?

**Comment by samerton** [comment]
Solution in https://github.com/NamelessMC/Nameless/issues/481#issuecomment-264727114
