### ISSUE TITLE
[Sugestion] Custom links name

### ISSUE THREAD

**Issue by dgateles** [NamelessMC/Nameless#345]
Add possibility to change links, for example:
www.mysite.com/infractions to www.mysite.com/bans
www.mysite.com/sigout to www.mysite.com/out 
or whatever name i want.

**Comment by samerton** [comment]
This is possible at the moment, however you'd need to change files manually.
You can rename the pages in the **pages** directory (for example infractions.php to bans.php), and you'll also need to manually find the link locations and change the code for them within other files. 

Version 2.0 will allow for custom modules, and it will be up to the authors of the modules if they want to allow this or not.

**Comment by samerton** [comment]
I'll mark this as closed, as technically it's possible for modules to implement this functionality in v2.
The core Nameless system itself won't have this ability, as too many things depend on it, but for modules such as Infractions it can be implemented.
