### ISSUE TITLE
There was a problem loading the widget Statistics: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`site_4195`.`nl2_users_groups`, CONSTRAINT `nl2_users_groups_ibfk_2` FOREIGN KEY (`group_id`) REFERENCES `nl2_groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

### ISSUE THREAD

**Issue by ClassyCoder1** [NamelessMC/Nameless#3455]
### Describe the issue

There was a problem loading the widget Statistics: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`site_4195`.`nl2_users_groups`, CONSTRAINT `nl2_users_groups_ibfk_2` FOREIGN KEY (`group_id`) REFERENCES `nl2_groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

### NamelessMC Version

Development version

### Screenshots

![Screenshot_2023-10-08-17-09-11-139-edit_com android chrome](https://github.com/NamelessMC/Nameless/assets/85794873/1f0ac6f7-cc35-4611-a07a-ea8b61e117af)

**Comment by samerton** [comment]
Hi,

Have you deleted the default Member group (with ID `1` in the StaffCP -> Groups tab)

**Comment by samerton** [comment]
I'll mark this as closed for now as I cannot reproduce the issue.
