### ISSUE TITLE
Where is located this

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#346]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10

May I ask where is this located?: 

/profile/{$discussion.last_reply_mcname} {$discussion.last_reply_avatar}

**Comment by samerton** [comment]
I'm not sure what you're referring to with this sorry, were you able to resolve the issue?
