### ISSUE TITLE
Green Checkmark does not get shown in color

### ISSUE THREAD

**Issue by JustJP2K** [NamelessMC/Nameless#3462]
### Describe the issue

The green checkmark emoji doesn't get shown as being green in the published page. it gets converted to black.

### NamelessMC Version

Development version

### To Reproduce

1. Make a custom page
2. click on emojies
3. select green check mark
4. publish page
5. see that it gets converted to black

### Expected Behaviour

Green emoji stays green.

### Screenshots

![image](https://github.com/NamelessMC/Nameless/assets/74447960/989ef147-a001-47af-b6e2-adc7ebfd88de)
![image](https://github.com/NamelessMC/Nameless/assets/74447960/a6ea31a0-f353-487a-b9ee-25a076fc1ecd)

### Additional Information

Tested with default template as well as custom template. doesnt work on either.
Version: 2.1.2

**Comment by PadowYT2** [comment]
Rather this is not a bug, it is because in the editor, your system shows the emoji as it's own unicode, but in StaffCP > Configuration > Emoji you are using a different type of a system

**Comment by JustJP2K** [comment]
> Rather this is not a bug, it is because in the editor, your system shows the emoji as it's own unicode, but in StaffCP > Configuration > Emoji you are using a different type of a system

Could it be made green? since other modules for example the wiki module have it shown as green

![image](https://github.com/NamelessMC/Nameless/assets/74447960/cd238606-7f3d-435a-b763-303c3e64cd76)

**Comment by Derkades** [comment]
Did you follow Padow's instructions to change the emoji type? I guess the wiki module does not respect StaffCP settings.

**Comment by JustJP2K** [comment]
> Did you follow Padow's instructions to change the emoji type? I guess the wiki module does not respect StaffCP settings.

I tried but there is no Emoji Settings in Configuration. at least i couldnt find any.
![image](https://github.com/NamelessMC/Nameless/assets/74447960/a4612184-f8b9-484d-97e9-1bcd894614f8)

**Comment by PadowYT2** [comment]
My bad, in General Settings

**Comment by JustJP2K** [comment]
> My bad, in General Settings

thanks that fixed it :)
