### ISSUE TITLE
Login verification bug

### ISSUE THREAD

**Issue by MsEDok** [NamelessMC/Nameless#3463]
### Describe the issue

When a user register their account with username and email

they will need to verify their account but if the setting is set to login method Email or USername user doesnt need to verify the account.

### NamelessMC Version

2.1.0

### To Reproduce

1. Register an account (without verify  your account with the email link)
2. change login method in "StaffCP -> General Settings -> Login Method" to Email
3. try login with email you will get send an message saying "account inactive please verify email"
4. change login method in "StaffCP -> General Settings -> Login Method" to Username
5. try login with email you will get send an message saying "account inactive please verify email"
6. change login method in "StaffCP -> General Settings -> Login Method" toEmail & Username
7. Try login with Email and you will be able to login
8. Try login with Username you will get send an message saying "account inactive please verify email"

### Expected Behaviour

User not able to login when their account is not verify and "StaffCP -> General Settings -> Login Method" is set to Email or Username

**Comment by partydragen** [comment]
Thanks for reporting the issue, I have confirmed the bug
