### ISSUE TITLE
"Unable to update your Minecraft username"

### ISSUE THREAD

**Issue by SkyDZN** [NamelessMC/Nameless#347]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10

Hello,
If I try to use the "Update your Minecraft username" button, it says: "Unable to update your Minecraft username", but I have no idea why it is giving this error.
Could someone help me with this?

Thanks.

**Comment by Ariuw** [comment]
Are you sure that the UUID is the correct?

**Comment by SkyDZN** [comment]
Yes, I just registered the account with an old IGN, so I tried to update the username, but still the error..

**Comment by Ariuw** [comment]
Any screenshot?

**Comment by SkyDZN** [comment]
Nevermind, I thought that when I create an account with an old IGN, that it will use the UUID, but guess not. I needed to enter the UUID manually via the AdminCP and now it works. Thanks though.
