### ISSUE TITLE
PHP Exif

### ISSUE THREAD

**Issue by HelloWorldCoder-China** [NamelessMC/Nameless#3477]
NamelessMC said that it need PHP Exif.So,where can I get PHP Exif and how can I install it into a server that haven't got a termitle , and got only :1-A file editer 2-A SQL page?

note:I am from China so there might be some spelling error in this issue file.

Please respond as soon as you can , thank you.

**Comment by PadowYT2** [comment]
If you are on a webhost, contact them. If you have a machine - `apt install php-exif`

**Comment by HelloWorldCoder-China** [comment]
> If you are on a webhost, contact them. If you have a machine - `apt install php-exif`

Thank you.

**Comment by JohnRichard4096** [comment]
Although I'm already installed php-exif,it just said " You must have all of the required extensions installed, and have correct permissions set, in order to proceed with installation."
![QQ截图20240419215227](https://github.com/NamelessMC/Nameless/assets/67693593/20adac16-41e3-4c23-a8a4-9664bd888601)

**Comment by Derkades** [comment]
If you have installed the exif extension and restarted php-fpm, or your webserver if you are not using php-fpm, the most likely cause is installing the extension for a different PHP version than the one being used for NamelessMC. Please ensure that you do not have duplicate PHP installations, for example by listing PHP packages using the command `apt list --installed 'php*'`. In the future, please post a new question as any new messages in this thread will notify everyone else who participated :)
