### ISSUE TITLE
Determine the right group for chown

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#3480]
### Describe the feature

This is based on 
https://github.com/NamelessMC/Nameless/blob/fcaa51708c23d592a92209d9ff7728f557070647/core/init.php#L43
basically, on CentOS, it is either nginx/apache and not www-data. Not sure if possible, but PHP should determine the right group

**Comment by Derkades** [comment]
get_current_user() should work

**Comment by samerton** [comment]
According to the docs, `get_current_user()` returns the owner of the current file as opposed to the user running the PHP process: https://www.php.net/manual/en/function.get-current-user.php
