### ISSUE TITLE
SMTP for Gmail does not work.

### ISSUE THREAD

**Issue by lezetho** [NamelessMC/Nameless#3481]
### Describe the issue

Gmail SMTP does not work. When I send a test email to my account, it says it successfully sent but after a couple of minutes the email doesn't get sent. I tried setting up my Zoho Mail SMTP but it says it wasn't able to successfully connect to the host.

### NamelessMC Version

2.1.0

### To Reproduce

1. Get the Dist ZIP
2. Send the outgoing email to a gmaill
3. Attempt sending a test email and wait
4. If you have a SMTP server, try using a SMTP server.

### Expected Behaviour

I was expecting the email to successfully send and my SMTP server works.

### Screenshots

![image](https://github.com/NamelessMC/Nameless/assets/126505858/92974d2c-fe81-4524-9644-aef8868365cc)
![image](https://github.com/NamelessMC/Nameless/assets/126505858/fd02a99e-02fb-4099-8c34-20ee0af52e3b)
![image](https://github.com/NamelessMC/Nameless/assets/126505858/d60239b9-4f79-47ce-ace2-b581b918de68)
![image](https://github.com/NamelessMC/Nameless/assets/126505858/ca1e86db-1157-49c8-b741-abefbcbf6a59)
![image](https://github.com/NamelessMC/Nameless/assets/126505858/17522ac4-4aff-491f-b16a-6cfaa1e32e85)

**Comment by SpookyKipper** [comment]
You can't send @gmail.com from a server other than Gmail, you have to use gmail's smtp for it
