### ISSUE TITLE
Verification Email will not send

### ISSUE THREAD

**Issue by PeterEstephan** [NamelessMC/Nameless#35]
Hey, 

I just setup a completely new NamelessMC site, and I just was testing the user registration. When I register a user and check the email for a verification email, it is not there. Then I go and check my Email settings under the core tab and it seems everything is right, unless I misconfigured something. My incoming email is the same as the outgoing email address. And I have tried both PHP mail() function on and off and it made no difference when my email was sent. I am using a gmail account to send the emails. 

Thanks for your support!

**Comment by samerton** [comment]
Hi,

If you're using a Gmail account, you'll need to do a bit more configuration. 

Edit **core/email.php** and fill in the following fields.

'username' is your Gmail address
'password' is your Gmail account password
'name' is, again, your site name
'host' is smtp.gmail.com

Make sure you don't touch the 'port' or 'secure' fields as they're correct as they are.

Then head into the AdminCP's Core tab and click "Email" near the top. Deactivate the "Use PHP mail() function", and click Submit.

Hopefully that helps.

**Comment by PeterEstephan** [comment]
<?php 
$GLOBALS['email'] = array(
	'username' => 'peter@theshadowsmc.net',
	'password' => '***password***',
	'name' => 'The Shadows - Support',
	'host' => 'smtp.gmail.com',
	'port' => 587,
	'secure' => 'tls'


So I would have to change the name to just the site name or it would not matter? I would have to change it to : "The Shadows" ? 

Also, this is my site: theshadowsmc.net


);

**Comment by samerton** [comment]
"Name" is simply the "From" field in the email, it's totally up to you what you'd like it to be.

**Comment by PeterEstephan** [comment]
So that is what I currently have and it does not send emails. Is there anything else I could try to see what the problem is?

**Comment by samerton** [comment]
Unfortunately I'm not too sure about this, Nameless uses an [external email library](https://github.com/PHPMailer/PHPMailer). Just to be sure, has the email shown up in your spam folder, and has the email account been set up within Gmail (as you're using a custom domain).

**Comment by PeterEstephan** [comment]
Well, the email is not in my spam folder, and I am using my domain name on google server. It was made with Google for Work (https://apps.google.com/). And I know it works on the smtp.gmail.com server because I previously used phpBB forums and I set it up using that and it worked.

**Comment by samerton** [comment]
I'll go ahead and close this issue as it has been resolved through email.

**Comment by DataPools** [comment]
I'm using a setup close to this. I have my own domain and have email setup to use google apps. I've turned off the php mail setting in the AdminCP.  I registered another account to test whether email verification would work, I get this error:
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting]

I'm currently using smtp.gmail.com

**Comment by samerton** [comment]
@DataPools I've recently experienced a similar issue with Gmail, I think it might be due to changes in Gmail security. 

Can you try the following:

- Open https://accounts.google.com/DisplayUnlockCaptcha and click "Continue"
- Open https://myaccount.google.com/security#connectedapps and enable "Allow less secure apps" near the bottom of the page

Wait about 30 seconds and then try registering an account on your site, hopefully the email will send and you won't have to perform these steps again.

If it still doesn't work, unfortunately I can only recommend using a different email provider such as [Zoho](https://www.zoho.com/mail/)(who have a free package available).
