### ISSUE TITLE
Disable Minecraft Username

### ISSUE THREAD

**Issue by TheAppleGamer** [NamelessMC/Nameless#350]
**What kind of issue is it (Question, Bug, etc.)?** Question
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.10
How do I disable where it checks your Minecraft account? I have people who don't have Minecraft accounts but want to use my forums, and they can't login.

**Comment by samerton** [comment]
Disabling UUID linking (AdminCP -> Minecraft) should achieve this.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any further questions feel free to re-open.
