### ISSUE TITLE
Sitemap XMLWriter Not Found

### ISSUE THREAD

**Issue by SrStellar** [NamelessMC/Nameless#3507]
### Describe the issue

Even though I have php-xml installed and activated in php.ini I can't generate the sitemap in my namelessmc.

### NamelessMC Version

2.1.2

### To Reproduce

1. Go to Configuration -> SEO on Admin Panel.
2. Click on 'Generate Sitemap'.
3. That's it.

### Expected Behaviour

I was specting to generate the site map of my instace of namelessmc to set on google search console.

### Screenshots

![image](https://github.com/NamelessMC/Nameless/assets/73672850/08729cdf-8165-4b71-9d19-e04cf64926f1)

### Additional Information

https://debug.namelessmc.com/S12SxFAZaubXOD3b

**Comment by samerton** [comment]
It looks like you are missing the php-xml extension. How are you hosting the website?

**Comment by SrStellar** [comment]
I'm hosting it on my pterodactyl panel, with an nginx egg. But on my main terminal its all installed, and on the staff panel its showing the xml its installed

**Comment by SrStellar** [comment]
i'm using namelessmc 2.1.2, but when i created this issue i cant select it, it show just the 2.1.0 version.

**Comment by samerton** [comment]
Unfortunately we do not officially support running Nameless within Ptero eggs as there tend to be many issues when doing so.

If you are running Ptero on your own VPS/dedicated server, I recommend running Nameless alongside Ptero as a second virtual host.
