### ISSUE TITLE
Online Users 

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#351]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10

Hello ! I am trying to create something like this 

<img src="http://image.prntscr.com/image/63651d178f7a437dadb0273e2a3d25c8.png">

Can someone help me?

**Comment by zTryhqrd** [comment]
I think you can do this pretty easy, if you have experience with some PHP and HTML. When you go to the Forum tab, you see that already "Online Users", so you can just change that to the Cravatar.eu images.

**Comment by Ariuw** [comment]
I know how to use HTML but not PHP I have already get the image working but not the avatar of the player it means that the image doesn't show the online user avatar, I don't know how to get that working :cry:

**Comment by samerton** [comment]
If you're referring to the online users list within the forums, you can change

`$online_users_string .= '<a href="/profile/' . htmlspecialchars($online_user->mcname) . '">' . htmlspecialchars($online_user->username) . '</a>, ';`

to

`$online_users_string .= '<a href="/profile/' . htmlspecialchars($online_user->mcname) . '"><img src="http://cravatar.eu/avatar/' . htmlspecialchars($online_user->mcname) . '/50.png" alt="' . htmlspecialchars($online_user->mcname) . '" /> </a>, ';`

It's untested, but it should work.

**Comment by Ariuw** [comment]
Yesss!!! It worksss thanks @Samerton !!
