### ISSUE TITLE
PHP Clean Page

### ISSUE THREAD

**Issue by zTryhqrd** [NamelessMC/Nameless#352]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10

I am busy with creating a clean page, so not with the "Pages" tab, implemented in NamelessMC, cause I need to use my own PermissionsEx rank system in the page, but I am trying to get the navbar included but this already gives me a 500 error:
http://hastebin.com/aluxenojux.php

So what files do I need to include to make everything working, so that the navbar is working aswell.. I can't even include a navbar.. :disappointed:

**Comment by samerton** [comment]
There is an example custom page [here](https://gist.githubusercontent.com/samerton/596515f5d0d2b132820c3d2dbaa51f52/raw/446119edb37e913ffd5da2ddfbc7d0667aefe8b8/custom_page.php), I haven't actually tested it but that should help.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any further questions please feel free to re-open.
