### ISSUE TITLE
Picture on the whole page

### ISSUE THREAD

**Issue by zikyales** [NamelessMC/Nameless#353]
Hello, how do I do to have the image on the entire page : http://minicraft.cz/

  Application: translator

**Comment by Ariuw** [comment]
Yes he means the background

**Comment by IsS127** [comment]
Checked his Page and looks like he has done it.

**Comment by samerton** [comment]
I'm not too sure which image you're referring to, as @IsS127 says it appears there is already a background image on the entire page.

**Comment by partydragen** [comment]
Wow i think this is the biggest network who using NamelessMC

**Comment by Ariuw** [comment]
Nono! That's not his webpage it is just an example he want it for his own network (I am not sure anyways)

**Comment by partydragen** [comment]
I wonder about that too how we fix about the background fill the whole screen and its frozen or what i should call it

**Comment by partydragen** [comment]
body { 
     background-image: url('http://cubedcraft.com/background.png');
     background-repeat: no-repeat;
     background-attachment: fixed;
	 background-size: cover;
 }

**Comment by samerton** [comment]
Just as I'm writing up a reply, @partydragen beats me to it.

The code in the previous reply needs pasting into **styles/themes/*Your Theme*/css/custom.css**, and if you don't notice any changes try forcing a refresh in your browser (Ctrl-F5 whilst viewing your website).

**Comment by zikyales** [comment]
Hello, I do not know how I do it, I do not

I am from the Czech Republic and used for translation: translator 

http://www.uschovna.cz/zasilka/KDXWRTMI8SUY5TYB-PA4/GLU8C648TH

**Comment by IsS127** [comment]
@zikyales done 
https://www.dropbox.com/s/jhtz3qgbcvvebnr/custom.css?dl=0

**Comment by zikyales** [comment]
Thank you very much, even though I use the compiler hope you understand it a little bit

**Comment by IsS127** [comment]
I didnt understand What u ment there but no problem :) check out the Link i gave u to fix a few background issues

**Comment by samerton** [comment]
I'll mark this as closed as the steps and CSS in @partydragen's reply will add a custom background. If you still have any questions please feel free to reopen.
