### ISSUE TITLE
$_GET Parameters

### ISSUE THREAD

**Issue by zTryhqrd** [NamelessMC/Nameless#354]
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10

Hello @samerton,
Can you maybe explain to me how I can use $_GET functions to my custom page (/pages), because when I go to https://example.com/test.php?test=test, it will redirect me to the index page.
Do you know how I can fix this?

Thank you.

**Comment by samerton** [comment]
If it's a custom PHP file within the pages directory, you can simply use http://example.com/test/?test=test

**Comment by zTryhqrd** [comment]
Oh thanks I see, thank you very much!
