### ISSUE TITLE
"Lasted Edited"

### ISSUE THREAD

**Issue by xBreaksx** [NamelessMC/Nameless#355]
* What kind of issue is it (Question, Bug, etc.)? Suggestion
* In which version of NamelessMC did it occur (1.x.x)? N/A
* How would you describe the issue? Asking for a "last edited by <time>" on posts.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? N/A
* Do you have an idea how or where the issue occurs? On posts posted by posters.

**Comment by Liphius** [comment]
I'd love to see this feature. Would be extremely useful as I use the forums a lot.

**Comment by samerton** [comment]
Implemented in version 2.0 development
