### ISSUE TITLE
Cant connect to the database during setup

### ISSUE THREAD

**Issue by Scralar** [NamelessMC/Nameless#3550]
### Describe the issue

Ive entered all the details correctly using the right passwords etc, but I keep getting this error message. Ive removed the username and address from the error message for security reasons but you should be able to get the idea

![image](https://github.com/user-attachments/assets/b8fcbbc7-e17f-47b3-8def-c63e56382b9e)

For context, I've contacted the website service provider (pebblehost) twice for help and both times they have pointed me to ask nameless for help as its "an issue on their end". I don't believe this to be the case as it appears to be pebblehost's cPanel SQL database that is denying me access but I want to know if you guys have any thoughts.

### NamelessMC Version

2.1.0

**Comment by PadowYT2** [comment]
This is not a bug, rather a user issue. Next time, please use the [Discord Server](https://discord.gg/nameless) to get support

![https://cdn.padow.ru/31Jp1](https://cdn.padow.ru/31Jp1)

**Comment by Scralar** [comment]
Ive gone through the discord server now, feel free to close this
