### ISSUE TITLE
Real timr group sync

### ISSUE THREAD

**Issue by webdevkinsuk** [NamelessMC/Nameless#3551]
### Describe the feature

like you could set a intervel within it check for user with group if the user got that role in dc or site or minecraft before he linked his acc with nameless mc
it will check every 2m - 3 m -5m -10m -30m - 1h that does that uset have this role in dc site or nameless if yes imagine the user has role in dc it will assine to mc and site then

**Comment by webdevkinsuk** [comment]
another ontop it there 2 more button in groups if bot linked
copy role from dc
copy role and & permission from DC

**Comment by Derkades** [comment]
The current group sync is already real-time, can you explain in more detail what you are missing from the current system?
