### ISSUE TITLE
OAuth2 Identity Server 

### ISSUE THREAD

**Issue by burdoto** [NamelessMC/Nameless#3552]
### Describe the feature

It would be great to have NamelessMC serve as an OAuth2 Server, to allow users (and most importantly, staff) to log in to internal apps (such as YouTrack, or similar) with their NamelessMC account, without having to manually configure their staff role every time.

**Comment by samerton** [comment]
Hi, there is an unofficial module which might achieve this? https://namelessmc.com/resources/resource/202-oauth2-module/

**Comment by burdoto** [comment]
oh, this seems to be just what i was looking for. thanks a lot for the heads up, i must have missed that!
