### ISSUE TITLE
White Screen before install [OVH]

### ISSUE THREAD

**Issue by Ksewedo5** [NamelessMC/Nameless#3556]
### Describe the issue

The application does not work at all on OVH hosting (PHP version 8.1). I tried to fix it on my own, including changing the permissions of the main directory via FTP to 777, but it had no effect. The hosting does not provide SSH access.

Only a white screen is displayed, and upon inspecting the page source, there is only an empty Head and Body section.

Translated by ChatGPT.

https://helldeen.net/info.php

### NamelessMC Version

Development version

### To Reproduce

Unpack to server :D

**Comment by samerton** [comment]
Hi, I can see a 500 error on your site - do you have any web server logs available in the web host control panel?

**Comment by samerton** [comment]
Thanks - I have removed the comment to hide the details

I will have a look now @Ksewedo5

**Comment by Ksewedo5** [comment]
You can still calmly enjoy your coffee hahaha :)) I’ve disabled CloudFlare protection and ordered an SSL certificate on the OVH side to avoid potential errors.

**Comment by samerton** [comment]
Unfortunately the error logs do not appear to be showing anything.

You can try enabling debugging within Nameless, by removing `//` from the start of line 13 within index.php, to see if that changes anything: https://github.com/NamelessMC/Nameless/blob/v2.1.2/index.php#L13

**Comment by Ksewedo5** [comment]
Okay, I enabled debugging... errors related to autoload_real.php have appeared.

**Comment by samerton** [comment]
Can you please share the full error message here?

**Comment by Ksewedo5** [comment]
Warning: require(/home/helldez/www/vendor/composer/../symfony/deprecation-contracts/function.php): Failed to open stream: No such file or directory in /home/helldez/www/vendor/composer/autoload_real.php on line 41

Warning: require(/home/helldez/www/vendor/composer/../symfony/deprecation-contracts/function.php): Failed to open stream: No such file or directory in /home/helldez/www/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/home/helldez/www/vendor/composer/../symfony/deprecation-contracts/function.php' (include_path='.:/usr/local/php8.1/lib/php') in /home/helldez/www/vendor/composer/autoload_real.php:41 Stack trace: #0 /home/helldez/www/vendor/composer/autoload_real.php(45): {closure}('6e3fae29631ef28...', '/home/helldez/w...') #1 /home/helldez/www/vendor/autoload.php(25): ComposerAutoloaderInit231053af99fcb6f7412fa29114da6709::getLoader() #2 /home/helldez/www/index.php(48): require_once('/home/helldez/w...') #3 {main} thrown in /home/helldez/www/vendor/composer/autoload_real.php on line 41 @samerton

**Comment by samerton** [comment]
It looks like you have some missing files.

You mention in your report that you are using the development version - is this definitely the case? Public websites should be using the files available from the latest release (currently https://github.com/NamelessMC/Nameless/releases/tag/v2.1.2)

You should use the "nameless-deps-dist" files as these include all dependencies ready to go.

If you are already using this, can you try reuploading the "vendor" folder onto your web host as this is where the files are missing from.

**Comment by Ksewedo5** [comment]
I’m really sorry for the trouble! It seems this was actually my mistake, and not all the files made it to the server. I’m halfway through uploading the files now… and the installer is already appearing :)) I sent a small donation via GitHub :D enough for a coffee, hahaha :))

Translated by ChatGPT.

**Comment by samerton** [comment]
Glad to hear the problem appears resolved - and thank you for the donation! If you have any more questions, please feel free to ask.
