### ISSUE TITLE
PHP Output number of friends, "Add friend" & "Remove friend" button + output who are friends.

### ISSUE THREAD

**Issue by zTryhqrd** [NamelessMC/Nameless#356]
- What kind of issue is it (Question, Bug, etc.)? Question
- In which version of NamelessMC did it occur (1.x.x)? 1.0.10

Hi @samerton,
I have another question :stuck_out_tongue_closed_eyes: 
I am currently busy with my own profile page, but I need to echo the number of friends that a player has and also what friends he has.
Example: https://i.gyazo.com/38796296e8efd317b896e5469b7fd59c.png

**-** But I do not know what files I need to include and what code I need to use to output the "Add Friend" button and the "Remove Friend" button and the number of friends and ofcourse what players are friends with him.

Can you please help me?

**Comment by samerton** [comment]
Is your custom page within the **pages** directory?

If so, you can use the following functions:

- `$user->addfriend($user->data()->id, $other_user_id)` to add friends
- `$user->removefriend($user->data()->id, $other_user_id)` to remove friends, 
- `$user->listFriends($user_id)` to obtain an array containing IDs of the $user_id's friends
- `$user->isfriend($user1, $user2)` to see if $user1 is friends with $user2

If your page isn't within the **pages** directory, you'll need to query the "nl1_friends" table to obtain the information from there.

**Comment by zTryhqrd** [comment]
Hey dude,
Thanks bro that you help me so much!
Can you maybe give me an example code how to use all that stuff? Like the add and remove friend button and an output of friends with head images and friend counter etc. :D

**Comment by zTryhqrd** [comment]
And if I make a profile.php in *pages/*, I can use https://example.com/profile/test

But what $_GET['??'] do I have to use if I want to use the parameters after the /profile/

So I can use /profile/Samerton, what $_GET is that?

**Comment by samerton** [comment]
It might be a bit more beneficial to see the code in action, lines [451-475](https://github.com/NamelessMC/Nameless/blob/master/pages/profile.php#L451) of pages/profile.php will check to see if the logged in user is a friend of the profile user, and will display a form (this is required to prevent spam clicking) containing an add or remove friend button. 
[Lines 78-87](https://github.com/NamelessMC/Nameless/blob/master/pages/profile.php#L78) will actually add or remove the user as a friend.

[Lines 388-411](https://github.com/NamelessMC/Nameless/blob/master/pages/profile.php#L388) will display a list of friends, and you can count the number of items in the array to display the number.

As for the URL username parameter, this is done by the **index.php** file within the root directory, if you take a look at [lines 83-89](https://github.com/NamelessMC/Nameless/blob/master/index.php#L83) you can modify that code to your liking (the $profile variable will contain the username).

**Comment by zTryhqrd** [comment]
Yea I know that it shows the 'profile' things from 83-89..
But this is only working:
https://www.example.com/profile/?username=zTryhqrd

It doesnt work if I try: https://www.example.com/profile/zTryhqrd

**Comment by zTryhqrd** [comment]
@samerton, please check your e-mail, I wrote it a little bit better there.

**Comment by zTryhqrd** [comment]
Hey dude,
I think you understood me wrong on GitHub, becuase you said that you can change the 'profile' thing to like http://example.com/user/ but that's not where I was looking for.
The problem is, when I make a custom profile page, it is not reachable by https://www.example.com/profile/Name
Because I am using $_GET["username"] so my custom profile is only reachable with the following link: https://example.com/profile/?username=zTryhqrd, so do you know how I can fix that?
That I can use http://example.com/profile/Name for my $_GET["username"]

I hope you understand me :)

Regards,
zTryhqrd

**Comment by samerton** [comment]
@zTryhqrd 
Try using the **$profile** variable instead of $_GET['username']

**Comment by zTryhqrd** [comment]
Now it is kinda working, the navbar works but the rest is a white page xD

https://shadowhcf.com/profile/zTryhqrd

See

**Comment by zTryhqrd** [comment]
Okay, it's working but I have the friends problem now, because if you take a look at https://shadowhcf.com/profile/zTryhqrd , it'll show a "Friends" list (https://i.gyazo.com/f1d07d43912699e502bafadba02b684e.png), but this is actually just HTML, I have no idea how to implement the friend stuff to my custom profile script, here is my custom profile script: http://hastebin.com/nemayipiwa.php (the code)

Because I want to add a friend list with the heads and a little friendcounter and a "Add Friend" & "Remove Friend" button aswell ;/ 

Do you know what kinda scripts I need to include or what I have to do.. I have no idea how to implement the friends to my php script.

**Comment by zTryhqrd** [comment]
Hello?

**Comment by WASasquatch** [comment]
Seems like you need a id2username. And username2id function for the dynamic
content.

**Comment by zTryhqrd** [comment]
@WASasquatch Don't understand your comment.
@samerton =

Okay, it's working but I have the friends problem now, because if you take a look at https://shadowhcf.com/profile/zTryhqrd , it'll show a "Friends" list (https://i.gyazo.com/f1d07d43912699e502bafadba02b684e.png), but this is actually just HTML, I have no idea how to implement the friend stuff to my custom profile script, here is my custom profile script: http://hastebin.com/nemayipiwa.php (the code)

Because I want to add a friend list with the heads and a little friendcounter and a "Add Friend" & "Remove Friend" button aswell ;/

Do you know what kinda scripts I need to include or what I have to do.. I have no idea how to implement the friends to my php script.

**Comment by samerton** [comment]
To list users, simply use the `$user->listFriends($user_id)` function to obtain a list of friends for the user (with id $user_id).

Example usage is as follows:

$friends = $user->listFriends($user_id);

foreach($friends as $friend){
  echo '<span rel="tooltip" title="' . htmlspecialchars($user->IdToName($friend->friend_id)) . '"><a href="/profile/' . htmlspecialchars($user->IdToMCName($friend->friend_id)) . '"><img class="img-rounded" style="padding-bottom:2.5px;" src="https://cravatar.eu/avatar/' . htmlspecialchars($user->IdToMCName($friend->friend_id)) . '/40.png" /></a></span>&nbsp;';
}

(pretty much taken straight from the default profile.php).

Hope that helps.

**Comment by zTryhqrd** [comment]
Thanks dude, that's helped alot, last question: what files do I need to include at the top of my custom php page to make all the friends stuff working?

**Comment by WASasquatch** [comment]
I'm assuming you would need to create your own action page, or integrate it in your custom page.

    <?php

	require_once('core/integration/uuid.php');

	if($user->isLoggedIn()){
	
		require('core/includes/htmlpurifier/HTMLPurifier.standalone.php');

		if(!isset($_POST['action'])){
			if(isset($_POST['AddFriend'])) {
				if(Token::check(Input::get('token'))){
					$user->addfriend($user->data()->id, $profile_user[0]->id);
					header('location: '.$_SERVER['HTTP_REFERER']);
				}
			}
			if(isset($_POST['RemoveFriend'])){
				if(Token::check(Input::get('token'))){
					$user->removefriend($user->data()->id, $profile_user[0]->id);
					header('location: '.$_SERVER['HTTP_REFERER']);
				}
			}
		} else {
			header('location: '.$_SERVER['HTTP_REFERER']);
		}
		
    ?>

**Comment by samerton** [comment]
To use the functions included with Nameless you need to have your custom PHP file within the **pages** directory, and it will load everything automatically.

**Comment by zTryhqrd** [comment]
My whole friend system is weird right now, I'll send you a hastebin and you can check it.
It kinda begins at line 589..

http://hastebin.com/rulapigode.php

But `<?php if(!$exists || $friends == false) echo '0'; else echo count($friends); ?>` returns at '0' because it doesn't know any user to check it from, because I added 1 friend, and it still counts as 0.
So I think that the system don't recognize a user or it doesnt know from what user to check.

Please check it for me from my hastebin.

**Comment by samerton** [comment]
Sorry for the late reply.

I've taken a look, and you simply need to add the following anywhere before your friends section :

`<?php`
`// Get friends`
`$friends = $user->listFriends($profile_user[0]->id);`
`?>`

You'll also need to replace `<?php if(!$exists || $friends == false) echo '0'; else echo count($friends); ?>` with `<?php if($friends == false) echo '0'; else echo count($friends); ?>`.

Hope that helps.

**Comment by zTryhqrd** [comment]
Doesn't work.. ;/ Still returns at '0'

**Comment by samerton** [comment]
Apologies for not being able to discover what the issue was, please feel free to re-open this if you're still looking for help on this.
