### ISSUE TITLE
Two Factor Authentication Login Page Messed Up

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#357]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? The Two Factor Authentication login page looks messed up..
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
![image](https://cloud.githubusercontent.com/assets/8834158/17137012/eab80e94-5338-11e6-869a-40ef845c2cd3.png)

* Do you have an idea how or where the issue occurs? No idea.

**Comment by samerton** [comment]
Apart from the "Message Sent" text, this is intentional appearance.

I've removed the "Message Sent" text in 529b376d385c0c0aa735e4f4744186746a631405, which will be included in 1.0.11.

**Comment by IsS127** [comment]
Well it would be a bit beautiful if it includes the nav and all that :) i would do that.. but im not really good at php only html and css

**Comment by samerton** [comment]
The reason the navbar isn't displayed is that the user is intended to complete that step before continuing, so navigating to other pages is disabled.

As for the message sent being removed, the text within the box ("We have sent you a code within an email for verification..") will remain, it's just the small message above which has been removed as it shouldn't be there.

**Comment by IsS127** [comment]
Oh ok, but what i meant was.. in that area where u need to type ur code, add a box like the ("We have sent you a code within an email for verification..") but replace it with (''Code Has Been Sent!'')

**Comment by zTryhqrd** [comment]
Just change it if you want, how hard is it to find the text in the code..

**Comment by IsS127** [comment]
I am gonna do that, just giving him suggestions..

**Comment by samerton** [comment]
Thanks for the suggestions, however for the time being I don't think the two factor authentication page will be modified. If you have any other questions/issues feel free to reopen.
