### ISSUE TITLE
line ur CSS Code  [TIPS]

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#358]
Ever wanting to change you're CSS code? but theres only 1 line.. Then use this tool.. it helped me aloott!!
http://www.cleancss.com/css-beautify/

**Comment by samerton** [comment]
Thanks for the link, the reason the themes included within Nameless are all on one line is because it actually reduces the page loading time, and as a result this won't be changed.

I'll close this issue, maybe this is better suited to the [forums](https://namelessmc.com/) ;)
