### ISSUE TITLE
view_forum_table.tpl is missing  a well

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#359]
view_forum_table.tpl is missing  a well thing i tryed to add but not working :/

  <div class="well">

So since i using background now its no well on background
http://cubedcraft.com/forum/view_forum/?fid=2

**Comment by IsS127** [comment]
[Off topic] You should blur ur background image :)

**Comment by IsS127** [comment]
Oh wait i think we have the same issue, does it look like this? https://github.com/NamelessMC/Nameless/issues/364

**Comment by partydragen** [comment]
yea :P

**Comment by IsS127** [comment]
I have nooo idea how to fix that..

**Comment by samerton** [comment]
@partydragen @IsS127 
For pages where a template is present, you can modify it (such as in this case, view_forum_table.tpl), however on pages such as the Infractions page I'll have to add one by default until that's also template based.
The Bootstrap component you need to add is `<div class="well">...</div>` around the page content.

**Comment by IsS127** [comment]
@samerton I have fixed infractions and the forums but i saw another thing.. its kinda been bothering me.. The profile Page.. i tried to fix it, then it looked like this.. the about posts and that was messed up
![image](https://cloud.githubusercontent.com/assets/8834158/17174004/809baad6-53fe-11e6-955d-a3d77c59a139.png)
![image](https://cloud.githubusercontent.com/assets/8834158/17174016/990f3178-53fe-11e6-8caa-bd859e4a41fb.png)
Officialy it looks like this
![image](https://cloud.githubusercontent.com/assets/8834158/17174037/bf576fb2-53fe-11e6-8198-bc5b78d61a15.png)
And if i change the color to white of the texts the forums are white soo they wont see text..
What should i do?

**Comment by samerton** [comment]
74b11e7c94dda716aa560afde6be8f8a10a156e7 adds a well to the infractions page, I'll mark this as closed as template files should be used for other pages. If you notice any non-template pages which are missing a well, feel free to reopen.
