### ISSUE TITLE
Cannot Disable Two Factor Authentication

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#360]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10
* How would you describe the issue? The Two Factor Authentication wont disable when im in usercp im clicking the disable and submitting it wont work
* Do you have an idea how or where the issue occurs? Nope..

[Question] Whats the Two Factor Authentication app?

**Comment by Fiiily** [comment]
To answer your question, here's a link to the Google 2FA help page. [https://support.google.com/accounts/answer/1066447?hl=en](Link)

**Comment by samerton** [comment]
I can't reproduce any issues, the Disable button works without issue for me.
It might be quite confusing, with the "Enable Two Factor Authentication" option too, but it's the "Disable" button which you want.

**Comment by IsS127** [comment]
This is so funny.. i didnt see that xD
