### ISSUE TITLE
Custom Background issues

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#364]
So i uploaded and edited my custom theme.. also got a custom background so if u got to the infractions or click on forums then u see topics.. there are white lines with no background.. How can i add the backgrounds tried to check code but i have no knowledge of php only html, css. Here are some pics 
![image](https://cloud.githubusercontent.com/assets/8834158/17156403/f8f493c8-5389-11e6-8186-0f4765b2627a.png) 
![image](https://cloud.githubusercontent.com/assets/8834158/17156409/fe217514-5389-11e6-85d2-6658833794d0.png)

**Comment by Fiiily** [comment]
Appears to be resolved by the issue opener.

**Comment by IsS127** [comment]
Resolved? not solved for me.. if you saw the referenced thing, we have the same issue

**Comment by samerton** [comment]
Thanks for the report, if we use #359 for discussion on this it might make things a bit easier so I'll close this for now.
