### ISSUE TITLE
Thumbnail Photo Change every 10 secs? 

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#365]
Hello, im not good with scripts like photos changing every 10 secs.. 
So can anyone help me making the thumbnail in the main page change every 10 secs?

**Comment by IsS127** [comment]
Anyone?

**Comment by IsS127** [comment]
Hello??

**Comment by samerton** [comment]
The [Bootstrap carousel](http://getbootstrap.com/javascript/#carousel) element should help you out.

**Comment by IsS127** [comment]
And where should i put the js? and where to include theese stuff? in tpl or index.php?

**Comment by samerton** [comment]
You can try placing it into the index.tpl (within your template folder).

**Comment by IsS127** [comment]
Cant really figure out how to change images..

**Comment by samerton** [comment]
The carousel method from the above link is the only method within Nameless I'm afraid.
Try pasting the Javascript onto line 254 of **pages/index.php** (after `?>` but before `</body>`).

**Comment by IsS127** [comment]
it still worked without pasting the javascript and i fixed the photos but the page layout messed up..

**Comment by samerton** [comment]
Can I have a link to your site?

**Comment by IsS127** [comment]
ive done 1 image for testing but the rest 3 havent done yet
https://www.ispiracraft.com/

**Comment by samerton** [comment]
You have an extra `</div>` which is closing the `<div class="container">` , try removing the `</div>` directly after 

`<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">`
  `<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>`
  `<span class="sr-only">Next</span>`
`</a>`

**Comment by IsS127** [comment]
Ty! any way i can do diff server $PLAYERS_ONLINE?? it shows the whole network.. if there was any way to show the other servers to?

**Comment by IsS127** [comment]
And any way to set size?

**Comment by IsS127** [comment]
Bump..

**Comment by samerton** [comment]
There isn't a way to choose which server's player count is displayed at the moment unfortunately. This is planned functionality for a future release, probably closer to the version 2.0 release.

**Comment by IsS127** [comment]
Ok, is there any php code i can add in index.php or tpl?

**Comment by samerton** [comment]
Unfortunately I can't provide you with code to do this, as querying each server at once would increase the page loading time a lot. I'll try and see if I can get this done a bit sooner than 2.0.

**Comment by IsS127** [comment]
Ok :)
