### ISSUE TITLE
New reply system

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#366]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.10

Hello. this question is about the reply (forum_create_post) that we are using... is there a way to change it? because it doesn't look good IMO should be better to move to a new one, can we do this? if so how?

**Comment by IsS127** [comment]
Do you mean how it looks like, or how it works?

**Comment by samerton** [comment]
Is there anything you'd like to see in particular?

**Comment by Ariuw** [comment]
Yeah @samerton is to remove that comment from the user <img src="http://image.prntscr.com/image/5a2f4af791d5488aba508fb5a89e9db3.png"> but add something to know that it is a reply and not that big thing because when you do a lot of replies it gets bigger and more bigger (I hope you know what I mean)

**Comment by Ariuw** [comment]
So.. is this possible?

**Comment by Ariuw** [comment]
Bump (:

**Comment by samerton** [comment]
I can look into this for a future release, thanks for the suggestion.

**Comment by MuhsinunCool** [comment]
@Ariuw do u mean like reddit style? Cuz if so, ig some ppl might want that but I personally like the normal kind like Xenforo style and if we have both maybe we can have an option to choose between the two reply designs @samerton?

**Comment by samerton** [comment]
I've improved the reply system for version 2.0, including removing quotes from inside quotes, as well as allowing for multiple quotes in one post.
