### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zikyales** [NamelessMC/Nameless#368]
Help : Error:
SQLSTATE[28000] [1045] Access denied for user 'u500224313_netsw'@'10.2.1.9' (using password: YES)
Please check your database connection settings.

**Comment by samerton** [comment]
Unfortunately I can't really suggest anything other than double checking your database details, and trying again.
A possible cause could be that, if your MySQL database is on a different IP to your website, MySQL remote hosts are disabled. Try searching for steps on how to allow remote access to your database.

**Comment by samerton** [comment]
Accidentally closed, apologies.

**Comment by samerton** [comment]
Were you able to get around your issue? I don't believe this is an issue with Nameless itself.

**Comment by samerton** [comment]
I'll mark this as closed as I don't think this is a Nameless issue, rather an issue with MySQL or the connection details used. Feel free to reopen if you're still experiencing issues.
