### ISSUE TITLE
[Bug] Donate Descriptions aren't updating

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#37]
When you sync with the donor store new things are getting added etc but the descriptions from items aren't getting updated.

**Comment by samerton** [comment]
Are you using Buycraft or MinecraftMarket?

**Comment by HappyHarm** [comment]
MinecraftMarket

**Comment by samerton** [comment]
This is an issue with the MinecraftMarket API itself, it won't return package descriptions so unfortunately it's not possible to display them on the integrated display page.
