### ISSUE TITLE
I banned Mehself

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#370]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Issue
* In which version of NamelessMC did it occur (1.x.x)? Irrelevant
* How would you describe the issue?  Horrifying! I banned myself from the webpage.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Nope
* Do you have an idea how or where the issue occurs? I go to the ModCP and ban myself.

Please prevent punishing the staff group Unless you're in the AdminCP but also don't let the Superuser be banned.

**Comment by Schwertspize** [comment]
Well that's a report but as hotfix go in the sql database and delete the ban.

**Comment by samerton** [comment]
I'll improve the punishments system in a future update, for now the root user can't be banned.
