### ISSUE TITLE
BuyCraft Synchronization not working

### ISSUE THREAD

**Issue by higoogle1234** [NamelessMC/Nameless#371]
**What kind of issue is it (Question, Bug, etc.)?** Question  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.10
**How would you describe the issue?** Every time I try synchronizing BuyCraft with the Donate page, it doesn't load any of the packages or recent donators, only the categories. I checked the database and nl1_donation_packages and nl1_donation_cache is empty. When I try clicking the auto synchronization link I get a long error (below). 
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'description' at row 1' in /home/furiousp/public_html/core/classes/DB.php:68 Stack trace: #0 /home/furiousp/public_html/core/classes/DB.php(68): PDOStatement->execute() #1 /home/furiousp/public_html/core/classes/DB.php(167): DB->createQuery('INSERT INTO nl1...', Array) #2 /home/furiousp/public_html/core/classes/Queries.php(42): DB->insert('donation_packag...', Array) #3 /home/furiousp/public_html/addons/Donate/sync.php(92): Queries->create('donation_packag...', Array) #4 {main} thrown in /home/furiousp/public_html/core/classes/DB.php on line 68  
**Do you have an idea how or where the issue occurs?** I'm not too sure.

**Comment by samerton** [comment]
There's currently a 2048 character limit on package descriptions for Nameless, this includes any HTML tags and entities. I'll change this for the 1.0.11 release.

**Comment by IsS127** [comment]
Same happend with me, i really need this.. when is 1.0.11 out?

**Comment by IsS127** [comment]
Any way i can change this manually?

**Comment by Liphius** [comment]
I'd recommend using an iframe for a custom page named 'shop' or something similar in the meantime, just like I have it set-up;

http://oxencraft.net/shop/

**Comment by IsS127** [comment]
True true but i kinda want to use This option. If i do a iframe does it
bring the ads?

**Comment by samerton** [comment]
To make the change manually, you'll need to modify the `description` column in the `nl1_donation_packages` table, using something like phpMyAdmin, so that its type changes from `varchar(2048)` to `MEDIUMTEXT`

**Comment by IsS127** [comment]
ok will do that rn

**Comment by IsS127** [comment]
Done, but it still wont show the packages or the recent donors.

**Comment by samerton** [comment]
There must be another issue somewhere, we'll need further errors to diagnose this.

**Comment by IsS127** [comment]
Where do i find the logs?

**Comment by samerton** [comment]
This depends on your setup, including OS and whether you're using cPanel.
It might be worth first enabling error reporting (AdminCP -> Misc) and then heading straight to the URL shown on **yoursite.com/admin/addons/?action=edit&addon=Donate&do=sync**

**Comment by IsS127** [comment]
ok done, i got no errors only this
Notice: Undefined offset: 2 in /home/user/public_html/core/includes/template/navbar.php on line 52

Notice: Undefined offset: 2 in /home/user/public_html/core/includes/template/navbar.php on line 52
when i look at line i see this
	if(isset($page) && $page == $item[2]){

**Comment by samerton** [comment]
Those errors won't appear on the page I'm referring to, the URL you need to load is that shown on the link in my previous reply, it should be something along the lines of **yoursite.com/addons/Donate/sync.php?key=...**.

**Comment by IsS127** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'package' cannot be null

**Comment by IsS127** [comment]
PS still not fixed in 1.0.11

**Comment by samerton** [comment]
Should hopefully be fixed in https://github.com/NamelessMC/Nameless/commit/b6c3ce46fbb84f37df74f5ff1d31522aa7ba6ffb
