### ISSUE TITLE
[Bug]Twitter Widget Integration

### ISSUE THREAD

**Issue by godleydemon** [NamelessMC/Nameless#373]
Looks like recently twitter changed there widget features and no longer gives out a widget ID. Work around could possible just use there embed coding that they force you to use. But for now, any future widget creation won't work with the current methods.

Previous work arounds was looking at the twitter widget url and getting it from there. But that's no longer a viable option it seems.

**Comment by godleydemon** [comment]
was able to solve this temporarily by adding a new line at line 197 with hard coded information


`		$twitter = '<a class="twitter-timeline" data-height="600" href="https://twitter.com/username">Tweets</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>';`


This shows the twitter feed as intended :) still need a fix admin side though.

**Comment by godleydemon** [comment]
Sorry I was extremely tired when I wrote that comment. Temp fix is to open index.php in pages and replace line 194 with
`$twitter = '<a class="twitter-timeline" data-height="600" href="' . htmlspecialchars($twitter_url[0]->value) . '">Tweets</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>';`

we can still use the variable from the admin panel to display the twitter feed. So now we can just change the twitter url in admin panel to display the correct corresponding twitter widget.

**Comment by samerton** [comment]
Thanks for the pull request, merged in 11a3be771d08663e86642aceed754adcfa4f5ddd
