### ISSUE TITLE
Email system glitches?

### ISSUE THREAD

**Issue by fenix12585** [NamelessMC/Nameless#38]
Hello,

I am loving nameless so far, only now I am having some issues with the email system.

First, phpmail will not send to gmail or zoho for some reason. Do you know of why this could be? I have not tried any others, although it does work for my dev, through his free domain email account.

Second, i tried to use smpt, i changed the settings in my email.php to mirror my normal email account with no luck. When i do a new account signup or password recovery email, i get a plain white page that says "Mailer Error: Message body empty"

Thank you in advance for any help you can provide

**Comment by samerton** [comment]
I've only seen a couple of cases of this before ([such as here](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-74#post-1067577)), however a solution hasn't yet been reached. 

I've just pushed a commit (5da763e3cc108fd301ff87040038e3bf9b561269), could you try and apply these changes?

**pages/register.php** will need replacing with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/5da763e3cc108fd301ff87040038e3bf9b561269/pages/register.php),
**pages/forgot_password.php** will need replacing with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/5da763e3cc108fd301ff87040038e3bf9b561269/pages/forgot_password.php),
**pages/admin/reset_password.php** will need replacing with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/5da763e3cc108fd301ff87040038e3bf9b561269/pages/admin/reset_password.php).

Hopefully that helps.

**Comment by Nefortix** [comment]
You should be using Body instead of AltBody for PHPMailer in my opinion.

**Comment by samerton** [comment]
I've commented out the AltBody lines for now.

I still can't think why the issue would happen for some people and not for others, as I can't reproduce the issue myself I'm struggling to diagnose it.

**Comment by Nefortix** [comment]
It's kinda strange. Which SMTP provider do you use for testing?

**Comment by samerton** [comment]
I've only used Gmail for my PHPMailer tests, I don't have an SMTP server available to use.

**Comment by Faicu** [comment]
I have this problem, can I disable this verification? Just click register and done, account created, I don't need link/email verification. How can I do this? please guide me :D

**Comment by samerton** [comment]
@Faicu I'll work on an option to disable email verification for an upcoming release (#65)

**Comment by samerton** [comment]
Hopefully fixed this issue (#64), will include the fix in 1.0.3
