### ISSUE TITLE
Theme error

### ISSUE THREAD

**Issue by Ariuw** [NamelessMC/Nameless#380]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.11
* How would you describe the issue?  When you click on the "Activate" button it doesn't work because it redirects me to a white page... I don't know what to do
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? <img src="http://image.prntscr.com/image/5b76eb8b43e64625a7123783ddce10eb.png">
* Do you have an idea how or where the issue occurs? I don't know

**Comment by godleydemon** [comment]
if your using chrome, right click on the page before you hit the activate on themes, and hit inspect. That's going to bring up a chrome dev tool. Click on the tab that says Console. Then go ahead and click on activate, then pastebin us the output of what the console says. That'll give us a better idea of whats actually happening.

**Comment by samerton** [comment]
Can you enable error reporting (AdminCP -> Misc) to see if any errors appear on the page after activating a theme?

**Comment by Ariuw** [comment]
Well it was my fault :S but I fix it doing this:

1- Join to the database
2- Click on nl1_themes
3- Choose the theme that I want and click on edit
4- then where it says "enabled - tinyint(1)" put instead of a 0 a 1

Sorry it was my fault
