### ISSUE TITLE
mail page in admin cp disappears after changing and saving

### ISSUE THREAD

**Issue by aycgit** [NamelessMC/Nameless#381]
Bug
release 1.0.11 
mail page in admin cp disappears after changing email data and saving
 [photo](https://snag.gy/Odij51.jpg)  
no idea, could be something with the page stopping a loop when somehting is changed

**Comment by samerton** [comment]
Try the following command in SSH:

**sudo chown -R www-data:www-data /var/www/html**

assuming Nameless is installed in /var/www/html

**Comment by aycgit** [comment]
how do i get chown on my webserver

**Comment by aycgit** [comment]
Also, this didnt happen before 1.0.11

**Comment by aycgit** [comment]
@samerton it seems like i cant use the chown command on my webserver, which permission do i need to change?

**Comment by godleydemon** [comment]
@aycgit what OS are you running on your webserver?

**Comment by samerton** [comment]
I've actually been able to reproduce your issue, I'll investigate it shortly.

**Comment by samerton** [comment]
If you manually edit **core/email.php**, and change the line saying `'smtp_auth' =>` so it reads `'smtp_auth' => true`, your issue should be resolved. However, you'll need to manually edit the file instead of using the AdminCP until version 1.0.12.
