### ISSUE TITLE
should there be posts here?

### ISSUE THREAD

**Issue by aycgit** [NamelessMC/Nameless#382]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

#### Example:
question
release 1.0.11
should there be posts in the marked place? i posted a thread in the news forum but it doesnt show there
i have table view on for the forum
photo: https://snag.gy/MaCdAI.jpg
no idea, but fixing would be good

**Comment by godleydemon** [comment]
you know what, you seem to be having all sorts of issues right now. Try this out for me. 

Navigate to your www root folder where you have your NamelessMC installed at and type the following into putty (or whatever terminal program your using for your server).

chown -R www-data:www-data ./*

Then try and reload everything and see what happens.

**Comment by samerton** [comment]
It looks like the News forum is set as a category instead of a discussion forum.

One way around this is to create a new forum (call it Forum for now), set it as a category, and then modify each forum you already have and set its "Parent Forum" option to this newly created forum.

**Comment by aycgit** [comment]
@godleydemon chown is a unknown command?

**Comment by aycgit** [comment]
@samerton but having everything in one category wont look that good

**Comment by aycgit** [comment]
and it happens to every forum

**Comment by samerton** [comment]
@aycgit 
In that case, you can create multiple categories. This approach is normal for forum software, and it will result in something like [this](https://www.spigotmc.org/forums/).

**Comment by aycgit** [comment]
in that case thanks, would be a idea to make it possible to just also show posts in those forums

**Comment by samerton** [comment]
Due to how the forums work, this is something I can't see changing sorry. The categories are simply intended to split up forums, instead of having posts in them.

I'll mark this as closed, if you have any other questions feel free to reopen.
