### ISSUE TITLE
Multiple Buycraft API keys

### ISSUE THREAD

**Issue by godleydemon** [NamelessMC/Nameless#383]
suggestion

Add multiple API keys for pulling up multiple shop tabs. Atm it's showing all of the servers, but only the one you have the api key in displays the shop items. If you add in the ability to poll multiple api keys, we'd be able to get all of the shop items in our tabs. Not exactly sure how to accomplish this though, as I'm to tired to understand how your polling the buycraft api.

**Comment by IsS127** [comment]
Ye, this is a good idea!

**Comment by partydragen** [comment]
Its already planned but u can create a new api that none servers using and lett all packages have that api key to list all catagories and all latest donators

**Comment by IsS127** [comment]
I have a network, and i would like my donate go to diff paypal accs and thats impossible so the api keys will solve it..

**Comment by godleydemon** [comment]
@partydragen thanks for that, I hadn't thought of making just a single api key hitting all of the servers as well as having there separate api keys. I was a little tired last night.. lol
