### ISSUE TITLE
Many mistakes in my web site help please! D=

### ISSUE THREAD

**Issue by LUNATICOS** [NamelessMC/Nameless#393]
Not if this topic is where I have q put this but well
The thing is that I have just installed the software without "problems" shaft that activates the function to see mistakes

Mistakes go out for me in almost the whole web to look at the video

Video: ===> [http://www.mp4upload.com/19yry6cur5fl](url)

my spigot page for contact send MP: [https://www.spigotmc.org/members/lunaticos.119407/](url)

**Comment by samerton** [comment]
This issue is being resolved via Spigot PM, I'll mark this as closed here :)
