### ISSUE TITLE
Twitter Widget Length

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#397]
After updating to 1.0.12, the Twitter Widget is occupying a very large amount of vertical space.
Example: http://www.pandacraft.org/
I suggest limiting it to only a few recent posts or adding the option to specify how many posts it should be limited to.

**Comment by samerton** [comment]
Are you using a custom template? If so you'll need to update the **navbar.tpl** file to implement the code below `{$GLOBAL_MESSAGES}` found [here](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/navbar.tpl).

**Comment by BlackBeltPanda** [comment]
Looks like the 'data-height="600"' was removed at one point. I added it into my index.php file and got the height fixed on my end. =)
