### ISSUE TITLE
Announcements not working

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#398]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.12
* How would you describe the issue? Announcements don't appear to work
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
  * Announcement: https://i.gyazo.com/252fcec3f47ae60148562c1b9f94fc5b.png
  * Website: http://www.pandacraft.org
* Do you have an idea how or where the issue occurs? No

**Comment by samerton** [comment]
Are you using a custom template? If so you'll need to update the **navbar.tpl** file to implement the code below `{$GLOBAL_MESSAGES}` found [here](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/navbar.tpl).

**Comment by BlackBeltPanda** [comment]
That fixed it, thanks =)
