### ISSUE TITLE
Web is a white page after instalation

### ISSUE THREAD

**Issue by TiTo-418** [NamelessMC/Nameless#399]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? https://github.com/NamelessMC/Nameless/commit/4404293c642df7f88c37a08e67e5266ade375b13
* How would you describe the issue? Title, all plages are blank
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No errors in the logs
* Do you have an idea how or where the issue occurs? When I get to `http://localhost/admin/?from=install`

**Comment by Ariuw** [comment]
There's a way to see the problem that you're having:

1- Go to your db where Nameless instalation is located
2- Then click on nl1_settings
3- Click on Edit in the "error_reporting" I think that is the 19 line ID not sure :P 
4- Change the value of 0 to 1
5- get on http://localhost/admin/?from=install again and you will see your problem that you have to fix

I hope this help, if you need help feel free to ping me :+1:

**Comment by samerton** [comment]
It might be worth trying the command **chown -R www-data:www-data /var/www/html** (if you're running Ubuntu/Debian), as this can be caused by your **cache** directory not being recursively writable.

**Comment by TiTo-418** [comment]
Not sure what happened, deleting the database and creating another fixed it! Thank you.
