### ISSUE TITLE
[Request] Make other groups be Admin (Like co-owners)

### ISSUE THREAD

**Issue by megoesrawr** [NamelessMC/Nameless#40]
All in the title. But, basically,  Allowing Admin group to be set for other groups like if I had a co-owner group, they have ALL the same perms as an admin/owner.

**Comment by megoesrawr** [comment]
I think I found it. I was confused because a while ago I tried to do somethings but I couldn't because I wasn't in group 3.

**Comment by samerton** [comment]
I'm hoping to improve the system with inheritance in 1.1, however for now groups need to be manually configured (you can give a group access to the AdminCP/ModCP by editing them in the "Groups" tab)

**Comment by megoesrawr** [comment]
Ok thanks.
