### ISSUE TITLE
Nameless Stays white

### ISSUE THREAD

**Issue by melerpe** [NamelessMC/Nameless#401]
Updated trough the updater from 10 to 11 to 12, everything became white. Reinstalled everything. Still stays white. Link: funtasiapark.nl

More info will be provided if needed.

**Comment by melerpe** [comment]
Parse error: syntax error, unexpected 'verification_failed' (T_STRING), expecting ')' in /home/u931764932/public_html/styles/language/Dutch/language.php on line 453

**Comment by melerpe** [comment]
Error found

And that made me totaly start over the instalation

**Comment by melerpe** [comment]
Submitting fix to a pull request

**Comment by samerton** [comment]
Thanks for the pull request fixing this, I'll go ahead and mark this issue as closed.
