### ISSUE TITLE
[Bug] User Alert

### ISSUE THREAD

**Issue by TheRealPear** [NamelessMC/Nameless#406]
* What kind of issue is it (Question, Bug, etc.)
Bug
* In which version of NamelessMC did it occur (1.x.x)
NamelessMC 1.0.12
* How would you describe the issue?
When a user make a post on their own wall, they receive a alert saying that they got a new post on their wall which is the one that the user made.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Yes, https://i.gyazo.com/95e330662af6b8f58c4db30a6c16a77a.png
* Do you have an idea how or where the issue occurs?
No I don't, but I noticed this bug before and forgot to report this to the NamelessMC author (samerton)

**Comment by partydragen** [comment]
this problem have been since 1.0.11 when profile alert got added
It will sure be fixed in future :)

**Comment by MuhsinunCool** [comment]
@partydragen XD

**Comment by samerton** [comment]
The alert when posting on your own wall has been removed as of 9b42cd57befd98291c7df72227284138973b4fb5, thanks to @PugaBear
