### ISSUE TITLE
Updating not working

### ISSUE THREAD

**Issue by justin57754** [NamelessMC/Nameless#408]
When I try to update to 1.0.11 from 1.0.10, I put the files in, I run the update. The website stops and it doesn't update.

**Comment by BukkitTNT** [comment]
Go to your MySQL-Database & set in "nl_settings" the version from "1.0.10" to "1.0.11".

**Comment by BukkitTNT** [comment]
![image](https://cloud.githubusercontent.com/assets/13138106/17939589/9cd2520c-6a2b-11e6-93f1-027ff89618c5.png)

**Comment by IsS127** [comment]
If you mean that the web is blank white. then before putting files, have the update page there. When u have put it, click update.

**Comment by samerton** [comment]
@justin57754 Were you able to resolve the issue from the above replies?

**Comment by samerton** [comment]
I'll mark this issue as closed as I can't reproduce any updating issues, this may have been caused as the initial installation was a "latest ZIP" download before the 1.0.11 release, this shouldn't happen in the future though.
