### ISSUE TITLE
View count bugged

### ISSUE THREAD

**Issue by Liphius** [NamelessMC/Nameless#409]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.12
* How would you describe the issue? The view count is bugged. Before the update, the view count of posts was normal, now its either 0 views with a few posts or extremely low number of views once it does somewhat work. On new posts, it does stay at 0 views now though, even though I do know that a few people have seen it.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://i.imgur.com/QzmSubX.png
* Do you have an idea how or where the issue occurs? View count in the forum sections of new posts.

**Comment by partydragen** [comment]
Looks like i have the same problem with most of the new posts after 1.0.12
some some new post have view idk why

**Comment by samerton** [comment]
Should be fixed in 457251b5cdec7df102324b57b27f1b49ccab7ae3
