### ISSUE TITLE
frameBorder Iframe

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#41]
Hi there,

I'm not fully sure or it is something with Nameless but when I add to my iFrame frameBorder="0" it won't remove the frameborder and deletes that piece out of the page source code. Do you know how to remove the border from an iframe?

**Comment by samerton** [comment]
I haven't allowed frameBorder to the allowed HTML attributes yet, I'll add it now.

**Comment by samerton** [comment]
Added in fa23f48641f31c014a8507ada61294590ed92807
