### ISSUE TITLE
Do I need the PHP mysqlnd extension to install namless

### ISSUE THREAD

**Issue by TechDIN0** [NamelessMC/Nameless#412]
@samerton While install nameless i see that it says that i dont have the PHP mysqlnd extension and im not sure if i need that or not, but if i do i dont know how to install it.

**Comment by samerton** [comment]
The mysqlnd extension is only required if you're upgrading from the old pre-releases (version 0.4), if it's a new installation it's not required.

**Comment by AlliedCore** [comment]
It not needed but as said by Sam it will be for older releases as I have experimented with this matter.

**Comment by samerton** [comment]
I'll mark this issue as closed, if you have any further questions feel free to re-open.
