### ISSUE TITLE
Requirements ( Proceed Button )

### ISSUE THREAD

**Issue by Ar1sC** [NamelessMC/Nameless#413]
I'm Trying to Install Nameless 1.0.12. I Fixed an error with the install button(Allow Override).Now when I click next and i see the Requirements (http://imgur.com/a/U9Kxg) I don't see "Proceed Button"

**Comment by Ar1sC** [comment]
Update#1 Probably It's Permission Problem. Will update soon.

**Comment by samerton** [comment]
Looks like you're missing the php-xml extension, this can cause the page to stop working.

On Debian/Ubuntu try `sudo apt-get install php5-dom`
and on CentOS try `yum install php-xml`

**Comment by Ar1sC** [comment]
Update#2 Found Solution. (Using Ubuntu 16.04)
I Proceed and now.... http://imgur.com/a/M8K1X
What Permission should i set it?

**Comment by Ar1sC** [comment]
Update#3  sudo chmod 0777 config.php

**Comment by Ar1sC** [comment]
Update#4 Another Problem. 
Your cache/ directory must be readable and writeable. Check your file permissions.
I'm Lucky.

**Comment by Ar1sC** [comment]
Update#4
Did sudo chmod 0777 cache.

**Comment by Ar1sC** [comment]
Update#6
My Admin Panel is White..... :|

**Comment by Ar1sC** [comment]
Whole Site is Blank....

**Comment by Ar1sC** [comment]
Update#7 Fixed.
Sites seems to operate normally.
Example:
Did sudo chown -R www-data:www-data /var/www/folder1/folder2/cache

**Comment by Ar1sC** [comment]
So the page Help had some permission errors. It was saying to chmod some files and did.
but now home page and play page...
`Notice: Undefined offset: 0 in /var/www/mcsociety.xyz/public_html/pages/index.php on line 15

Notice: Trying to get property of non-object in /var/www/mcsociety.xyz/public_html/pages/index.php on line 15

Notice: Undefined offset: 0 in /var/www/mcsociety.xyz/public_html/pages/index.php on line 16

Notice: Trying to get property of non-object in /var/www/mcsociety.xyz/public_html/pages/index.php on line 16

Notice: Undefined offset: 0 in /var/www/mcsociety.xyz/public_html/pages/index.php on line 17

Notice: Trying to get property of non-object in /var/www/mcsociety.xyz/public_html/pages/index.php on line 17`

**Comment by Ar1sC** [comment]
Update#8
I just realize that misc "Error Reported" did that. Disabled and fixed.

**Comment by Ar1sC** [comment]
Update#9
Every page I Create I click on it and it redirects me back to home page. I Enabled The error reporterting and fixed the permissions problem on page but I still have error on home page with pages/index.php lines 15,16,17 Undefined offset: 0 and  Trying to get property of non-objec.

**Comment by Ar1sC** [comment]
Also on play page, lines 53,54,54 same notice errors.

**Comment by Ar1sC** [comment]
Also on play page, lines 53,54,54 same notice errors.

**Comment by Ar1sC** [comment]
Also on play page, lines 53,54,54 same notice errors.

**Comment by Ar1sC** [comment]
Also on play page, lines 53,54,54 same notice errors.

**Comment by samerton** [comment]
If you're being redirected back to the homepage from your custom pages, check your page permissions by editing the page in the AdminCP -> Custom Pages tab.

As for the errors on the homepage and the play page, you'll need to configure a Minecraft server to remove them (AdminCP -> Minecraft tab). If you won't want your site to be Minecraft related, you can hide the messages by disabling error reporting (AdminCP -> Misc).

**Comment by Ar1sC** [comment]
Update#10 
yep, custom page permissions was the problem.
I will add later the servers. Also I want to Install LetsEncrypt on my server. Will it mess anything?

**Comment by samerton** [comment]
LetsEncrypt/SSL shouldn't affect Nameless at all.

**Comment by Ar1sC** [comment]
I don't get any error now. But I Added Server Discord ID, its just loading http://imgur.com/a/aynxp. Also Can I remove something from your code?

**Comment by samerton** [comment]
If you're having problems with the Discord widget, ensure your widget is actually enabled in your Discord server settings (http://i.imgur.com/lJf2AwN.jpg). If it's enabled, double check your server ID is correct and if it still doesn't work, it'll be a problem on Discord's side.

As for modifying Nameless code, Nameless is licensed under MIT so feel free to modify anything you like.

**Comment by Ar1sC** [comment]
Thx for helping me out.
