### ISSUE TITLE
'Play' tab ignoring port for getting player count

### ISSUE THREAD

**Issue by RobinMCNetwork** [NamelessMC/Nameless#415]
I am having this bug in the latest version (1.0.12):
I have a server running on port 6660. On the 'Play' page it shows players that are on ip:6660, but the player count is from ip:25565.

When joining on port 6660: http://i.imgur.com/upG3xRr.png
When joining on port 25565: http://i.imgur.com/LChZBee.png

I might make a PR if I can figure out where the code is and how it works

**Comment by IsS127** [comment]
are theese servers bouth vanilla?

**Comment by RobinMCNetwork** [comment]
The server on port 25565 is BungeeCord (1.10) and the one on 6660 is running spigot 1.10.2

**Comment by IsS127** [comment]
Does the 25565 go to the 6660?

**Comment by RobinMCNetwork** [comment]
I don't get what you mean by that, sorry

**Comment by AlliedCore** [comment]
Its port forwarding is what he is trying to say to you. Does one of the ports connect to the other one?

**Comment by RobinMCNetwork** [comment]
25565 -> 25565 Server 1
6660 -> 25565 Server 2

**Comment by AlliedCore** [comment]
You wan to display both of the servers?

**Comment by RobinMCNetwork** [comment]
I want to show 6660, but the play tab displays this:
Player count of 25565
Player list of 6660

**Comment by AlliedCore** [comment]
Unable to be done. Add this to a suggestion to a later update to the software.

**Comment by RobinMCNetwork** [comment]
You do not seem to be getting what I am trying to explain, here it is again:

What I want:
Player count of 6660
Player list of 6660

What actually happens:
Player count of 25565
Player list of 6660

**Comment by AlliedCore** [comment]
Wait so you want the player count and also to show the players within the live status of the server? @RobinMCNetwork

**Comment by RobinMCNetwork** [comment]
Yes.

**Comment by IsS127** [comment]
Unfortunatley... that isnt possible. It only shows the count of the main
server.. that is 25565 for you.
You could change the code thou.

2016-09-29 16:32 GMT+02:00 Robin <notifications@github.com>:

**Comment by RobinMCNetwork** [comment]
At first I wanted to create a PR but I could not figure out how the code works. That's the reason why I have created this issue. There should be a way for them to add a port to the server ping, since it does work for player list.

**Comment by RobinMCNetwork** [comment]
I managed to do this by hardcoding the IP and port in core/integration/status/global.php

**Comment by AlliedCore** [comment]
Solved? @RobinMCNetwork
