### ISSUE TITLE
Creating new user issue [solved]

### ISSUE THREAD

**Issue by DaedalusPrime97** [NamelessMC/Nameless#418]
When I want to create a new user, I'am getting this error while clicking on the 'submit' button

SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value

Does any of you know how to fix this error?

**Comment by samerton** [comment]
Thanks, I'll take a look.

**Comment by AlliedCore** [comment]
Must have been solved by now. /close?

**Comment by DaedalusPrime97** [comment]
This has been solved by now, Thank you :)

**Comment by AlliedCore** [comment]
@samerton  add closed tag

**Comment by samerton** [comment]
@AlliedCore I'll keep this open so I can implement a fix which will prevent this from happening in the future.

**Comment by AlliedCore** [comment]
@samerton Sounds good to me! :+1:

**Comment by AlliedCore** [comment]
Solved.
