### ISSUE TITLE
Installer is missing?

### ISSUE THREAD

**Issue by KingLinux01** [NamelessMC/Nameless#419]
When it redirects me to the installer it says it is not there
Not Found

The requested URL /install was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by samerton** [comment]
Sounds like there's some extra configuration that needs to be done, [this](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) should help you out.

**Comment by samerton** [comment]
I'll mark this as closed as the steps to fix this are in the link in my previous reply, if you're still experiencing issues feel free to re-open.
