### ISSUE TITLE
[Suggestion] Add Ad-don to add  Ads on Left or Right 

### ISSUE THREAD

**Issue by Ar1sC** [NamelessMC/Nameless#421]
Suggestion:
Add Ad-don to add Ads/Sponsor Ads on left or right or on header etc.

**Comment by AlliedCore** [comment]
When you say this do you mean by adding an add-on feature that allows advertisements?

**Comment by Cl1608Ho** [comment]
Basically implement admob, right?

**Comment by Ar1sC** [comment]
@AlliedCore Yes.

**Comment by AlliedCore** [comment]
@Ar1sC  I am pretty sure if you can configure the code you can add the feature for yourself. But always give credit to @samerton for the main build of the project.

**Comment by Cl1608Ho** [comment]
@AlliedCore this is probably off topic, but nameless uses the MIT license which doesn't imply that you need to credit samerton. 

In fact samerton even told me via mail that I can remove the notice without any problems......

**Comment by AlliedCore** [comment]
@Cl1608Ho  Thanks for clarifying. But even though some licences do state this the owners of the software do get a bit crabby on the matter. But I do understand that samerton said so.

**Comment by samerton** [comment]
I can look into adding advert support in version 2.0.

It's absolutely fine if you'd like to remove the notice as I understand people want to totally customise their site, however it's certainly appreciated if it's kept.

**Comment by AlliedCore** [comment]
@samerton Apparently the API is broken. Check one of the issue reports.

**Comment by AlliedCore** [comment]
@samerton Well the person who posted it thinks so
