### ISSUE TITLE
[Suggestion] Multiple Groups

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#425]
- What kind of issue is it (Question, Bug, etc.)? Suggestion
- In which version of NamelessMC did it occur (1.x.x)? 1.0.12
- How would you describe the issue? I was suggesting that players be able to be put into two groups like say VIP and Admin at the same time
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No, it's a suggestion
- Do you have an idea how or where the issue occurs? No, it's a suggestion, but I was trying to put one of my player's faction rank along with their staff rank and realized that I can't do that on the website

**Comment by partydragen** [comment]
Its already planned :) https://github.com/NamelessMC/Nameless/issues/217
Its stand v1.1 But i think its being v2.0 hopefully not to long

**Comment by samerton** [comment]
I'll mark this as closed so #217 can be used for discussion :)
