### ISSUE TITLE
[CRITICAL] MAILS NOT SENDING.

### ISSUE THREAD

**Issue by AsaPlaysMC** [NamelessMC/Nameless#427]
How to fix; 

Go to every PHP file that has to do with mail sending and change the lines:

```
    $mail->setFrom($GLOBALS['email']['username'], $GLOBALS['email']['name']);
    $mail->From = $GLOBALS['email']['username'];
```

to

```
    $mail->setFrom($GLOBALS['email']['name'], $GLOBALS['email']['name']);
    $mail->From = $GLOBALS['email']['name'];
```

@samerton Fix it right as you can and give me a list of files to update/fix for my install

**Comment by yargevad** [comment]
This happened when using NamelessMC with SparkPost. The issue was that NamelessMC uses `$GLOBALS['email']['username']` as both the `SMTP AUTH` username and the `MAIL FROM` email address, which won't necessarily be the same.

The change above is how @AsaPlaysMC fixed the issue in their environment.

**Comment by samerton** [comment]
Being dependant on the environment, as @yargevad says, this will take some looking into to make sure that all environments are accounted for.

**Comment by Derkades** [comment]
Is this fixed in v2? I think we can close this.

**Comment by baxandrei** [comment]
In tested on v1 and v2 and work correctly , but depend in server settings, i haved an shared host and email wont send because îs in mail blocklist or îs spam like content

**Comment by samerton** [comment]
Unfortunately this isn't something I can add options for within Nameless, however in v2 emails are sent from a centralised class so making code modifications is easier. 
As the majority of configurations work with the default Nameless config I'll keep it how it is currently, but I'll create a guide in the future on modifying the email config for instances like this.
