### ISSUE TITLE
[Suggestion] CoreProtect2 Data Lookup

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#429]
- What kind of issue is it (Question, Bug, etc.)? Suggestion
- In which version of NamelessMC did it occur (1.x.x)? 1.0.12
- How would you describe the issue? I would like access to CoreProtect2 data lookups through the website like [this](https://github.com/SimonOrJ/CoreProtect-Lookup-Web-Interface). I use that one.
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Not an issue.
- Do you have an idea how or where the issue occurs? Not an issue.

**Comment by samerton** [comment]
I'll mark this as closed, thanks for the module (https://github.com/MuhsinunCool/CoreProtect-Lookup-Web-Interface) ;)
