### ISSUE TITLE
[Suggestion] Web Console

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#431]
- What kind of issue is it (Question, Bug, etc.)? Suggestion
- In which version of NamelessMC did it occur (1.x.x)? 1.0.12
- How would you describe the issue? I would like a web console with file access similar to [JPanel](https://github.com/rymate1234/JPanel), but built into the website and perhaps the plugin part of the console might be included with the official NamelessMC plugin?
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Not an issue.
- Do you have an idea how or where the issue occurs? Not an issue.

**Comment by AsaPlaysMC** [comment]
First and foremost, Why would you need a "Web Console"? Most systems nowadays have a subuser system to allow your staff to get console.

Second, Why are you using the default format? XD

**Comment by MuhsinunCool** [comment]
First: My host has a crappy looking Web UI and it doesn't even support sub users XD and I wanted a nice and flashy one XD which is exactly the one I use XD

Second: Cuz I can :P And I like uniform :P

**Comment by AlliedCore** [comment]
@MuhsinunCool 
Who is your host? Also if they are that devolved then I suggest you switch hosts just for your own convenience.

**Comment by MuhsinunCool** [comment]
@Emoxus Fluctis Hosting. It's cheap tho :P

**Comment by Emoxus** [comment]
@MuhsinunCool 
In that case I guess you are okay with having to use their services.

**Comment by Emoxus** [comment]
Closed

**Comment by WASasquatch** [comment]
Coming from a admin of 100k a web console is very much needed. Too much
monitoring from work, home, the car, etc.

**Comment by MuhsinunCool** [comment]
Agreed I still want a web console regardless ur rebuttles @Fellings1 I believe it's up to @samerton to make the decision of whether or not to add the web console.

**Comment by Fellings1** [comment]
@MuhsinunCool I am actually part of the NamelessMC staff team just to be clear. Also I was just leaving my opinion on this post because some other options can assist in solving the issue.

**Comment by samerton** [comment]
Whilst this is outside the scope of the main Nameless project, this is definitely something I can look into in terms of an addon for 2.0.

A third party plugin would have to be used, potentially jPanel itself (if the plugin is still active and it works).
