### ISSUE TITLE
[Suggestion] Move Around Questions For Staff Applications

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#432]
- What kind of issue is it (Question, Bug, etc.)? Suggestion/Bug
- In which version of NamelessMC did it occur (1.x.x)? 1.0.12
- How would you describe the issue? I can't move around the staff applications questions after making them so I have to make them in order from last to first. Please allow us to do this! Thanks!
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No.
- Do you have an idea how or where the issue occurs? In the staff applications question list.

**Comment by PugaBear** [comment]
@MuhsinunCool I believe if you edit the database using a database interface like phpMyAdmin, you can change the `id` if the questions to be in the order you want them to be in.

**Comment by MuhsinunCool** [comment]
@PugaBear But it wud be much easier and much more intuitive if there was the ability to move them around normally especially for users without much knowledge on that stuff. :P

**Comment by PugaBear** [comment]
@MuhsinunCool I agree, I'm just giving you a solution in the meantime.

**Comment by samerton** [comment]
This is one to ask in the forms module repo, found here: https://github.com/partydragen/Nameless-Forms, if not already possible.

**Comment by partydragen** [comment]
Ordering already possible in the new forms module
