### ISSUE TITLE
[Suggestion] AuthMe Account Compatibility

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#433]
* What kind of issue is it (Question, Bug, etc.)? Suggestion
* In which version of NamelessMC did it occur (1.x.x)? 1.0.12
* How would you describe the issue? I would like for there to be an addon or module or something that we can enable in order to use [AuthMe](https://www.spigotmc.org/resources/authme-reloaded.6269/) accounts on the website. I saw [this](https://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/web-site-integration/) and was wondering if it could be implemented into NamelessMC.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

**Comment by samerton** [comment]
Thanks for the suggestion, I'll mark this issue as closed so we can use #6 as a single issue.
