### ISSUE TITLE
[Suggestion] Set a custom description for donate packages

### ISSUE THREAD

**Issue by dwilson390** [NamelessMC/Nameless#434]
Would it be possible to be able to set a custom description for donation packages, instead of taking the description from Buycraft.

Thanks.

**Comment by MuhsinunCool** [comment]
I like the ease of access idea but isn't it just easier to edit it from Buycraft or MinecraftMarket? :P

**Comment by dwilson390** [comment]
The issue is there is too small a space to hold all the information I want.
I want to strip it down simply to something like;

You will be charged £7.50 every 3 months.

**Comment by samerton** [comment]
Added in 2bdc4b017346a901b82adc6754c21576498a3408
