### ISSUE TITLE
[Suggestion] Allow The Showing/Hiding Of "Ban Appeal" In The Nav Bar

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#439]
- What kind of issue is it (Question, Bug, etc.)? Suggestion
- In which version of NamelessMC did it occur (1.x.x)? 1.0.12
- How would you describe the issue? Title says it all. There shud be a button that allows u to toggle showing it in the nav bar and there shud also be an easy way to change the text it says
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Not an issue.
- Do you have an idea how or where the issue occurs? Not an issue.

**Comment by AlliedCore** [comment]
@samerton This is a good suggestion. Just tagged you so you can follow up! :+1:

**Comment by samerton** [comment]
I'll mark this as closed, and use https://github.com/partydragen/BanAppeal/issues/6 as the discussion for this :)
