### ISSUE TITLE
[Suggestion] Language Switcher

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#440]
* What kind of issue is it (Question, Bug, etc.)? Suggestion
* In which version of NamelessMC did it occur (1.x.x)? 1.0.12
* How would you describe the issue? I think it would be helpful if users on the website could use a language switcher at the bottom of the website to display the website in their native language. Also, maybe instead of having to make a whole new file for the messages in different languages, can you use like Google Translate if it has and API or something?
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Not an issue.
* Do you have an idea how or where the issue occurs? Not an issue.

**Comment by samerton** [comment]
Thanks for the suggestion, this has been implemented in my local 2.0 development builds so I'll mark this as closed :)

**Comment by AlliedCore** [comment]
Yeah I was going to say I thought you had already implemented this idea.
