### ISSUE TITLE
Players Have Weird Names In The Play Tab Of The Website

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#442]
- What kind of issue is it (Question, Bug, etc.)? Bug
- In which version of NamelessMC did it occur (1.x.x)? 1.0.12
- How would you describe the issue? Players have weird names in the play tab of the website.
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Yes:

![image](https://cloud.githubusercontent.com/assets/11369216/19097114/129eec70-8a70-11e6-9f88-1acfdcdbbe8a.png)

![image](https://cloud.githubusercontent.com/assets/11369216/19097123/1bc4e94e-8a70-11e6-9c5d-0a8722d684b9.png)
- Do you have an idea how or where the issue occurs? No idea how or why it occurs but it occurs in the Play tab of the website.

**Comment by samerton** [comment]
This tends to happen if you're using a plugin to modify the MOTD, or if it's a Bungee instance.

If it's a Bungee instance, you'll need to edit the server in the AdminCP -> Minecraft tab, and then uncheck "Show on Play page?", before adding your back-end Spigot instances as different servers.

**Comment by MuhsinunCool** [comment]
I modify the MOTD is there any way for u to fix this? Maybe query the server with something like Dinnerbone's[https://dinnerbone.com/minecraft/tools/status/](url) system? Thanks!

**Comment by samerton** [comment]
Unfortunately at the moment there isn't much that can be done about this, I'll have to look into potential solutions.

**Comment by MuhsinunCool** [comment]
Can't u use Dinnerbone's system?

**Comment by samerton** [comment]
Unfortunately I don't believe anything can be done about this as it's Minecraft server-side (caused by plugins modifying the MOTD/player count).
