### ISSUE TITLE
NamelessMC setup not possible

### ISSUE THREAD

**Issue by TopMaax** [NamelessMC/Nameless#445]
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.13.  
**How would you describe the issue?** The NamelessMC setup is not possible.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://prntscr.com/cr4ph7) [And here](http://prntscr.com/cr4pph)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the setup files but not sure. The continue button is not displayed.

**Comment by samerton** [comment]
Try the following commands in SSH:

Debian/Ubuntu:
sudo apt-get install php5-dom
sudo service apache2 restart

CentOS:
yum install php-xml
httpd restart

**Comment by TopMaax** [comment]
Thanks this works, but now I have a database problem [Click here](http://prntscr.com/cr4vaq)
