### ISSUE TITLE
Init bug

### ISSUE THREAD

**Issue by GlitchPlayer** [NamelessMC/Nameless#446]
* What kind of issue is it (Question, Bug, etc.)? Its a bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.13
* How would you describe the issue? I couldn't install the website. The php error only appears.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Look at this
![image](https://cloud.githubusercontent.com/assets/16515013/19220711/717c03fa-8e66-11e6-82e7-55913c57c4ad.png)

* Do you have an idea how or where the issue occurs?
No wonder How it is happening :/

**Comment by samerton** [comment]
This is caused by PHP not being at least version 5.3, simply updating to 5.3+ will fix this.

I'll add a better check to prevent this message in an upcoming update.

**Comment by AlliedCore** [comment]
Solved? @samerton

**Comment by samerton** [comment]
Yup, I'll go ahead and mark this as closed.
