### ISSUE TITLE
Nothing Showing Up

### ISSUE THREAD

**Issue by lmartim4** [NamelessMC/Nameless#447]
Right after installing it and seding me to the admin cp it just shows up a completely blank screen
https://i.gyazo.com/1927238bf7335eaf276464b4b60eec62.png

**Comment by lmartim4** [comment]
OUTPUT------------------------------------------------------------------
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="The homepage for the M4Play community">
    <meta name="author" content="Samerton">
    <meta name="theme-color" content="#454545" />
		
	<title>Home &bull; M4Play</title><link href="/styles/themes/Bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/styles/themes/Bootstrap/css/custom.css" rel="stylesheet">
<link href="/styles/themes/Bootstrap/css/font-awesome.min.css" rel="stylesheet">
<link href="/core/assets/css/toastr.css" rel="stylesheet">
<link href="/core/assets/css/custom_core.css" rel="stylesheet">
<link rel="icon" href="/core/assets/favicon.ico">	
	
	<style>
	html {
		overflow-y: scroll;
	}
	.jumbotron {
		margin-bottom: 0px;
		background-image: url(core/assets/img/background-1920x828.jpg);
		background-position: 0% 25%;
		background-size: cover;
		background-repeat: no-repeat;
		color: white;
	}
	</style>
	
  </head>
  <body>
---------------------------------------------------------------------------------------------------------------

**Comment by samerton** [comment]
Try the following SSH command (Debian/Ubuntu):

`sudo chown -R www-data:www-data /var/www/html/cache`

assuming Nameless is installed in /var/www/html

**Comment by lmartim4** [comment]
I am running Centos, but I assumeyou just want me to 
"chmod 0777 /var/www/html/cache"
 right?

**Comment by samerton** [comment]
Make sure that any permission changes are recursive, a CentOS example command would be

`chown -R apache:apache /var/www/html/cache`

**Comment by lmartim4** [comment]
It is now working, thank you for fast answearing, I apreciate that. right it's running on http://sgs.m4play.net if you want to see it

**Comment by lmartim4** [comment]
By the way where is the plugin download?

**Comment by samerton** [comment]
No problem, glad it's working!

The plugin is not ready for release yet unfortunately, there's no estimated completion date at the moment.

**Comment by lmartim4** [comment]
Ok, thank you

**Comment by lmartim4** [comment]
Ah why is the website so slow, I mean I used to run xenforo is a similar vps and that was much faster

**Comment by lmartim4** [comment]
Warning: Directory /var/www/html/core/includes/htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer/HTML not writable, please chmod to 777 in /var/www/html/core/includes/htmlpurifier/HTMLPurifier.standalone.php on line 15335

I CHMOD'ed and nothing happens

**Comment by samerton** [comment]
From my (brief) performance tests, Nameless is light on sever resources so I'm not sure why your site is acting slow unfortunately.

As for the error, try:

`chown -R apache:apache /var/www/html/core/includes/htmlpurifier`

**Comment by AlliedCore** [comment]
Solved.

**Comment by samerton** [comment]
I'll mark this issue as closed, if you're still experiencing issues feel free to re-open.
