### ISSUE TITLE
Question - Change the author title

### ISSUE THREAD

**Issue by partydragen** [NamelessMC/Nameless#449]
Hey @samerton idk u want it or not but can u change the author on all pages to be website name instant?

Because when we always sending the link to like discord, skype then its stand Samerton as tittle because its loading the author i really don't know why its like that :/

And its really looks bad about its stand Samerton as title instant of Website name

You can see it here: http://imgur.com/a/XRIVV

Idk its any other may to solve it or its a bug but i have tryed and its the author code that set the title Samerton

**Comment by Emoxus** [comment]
@partydragen Are you just a user of the software? I was going to suggest that if you knew how to read the code maybe you could edit it because this is a open source project.

**Comment by samerton** [comment]
Fixed in #462
