### ISSUE TITLE
forum

### ISSUE THREAD

**Issue by Toxic-Waste** [NamelessMC/Nameless#45]
Dont know if its me but.in the admin cp under forums i create a forum

![forum](https://cloud.githubusercontent.com/assets/1909777/11613910/074b6140-9bf7-11e5-81e2-7dda3899d9ce.png)

under the permissions i have checked all the boxes for permissions and unchecked the permissions still the same result.
no forum shows up un the navabar link.

![forumpage](https://cloud.githubusercontent.com/assets/1909777/11613918/577f1ecc-9bf7-11e5-8c95-b5cc47c5a243.png)

mc.tooncraft.net

**Comment by Adobes** [comment]
Simple fix, you need to have a parent category first. The easiest way for me to explain this would be by providing pictures:

This is how it should look like:
![image](https://cloud.githubusercontent.com/assets/7917503/11614033/4a37988c-9c03-11e5-9397-1fab5466d4a2.png)

The "McVerge" in this case is the parent category, whilst Announcements is one that falls under it.

For the parent category, make sure you have this:
![image](https://cloud.githubusercontent.com/assets/7917503/11614035/6dce160e-9c03-11e5-8acc-62837304739f.png)


For the sub category make sure you have this:
![image](https://cloud.githubusercontent.com/assets/7917503/11614037/841475ac-9c03-11e5-8dd8-30439fd53155.png)


Obviously this alters for your needs.

Hope this helps!

**Comment by Toxic-Waste** [comment]
hell that worked ty. the name of the parent i made was Toon Craft is it suppose to show up the parent catagory. The parent catagories no not seperate sections, made another Tooncraft plugins added a forum to it and looks like its ibn the same section as the others. take a look if you want

http://mc.tooncraft.net/forum

**Comment by Toxic-Waste** [comment]
seen in a another issue ty
