### ISSUE TITLE
Social logins

### ISSUE THREAD

**Issue by MuhsinunC** [NamelessMC/Nameless#451]
I was hoping for the ability to register and login using those "Sign In With Google" and "Sign In With Facebook" buttons and to link those accounts to your regular account. Maybe you can link your Minecraft account with your account using something like Enjin's system?

**Comment by samerton** [comment]
Good idea, thanks for the suggestion. I'll look into this once an initial version 2.0 build is ready.

**Comment by MuhsinunCool** [comment]
Yay tysm! :D

**Comment by TheRealPear** [comment]
Can't wait to see this

**Comment by MicroBotCodes** [comment]
I cant wait to see this 4 years later I am here and hopefully, we get this soon!!

**Comment by MuhsinunC** [comment]
Lmao

**Comment by StormyIceLeopard** [comment]
I hope we will be able to control which ones are allowed.

**Comment by zJerino** [comment]
:D

**Comment by Slddev** [comment]
bump

**Comment by Aberdeener** [comment]
> I hope we will be able to control which ones are allowed.

You will be!
I think we will support Discord, Google and possibly another out of the box - each will require small configuring by the site admin to setup their specific credentials, but each will also be able to be disabled.

See #2570 for status
