### ISSUE TITLE
Categorizing the Official NamelessMC Website 

### ISSUE THREAD

**Issue by Emoxus** [NamelessMC/Nameless#452]
* What kind of issue is it (Question, Bug, etc.) Suggestion.
* In which version of NamelessMC did it occur (1.x.x)? - The Official Website (http://namelessmc.com/)
* How would you describe the issue? - Just a minor change to the theme of the website so it can be accessed in educational environments (School campuses).
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? - No
* Do you have an idea how or where the issue occurs? Its not really an issue but a good change to see in the near future.

**Comment by samerton** [comment]
Thanks for the suggestion, I was wondering which theme changes would help with accessing from the campus?

**Comment by Emoxus** [comment]
@samerton 
We discussed this "issue". Closed?
