### ISSUE TITLE
[Error/Help] Can't connect to external mysql server

### ISSUE THREAD

**Issue by melerpe** [NamelessMC/Nameless#455]
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.13.  
**How would you describe the issue?** Cannot connect to mysql server
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?**
Yes!
Website: http://avonturacraft.nl/
Config:
`<?php
$GLOBALS['config'] = array(
	"mysql" => array(
		"host" => '91.134.3.208', // Web server database IP (Likely to be 127.0.0.1)
		"username" => "minewalibi", // Web server database username
		"password" => '**************', // Web server database password
		"db" => "minewalibi", // Web server database name
		"prefix" => "nl1_" // Web server table prefix
	),
	"remember" => array(
		"cookie_name" => "nlmc", // Name for website cookies
		"cookie_expiry" => 604800
	),
	"session" => array(
		"session_name" => "user",
		"admin_name" => "admin",
ase IP (Likely to be 127.0.0.1)
		"username" => "minewalibi", // Web server database username
		"password" => 'wikikansloos1', // Web server database password
		"db" => "minewalibi", // Web server database name
		"prefix" => "nl1_" // Web server table prefix
	),
	"remember" => array(
		"cookie_name" => "nlmc", // Name for website cookies
		"cookie_expiry" => 604800
	),
	"session" => array(
		"session_name" => "user",
		"admin_name" => "admin",
		"token_name" => "token"
	)
);
`

**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by Headhunterzpw** [comment]
If you're using remote mysql from your vps try to add a # in front of bind-address in /etc/mysql/my.cnf

And otherwise take contact with your hosting provider.

**Comment by melerpe** [comment]
FIXED!, was a typo in the config!

**Comment by Fellings1** [comment]
@Headhunterzpw Thank you for the solution!
