### ISSUE TITLE
[Bug] Online Players Reply Error

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#457]
- What kind of issue is it (Question, Bug, etc.)? Bug
- In which version of NamelessMC did it occur (1.x.x)? 1.0.13
- How would you describe the issue? My server has been offline for a while and instead of the homepage saying there are 0 players online it says there are players online.
- Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Yes: 
  ![image](https://cloud.githubusercontent.com/assets/11369216/19831216/87815846-9dd2-11e6-8952-3cfb0721285a.png)
- Do you have an idea how or where the issue occurs? On the homepage. I think it's just a simple mistake in the response message for online players when the server is offline. Also, I think u should try Dinnerbone's Minecraft server pinger API: https://dinnerbone.com/minecraft/tools/status/ Thanks!

**Comment by Headhunterzpw** [comment]
"Do you have an idea how or where the issue occurs? On the homepage. I think it's just a simple mistake in the response message for online players when the server is offline. Also, I think u should try Dinnerbone's Minecraft server pinger API: https://dinnerbone.com/minecraft/tools/status/ Thanks!"

Dinnerbone's api is python based which you have to install on your dedicated server or VPS which requires to hardcode everything of your server..

**Comment by Fellings1** [comment]
@Headhunterzpw @MuhsinunCool Hey Guys! The message saying there are players online is simply a added message with the code of the website but can be edited to your will. If you need help with the code feel free to ask.

**Comment by samerton** [comment]
Thanks for spotting this, this should indeed state that the server is offline. I'll implement a fix for the next release.

**Comment by Fellings1** [comment]
@samerton Guess it was just an error within the code then. Thanks for taking it into consideration!

**Comment by MuhsinunCool** [comment]
@samerton Thanks! :D

**Comment by MuhsinunCool** [comment]
@Headhunterzpw Dinnerbone's API isn't Python based:
`Installation

mcstatus is available on pypi, and can be installed trivially with:

pip install mcstatus
Alternatively, just clone this repo!`

**Comment by samerton** [comment]
Unfortunately it's not possible to implement Dinnerbone's API as it is indeed a Python class (which isn't compatible with, for example, shared web hosts). I'm hoping to implement an improved query system in a future update though.

**Comment by Fellings1** [comment]
close
