### ISSUE TITLE
invalid token, glitchy custom pages

### ISSUE THREAD

**Issue by Venomancy** [NamelessMC/Nameless#458]
### Template:
Bug
1.0.13
Whenever I create a custom page, it makes it, but then when I go to it, it just redirects me back to the home page. Also, sometimes it says Invalid Token
forums.venomance.net, forums.venomance.net/vote
No idea why.

**Comment by partydragen** [comment]
Thats happen because you have multiple pages up at same time
like if you opening a another window to your website the other token will expire

Its fixed in the upconing v2 i think

**Comment by Venomancy** [comment]
Thanks!
