### ISSUE TITLE
Error while upgrading from previous version

### ISSUE THREAD

**Issue by HexaCubist** [NamelessMC/Nameless#46]
Attempted to upgrade the website with the new features from the commits, won't go past the upgrade page on the install.php. Following error is given:
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in /storage/web/websites/minecraft/core/classes/DB.php:68 Stack trace: #0 /storage/web/websites/minecraft/core/classes/DB.php(68): PDOStatement->execute() #1 /storage/web/websites/minecraft/core/classes/DB.php(167): DB->createQuery('INSERT INTO nl1...', Array) #2 /storage/web/websites/minecraft/core/classes/Queries.php(42): DB->insert('groups', Array) #3 /storage/web/websites/minecraft/pages/install.php(323): Queries->create('groups', Array) #4 /storage/web/websites/minecraft/index.php(33): require('/storage/web/we...') #5 {main} thrown in /storage/web/websites/minecraft/core/classes/DB.php on line 68
```

**Comment by HexaCubist** [comment]
Had to manually enable error reporting for that to show, otherwise page would just be blank

**Comment by samerton** [comment]
After applying the latest commits, you won't need to run the installer again, simply replacing the files involved in the commits will be enough.

**Comment by HexaCubist** [comment]
Okay. What should I do now then? I tried putting the old files back but it's not working. Will I need to reinstall the db or is there something I can do to save it? I have access to the db with phpmyadmin

**Comment by samerton** [comment]
You'll most likely have a large number of duplicate entries in your database, did you have a lot of data on the site beforehand?

**Comment by HexaCubist** [comment]
Quite a bit. What tables will be affected? All of them?

**Comment by samerton** [comment]
Looking at the upgrader code, you may only have duplicate entries in the "forums", "forums_permissions", and the "friends" table as the error may have killed the rest of the script. Hopefully that is the case, as then there wouldn't be too much duplicate data.

**Comment by HexaCubist** [comment]
Removed the duplicate data. What shall I do to get the website operational again?

**Comment by samerton** [comment]
Try removing the **pages/install.php** file, and see if the site works after that.

**Comment by HexaCubist** [comment]
No such luck. Here's what it shows:
```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="The homepage for the  community">
    <meta name="author" content="Samerton">
	
    <title> &bull; Home</title>
	
	<link href="/styles/themes//css/bootstrap.min.css" rel="stylesheet">
<link href="/styles/themes//css/custom.css" rel="stylesheet">
<link href="/styles/themes//css/font-awesome.min.css" rel="stylesheet">
<link href="/core/assets/css/toastr.css" rel="stylesheet">
<link href="/core/assets/css/custom_core.css" rel="stylesheet">
<link rel="icon" href="/core/assets/favicon.ico"><link href="/core/assets/plugins/bootstrap-multiselect/css/bootstrap-multiselect.css" rel="stylesheet"><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70844888-1', 'auto');
  ga('send', 'pageview');

</script>	
	<!-- Custom style -->
	<style>
	html {
		overflow-y: scroll;
	}
	.jumbotron {
		margin-bottom: 0px;
		background-image: url(core/assets/img/background-1920x828.jpg);
		background-position: 0% 25%;
		background-size: cover;
		background-repeat: no-repeat;
		color: white;
	}
	</style>
	
  </head>
  <body>
	
```

**Comment by samerton** [comment]
Can you add [this code](https://gist.githubusercontent.com/samerton/4909c7694ff435280765/raw/aa5cafd96ff93ca458552a7f235200e1e8f39cb5/Error%2520Reporting) to the very bottom of **core/init.php**? An error should display on the page allowing us to diagnose the issue.

**Comment by HexaCubist** [comment]
Fatal error: Uncaught --> Smarty: Unable to load template file 'styles/templates//navbar.tpl' <-- thrown in /storage/web/websites/minecraft/core/includes/smarty/sysplugins/smarty_internal_template.php on line 219

**Comment by SystemUpdate** [comment]
@samerton The issue may be the double // in the loading of the template file.

**Comment by samerton** [comment]
Looks like, for some reason, there was no template defined.

@HexaCubist Can you try replacing the contents of **core/init.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/c306542f1735fd3fb76208cbdce36a3d7304dfa4/core/init.php)?

**Comment by HexaCubist** [comment]
No such luck. I did some debugging of my own and narrowed it down to the "theme" and the "template" parameters not being in the cache file. For now, I've just hard coded in my choices, which will work fine for us. Thanks for the support!
