### ISSUE TITLE
[CRITICAL] Updating Issue 10.11 to 10.12

### ISSUE THREAD

**Issue by justin57754** [NamelessMC/Nameless#460]
Updating
This is happening when I update 10.11 to 10.12
When I go on the website it is just an error.
Text on the website: `
Notice: Undefined offset: 0 in K:\_webserver\XAMPP\htdocs\core\modules\Social_Media\initialisation.php on line 35

Notice: Trying to get property of non-object in K:\_webserver\XAMPP\htdocs\core\modules\Social_Media\initialisation.php on line 35

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nameless_install.nl1_announcements_pages' doesn't exist' in K:\_webserver\XAMPP\htdocs\core\classes\DB.php:42 Stack trace: #0 K:\_webserver\XAMPP\htdocs\core\classes\DB.php(42): PDOStatement->execute() #1 K:\_webserver\XAMPP\htdocs\core\classes\DB.php(104): DB->query('SELECT * FROM n...', Array) #2 K:\_webserver\XAMPP\htdocs\core\classes\DB.php(134): DB->action('SELECT *', 'announcements_p...', Array) #3 K:\_webserver\XAMPP\htdocs\core\classes\Queries.php(11): DB->get('announcements_p...', Array) #4 K:\_webserver\XAMPP\htdocs\core\includes\template\header.php(54): Queries->getWhere('announcements_p...', Array) #5 K:\_webserver\XAMPP\htdocs\core\includes\template\generate.php(9): require('K:\\_webserver\\X...') #6 K:\_webserver\XAMPP\htdocs\pages\index.php(106): require('K:\\_webserver\\X...') #7 K:\_webserver\XAMPP\htdocs\index.php(73): require('K:\\_webserver\\X...') #8 {main} thrown in K:\_webserver\XAMPP\htdocs\core\classes\DB.php on line 42` or on http://zamination-servers.org
This is happening in the core files.

**Comment by Cl1608Ho** [comment]
I experienced the same. You need to create that table on your own. 

What I did, to not have anything wrongly, was temporary copying line 115 of core/classes/Queries.php (which is about creating the table announcemens_pages) up to line 110 (in the if body, not the else). Then modify index.php (directly in the webroot) and insert `$queries->dbInitialise();' in line 50, directly after `require('core/init.php'`. Then open the forum once, then delete both lines you added. 

Why am I adding code within the page to do that, not just print you a sql statement to execute? Because I am not 100% sure what kind of Sql statement it should be, and I'm reusing the original code so nothing could be wrong.

**Comment by justin57754** [comment]
> Then open the forum once, then delete both lines you added.
Can you please elaborate? I do not know how to open the forum, it still shows the error on the website.

**Comment by samerton** [comment]
What happens when you navigate straight to **yoursite.com/admin/update_execute** and then try viewing your site?

**Comment by justin57754** [comment]
It just sends me back to the normal domain with the error.

**Comment by samerton** [comment]
Try replacing the contents of **pages/admin/update_execute.php** with [this code](https://gist.githubusercontent.com/samerton/269be2f93b2757424c04bd723bdd7ac0/raw/f05cf938e615a0e7101453a4237a3872cb9f9b55/update_execute.php), and try navigating to the same URL again.

**Comment by justin57754** [comment]
It worked but now I am getting this:

Notice: Undefined offset: 0 in K:\_webserver\XAMPP\htdocs\core\modules\Social_Media\initialisation.php on line 35

Notice: Trying to get property of non-object in K:\_webserver\XAMPP\htdocs\core\modules\Social_Media\initialisation.php on line 35

Fatal error: Call to undefined method DB::modifyColumn() in K:\_webserver\XAMPP\htdocs\core\classes\Queries.php on line 92

**Comment by samerton** [comment]
On which page do those errors appear?

**Comment by Fellings1** [comment]
@samerton Please check skype.

**Comment by justin57754** [comment]
I fixed the first 2 errors, just the last one now.


Fatal error: Call to undefined method DB::modifyColumn() in K:\_webserver\XAMPP\htdocs\core\classes\Queries.php on line 92

**Comment by justin57754** [comment]
That error only appears on the update execute page, the website is working now everywhere else.

**Comment by justin57754** [comment]
Now on the forum page it says this:

Notice: Trying to get property of non-object in K:\_webserver\XAMPP\htdocs\pages\forum\index.php on line 322

Notice: Trying to get property of non-object in K:\_webserver\XAMPP\htdocs\pages\forum\index.php on line 414

**Comment by samerton** [comment]
Looks like there was an issue with uploading the upgrade files somehow, if you replace the contents of **core/classes/DB.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/core/classes/DB.php) the issue should be resolved.

As for the issue on the forum page, that's simply a notice and it can be hidden by disabling error reporting in the AdminCP -> Misc tab.

**Comment by justin57754** [comment]
Now there is a blank tab in the AdminCP:

http://i.imgur.com/2bNuHzB.png

**Comment by samerton** [comment]
There'll be more missing files from the upgrade, it's best if you re-download the upgrade files from [here](https://worldscapemc.co.uk/nl_core/nl1/updates/1012.zip) and then simply reupload them.

How did you upgrade from 1.0.11 to 1.0.12?

**Comment by justin57754** [comment]
> How did you upgrade from 1.0.11 to 1.0.12?

I just dragged the files in and replace the existing ones.

**Comment by samerton** [comment]
I'm presuming there may have been issues when replacing the existing files, as it looks like it's just the files which should have been updated (as opposed to the new ones) which are causing issues.

**Comment by justin57754** [comment]
I'm going to update to 1.0.13 now.

**Comment by justin57754** [comment]
Everything is up to date and fixed! Thank you!
