### ISSUE TITLE
"This website use cookies to improve your experience" banner popup every time.

### ISSUE THREAD

**Issue by TheRealPear** [NamelessMC/Nameless#464]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.1.3
* How would you describe the issue? The blue banner always pop up when a user sign in, when loading the page and there is no option to disable that or move it.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? None.
* Do you have an idea how or where the issue occurs? Not really a issue.

**Comment by partydragen** [comment]
Currently there are no options to disable that cookie alert but it will be added in future,
for now you can remove lines 215-221 from core/init.php

**Comment by Fellings1** [comment]
@partydragen Thanks for the solution!

**Comment by TheRealPear** [comment]
Thank you, I'll keep that in mind
