### ISSUE TITLE
[Solved] 1.0.13 Update issue

### ISSUE THREAD

**Issue by MitesMC** [NamelessMC/Nameless#466]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Not sure if this is a bug or just an issue on my part.
* In which version of NamelessMC did it occur (1.x.x)?
Occurred when trying to update to 1.0.13
* How would you describe the issue? 
I had an older version of NamelessMC running. Noticed that there was a new version so I went ahead and tried to update as instructed. When trying to update to 1.0.13, after uploading the files, whenever I try to load any page it appears as blank. I wiped out the root directory and reinstalled in case something went wrong with my update attempt but the issue persists after successful reinstallation.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?

**Error log (after update and before reinstall):**
`[03-Nov-2016 10:07:28 Europe/London] PHP Warning:  require(core/init.php): failed to open stream: No such file or directory in /home/endrxyz/public_html/forum.mitecraft.com/index.php on line 48
[03-Nov-2016 10:07:28 Europe/London] PHP Fatal error:  require(): Failed opening required 'core/init.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/endrxyz/public_html/forum.mitecraft.com/index.php on line 48`

**Error log (after reinstall):** 
`[03-Nov-2016 11:29:40 Europe/London] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/endrxyz/public_html/forum.mitecraft.com/pages/install.php:49) in /home/endrxyz/public_html/forum.mitecraft.com/core/classes/Cookie.php on line 12`
* Do you have an idea how or where the issue occurs?
Not sure as I'm not keen with PHP and not sure what the error messages are trying to say.

**Comment by samerton** [comment]
Looking at your site since reinstalling, it looks like there is a permission issue; the cache directory needs to be recursively writable.

If you're running Ubuntu/Debian, try the command
`sudo chown -R www-data:www-data /var/www/html/cache`

**Comment by Fellings1** [comment]
@samerton Seems you have gave a reasonable solution to the issue. Ill close this for now feel free to comment down below for any further details and questions regarding the OP.

**Comment by MitesMC** [comment]
Sorry for the delayed response. I have gone ahead and did what @samerton advised. Made the cache directory writable but the issue still persists. No additional error logs appeared since the initial report.

**Comment by samerton** [comment]
@MitesMC Can you double check the permissions of the **cache/templates_c** directory, to ensure they're also writable?

**Comment by MitesMC** [comment]
@samerton I just made the mentioned directory writable but hasn't resolved the issue.

**Comment by MitesMC** [comment]
I hate to seem impatient or annoying but does anyone have any idea what's causing this? Would really wish to have the forum working. Thank you in advance!

**Comment by samerton** [comment]
Sorry for the late reply.

Can you try replacing **core/init.php** with [this code](https://gist.githubusercontent.com/samerton/fd43d734058acb611d51dfbaa5a473bb/raw/1ace90a184428069cfc7473726496ce938269037/init.php), in order to force-enable error reporting? Hopefully we'll get an error message being displayed on the page, or in the page source.

**Comment by MitesMC** [comment]
@samerton 
Here's what I got:
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'endrxyz_nmls.nl1_announcements_pages' doesn't exist' in /home/endrxyz/public_html/forum.mitecraft.com/core/classes/DB.php:42 Stack trace: #0 /home/endrxyz/public_html/forum.mitecraft.com/core/classes/DB.php(42): PDOStatement->execute() #1 /home/endrxyz/public_html/forum.mitecraft.com/core/classes/DB.php(104): DB->query('SELECT * FROM n...', Array) #2 /home/endrxyz/public_html/forum.mitecraft.com/core/classes/DB.php(134): DB->action('SELECT *', 'announcements_p...', Array) #3 /home/endrxyz/public_html/forum.mitecraft.com/core/classes/Queries.php(11): DB->get('announcements_p...', Array) #4 /home/endrxyz/public_html/forum.mitecraft.com/core/includes/template/header.php(54): Queries->getWhere('announcements_p...', Array) #5 /home/endrxyz/public_html/forum.mitecraft.com/core/includes/template/generate.php(9): require('/home/endrxyz/p...') #6 /home/endrxyz/public_html/forum.mitecraft.com/pages/index.php(106): in /home/endrxyz/public_html/forum.mitecraft.com/core/classes/DB.php on line 42
`
No idea what this means though as I'm not keen with php. Thank you for your help :)

**Comment by MitesMC** [comment]
Had a gut feeling it was a database issue based on the error message, gave reinstalling a quick try with a new database (I was using the old database). That solved the issue and things are working as intended now. Thank you so much for the help and cheers to the team!

**Comment by samerton** [comment]
Glad your issue is resolved! :)
