### ISSUE TITLE
[Question] NamelessMC Plugin

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#467]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.13
* How would you describe the issue? I read somewhere that the plugin will have some interesting features. For example, I saw on the AdminCP that there's rank synchronization with this so called plugin and that it requires a key. Is this plugin already made or in-dev?

**Comment by samerton** [comment]
The Nameless plugin is still a work in progress, unfortunately there's no estimated completion date at the moment.

**Comment by Fellings1** [comment]
@MuhsinunCool This is a good question that I have reason to believe that many people must be thinking.
Thanks for the good question!
