### ISSUE TITLE
cant reset password

### ISSUE THREAD

**Issue by Venomancy** [NamelessMC/Nameless#468]
### Template:
* What kind of issue is it (Question, Bug, etc.)? question
* In which version of NamelessMC did it occur (1.x.x)? most recent
* How would you describe the issue? i forgot the admin panel password, and i dont know how to reset it
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs? no

**Comment by mvilcis** [comment]
**New installation?**  
Can’t you just reinstall Nameless then?

**Existing installation?**  
Try resetting your password like a normal user.

**Comment by Venomancy** [comment]
It just says Please Re-Authenticate although I'm already logged in for the forums, how would I reset the admin panel? Plus I can't reinstall it because all my forums is done already. I found the MySQL database but it's encrypted on my password, anyway to just change that?

**Comment by mvilcis** [comment]
I see. Try this: Open an incognito window or just sign out. Try resetting your password like an ordinary user. Open the “Sign in” page and click the “Forgot password” link. Now, once you’ve reset your password, try to login again, and access the admin panel with that password you just added to the account.

Keep in mind that the MySQL database is encrypted for security reasons, therefore you cannot alter its records.

**Comment by Venomancy** [comment]
Worked! Thanks <3

**Comment by mvilcis** [comment]
@Fellings1 Can you close this issue?
