### ISSUE TITLE
[Suggestion] Switch away from Toastr to native browser notifications

### ISSUE THREAD

**Issue by CallMeMantas** [NamelessMC/Nameless#469]
This is a feature request for future versions of Nameless. So, you might be thinking: Why? What are the benefits of switching? Well…

- Browser notifications can be seen even if you’re focused on another tab or program. You don’t have to look at the tab or site to see that something new is happening.
- By using native browser notifications, that means Nameless doesn’t have to worry about creating any UI—the browser takes care of all that.
- Notifications are widely supported on all platforms, including mobile.
- The Notifications API is just plain easy to use. And you don’t need to use any libraries!

I see no reason to use toasts anymore.

**Comment by Fellings1** [comment]
Seems like a good suggestion. Ill leave @samerton to make that decision

**Comment by samerton** [comment]
I've stuck with Toastr for version 2, as I have some extra uses that I've implemented, however browser notifications can be used alongside. Thanks for the suggestion!

**Comment by samerton** [comment]
I've implemented browser notifications for version 2, which is not far off an initial pre-release :)
