### ISSUE TITLE
Change Homepage image

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#47]
Hi there,

Where's this image stored? http://prntscr.com/9bglsy Want to change it but can't find it.

**Comment by Toxic-Waste** [comment]
/var/www/html/core/assets/img

**Comment by HappyHarm** [comment]
Ah thanks but which one is the right one?

**Comment by Toxic-Waste** [comment]
background-1920x828

**Comment by samerton** [comment]
@Toxic-Waste is correct, you'll need to replace background-1920x828.jpg within /core/assets/img with an image of your choice.
