### ISSUE TITLE
Help with saving/uploading a NamelessMC version

### ISSUE THREAD

**Issue by darkkir3** [NamelessMC/Nameless#471]
So I did save my current NamelessMC version before doing an update. Since I was more than a few versions behind I got the latest build from github. However, when trying to recover my old save, i get an 500 error.  The apache2 error log doesnt state any issues. I know that this is most likely not a bug of NamelessMC and it is just me screwing things up.

**Comment by samerton** [comment]
There will probably be a large number of database changes which haven't been applied, as each individual update package from the AdminCP contains database patches. 
If you can let me know which version you had initially, and the version you've updated to, I can create a script to update the database for you in one go.

**Comment by darkkir3** [comment]
I was trying to update from 109 to the currently newest version. Thank you for the fast support.

**Comment by samerton** [comment]
I've quickly put together an upgrade script for you, if you create a new file named "upgrade.php" within the **pages** folder, and paste [this code](https://gist.githubusercontent.com/samerton/2bb2b40f334a338f007e9fde96b0e183/raw/20cc8fc8ea2ec893480c1ececbc46085678d421a/upgrade.php) within, you can head to yoursite.com/upgrade and hopefully the script will work.
It is untested though, and I highly recommend that you back up your database and files (if you haven't already).

**Comment by darkkir3** [comment]
Well, it seems to have something to do with the current configuration. Applying the old configuration seems to throw an 500 error. Using a blank one will obviously fail since the page can't create a database connection. I tried running the script, however it seems like i can not head to any page of NamelessMC without a 500 error whatsoever. Is there a template for the config.php of the newest version?

**Comment by samerton** [comment]
The configuration itself hasn't changed since version 1.0.0 was first released, as long as the connection details are the same there shouldn't be any issues there.

Can you try searching your server for the Apache error logs for the most recent errors? If you're using something like cPanel there should be an error log option within there.

**Comment by partydragen** [comment]
@samerton think so easy it was if we had Server Hosting like NamelessHosting
Then its possible to help people directly

**Comment by darkkir3** [comment]
Sadly i dont use any webpanel. However, those are the recent entries in the apache2 log (var/log/apache2/error.log):
http://hastebin.com/ibayexulim.pas

**Comment by samerton** [comment]
Unfortunately those errors don't seem to shed any light on the situation.

Can you try renaming the **upgrade.php** file you created within the **pages** directory to **install.php**, and then try navigating to yoursite.com/install? If you get a message saying the upgrade was successful, you can go ahead and delete the install.php file.

**Comment by darkkir3** [comment]
That actually worked. However it seems to throw some sql errors? o.o
http://hastebin.com/bizudafoku.sql

**Comment by samerton** [comment]
I've updated the [gist](https://gist.githubusercontent.com/samerton/2bb2b40f334a338f007e9fde96b0e183/raw/968a278c5f8785d2dcb44fa13202c5388c8ccd4b/upgrade.php), can you replace the contents of the install.php file with that code?

**Comment by darkkir3** [comment]
The script didnt throw any errors, however the 500 error still persists. Also I do not seem to get any errors on my log file.

**Comment by samerton** [comment]
Hopefully, replacing the contents of **core/init.php** with [this code](https://gist.githubusercontent.com/samerton/ccf74b29de40810394e7f8d18dc4b5f6/raw/df831764e0b82dafeef7a31807182c1df12a5cdc/init.php) should force errors to display on the screen.

**Comment by darkkir3** [comment]
It told me that my cache folder was not readable. After setting the perms correctly it seems to load now. However using the forums seems to display those errors: http://hastebin.com/gerujamuwa.pas

**Comment by samerton** [comment]
Those notices don't actually affect functionality, and can be hidden by reverting your **core/init.php** [back to normal](https://raw.githubusercontent.com/NamelessMC/Nameless/master/core/init.php), and ensuring error reporting is disabled in the AdminCP -> Misc tab.

**Comment by darkkir3** [comment]
It seems to work fine now. Thank you for your help :3
