### ISSUE TITLE
[Suggestion] Option to use only in-game registration

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless#473]
Suggestion: An option to disable the default registration in favor of a page instructing the user how to register in-game (using the new NamelessMC Plugin), including some minor details like ensuring they check their spam folder if they don't see their activation e-mail.

**Comment by samerton** [comment]
This is possible with the latest plugin dev builds (see the plugin repo for a link to the Jenkins), as registration can be disabled in the AdminCP -> Core -> Modules tab.
