### ISSUE TITLE
Please help a web

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#481]
Hello, I come from the Czech Republic and I have a problem with NamelessMC when basing on the forum topic and write a message there: česky 
It writes: ?esky 
Please advise me how to set it to not do this?

Here I give a photo : https://ctrlv.cz/vwbv

Here I set the table PhPMyAdmin : https://ctrlv.cz/ykwe

Web : netsword-server.tk

**Comment by samerton** [comment]
Works okay on my localhost ([image](http://i.imgur.com/UOCz2ox.jpg)), but not on the official Nameless site. I'll take a look to see what the cause is (also links with #344).

**Comment by samerton** [comment]
I've found the issue :)

To fix, head back into phpMyAdmin and edit your "nl1_custom_pages" and "nl1_posts" tables. Click "Operations", and beneath the "Collation" dropdown, tick the box saying "Change all column collations" and then click Go.

You'll need to edit your posts to fix the character, but you shouldn't experience the issue again.

**Comment by zikycz** [comment]
Hi, I'm here, I do not : "Change all column collations"

Photo : https://ctrlv.cz/DcJF

**Comment by samerton** [comment]
In that case, try:

- Edit the "content" column in the "nl1_custom_pages" table, and check the "Collation" field is utf8_czech_ci ([image](http://i.imgur.com/TXYyxom.jpg))
- Edit the "post_content" column in the "nl1_posts" table, and check the "Collation" field is also utf8_czech_ci ([image](http://i.imgur.com/hijxLhJ.jpg))

**Comment by zikycz** [comment]
It works, thank you

**Comment by samerton** [comment]
Glad to hear!

**Comment by DSArtyFixLife** [comment]
But... My friend writes me this - Já jsem to upravoval ve configech » I edited it in configs

**Comment by DSArtyFixLife** [comment]
But okay, I will try it.

**Comment by samerton** [comment]
@DSArtyFixLife 

If it doesn't work, I can only recommend asking your friend how exactly they fixed it as I don't know sorry.

**Comment by DSArtyFixLife** [comment]
So, thanks for support :) Im trying now it.

**Comment by DSArtyFixLife** [comment]
Wait, Im not good at mysql, It must be like that? 
![screenshot - 18_11 003](https://user-images.githubusercontent.com/33781032/32979843-b2ebe8a2-cc5c-11e7-808d-78cd6524aa5e.png)

**Comment by samerton** [comment]
@DSArtyFixLife Yes, that looks fine to me. Also make sure you do the same to the **nl1_posts** table.

**Comment by DSArtyFixLife** [comment]
O MY GOD! THANKS, YOURE AMAZING DEVELOPER!

**Comment by samerton** [comment]
@DSArtyFixLife No problem, make sure you edit posts which have the ? to get your character back :)

**Comment by DSArtyFixLife** [comment]
Yea, I see it, it dont replaces the "?" on posts, but I created my test post, and it works.

**Comment by samerton** [comment]
@DSArtyFixLife 

One more thing, if you create a new forum in the AdminCP and name it "Forum", you can then edit "Novinky" and set its "Parent Forum" option to "Forum". Then the forums will look a bit nicer :)

**Comment by DSArtyFixLife** [comment]
Hmmm... Thats good idea! I will try it.

**Comment by DSArtyFixLife** [comment]
And one little more question, if it always bugs in members, I must over edit it in mysql?

**Comment by samerton** [comment]
@DSArtyFixLife 

If you have the same problem with groups, then you must edit the **nl1_groups** table in phpMyAdmin, and change the `name`, `group_html` and `group_html_lg` fields to change their collation to `utf8_slovak_ci` too.

**Comment by DSArtyFixLife** [comment]
Thank so mutch.
