### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#483]
Hi How do I change the color groupky for groups that need Admin was at the red, but green.

**Comment by samerton** [comment]
Hi,

To do this, you need to change the "Group HTML" when editing the group in the AdminCP.

To change the admin colour from red to green, you can change the `<span class="label label-danger">` tag to `<span class="label label-success">`, in accordance with the [Bootstrap component variations](http://getbootstrap.com/components/#available-variations).

**Comment by zikycz** [comment]
Tanks
