### ISSUE TITLE
TeamSpeak3

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#484]
Hello, my TS3 does not understand why page

Photo : https://ctrlv.cz/RS0t

Pages photo : https://ctrlv.cz/XXpp

IP : 149.202.93.191:12353

IP : ts3.hicoria.com:12353

**Comment by samerton** [comment]
A time-out error is either due to incorrect ports (try double checking the virtual server port 9987), or if you're using web hosting they may have blocked external connections.

**Comment by zikycz** [comment]
Ok

**Comment by samerton** [comment]
I'll go ahead and close this issue, if you're still experiencing issues with the TeamSpeak query feel free to re-open.
