### ISSUE TITLE
Colour

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#486]
Hello, How do I adjust to my forum when I write something, so the font color to be what is in the photo:  https://ctrlv.cz/cKBP

**Comment by samerton** [comment]
Is this the font colour option you're referring to? http://i.imgur.com/Up0xKb7.jpg

**Comment by Fellings1** [comment]
@zikycz Could we have a response? Just so we can clear out the issues.

**Comment by samerton** [comment]
I'll mark this issue as closed, if you still have any questions feel free to re-open :)
