### ISSUE TITLE
Redundant access to forum permissions

### ISSUE THREAD

**Issue by Cl1608Ho** [NamelessMC/Nameless#487]
The edit group view in the admin panel should also show the permissions of the group to be edited for each forum and allow editing these permissions. This makes adding groups a lot less a hassle

**Comment by Fellings1** [comment]
Thinking this would be a suggestion we will take this into consideration. Thank you!

**Comment by samerton** [comment]
The upcoming v2 release separates the core module (which includes the group editor) and the forum module (containing forum permissions) so for the initial v2 pre-releases it won't be possible to simply attach forum permissions to the group editor.

This is something which makes perfect sense though, so I'll get this done at some point post pre-release.

**Comment by samerton** [comment]
I'm coming back to this much further into v2's development, and with a new permissions system coming up sadly this would only make things messier; having permissions attached to the forum editor makes more sense at this point.

I'll mark this as closed, hopefully when the new permissions system is ready you'll be able to see what I mean about how it'd become messy.
