### ISSUE TITLE
Help a web

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#489]
Hello, today I opened a website where I have installed NamelessMC and this give me what to do?

Photo : https://ctrlv.cz/C6Yl

**Comment by samerton** [comment]
It looks like you are missing some files, have you already installed Nameless?

**Comment by zikycz** [comment]
Somehow I missed you miss my files that I had already installed?

**Comment by samerton** [comment]
From that error, you are missing [this file](https://github.com/NamelessMC/Nameless/blob/master/core/init.php) from your website; if you haven't installed Nameless yet, try reuploading all files again.

**Comment by samerton** [comment]
Were you able to fix the issue @zikycz?

**Comment by zikycz** [comment]
No

**Comment by samerton** [comment]
I believe this is a host issue, I'll mark this as closed.
