### ISSUE TITLE
Web 

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#493]
Hello, how do takovoudle table to her players to fill out and submit, and I like to read it?

https://ctrlv.cz/gSAj

**Comment by samerton** [comment]
The upcoming version 2 update for Nameless will include a new custom form system, so you can create new applications for players to fill out and submit, and you will be able to read the applications in a much nicer layout.

**Comment by zikycz** [comment]
And it's been set up now? I need it

**Comment by masterdoctor** [comment]
@zikycz He means this release: https://github.com/NamelessMC/Nameless/milestone/4
You can track it's release at that link and I assume @samerton will issue a release date as it's about to arrive.
In short: No and it won't be released for a while (>2 weeks)

**Comment by samerton** [comment]
#205
