### ISSUE TITLE
šablona

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#494]
It is done to the background of falling snowflakes on a template?

**Comment by samerton** [comment]
The following steps will add snow to your website:

- First, download [this library](https://github.com/VincentGarreau/particles.js)
- Upload the file named **particles.min.js** to the **core/assets/js** folder
- Create a new file in the **core/assets/js** folder called **particlesjs-config.json**, and paste [this inside](https://gist.githubusercontent.com/samerton/15acb957e733ac95bdfcda00c62c688c/raw/b7f2c5ab707ba8a4a42fd1dc5f2f5d61d454108c/particlesjs-config.json)
- Edit **core/includes/template/scripts.php**, and just after the `?>` on line 17, add `<script src="/core/assets/js/particles.min.js"></script>`
- Also, within the same scripts.php file, add 
```
        particlesJS.load('particles-js', '/core/assets/js/particlesjs-config.json', function() {
            console.log('callback - particles.js config loaded');
        });
```
- Next, add this to the very top of **styles/templates/Template/navbar.tpl**: `<div id="particles-js"></div>`
- Finally, paste this to the bottom of **styles/themes/Theme/css/custom.css**:
```
#particles-js{
    position: fixed;
	
    top: 0;
    width: 100%;
    height: 100%;
}

.container {
    position: relative;
    z-index: 1;
}
```

**Comment by Lmmb74** [comment]
DAAMN DANIEL, but it would be awesome that this was integrated.

**Comment by Lmmb74** [comment]
Can not get it to work :/

**Comment by samerton** [comment]
@Lmmb74 what seems to be the problem? If you could send me a link to your site I can check it out.

**Comment by Lmmb74** [comment]
http://protonet.sytes.net/

**Comment by samerton** [comment]
@Lmmb74 Can you make sure you followed the third bullet point, and named the json file correctly?

**Comment by Lmmb74** [comment]
Ok

**Comment by Lmmb74** [comment]
Checked

**Comment by Lmmb74** [comment]
Check the page now XDDD

**Comment by Lmmb74** [comment]
Seems that the trouble was the white background :V

**Comment by Lmmb74** [comment]
Actually I set the script to be loaded like this:
`echo '	<script src="' . PATH . 'core/assets/js/particles.min.js"></script>' . PHP_EOL;`
just after the toastr.js script ;)

**Comment by Lmmb74** [comment]
Mmmmm, maybe I will make a fork just to add this as an option, where should it be set? I thought that adding an 'Enable Christmas?' option in the General Settings will do it.

**Comment by Fellings1** [comment]
Maybe a snowy background that can you can enable? @Lmmb74 

I was looking into that and seeing if Sam might consider it.

**Comment by Lmmb74** [comment]
Yup

**Comment by Fellings1** [comment]
@partydragen Has something of the sort on his Site I can look into how he did it.

**Comment by Lmmb74** [comment]
Yeah please :D

**Comment by samerton** [comment]
The problem with having an enable/disable button is that the snow effect depends on the template and any custom CSS that may be used, however it'd be possible in Nameless v2 to have a specific addon (however, it'd have to be developed specifically for one theme) which could do this.

**Comment by Lmmb74** [comment]
Or just adding the div in every theme but activating the script only if the option is enabled.

**Comment by Fellings1** [comment]
@Lmmb74  I dont think so.

**Comment by samerton** [comment]
I'll go ahead and mark this as closed, as in version 1 the only solution is to modify the template manually.

**Comment by Lmmb74** [comment]
U.u, ok
