### ISSUE TITLE
Block other users

### ISSUE THREAD

**Issue by Liphius** [NamelessMC/Nameless#495]
Is it possible to add a block feature in the upcoming releases?

So for example, you could block incoming PMs from another user by clicking on a "Block" button on their profile (perhaps something next to the "Follow" option?).

**Comment by Fellings1** [comment]
@Liphius I believe that this suggestion has been brought up before but Ill check to make sure if this is going to be implemented within an upcoming update.

**Comment by samerton** [comment]
Added in 6d84ae479bd940c857568a3067e783aa042bcd54
