### ISSUE TITLE
Ability to un-punish users from infractions

### ISSUE THREAD

**Issue by Chearful** [NamelessMC/Nameless#498]
As with other interfaces, I can always seem to find a way to unban/unmute a player from the web UI - I'd love to see this in Nameless.

I am currently using BungeeAdminTools.

Thanks!

**Comment by dangerORclose** [comment]
I think that this is more a part you need to discuss with the developer of that Plugin. 
I also want this for lite and, but as I said, I think you better contact that Plugin developer for this.

**Comment by Chearful** [comment]
There's this functionality already in BAT's (ugly) web interface; as far as I know it should just be a few simple SQL queries.

**Comment by MuhsinunCool** [comment]
I created an addon that does JUST what u want! :D I took the BAT Web Interface and then themed it to look like NamelessMC :D I submitted a pull request and I'm currently waiting on them to accept it :D

**Comment by Chearful** [comment]
Ayy, thanks! :1st_place_medal:

**Comment by MuhsinunCool** [comment]
Np! :D

**Comment by dangerORclose** [comment]
@Chearful Status update.
Thanks btw!
