### ISSUE TITLE
Infractions page takes ages to load

### ISSUE THREAD

**Issue by Adondriel** [NamelessMC/Nameless#499]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.15
* How would you describe the issue? 
The infractions addon: The page takes ~30seconds to load, each time, every time. 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
I can take a video if you want? I guess, lol.
* Do you have an idea how or where the issue occurs?
This may be tied to this page specifically, using a database that is not local to it. The database is on the MC server's hosting, while the website is on a different host. 
Using LiteBans plugin. 
I also have 2079 rows of bans, alone. Not even counting kicks.

**Comment by MuhsinunCool** [comment]
@samerton yes, please that would be great! Thanks!
