### ISSUE TITLE
[QUESTION]  Forum wider.

### ISSUE THREAD

**Issue by dangerORclose** [NamelessMC/Nameless#504]
http://prntscr.com/dqcxzc
How do i change my forum starting from the left?
So it gets a bit bigger. But still end at the righter side like it is now.

**Comment by samerton** [comment]
The only way to achieve this is to change line 1 of **styles/templates/*Template*/forum_index_latest_discussions.tpl** from `<div class="container">` to `<div class="container-fluid">`, although this would also change the right side of the page.

**Comment by samerton** [comment]
I'll mark this as closed as it can be customised through the template, if you're still experiencing issues feel free to re-open.
