### ISSUE TITLE
Voice server module TS3 - add support for SRV records

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless#506]
I am using the lastest version of NMC, but i know this was allready before an issue so i report it now once again here so it can gets fixed for a next update hopply.

The issue is when you fill in the info for the ts3 server it shows only the main ip on the homepage.
When you press join it connects you to that ip with the port 10011. Even when you change the port.

Thats issue 1 about that, but i have a srv for my teamspeak server.
And when i put the srv as ip and then the ports correct, i get this yellow error. 
**php_network_getaddresses: getaddrinfo failed: No address associated with hostname**

**Comment by samerton** [comment]
Sorry for the nearly 9 month old reply, were you ever able to resolve this @dangerORclose?

**Comment by dangerORclose** [comment]
No none.

**Comment by dangerORclose** [comment]
No solution found*

**Comment by samerton** [comment]
I'd imagine the query used is not compatible with SRV records, if you try the IP address directly does it work?
