### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by PeterEstephan** [NamelessMC/Nameless#51]
I was just updating from an older version of the pre-release, when after I put in all my database info i get this fatal error: 

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in C:\xampp\htdocs\core\classes\DB.php:68 Stack trace: #0 C:\xampp\htdocs\core\classes\DB.php(68): PDOStatement->execute() #1 C:\xampp\htdocs\core\classes\DB.php(167): DB->createQuery('INSERT INTO nl1...', Array) #2 C:\xampp\htdocs\core\classes\Queries.php(42): DB->insert('groups', Array) #3 C:\xampp\htdocs\pages\install.php(309): Queries->create('groups', Array) #4 C:\xampp\htdocs\index.php(33): require('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\core\classes\DB.php on line 68

Im not 100% sure on what is wrong with it updating. 

Thanks.

**Comment by samerton** [comment]
If you're updating from one older pre-release version to a newer one, you don't need to run the installer again, you simply need to replace all files other than the installer. Deleting pages/install.php should fix this, you may experience some data duplication however.

**Comment by PeterEstephan** [comment]
So I would pretty much update all my /core/ files (not the database and email configuration files) and all the /pages/ files with the new files required? Or would I replace everything (except for the database and email config files) but delete the install.php file? 


Thanks.

**Comment by samerton** [comment]
The easiest way would be to replace everything other than core/config.php and core/email.php and delete pages/install.php

**Comment by PeterEstephan** [comment]
Alright Ill give that a shot, thanks.

**Comment by PeterEstephan** [comment]
Thanks, It worked.

**Comment by samerton** [comment]
No problem, glad it's working now.
