### ISSUE TITLE
Support sub directory

### ISSUE THREAD

**Issue by Maximvdw** [NamelessMC/Nameless#514]
Support installation on a sub directory such as /forum .. etc..

Currently the site breaks with a
http://i.mvdw-software.com/2017-01-03_20-45-46.png

**Comment by samerton** [comment]
Unfortunately, fixing this issue for v1 would require modifying every link in the package, however the upcoming version 2 release (currently in pre-release stage, [repo can be found here](https://github.com/NamelessMC/Nameless/tree/v2)) fully supports subdirectory usage.

The only v1 workaround is to point a subdomain to the subdirectory.

**Comment by Maximvdw** [comment]
Sorry, wasn't aware this was fixed in 2.0
