### ISSUE TITLE
Usage of REST API conventions

### ISSUE THREAD

**Issue by Maximvdw** [NamelessMC/Nameless#515]
Concerning "GET"ting a user
http://i.mvdw-software.com/2017-01-03_20-55-25.png

It isn't very logical to use a POST request to GET a user.
REST api conventions should require this to be a get request.

Too make this more like the REST api conventions I would change the following:

1. Make the "getting" of a user a GET request
2. To "put" the user a in different group use the PUT request

**Comment by Maximvdw** [comment]
The 2. is a vague one. A lot of REST API's will make this a POST as well. But the 1st one seems a bit out of place

**Comment by Maximvdw** [comment]
Also I don't see any docs for v2, so I assume this still applies to v2?

**Comment by Maximvdw** [comment]
A few other notes I have on the API conventions is the response data. Instead of having
a "error":true and "success":true
I would use either of those and set it to true or false. Now a developer has to do 2 checks before actually knowing if the result is positive or false
http://i.mvdw-software.com/2017-01-03_21-22-12.png

**Comment by partydragen** [comment]
Oh hey @Maximvdw :P You goes to use this API since your here? :P what u planning

will get @Samerton to take a look at this

**Comment by Maximvdw** [comment]
Yeah, creating a quick module for my QAPlugin to ask the assistant to report users, register ,etc...

Another note:
http://i.mvdw-software.com/2017-01-03_21-33-07.png
The "response" should not be JSON inside a "message" this won't be parsed by JS, PHP or JSON.org (used in spigot) meaning you basically have to parse it an extra time

**Comment by IsS127** [comment]
Hey If we have a namelessplugin in DEV. 
If you want to check it out how we access the api feel free to. https://github.com/NamelessMC/Nameless-Plugin
We Will also make a api plugin/library soon.

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/wiki/v2-API-(draft)
