### ISSUE TITLE
Allow formatting/new lines in report content

### ISSUE THREAD

**Issue by Maximvdw** [NamelessMC/Nameless#516]
Allow the usage of a formatting such as BBCode, ... in report content API
HTML is sanitized (what is good) so `<br>` can't be used.
But \n is not translated to `<br>` as well (what would be an easy fix)

This would make formatting more easier
![](http://i.mvdw-software.com/2017-01-04_00-21-41.png)

As you can see in the above image I want to include meta information about a report, but this is on the same line, making it hard to read

**Comment by samerton** [comment]
Thanks, I'll modify the report system to allow the use of \n

**Comment by Maximvdw** [comment]
Another option would be http://us2.php.net/strip_tags
that way you can enable HTML formatting limited to specified tags such as `<b>` `<br>` `<u>`

**Comment by samerton** [comment]
There is a purification library used within Nameless to remove potentially harmful HTML tags whilst keeping  tags such as <br />, <strong> etc, however it's currently not used within reports. 

I could add this if you think HTML would be a better option than \n

**Comment by samerton** [comment]
There is a purification library used within Nameless to remove potentially harmful HTML tags whilst keeping  tags such as `<br />`, `<strong>` etc, however it's currently not used within reports. 

I could add this if you think HTML would be a better option than \n

**Comment by Maximvdw** [comment]
Would def. allow for more formatting. Bold can always be handy

**Comment by samerton** [comment]
I've taken a quick look, and the use of HTML in report content should already be already permitted in v1. I've also added support for `\n` in the latest commit (55897ba50129feb8109a60f3cd76fa1b4a9988a2).

**Comment by Fellings1** [comment]
Solved?

**Comment by samerton** [comment]
I'll double check HTML works as planned through the API first, if so hopefully the issue is resolved.

**Comment by Maximvdw** [comment]
will try tonight

**Comment by samerton** [comment]
I'll mark this as closed, v1.0.16 will support both \n and basic HTML in reports created through the API.
