### ISSUE TITLE
Signature Characters Bug

### ISSUE THREAD

**Issue by PeterEstephan** [NamelessMC/Nameless#52]
When I am making my signature under the profile control panel or admin control panel I get an error saying "Signature must be a maximum of 256 characters." But I am using less than 256 Characters. 
This is what im trying to put: http://postimg.org/image/y8tophiub/
And the error im getting: http://postimg.org/image/qg6hn0nhx/

Im not too sure whether the problem is simply text being centered or what value emojis have on themselves. 

Thanks.

**Comment by samerton** [comment]
This issue is due to the HTML tags for the image and the centred text being close to/more than 250 characters. I'll look into it.

**Comment by PeterEstephan** [comment]
Alright Thanks. 

Is there anything I could change to make the characters limit more than 250 for now or would it have no effect on the character limit?

Thanks.

**Comment by samerton** [comment]
For now you can edit **pages/user/settings.php** and change line 34 to

					'max' => 1000

and also **pages/admin/users.php** and change line 381 to

										'max' => 1000

You can change 1000 to whatever limit you want.

**Comment by PeterEstephan** [comment]
Alright Thanks for your help!
