### ISSUE TITLE
[Suggestion] Translation for Installation page

### ISSUE THREAD

**Issue by dgateles** [NamelessMC/Nameless#520]
Make possible translate installation page.

**Comment by Headhunterzpw** [comment]
This is inpossible because of the nature how the system translates the system because of the variable which language should being used is saved in the database

**Comment by dgateles** [comment]
This is possible adding a language selector on installation start page.

**Comment by Headhunterzpw** [comment]
@dgateles And how would you save it? There are no tables that can save that information before the installation is completed. Or you need to hardcode the language which might reset after every update

**Comment by dgateles** [comment]
JS can make it easy

**Comment by Headhunterzpw** [comment]
It could be a cookie but I don't know how to store that..

**Comment by samerton** [comment]
It can be done through a session variable, I'll look into it for the full v2 release.

**Comment by rodymol123** [comment]
This can easily be achieved if https://github.com/NamelessMC/Nameless/pull/563 is merged. Since the views and logic are somewhat seperated it would be possible to create a language folder at ```core/installation/languages``` and load those into the new views.

**Comment by samerton** [comment]
Added in b65f6d63c66e0d949de4ff0aeb7b478e81876d84
