### ISSUE TITLE
[SUGGESTION] Social media login/register

### ISSUE THREAD

**Issue by dangerORclose** [NamelessMC/Nameless#526]
Can you allow players to log in and or registrer with there social media like facebook and twitter?
Becouse they never understands that after they register they need to go to there mail and click it.
And this is the solution in my part to it and to let them log in very fast.
And maybe direct integrated to ask to like the facebook page of the server too.

**Comment by Fellings1** [comment]
So an integration with those social media to sign in? @dangerORclose

**Comment by samerton** [comment]
This is a planned addition for some point after v2's full release, see #451 
I'll mark this as closed so we can use that issue for discussion :)

**Comment by Fellings1** [comment]
@samerton Added it to the milestone!
