### ISSUE TITLE
Converting from XenForo Error

### ISSUE THREAD

**Issue by Faicu** [NamelessMC/Nameless#528]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.15.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.
Ok, so, I have latest nameless version.
PHP 7.0
I get this error:
http://prntscr.com/dvn0qc
I get this when I install namelessmc and I select yes at converting.

**Comment by Derkades** [comment]
Is this issue still relevant?

**Comment by samerton** [comment]
A v2 converter still needs to be created

**Comment by Derkades** [comment]
#877
