### ISSUE TITLE
Issues with namelessmc 2.0

### ISSUE THREAD

**Issue by TheSander562** [NamelessMC/Nameless#531]
* What kind of issue is it (Question, Bug, etc.)?
Bugs
* In which version of NamelessMC did it occur (1.x.x)?
2.0 prerelease 1
* How would you describe the issue? 
There is a bug at AdminCP -> Core -> Reactions.
If you want to edit or create a new reaction with a negative type, you cant save it.
The others do work.
And at the registration page, the terms and conditions doesnt work.

**Comment by samerton** [comment]
I'll take a look into negative reactions not creating now.

As for the terms and conditions not working, this is something I haven't yet implemented, along with the contact page.

**Comment by TheSander562** [comment]
Thank you, it works now.

**Comment by samerton** [comment]
Terms and conditions added in 68ceddc556eae500416360946dfcbef112b4cffb
