### ISSUE TITLE
Website maintenance mode?

### ISSUE THREAD

**Issue by DaedalusPrime97** [NamelessMC/Nameless#533]
Hi,

I don't know if this is the right section to place this in, but I was wondering would it be a coll features that you could put the website in maintenance mode? So for example when you put in the link of your website, that you will get a page with (This website is under construction, maintenance etc?) 

Thank you :)

**Comment by jesseke55** [comment]
You can also create a index.html with a text that its in maintenance?

**Comment by Awtra** [comment]
Seems like I good idea. But as the user said above it is able to be done via the index.html. Let me know if you need anything else @DaedalusPrime97 .

**Comment by samerton** [comment]
Added in 7e0eeddb8adb407b9f87d51289753a8458de122c
