### ISSUE TITLE
Bug tracker

### ISSUE THREAD

**Issue by tomf42** [NamelessMC/Nameless#534]
Can you add BugTracker? It is page, where players can report bugs. I thing it is very useful for servers.

**Comment by jesseke55** [comment]
There is a option called: Create a forum.

I believe that a forum would be more efficient and takes less time to maintain

**Comment by Awtra** [comment]
@tomf42 I would agree with the user above. You are able to create sub categories in which users are able to submit bugs.

**Comment by samerton** [comment]
It's always a possibility that a bug tracker can be implemented in the form of an optional module in the future, however it'd be at some point after the v2 release.

**Comment by samerton** [comment]
Added in 4b97d2523ffc936a4ce82e422947b6f5e56ed0ae, credit @relavis
