### ISSUE TITLE
[Suggestion] More Forum Post Abilities

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#535]
* What kind of issue is it (Question, Bug, etc.)? Suggestion
* In which version of NamelessMC did it occur (1.x.x)? 1.0.15
* How would you describe the issue? I would like a few new abilities to create a more intuitive forum posting interface. I would like the ability to add attachments to the post & put a calendar in the post. Any & all extra features would be amazing. Thanks! :D
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No
* Do you have an idea how or where the issue occurs? No

**Comment by Derkades** [comment]
I think @samerton would rather not have to code a file uploader if he doesn't have to. Ask your users to use links to e.g. dropbox or google drive for attachments, it will save on storage and bandwidth as well. For pictures just upload to imgur and insert an image.
