### ISSUE TITLE
How To Edit Pagination

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#538]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 2.0.0 pr1
* How would you describe the issue? Where are the files for the code for the pagination stored? I need the change the look of the pagination for my template. Thanks!

**Comment by samerton** [comment]
If it's just the pagination CSS you need to change, simply override Bootstrap's pagination classes.
Otherwise, if you need to change the actual HTML, you can find it in **core/includes/render.inc.php**.

**Comment by MuhsinunCool** [comment]
It's HTML, thanks! :D <3

**Comment by MuhsinunCool** [comment]
@samerton just realized that core/includes/render.inc.php isn't part of the template... I just want to edit the html for my template... :c

**Comment by samerton** [comment]
Unfortunately it's only possible to modify it globally (same goes for v2 at the moment, hopefully this will have changed for the full v2 release).

**Comment by MuhsinunCool** [comment]
Yea, I'm trying to make the template for NMC v2 :/ alr well ty anyways :/

**Comment by MuhsinunCool** [comment]
Has this been resolved?

**Comment by Derkades** [comment]
I thought your question had been answered (not possible to modify globally)

**Comment by MuhsinunCool** [comment]
The other way around. I was told it can only be modified globally. I was wondering if that was fixed.

**Comment by samerton** [comment]
Now possible in v2 after e9178adff513726bfe8f5b93fe2912f89d8f12db and 70c043269a4bcf416f1c0903dcea07e61508f483, using the $template_pagination array

**Comment by MuhsinunCool** [comment]
Thanks!
