### ISSUE TITLE
404 After install

### ISSUE THREAD

**Issue by iOnixS** [NamelessMC/Nameless#54]
Hey, when I install Nameless, I get a 404, no matter what page I go to. Please fix, thankies c;
http://prntscr.com/9miliw

**Comment by samerton** [comment]
Hi,

Have you installed Nameless within the root directory of your websever, for example "/var/www/html"?

**Comment by iOnixS** [comment]
http://kittyforums.co.uk/s/

**Comment by samerton** [comment]
The fact it's installed within a subdirectory will be the issue here. It's possible to use Nameless with a subdomain though,.

If you're using a host with cPanel, you'll simply need to set one up within the "Subdomains" page of the panel.

If you're hosting it on your own VPS/dedicated machine, [these instructions](http://askubuntu.com/a/463623) should help you out (Ubuntu).

**Comment by iOnixS** [comment]
Yeah, I use cPanel. So make a registered subdomain and install it there?

**Comment by samerton** [comment]
Simply create a new subdomain and point it to your /s/ folder, and it should work.

**Comment by iOnixS** [comment]
Thanks, I'll try that now.

**Comment by iOnixS** [comment]
Nope, nothing. "404"

**Comment by samerton** [comment]
Here's my cPanel subdomain setup: http://i.imgur.com/6KzGlYF.jpg

Nameless was installed in the "public_html/demo" folder, where the subdomain points to, and worked perfectly when you navigated to demo.worldscapemc.co.uk, but not worldscapemc.co.uk/demo.

This isn't actually an issue with Nameless itself, it's designed to work in either the root directory or a subdomain as it's a standalone system.

**Comment by iOnixS** [comment]
That still doesn't work .-.

**Comment by samerton** [comment]
Unfortunately, I'm out of ideas. As it's a server configuration issue, there's not much I can do for the time being.

**Comment by samerton** [comment]
I'm going to go ahead and close this issue as it's not an issue with Nameless itself, it's intended design for the time being.
