### ISSUE TITLE
404 issue when going to my website

### ISSUE THREAD

**Issue by TheSander562** [NamelessMC/Nameless#540]
What kind of issue is it (Question, Bug, etc.)?
Bugs
In which version of NamelessMC did it occur (1.x.x)?
2.0 prerelease 1
How would you describe the issue?
If i go to my website or any page of it, you get the 404 error, website: http://holocraftium.pe.hu/
Do you have an idea how or where the issue occurs?
If you go to any page even the index you get the 404 error.

**Comment by samerton** [comment]
Have you moved your website between folders at any point? If so, you'll need to change the "path" config value (in **core/config.php**), as your website is in the main directory it'll need to be set to `""`.

**Comment by TheSander562** [comment]
"core" => array(
        "path" => "",
        "friendly" => true
    )
this is what it looks like, but it was already this when I got the error.

**Comment by samerton** [comment]
Can you try changing `friendly` to false?

**Comment by TheSander562** [comment]
okay changed it and the homepage works yeey, but if i want to go to example the login page it says the 404 error.

**Comment by TheProKiller756** [comment]
Have you uploaded the .htacess file?

**Comment by TheSander562** [comment]
![image](https://cloud.githubusercontent.com/assets/14059770/22790461/946ac82a-eee6-11e6-94b1-8f40fb7c5c7a.png)

Yes i have uploaded the htacces file. (look at the right), but how do i check if the server has acces to it?

**Comment by samerton** [comment]
The .htaccess file isn't the issue if you have `friendly` set to false. 
I really can't think what the problem could be at the moment, has the website always done this, and if not what did you change which could have led to the problem?

**Comment by Headhunterzpw** [comment]
Check your apache error logs that you can view: /var/log/apache2/error.log to see whats wrong.

**Comment by TheSander562** [comment]
@samerton the website worked a few weeks ago, then i didnt do anything for a long time and now i get this, but i didnt change anything.
@Headhunterzpw how can i check apache logs if im on a hosting website?

**Comment by Headhunterzpw** [comment]
@TheSander562 Which control panel do you have? cPanel?

**Comment by TheSander562** [comment]
@Headhunterzpw i have hostinger webhost, so i dont think so, but i dont know for sure

**Comment by Headhunterzpw** [comment]
On hostinger it should work fine.. Check the .logs folder when you are in / of your FTP

**Comment by TheSander562** [comment]
will look at it now, should i send you the file?

**Comment by Headhunterzpw** [comment]
Well your best bet is to contact their support about it because they might give you the log for your site

**Comment by TheSander562** [comment]
okay will do it now.

**Comment by IsS127** [comment]
dont delete cache.

**Comment by Headhunterzpw** [comment]
If you delete cache the site would break because it will being impossible to cache data

**Comment by TheSander562** [comment]
I have just reset the website, and now i have one last question. Why does my hostinger say that the rescource limit is exceeded? If i use namelessmc 1.0.15 it doesnt say that. If i look at the network tab from the developer tools from my browser i can see that pms.php and alert.php are constantly querying(dont know if this is the right word to say this). How can i resolve this?

**Comment by TheProKiller756** [comment]
Thats because in  hostinger free plan usually happens this because you're using a lot of recourses and exceding the limit,I recommend you pay a hosting or search another free hosting like viewsocial.es or hostminio.es

**Comment by IsS127** [comment]
Or you could use namelesshosting Thats free.

**Comment by Headhunterzpw** [comment]
Yea use namelesshosting or get a VPS or a paid webhosting

**Comment by samerton** [comment]
It looks like I kept the PM/alert query interval really low after doing some testing a while back, I've increased them back up to the original 20 seconds so hopefully things should be a bit better now. 
If you want to apply the necessary changes now, before the next pre-release, you can find the related commit here: fbd769fde378f58953880df8497a7004d31a819c

**Comment by TheSander562** [comment]
okay thank you all, it's all working great again.
