### ISSUE TITLE
Databaze

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#541]
Help : https://ctrlv.cz/mZdD

**Comment by samerton** [comment]
It looks like your web host does not support the InnoDB storage engine for MySQL, which is required by Nameless at the moment.

**Comment by zikycz** [comment]
Oh, and how to solve it? Not in some old version NamelessMC normal MYSQL so I can connect.

**Comment by samerton** [comment]
Nameless has always used the InnoDB engine for MySQL, so this must be down to host configuration. 
If you're using shared hosting, I can only recommend asking them about the InnoDB MySQL engine.

**Comment by zikycz** [comment]
Fuck. :D

**Comment by samerton** [comment]
I'll close this to stick with #546
