### ISSUE TITLE
When i download the .zip i dont get the install ?

### ISSUE THREAD

**Issue by NoelBank** [NamelessMC/Nameless#544]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.15.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by NoelBank** [comment]
Ps i dont get the install **

**Comment by Headhunterzpw** [comment]
https://github.com/NamelessMC/Nameless/releases/tag/v1.0.15

Have fun ;)

**Comment by samerton** [comment]
There is in installation file provided, and Nameless will load it provided your server is correctly configured. If you're getting a not found error, you'll need to follow the steps provided [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) to correctly configure your server.

**Comment by samerton** [comment]
I'll close this and use #547
