### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#546]
When your system does not use InnoDB database, I want a normal database, I've used before. Please consult your me what to do.

**Comment by samerton** [comment]
Nameless has always used InnoDB as its database engine, may I ask which web host you are using?

**Comment by zikycz** [comment]
I use a hosting Endora.cz, but there must be bought InnoDB

**Comment by zikycz** [comment]
And it would not somehow be converted into a normal Mysql, earlier it worked

**Comment by samerton** [comment]
InnoDB is the "normal" MySQL engine (it's the standard), however some free web hosts block it as an incentive to get users to upgrade to their paid plans, seeing as it's used so frequently. I can look into adding an option to change the database engine for v2.

For now, if you're looking to stick with free hosting, you can either:
- edit [lines 112-150](https://github.com/NamelessMC/Nameless/blob/master/core/classes/Queries.php#L112-L150) of **core/classes/Queries.php** and replace every single ocurrance of `InnoDB` with `MyISAM`, or
- use [NamelessHosting](https://namelesshosting.com/), which allows you to host free Nameless websites
