### ISSUE TITLE
I need help i dont get the install.php!

### ISSUE THREAD

**Issue by NoelBank** [NamelessMC/Nameless#547]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.15.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by Headhunterzpw** [comment]
Its build in and you aren't telling us what did you do and such... for fuck sake

**Comment by NoelBank** [comment]
Look at that http://noelbank.de/Nameless/ <----

**Comment by Headhunterzpw** [comment]
Did you read the installation guide?

**Comment by NoelBank** [comment]
yes

**Comment by NoelBank** [comment]
i put that on my VPS an open it at web more not

**Comment by Headhunterzpw** [comment]
Nameless should being installed in the root directory of your website.

**Comment by NoelBank** [comment]
no in the Nameless.

**Comment by NoelBank** [comment]
but i dont get the install.php or the install directory

**Comment by Headhunterzpw** [comment]
It should being installed onto a root part of the domain otherwise it will not work. And also enable mod rewriting.. Which OS do you have?

**Comment by NoelBank** [comment]
Debian 8

**Comment by NoelBank** [comment]
that my root part /var/www/wordpress an i made it /var/www/wordpress/Nameless

**Comment by Headhunterzpw** [comment]
It should be in /var/www/wordpress Or create a subdomain with virtualhost to run nameless onto it.

**Comment by NoelBank** [comment]
And how do I do it? And I still lack the install folder

**Comment by NoelBank** [comment]
look at that pls : http://noelbank.de/Nameless/install?step=requirements 👎

**Comment by Headhunterzpw** [comment]
http://bfy.tw/A28P

**Comment by NoelBank** [comment]
wow, thats help me not enought.

**Comment by NoelBank** [comment]
Sorry vor my bad English i'm a german

**Comment by Headhunterzpw** [comment]
It tells you how to search: How to create a virtualhost on debian 8 because you don't have enough knowledge to use linux and to host a website at all... Please learn that before you are doing that. Host your website on a webhosting to prevent those issues.

**Comment by NoelBank** [comment]
http://37.114.62.186/   <--- My Test Server i install it

**Comment by Headhunterzpw** [comment]
Install php and it looks like you don't know enough about linux.. This is just a basic thing that the most medium experienced system administrators and linux users know

**Comment by NoelBank** [comment]
but i can install the 2.0 pre is any diffrent??

**Comment by Headhunterzpw** [comment]
You will still get the same error if you didn't follow the right steps and tips that I gave you

**Comment by NoelBank** [comment]
no the 2.0 Has worked great

**Comment by NoelBank** [comment]
look in the root but agains http://37.114.62.186/install?step=requirements

**Comment by Daf4Life** [comment]
@NoelBank Follow the steps that @Headhunterzpw gave you :)

**Comment by Headhunterzpw** [comment]
It works fine for me on my VPS and cPanel server.

**Comment by NoelBank** [comment]
@daf4life i made it

**Comment by NoelBank** [comment]
https://gyazo.com/323544e9133a1a0aafdd12dce0385e0b

**Comment by NoelBank** [comment]
I just follow the steps from `https://www.youtube.com/watch?v=BlRz9gpS-Ew`

**Comment by NoelBank** [comment]
and from `https://github.com/NamelessMC/Nameless/wiki/Installation`

**Comment by Headhunterzpw** [comment]
You have this issue: https://www.i.jessegeerts.nl/2017-02-11_18-50-41.png

**Comment by NoelBank** [comment]
nope

**Comment by Headhunterzpw** [comment]
Did you enable mod_rewrite?

**Comment by NoelBank** [comment]
I am missing the install directory after downloading the rest fits

**Comment by samerton** [comment]
You are missing the `.htaccess` file from your /var/www/html folder, try creating one and paste [this](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess) inside.

If, even with the .htaccess file there, you are still getting the error, you will need to configure your server to allow the use of Apache's mod_rewrite and htaccess files as @Headhunterzpw says.

**Comment by NoelBank** [comment]
but my website noelbank.de fits very good an my pannel noelbank.de/pan an my Music bot too noelbank.de:8087

**Comment by Headhunterzpw** [comment]
The install file is placed in a directory that can only being reached if the .htaccess file is in use and mod_rewrite enabled

**Comment by Headhunterzpw** [comment]
Nameless works in a different way then your music bot and panel.

**Comment by NoelBank** [comment]
thats right but i dont have the install directoy not!!! I think that is the problem

**Comment by NoelBank** [comment]
I just add that from  @samerton 
and it work not -.-

**Comment by Headhunterzpw** [comment]
Its a file. And did you restart apache too to see if that would help?

**Comment by Headhunterzpw** [comment]
I did a nasty workaround on your site... http://noelbank.de/Nameless/?step=requirements

Remove the install part

**Comment by NoelBank** [comment]
i dont hav any install part!1!

**Comment by Headhunterzpw** [comment]
Remove the install part from the URL -______-

Use your brain or just let setup someone else for you.

**Comment by samerton** [comment]
I can assure you the install file is definitely there, it can be found in the **pages** folder. 
It **must** be in the pages folder to work; if you take it out of there, it won't work correctly.

The version 2.0 pre-release 1 will work without changing anything, so you can either try that (although it is probably quite buggy and missing features), or the guide [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) will tell you how to modify your server so Nameless v1 works on there. 
If you don't want to modify the server configuration yourself, feel free to send me a private message over on Spigot (my profile is [here](https://www.spigotmc.org/members/samerton.10676/)).

**Comment by Headhunterzpw** [comment]
@samerton It won't work without a proper rewrite rule.

**Comment by samerton** [comment]
@Headhunterzpw By default, v2 has friendly URLs disabled and it doesn't use the htaccess file, which is an optional setting in the AdminCP.

**Comment by NoelBank** [comment]
okay okay okay stop i dont can follow what have i to do?

**Comment by NoelBank** [comment]
in my .htacces is 
`# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
  Options +FollowSymLinks
  Options -Indexes
  RewriteEngine On

  RewriteCond %{SCRIPT_FILENAME} !-d
  RewriteCond %{SCRIPT_FILENAME} !-f

  RewriteRule ^.*$ ./index.php`

**Comment by Headhunterzpw** [comment]
You need a .htaccess from the nameless repository into the Nameless folder.

**Comment by samerton** [comment]
Nameless v1 won't work alongside Wordpress, if you don't actually have Wordpress installed remove everything from that file up until `### END WordPress`

**Comment by NoelBank** [comment]
okay i delete evrything from Wordpress but i get agans error 400

**Comment by Headhunterzpw** [comment]
@NoelBank https://www.lifewire.com/how-to-fix-a-400-bad-request-error-2617988

**Comment by NoelBank** [comment]
@Headhunterzpw im mean 404

**Comment by samerton** [comment]
The only way you can fix the 404 is to follow [these steps](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc), or contact either myself or @Headhunterzpw to configure your server for you.

**Comment by NoelBank** [comment]
Okay im in `/var/www/wordpress/Nameless` and then i open `.htaccess` and add 
`  Options +FollowSymLinks
  Options -Indexes
  RewriteEngine On

  RewriteCond %{SCRIPT_FILENAME} !-d
  RewriteCond %{SCRIPT_FILENAME} !-f

  RewriteRule ^.*$ ./index.php`
And its works not for me

**Comment by NoelBank** [comment]
i put the nameless site to root and its works not [LINK](noelbank.de)

**Comment by Headhunterzpw** [comment]
Issue not found.

**Comment by Headhunterzpw** [comment]
Best workaround: https://www.i.jessegeerts.nl/2017-02-11_19-21-58.gif

**Comment by NoelBank** [comment]
Yes i dont know can you help me to setup an system?

**Comment by NoelBank** [comment]
wow thanks <3 <3 <3 <3 <3 <3 <3 <3 <3

**Comment by Headhunterzpw** [comment]
That gif would show the "best" way to have it as a temporaily workaround of this issue
