### ISSUE TITLE
install

### ISSUE THREAD

**Issue by bluesksksk** [NamelessMC/Nameless#55]
hello i wanna to use your system for my server but when i want to install system it show me this

https://ctrlv.cz/shots/2016/01/08/740N.png

and when i do /pages/install.php it says this

https://ctrlv.cz/shots/2016/01/08/58Ll.png

CAN YOU HELP ME PLEASE

**Comment by samerton** [comment]
You'll need to move the files up one directory, so it's out of the "website" folder and moved into the root directory.

**Comment by bluesksksk** [comment]
i dont understant

**Comment by HappyHarm** [comment]
@bluesksksk You have put your files in rootsiteexample/website/ Just put them in /rootsiteexample (so one folder up).

**Comment by bluesksksk** [comment]
yes i have it on my vps /var/www/html and still this error

**Comment by bluesksksk** [comment]
you can try http://185.91.116.223/

**Comment by HappyHarm** [comment]
http://prntscr.com/9nmb8v What's not working?

**Comment by HappyHarm** [comment]
Oh nvm, give the right file permissions to install.php

**Comment by bluesksksk** [comment]
https://ctrlv.cz/50rG

**Comment by bluesksksk** [comment]
i have and nothing

**Comment by bluesksksk** [comment]
some help?

**Comment by bluesksksk** [comment]
i try to move install.php from pages to index.php and it show system req.. and i click on next step and nothing show just white you can try it http://185.91.116.223/

**Comment by HappyHarm** [comment]
Does the file /html/pages/install.php exists? If not, redownload and upload all the files.

**Comment by bluesksksk** [comment]
yes but i now try to upload new version 1.0.1 i hope it help

**Comment by bluesksksk** [comment]
dont help me to update version

**Comment by bluesksksk** [comment]
any fix please? :)

**Comment by samerton** [comment]
The steps set out in [this post](http://askubuntu.com/a/48363) will fix your problem.

**Comment by Adobes** [comment]
Do you have a .htaccess file? It (by the looks) seems as there isn't one, double check.

**Comment by samerton** [comment]
I'm going to go ahead and close this as it's down to the server configuration, and the steps in my previous comment will fix the issue.
