### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#551]
How do I edit an email message?

**Comment by zikycz** [comment]
https://ctrlv.cz/fKUr

**Comment by samerton** [comment]
You can edit the `$email_language` array in [styles/language/*Language*/language.php](https://github.com/NamelessMC/Nameless/blob/master/styles/language/EnglishUK/language.php#L792-L797) to modify the email content.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any further questions please feel free to re-open.
