### ISSUE TITLE
Unable to check for updates. Please try again later.

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#56]
When I activate the addon and go to the members page I get a 404 error. When I enable debugging it says: Notice: Undefined offset: 0 in /var/www/html/core/init.php on line 134

**Comment by HappyHarm** [comment]
Nvm, was updating and sees I put members.php on the wrong place :S Came to another small thing and that is that when I go to Update it says "Unable to check for updates. Please try again later.
"

**Comment by samerton** [comment]
Could be a problem with Cloudflare protection, I'll look into it now.

**Comment by samerton** [comment]
My fault, the upgrade process from 0.4.x -> 1.0.0 didn't actually update the version number.

Unfortunately this will require a manual fix for now.

If you have something like phpMyAdmin to access your database with, open the "nl1_settings" table, find the row where "name" is equal to "version", and change the value from '0.4.0' to '1.0.0'.

**Comment by HappyHarm** [comment]
Will try it out thanks!

**Comment by HappyHarm** [comment]
Already manually updated to 1.0.1. Guess I should set this as version then?

**Comment by samerton** [comment]
Indeed, the version number will need changing to 1.0.1 instead of 1.0.0

**Comment by HappyHarm** [comment]
Did it and works now :) Thanks!
