### ISSUE TITLE
Menu colour

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#561]
Hello, I would like to change the color of the menu is in the photo : https://ctrlv.cz/5W6L I would like to change it to that color : https://ctrlv.cz/APUm

**Comment by samerton** [comment]
You'll need to override the Bootstrap navbar component CSS, [this](http://stackoverflow.com/a/18529465) provides all the information you'll need to do this :)

**Comment by zikycz** [comment]
Thanks

**Comment by samerton** [comment]
No problem
