### ISSUE TITLE
Subdomain?

### ISSUE THREAD

**Issue by tomf42** [NamelessMC/Nameless#565]
Hi, is there any way to make subdomain with NamellesMC? If I try to acces to subdomain, it show me the home page... not the page which I want to soubdomain

**Comment by samerton** [comment]
Subdomains do work with Nameless, however if it's not working it's down to your server configuration.

Make sure you point your subdomain to your subfolder where Nameless is installed.

**Comment by tomf42** [comment]
Oh you donť understand me... I have Nameless in home folder, so it is normal domain (example.com) and if I want to make subdomain (with other site) I can´t...

**Comment by samerton** [comment]
If you're using version 2, the next pre-release will fix this for subfolders only (subdomains still work differently, make sure you have configured it correctly).

Version 1 will work with both subfolders and subdomains equally.

**Comment by tomf42** [comment]
So, How can I make subdomain?

**Comment by samerton** [comment]
Subdomains aren't related to Nameless itself, and is down to your server.

Which operating system are you using (if you're running a VPS/dedicated server), and I can provide you with a link to a guide?

**Comment by tomf42** [comment]
I have a hosting

**Comment by samerton** [comment]
If you point your subdomain (assuming your host uses something like cPanel) to the subfolder with your non-Nameless files, it should work without any issues.

**Comment by tomf42** [comment]
I can´t do that :(

**Comment by samerton** [comment]
I'll mark this as closed as it's host related, if you still have any further questions please feel free to re-open.
