### ISSUE TITLE
404, Page Not Found After Installation.

### ISSUE THREAD

**Issue by theofficialsean** [NamelessMC/Nameless#568]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? Latest Version
* How would you describe the issue? Every time I install NamelessMC on my web root (public_html) I get this: http://prnt.sc/9miliw I have reinstalled it like 5 times, and I can't get anything to work! The step that doesn't work is the Finish step! All I want is to be able to use this site software as my main site and it just won't work.. I am do frustrated and I usually like/know how to fix things myself, but this time, I just can't. I am using a MAC and have already enabled the file override and uploaded again. But as you know, the same 404 error page. That page is a nightmare to me, so please make the site appear as a dream to me.. 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://prnt.sc/9miliw
* Do you have an idea how or where the issue occurs? No. *****. Idea. :)

**Comment by samerton** [comment]
When you mention Nameless was installed in the public_html folder, is it within a folder eg `public_html/Nameless-1.0.15` or something along those lines?

**Comment by theofficialsean** [comment]
No, I installed everything into the public_html freely. No sub domains or sub folders present.. it just won't go to the homepage after I install everything "successfully" as it says.

**Comment by samerton** [comment]
Very strange, is there a file named ".htaccess" present in the `public_html` directory?

**Comment by theofficialsean** [comment]
Yes, I have AllowOverride All through Terminal on my mac, and re-downloaded the file with the new .htaccess file and loaded it in. Still nothing :( can you install it for me? :(

**Comment by samerton** [comment]
Sure, feel free to send me a private message over on [Spigot](https://www.spigotmc.org/members/samerton.10676/) or in our [Discord](https://discord.gg/r7Eq4jw)

**Comment by theofficialsean** [comment]
I sent you a PM via. Spigot.
