### ISSUE TITLE
Install Page Not Found

### ISSUE THREAD

**Issue by MoeXIV** [NamelessMC/Nameless#569]
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.15.  
**How would you describe the issue?** The install page is not found on the webserver although it is in fact there.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have a screenshot of it. http://prntscr.com/ehbxi3
**Do you have an idea how or where the issue occurs?** Happens when I click "No, this is a new install" when I go to install the new page.

webserver: NGINX
php: php5-fpm

**Comment by MoeXIV** [comment]
Keep in mine, 1.0 does NOT install; every version I get this problem. 
BUT, on version 2.0 (the version not meant to be used publically), everything installs fine. No problems...

**Comment by samerton** [comment]
You will be experiencing the issues on version 1 due to your server not allowing the use of mod_rewrite and htaccess files. You can find the solution [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc).

Version 2 doesn't experience this issue as friendly URLs are disabled by default, so the htaccess file is not used.

**Comment by MoeXIV** [comment]
I tried what was said on that page but still having the same issue.
All the pages are there it's just you have to know the exact link on how to get there, you know what I mean?

It's like every page sends you to the incorrect link. What do you think could be the issue in our setup?

**Comment by samerton** [comment]
Apologies, as you're using nginx, you'll need to modify your nginx website configuration to match [this](https://raw.githubusercontent.com/NamelessMC/Nameless/master/nginx.example).

**Comment by samerton** [comment]
Were you able to resolve the issue @MoeXIV?

**Comment by MoeXIV** [comment]
Thank you very much, issue has been resolved!
