### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by lolmanz0** [NamelessMC/Nameless#570]
What is this for? And how can I install it on Windows?

**Comment by manselis** [comment]
That seems pretty obvious to me:

> NamelessMC is a free, easy to use & powerful **website software for your Minecraft server**, which includes a large range of features.

It’s used as a forum and blogging platform by many. Is that explanation good enough?

**Comment by lolmanz0** [comment]
Yes, thanks. But it would be great with some default HTML pages too.

**Comment by manselis** [comment]
You can use themes and make Nameless your own!

**Comment by lolmanz0** [comment]
Okay, thank you a lot!
