### ISSUE TITLE
Is it possible to edit the text in the google two factor client? [question]

### ISSUE THREAD

**Issue by xXTsunami72Xx** [NamelessMC/Nameless#578]
When you activate the two factor and bind it in the app you can see that it says "NamelessMC (ServerName: username)", is it possible to change it ?, and if so how can it be changed.

**Comment by herm1ne** [comment]
I'm not sure if we may edit this...
go `pages\user\fta.php`  
find the line which contains `$tfa = new TwoFactorAuth('NamelessMC');`  
Change as you like and done!

**Comment by xXTsunami72Xx** [comment]
Thanks!!!

`<img src="<?php echo $tfa->getQRCodeImageAsDataUri($sitename . ':' . htmlspecialchars($user->data()->mcname), $secret); ?>">`

**Comment by xXTsunami72Xx** [comment]
Thanks you!!!

`<img src="<?php echo $tfa->getQRCodeImageAsDataUri($sitename . ':' . htmlspecialchars($user->data()->mcname), $secret); ?>">`
