### ISSUE TITLE
[Bug] Download does not include the "install" folder.

### ISSUE THREAD

**Issue by KKosyfarinis** [NamelessMC/Nameless#579]
There is not an install folder inside of the .zip and .tar.gz downloads. (Version 1.0.15)
http://prntscr.com/ek5xi7 (as seen using ftp)
http://prntscr.com/ek5xoj (.tar.gz)
http://prntscr.com/ek5xst (.zip)
http://prntscr.com/ek5yhp (before clicking on install) 
http://prntscr.com/ek5ynp (after clicking on install)

**Comment by KKosyfarinis** [comment]
Doing a bit of research turns out I had to enable .htaccess and mod_rewrite.

**Comment by samerton** [comment]
Yep, exactly. Instead of there being an install folder included in Nameless, the page is loaded in the same way as the rest of the site, which is through routing which requires mod_rewrite and htaccess files.

Glad you were able to resolve the issue!
