### ISSUE TITLE
Issue: Buycraft API not syncing

### ISSUE THREAD

**Issue by TechDIN0** [NamelessMC/Nameless#58]
The buycraft API is not syncing so my shop it not showing up under the donate page

**Comment by HappyHarm** [comment]
Thought you have to setup a cron task for it.

**Comment by samerton** [comment]
Interestingly this issue only occurs with Buycraft, I'll look into it now.

**Comment by samerton** [comment]
Fixed in the latest commit. To apply the changes now, update your addons/Donate/integration/buycraft.php with the latest repository version.
