### ISSUE TITLE
2FA Can be circumnavigated

### ISSUE THREAD

**Issue by Penguinexpert1** [NamelessMC/Nameless#580]
Version: 1.0.15

When wanting to get into the Admin Panel, an admin can do the following to avoid using 2FA.

1. 
2. Sign in as any other user
3. Go to /admin and use your normal login details
4. The admin panel will load as your primary account
5. By clicking on the arrow next to your name and clicking 'Profile', you can now access the rest of the site using your account, without having to use 2FA.

Please fix this urgently!

**Comment by samerton** [comment]
Thanks, fixed in b285af51e32d37718ff9e21835b1d15a2d94e0e1
