### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by YouTiao233** [NamelessMC/Nameless#581]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)?laster
* How would you describe the issue? i type the chinese and it change it to "??" how to fix
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
![image](https://cloud.githubusercontent.com/assets/21272351/24077615/4d3fbfc6-0c8e-11e7-8f9c-9e5641526761.png)
* Do you have an idea how or where the issue occurs?I dont know :(

**Comment by herm1ne** [comment]
What characters were you trying to type?  
I use Japanese characters a lot (which is the same character as Chinese one) but it never happens...

**Comment by YouTiao233** [comment]
@herm1ne just nomal Characters,i type any characters it will auto change "?"

**Comment by herm1ne** [comment]
I think you misconfigured php... in order to process multi-byte characters correctly, you need to deal any input as UTF-8  
![https://i.imgur.com/1MhvKU4.png](https://i.imgur.com/1MhvKU4.png)

**Comment by YouTiao233** [comment]
@herm1ne what system are you using?

**Comment by herm1ne** [comment]
Linux(Ubuntu) + Apache + MySQL + PHP(7.0.15) + latest (not 2.0) NamelessMC  
Unfortunately I forgot how to configure PHP for UTF-8 input...

**Comment by YouTiao233** [comment]
@herm1ne ok thank yu

**Comment by YouTiao233** [comment]
@herm1ne i try to seach form google

**Comment by herm1ne** [comment]
yeah good luck

**Comment by YouTiao233** [comment]
@herm1ne i use like &#20320;&#22909; the cheinese is working
![image](https://cloud.githubusercontent.com/assets/21272351/24077963/5fd670ac-0c99-11e7-8174-c28fb2a28592.png)

**Comment by YouTiao233** [comment]
@samerton

**Comment by samerton** [comment]
At the moment it seems to depend on the web server the site is running on; it works on some but not others.

I've been working to modifying Nameless so it will work on all servers, regardless of the configuration. It'll hopefully be ready in the full version 2 release.

**Comment by YouTiao233** [comment]
@samerton  When will it update the 2.0 version?

**Comment by samerton** [comment]
There's no estimated release date yet I'm afraid.

**Comment by samerton** [comment]
A user has trialled the v2 pre-releases on their server where they were experiencing the `?` issue for Chinese characters, and they have said the v2 pre-release has fixed their problem.
