### ISSUE TITLE
Replace / add smileys

### ISSUE THREAD

**Issue by Sataniel98** [NamelessMC/Nameless#582]
Hi, I've got a question concerning NamelessMC 1.0.15. Where are the smiley images saved or where are they accessed in the code? Can I replace them or maybe even add new ones? I'd appreciate it if someone could point me in the right direction.

Thank you and please keep up the great work :)

**Comment by samerton** [comment]
The smileys are located in the core/assets/js/plugins/smiley/images folder, and can simply be replaced.

Unfortunately it's not too straightforward to add new smileys. [This post](http://ckeditor.com/comment/43046#comment-43046) explains the required steps, and the `config.js` the post refers to is the `/core/assets/js/config.js` file. If, after adding the code to add new smileys, the smileys don't change, you may have to force a config refresh by either adding or incrementing the config timestamp defined in each page which has an editor (check out [this commit](https://github.com/NamelessMC/Nameless/commit/c4c6079d1cee57b21bd7a3b2b91b80b430fe63b1) for an example).

**Comment by Sataniel98** [comment]
Thank you very much! It worked perfectly fine.
