### ISSUE TITLE
Profile description - possible?

### ISSUE THREAD

**Issue by omginput** [NamelessMC/Nameless#586]
I'd like to know whether it is possible that each registered player can have a profile description.
I mean something that can be quite long with pictures etc..
Is this possible yet? How can it be done?

Thank you

**Comment by samerton** [comment]
Creating custom profile fields is possible in version 2 (currently still in pre-release stages) :)

**Comment by samerton** [comment]
I'll mark this as closed (v2 branch found [here](https://github.com/NamelessMC/Nameless/tree/v2))
