### ISSUE TITLE
Submitting Minecraft in Admin Panel

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#59]
Hi,

When you click on submit on the minecraft page in the admin panel all the settings turn white and aren't getting saved like this:
http://prntscr.com/9oa4sj

EDIT; It looks like it is just the "Display server status module" that isn't getting saved. Any ideas how to enable it?

**Comment by samerton** [comment]
There were database changes in 1.0.1 which may have caused your issue as you had to upgrade manually.

To fix this, create the following new entries in the "nl1_settings" database table:

First entry:
'name' => 'mc_status_module',
'value' => 'false'

Second entry:
'name' => 'recaptcha_secret',
'value' => 'null'

**Comment by HappyHarm** [comment]
Ok will try it out thanks again!

**Comment by HappyHarm** [comment]
It worked :) Is there btw a way to remove that big "Social" at the front page when the social module is disabled?

**Comment by samerton** [comment]
You can edit templates/Default/index.tpl to remove this.

**Comment by HappyHarm** [comment]
Got it to work thank you!
