### ISSUE TITLE
Next step does not exist

### ISSUE THREAD

**Issue by donleo123** [NamelessMC/Nameless#591]
### Template:
**What kind of issue is it (Question, Bug, etc.)?** Bug
**In which version of NamelessMC did it occur (1.x.x)?** 1.0.15
**How would you describe the issue?** step=requirements does not exist
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** http://prntscr.com/eqfn9p
**Do you have an idea how or where the issue occurs?** No

**Comment by samerton** [comment]
[This](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) should help with your issue.

**Comment by donleo123** [comment]
Dont understand that

**Comment by samerton** [comment]
Are you running your website on a shared web host, or on your own VPS/dedicated machine?

**Comment by donleo123** [comment]
Shared

**Comment by samerton** [comment]
Can you see if a file named `.htaccess` exists in your main website folder (usually public_html), and if not can you create one and paste [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess) inside?

**Comment by donleo123** [comment]
No, and if i create one it doesnt show up

**Comment by samerton** [comment]
As this is something that differs between hosts, try contacting your web host to see if they can help you with creating the htaccess file.

**Comment by ipixelfan** [comment]
I'm having the same issue. I'm using IIS. When I look through the web root, there is not an install folder.

**Comment by samerton** [comment]
@ipixelfan [This post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-66#post-1013093) might help with IIS.

**Comment by samerton** [comment]
I'm going to mark this issue as closed as it's down to the server configuration. If you're still having issues, feel free to re-open.
