### ISSUE TITLE
Add a feature that sends testing mails

### ISSUE THREAD

**Issue by BirkhoffLee** [NamelessMC/Nameless#596]
* What kind of issue is it (Question, Bug, etc.)?
future-request

* In which version of NamelessMC did it occur (1.x.x)?
1.0.15

* How would you describe the issue? 
Can you add a feature that sends testing mails? The configuration process of email sending will be much better after implementing this.

**Comment by samerton** [comment]
Added in 21072f238fd228e89a306247792d41779b7e57ef along with better email error reporting
