### ISSUE TITLE
All Nameless 1.0.15 Pages taking 1-3 mins to load

### ISSUE THREAD

**Issue by ipixelfan** [NamelessMC/Nameless#598]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.15.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by ipixelfan** [comment]
Oops sorry forgot to remove the Example.

**Comment by samerton** [comment]
This may be a host/connection issue, as Nameless itself is fairly lightweight.

**Comment by ipixelfan** [comment]
I have tried it from different connections like my home connection. The web server is IIS and is running through a virtual machine. I have tried to access nameless through the virtual machine and it is still slow. I'm sorry but I just realised that my post didn't post what I had typed in, it posed the default template. But I have tried other indexs and they work fine

**Comment by samerton** [comment]
Unfortunately I'm not sure what the cause would be, sometimes the Minecraft server query (which is on the homepage, forum page and play page) can be slow if the Minecraft server defined is down/unreachable (check your firewall in this case).

Another possible cause is if the MySQL database is on a different machine to the website.

**Comment by samerton** [comment]
Were you able to track down the cause of the issue @ipixelfan?
