### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by woodzykiler** [NamelessMC/Nameless#599]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
bug? 
* In which version of NamelessMC did it occur (1.x.x)?
1.0.15
* How would you describe the issue? 
was doing a first time install
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
This is what i seen after i clicked the the Fresh install button
Not Found
The requested URL /install was not found on this server.
* Do you have an idea how or where the issue occurs?
i looked and i didnt see any file or folder called /install
#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.15.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by ipixelfan** [comment]
What web server are you using. If you are using Apache make sure the included .htaccess file is in the root directory. If your using IIS then you'll need to import .htaccess using the URL Rewrite option in the IIS Control Panel. If you don't have this option just Google how to get it

**Comment by samerton** [comment]
The solution to the 404 not found error is [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc).

**Comment by woodzykiler** [comment]
well i dont have the "AllowOverride FileInfo (as in the guide) to AllowOverride All" in my ubuntu 16.04 and apache2.. and the guide says to ".htaccess" exists in your web server's root directory" theres like 3 spots i found that have apache2 witch one lol
