### ISSUE TITLE
[Suggestion] Authme Support

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless#6]
Hi, 
Would you mind adding authme support ?
I use this plugin for register, etc..
User data are in database (mysql).

Thank you very much.
Very looking forward 1.0 && language .

BTW, is there a donate link?

**Comment by samerton** [comment]
This looks possible, I'll look into it.

There isn't currently a donate link, I'll consider adding one in the future.

**Comment by youwillneverk** [comment]
Yes,add one please. I really like this project.

**Comment by JHXSMatthew** [comment]
Yeah,

**Comment by MrSnowHD** [comment]
integration of this plugin it will be displayed in the namelessmc v2 ?

**Comment by samerton** [comment]
Added in d0389275b9a0a9e91d2ce4b1ecbe7e5ce6ef5e25
