### ISSUE TITLE
Is it possible to modify the limit of maximums & minimums? 

### ISSUE THREAD

**Issue by BirkhoffLee** [NamelessMC/Nameless#600]
As the title said.

**Comment by Headhunterzpw** [comment]
You can't without editing the source code for so far as I know..

**Comment by BirkhoffLee** [comment]
@samerton Any plans?

**Comment by samerton** [comment]
For which values exactly would you like the minimums/maximums to be changed?

**Comment by BirkhoffLee** [comment]
Like titles?

**Comment by DSArtyFixLife** [comment]
@BirkhoffLee, I'm almost sure that NamelessMC v2 has already limitators. But as jesgeerts said, you can without problems  add it yourself.

**Comment by Derkades** [comment]
#1680
