### ISSUE TITLE
Not posting topics

### ISSUE THREAD

**Issue by BirkhoffLee** [NamelessMC/Nameless#603]
* What kind of issue is it (Question, Bug, etc.)?
Bug

* In which version of NamelessMC did it occur (1.x.x)?
1.0.15

* How would you describe the issue? 
Open the post page, write something, post, and it redirects to the forum. The topic's not posted.

**Comment by samerton** [comment]
It could be caused by an invalid form token, in which case you simply need to try again.
I will improve this so it displays an error instead of redirecting to the forum index.

**Comment by samerton** [comment]
Just changed how an invalid form token is handled on topic submission in f5f3cd431e97bfcdde7ac718c9f432e5b507a0e3

**Comment by samerton** [comment]
Hopefully fixed/massively improved in v2 (https://github.com/NamelessMC/Nameless/commit/82f52858956f8ec9837189eb843046e71e55b64d)
