### ISSUE TITLE
Navbar takes container class

### ISSUE THREAD

**Issue by TheSander562** [NamelessMC/Nameless#608]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? Navbar takes the container class
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No
* Do you have an idea how or where the issue occurs? in the admin pages: core, announcements, forums, pages, users.

I know how to resolve: 
change:
```
<div class="container">
	  <?php
	  // "Core" page
	  // Load navbar
	  $smarty->display('styles/templates/' . $template . '/navbar.tpl');
	  ?>
```

to 
```
<?php
	  // "Core" page
	  // Load navbar
	  $smarty->display('styles/templates/' . $template . '/navbar.tpl');
	  ?>
    <div class="container">
```

**Comment by IsS127** [comment]
and what does this change?

**Comment by TheSander562** [comment]
It wont change the navbar, but only the page
