### ISSUE TITLE
How to setup cron job for api

### ISSUE THREAD

**Issue by TechDIN0** [NamelessMC/Nameless#61]
How would i go about setting up a cron job for api

**Comment by samerton** [comment]
Are you using a webhost (with something like cPanel installed) or your own VPS/dedicated machine?

**Comment by TechDIN0** [comment]
Webhost with cPanel

**Comment by samerton** [comment]
Find the link to "Cron Jobs" in your cPanel, and add a setting as follows:

Minute: 0
Hour: *
Day: *
Month: *
Weekday: *

Command: wget -O - -q -t 1 http://URL_FROM_PANEL/?key=KEY

The http://URL_FROM_PANEL/?key=KEY can be obtained from
AdminCP -> Addons -> Donate Settings -> Synchronise donor store -> "Automating the synchronisation"

Hope that helps.

**Comment by TechDIN0** [comment]
Yea Thanks
