### ISSUE TITLE
Donation Page 404 Error Issue

### ISSUE THREAD

**Issue by Gonfonix** [NamelessMC/Nameless#611]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)?  1.0.16, though I have had this issue for quite some time now.
* How would you describe the issue? When I click on the donation tab on the website, then choose a package, and type in username then click agree, it takes me to a 404 error. BTW I use Buycraft.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No as all it gives me is the 404 error.
* Do you have an idea how or where the issue occurs? Not exactly, but it could possibly be a error within my VPS, or possibly Buycraft. I am just looking for any input.

Here is the website URL: http://www.gonfonix.com/donate -- the Donation page. It is also a tab on the top of the website.

Other than that, the website seems to be fine. I appreciate the time and effort for the work put into NamelessMC. :D

**Comment by samerton** [comment]
Hi,

You'll need to make sure you have set your store URL in the Donate addon's settings, and that it has been preceded with http:// or https://

**Comment by Gonfonix** [comment]
Oh ok thank you for the response :D
