### ISSUE TITLE
Play Page/Adding Servers

### ISSUE THREAD

**Issue by nathan93** [NamelessMC/Nameless#613]
**What kind of issue is it?** Issue/Bug
**In which version of NamelessMC did it occur?** 1.0.16
**How would you describe the issue?** When I add servers in the AdminCP, they don't show up as online on the Play page.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** http://imgur.com/a/Hdrgf
**Do you have an idea how or where the issue occurs?** Not sure.

**Comment by samerton** [comment]
Can you check the "Query Errors" tab in the AdminCP -> Minecraft tab to see if any errors appear?

**Comment by nathan93** [comment]
Here is a screenshot from the errors log: http://imgur.com/a/PSvJN

**Comment by samerton** [comment]
It's a possibility that your web host does not allow the use of PHP sockets, or there is a firewall blocking traffic through port 25565. 
Can you try selecting the "External Query" option in the AdminCP -> Minecraft tab to see if that resolves the issue? Unfortunately a limitation of the external query is that it cannot obtain a list of online players.

**Comment by nathan93** [comment]
That solved it. Is there a chance that the External Query option will be able to show online players+avatars in the future?

**Comment by samerton** [comment]
Yep, the upcoming Nameless version 2 will display online players with both the internal and external query.
