### ISSUE TITLE
Uncaught PDOException

### ISSUE THREAD

**Issue by GoldCodes** [NamelessMC/Nameless#615]
Newest version: Question
The installer is now attempting to create the necessary tables in the database.

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'InnoDB' in /home/u390541283/public_html/Nameless-1.0.16/core/classes/DB.php:68 Stack trace: #0 /home/u390541283/public_html/Nameless-1.0.16/core/classes/DB.php(68): PDOStatement->execute() #1 /home/u390541283/public_html/Nameless-1.0.16/core/classes/DB.php(85): DB->createQuery('CREATE TABLE `n...') #2 /home/u390541283/public_html/Nameless-1.0.16/core/classes/Queries.php(112): DB->createTable('nl1_addons', ' `id` int(11) N...', 'ENGINE=InnoDB D...') #3 /home/u390541283/public_html/Nameless-1.0.16/pages/install.php(885): Queries->dbInitialise('nl1_') #4 /home/u390541283/public_html/Nameless-1.0.16/index.php(43): require('/home/u39054128...') #5 {main} thrown in /home/u390541283/public_html/Nameless-1.0.16/core/classes/DB.php on line 68

**Comment by samerton** [comment]
Your web host does not support the InnoDB engine. This is usually on free hosts as an incentive for you to upgrade to their paid plan.
