### ISSUE TITLE
Blank After Installation

### ISSUE THREAD

**Issue by TheSquidHQ** [NamelessMC/Nameless#617]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

### Please use image uploading websites such as Imgur or Gyazo 

* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? During installation after I put in my database information the website just goes blank and it doesnt load anything at all.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://prntscr.com/f0i7tu 
* Do you have an idea how or where the issue occurs? Not really sure :/

**Comment by samerton** [comment]
Can you edit **pages/install.php** in a text editor, and replace all code inside there with [this code](https://gist.githubusercontent.com/samerton/839f62ebde45c878006f65ad12b0f511/raw/5d6fe962056fe9a9f83cc152d16bf62f1818e248/install.php), before trying again? You should then have the error message displaying on the page.

**Comment by TheSquidHQ** [comment]
Nothing happened, not even an error.

**Comment by samerton** [comment]
In that case, can you check your server's Apache error logs to see if there is anything in there?

**Comment by TheSquidHQ** [comment]
When I try other browsers I get: http://prntscr.com/f0oxxb

**Comment by TheSquidHQ** [comment]
I got this error if it means anything
[Tue Apr 25 11:31:34 2017] [error] [client 68.186.141.238] client denied by server configuration: /home/projldlk/public_html/pages/install.php

**Comment by samerton** [comment]
Which server host are you running?

**Comment by TheSquidHQ** [comment]
namecheap

**Comment by samerton** [comment]
As far as I know, Nameless is compatible with Namecheap straight away. 
Can you check your database using phpMyAdmin to see if anything is in there?

**Comment by TheSquidHQ** [comment]
What am I checking for?

**Comment by samerton** [comment]
Just check to see if there are any tables in there, Nameless tables start with the nl1_ prefix.

**Comment by TheSquidHQ** [comment]
There are no tables: http://prntscr.com/f0p21p
The database is the one with _nameless

**Comment by samerton** [comment]
In that case, can you edit **core/config.php** in a text editor, delete everything in there, and try again?

**Comment by TheSquidHQ** [comment]
I just did
Nothing again

**Comment by TheSquidHQ** [comment]
No tables

**Comment by samerton** [comment]
Unfortunately at this point I can only recommend trying a different host, there are free options available specifically available for Nameless including [NamelessHosting](https://namelesshosting.com/) and [Kryptic Hosting](https://billing.kryptichosting.com/)

**Comment by TheSquidHQ** [comment]
Wait!

**Comment by TheSquidHQ** [comment]
Something happened!

**Comment by TheSquidHQ** [comment]
Never mind XD

**Comment by TheSquidHQ** [comment]
Ok

**Comment by TheSquidHQ** [comment]
Um

**Comment by TheSquidHQ** [comment]
For some reason ( I dont know what I did) but now its working ;-;

**Comment by samerton** [comment]
Glad it's working :)

**Comment by TheSquidHQ** [comment]
Thanks :D
