### ISSUE TITLE
Litebans not showing

### ISSUE THREAD

**Issue by Headhunterzpw** [NamelessMC/Nameless#628]
#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.16.  
**How would you describe the issue?** For litebans infractions it will tell you that the table doesn't exist (Found with error debugging) 
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** It requires to set the prefix but sadly there is a small temp workaround  
**Do you have an idea how or where the issue occurs?** No but I have a small workaround by editing the config.php in addons/Infractions/ and edit the prefix with litebans_

**Comment by Headhunterzpw** [comment]
Bump

**Comment by samerton** [comment]
You should be able to set the table prefix to `litebans_` in the Infractions addon settings.

**Comment by Headhunterzpw** [comment]
I did but it's not about to being saved

**Comment by samerton** [comment]
Can you make sure your addons/Infractions/config.php file is writable?

**Comment by Headhunterzpw** [comment]
It's writable. It was able to save the host, username, database and password but it didn't save the prefix.

**Comment by partydragen** [comment]
@Headhunterzpw You got it solved?

**Comment by samerton** [comment]
I'll mark this as closed @Headhunterzpw, if you weren't able to resolve the issue please feel free to re-open.

**Comment by Headhunterzpw** [comment]
@samerton It was fixed by writing the tables manually into the config.php so it was resolved actually
