### ISSUE TITLE
Topic Labels

### ISSUE THREAD

**Issue by Faicu** [NamelessMC/Nameless#63]
Why is not working? This error appear, and label nope.
And a question, when you will release 1.1? Really like this :D
![3](https://cloud.githubusercontent.com/assets/16672714/12274529/fdcbaf90-b973-11e5-9f4c-8f34d0a345bd.PNG)

**Comment by samerton** [comment]
I'll add a check to prevent this message from appearing, but it looks as though you need to edit the label and assign it to some forums. 
At the moment, it hasn't been added to any so it won't appear.

**Comment by Faicu** [comment]
ok, thanks
