### ISSUE TITLE
Error 500..

### ISSUE THREAD

**Issue by jweenk** [NamelessMC/Nameless#631]
Hi, i have a problem.. I added a custom module and after adding it my site was offline. I deleted the module but now my site isnt working anymore. 

Check; www.colorcraft.nl

It says error 500, i checked the error log of my hosting and it says: 

[Sat Apr 29 00:10:08.772815 2017] [ssl:warn] [pid 5490] AH01909: www.colorcraft.nl:443:0 server certificate does NOT include an ID which matches the server name

Could you help me?

**Comment by samerton** [comment]
You will need to disable the module in the nl1_modules table in your MySQL database (using something like phpMyAdmin to do so).

**Comment by jweenk** [comment]
There is no modules table in my phpmyadmin

**Comment by samerton** [comment]
Were you able to resolve the issue @jweenk?

**Comment by samerton** [comment]
I'll mark this as closed, if you are still experiencing the issue feel free to re-open.
