### ISSUE TITLE
Photo in theme

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#635]
Hi, I made the template the background, which I wanted to change to another image so we changed it, but still I have the same thing.

Photo theme: https://ctrlv.cz/TtkX
Changed the background: https://abload.de/img/wallup-102616y2shj.png

custom.css

> `.white-text {
>   color: #fff;
>   text-decoration: none;
> }
> .custom-nav-exclaim {
>   color: red;
> }
> /* Credit to bootsnipp.com for the social items */
> #social:hover {
> -webkit-transform:scale(1.1); 
> -moz-transform:scale(1.1); 
> -o-transform:scale(1.1); 
> }
> #social {
> -webkit-transform:scale(0.8);
>  /* Browser Variations: */
> -moz-transform:scale(0.8);
> -o-transform:scale(0.8); 
> -webkit-transition-duration: 0.5s; 
> -moz-transition-duration: 0.5s;
> -o-transition-duration: 0.5s;
>             }           
> /* 
> Only Needed in Multi-Coloured Variation 
>  */
> .social-fb:hover {
>     color: #3B5998;
> }
> .social-tw:hover {
>     color: #4099FF;
> }
> .social-gp:hover {
>     color: #d34836;
> }
> .social-em:hover {
>     color: #f39c12;
> }
> /* Credit to bootsnipp.com for the css for the color graph */
> .colorgraph {
>   height: 5px;
>   border-top: 0;
>   background: #c4e17f;
>   border-radius: 5px;
>   background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
>   background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
>   background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
>   background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
> }
> /* Bootstrap nav list from 2.3.2 */
> .nav-header {
>   display: block;
>   padding: 3px 15px;
>   font-size: 11px;
>   font-weight: bold;
>   line-height: 1.5;
>   color: #000;
>   text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
>   text-transform: uppercase;
> }
> .nav li + .nav-header {
>   margin-top: 9px;
> }
> .nav-list {
>   padding-left: 15px;
>   padding-right: 15px;
>   margin-bottom: 0;
> }
> .nav-list > li > a,
> .nav-list .nav-header {
>   margin-left: -15px;
>   margin-right: -15px;
>   text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
> }
> .nav-list > li > a {
>   padding: 3px 15px;
> }
> .nav-list > .active > a,
> .nav-list > .active > a:hover,
> .nav-list > .active > a:focus {
>   color: #ffffff;
>   text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
>   background-color: #428bca;
> }
> .nav-list [class^="icon-"],
> .nav-list [class*=" icon-"] {
>   margin-right: 2px;
> }
> .nav-list .divider {
>   height: 1px;
>   margin: 9px 0;
>   overflow: hidden;
>   background-color: #e5e5e5;
> }
> /* Make images responsive */
> img {
>       display: inline-block;
>       height: auto;
>       max-width: 100%;
> }
> body {
>   padding-top: 50px;
>   background-image: url('https://abload.de/img/wallup-102616y2shj.png');
>   background-repeat: no-repeat;
>   background-attachment: fixed;
>   background-size: cover;
> }
> }
> .btn-file {
>     position: relative;
>     overflow: hidden;
> }
> .btn-file input[type=file] {
>     position: absolute;
>     top: 0;
>     right: 0;
>     min-width: 100%;
>     min-height: 100%;
>     font-size: 100px;
>     text-align: right;
>     filter: alpha(opacity=0);
>     opacity: 0;
>     outline: none;
>     background: white;
>     cursor: inherit;
>     display: block;
> }
> .frame {  
>     height: 50px;
>     width: 100%;
>     position: relative;
> }
> .frame-sidebar {  
>     height: 50px;
>     width: 100%;
>     position: relative;
> }
> .img-centre {  
>     width: auto;
>     height: auto;
>     position: absolute;  
>     top: 0;  
>     bottom: 0;  
>     left: 0;  
>     right: 0;  
>     margin: auto;
> }
> a {
>   text-decoration: none !important;
> }
>  
> /* Tooltip content on one line only */
> .tooltip-inner {
>   white-space:nowrap;
>   max-width:none;
> }`
>

**Comment by Headhunterzpw** [comment]
Go to the folder pages and edit the file index.php


You might see a snippet like this:
`	<style>
	html {
		overflow-y: scroll;
	}
	.jumbotron {
		margin-bottom: 0px;
		background-image: url(core/assets/img/background-1920x828.jpg);
		background-position: 0% 25%;
		background-size: cover;
		background-repeat: no-repeat;
		color: white;
	}
	</style>`

To edit the background-image url you need to use 'http://example.com/background.png'

So something like this:
`	<style>
	html {
		overflow-y: scroll;
	}
	.jumbotron {
		margin-bottom: 0px;
		background-image: url('http://example.com/bg.jpg');
		background-position: 0% 25%;
		background-size: cover;
		background-repeat: no-repeat;
		color: white;
	}
	</style>`

**Comment by zikycz** [comment]
But I think the background of the whole, not the image, which is smaller, I mean by the big.

**Comment by samerton** [comment]
If your background image isn't changing, your browser could be caching the old image. In that case you can try Ctrl-F5 in your browser to force a cache refresh.

**Comment by samerton** [comment]
Were you able to resolve the issue @zikycz?

**Comment by samerton** [comment]
I'll go ahead and close the issue, if you are still experiencing the issue feel free to re-open.
