### ISSUE TITLE
Diacritic

### ISSUE THREAD

**Issue by Andoz** [NamelessMC/Nameless#636]
http://imgur.com/E0cHrrq

**Comment by samerton** [comment]
I'm not sure I understand the issue, if you are referring to the ? in the text it will hopefully be improved in the upcoming version 2.

**Comment by Andoz** [comment]
Instead of some characters (ě,š..) that have showing question marks.

Sorry for my bad English :/

**Comment by DSArtyFixLife** [comment]
Hello, I wants to fix bug with diacriticon my page - www.softgames.tk - Can someone from here help me? Sorry for my bad english, Im from Slovakia.

**Comment by samerton** [comment]
Hi @DSArtyFixLife 

The issue is fixed in [version 2](https://github.com/NamelessMC/Nameless/tree/v2), which has not been released yet.

Hopefully version 2 will be released soon :)

**Comment by DSArtyFixLife** [comment]
But my friends fixed it. O_O

**Comment by DSArtyFixLife** [comment]
Check - www.elementix.cz - My old project, and webmaster really fixed it.

**Comment by DSArtyFixLife** [comment]
![screenshot - 18_11 002](https://user-images.githubusercontent.com/33781032/32979733-3b423dfc-cc5b-11e7-952f-467f6fe6c54e.png)

**Comment by DSArtyFixLife** [comment]
Thats my page.

**Comment by DSArtyFixLife** [comment]
![screenshot - 18_11](https://user-images.githubusercontent.com/33781032/32979744-657e47a0-cc5b-11e7-9208-8c5af07766f2.png)

**Comment by DSArtyFixLife** [comment]
My friends page.

**Comment by samerton** [comment]
@DSArtyFixLife 
There is one thing you can try, which is to follow the steps [here](https://github.com/NamelessMC/Nameless/issues/481#issuecomment-264727114) (or if you can't find "Change all column collations", [here](https://github.com/NamelessMC/Nameless/issues/481#issuecomment-264880740)).

You will need to use phpMyAdmin to follow those steps, if your web host provides it to you.
