### ISSUE TITLE
Permission to include this in ServerSetup

### ISSUE THREAD

**Issue by Beags** [NamelessMC/Nameless#637]
Hello,

I am the developer of the Server Setup script, and I am looking to add support for installing this to a dedicated box with in my script. 

Here is the spigot resource page: 

[https://www.spigotmc.org/resources/automated-server-setup.36917/](url)

Source code can be viewed on my github.

Thanks,

Buzzy

**Comment by samerton** [comment]
Hi,

Absolutely, you have full permission to include this (for further information the license can be found [here](https://github.com/NamelessMC/Nameless/blob/master/LICENSE.md)) :)

**Comment by Beags** [comment]
I have added this into the script, thanks for the help.
