### ISSUE TITLE
How to destroy NamelessMC

### ISSUE THREAD

**Issue by Aviorleking** [NamelessMC/Nameless#638]
Bug on latest V2 Git

simply upload the V1.0.16 member plugin
create a little module.php
go to modulesl list and enable it 
your site will now don't work xD

**Comment by Aviorleking** [comment]
to correct it go to your FTP copy the Example module
rename it to the corrupted module "Member in my case"
then replace the corrupted by the new one and go disable it on the website

**Comment by samerton** [comment]
Glad you were able to resolve the issue
