### ISSUE TITLE
Registration --> Invalid Token

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#64]
Hi there,

Having reported this issue earlier but it looks like the error messaged has changed now. When someones try to register they get "Invalid token, please try again later". Any clue how to fix this?

**Comment by HappyHarm** [comment]
Thought maybe it should work with smtp. But then I'm getting this error "Warning: file_get_contents(/var/www/html\styles\templates\Default\email\register.html): failed to open stream: No such file or directory in /var/www/html/pages/register.php on line 244
Mailer Error: Message body empty"

**Comment by samerton** [comment]
Could I have a link to your site to test the token?

As for the mailer error, I'll look into it shortly.

**Comment by HappyHarm** [comment]
gravelcraft.nl Sometimes it works after a long loading time and sometimes it gives me the invalid token.

**Comment by HappyHarm** [comment]
Do you want to have debugging enabled btw for testing?

**Comment by samerton** [comment]
I've had a quick test now, and I'm not getting the token error; this may be caused by navigating to other tabs whilst registering, although unlikely. Unfortunately I'm not sure what else could cause this.

**Comment by HappyHarm** [comment]
Did try it by myself some seconds ago and still getting that error :S

**Comment by HappyHarm** [comment]
Strange thing is, when you get it you are actually registered but it just says invalid token in stead of success or whatever.

**Comment by samerton** [comment]
With the email issue, which OS are you using?

**Comment by HappyHarm** [comment]
Centos 6

**Comment by samerton** [comment]
I'll try and fix the email issue in the next day or two.

As for the token, I'm not sure what could cause that. Can I register an account on your site to see if I can reproduce the issue?

**Comment by HappyHarm** [comment]
Of course, feel free to register. Do you want the php checkmail enabled? And debugging eventually?

**Comment by samerton** [comment]
Could you try with your SMTP settings (so the "Message Body Empty" error appears), but can you replace the contents of **pages/register.php** with [this code](https://gist.githubusercontent.com/samerton/8f137337001ff64a8ae0/raw/bc8077c2af0e19d71161ead08f4cdcf0c9b6e895/register.php). I'm looking to fix the "Message Body Empty" error.

**Comment by HappyHarm** [comment]
Of course give me a moment to replace and test :)

**Comment by HappyHarm** [comment]
Replaced it and the page looks broken http://gravelcraft.nl/register

**Comment by HappyHarm** [comment]
Did only edit the register.php file btw. All the other files are last updated at the 1.0.2 update.

**Comment by samerton** [comment]
My bad, [this code](https://gist.githubusercontent.com/samerton/c6037a73a23aa3a80e5b/raw/1a68b4d1cdc17f9be5e66a8ab374386ed645ab56/register.php) should work.

**Comment by HappyHarm** [comment]
Yes it works :) Even faster then the old php mail method for me and I don't get Invalid token with this. Thank you very much (again :smile:)

**Comment by samerton** [comment]
Glad it's working! I'll release 1.0.3 tomorrow hopefully which will include this fix for real.
