### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by VainSinful** [NamelessMC/Nameless#641]
Question: Navigation Bar
NamelessMC version 1.0.15
Running PHP 5.6.30 
I am wondering how I can rearrange the tabs listed in the navigation bar on all of the pages. Along with removing currently listed tabs in the navigation bar and adding in new ones
[Nav Bar](http://i.imgur.com/PbQcc4z.jpg)

**Comment by samerton** [comment]
Whilst it's not possible to rearrange the position of your navbar tabs, you can change the location of addon links (for example Donate, Members etc can be moved to the footer or can be removed altogether) if you update to version 1.0.16.

If you're comfortable with PHP, all navbar links are generated through the [core/includes/template/navbar.php file](https://github.com/NamelessMC/Nameless/blob/master/core/includes/template/navbar.php).

**Comment by A248** [comment]
Furthermore, this feature is fully implemented in version 2 pre6. If you are able to update you will thus be able to move the navbar pages at will.
