### ISSUE TITLE
Docker Hub organization

### ISSUE THREAD

**Issue by BirkhoffLee** [NamelessMC/Nameless#642]
Hey there. Since we've got a working Docker image I think we can create a Docker Hub organization that serves the image, so people can deploy Nameless like
```
$ docker run -d -e "MYSQL_ROOT_PASSWORD=nameless" -e "MYSQL_USER=nameless" -e "MYSQL_PASSWORD=nameless" -e "MYSQL_DATABASE=nameless" --name nameless_db mysql
$ docker run -d -p 80:80 --link nameless_db nameless/nameless
```

So the repo won't be my name `birkhofflee/namelessmc_docker` and people can use it without fear.

Just here to ask, if I can use that name to create the organization?

# ref
https://github.com/BirkhoffLee/namelessmc-docker
https://hub.docker.com

**Comment by samerton** [comment]
Absolutely, please feel free to use the name and we can promote it as the official Docker image :)

**Comment by BirkhoffLee** [comment]
By the way maybe you wanna transfer my current GitHub repository to your organization?

**Comment by samerton** [comment]
@BirkhoffLee 
Just created a new repo [here](https://github.com/NamelessMC/Nameless-Docker), I've also sent you an invitation as a collaborator :)

**Comment by BirkhoffLee** [comment]
Accepted. Thanks! I'll push stuff later today.

**Comment by BirkhoffLee** [comment]
@samerton I don't know but I think you need to add me to your GitHub organization in order to set up an automated build repository on Docker Hub.

**Comment by BirkhoffLee** [comment]
Thanks again for the invitation - the Docker Hub repository is up!
https://hub.docker.com/r/namelessmc/nameless-docker/builds/
