### ISSUE TITLE
Installer fails?

### ISSUE THREAD

**Issue by Headhunterzpw** [NamelessMC/Nameless#648]
#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.16.  
**How would you describe the issue?** The layout of the installer is messed up
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](https://www.i.jessegeerts.nl/2017-05-16_20-33-21.png)  
**Do you have an idea how or where the issue occurs?** I think that there has to being something with bootstrap.. [Click here for the console log of google chrome](https://www.i.jessegeerts.nl/2017-05-16_20-34-42.png)

**Comment by TheSander562** [comment]
Weird, i dont get it.
![schermafdruk 2017-05-16 21 46 30](https://cloud.githubusercontent.com/assets/14059770/26125082/2f4c8e24-3a81-11e7-9075-903108cdb4ad.png)

**Comment by samerton** [comment]
You seem to have Bootstrap v4 CSS cached, which may have happened if you tried out the v2 pre-release.

Try Ctrl+F5 in your browser to force a cache refresh.

**Comment by JosGCS** [comment]
@samerton i have a problem with the installation, i have installed cURL extension for PHP 7.0 but the NamelessMC installer dont works, please check my attatchment for more details.
![captura2](https://cloud.githubusercontent.com/assets/22751399/26132962/f46d3bca-3a60-11e7-8f05-1588300867ce.PNG)

**Comment by samerton** [comment]
@JosGCS 
The cURL package specifically needs to be the `php-curl` package, once that is installed you will need to restart Apache.

**Comment by JosGCS** [comment]
@samerton Thanks to much 👍

The error was caused because i have installed **php7.0-curl**, **php-curl** and **curl** at the same time, now i have only **php-curl** installed on the server.

**Comment by samerton** [comment]
@Headhunterzpw were you able to resolve the issue?

**Comment by Headhunterzpw** [comment]
@samerton Yes, thank you +1

**Comment by samerton** [comment]
No problem, glad to hear
