### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by PugaBear** [NamelessMC/Nameless#651]
Version 1.0.13 with a heavily modified codebase
http://beta-new.bn-mc.net

I have massively modified the code in nameless and have neglected to update for a long time. If you could just point me to where I should be looking, I may be able to figure it out for myself. I understand it is hard to support people who do not update and modify the code

**Comment by samerton** [comment]
The remember me issue was fixed in version 1.0.1 back in January 2016 (commit 39d40bf3920754c600011b1f909808e5f0051702), and users will be remembered for 7 days (configurable in core/config.php).

If the functionality isn't working, it's worth checking cookies are being set client-side.

**Comment by PugaBear** [comment]
I have no idea how cookies work but this is all I'm seeing ![image](http://i.imgur.com/k5aKFQZ.png)

**Comment by samerton** [comment]
Something doesn't seem right, as there should be at least one more named "nl" (or whatever the value is set to in the Nameless config).

What if you var_dump the $_COOKIE array?

**Comment by samerton** [comment]
Any luck with this @PugaBear?

**Comment by PugaBear** [comment]
I recall finding something related but I forget what it was. I dont believe it is working currently however I've not had much time to work on it since I started a full time job recently. Feel free to close this if you'd like to, I'll keep experimenting and message you on discord if I need anything.

**Comment by samerton** [comment]
Sure, I'll close this for now. Feel free to re-open at any time :)
