### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by Aviorleking** [NamelessMC/Nameless#652]
### Template:
* What kind of issue is it (Question, Bug, etc.)? 
Question
* In which version of NamelessMC did it occur (1.x.x)? 
null
* How would you describe the issue? 
Add a force https option
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
null
* Do you have an idea how or where the issue occurs?
null

It could be interesting to ass a force https option for security

**Comment by Headhunterzpw** [comment]
You could use a htaccess rewrite for doing that

`RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L] ` by pasting that in your htaccess (on the last lines)

**Comment by Derkades** [comment]
For nginx something like this:
```server {
    listen 80;
    server_name example.com;
    return 301 https://$server_name$request_uri;
}```

**Comment by ItzSomebody** [comment]
Headhunter's method not working for me xD

**Comment by samerton** [comment]
A full SSL-enabled htaccess can be found [here](https://gist.githubusercontent.com/samerton/83145e0b9367bdf3211f0e1f16c0185f/raw/ebbd85b1adecee8fe0f34f110779729b7eabd1ca/.htaccess).

**Comment by samerton** [comment]
Added in ad05f7c53af4347933effce3bd71667f3c0725cc
