### ISSUE TITLE
discord server only loading

### ISSUE THREAD

**Issue by magnus505** [NamelessMC/Nameless#654]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? I'm trying to add my discord server to my website but it only load any idea why?
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://imgur.com/riELnID
* Do you have an idea how or where the issue occurs? No

**Comment by samerton** [comment]
Quoted from support channel in Discord:
In Discord itself, in the top left of your screen (whilst viewing your server) is a dropdown where you can edit roles, server information etc
Click the Widget tab in there, and then check the box saying "Enable server widget"
