### ISSUE TITLE
Thread Amount  not Update

### ISSUE THREAD

**Issue by Leon338** [NamelessMC/Nameless#655]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Bug

* In which version of NamelessMC did it occur (1.x.x)?
Version 1.0.16

* How would you describe the issue?
The Amount of Threads get not updated on Thread Delete.

### Please use image uploading websites such as Imgur or Gyazo 
<a href="https://www.pic-upload.de/view-33247840/Bildschirmfotovom2017-05-2914-15-26.png.html" target="_blank"><img src="https://www2.pic-upload.de/thumb/33247840/Bildschirmfotovom2017-05-2914-15-26.png" title="Bilder oder Fotos hochladen"></a>

**Comment by samerton** [comment]
I can't seem to reproduce the issue, both the post count and the thread count update correctly on my end. Can you tell me exactly what you are doing so I can try again?

**Comment by samerton** [comment]
I'll mark this as closed for now, hopefully the upcoming version 2 might help with this.
