### ISSUE TITLE
Not creating tables

### ISSUE THREAD

**Issue by WazUpItsZion** [NamelessMC/Nameless#664]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? When installing the database tables do not create.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 

http://imgur.com/a/sZAro
http://imgur.com/a/R0doO
http://imgur.com/a/hPfTX

* Do you have an idea how or where the issue occurs? I'm not sure if the install.php is wrong or something, I looked through old issues and tried some of the code that was put for other people but nothing worked. 

NOTE: I am hosting this off my Mac for personal use.

**Comment by samerton** [comment]
Unfortunately I have no idea what's going on there, looking at the code you will only get that message if the tables are indeed created, or if the tables already exist.

What happens when you try to continue with the installation anyway?

**Comment by WazUpItsZion** [comment]
This has been solved, it was just an issue on my end with the SQL database.

Thank you for the help.

**Comment by samerton** [comment]
No problem, glad it's working!
