### ISSUE TITLE
[Suggestion] Better SEO

### ISSUE THREAD

**Issue by miguelrisero** [NamelessMC/Nameless#665]
Hello!

I want to make a few suggestions for better SEO.

**Title**

![title_problems](https://user-images.githubusercontent.com/7783276/27126077-9d71dcd4-50f6-11e7-9916-646e3d96510e.png)

**Metadescription** (the same as title problems)

![metadescription_problems](https://user-images.githubusercontent.com/7783276/27126087-a78218e2-50f6-11e7-91bb-d630e38a0248.png)

**H1**

![h1_problems](https://user-images.githubusercontent.com/7783276/27126094-af65dee0-50f6-11e7-9425-f2415e89a219.png)

**Comment by samerton** [comment]
Thanks for this, it's really helpful. I will improve these for version 2 :)

**Comment by samerton** [comment]
Started in 8a0aacad34fe26c2d29e71298b1aacb8e03928d5

**Comment by miguelrisero** [comment]
**Another suggestion:**
For all external links in signatures and forum (just externals, if the link is to the same domain no problem), add target="_blank" rel="noopener nofollow", otherwise the page with that links is giving free pagerank to the other.

**Examples:**

**Xenforo**
![5244857162e49d892bbaad26744db048](https://user-images.githubusercontent.com/7783276/28669328-28754006-72d4-11e7-8265-9e2a019ac21d.png)

**Twitter**
![e7087777aa148e1376f463bbc56d6107](https://user-images.githubusercontent.com/7783276/28669349-46f1a484-72d4-11e7-9613-8b018cc81ee8.png)

**YouTube**
![720ad88627ae73894e75ec1599588e5b](https://user-images.githubusercontent.com/7783276/28669358-4cf4fe3a-72d4-11e7-847e-3ac0262d2d7b.png)

**Facebook**
![1bbfc41ac4f2908a8caa746f26a46b0a](https://user-images.githubusercontent.com/7783276/28669373-5e27798a-72d4-11e7-98ed-194c0f9da9fb.png)

**Comment by samerton** [comment]
target="_blank" and rel="noopener nofollow" added to every external link since 82dbf583375c6b1b8dfb9950ba7803f6c1b0de5c

**Comment by samerton** [comment]
It's now possible to customise the description and keywords for each page (plus opengraph tags have been added).

To-do:
- ensure each page has a H1
