### ISSUE TITLE
Photo avatar

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#668]
Hi, how do I change the picture on the forum, how the player has his head, or the avatar as I change it to be on a picture ?

**Comment by ThatTonybo** [comment]
@zikycz You need to have custom avatars enabled. Otherwise the avatar will be the users Minecraft head (sourced from the supplied IGN / Minecraft Name)

**Comment by zikycz** [comment]
I'd like to put there my own picture

**Comment by samerton** [comment]
Check out [this topic](https://namelessmc.com/forum/view_topic/?tid=351) for information on changing the default profile picture.

**Comment by samerton** [comment]
The ability to set a default avatar has been added in d8276bb766d35ea31917ecad8929db690618d418 for the upcoming version 2
