### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Fluffed** [NamelessMC/Nameless#67]
I keep getting this
Fatal error: Class 'Input' not found in /home/hydrafac/public_html/install.php on line 664

**Comment by samerton** [comment]
Try moving your install.php file into the pages directory and trying again.

**Comment by Fluffed** [comment]
The requested URL /install.php was not found on this server.

**Comment by samerton** [comment]
Following the steps in [this post](http://askubuntu.com/a/48363) will solve that error. (Ubuntu + Apache)

**Comment by Fluffed** [comment]
Yeah, doesnt work

**Comment by Fluffed** [comment]
When the install.php is on the pages folder I get this
The server can not find the requested page:

199.202.216.66/~hydrafac/Nameless-master/install.php?step=configuration (port 80)


When it is on the nameless folder I get this
Fatal error: Class 'Input' not found in /home/hydrafac/public_html/Nameless-master/install.php on line 676

**Comment by HappyHarm** [comment]
Not sure, but it looks like you did put in your /html/ directory the whole Nameless-master thing. Put in the home/hydrafac/public_html/ directory **only** the contents of Nameless-master.

**Comment by Fluffed** [comment]
I've tried that too, I get the same errors

**Comment by samerton** [comment]
Hopefully fixed this issue via Skype :)
