### ISSUE TITLE
Apache Error 500

### ISSUE THREAD

**Issue by nate2014jatc** [NamelessMC/Nameless#670]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Bug?
* In which version of NamelessMC did it occur (1.x.x)?
1.0.16
* How would you describe the issue?
Unable to access any pages after installing.
All addresses result in error 500
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
All relevant logs (php, Apache2, and syslog) hold no clues.
* Do you have an idea how or where the issue occurs?
no

**Comment by nate2014jatc** [comment]
[nl1_query_errors.txt](https://github.com/NamelessMC/Nameless/files/1084018/nl1_query_errors.txt)
I checked the database on a whim and found these.
Not sure if they're relevant.

**Comment by samerton** [comment]
Unfortunately we will need to find an Apache related error to figure out exactly what's happening.

Can you try editing core/init.php in a text editor, and replace everything inside with [this code](https://gist.githubusercontent.com/samerton/ccf74b29de40810394e7f8d18dc4b5f6/raw/df831764e0b82dafeef7a31807182c1df12a5cdc/init.php) to see if an error will appear on screen?

**Comment by nate2014jatc** [comment]
Cache error on my end I think.
