### ISSUE TITLE
[Suggestion] API additions

### ISSUE THREAD

**Issue by Bayside308** [NamelessMC/Nameless#673]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Suggestions
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? I would like a method of creating a post by a specific user to be added to the API, the same way you can create reports and such. For example, the POST arguments would include the username of the player to post, the title of the post, and the content of the post. 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? N/A
* Do you have an idea how or where the issue occurs? N/A

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/wiki/v2-API-(draft)
