### ISSUE TITLE
<A> hover color

### ISSUE THREAD

**Issue by HimahoYT** [NamelessMC/Nameless#688]
I need help to change the Hover color of the <A> in the theme Superhero because is the same color as the background

Normal: http://imgur.com/PTIX7Fw
Hover: http://imgur.com/KpXWCuB

**Comment by samerton** [comment]
Thanks for spotting this, I've fixed it in the latest commit.

For now you can edit **styles/themes/Superhero/css/custom.css** in a text editor, and add this right at the bottom:
```
.white-text:hover {
  color: #fff;
}
```
You may need to force a browser refresh (ctrl+F5) to view the changes.
