### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Hunterherobrine** [NamelessMC/Nameless#689]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
* In which version of NamelessMC did it occur (1.x.x)?
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.16.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

Not sure I think it is an error on my part or a bug

1.0.16

That error pops up : 

Warning: require(/storage/ssd4/761/1351761/public_html/forums/core/config.php): failed to open stream: No such file or directory in /storage/ssd4/761/1351761/public_html/forums/core/init.php on line 10

Fatal error: require(): Failed opening required 'core/config.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd4/761/1351761/public_html/forums/core/init.php on line 10

Thanks for having time to read this

Now it shows that error when I tried to replace init.php from the one in git hub

Warning: require(/storage/ssd4/761/1351761/public_html/forums/core/config.php): failed to open stream: Success in /storage/ssd4/761/1351761/public_html/forums/core/init.php on line 9

Fatal error: require(): Failed opening required 'core/config.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd4/761/1351761/public_html/forums/core/init.php on line 9

**Comment by samerton** [comment]
If Nameless is installed in the "forums" directory, this will be the problem. 

Nameless needs to be installed in the web root (in this case, public_html), or alternatively you can point a subdomain (for example forums.example.com) to the "forums" directory.

**Comment by samerton** [comment]
@Hunterherobrine Any luck with this?

I'll mark this as closed, if you are still experiencing the issue feel free to re-open.
