### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by HimahoYT** [NamelessMC/Nameless#690]
I dont know because some avatars not work:
Version: 1.0.16

Not working: http://imgur.com/bpJ2uKd
Working: http://imgur.com/bpJ2uKd

If I change the size of the avatar to 35 work but in 40 not work. Where of php file I can change the size of the avatar

**Comment by partydragen** [comment]
cravatar currently have problems so it goes very slow 
the 35 size is sure cached so thats why it work but 40 is not cached

Try again later and hopefully cravatar work again

**Comment by samerton** [comment]
Yep, as @partydragen says this is an issue with the avatar service used in Nameless version 1. The upcoming version 2 release has the option to switch avatar services, which will resolve the problem.

For now I'm afraid you'll have to wait until the third party avatar service is up and running again, it shouldn't be too long.

**Comment by partydragen** [comment]
Cravatar is working again so i close this Issue
