### ISSUE TITLE
Update Process Not Working On 1.0.16

### ISSUE THREAD

**Issue by Gonfonix** [NamelessMC/Nameless#691]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question / Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? Update process not working. The download button takes me to the new website's main home page. How to fix?
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Yes. An image.
* Do you have an idea how or where the issue occurs? Sort of, based off what the image says.

![image](https://user-images.githubusercontent.com/5055478/27779353-6e17592a-5f90-11e7-99ce-44438d8c3783.png)

**ALSO** here is the link the "**download**" button takes me to: https://worldscapemc.co.uk/nl_core/nl1/updates/%3Cbr%20/%3E%3Cb%3EWarning%3C/b%3E:%20%20mysqli::mysqli():%20(HY000/2002):%20Connection%20refused%20in%20%3Cb%3E/home/worldscapemcco/public_html/nl_core/nl1/statsphp%3C/b%3E%20on%20line%20%3Cb%3E2%3C/b%3E%3Cbr%20/%3EFailed.zip

**Which...** redirects you to https://worldscapemc.co.uk/

**Comment by samerton** [comment]
It seems to have been a temporary issue, hopefully it's resolved itself and I've also prevented the checker from returning the broken URL.
There isn't currently an update available for 1.0.16, as it's still the latest.

**Comment by Gonfonix** [comment]
Okay thank you for the response.
