### ISSUE TITLE
[Question] Not just Minecraft?

### ISSUE THREAD

**Issue by DJCookiez** [NamelessMC/Nameless#696]
* What kind of issue is it (Question, Bug, etc.)? Question
* How would you describe the question? The question is, can it just be used as a normal Forum Software? Not just for minecraft, say, Gmod?

**Comment by samerton** [comment]
Nameless is centred around Minecraft, so ideally you do need to be running a Minecraft server, however you can disable the "Enable UUID Linking" option in the AdminCP to disconnect accounts from Minecraft.

The upcoming version 2 release has a switch to simply disable all Minecraft integration so it can be used for non-Minecraft websites.
