### ISSUE TITLE
Group synchronisation 

### ISSUE THREAD

**Issue by Spikey101** [NamelessMC/Nameless#698]
* Bug
* NamelessMC 1.0.1.6 - Spigot 1.8.8 - Latest BungeeCord - LuckPerms - AuthmeReloaded
* I setup group synchronisation with the namelessmc plugin and put the plugin in my bungeecord folder, set the api key in the config and enabled the plugin API. I created a group "testgroup" on the website which gave the ID 4, I went in the bungeecord plugins and edited the GroupSyncPermissions.yml and added 4: "web.testgroup" i then gave the permission "web.testgroup" to a user and when they registered on the forums they are still in the default group...

I have no errors in the bungeecord console.

**Comment by samerton** [comment]
Hi,

Thanks for the report, could you please create the issue in the [Nameless Plugin](https://github.com/NamelessMC/Nameless-Plugin) repository so the plugin devs are able to see it?
