### ISSUE TITLE
Authme Link account bug? 

### ISSUE THREAD

**Issue by Spikey101** [NamelessMC/Nameless#699]
### Template:
* Bug
* Nameless 2.0 PR2
* A glitch
Create in-game account, Go to website and click Register & Connect Auth-Me account, Enter e-mail address, I will use test@msn.com, Submit, "Your account has been validated please login" Login and log out. Click register, Enter same authme ingame account that we just registered enter a new email address (I will use test1@msn.com) and click submit. "Your account has been validated message you can now login" again, now try and do that again but use the same email you used the first time (test@msn.com) and it says that email address is in use, but shouldn't it have been changed to test1@msn.com .

After clicking register you get to the "Connect authme account" where you enter a username and password, I think that after entering the username and password it should do a check to see if that account is already registered on the website and if so say "This authme account has already been linked, Please login or reset your password, If you forgot the e-mail used when creating your account please contact support@blah.com" 

Or at least unlink the old email from the account so that it is not in use maybe im not sure.

**Comment by samerton** [comment]
Thanks, I've fixed this in cf6ab8f942375ee89279e8dec0056a1d3139312b :)
