### ISSUE TITLE
My page looks like this?

### ISSUE THREAD

**Issue by IceRaider** [NamelessMC/Nameless#7]
My page looks like this https://gyazo.com/3450671a1063a5a25d53333c192bcb8d

**Comment by samerton** [comment]
Have you installed the files in the root directory of your web-server, or in a sub-directory?

**Comment by IceRaider** [comment]
I moved it into the root directory, now it does this https://gyazo.com/8ed6f47ef2a52af508f7f40db97e2a81

**Comment by samerton** [comment]
Looks like the same issue as [this](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-64#post-1009788), I'll look into it.

**Comment by samerton** [comment]
Can you try the steps found [here](https://github.com/NamelessMC/Nameless/wiki/Installation#common-problems)?

**Comment by IceRaider** [comment]
Yup, fixed it :D

**Comment by samerton** [comment]
Great, glad it works!
