### ISSUE TITLE
install.php is 404, doesnt exist

### ISSUE THREAD

**Issue by sweepyoface** [NamelessMC/Nameless#70]
as the title says.

**Comment by samerton** [comment]
Can you try following [these steps](http://askubuntu.com/a/48363) (assuming Apache + Ubuntu)?

**Comment by sweepyoface** [comment]
It's hosted on shared hosting. I am also getting 403 forbidden while trying to access pages/install.php

**Comment by samerton** [comment]
If it's on shared hosting, can you check a file exists in the root directory (usually public_html) named **.htaccess**? If not, can you create one containing [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess).

**Comment by sweepyoface** [comment]
Now I am getting internal server error.

Date: Sat, 23 Jan 2016 04:51:17 -0800

**Comment by samerton** [comment]
Are you navigating to /pages/install.php in your browser, or simply /install?
Is the software installed in the root directory (not a subfolder of public_html)?

**Comment by sweepyoface** [comment]
It is installed in /public_html/nameless so I am navigating to /nameless/ which is the index, and that is where it starts the install.

**Comment by sweepyoface** [comment]
Thanks that worked, but now I am having trouble connecting to the database, one sec

**Comment by sweepyoface** [comment]
nevermind, I have it all working now, thank you :)

**Comment by samerton** [comment]
No problem, glad it's working!

**Comment by sweepyoface** [comment]
One more thing, the questions I am creating for staff applications aren't saving.

**Comment by sweepyoface** [comment]
Neither are the forums.

**Comment by sweepyoface** [comment]
Infact nothing is, I can't even change my alerts to read.

**Comment by samerton** [comment]
For the staff applications, you need to ensure the "name" field is short and is only one word; it can even be something like "one", "two" etc. It won't be displayed at any point.

The forums have a very specific way of being set up. First you need to create a "parent forum". This is done in exactly the same way as any other forum, however it won't be displayed to the user.
Next, all forums you want to show to the user need to be created, and you then need to set their "parent forum" option as the first one you made.

As for the alerts, at the moment you have to click "View Alerts" and then mark the alert as read. This will change in the next version hopefully, as the alerts system is still new.

**Comment by sweepyoface** [comment]
Ah okay thank you. I was trying to mark all as read.

**Comment by sweepyoface** [comment]
uh, what it wrong with the image preview? https://i.gyazo.com/f39aef2126b4cde859962a7faa3ab7db.png

**Comment by samerton** [comment]
Not too sure about that, the editor is an external library which Nameless includes, it's not something I've written myself.

**Comment by sweepyoface** [comment]
Hello, not sure if I should create a new issue for this, but how would I safely disable the built in forum while keeping the play tab and custom pages and make the link in the header go to a MyBB forum?

**Comment by samerton** [comment]
There's no way of disabling the forum, and doing this manually would require a large number of changes to multiple areas of the site.
