### ISSUE TITLE
Some suggestions for version 2 or up

### ISSUE THREAD

**Issue by renzotom** [NamelessMC/Nameless#700]
# Users profiles
- [ ] You can add here option to add own note to user
- [ ] You can add option to adminCP, we can set how many comments and posts will display on user´s profile
- [x] You can add next page, when there will be too many comments
- [x] When user write comment, option to edit it or delete it
- [ ] When someone write comment, before his name can be also his group
- [x] In page about me you can add before user´s name also his group (under skin)
- [x] **When player is Warez, it can display Steve/Alex instead of icon with broken image**
- [ ] It can display statics from MC server there (but on that is probably need module or plugin)
- [ ] You can add default background for all users on their profile
- [ ] You can add next page, when there will be too many posts in Forum page

# Forum
- [ ] **Add voting system here**
- [ ] **Way to set up more permissions - what users can edit posts**
- [ ] Way to set up more permissions - what users can react to topics/posts
- [ ] **Way to set up more permissions - what users can input images or videos to topics/posts**
- [ ] Way to click on label name, ex. important and it shows page with all important topic, what were mark as important (or something like that)
- [ ] **Parent labels**
- [ ] **Way to select multiple labels (one label from every parent labels)**
- [x] On topic page, next to topic name can be also labels used for that topic

# UserCP
- [x] In overview can moderators and admins see IP adress of user
- [ ] In overview - registration date can be translatable (instead of July we can set our own word, or translatable by timezone)
- [ ] Way to search between alerts (we can write there, what we want to search and it find... also filters - what user created alert, filter for in what forum was that alert made, date when was that alert made...)
- [ ] I am not sure, if there is option delete all messages?
- [ ] If there will be too many alerts (user don´t want delete them), create new page or say user: Your alerts will be deleted in ... automatically, beacuse your alerts page is full
- [ ] Way to search between messages (we can write there, what we want to search and it find... also filters - what user started conversation, what user reply last, if user reply, filter for groups, date when was that message made...)
- [x] If there will be too many messages (user don´t want delete them), create new page or say user: Your messages will be deleted in ... automatically, beacuse your alerts page is full

# ModeratorCP
## In two suggestions DOWN I don´t know, if that can be via ModCP, so maybe only via permissions or something like that
- [x] **Option for group with permission, they can edit/delete comments on user´s profile via ModCP (ex. if comment by someone will be vulgary or there will be something forbidden, ex. IP on another server)**
- [ ] **Option for group with permission, they can edit/delete users fields on user´s profile via ModCP (ex. when player write there IP on another server or something else)**

Now finally ModCP:
- [x] In reports can be name of user, who created report
- [x] In reports can be date, when user created that report

# AdminCP
## Add more ways to edit main (default) page
- [x] Copy icon for IP by default (from main page).
- [ ] Next to IP adress on main page can be server version by default.
- [ ] Maybe some field for text by default
- [ ] Way to set how much topics (posts) from forum we can display on main page (now it is too big, or you can add smaller way by default and add there pages)
- [ ] Make somewhere on main page banner with our server by default
- [x] **Way to create more widgets (as social media) by default, from adminCP**
- [x] Widget for voting
- [x] **Widget for online staffs**
- [ ] Widget for new users fields
- [ ] Ticket system

## Overview
- [x] In overview you can add server graph, like how many players there were (or add it to Minecraft)

### Avatars
- [ ] Way to add default avatar ONLY for no premium users

### Own profile fields
- [ ] You can add way to set order for users fields in AdminCP, ex. we want make from third user´s field first, so we simply use arrows to move it up (arrow for move it down also can exist :D )
- [ ] For way to view some private user fields you can add new permission, what we can give only to some groups

### Maintenance mode
- [x] When maintenance mode is active, it displays message on main page and on other pages.... maybe you can add cross (icon to close that message).
- [x] Way to set maintenance window color

### Emails
- [x] Add field for port

### Reactions
- [ ] Way to move reactions down or up, so arrows for moving down and up, like my suggestion in own profile fields, but now here in reactions
- [ ] Option to disable reaction on website and enable them only on Forum
- [ ] Way to add special reactions to some groups or users..... so permission on that (ex. special reactions pack for VIP)

### Registration
- [x] Way to enable and Captcha or other services
- [ ] Way to disable registration in specific time
- [ ] Way to disable registration in specific states (easier will be, when you add way to enable registration in specific states... via IP)
- [ ] Way to block VPN
**Small supplement**
- [ ] Add Captcha.... while someone try too much passwords, while logining

### Social media
- [ ] Add, we can set order of social media (ex. first will be Facebook than twitter...) arrows to move up and down social medias, so we can set our own order - so arrows to move up and down

## Minecraft
- [x] **Add API for plugins**
- [x] Graph about online players (or add it to Overview)

### Banner
- [ ] Display on banner server version
- [x] Way to upload own banner background
- [ ] Way to upload another logo on banner, than server actually has

## Addons / Modules
- [ ] Way to remove deleted addons / modules from FTP, they are still there
- [x] Way to add addons (like we can add modules now), for plugins etc.

## Safety / security
- [ ] Here you can add also, when someone change permissions
- [ ] Changes on forums (adding new forums...)
- [ ] List of deleted posts and topics from forums
- [ ] Other changes

## Styles
- [ ] Night mode, like night mode in AdminCP

### Image
- [ ] Way to upload here faviction (easier way than FTP)
- [x] Way to upload here header (easier way than FTP)
- [ ] In all images write recommend size and some informations, where it will be displayed

## Update
- [ ] **Way to update changes from Github, no only releases?**

### Users
- [ ] **Way to add permissions for users (example, when player is CheatHunter, he can´t have group CheatHunter, he must be secret.... but he must have access to some forums, where normal players can´t)**
- [ ] Way to disable user some reactions
- [x] **Way to add user to multiple groups**

### User groups
- [ ] You can add more permissions for there, ex. if they can use reaction or not (maybe what reactions, some can be for VIP...)
- [ ] Way to click on HTML tag (label) for group, ex. admin and it shows page with all admins on server (or something like that)

# Language
- [x] Way to translate Maintenance text in the window tab
- [ ] Way to translate group names
- [ ] Way to translate labels
- [ ] Way to add forum for another language (so forum per language)
- [ ] Way to see topics from selected language, from forum for that language

# Other
- [x] **Add way to add own pages**
- [x] Way to translate text by pages -> previous and next
- [ ] Way to login via FB...

If I get another idea, I write it here.

**Comment by IsS127** [comment]
What do you mean with
"When player is Warez, it can display Steve/Alex instead of icon with broken image"?

**Comment by baxandrei** [comment]
In some cases, if avatar have problems or non-premium account show an avatar with an "?" on it or nothing.

**Comment by IsS127** [comment]
Ah alright

**Comment by renzotom** [comment]
Yeah, I thought that

**Comment by Derkades** [comment]
Since massive issues like these are hard to keep track of, I've created issues for any unimplemented suggestions:

#1718
#1719

Many suggestions made here have already been implemented since, but maybe I've missed some. Please create issues if I did miss anything.
