### ISSUE TITLE
AuthMe Link [Enhancement]

### ISSUE THREAD

**Issue by Informatique101** [NamelessMC/Nameless#701]
* Enhancement
* PR2
* It's not an issue, but an enhancement suggestion.

I was wondering if it was possible to make it so that a user does not need to link his account to the website, but it would be done automatically upon registering in-game, then he could just login to the website instead of linking the accounts. Or just get rid of the register page and the login page will check if the account is linked already (valid email check), if so forward to user cp, if no e-mail is found under account entered, have them enter an email address which would then register them..

But this is just a suggestion and maybe I'm wrong and it's a bad idea. I really appreciate all of your hard work, You're really good at what you do!

EDIT: Also is there any ETA on when PR2 would be ready to deploy for a live server? Just curious where it's at around, from my point of view it looks ready , just missing some addons xD

**Comment by samerton** [comment]
Unfortunately Nameless has its own database which is separate from Authme, so the account linking process will always be required.
I can look into moving the linking process from the registration page into the login page though, it sounds like it would make more sense than the current system.

As for an ETA, unfortunately I'm really not sure at the moment as I'm still ironing out the bugs in the release, hopefully it's not far off being ready though, but as you mention there are still a lot of missing addons which will take longer.
