### ISSUE TITLE
Facebook widget in sidebar

### ISSUE THREAD

**Issue by Informatique101** [NamelessMC/Nameless#702]
### Template:
* NMC PR2
* In which version of NamelessMC did it occur (1.x.x)?
* I go into Core->Social and add servers facebook page, but nothing appears on the homepage? I thought that maybe a little box would be found showing how many likes or something, you can see an example here: www.informatiquerivesud.ca/en (unrelated WP website, check the sidebar)

Obviously its in pre release, if this feature is not supposed to work yet, simply close this issue and I will get the message :P

**Comment by samerton** [comment]
I like the idea of adding a Facebook widget, I can look into it for the full v2 release

**Comment by samerton** [comment]
Added in 5efb9ddcf4ba9dafab14e8b4baa8a0e8ffc19fee
