### ISSUE TITLE
Missed php mail headers

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#705]
PHPMail header MIME-Version: 1.0 and Content-type: text/plain; charset=UTF-8 is missing from these files:
/pages/register.php
/pages/signin.php
/pages/api/v1/index.php

It looks like:`				$headers = 'From: ' . $siteemail . "\r\n" .
					'Reply-To: ' . $siteemail . "\r\n" .
					'X-Mailer: PHP/' . phpversion();
				mail($to, $subject, $message, $headers);`

But these need to look like: `				$headers = 'From: ' . $siteemail . "\r\n" .
					'Reply-To: ' . $siteemail . "\r\n" .
					'X-Mailer: PHP/' . phpversion() . "\r\n" .
					'MIME-Version: 1.0' . "\r\n" . 
					'Content-type: text/plain; charset=UTF-8' . "\r\n";`

On my server this cause an message (email) split before it to be send, and this is a bad thing, especially when is send an confirmation code to acces to activate account and the code is spited in 2 parts, and users don't realise that. 

The message will look like this: `Hi
Thanks for registering! In order to complete your registration, please =
click the following link:

[...]/validate/?c=tdx6VN0bkzTfXmwyY9JlEKLpr1WsRa73Z=
cM42Bgh5iUOvSeHuADjQFInoGqC

Thanks,
[...]`

**Comment by samerton** [comment]
Thanks, I'll take a look into it :)

**Comment by samerton** [comment]
Hopefully resolved in the PR :)
