### ISSUE TITLE
Suggestion / Add a Wiki module to NamelessMC.

### ISSUE THREAD

**Issue by dannygtech** [NamelessMC/Nameless#706]
### Suggestion!
* What kind of issue is it (Question, Bug, etc.)? Suggestion
* In which version of NamelessMC did it occur (1.x.x)? N/A
* How would you describe the issue? A wiki module for NamelessMC. You'd be able to add wiki pages, with tables, text, headers, pictures, etc. So you don't need to use GitHub Wikis or Wikia. You'd also have an option if you'd like members to be able to edit the wiki.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? A great example of it would be at [the BogNations website](http://www.bognations.com/wiki) where it's completely custom coded.
* Do you have an idea how or where the issue occurs? N/A

**Comment by samerton** [comment]
A wiki is planned as a future module for version 2 :)

**Comment by dannygtech** [comment]
yeet
