### ISSUE TITLE
Add a trophies system to v2

### ISSUE THREAD

**Issue by ThatTonybo** [NamelessMC/Nameless#708]
Suggestion for v2: add trophies like xenForo has. Like a user gets a trophy if they post there 1st message, they edit there profile, things like that. You could also make it so every trophy a user earns gives them a point, and each post / action they do on the site adds to there points, then on the members page you can choose to sort members via A to Z or points (highest to lowest, vice versa)

**Comment by Derkades** [comment]
closing in favour of #173 which is not exactly the same but probably close enough
