### ISSUE TITLE
Installer issue(possible Bug)

### ISSUE THREAD

**Issue by firestorm942** [NamelessMC/Nameless#709]
* Bug Installer Issue.
* v1.0.16
* File or dir(/install) not found during install.
* http://imgur.com/a/tqaPe
i not used to asking for help or posting bugs.
But, ive tried a few different times to set this up.
i just need someone to tell me if its me or the code.
i can have read only access set up(ssh) for anyone who would like to look at my apache install or config.

**Comment by samerton** [comment]
Hi,

The solution can be found [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc) :)

**Comment by firestorm942** [comment]
Tyvm, i had to change it to AllowOverride All. just a FYI for future pple.
