### ISSUE TITLE
Mandrill Support

### ISSUE THREAD

**Issue by computerwizjared** [NamelessMC/Nameless#71]
Hi! I just installed Nameless for my Minecraft community, but I am experiencing the same issue outlined in issue #38. I have temporarily disabled email verification, but this is not optimal. A possible solution would be to add [Mandrill](https://mandrill.com/) support as an option alongside PHPMailer. This way the mail would be handled via an external server. Thanks for the awesome software!

**Comment by samerton** [comment]
Can you try the following email settings (core/email.php):

Username: your Mandrill username
Password: your Mandrill API key
Name: your website's name
Host: smtp.mandrillapp.com
Port: 587
Secure: tls

Once that's done, disable the "Use PHP mail() function" option in the AdminCP -> Core -> Email

**Comment by computerwizjared** [comment]
Wow, awesome! I didn't realize that there were configs in that directory :smiley: Thanks so much!
