### ISSUE TITLE
New posts badges in forums

### ISSUE THREAD

**Issue by ThatTonybo** [NamelessMC/Nameless#710]
I really think this'll be good. 
![image](https://user-images.githubusercontent.com/28176227/28294986-e02de0e4-6ba0-11e7-80b6-455c5bcbf56c.png)
Where I have circled, could you add small badges, so if a user logs on and there's say 2 new posts in that forum, there'll be a badge there saying "2"? Just like how the badges work on subforums.

**Comment by samerton** [comment]
As this view is no longer available I'll mark this as closed and link to https://github.com/NamelessMC/Nameless/issues/1695
