### ISSUE TITLE
Delete button for templates

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#719]
**What kind of issue is it (Question, Bug, etc.)?** Bug.  

**In which version of NamelessMC did it occur (1.x.x)?** pre v2.

**How would you describe the issue?** After a template is removed from ftp, it still exists on database and generate errors
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** PHP ERROR LOG:

**Warning: require(/var/www/.clienti/hartexcraft/custom/templates/Default2/template.php): failed to open stream: No such file or directory in /var/www/.clienti/hartexcraft/modules/Core/pages/admin/styles.php on line 93

Fatal error: require(): Failed opening required '/var/www/.clienti/hartexcraft/custom/templates/Default2/template.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/.clienti/hartexcraft/modules/Core/pages/admin/styles.php on line 93**

**Do you have an idea how or where the issue occurs?** I suggest to ceck if template exists in database and in folder, and if folder don`t exist, remove it.

**Comment by Derkades** [comment]
Isn't there a delete button in AdminCP?

**Comment by baxandrei** [comment]
Nope. There îs no delete button

**Comment by samerton** [comment]
The ability to delete templates properly is coming soon.

**Comment by baxandrei** [comment]
Thanx.

**Comment by samerton** [comment]
Added in 083fbd922ecf156aade77f5a5aafc4284113da30
