### ISSUE TITLE
Player Heads

### ISSUE THREAD

**Issue by MCTyler** [NamelessMC/Nameless#73]
Hi, I was told on Spigot that I am Modifying the Names of Players and interfering with heads displaying properly, but I disabled all my Bungee Plugins and heads are still not displayed on the Play Page. Are they supposed to be and if so, How? I have my Server IP and port configured correctly as it shows "how many" players are online but it does not show their Heads.

**Comment by HappyHarm** [comment]
Had the same problem and I just added each server connected to the bungee with the correspondending name. You can use my site as example gravelcraft.nl/play

**Comment by MCTyler** [comment]
I'll try that but all the Bungee Servers connected are offline. Not sure How that's gonna work, can you Post your settings?

**Comment by MCTyler** [comment]
Yours works great! But how do you add a Bungee Server that is offline?

**Comment by samerton** [comment]
Are you using the internal or external query (AdminCP -> Minecraft -> Servers)

**Comment by MCTyler** [comment]
internal, external won't work. It shuts everything down on the Player Tab.

**Comment by samerton** [comment]
The query can only get a list of players from the Spigot instances, not the Bungee instance. You'll need to create a new server through the AdminCP for each Spigot instance you have, so they can be queried separately.
If they're firewalled, you'll need to allow the website's IP address to communicate with them.

**Comment by MCTyler** [comment]
I kinda figured it was something like this...So Open the Ports IE 25570 ect in the firewall then the IP is 127.0.0.1, right?

**Comment by samerton** [comment]
Make sure you only open the firewall for wherever your website is hosted; don't allow any other IP address to connect to your backend servers directly.

If your website is on the same machine as your server, 127.0.0.1 is the IP address you need.

**Comment by MCTyler** [comment]
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22                         ALLOW IN    Anywhere
[ 2] 25565                      ALLOW IN    Anywhere
[ 3] 80                         ALLOW IN    Anywhere
[ 4] 25570                      ALLOW IN    127.0.0.1
[ 5] 22 (v6)                    ALLOW IN    Anywhere (v6)
[ 6] 25565 (v6)                 ALLOW IN    Anywhere (v6)
[ 7] 25570 (v6)                 ALLOW IN    Anywhere (v6)
[ 8] 80 (v6)                    ALLOW IN    Anywhere (v6)

Still not connecting and showing the heads...Ugh!
In the AdminCP I have 127.0.0.1:25570, but it shows no players online when I am actually online and on that Server.

**Comment by MCTyler** [comment]
I am thinking that my Spigot instances have to be in the online mode to get these heads to show up. I suppose I can live without Player Heads on the Web Page for now.

**Comment by samerton** [comment]
Not sure why it wouldn't work for you, the query will work with offline mode servers also.

As you say, it might just be worth waiting for the plugin, as at some point it will support this.

**Comment by MCTyler** [comment]
It's interesting that you mentioned the word queries...Does Query have to be enabled in Server Properties and in Bungee in order to Query or is it querying thru the Server Port?

**Comment by samerton** [comment]
Your Minecraft server's query doesn't need to be enabled for the query to work.

Very unusual, I'm unsure why you'd get a "name or service not known" error for querying 127.0.0.1. A bit of a longshot, but try replacing the query IP with your server's actual IP (provided you're not using an SRV record), or even localhost:25565.

**Comment by MCTyler** [comment]
Yea, I'm using server records, but I added all the ports for query in the server records. Something is modifying my {TAB} info so I'm trying to trace down which plugin is doing that. 25565 is the port for Bungee, I need to add 25570 which is one server port for a Spigot instance, right? I'll try the localhost on all the ports and see what that does.

**Comment by MCTyler** [comment]
Ok, adding localhost:25565 Just shows the gold bar and the text "There are 1 Players Online" If I change the port to 25570, the Spigot instance it shows the gold bar and "No Player online" even though I'm on there. Is this possibly related to the Style I'm using? I'm gonna try different Styles.

**Comment by samerton** [comment]
Querying a Bungee instance (25565) will never return player heads as Bungee won't return a player list. Do you get the same "Name or service not known" error querying the Spigot backend servers?

**Comment by MCTyler** [comment]
No, It just says "No Players Online" It's like it's not even querying the Server.

**Comment by MCTyler** [comment]
Ok...I had a typo in my SRV record...It does use _udp correct?

**Comment by samerton** [comment]
I believe SRV records use _tcp.
Querying your SRV record isn't supported by the query, it must either be a numeric IP or an A record.

**Comment by MCTyler** [comment]
Ok, lol your over my head there...I thought SRV records just allowed for communication. IE I have a SRV record for Vote that allows 8192, so this is useless huh? That's all handled thru the firewall I guess. OMG I have a A>A>S in Network Infrastructure too, :) time to go back to school!

**Comment by MCTyler** [comment]
Ok so back on topic, The IP of the server is 127.0.0.1:25570 and it shows nothing when I query that, and that Port is open to that IP although since it's internal I don't think it needs to be.

**Comment by MCTyler** [comment]
Ok, I disabled almost every plugin on the server Bungee/Spigot and it's still not working so I'm gonna re-enable all that.

**Comment by MCTyler** [comment]
I'm gonna try a little experiment...I'm gonna run the server online without Bungee and see what happens.

**Comment by MCTyler** [comment]
Ok, even though I open the port its refusing the connection, I guess I need to make a A Record with that port.

**Comment by MCTyler** [comment]
Gonna close this cause there is nothing we can do to resolve this...Just gonna wait for the Server Plugin to hook into the server instances for querying the heads.
