### ISSUE TITLE
Version 1.0.16 no installer

### ISSUE THREAD

**Issue by CyberZ0mbie** [NamelessMC/Nameless#730]
Trying to install Version 1.0.16 but when i select New install I am redirected to example.com/install and that doesn't exist. I've gone back a few versions and none of them have install folders. Is there any way to get this?

**Comment by Tim-NL** [comment]
What webserver do you have, and if it's Apache, do you have mod rewrite enabled?

**Comment by CyberZ0mbie** [comment]
Apache, and yes. Its a shared web host.

**Comment by Tim-NL** [comment]
Are sure that you uploaded all the files? Including the .htaccess? I just downloaded a new copy from here, uploaded it and it gives the install wizard.

**Comment by CyberZ0mbie** [comment]
Hmm. Yea, I uploaded the zip and extracted it right there. Ill double check

**Comment by partydragen** [comment]
Is its installed in root? v1 Must be installed in root folder

**Comment by baxandrei** [comment]
Rewrite engine is on and working?

**Comment by CyberZ0mbie** [comment]
All good now. Thanks all.

**Comment by baxandrei** [comment]
You're welcome.

**Comment by samerton** [comment]
Glad it's working :)
