### ISSUE TITLE
Nameless 1.0.16 won't install

### ISSUE THREAD

**Issue by fenix12585** [NamelessMC/Nameless#731]
I have successfully installed nameless 2.0, but it was not good to go live with, so I deleted it completely and download the recommended version 1.0.16.

When going to my site, i get to the usual install page. It prompts me for new install or upgrade.
I pick new install
then i get an error 404 not found page. the url is:
https://enderbyte.com/install?step=requirements
I am running nginx latest version
php 7.0
mysql latest version

**Comment by fenix12585** [comment]
ok, you can close this. You just have to go in to the server block and change
    location / {
        try_files $uri $uri/ =404;
    }

to:
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

Then restart nginx and the rewrites will work

**Comment by samerton** [comment]
Glad you could resolve the issue :)
