### ISSUE TITLE
Russian Support

### ISSUE THREAD

**Issue by HockeyCockey16** [NamelessMC/Nameless#732]
-  What kind of issue is it (Question, Bug, etc.)?
**Question**
- In which version of NamelessMC did it occur (1.x.x)?
**Release 1.0.16.**  
- How would you describe the issue?
**I type the russian (such as Пример) and it change to ?? how to fix it?**
- Do you have an idea how or where the issue occurs?
**I don`t know**

**P.S.**
If i change **varchar** to **nvarchar** in Queries.php it can help me?

**Comment by samerton** [comment]
Unfortunately in version 1 this depends on your web host configuration so it can't be fixed; hopefully the upcoming version 2 release will fix this though.

**Comment by HockeyCockey16** [comment]
Thanks, i will wait version 2. I hope it will be released soon.

**Comment by HockeyCockey16** [comment]
I accidentally found way, how to fix this error. In problemmed tables i changed encoding from latin1 to utf8mb4_unicode_ci and it start works without errors :)
P.S.
I used phpMyAdmin for editing database
