### ISSUE TITLE
Your core directory is not writable

### ISSUE THREAD

**Issue by jasoryeh** [NamelessMC/Nameless#733]
I tried to set it up so that it works like this: My main website is / and my forums is /forums.
I get this:
At /forums of my domain
![image](https://user-images.githubusercontent.com/13290941/28902273-becc189e-77b2-11e7-95ce-c503e3f2706b.png)
At /forums/index.php
![image](https://user-images.githubusercontent.com/13290941/28902228-8b5a11be-77b2-11e7-9f94-58acd7916a47.png)
Idk what I did wrong...
I have it set to /forums of my domain
![image](https://user-images.githubusercontent.com/13290941/28902240-9b0e00f2-77b2-11e7-95c3-f006b6b42077.png)

**Comment by jasoryeh** [comment]
Before, I've tried to put it in the forums folder of /var/www/html/ and I get "Your core directory is not writable, please check your file permissions."

**Comment by samerton** [comment]
Unfortunately I don't know much about nginx, however you will need to make sure the `location /forums` section in your nginx configuration matches the [example nginx config](https://raw.githubusercontent.com/NamelessMC/Nameless/master/nginx-non-ssl.example) so the rewriting works correctly.

**Comment by baxandrei** [comment]
Try this:
`	location /forums {
		try_files /forums/$uri /forums/$uri/ /forums/index.php?$args;
	}`

or

`	location /forums {
		try_files forums/$uri forums/$uri/ forums/index.php?$args;
	}`

**Comment by jasoryeh** [comment]
@baxandrei  First one gives 404, second one gives a file not found.

**Comment by samerton** [comment]
Just realised that you're running Nameless in a subdirectory; you either need to configure a subdomain (eg forums.yoursite.com) or install Nameless in the web root as version 1 of Nameless does not support subdirectory installations.

**Comment by Derkades** [comment]
Did the solution provided by Samerton work for you @jasoryeh ? If so please close the issue

**Comment by jasoryeh** [comment]
I haven't gotten around to trying it.

**Comment by samerton** [comment]
Were you able to get any further with this @jasoryeh?

**Comment by jasoryeh** [comment]
Closing because this forums software is not what I was looking for.
