### ISSUE TITLE
Cant post in profile status

### ISSUE THREAD

**Issue by kamrxxn** [NamelessMC/Nameless#734]
What kind of issue is it (Question, Bug, etc.)?** Bug.  
In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.16.  
How would you describe the issue?** I can not post in my or anyone elses profile pic, I cannot click on the options either.
Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [[Click here](http://prntscr.com/g3pjgb)]
*Do you have an idea how or where the issue occurs?**  No idea.

**Comment by samerton** [comment]
It looks like you may have upgraded from an old Nameless version straight to 1.0.16, which is not possible to do (for example, you need to upgrade from 1.0.8 -> 1.0.9 -> 1.0.10 -> 1.0.11 and so on). If this is the case, you will need to install the files from the version you were running previously and then keep upgrading through the AdminCP until you reach the latest version.

**Comment by kamrxxn** [comment]
No I have not upgraded from an old Namelessmc version.

**Comment by samerton** [comment]
Unfortunately I'm really not sure what's going on then, perhaps the table was manually deleted by accident at some point.

Can you create a new file in the **pages** folder named **fix.php**, paste [this code](https://gist.githubusercontent.com/samerton/6708ec8425798ef5772cddfeade32503/raw/282cb58b4a77b3aeaf0b828abbfa33ee2935971d/fix.php) inside, and then visit yoursite.com/fix?

Hopefully you will get some messages on screen, and then if you visit your user profiles again the error will disappear and they will work as normal. Once you have visited the page, you can then delete **pages/fix.php**.

**Comment by kamrxxn** [comment]
Thank you soo much, that's fixed but I still cant click [these](http://prntscr.com/g4egh1) buttons? Any solution to that?

**Comment by samerton** [comment]
Mind sending me a link to your site so I can take a look?

**Comment by kamrxxn** [comment]
Yes, [thequadpvp](https://thequadpvp.net/)

**Comment by baxandrei** [comment]
I visited your website and I see some pages not work from users profile like: https://thequadpvp.net/profile/KartoffelPirat13 and nother work, strange..

**Comment by samerton** [comment]
It seems like there are more missing tables for some reason, I have new code for the **pages/fix.php** file [here](https://gist.githubusercontent.com/samerton/6708ec8425798ef5772cddfeade32503/raw/c9940c976b031f6d2d54634181cf03fe9137c6b2/fix.php) which should repair any missing tables throughout the whole site.

If you create a new file called **pages/fix.php**, paste that code inside, and then go to yoursite.com/fix hopefully the new tables will be created successfully. You can then delete pages/fix.php afterwards.

**Comment by kamrxxn** [comment]
Thank you so much you guys have the best support, I'm not sure If I have to create another thread for this but I just wanted to ask how do I edit the HTML in a email?

**Comment by kamrxxn** [comment]
Another issue that I when I search for a user in thequadpvp.net/profile it redirects me to a HTTP ERROR 500.

**Comment by baxandrei** [comment]
To edit html of email You need to go in register file or edit lang file

**Comment by kamrxxn** [comment]
Where is the register file?

**Comment by baxandrei** [comment]
V1 or 2

**Comment by kamrxxn** [comment]
V2

**Comment by baxandrei** [comment]
/modules/Cote/pages

**Comment by kamrxxn** [comment]
I'm sorry but I can't edit the HTML of the email there..?

**Comment by kamrxxn** [comment]
Nvm, I found out where it's located. :D

**Comment by kamrxxn** [comment]
Also, is there a way the applications can see the comments? So they know the reason of their denial.

**Comment by baxandrei** [comment]
Verify permissions of module

**Comment by kamrxxn** [comment]
Huh what?

**Comment by kamrxxn** [comment]
Hi, If I upgraded from V1 to V2 will the users have to register all over again? @samerton

**Comment by samerton** [comment]
Nope, v2 includes an upgrade process so users and forum posts on your v1 site will be transferred to the v2 site.

**Comment by kamrxxn** [comment]
Is there like an upgrade script or something? Or do I just delete the V1 files and paste in the new V2 files?

**Comment by Derkades** [comment]
Replace the files, then in the v2 installer choose upgrade from v1

**Comment by kamrxxn** [comment]
I get bunch of these errors, [link](http://prntscr.com/g7a3o6) 
 [link](http://prntscr.com/g7a3ry )[link]( http://prntscr.com/g7a3y2). And at last, when I do continue nothing is the same as the old Version, like users, forums and stuff.

**Comment by samerton** [comment]
Version 2 has already been installed in your database, you will need to delete all tables in there beginning with `nl2_` (not `nl1_` or you will remove your v1 installation data) and then try again.

**Comment by kamrxxn** [comment]
How do I do that?

**Comment by samerton** [comment]
You can use something like phpMyAdmin if your web host provides you with it.

**Comment by kamrxxn** [comment]
Alright, I fixed it. Thank you so much guys! You guys have the best customer support.

**Comment by samerton** [comment]
No problem, glad it's fixed! I'll go ahead and mark this issue as closed, if you have any further questions feel free to re-open :)

**Comment by kamrxxn** [comment]
I'm sorry for giving so much trouble but I got this new theme for namelessmc v2 and this thing looks very odd. The author of this theme isn't replying either so I wanted to ask here.. How do I fix this? :/

[link](http://prntscr.com/g8tmub)

**Comment by samerton** [comment]
I'm afraid I'm not sure, only the theme author would be able to help you out with that.

**Comment by baxandrei** [comment]
Compare default template menu and new
