### ISSUE TITLE
Gallery function in editor

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#735]
![image](https://user-images.githubusercontent.com/15892014/28975922-2d08627e-793c-11e7-8ee2-9aa2c80b1718.png)
A gallery with buttons to go to the next and previous picture.

**Comment by baxandrei** [comment]
This idea is wonderful. Users have the ability to add screenshots or artworks to the site. It would be nice.

**Comment by TheMinorz** [comment]
I agree! This would be a great addition!

**Comment by masterdoctor** [comment]
On it!

**Comment by Derkades** [comment]
It doesn't really make sense to have it as a module/addon since modules can only create pages and not modify existing ones

**Comment by samerton** [comment]
I think a gallery would have to be in the form of a separate section to the website, adding something like that to the post editor would be pretty unnecessary imo. Having a dedicated section where users can upload screenshots and comment on them would make more sense.

**Comment by masterdoctor** [comment]
@samerton Then again, it might be quite useful if they wanted to put them inline.

**Comment by Derkades** [comment]
I remember using galleries in announcements on my wordpress site when a new minigame or map released, there are definitely use cases.

**Comment by samerton** [comment]
That's fair enough, and it can be investigated for a future update.

I do think a separate gallery module is a good idea too.

**Comment by masterdoctor** [comment]
Okay, seeing as the priority is low, I'll put this on hold.
I've not made much progress as I'm still working on understanding Nameless's code base.

**Comment by Derkades** [comment]
No excuse anymore now! >:)

(Just kidding by the way)

**Comment by Aberdeener** [comment]
Closing in favor of [this](https://namelessmc.com/resources/resource/125-gallery/)
