### ISSUE TITLE
v2 not support special characters on email.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#736]
v2 not support special characters on email like: ă, â, Ă, Ţ, Î and others.

https://i11.servimg.com/u/f11/17/31/96/85/screen10.png

**Comment by samerton** [comment]
@baxandrei Is the "Enable PHPMailer?" option in the AdminCP -> Core -> Email tab enabled or disabled?

**Comment by baxandrei** [comment]
I use an advanced phpmail() that allow me settup an smtp server to send emails. :msmtp

But i tested with default sendmail, msmtp and smtp and looks like this.

**Comment by samerton** [comment]
Can you apply the changes from [this commit](https://github.com/NamelessMC/Nameless/commit/eeb3186ccd0512659fcbc599c3d10e20563d6cca) if you haven't already?

**Comment by baxandrei** [comment]
I will try and return with result

**Comment by baxandrei** [comment]
it is already text/html

**Comment by samerton** [comment]
Does it also have `charset=UTF-8`?

If so, unfortunately I don't know why that's happening as I can't reproduce the issue.

**Comment by baxandrei** [comment]
I checked again. All is well. It should be noted that only in the subject of the message are not supported these characters, its content goes.

**Comment by baxandrei** [comment]
I found the problem. I use a personalized email address that redirects to my gmail address. When the message is redirected, the special characters are replaced with question marks. But when the message is sent directly to my address everything goes well.

**Comment by samerton** [comment]
Glad you found the problem, it sounds like there is an issue in the forwarding process somewhere.
