### ISSUE TITLE
Addon to get data from the Statz plugin

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#738]
https://www.spigotmc.org/resources/statz.25969/

Statz collects a lot of data about players

**Comment by krustymk** [comment]
You realise by linking to #194 this is now a loop!? That is closed linking to this

**Comment by Derkades** [comment]
#194 links to this issue, but this issue does not link to #194

**Comment by krustymk** [comment]
You closed that thread with 'Statistics will be in a new module: #738' which sends the reader here to this thread
You closed this thread with '@Derkades Derkades referenced this issue on Nov 10
[Sugestion] Addons #194'
Which sends the reader back to the first thread

What do you call the last line the post you closed this thread with if not a link to the previous thread....

**Comment by Derkades** [comment]
"Derkades referenced this issue"
= I referenced this issue from another issue

**Comment by Derkades** [comment]
This will be possible with #1484
