### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by Noblesuntzu** [NamelessMC/Nameless#741]
Okay super sorry if this is not the right way to go about this but a server that I'm staff on, one of the servers just kinda... reset. Not entirely, but player data and server properties have been reset. On the web site I get this error
Forbidden

You don't have permission to access / on this server.

Possible causes of this error include:

The request was forbidden by rules in the .htaccess file.
The directory you requested does not have an index.html or index.php file.
The permissions on the file or directory are incorrect.
For details about why the request was forbidden, see the Apache error log at:

/srv/users/SYSUSER/log/APPNAME/APPNAME_apache.error.log

(you can view it at terrapvp.com)
The owner currently isn't reachable and I was just wondering if anyone knew what was wrong. Thanks, <3

**Comment by godleydemon** [comment]
Do you have access to sql database? If so, you can give your user account super admin rights. If the server got reset Though, your going to need to reinstall after making a backup of your current stuff and then see about rebuilding the user database. Because reset to me sounds like you've completely lost the user database.

**Comment by Noblesuntzu** [comment]
I meant the files called server properties and playerdata (on the actual server, these are the vanilla server components that track player data), I'm not sure if this is related to the website shutting down, was just putting it out there XD

**Comment by godleydemon** [comment]
Oh your talking about your Minecraft server? Or?

**Comment by Derkades** [comment]
Run `chmod -R www-data:www-data /path/to/nameless` for debian/unbuntu or `chmod -R apache:apache  /path/to/nameless` for CentOS

**Comment by Noblesuntzu** [comment]
As I said, I'm staff ON the server (so no)

**Comment by Derkades** [comment]
Then ask the server owner to do this if you can't?

**Comment by IsS127** [comment]
Well, its the permissions that are messed up, that's why derkades provided those commands to run, someone that has access to ssh can run those commands.

**Comment by samerton** [comment]
Were you able to resolve this issue @Noblesuntzu?

**Comment by Derkades** [comment]
I just realised, a 403 forbidden error in Nginx (apache as well probably?) can often also indicate an empty directory. It may be that your entire Nameless installation is gone.

**Comment by samerton** [comment]
I'll mark this as closed as it's down to server configuration, feel free to re-open if you're still experiencing issues.
