### ISSUE TITLE
Where is the forum label code?

### ISSUE THREAD

**Issue by sfkwww** [NamelessMC/Nameless#742]
I want to create rank tags for my forum with more certain colors, but I'm not very familiar with html so I don't know where to find the code for the labels, or where to put it once I do find it. I read that a year ago it was in custom.css, but I can't find it there anymore.

**Comment by samerton** [comment]
In version 1 you can't create any extra label colours, you can only use the ones already there.

The upcoming version 2 release already has custom label colours added.

**Comment by samerton** [comment]
I'll mark this as closed as it's in v2
