### ISSUE TITLE
Xampp warnings

### ISSUE THREAD

**Issue by Amiroslo** [NamelessMC/Nameless#743]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16
* How would you describe the issue? Warrning
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Pastebin
* Do you have an idea how or where the issue occurs? Check pastebin below

https://pastebin.com/hc0FD3Ew

**Comment by samerton** [comment]
These won't cause any issues, and can be hidden by disabling "Enable error reporting" in the AdminCP -> Misc tab.

**Comment by Derkades** [comment]
XAMMP is made for development environments, not for production use. Warnings are enabled by default. Like @samerton said above these warnings can be disabled, but keep in mind that XAMMP has many security features disabled to make it easier for developers. It is not safe to use as a public webserver.
