### ISSUE TITLE
Live demo page

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#762]
My suggestion: Make a live demo page with latest commits from github.

**Comment by samerton** [comment]
https://namelessmc.com/ will always be our only demo site available, unfortunately it's not possible currently to keep updating it after every commit though, however manual updates are applied from time to time.

**Comment by Derkades** [comment]
The code in the GitHub repo is not always working, which is why manual updates need to be done. Database changes would be difficult to manage as well.
