### ISSUE TITLE
Player graphs

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#764]
Ways to make this:
1) On the website, ping the server every time the website is loaded if it hasn't done so in half an hour.
Pros: People won't need to do any work
Cons: This will produce blanks for people with less popular websites

2) On the website server, ping the server every half an hour by setting up a cron job.
Pros: No need for a plugin but still very consistent
Cons: This will be hard to set up for the average server owner linux noob and only possible on most linux systems

3) In the plugin, send the online player count through the web api to the webserver.
Pros: Plugin is easier to install than a cron job for most people, and they probably have the plugin installed anyway
Cons: You do need to install an additional plugin on your server.

By the way, highcharts is free for open source projects!

**Comment by samerton** [comment]
1 and 2 added in 71e4bcc193f4e7316f12632fefbd3bdfce51c988

**Comment by Derkades** [comment]
In my opinion having the third option is no longer necessary since the combination of 1 and 2 works pretty good. What's your opinion on this @samerton ?

**Comment by baxandrei** [comment]
În some cases, #3 îs necesary because no posibility fi settup cronjob

**Comment by Derkades** [comment]
@baxandrei But then option 1 should be sufficient maybe. 

Anyway @samerton if you add an API method for this let me know, I'll add it to the plugin

**Comment by samerton** [comment]
3 added in 815265b7a4f2593d71d40f0d17b7f41e78c88c05
