### ISSUE TITLE
Buycraft not syncing correctly

### ISSUE THREAD

**Issue by rwsender** [NamelessMC/Nameless#77]
https://www.supercraft-mc.com/donate
catergorys: http://puu.sh/mIq5N/c8e5c78438.png
Here is a link to my installation, slimeballs are clearly not in the ranks catergory, either is wither skulls, I have a cron job set up and i tried syncing manually, both will not work.

**Comment by SystemUpdate** [comment]
Image works fine for me

**Comment by rwsender** [comment]
What image? I mean the packages keep appearing in the incorrect categorys?

**Comment by samerton** [comment]
Can you clear out the "nl1_donation_packages" table within something like phpMyAdmin, and re-sync to see if it helps?

**Comment by rwsender** [comment]
sorted, thanks!
