### ISSUE TITLE
sugestion FAQ or Knowledge Base

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#772]
My suggestion: add an faq or Knowledge Base module with categories and topics where webmaster can settup answers to questions and more other things.

Example: http://demo2.themewarrior.com/iknowledge/ , http://deskpress.thimpress.com/ , http://demo.wpsmartapps.com/themes/manual/home-11/

**Comment by samerton** [comment]
A wiki is coming soon, probably alongside version 1's release.

**Comment by baxandrei** [comment]
Oh, ok, thanx
