### ISSUE TITLE
Remove user's posts upon user deletion

### ISSUE THREAD

**Issue by rwsender** [NamelessMC/Nameless#78]
http://puu.sh/mIqdf/cd48fcaa59.png This is showing up like a blank avatar, then when i click it it becomes a 404 error.
There is also only one post here not the three that it says http://puu.sh/mIqkW/25ce5ded22.png

**Comment by samerton** [comment]
Just wondering, has a topic been moved from that forum into another, or deleted?

**Comment by rwsender** [comment]
deleted, I solved it by changing the user ID of the last displayed post to mine. Some creative spammer decided to create a thread with the N word as the title in every possible forum on the site.

Possibly add that when a user is deleted, all their posts go too?

**Comment by samerton** [comment]
Sure, that's something I've overlooked. I'll change the issue title to reflect this.
