### ISSUE TITLE
Move buttons to save space

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#782]
Suggested by and image credit to Eufranio#0642 in the Discord
![image](https://user-images.githubusercontent.com/15892014/29833899-4b26423e-8ced-11e7-881b-2edc93cf9fe5.png)

**Comment by IsS127** [comment]
I think they should swap places instead.

**Comment by Awtra** [comment]
Can be put into place. Thanks :)

**Comment by samerton** [comment]
Added in 41af7387073362685c39736cabdb657aac3ea925
