### ISSUE TITLE
Some Suggestions for NL v2 Texteditor

### ISSUE THREAD

**Issue by H4nSolo** [NamelessMC/Nameless#784]
* What kind of issue is it (Question, Bug, etc.)?
  - Suggestion 
* In which version of NamelessMC did it occur (1.x.x)?
  - Latest Nameless v2 Release
* How would you describe the issue? 
  - extension of the text editor

Description:

I think that some extensions maybe include into the Texteditor too.

- Font style:
   A Select Menu to change the text Font / Style
- Ruler:
  On the left side of the editor you could insert a ruler or a scale to count the lines. 
- Tab spacer
  A function for Include tab spacer like in OpenOffice or MS Word.

**Comment by baxandrei** [comment]
I agree with you

**Comment by samerton** [comment]
Looking through the ckeditor plugin list, there doesn't appear to be a plugin to add a ruler/line count to the editor I'm afraid. What exactly are you referring to by the tab spacer?

**Comment by H4nSolo** [comment]
With Spacer I mean the distance one can make with the Tab key.

Too bad that the ruler can not paste.
Perhaps however other nice functions can be added which are offered as an extension for the editor.
I would be happy anyway.

Thank you for your efforts.

**Comment by samerton** [comment]
Support for tabs added in 158a9fd583d4c076fc23cf8d2dc46ce8ddb0dcf2
Font selection added in 90a70cca801745c395469df7df682b72c0a4fc72
