### ISSUE TITLE
Your core directory is not writable, please check your file permissions.

### ISSUE THREAD

**Issue by TjeuVreeburg** [NamelessMC/Nameless#787]
### Template:
**Issue**
Permissions

**Version**
pre-release 2.0.0

**Description**
Core directory not writable because no permissions?

**Resources**
Logs:
"Your core directory is not writable, please check your file permissions."

**Idea of the issue**
Something todo with index.php? not sure

Thanks,
Stef

**Comment by samerton** [comment]
This depends on your operating system and where Nameless is installed. I'll assume Nameless is installed in **/var/www/html** in these examples, and you're using Apache.

Ubuntu/Debian:
`sudo chown -R www-data:www-data /var/www/html`

CentOS:
`sudo chown -R apache:apache /var/www/html`

**Comment by H4nSolo** [comment]
1. Check the permission level on your webroot folder
2. Be Sure that your Webserver Configuration alraid set up for using Modrewrite.

**Comment by TjeuVreeburg** [comment]
Yep that is exactly what I am doing cause hosted on a VPS. I will try it out :)

**Comment by samerton** [comment]
Glad to hear :)

**Comment by Rastrian** [comment]
I had this same issue, but already had checked the modrewrite and apache access, but still not working.

**Comment by samerton** [comment]
@Rastrian are you using a web host, or a VPS/dedicated server?

**Comment by Rastrian** [comment]
@samerton dedicated server.

**Comment by baxandrei** [comment]
try: chown apache;apache /var/www -R

**Comment by Rastrian** [comment]
![image](https://user-images.githubusercontent.com/10719452/55688959-25a25a80-5955-11e9-9835-73aee6a2abb9.png)

same

**Comment by baxandrei** [comment]
Are you using centos or ubuntu?

**Comment by Rastrian** [comment]
centos 7

**Comment by samerton** [comment]
@Rastrian 
```
sudo chown -R apache:apache /path/to/Nameless
```
replacing /path/to/Nameless with the path, eg /var/www/html

**Comment by Rastrian** [comment]
I had fixed that issue.

The problem its not about chown permissions.
Centos 7 had to active a protection flag first for enable that module with security.

But thanks for help :)
