### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SteveTastisch** [NamelessMC/Nameless#789]
Hello,

I have a question and can be assigned to the groups tags in a 'Span', just where do I find this?

Best regards,
Steven

**Comment by samerton** [comment]
In the AdminCP -> Users and Groups -> Groups tab, you will see a "Group HTML" and a "Group HTML Large" field whenever you create or edit a group.

You can use any HTML in there, such as an `<img>` tag if you have an image you'd like to use, or you can use the built-in Bootstrap labels, which can be found [here](https://getbootstrap.com/docs/3.3/components/#available-variations) if you're using Nameless v1.
