### ISSUE TITLE
Use Flarum as base of NamelessMC?

### ISSUE THREAD

**Issue by xaoseric** [NamelessMC/Nameless#79]
Would it be easier to use Flarum as the base of NamelessMC?
https://github.com/flarum/core

**Comment by SystemUpdate** [comment]
Considering Nameless is already pretty heavily developed, I would say no

**Comment by samerton** [comment]
Thanks for the suggestion. As much as I am a fan of Flarum, I don't think modifying it for the needs of Nameless would be any easier than building upon the existing forums.
