### ISSUE TITLE
Where can I find the directory from the Bootstrap labels ?

### ISSUE THREAD

**Issue by SteveTastisch** [NamelessMC/Nameless#790]
Hello,

where can I find the directory from the Bootstrap labels ?

Best regards,
Steven

**Comment by samerton** [comment]
Not sure I understand the question I'm afraid, the labels are listed in the [Bootstrap docs](https://getbootstrap.com/docs/3.3/components/#available-variations) and the code for them is in styles/themes/*theme*/css/boostrap.min.css, and if you want to add more labels you can follow the steps in [this post](https://www.spigotmc.org/threads/namelessmc.88001/page-45#post-1840257).

**Comment by baxandrei** [comment]
https://bootswatch.com/lumen/ look here, replace label with badge and will work.
