### ISSUE TITLE
Namelessmc 2.0 Donations Addon location?

### ISSUE THREAD

**Issue by GoNelson** [NamelessMC/Nameless#792]
Hello!

I recently just started using namelessmc 2.0
on my website to test around with, but i cant
seem to see any donations addon? can you
let me know if there is one, and where its located

Thanks

~ Nelson

**Comment by samerton** [comment]
Modules for version 2, such as the donation addon, are still a work in progress and will be released along with the time of the full v2 release (for which an estimated release date is still unknown).
