### ISSUE TITLE
Some languages not present on acp.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#797]
Aviable: Czech  Dutch  EnglishUK  EnglishUS  German  Greek  Norwegian  Portuguese  Romanian  Spanish  SwedishSE

Aviable on ACP: Czech  Dutch  EnglishUK  EnglishUS  German  Greek  Norwegian  Portuguese  Romanian
Not present on ACP: Spanish  SwedishSE

Version of script: v2

**Comment by samerton** [comment]
Fixed in 46f126048ed5cbcceb4fff83f16c852f47cc2f06
