### ISSUE TITLE
I added a post, it exist on forum category, but on forum index it not exist, if i use incognito they apear.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#815]
I added a post, it exist on forum category, but on forum index if not exist, if i use incognito they appear.

But if i don`t use incognito, i need to wait some time for the post to be showed on forum list:

https://i11.servimg.com/u/f11/17/31/96/85/screen16.png
https://i11.servimg.com/u/f11/17/31/96/85/screen17.png
https://i11.servimg.com/u/f11/17/31/96/85/screen18.png

**Comment by samerton** [comment]
This is perfectly normal and is a result of caching the forums :)

**Comment by baxandrei** [comment]
hmm, ok, and how can i make it to be showed instantly after post?

**Comment by samerton** [comment]
There is no option to disable the cache at the moment, in the future I can look into force updating the cache whenever a topic/post is created but for now there is no way of changing this.

**Comment by baxandrei** [comment]
ok, thanx you :D
