### ISSUE TITLE
option to enable page load timer

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#816]
I can`t find this option: https://i11.servimg.com/u/f11/17/31/96/85/screen19.png

**Comment by partydragen** [comment]
Hi @baxandrei 

I have checked and it is added, Be sure you updated all files

**Comment by baxandrei** [comment]
i will ceck, wait

**Comment by baxandrei** [comment]
Solved, thanx, some files didn`t uploaded!

**Comment by samerton** [comment]
Glad it's resolved :)
