### ISSUE TITLE
QUERY ERROR INTERNAL AND EXTERNAL

### ISSUE THREAD

**Issue by TheProKiller756** [NamelessMC/Nameless#82]
Hey im trying to configure nameless and its awesome :D buy i have a problem when i add my server it dos not work fine becouse in the externar query its says it is online buy nothing more:
![1](https://cloud.githubusercontent.com/assets/8642690/12619368/f9c3411a-c517-11e5-94b6-b8cb9faf4dc6.png)
And with the internal its says the ping but nothing more :cry::
![2](https://cloud.githubusercontent.com/assets/8642690/12619425/3d7febb0-c518-11e5-9e39-1c3e752c2887.png)
It give me this error with the internal
![3](https://cloud.githubusercontent.com/assets/8642690/12619456/65d172b4-c518-11e5-9498-0e9283ad3647.png)
What can I do?Here is my config:
![4](https://cloud.githubusercontent.com/assets/8642690/12619487/8db408dc-c518-11e5-8158-f48f102e0601.png)
Thnks :smile:

**Comment by samerton** [comment]
The external query has its issues, there's nothing I can do about this for now as I'm not in control over it.
I've just tested the internal query on my end and it's connecting to your server fine, the only thing I can think of is your web host might be blocking sockets. Do you host the website yourself?

**Comment by TheProKiller756** [comment]
I use hostinger

**Comment by samerton** [comment]
I can only assume your host is blocking the query somehow, unfortunately there's nothing that can be done about this.

**Comment by samerton** [comment]
I'm going to close this as I don't believe this is an issue with Nameless, but rather either a configuration issue, a hosting issue or an issue with the [querying library Nameless uses](https://github.com/xPaw/PHP-Minecraft-Query).
