### ISSUE TITLE
Punishments and Bans

### ISSUE THREAD

**Issue by PeterEstephan** [NamelessMC/Nameless#83]
Hey, 

Recently I have tried banning and punishing someone on my website to realize it did not work. So Im just wondering if that is going to be implemented or if it already is, it might be a bug. 

Thanks!

**Comment by samerton** [comment]
I'll look into it, thanks for the report.

**Comment by samerton** [comment]
Should be fixed in d49a46337bba9de796e1de032e6babcb68616c6f
