### ISSUE TITLE
Theme Settings

### ISSUE THREAD

**Issue by masterdoctor** [NamelessMC/Nameless#831]
### General
* **Type:** Feature Request
* **Version:** `2.0.0-pre3`

### Overview
Is there a possibility of themes being able to add custom settings to the Admin Panel?

**Comment by samerton** [comment]
The Nextyle theme for pre1 worked around this by including a custom module which allowed for template customisations (also something I've seen in other forum softwares). If it's not feasible to create a new module for the settings I'll look into it.

**Comment by baxandrei** [comment]
In agree

**Comment by DSArtyFixLife** [comment]
Hi, you do not need to use Nextyle, you can do anything you want, it is opensource, so you can load external css, load internal css or remake it by yours. But be CAREFUL, because it is not safe to edit it, before you will do anything, make be sure you will not destroy something.
Sorry for my bad English.

**Comment by masterdoctor** [comment]
@DSArtyFixLife um.. The point if this PR is to allow people to install addons without patching their installation and without the risk of destroying something.

**Comment by DSArtyFixLife** [comment]
@masterdoctor Yeah, I know. I just said you can do it already. But the idea is great, because as I said, the way to edit it yourself is not safe. So I just mean if you realy want to do it, now. But now I understand you.

**Comment by samerton** [comment]
Added ability for templates to define a settings page in https://github.com/NamelessMC/Nameless/commit/48bc5a8f39cc9c3bac07b82f408a486b0e78fb4f

For complex setting structures, such as those in the Cesium template, a module is the preferred solution.
