### ISSUE TITLE
Need to escape password with ' in it.

### ISSUE THREAD

**Issue by masterdoctor** [NamelessMC/Nameless#832]
#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 2.0.0-pr3
**How would you describe the issue?** You are able to enter a password with a ' in it but then there is just an error as it is not commented out when placed into the config.
**Do you have an idea how or where the issue occurs?** It's in the install.php file, on the database configuration step (entering the password) as it writes it to config.php.

**Comment by Derkades** [comment]
A simple mysql real escape string should fix this probably

**Comment by samerton** [comment]
This issue is simply related to inserting the database password into the config, str_replace is all that's needed here.

**Comment by samerton** [comment]
Fixed in 28c5672ed3c6dec0f36d692db70f9cf07afc4cdf
