### ISSUE TITLE
Donation addon settings table not being created

### ISSUE THREAD

**Issue by redstonedesigner** [NamelessMC/Nameless#835]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.17
* How would you describe the issue? The donation addon's settings table is not being created.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://phalanxpvp.ml/donate
* Do you have an idea how or where the issue occurs? Activating the addon

**Comment by partydragen** [comment]
Hey if you click on settings icon on the addon then the database will be installed

AdminCP -> Addons -> Setting icon

**Comment by redstonedesigner** [comment]
I tried this, in fact I tried that about 5 times.

Nothing is working :(

Site = http://phalanxpvp.ml

**Comment by samerton** [comment]
Try the following:
- Edit **addons/Donate/settings.php** in a text editor
- Delete all code inside
- Paste [this new code](https://gist.githubusercontent.com/samerton/b651223f37550aac6f20553e4af82665/raw/d7659f2c9c79d589895d032163fdb15baa013906/settings.php) inside
- Visit the settings for your Donate addon again in the AdminCP -> Addons tab
- Edit **addons/Donate/settings.php** again
- Delete all code inside
- Paste the [original file code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/addons/Donate/settings.php) inside

**Comment by redstonedesigner** [comment]
@samerton I tried that and it did not work.

Could I have the SQL queries to create the table which I can execute in PHPMyAdmin?

Thanks,,
Redstone

**Comment by samerton** [comment]
I really can't see why that's not working I'm afraid, I've never seen this issue before and the above code update removes all checks so it just executes the table creation code.

The SQL queries are (untested):
```
CREATE TABLE donation_cache ( `id` int(11) NOT NULL AUTO_INCREMENT, `time` int(11) NOT NULL, `uuid` varchar(32) NOT NULL, `ign` varchar(20) NOT NULL, `price` varchar(10) NOT NULL, `package` varchar(64) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE donation_categories ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(64) NOT NULL, `cid` varchar(64) NOT NULL, `order` int(11) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE donation_packages ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(64) NOT NULL, `description` mediumtext, `cost` varchar(10) NOT NULL, `package_id` varchar(64) NOT NULL, `active` tinyint(4) NOT NULL, `package_order` int(11) NOT NULL, `category` varchar(64) NOT NULL, `url` varchar(512) NOT NULL, `custom_description` tinyint(1) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE donation_settings ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(32) NOT NULL, `value` varchar(128) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by redstonedesigner** [comment]
Upon checking my database, it appears that ONLY the settings table was not created.
Some sort of bug with the table creation?

**Comment by samerton** [comment]
Really not sure what's happened, it should create them all in one go. I'd have to investigate further.

**Comment by samerton** [comment]
I still really don't know what happened, to be honest I think this is a very unusual one off occurrence. 
I'll close this issue as there is nothing I can see that's wrong specifically with the donation tables installation, as it's the same method that's used in the rest of the site (including the installer).
