### ISSUE TITLE
SQL Error on loading a player's profile

### ISSUE THREAD

**Issue by fisher8557** [NamelessMC/Nameless#839]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.17
* How would you describe the issue? When loading any player's profile, i get this error, 
Error:
SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
Please check your database connection settings.

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? https://gyazo.com/47b17eb61a70755a50d05bd0a068df0e
* Do you have an idea how or where the issue occurs?
Anytime you load a players profile, said error occurs. Might have something to do with the nameless plugin because it was working before i configured it.

**Comment by samerton** [comment]
Hi,

Make sure you have configured the Infractions addon in the AdminCP -> Addons tab, or if you don't want to use it you can disable it in there too.

**Comment by fisher8557** [comment]
Works, Thanks!
