### ISSUE TITLE
Add view count to profile pages

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#840]
Add view count to profile pages, suggested by VaneHD in Discord

**Comment by Derkades** [comment]
Would be awesome for threads as well (like stack exchange sites)

**Comment by samerton** [comment]
Topics already have view counts (eg [here](https://namelessmc.com/forum/view/3-news-%26-announcements/)]), if that's what you're referring to @Derkades?

**Comment by Derkades** [comment]
k nvm
