### ISSUE TITLE
Install file don't exist

### ISSUE THREAD

**Issue by ucraft02** [NamelessMC/Nameless#848]
I get this page
 http://prntscr.com/h59xiq
please help

**Comment by ucraft02** [comment]
I delete install.php in pages/install.php and now show me this http://prntscr.com/h5bbie

**Comment by partydragen** [comment]
Hey, NamelessMC v1 must be installed in root folder, It can't be installed in subfolders

The new v2 is currnetly in pre release and allow websites to ne installed on subfolders :)
