### ISSUE TITLE
Stuck at database initialisation

### ISSUE THREAD

**Issue by Tomw787** [NamelessMC/Nameless#849]
Bug
Version: 1.0.17
While trying to install, getting stuck at the following screen:
Stuck at "The installer is now attempting to create the necessary tables in the database."

UPDATE: Appears to have installed and is working however keep getting the following error message while viewing website:

Error:
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
Please check your database connection settings.

**Comment by Tomw787** [comment]
Also keep getting this issue randomly:
Error:
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
Please check your database connection settings.

**Comment by H4nSolo** [comment]
Is your database on the same server who is your Webserver or the database has a diffrent adress ;-)
Most database are on the same server and aviable with "localhost" or "127.0.0.1"

Check your Database Server ;-)

**Comment by shadowolfyt** [comment]
I have the same issue as well, attempting to install up to the Database setup & Configuration: 
I get the error '2006 - MySQL server has gone away'

[![Screenshot from Gyazo](https://gyazo.com/f38b1a839e79b8eb3cce9120c16e38ee/raw)](https://gyazo.com/f38b1a839e79b8eb3cce9120c16e38ee)

**Comment by samerton** [comment]
Was this issue resolved? @Tomw787

**Comment by samerton** [comment]
I'll mark this as closed, if you're still having issues feel free to re-open.
