### ISSUE TITLE
Private Message Bug!

### ISSUE THREAD

**Issue by TheOnlyOlly** [NamelessMC/Nameless#85]
So I see that you made a commit that fixed the private message issue, however it did not fix it.

Firstly on the Private Messaging Notification Page:

As you can see by this screenshot: (http://i.imgur.com/RBHTCsx.png) at first the usernames where not duplicating, however when the second person replied it did duplicate!

Secondly on the Private Message itself:

On the first one (where it doesn't actually say"Mibbagirl" twice), when a person is too click the message and read it they can see that it does in fact say "MIbbagirl" twice; Screenshot: http://i.imgur.com/GdL4feO.png

Thanks :smiley:

**Comment by samerton** [comment]
Does replacing the contents of **pages/user/messaging.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/pages/user/messaging.php) help at all?

**Comment by TheOnlyOlly** [comment]
Can confirm it now works!

Thanks!

**Comment by TheOnlyOlly** [comment]
Any ETA on a fix?

**Comment by samerton** [comment]
Haven't had much time recently due to uni work unfortunately, I might get a chance to look into it at the weekend.

**Comment by TheOnlyOlly** [comment]
Alright, No problem.

**Comment by samerton** [comment]
Fixed in the latest commit, if you want to apply the change now replace the contents of **pages/user/messaging.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/pages/user/messaging.php).
