### ISSUE TITLE
namelessmc.com website not loading

### ISSUE THREAD

**Issue by shadowolfyt** [NamelessMC/Nameless#850]
What kind of issue is it (Question, Bug, etc.)?
Bug

How would you describe the issue? 
I don't know if it's me or.... I can't load any page on the https://namelessmc.com/ website.

Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
[![Screenshot from Gyazo](https://gyazo.com/826c9e751cd8af52037202d877f27640/raw)](https://gyazo.com/826c9e751cd8af52037202d877f27640)

**Comment by samerton** [comment]
Should be fixed either tonight or tomorrow, just awaiting a response from the host

**Comment by Headhunterzpw** [comment]
OVH had a major power issue in theri SBG datacentres and in RBX a networking issue. But namelessmc.com gives for my browser an error 500: (https://i.jessegeerts.nl/2017-11-09_19-08-36.png)[Click]

**Comment by samerton** [comment]
Ah right, that may well have been related to the white screen; the 500 error's new and I'll check it out when I next get a chance.

**Comment by samerton** [comment]
The website's back up and running
