### ISSUE TITLE
Nameless setup 404 redirect

### ISSUE THREAD

**Issue by shadowolfyt** [NamelessMC/Nameless#851]
What kind of issue is it (Question, Bug, etc.)?
Bug

In which version of NamelessMC did it occur (1.x.x)?
1.0.16

How would you describe the issue? 
After doing the Nameless setup it redirects you to a 404 page and you can't do anything else from there.

Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
[![Screenshot from Gyazo](https://gyazo.com/fea7ea9a93e2706c6631701d53a2e8a0/raw)](https://gyazo.com/fea7ea9a93e2706c6631701d53a2e8a0)

**Comment by samerton** [comment]
Version 1 of Nameless must be installed in the root directory (so directly at localhost:9987), and not in the /Nameless subfolder.

You can try the version 2 pre-releases which has support for subdirectory installations, however as they're just pre-releases expect bugs and missing features.
