### ISSUE TITLE
Error positioning the error

### ISSUE THREAD

**Issue by shadowolfyt** [NamelessMC/Nameless#852]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Bug
* In which version of NamelessMC did it occur (1.x.x)?
Version 2.0.0 pre-release 3
* How would you describe the issue? 
This occurs on the start screen of the installation
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
[![Screenshot from Gyazo](https://gyazo.com/d721ca4a452dac97dc219a0fe344e3cd/raw)](https://gyazo.com/d721ca4a452dac97dc219a0fe344e3cd)

**Comment by shadowolfyt** [comment]
This also happens with the remainder of the setup process.

**Comment by samerton** [comment]
Your browser is caching old CSS, if you press Ctrl+F5 to force a cache refresh it'll display fine :)
