### ISSUE TITLE
WooMinecraft

### ISSUE THREAD

**Issue by madtomic** [NamelessMC/Nameless#855]
Please add support for http://woominecraft.com

**Comment by samerton** [comment]
I've taken a look, and it appears to be designed for a Wordpress plugin. Nameless is not compatible with Wordpress or its plugins, so I can't see how this can be done.

**Comment by madtomic** [comment]
Have you look at the WooMinecraft plugin?

**Comment by samerton** [comment]
Yep, and unfortunately it requires [WooCommerce](https://wordpress.org/plugins/woocommerce/) and [WooMinecraft-WP](https://wordpress.org/plugins/woominecraft/) (the Wordpress "hook" for the plugin), neither of which are compatible with Nameless.
