### ISSUE TITLE
Maintenance Mode error V2

### ISSUE THREAD

**Issue by PenguinNexus** [NamelessMC/Nameless#856]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 2.0.0-pr3
* How would you describe the issue? You cannot log into your site once using Maintenance Mode,
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
http://prntscr.com/h9n1k4 (Database shows the setting to be off)
* Do you have an idea how or where the issue occurs?
When using the Maintenance Mode setting in Core > Debugging and Maintenance. When using Maintenance mode and closing the admin CP browser tab, You cannot get back into the site after doing so. Even going to the admin directory (/admin) redirects to the Maintenance Page.

**Comment by samerton** [comment]
You need to make sure you're logged in by going straight to yoursite.com/login, and then if you're logged in using your admin account you can browse the site even with maintenance mode enabled.

**Comment by PenguinNexus** [comment]
Thanks samerton, that fixed it :) Wasn't logged in. How come I couldn't force it via the Database though?

**Comment by samerton** [comment]
Maintenance mode also creates a cache file in the **cache** directory, so that would have needed deleting too.

I'll mark this as closed :)
