### ISSUE TITLE
Stucked at creating tables

### ISSUE THREAD

**Issue by danbulant** [NamelessMC/Nameless#858]
i have stucked at instalation. It says the installer is now trying to create tables but MySQL is not creatig anything... I have tried PHP 7.0,7.1,5.6.

**Comment by H4nSolo** [comment]
What for Nameless Version are used?
Be sure you have all requireds correct installed on your webserver (php7, php7-mysql, etc)
Check your Database Connection is functionaly between the webserver and the Database server.

Did you have any Errors or Messages when you run the Installer?

**Comment by samerton** [comment]
To add on to H4nSolo's reply, usually this happens if you are using a free host that does not support the InnoDB MySQL storage engine, in an attempt to get you to upgrade to their premium plan.

**Comment by Derkades** [comment]
I'll mark this as solved for now, if you still need help feel free to reopen.

**Comment by danbulant** [comment]
> To add on to H4nSolo's reply, usually this happens if you are using a free host that does not support the InnoDB MySQL storage engine, in an attempt to get you to upgrade to their premium plan.

3 years later, at the time I was using a free hosting with exactly that. Hope it at least helps other people having similar issues.
