### ISSUE TITLE
[Bug] Nameless V2 McQuery

### ISSUE THREAD

**Issue by H4nSolo** [NamelessMC/Nameless#859]
* What kind of issue is it (Question, Bug, etc.)? 
**Bug**

* In which version of NamelessMC did it occur (1.x.x)? 
**Nameless v2 (latest Github Version)**

* How would you describe the issue?
**When you will use the MC Server Graph Cronjob, the File check the Server but alway he added the Server with 0 Players.
All options to change the connection settings (external or normal query) are not functional.
In the MC Banner Site on the Admin Page, he show me the correct Informations about the Server, but not in the Player Graph.
In the Database (nl2_query_results) he creates entrys with 0 Player
When i run the Query Site for the Cronjob manualy, i get a white page with with the number 2.
I comes from the die() function in the modules/core/queries/servers.php.**

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
**none**

* Do you have an idea how or where the issue occurs?
**I think that the MCQuery Class script has an Bug.**

**Comment by samerton** [comment]
I can't reproduce any issues with the status query, nor any of the settings.

If you enable error reporting in the AdminCP -> Core -> Debugging and Maintenance tab, do you get any errors if you run the cronjob manually?

**Comment by H4nSolo** [comment]
nope no Errors only the numer "2" when is runs the script manually
i have added the server with her srv record. 
Is that the Problem?

**Comment by samerton** [comment]
SRV records shouldn't be an issue, but just to check can you try the IP/port?

**Comment by H4nSolo** [comment]
Yep, with ip and port it`s run correctly.
But when i try the domain (SRV record) without any port, he creates entrys with 0 player.
I think there is a problem in script to resolve a srv Record but i have no errors :(

**Comment by samerton** [comment]
If you apply the changes from [the latest commit](https://github.com/NamelessMC/Nameless/commit/4ce58d9ea1060dee7e4c0daba480eb5e72202809) does that help at all?

**Comment by H4nSolo** [comment]
ok, seems to be fixed.
Thx
