### ISSUE TITLE
DONATE MESSAGE CAN'T BE TRANSLATED

### ISSUE THREAD

**Issue by TheProKiller756** [NamelessMC/Nameless#86]
Hello,
When I try to translate the donate messages it does not work,when I click in the page its redirect to /donate but at the moment it come back to the homepage,why?
My code:
`<?php 
/*
 *	Made by Samerton
 *  http://worldscapemc.co.uk
 *
 *  License: MIT
 */
// Language file for "Donate" addon
$donate_language = array(
	'donate' => 'Rangos',
	'latest_donors' => 'Ultimos donadores',
	'agree_with_terms' => 'Donando, aceptas los siguientes terminos y condiciones.',
	'link' => '(Link)',
	'agree' => 'Aceptar &raquo;',
	'cancel' => 'Cancelar',
	'select' => 'Seleccionar'
);`
Thanks

**Comment by samerton** [comment]
Thanks for spotting this, to fix this issue now before the release of 1.0.4, please replace the contents of **pages/donate.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/pages/donate.php).
