### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by iJustBlessed** [NamelessMC/Nameless#861]
- AutoMessage if you are not registered in the chat...
- Staff chat #(message) /sc (message) /staffchat (message)And to toggle for see the message /sc or /staffchat, And on the site https:///(domain).net/Staffchat :smiley:
- /msg sync with website conversations...
- Clans on the site like hypixel did with guilds https://gyazo.com/8d29172e01ff040b55daec22bbaf7b87 connected with api: https://www.spigotmc.org/resources/clans-for-party-and-friends-extended-for-bungeecord.13890/
- If you are banned in minecraft that you get the prefix: [BANNED IN MINECRAFT] And if you are banned on the forum that staff still can see your post but that you have the [BANNED] prefix for them same for deleted post
- If you are banned form the site that you have the option to ban appeal...
- That you can make more forms like Ban appeal and staff apply for thinks like build team apply and Kingdom apply...

**Comment by iJustBlessed** [comment]
With ofcource for msg/conversasion a msgspy in web and minecraft. In minecraft it can get toggled using /msgspy

**Comment by iJustBlessed** [comment]
And for MSG a hook into mute plugins (advancedbans, litlebans)

**Comment by iJustBlessed** [comment]
- Friends form https://www.spigotmc.org/resources/party-and-friends-extended-edition-for-bungeecord-supports-1-7-1-12-2.10123/ get hooked in Friend system on the website!

**Comment by iJustBlessed** [comment]
Block system hooked in https://www.spigotmc.org/resources/block-for-party-and-friends.34762/

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless-Plugin/issues/49

There are already plenty of staff chats and making one that also works on the website would be something for a module not for built-in functionality.

Basically same thing

If you want this please create a specific issue for it

-

This has been discussed previously and I believe an issue is open already for this

-

**Comment by iJustBlessed** [comment]
- Minecraft names get updated if someone log in the site or in minecraft... So they doesn't have to do it manually...
- If you want to registter but its disabled that you see how to /register in minecraft and not 'Register is disabled.'
- Rank category: for (website.com/register) like All, Staff, Donators... Because now all ranks are vieuwed... and i got more ranks but it doesn't show alll because its too much! https://felixmc.net/members..
- Ignore case on links https://felixmc.net/Vote doesn't work it have to be https://felixmc.net/vote.

**Comment by iJustBlessed** [comment]
- edit where things placed... That i can change the location of https://felixmc.net/admin/users form admin panel to https://felixmc.net/mod/users Mod panel.

**Comment by Derkades** [comment]
- the plugin does this already
- modify the message in messages.yml
- coming soon
- https://github.com/NamelessMC/Nameless/issues/863
- probably not coming ever

If you have any more suggestions please create a new issue for every suggestion

**Comment by IsS127** [comment]
On the last part "move admin/users -> modcp/users". I don't think it will happen. But in v2 you will be able to give specific permissions of what users can have access to in the admin panel.

**Comment by iJustBlessed** [comment]
is okay too :P

**Comment by Derkades** [comment]
Continuing this thread will become a mess, so I'll close this. @iJustBlessed if you have any more suggestions please create a new individual issue for every suggestion. Thanks!

**Comment by iJustBlessed** [comment]
?
