### ISSUE TITLE
Moderation Update

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#862]
Large update to the ModCP, including:

- ~~Redesign - separate panel like AdminCP or combine into one panel?~~ - added in 2.0.0 pr5
- Ingame infractions management, tied into ban appeals and player reports
- CoreProtect/alternatives integration
- Possible ingame staff chat integration (#861)
- ~~Add custom pages to ModCP~~
- ~~Edit basic user settings (signatures/avatars)~~ - still need to add custom profile field editing
- More configurable permissions - warnings, temp bans, full bans, forum moderation
- Allow deleting website punishments

**Comment by Derkades** [comment]
I'd add everything into one panel and only show the links in the navbar for settings users have permission for, like Discord.

**Comment by samerton** [comment]
[This](https://cdn.discordapp.com/attachments/247864759947362304/381865519533391884/Skjermbilde.PNG) is a mockup of an all in one panel that Partydragen created.

**Comment by Derkades** [comment]
I kinda liked the navigation on the left actually

**Comment by IsS127** [comment]
Im thinking this: 
![bild](https://user-images.githubusercontent.com/8834158/33026538-eedfe236-ce10-11e7-995d-2dc9a63c546f.png)

The AdminCP is selected, you can select ModCP and it will bring up a modcp dashboard and with the side navbar of modcp.

**Comment by Derkades** [comment]
Vote on my comment

👍 for everything in one panel (except user settings)
👎 for AdminCP and ModCP

I still think everything in one panel would make more sense because stuff in ModCP doesn't have to be for moderators only and same goes for AdminCP.
