### ISSUE TITLE
Ignore case in urls

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#863]
Redirect urls to lower case to fix 404 errors
E.g. /Vote -> /vote

Or change the router code so it ignores case

**Comment by samerton** [comment]
This shouldn't have been an issue in version 1, but I've forced lowercase in this commit: 595da04ae4fce63a14ed5fd58e5e1cdd3ac330d6
Version 2: 5ee7b51aa4f6de5b1ec8ec072e1c626572754271
