### ISSUE TITLE
Background Cant Change

### ISSUE THREAD

**Issue by GamemodeCreative** [NamelessMC/Nameless#864]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 2.0 PreRelease 2
* How would you describe the issue? AdminCP > Style > Images - When I try to change the background nothing works. I can upload new images but nothing will clear the old one.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
* Do you have an idea how or where the issue occurs? AdminCP > Style > Images ?

**Comment by samerton** [comment]
Are you referring to the website background, or the image in the banner on the homepage?

The website background might require a browser cache refresh (pressing Ctrl+F5 whilst viewing your site should fix it), and the banner background on the homepage can be changed by replacing **custom/templates/Default/img/homepage_bg_trimmed.jpg** with an image of your choice using a file manager.

**Comment by Derkades** [comment]
If you still need help feel free to create a new issue
