### ISSUE TITLE
Bug in admin/core/general

### ISSUE THREAD

**Issue by H4nSolo** [NamelessMC/Nameless#869]
* What kind of issue is it (Question, Bug, etc.)?
**Bug**

* In which version of NamelessMC did it occur (1.x.x)?
**Latest Nameless V2 (Repo from Github)**

* How would you describe the issue?
**Bug in the _admin/core/&view=general_
When you send up the Form, you will redirected to the Site again but you see only the Header of the Page "Core"
After i have enabled the Debugger, i get this:

On the Core/generel Site the Private User Profile Option Form:

- _Notice: Undefined offset: 0 in ...\modules\Core\pages\admin\core.php on line 503_
- _Notice: Trying to get property of non-object in ...\modules\Core\pages\admin\core.php on line 506_

On Submit:
- _Notice: Undefined offset: 0 in ...\neu\modules\Core\pages\admin\core.php on line 284_
- _Notice: Trying to get property of non-object in ...\modules\Core\pages\admin\core.php on line 284_
- _Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1' in ...\core\classes\DB.php:77 Stack trace: #0 ...\core\classes\DB.php(77): PDOStatement->execute() #1 ...\core\classes\DB.php(197): DB->createQuery('UPDATE nl2_sett...', Array) #2 ...\core\classes\Queries.php(45): DB->update('settings', NULL, Array) #3 ...\modules\Core\pages\admin\core.php(288): Queries->update('settings', NULL, Array) #4 ...\index.php(69): require('...') #5 {main} thrown in ...\core\classes\DB.php on line 77_**

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
**No, but I can create some if necessary** 

* Do you have an idea how or where the issue occurs?
** No**

**Comment by partydragen** [comment]
Be sure you updated all new database changes

**Comment by IsS127** [comment]
Add private_profile in users as a new field.
Add private_profile as a option in settings

**Comment by H4nSolo** [comment]
i have cleared my old Nameless v2 Install Version & Database and reinstall the new v2 from Github but the Errors comes again.
Other changes in the Core (like Debugger or other thing) are running but only the General Tab is buggy :(

**Comment by IsS127** [comment]
So did u replace the installer.php? Or everything?

**Comment by H4nSolo** [comment]
yes i tested it local with my xampp on Windows

**Comment by IsS127** [comment]
Go into core/installation/view/installer.view.php
And search for line 2192-2195,
Is it this?:
`$queries->create('settings', array(
                'name' => 'private_profile',
                'value' => 1
   ));`

**Comment by IsS127** [comment]
Found the issue, should be fixed in https://github.com/NamelessMC/Nameless/commit/ddc5e5a5e1a21f9419ab90e189d7d9ccd747a3e2
Thanks for reporting this!
