### ISSUE TITLE
[Suggestion] Staff Online Now Board

### ISSUE THREAD

**Issue by ThiagoEloy** [NamelessMC/Nameless#870]
Add an ''Staff online now'' board below ''latest posts'' that would make it easier to contact staff members in case you have an question, a bug to report, etc.

**Comment by Derkades** [comment]
Or like xenforo a list of all online members with a seperate section for staff, or all staff at the top of the list ans in a different color.

**Comment by ThiagoEloy** [comment]
@Derkades Exactly what i was thinking on

**Comment by partydragen** [comment]
Well staff already have different colors in v2 IF you have selected a group color

**Comment by CHYTsuki** [comment]
I made a tutorial on how you can do this with v1: https://namelessmc.com/forum/topic/439-tutorial-online-staff-members-module mabey that can help you. :D

**Comment by ThiagoEloy** [comment]
@CHYTsuki Thanks! your tutorial helped me a lot, thats gonna do it till the V2 is totally done.

**Comment by CHYTsuki** [comment]
Hey. I just wanted to say that I just finished the same Addon for Version 2.
You can find it here: https://namelessmc.com/forum/topic/491-nameless-version-20-pre-3-online-staff-members/#post-1750

**Comment by IsS127** [comment]
Oh thats nice! But you could create a widget, thats much more simple.

**Comment by IsS127** [comment]
Added at https://github.com/NamelessMC/Nameless/commit/79be86dbd4f45ff6da77e5460617fae527a61b61
