### ISSUE TITLE
index.php working but install.php not

### ISSUE THREAD

**Issue by MexmexMe** [NamelessMC/Nameless#872]
Hello,

fist I want to say, that my english isnt good. sry

I have installed Nameless and IP/index.php is working.
When I click on the Button "No, this is an new install" there is an error "The requested URL /install was not found on this server.".

Please help me!
Thanks.

~ MexmexMe

**Comment by samerton** [comment]
The solution can be found here: https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache

**Comment by samerton** [comment]
I'll mark this issue as closed, as the solution is in my previous reply.

If you're still experiencing issues, please feel free to re-open.
