### ISSUE TITLE
Index page is Apache page

### ISSUE THREAD

**Issue by MexmexMe** [NamelessMC/Nameless#875]
Hey,

i have installed Nameless 2.0 in var/www/html.
Now when i got to my site, there is the apache2 standard-page.
But in the folder html isnt a idex.html.

Please help

**Comment by samerton** [comment]
This doesn't sound like a Nameless problem. 
Can you make sure Nameless isn't in a subfolder (for example /var/www/html/Nameless-2)?

**Comment by H4nSolo** [comment]
I think there is a priority problem with php.
Your Webserver runs the htm / hrml file primar.
Make sure that you vhost configration or the general config of your webserver (like apache or other) accept php index files too ;)

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues feel free to re-open/create another issue.
