### ISSUE TITLE
How to make this module

### ISSUE THREAD

**Issue by SarcasticDroppz** [NamelessMC/Nameless#878]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? NamelessMC version 1.0.19
* How would you describe the issue? Well i have seen it on other websites and it's a cool feature just didn't know how to do it. It's basically like the staff application module mut they have a custom one or something.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? https://cdn.discordapp.com/attachments/340011963868250113/385529293033308180/unknown.png
* Do you have an idea how or where the issue occurs? N/A

**Comment by samerton** [comment]
The ban appeal addon is already included in Nameless (AdminCP -> Addons, click "Install Addon" in the top right if you can't see it).

**Comment by IsS127** [comment]
Closing this, as the question has been answered. If there are any more issues please reopen this issue.
