### ISSUE TITLE
Teamspeak Module - Enchancements

### ISSUE THREAD

**Issue by derrickmehaffy** [NamelessMC/Nameless#88]
Teamspeak 3 clients have the option of creating an auto join url redirect (there is also support for ts3server links). 

~~I'd also like to see the option of displaying a Teamspeak url vs just the IP, as I generally run 2 Teamspeak 3 servers and if one goes down I run a script that will change my domains dns records to point to the backup Teamspeak 3 server. (Makes it easy for players so they dont have to bookmark both servers)~~

My enhancement suggestion would be to add a button of some sort to allow players to click and either start the URL Redirect to automatically join the Teamspeak 3 server.

To find this option in the TS3 Client go to Tools > Invite Buddy

An example of this redirect is:
`http://www.teamspeak.com/invite/ts.blahdomain.com/`
or
`ts3server://ts.blahdomain.com `

The option for an html redirect is also there as well:
`<a href="ts3server://ts.blahdomain.com">Invitation</a>`

**Comment by derrickmehaffy** [comment]
Ignore my suggestion about the URL. It seems I didn't have my backend DNS correctly updated with the correct CNAME entry.

**Comment by lockerecca** [comment]
is posible move the Teamspeak3 List to other part or put on Cache or similar my loading time is 9 Secs on Xeon 8 Cores :/ for Home Website
