### ISSUE TITLE
[Suggestion] Custom meta tags

### ISSUE THREAD

**Issue by Ramacraft123** [NamelessMC/Nameless#880]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Suggestion
* In which version of NamelessMC did it occur (1.x.x)? Next version
* How would you describe the issue?
Please add an option to add my own meta tags, so I can add keywords and description for my custom page
For the forum I suggest to take the first few word from the post as description

**Comment by H4nSolo** [comment]
In V2 you can edit the Template yourself.
This include Meta Tags for Searching Machines like Google and more ^^

**Comment by Ramacraft123** [comment]
Wow, that's neat!
Thanks for informing me
