### ISSUE TITLE
Error 404 and errordocument

### ISSUE THREAD

**Issue by TheEgyptian11** [NamelessMC/Nameless#883]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Issue with install. error 404 and error document
* In which version of NamelessMC did it occur (1.x.x)? 1.0.16 and 1.0.19
* How would you describe the issue? i downloaded the file and put it in my public_html folder and when i go to the website it shows me upgrade from 0.0.41 so i pressed on new install and thats when it showd up 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? yes i have screenshots
* Do you have an idea how or where the issue occurs?
i think its something with .htaccess of sometype
### Please use image uploading websites such as Imgur or Gyazo
![tttttt](https://user-images.githubusercontent.com/34172060/33520750-ea26cba6-d775-11e7-9ecf-51ac0ddc7116.PNG)

**Comment by samerton** [comment]
Hi,

The solution can be found here: https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache

**Comment by samerton** [comment]
I'll mark this as closed, if you're still having issues feel free to re-open.
