### ISSUE TITLE
totally white screen after installing

### ISSUE THREAD

**Issue by slaapkopamy** [NamelessMC/Nameless#884]
Hi, I have tried two times after in 24 hours to install namelessmc on my webserver. Installation is 100% done, I delete install.php from pages/ after refreshing it asking to relog. I do that and since then i have white screen...

MySQLnd is not installed i think but thats official not a problem looks it?
I have running on my own webhosting with php 5.6.30+ apache2 and nginx both enabled, I don't know whats te problem, from apache logs doesn't give any information about the problem.

here a screenshot: https://i.imgur.com/mm4RR57.png
webadress: https://lgn.yt

I hope someone can help my with this problem.

**Comment by H4nSolo** [comment]
Hello slaapkopamy,

first, please check your Webserver settings and installed modules.
Your Source Code says that the Site cancel the loading process on the <body> Tag.

Please Check up this list:

- On the Installation Process you see on the first Site the Required. Are this Requireds OK and not failed?
  - PHP Modules installed (like curl | modrewrite | php-mysql | etc)
- > [MySQLnd is not installed i think but thats official not a problem looks it?] You have install the Nameless Website without an Database Server? 0_o
- Retry Installationprozess with the newest v2 Website here from Github and **don't delete the install.php**

good luck ;)

H4nSolo

**Comment by samerton** [comment]
The white screen issue is down to site permissions, make sure the Nameless **cache** directory is writable, for example on Ubuntu/Debian:
`sudo chown -R www-data:www-data /var/www/html` (assuming Nameless is in /var/www/html), and CentOS:
`sudo chown -R apache:apache /var/www/html`

**Comment by slaapkopamy** [comment]
@samerton i'm using vestacp on debian, so the permission must be set automatic. because every other folder and file on every site is readable

**Comment by samerton** [comment]
In this case permissions must be incorrect, as you had to manually delete pages/install.php too (the installer will delete itself if permissions are correct), so I can only recommend double checking permissions.

**Comment by slaapkopamy** [comment]
I have set the permissions on www-data:www-data for the map cache but didn't work.

@H4nSolo I have now installed the newest version but didn't work.
https://i.imgur.com/CGolWcX.png this is a screenshot from the installed modules
I have running multiple websites on the webhosting including websites from customumers so I don't want try install mysqlnd because i don't know what that does about the other sites.

**Comment by samerton** [comment]
You won't experience any issues for a new installation of Nameless without mysqlnd, don't worry about that.

If you open **core/init.php** in a text editor, delete all code inside, and replace it with [this new code](https://gist.githubusercontent.com/samerton/ccf74b29de40810394e7f8d18dc4b5f6/raw/4f6e839e9be3b8004065f1fdd07612753cf1ce2d/init.php), you should hopefully get an error message on screen instead of it remaining blank.

**Comment by slaapkopamy** [comment]
@samerton i have a white screen with errors now :P https://i.imgur.com/CTzKSSe.png

**Comment by samerton** [comment]
Yep it's still a permissions issue, note the final error message.

I've personally never used VestaCP I'm afraid so I don't know what the permissions need setting to, but all I can say is that the cache directory in Nameless needs to be recursively writable (so cache/templates_c also needs to be writable).

**Comment by slaapkopamy** [comment]
I have deleted all files and tried via filezilla uploading and chmodden. I did always via cli instead via ftp.
It is now done :) thanks for the support
