### ISSUE TITLE
Invalid address: (setFrom)

### ISSUE THREAD

**Issue by gangmembervcs** [NamelessMC/Nameless#888]
Me and a couple of friends have tried setting up a server forums. But it seems every time someone registers, the email is never sent. This is what it says: http://prntscr.com/hl9p2c And these are our core email settings: http://prntscr.com/hl9pfg. 

Our forums are: http://fenixmcnetwork.namelesshosting.com/forum/

**Comment by H4nSolo** [comment]
- is phpmail() running on your webserver?
- if used extern email server, are set up right datas?
- correct Emailadress?

**Comment by gangmembervcs** [comment]
PHPMail is enabled. What data’s do I put in also what email shall I use?

**Comment by samerton** [comment]
The core email settings aren't correct, if you click the link provided in the info above the email settings to the wiki ([this one](https://github.com/NamelessMC/Nameless/wiki/Setting-up-Gmail-or-SMTP-with-Nameless)), it will provide you with the information you need to input in each field.

**Comment by samerton** [comment]
Were you able to resolve the issue @gangmembervcs?

**Comment by samerton** [comment]
I'll mark this issue as closed, if you're still experiencing the issue please feel free to re-open.
