### ISSUE TITLE
Can't register for admin

### ISSUE THREAD

**Issue by whistleac** [NamelessMC/Nameless#89]
When I try registering for admin it give me this every time -

Unable to create account. Please check:
- You have entered a username between 4 and 20 characters long
- Your Minecraft username is a valid account
- Your passwords are at between 6 and 64 characters long and they match
- Your email address is between 4 and 64 characters

I don't know what to do, Please help <3

**Comment by SystemUpdate** [comment]
Do you meet the above requirements?

**Comment by whistleac** [comment]
Yes, but cracked players can registers?

**Comment by whistleac** [comment]
can't*

**Comment by whistleac** [comment]
never mind got it
