### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#890]
Hello, what can I do to add a voting page, just write this to me and I can not add a URL to the polls

https://ctrlv.cz/7dTo

**Comment by samerton** [comment]
Can you enable error reporting in the AdminCP -> Misc tab to see if any errors appear on the Vote addon settings?

**Comment by Derkades** [comment]
Closing this because of lack of user activity. @zikycz if you still need help feel free to reopen
