### ISSUE TITLE
Prefix for players that are banned in-game & website

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless#896]
If you are banned in minecraft that you get the prefix: [BANNED IN MINECRAFT] And if you are banned on the forum that staff still can see your post but that you have the [BANNED] prefix for them same for deleted post. And tempbans for the website and Banappeal if you are banned on the website

**Comment by iJustBlessed** [comment]
When i will get a response?

**Comment by samerton** [comment]
We only respond to issues if they're being closed, so the fact that this is still open (and has labels assigned) means it's being investigated.

**Comment by baxandrei** [comment]
This issue have tag enchantment, so when will ne added, an admin will reply about that and will close this issue .

**Comment by Derkades** [comment]
Closing in favour of #2058
