### ISSUE TITLE
404 on install

### ISSUE THREAD

**Issue by fenix12585** [NamelessMC/Nameless#90]
hello, whenever my web guy tries to install nameless he gets a 404 error. The first page loads fine, but when you select upgrade or fresh install neither one will work. 

we use Nginx and rewrites are working. installing latest version of nameless

**Comment by fenix12585** [comment]
hey, im just checking if there is any additional info that you need for this, most of the time issues seem to be resolved by now..

**Comment by samerton** [comment]
Unfortunately I've never used nginx before.

Have you configured nginx to use something similar to the [example configuration](https://github.com/NamelessMC/Nameless/blob/master/nginx.example)?

Is Nameless installed in the root directory of the webserver, so you don't access it via a subdirectory?

**Comment by fenix12585** [comment]
It is in the root, and we are using that configuration

**Comment by samerton** [comment]
Unfortunately I don't have access to an nginx installation to look into your issue, as soon as I'm able to get my hands on one I can look into it however I don't know when that will be.

**Comment by samerton** [comment]
I'm hearing from a couple of other users that they have been able to install Nameless without issues on an nginx installation, I can only assume this is down to a server configuration error and not Nameless itself.

**Comment by samerton** [comment]
I'm going to go ahead and close this issue as I believe this is due to a server configuration issue.
