### ISSUE TITLE
Ability to group ranks on members page

### ISSUE THREAD

**Issue by iJustBlessed** [NamelessMC/Nameless#904]
Rank category: for (website.com/register) like All, Staff, Donators... Because now all ranks are vieuwed...

**Comment by IsS127** [comment]
Sorry but why do people choose their own ranks on register?

**Comment by iJustBlessed** [comment]
sorry i mean website.com/members

**Comment by iJustBlessed** [comment]
my fault @IsS127

**Comment by samerton** [comment]
Something for https://github.com/partydragen/Members
