### ISSUE TITLE
buggie bugs

### ISSUE THREAD

**Issue by iJustBlessed** [NamelessMC/Nameless#905]
Ignore case on links https://felixmc.net/Vote doesn't work it have to be https://felixmc.net/vote.

**Comment by Derkades** [comment]
Already fixed in a recent commit

**Comment by samerton** [comment]
Was fixed in a previous commit but it needed rolling back due to issues elsewhere, unfortunately this won't happen any time soon.

**Comment by Derkades** [comment]
ah ok
