### ISSUE TITLE
Text white in night mode on white editor background

### ISSUE THREAD

**Issue by iJustBlessed** [NamelessMC/Nameless#908]
in night mode

[![Screenshot from Gyazo](https://gyazo.com/bf34bb3832cb2281cb8161d8e4f7ec2c/raw)](https://gyazo.com/bf34bb3832cb2281cb8161d8e4f7ec2c)
[![Screenshot from Gyazo](https://gyazo.com/d271713c4b6af2eea609ab8cfd77650f/raw)](https://gyazo.com/d271713c4b6af2eea609ab8cfd77650f)

**Comment by samerton** [comment]
Thanks, fixed in 9249ec29547cde55545862e4e2e6e1ea21538fb8
