### ISSUE TITLE
cant remove index.php?route=

### ISSUE THREAD

**Issue by iJustBlessed** [NamelessMC/Nameless#910]
like the title says

**Comment by samerton** [comment]
You can enable "Use friendly URLs" in the AdminCP -> Core -> General Settings tab, just make sure your server is correctly configured (or if it's a web host, make sure the htaccess file exists in public_html containing [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/v2/.htaccess)).

**Comment by iJustBlessed** [comment]
Doesn't work it get disabled again....
