### ISSUE TITLE
custom page doesn't work

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless#911]
this doesn't work 
https://cleanmc.net/google
 https://gyazo.com/da7bd574c6426697e12ce27ddc0c63af

**Comment by Derkades** [comment]
Disable maintenance mode?

**Comment by samerton** [comment]
Looks like you've deleted the custom page, if you can add it back again so we can take a look that'd be great.

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues feel free to reopen.
