### ISSUE TITLE
Add email field to contact form

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#915]
Add email field to contact form so staff can respond to messages

**Comment by RichardB122** [comment]
Hi, I'm interested in contributing and I have made a commit for this on my fork. Is there any place where I can find a style guide and your policies about contributing?

**Comment by samerton** [comment]
Hi @RichardB122, to be honest it's very relaxed on that front, we don't have anything like that set out at the moment.
If you have any questions or anything, I can try my best to answer them.

**Comment by samerton** [comment]
Added in d1289657df4e14af0b8609e66580e9a27a89f76e, thanks to @RichardB122
