### ISSUE TITLE
NamelessReport module QAPlugin

### ISSUE THREAD

**Issue by iJustBlessed** [NamelessMC/Nameless#916]
Hi cool people form namelessmc xD I use the nameless plugin in bungee and i got QAPlugin on spigot with the report module do that still works? and where can i get my v2 api key

**Comment by samerton** [comment]
There is no API in version 2 pr3 (it's been added since and will be in pr4). QAPlugin will work with the Legacy API option in the next release.

**Comment by iJustBlessed** [comment]
oh kk
