### ISSUE TITLE
Only Background

### ISSUE THREAD

**Issue by CapnCranch** [NamelessMC/Nameless#919]
* What kind of issue is it (Question, Bug, etc.)?

Bug

* In which version of NamelessMC did it occur (1.x.x)?

1.0.19

* How would you describe the issue?

The website only shows the background with no buttons or anything else

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?

https://gyazo.com/f584694c94450c3e80f22c0822467911
https://gyazo.com/176e7078b823a5b756c41e178a2d6de1

* Do you have an idea how or where the issue occurs?

I reinstalled my vps and when i put the files back on the site it just did this

**Comment by samerton** [comment]
Can you make sure your **cache** and **cache/templates_c** directories are writable?

**Comment by samerton** [comment]
I'll mark this as closed, if you're still having issues please feel free to re-open.
