### ISSUE TITLE
My homepage isnt working, it is only white.

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#927]
Please, help me, my homepage of web isnt working, and i cant add forum... 
> www.meggaplay.eu

**Comment by DSArtyFixLife** [comment]
+ I cant add page... It is very bugy...

**Comment by samerton** [comment]
Can you install the **php-xml** extension, for example:
```sudo apt-get install php-xml``` for Ubuntu/Debian, before restarting Apache

**Comment by samerton** [comment]
Were you able to resolve this problem @DSArtyFixLife?

**Comment by Derkades** [comment]
The website looks fine to me now, I'll mark this as closed. If you still need help feel free to leave a comment

**Comment by ItzArty** [comment]
That was a thing man, thaat was a thing

**Comment by Tatussee** [comment]
Don't ya say
