### ISSUE TITLE
Force https instantly crashes the site

### ISSUE THREAD

**Issue by ProfiiQus** [NamelessMC/Nameless#928]
Hello,
I've recently swapped the work done on one website to another hosting, replacing the files in the destination. The web seemed to work fine, after a while, it stopped working. It seems that "Force https" option was enabled on the last web and I can't actually swap it off.

In which directory/file can I find this option? Thanks really much.

www.craftzone.cz

**Comment by samerton** [comment]
Currently, the only way to disable the Force HTTPS option is to delete the file **cache/033f3da34ae9ec9661072ab0897ddf7ed642de3f.cache** from within your Nameless directory.

**Comment by ProfiiQus** [comment]
Well, thanks you really much!

Solved.
