### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless#929]
When i log in succesfull i get redirected to: https://cleanmc.net/favicon.ico/

**Comment by Natfan** [comment]
When I try to access https://cleanmc.net/ I get a `403 Forbidden` error. Try fixing your perms with `chmod`

**Comment by Derkades** [comment]
Are you still having this issue?

**Comment by Derkades** [comment]
It looks like it's no longer a problem so I'll close this. If you still need help feel free to reopen.
