### ISSUE TITLE
DOMDocument.php missing

### ISSUE THREAD

**Issue by Nyxiu** [NamelessMC/Nameless#930]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.9
* How would you describe the issue? Users just can't register on my site (They can't click on the "I agree" button) and i can't modify "terms and conditions" or enable recaptcha on my site cause button "submit" is missing.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? You can try to register to my site, if you want I can give add you to the admin group
* Do you have an idea how or where the issue occurs? I activated the "debug mode" and I had the following output: 
<br />
<b>Warning</b>:  require_once(core/classes/DOMDocument.php): failed to open stream: No such file or directory in <b>/var/www/html/core/init.php</b> on line <b>26</b><br />
<br />
<b>Fatal error</b>:  require_once(): Failed opening required 'core/classes/DOMDocument.php' (include_path='/var/www/html/core/includes/htmlpurifier/standalone:.:/usr/share/pear:/usr/share/php') in <b>/var/www/html/core/init.php</b> on line <b>26</b><br />

**Comment by Derkades** [comment]
Make sure `php-xml` is installed

**Comment by Nyxiu** [comment]
Thank you so much

**Comment by samerton** [comment]
Glad your issue is resolved :)
