### ISSUE TITLE
error profile

### ISSUE THREAD

**Issue by Ozoow** [NamelessMC/Nameless#932]
Error:
SQLSTATE[HY000] [1045] Access denied for user 'guilduni_db'@'localhost' (using password: YES)
Please check your database connection settings.

**Comment by partydragen** [comment]
@Ozoow That is because you have infractions addon enabled, Either disable the addon or setup the database connection

**Comment by samerton** [comment]
I'll mark this issue as closed (due to Partydragen's response), if you're still experiencing issues feel free to re-open.
