### ISSUE TITLE
404 during install

### ISSUE THREAD

**Issue by Ozoow** [NamelessMC/Nameless#934]
Not Found
The requested URL /install was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by samerton** [comment]
Hi,

The solution can be found [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache)
