### ISSUE TITLE
Change Banner Image In AdminCP?

### ISSUE THREAD

**Issue by HetIsJoey** [NamelessMC/Nameless#94]
like the title says.

made u can add that?

**Comment by samerton** [comment]
You can manually change **core/integration/banner/background.png** with an image of your choice.
As for adding an option to do this in the AdminCP, I may do something much later on, probably more version 2.0.

**Comment by HaynoPrison** [comment]
I also wish to see this intergrated along with the hompage and user profile image.

**Comment by Derkades** [comment]
And here we are over a year later.. Are you planning to do it in 2.0 like you said you were going to?

**Comment by samerton** [comment]
Absolutely, everything in the 2.0.0 milestone will be completed before the full release :)

**Comment by samerton** [comment]
The ability to change profile and Minecraft banner backgrounds has been added in v2, however changing the homepage banner image is template specific and therefore it's up to the template to provide you with a means of changing this; the v2 Nextyle template has a module, for example, that can do this.
