### ISSUE TITLE
TeamSpeak3 query is not working on my website.

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#943]
Hi, I used for my website namelessmc software, but I want to add teamspeak3 voice module, but it always says if I do the save, Voice Server Query is supporting only TeamSpeak3 and Discord!
Sorry for bad english. Faster by screen-shots: [What Im doing bad?]
https://i.imgur.com/DK299Br.png
https://i.imgur.com/zspJqB5.png

**Comment by samerton** [comment]
Hi,

The "Connection timed out" issue is caused by incorrect connection details to the server, possibly due to the "Port" or "Virtual Port" being wrong. Unfortunately I can't provide any more information than that.

**Comment by DSArtyFixLife** [comment]
And where I can get virtual port?

**Comment by samerton** [comment]
@DSArtyFixLife To be honest, I'm really not sure as I haven't used TeamSpeak myself for a few years. Are you hosting the TeamSpeak server on your own machine, or is it on a host?

**Comment by samerton** [comment]
Were you able to resolve this @DSArtyFixLife?

**Comment by samerton** [comment]
I'll close due to inactivity, feel free to re-open.
