### ISSUE TITLE
(Question/Bug) Cannot install theme, how may I install one.

### ISSUE THREAD

**Issue by ItzVinex** [NamelessMC/Nameless#947]
NamelessMC (1.0.19) it occurred.
Unsure if I am doing it right or not I am using Centos 7 w/ Apache

**Comment by samerton** [comment]
What's the template you're trying to install? You'll need to make sure it matches your Nameless version.

**Comment by ItzVinex** [comment]
https://namelessmc.com/resources/resource/9-nextyle-updated/

**Comment by ItzVinex** [comment]
The theme shows that it is installed but when I click it I only see like three lines on the left side of my screen and then I click them and It'll show my site name in the admin panel but if I am not in the admin panel it just doesn't display my website.

**Comment by samerton** [comment]
Nextyle is for NamelessMC version 2 (you can check your version in the AdminCP -> Overview tab).

If you are using version 2, make sure you've also installed and activated the module in the AdminCP -> Modules tab.

**Comment by ItzVinex** [comment]
NamelessMC version 1.0.19

I have no idea how to install it and where to install it.

**Comment by ItzVinex** [comment]
Where do I even get Version 2.0

**Comment by samerton** [comment]
Version 2 is available from [here](https://github.com/NamelessMC/Nameless/archive/v2.zip). As it's still in development, it's currently missing features such as staff applications, and modules such as the infractions and donation addons in v1.

**Comment by ItzVinex** [comment]
Ty
And will I lose my stuff if I upload this?

**Comment by samerton** [comment]
There is an option in the version 2 installer to upgrade from version 1.

If you do want to upgrade, please back up your version 1 files, and the database as well (using something like phpMyAdmin) in case you want to go back to version 1 afterwards.

**Comment by ItzVinex** [comment]
Okay

**Comment by ItzVinex** [comment]
I just dragged and dropped the files on to my FTP to replace the other ones, I really don't mind if I lose the other site I barely did anything.

**Comment by samerton** [comment]
You'll have to delete the version 1 files first, as version 2 isn't a direct file replacement.

**Comment by ItzVinex** [comment]
Ok ty.

**Comment by ItzVinex** [comment]
I'm getting an error https://gyazo.com/3657dcc0dc13f691a4b67dbe2f25fac5

**Comment by samerton** [comment]
@ItzVinex we'll need an error message to find out what the problem is. Has this happened after the installer, or during the installer?

If you're using a web host, try finding some error logs in their control panel, otherwise if you're on a VPS/dedicated server there are Apache error logs available.

**Comment by ItzVinex** [comment]
Nothing is popping up I'm on Centos 7 all files are uploaded and I went to try it and nothing shown. So this is before the installer.


I'm on Apache as well.

**Comment by ItzVinex** [comment]
Nvm I got it ty.

**Comment by samerton** [comment]
Okay great :)

**Comment by ItzVinex** [comment]
Why is the control panel German.

**Comment by samerton** [comment]
The default language is EnglishUK, I'm honestly not sure why that would be happening.
You can change the default language in the AdminCP -> Core -> General Settings tab, and your own user's language in the UserCP -> Settings tab.

**Comment by ItzVinex** [comment]
Okay its set to EnglishUS

**Comment by samerton** [comment]
Ok, is everything working now @ItzVinex?

**Comment by ItzVinex** [comment]
Yes.

**Comment by Derkades** [comment]
Oops sorry
