### ISSUE TITLE
Password Resets Not working

### ISSUE THREAD

**Issue by rwsender** [NamelessMC/Nameless#95]
A user has forgotten their password and cannot reset it using the link they get sent, I cant generate a random password in order for them to change it themselves

**Comment by samerton** [comment]
What is the issue they get when using the link?

**Comment by mentimjojo** [comment]
This is fixed with this push request: https://github.com/NamelessMC/Nameless/pull/142

**Comment by samerton** [comment]
Were you able to resolve this issue?

**Comment by samerton** [comment]
I'm going to mark this as closed as I feel this is down to some sort of server side issue, as I've not been able to reproduce any issues.
If you're still experiencing this issue, feel free to re-open.
