### ISSUE TITLE
Can't switch language

### ISSUE THREAD

**Issue by X00LA** [NamelessMC/Nameless#950]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Problem.

* In which version of NamelessMC did it occur (1.x.x)?
Release 1.0.19.

* How would you describe the issue?
When I want to change the language i get this message: "Unable to update settings. Please ensure no fields are left empty."

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Here's a picture of it: [Imgur](https://i.imgur.com/83BcRGJ.png)

* Do you have an idea how or where the issue occurs?
No idea.

**Comment by samerton** [comment]
The problem seems to be the site name, which in the AdminCP has a limit of 32 characters, and yours appears to be 33 characters. 
I can look into adding a more informative error message, and possibly increasing the limit in the future.

**Comment by X00LA** [comment]
Thanks for the fast answer.
I will shorten the name, no problem.
Would be niche for newbies like me when the error message includes more informations. Would makes things easier.

Thanks
