### ISSUE TITLE
Site brokes after creation of announcement

### ISSUE THREAD

**Issue by X00LA** [NamelessMC/Nameless#951]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Bug/Problem

* In which version of NamelessMC did it occur (1.x.x)?
Release 1.0.19

* How would you describe the issue?
I created an announcement and after I published it, the page went black and you could not do anything anymore. I have to delete it from the database to get the site working again.
In the ACP the announcement appears without any options. It's a solid block.

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
[ACP Screenshot](https://i.imgur.com/4feN4Wf.png)

* Do you have an idea how or where the issue occurs?
I cant see anything in the apache logs. No errors or something similar.

Regards

**Comment by partydragen** [comment]
well about the picture, It happens when the annoucement is emtpy or have none selected pages
So its a bug

**Comment by samerton** [comment]
If you enable error reporting in the AdminCP -> Misc tab, do any errors appear on the announcements page?

**Comment by X00LA** [comment]
@partydragen The announcement wasnt empty and a site was selected.
@samerton I activated it and here's what i get:
`
Notice: Undefined offset: 0 in /var/www/html/cgn-minecraft.tk/pages/index.php on line 15

Notice: Trying to get property of non-object in /var/www/html/cgn-minecraft.tk/pages/index.php on line 15

Notice: Undefined offset: 0 in /var/www/html/cgn-minecraft.tk/pages/index.php on line 16

Notice: Trying to get property of non-object in /var/www/html/cgn-minecraft.tk/pages/index.php on line 16

Notice: Undefined offset: 0 in /var/www/html/cgn-minecraft.tk/pages/index.php on line 17

Notice: Trying to get property of non-object in /var/www/html/cgn-minecraft.tk/pages/index.php on line 17`

**Comment by X00LA** [comment]
@samerton I reinstalled nameless and now all works fine except the eroors I posted above! That's the same I had on the old one.
On my second try I installed version 1.0.15 first and upgraded step by step to 1.0.19.
It looks like something went wrong in my first installation.
I hope that stays that way now.

**Comment by samerton** [comment]
@X00LA Those notices won't cause any issues, and to fix them you can either disable error reporting in the AdminCP -> Misc tab, or create and set a default Minecraft server in the AdminCP -> Minecraft -> Servers tab.

**Comment by X00LA** [comment]
Ok.

Thank you for the help.
