### ISSUE TITLE
Adding a page to get logged in-game punishments

### ISSUE THREAD

**Issue by Gnat008** [NamelessMC/Nameless#952]
### Template:
* What kind of issue is it (Question, Bug, etc.)? _Question_
* In which version of NamelessMC did it occur (1.x.x)? _1.0.19_
* How would you describe the issue?

I want to create a page on my instance to view reports on players (warns, kicks, etc.). I can't use the included addon for them because this is a plugin I wrote myself for my server. I'm newer to the webdev scene, so I'm not sure if I should (or can) use the custom page creator in Nameless, or upload my own php file(s) and somehow get that to tie in with the rest of the site.

**Comment by samerton** [comment]
The custom page editor in Nameless is for basic HTML pages only, however to add your own PHP page to Nameless, the process is as follows:

- Create a new .php file in the **pages** folder, with the page path as the file name (for example, yoursite.com/bans would be bans.php)
- Paste [this code](https://gist.githubusercontent.com/samerton/16e36d3804949e4b83046de39ebee897/raw/f23b975323e67f55697d3871f8443c97f5f4a01a/example.php) inside to get things like the Nameless header and footer generated
- Add your own PHP/HTML code to that file

To add a link to your navbar, you can create a custom page in the AdminCP with the page URL the same as your .php file (eg /bans), as when loading a page, Nameless will prioritise a file in the pages folder over the custom page created through the AdminCP.

**Comment by Gnat008** [comment]
Ahh, okay, I see now. I had got part of the way there, just not all of the way there. haha. Thanks!
