### ISSUE TITLE
Problem with encoded data in sites

### ISSUE THREAD

**Issue by X00LA** [NamelessMC/Nameless#953]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Security Issue / Translation problem

* In which version of NamelessMC did it occur (1.x.x)?
1.0.19

* How would you describe the issue?
I'm forced to implement a imprint into my site and I use encoded E-Mail, Phone and Address data to prevent spam and unwanted calls from call centers.
When I insert the encoded strings into the editor and save the created site the encoded part gets lost and spider bots can read my data.

I created a file for the donation module to fit my language. I uploaded it, gave the right permissions but it has no effect.

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Encrypted Input:
` &#077;&#121;&#032;&#101;&#110;&#099;&#111;&#100;&#101;&#100;&#032;&#100;&#097;&#116;&#097; `
Site Output:
` My encoded data. `

For the language problem:
[Pastebin](https://pastebin.com/WAfLmcaY)

* Do you have an idea how or where the issue occurs?
No, I have no idea why this happend.

Hope you can help.

Regards

**Comment by samerton** [comment]
All posts are first processed by htmlspecialchars before being stored in the database, so for example the character `<` becomes `&lt;`, and when the post is then displayed in the forum htmlspecialchars_decode is called, which turns any characters (such as the example in your post) back to their normal ones. Currently, nothing can be done about this issue I'm afraid.

As for the language not working, you will have to rename the existing language.php to something else, and then rename your language_german.php to language.php; the Donate addon only loads the language.php file.

**Comment by Derkades** [comment]
> when the post is then displayed in the forum htmlspecialchars_decode is called
Is this necessary? `&lt;` and `<` are both shown as `<` by the browser

**Comment by samerton** [comment]
Really the encoding and then decoding performed isn't necessary, as all data is purified with HTMLPurifier before being outputted to the user.

**Comment by X00LA** [comment]
@samerton 
Security Issue --> Ok, Thank you for this answer. I will create a Image with the data and put this in.
Language --> Ah, ok. Thanks. Do you want the translated files to implement it into you site? I also fixed some typos and translated some new lines in the main language file. If you want them I will send a pull request.

Regards

**Comment by samerton** [comment]
A pull request would be great, thanks :)

**Comment by X00LA** [comment]
I will send it, when I got a few minutes spare time.
