### ISSUE TITLE
Suggestion: Subscribe Option for Forum Post Threads / Areas

### ISSUE THREAD

**Issue by H4nSolo** [NamelessMC/Nameless#956]
Option to subscribe to forum areas or topics to be notified by email that a reaction has been made.

In his own profile settings, you could then create a separate tab, which topics are currently subscribed to, if necessary, to delete them or turn off the notifications.

**Comment by Derkades** [comment]
Duplicate of https://github.com/NamelessMC/Nameless/issues/726
