### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by Aviorleking** [NamelessMC/Nameless#957]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Enhancement
* In which version of NamelessMC did it occur (1.x.x)? all
* How would you describe the issue?
allow admins to disable/recreate cache
why ? for skin creation

**Comment by samerton** [comment]
I'm assuming you're referring to the built-in avatar system? If so, I can look into an option to force clear the cache, as avatars are currently cached for 60 minutes.

**Comment by Aviorleking** [comment]
not only all the style files 
while logged i have to wait(2-5mins) and force reload CTRL-F5 to see changes

**Comment by samerton** [comment]
Theme files (css/js/images etc) aren't cached by Nameless, it'll be either your browser or something like Cloudflare (if you have it enabled) caching them.

Template files might be cached by Smarty, in which case refreshing about 5 times should update it.

**Comment by Aviorleking** [comment]
ok thanks !
i will try to make something up to my mind to add cache deleter 😄
