### ISSUE TITLE
user nav link

### ISSUE THREAD

**Issue by Aviorleking** [NamelessMC/Nameless#958]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 2.0.0-pre.3
* How would you describe the issue?
Why does `$USER_AREA` `$item.title` return `<i class="fa fa-cogs" aria-hidden="true"></i>` and not `user` like does `$NAV_LINKS`

for my skin using mdi icons and not font awesome it's not cool

**Comment by samerton** [comment]
At the moment you can change the cogs icon in the user.php language file (https://github.com/NamelessMC/Nameless/blob/v2/custom/languages/EnglishUK/user.php#L21), but I'll change this to be template related in the future.

**Comment by Aviorleking** [comment]
ok thanks
