### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by MoeXIV** [NamelessMC/Nameless#962]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.19
* How would you describe the issue? Lack of knowledge.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://prntscr.com/i7gh6f
* Do you have an idea how or where the issue occurs? Yes, this happens when I change the nginx config to the one on the Wiki.
* What Modules are you using ? None
* What theme are you using ? None

Sorry to be a noob, I am new to nginx. I installed NamelessMC on my VPS and had the "404 Not Found" error for the install page, so I modified the nginx.conf to match the one on the Wiki. When I try to restart the service after I get that error in the prntscrn. 

This is what I got in my nginx.conf: https://hastebin.com/ovufitakuq.nginx
Did I put that text in the wrong file?

**Comment by samerton** [comment]
The nginx conf is only an example, you need to update it to match your installation.

For example, wherever you see a path (eg /var/www/example.com/public), it needs changing to whichever folder Nameless is installed in, and you also need to update `server_name ~^(www.)?example.com;` to your own domain.

**Comment by samerton** [comment]
Were you able to resolve this issue?

**Comment by samerton** [comment]
I'll mark this as closed, feel free to re-open if you're still experiencing the issue.
