### ISSUE TITLE
How to change the home page font/ text colour

### ISSUE THREAD

**Issue by loldylanrose** [NamelessMC/Nameless#965]
Hello, i am using version 1.0.19, and was wondering if there's a way to change the font, and colour on the main page? I've posted a picture below so you can see what i'm talking about

![image](https://user-images.githubusercontent.com/36086430/35752362-ab09599a-0829-11e8-87db-ef42cc110b47.png)

**Comment by samerton** [comment]
Hi,

The CSS for that section is in the top of pages/index.php ([this code](https://github.com/NamelessMC/Nameless/blob/master/pages/index.php#L119-L126) to be precise), you can add any CSS rules to there

**Comment by samerton** [comment]
I'll mark this as closed, if you're still not sure please feel free to re-open.
