### ISSUE TITLE
Registration results in 500 error

### ISSUE THREAD

**Issue by computerwizjared** [NamelessMC/Nameless#97]
I recently switched to nginx as my web server, but now saw that when users are attempting to register, it results in a 500 error. Both PHP and Nginx do not log anything, and neither does the browser console. Here is my nginx config:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.php index.html index.htm;

        server_name _;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;

                fastcgi_pass unix:/var/run/php5-fpm.sock;
        }
}
```
I understand that you may not have experience with nginx, but I believe that this is the issue since it only started after I switched. I've found nginx to be a lot less resource-intensive on my server, and load times are a bit faster. If you could help, that would be awesome!

**Comment by samerton** [comment]
Was this simply a change from Apache to nginx, or are you using a different server?

**Comment by computerwizjared** [comment]
@samerton I only changed from Apache to nginx.

**Comment by computerwizjared** [comment]
Nevermind, out of my own ignorance I somehow removed the php5-curl package on my Debian box, therefore reCAPTCHA wouldn't work. I also found the "Enable error reporting" option, which I overlooked somehow. Thank you so much!
