### ISSUE TITLE
Block pages for all except a specific group

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless#973]
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.19
* How would you describe the issue? I have a specific page I wanted to add to my server. It requires to be in its own folder along with its prerequisites and such. I was wondering how I could verify that a user is rank "Owner" and then allow them to view it and if they're not rank "Owner" then they just get redirected back to the home page. Basically I want to use the rank permissions system that custom pages has so only specific groups can view the page.

**Comment by samerton** [comment]
Unfortunately in version 1, this isn't possible without some updates to the core/init.php file, allowing it to include files in other directories.

This is possible in version 2 though, all you need to do is include core/init.php in your project, setting the required $page variable (just a name for your page), and the ROOT_PATH constant, which is the Nameless root path relative to your current directory.

**Comment by MuhsinunCool** [comment]
Should I update my website from 1.0.19 to v2? And how do I go about it?

**Comment by samerton** [comment]
It's important to note v2 is still in development, and is currently missing most v1 addons (such as donate and full infractions integration, although I've recently added LiteBans support to the [v2 infractions module](https://github.com/samerton/Nameless-Infractions)), as well as staff applications amongst other things.

If you do want to upgrade, first back up your files and the database; it's not possible to downgrade back to v1 afterwards. Next, delete the v1 files (but **don't** touch the database).
You should then download the latest v2 development code from [here](https://github.com/NamelessMC/Nameless/archive/v2.zip), and upload them to your website. You can finally run through the installer, just tell it you want to upgrade from v1 at the start, and follow the rest of the instructions.

**Comment by samerton** [comment]
Were you able to resolve this @MuhsinunCool?

**Comment by MuhsinunCool** [comment]
I'm not sure whether or not I would like to update to 2.x given its incomplete status.

**Comment by samerton** [comment]
It's totally up to you, the missing features in my previous reply are the main things from v1 that are missing. There are a couple of extra features that v1 doesn't have, and it's definitely stable enough to use.

**Comment by MuhsinunCool** [comment]
How long do you reckon until said elements will be integrated into v2?

**Comment by samerton** [comment]
I really can't estimate that I'm afraid, I'm really busy at the moment so I barely have a chance to work on Nameless. I'd hope to complete everything in the summer, but it might not happen.

**Comment by samerton** [comment]
I'll mark this as closed since the original question was answered; v2 updates can be tracked in [the v2 branch](https://github.com/NamelessMC/Nameless/tree/v2) along with [the project](https://github.com/NamelessMC/Nameless/projects/1).
