### ISSUE TITLE
Question: iFrame behavior

### ISSUE THREAD

**Issue by K0demonkey** [NamelessMC/Nameless#974]
![namelessmc-iframe](https://user-images.githubusercontent.com/36743268/36558288-8b730680-17d8-11e8-8234-e352eafb8358.JPG)

v1 NamelessMC

If I attempt to use an iFrame to include a map of my Minecraft world it does not use the full screen (see attached photo).

The code in the index.html file for the map is set to use 100% (H & W) and values in NamelessMC for an iFrame are set to 100%.

Is there something I am doing incorrectly?

Can't wait to see v2!

Thanks in advance.

**Comment by samerton** [comment]
It's been a while since I've played around with iFrames in a custom page, however in the "Source" view within the custom page editor, can you try adding `style="height:400px;"` (or any other height you think is suitable) to the iFrame to force its height?

**Comment by K0demonkey** [comment]
Thank You! That worked!

**Comment by samerton** [comment]
No problem :)
