### ISSUE TITLE
NamelessMV v2 - stylesheet path?

### ISSUE THREAD

**Issue by K0demonkey** [NamelessMC/Nameless#975]
![nameless-stylesheet](https://user-images.githubusercontent.com/36743268/36599540-abb6a5aa-187d-11e8-9e3f-bb9928657739.JPG)

So I am playing around with version 2 and did a fresh install on my server. 

I do have version 1 running without issue on the same server.

As you can see above that direrctory path does not exist. It should be 

core/assets/plugins/toastr/toastr.min.css

Why is it putting /sites/knowhere/ in front of the path to the stylesheets?

Did I configure something wrong upon install? If I alter the config.php file to the correct path

**Comment by samerton** [comment]
It'll just be an issue with the path detection in v2, on the odd occasion it won't detect it correctly. I'll add an option in the installer at some point in the future to allow for manual adjustment, but for now as you say it can be changed in config.php

**Comment by K0demonkey** [comment]
This is still not fixed. I have the latest v2 source code. The config file is still being written like this.

	"core" => array(
		"path" => "sites/knowhere",
		"friendly" => false
	),
	"allowedProxies" => ""

If I change it to "/" nothing shows on the site.

http://knowhere.shannoncase.com/

**Comment by samerton** [comment]
I've not had a chance to allow this to be configurable in the installer, however instead of changing the path to "/", simply leave it empty (ie `"path" => "",`)

**Comment by K0demonkey** [comment]
I tried that, but it still did not work. I used "." and now the site comes up fine. 

	"core" => array(
		"path" => ".",
		"friendly" => false
	),
	"allowedProxies" => ""

Thank you for the work you do.
