### ISSUE TITLE
Android Bug

### ISSUE THREAD

**Issue by kaliiks** [NamelessMC/Nameless#976]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Bug
* In which version of NamelessMC did it occur (1.x.x)?
The one from github
* How would you describe the issue?
When you click your head on android to open Menu with AdminCP etc, it does not display it.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
No
* What theme are you using ?
Paper

**Comment by samerton** [comment]
Which web browser on Android are you using? 

I use Chrome on Android personally and I've never experienced any issues, which leads me to believe it's a Javascript issue on your site.

Would you be able to send me a link to your website?

**Comment by samerton** [comment]
I'm unable to reproduce any issues, I'll mark this as closed for now.

If you could send me a link to your website, I can re-open this issue.
