### ISSUE TITLE
505 error

### ISSUE THREAD

**Issue by Giirion** [NamelessMC/Nameless#977]
* Error
* 1.0.19
* After installing Nameless I got 404, I allowed the mod_rewrite, since then I keep getting 505
* Well, screen of Internal Server Error.
* I really don't, that's why I am here =D

Thanks for help!

*EDIT: It seems that the 505 error appears after allowing the mod_rewrite, because I also get 505 error when I want to log in on my web.

**Comment by samerton** [comment]
Hi,

Can you make sure you also added AllowOverride All to your <Directory> block in your vhost, see [here](https://github.com/NamelessMC/Nameless/wiki/FAQs#im-getting-a-404-not-found-error-whilst-trying-to-install-namelessmc-on-apache) for instructions on doing that.

**Comment by Giirion** [comment]
Ok, it workd after following the instructions - thank you!

**Comment by samerton** [comment]
Great, glad it's working!
