### ISSUE TITLE
Suspended server

### ISSUE THREAD

**Issue by Liqhtro** [NamelessMC/Nameless#978]
### Template:
* What kind of issue is it (Question, Bug, etc.)? My website server got just randomly suspended
* In which version of NamelessMC did it occur (1.x.x)? Lastest
* How would you describe the issue? Everything worked well, and today, the website just randomy got suspended
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Nope, unfortunately
* Do you have an idea how or where the issue occurs? No idea
* What Modules are you using ? Dm me discord for more info Liqhtro#3534
* What theme are you using ? Default

[PLEASE CONTACT ME ON DISCORD ASAP Liqhtro#3534]

#### Example:
**What kind of issue is it (Question, Bug, etc.)?** Bug.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.19.  
**How would you describe the issue?** The index does not load up at all.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/QqkXhVx.png)  
**Do you have an idea how or where the issue occurs?** I think it has to do with the "index.php" file but not sure.

**Comment by samerton** [comment]
Hi,

If you are using Nameless Hosting, they have temporarily suspended all websites until the summer due to the expenses of running a free host (as per emails/announcements sent out).

However, this is the repository for the NamelessMC website software, which is totally separate from Nameless Hosting. You can find the Nameless Hosting website [here](http://namelesshosting.com/).

**Comment by Liqhtro** [comment]
So we are not able to use nameless websites till summer?

Dana 3. ožu 2018. 03:08 osoba "Sam" <notifications@github.com> napisala je:

Hi,

If you are using Nameless Hosting, they have temporarily suspended all
websites until the summer due to the expenses of running a free host (as
per emails/announcements sent out).

However, this is the repository for the NamelessMC website software, which
is totally separate from Nameless Hosting. You can find the Nameless
Hosting website here <http://namelesshosting.com/>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NamelessMC/Nameless/issues/978#issuecomment-370107685>,
or mute the thread

**Comment by samerton** [comment]
@Liqhtro 
NamelessMC is a website software, meaning you can run it on any web host. 
You can download the files from [here](https://github.com/NamelessMC/Nameless/releases), and upload them to any web host and install it.

Nameless Hosting is one of these web hosts, however there are many more web hosts available.
