### ISSUE TITLE
404 error after install

### ISSUE THREAD

**Issue by ReduxRedstone** [NamelessMC/Nameless#98]
Right after I completed a fresh install I got a 404 error saying "Sorry, we couldn't find that page.". even when i travel to the folder with index.php it gives me the error. Any thoughts?

**Comment by samerton** [comment]
There could be one of a couple of things happening here.

Have you installed Nameless in a subdirectory or your web server's root directory?
Is there a file named ".htaccess" within the root directory?

If it's installed in the root directory and there is indeed a .htaccess file present, it sounds like you need to enable Apache's mod_rewrite and the use of .htaccess files on your webserver. [Here is a guide for Ubuntu](http://askubuntu.com/a/48363).

**Comment by ReduxRedstone** [comment]
I have it installed in a subdirectory, is that causing the issue? I had assumed it would work anywhere, like MyBB and others do. There is a .htaccess file, yes. I was hoping that I could use this to make something like examplesite.com/forum, but if it cant be installed in a subdirectory then I suppose I cant use this.

**Comment by samerton** [comment]
The subdirectory is the issue, as Nameless is designed as a standalone package. 
You can try setting up a subdomain to point to the subdirectory, as this should work.

**Comment by ReduxRedstone** [comment]
Damn. okay. Are there any possible plans to make this package work in subdirectories?

**Comment by samerton** [comment]
There's a chance in the future that I'll work on a standalone forum option which would run in a subdirectory, but for the time being it's more of a CMS.

**Comment by josephworks** [comment]
a subdirectory option would be nice... I kinda need it.

**Comment by samerton** [comment]
@josephworks subdirectory support has been added in version 2, which is getting close to a full release. You can find version 2 here: https://github.com/NamelessMC/Nameless/tree/v2
