### ISSUE TITLE
Login Error Message Typo

### ISSUE THREAD

**Issue by DarethZ33** [NamelessMC/Nameless#980]
### Template:
* What kind of issue is it (Question, Bug, etc.): Typo
* In which version of NamelessMC did it occur (1.x.x): 2.0
* How would you describe the issue: While testing on my staging domain I noticed a typo with the login error message.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.): [Error Message Image](https://i.gyazo.com/e103df59a935fb76dc16744bea9d2cc0.png)
* Do you have an idea how or where the issue occurs: I found a comment reference in modules/Core/pages/authme_connector.php line 254 but is linked to the language files in custom/languages. This typo is in the EnglishUS and EnglishUK files on line 117. I do not speak the other languages, but would check to make sure those are correct. Text should read "You have input incorrect details."
* What Modules are you using: Core and Bootstrap 3
* What theme are you using: Testing on Default and the Bootstrap 3 Theme

**Comment by samerton** [comment]
Thanks, hopefully cleared up in 96864b85317233f7566d31540765a028e8919d06
