### ISSUE TITLE
embed images from imgur/upload own images.

### ISSUE THREAD

**Issue by rwsender** [NamelessMC/Nameless#99]
Currently players have to link their images to get them to work, alot of the image hosting sites come up like this : http://puu.sh/nbKUs/2a4edd711d.png which is annoying as player cant view images on-site.

With this in mind, a possible option to enable image uploads would be nice as when people do manage to link to external image hosting it usually takes away the https in green.

**Comment by samerton** [comment]
The problem with the screenshot is that the URL inputted isn't actually the image URL. To get the URL from an Imgur link, right click on the image and select "Copy image address".

**Comment by rwsender** [comment]
I get this now, is there any chance of a built in file upload in the future?

**Comment by samerton** [comment]
There's a possibility, however this is more likely to arrive further down the line, closer to 2.x.

**Comment by samerton** [comment]
Ability to upload your own images added in 9ed435b791336235dd1f35a9130b0c95ed3ed4e6
