### ISSUE TITLE
Config.php from core is not configured

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#990]
Hello,
I'm using NamelessMC, but in core directory is config.php not configured, as well, I'm running setup, it still display's about no permission to access to config.php, but it has permission. But when I checked it, it was blank. Please send me the template for it. :) Sorry for my bad english, and thank you.

**Comment by Derkades** [comment]
Are you sure it's writable by the www-data user? Check with ls -l

**Comment by DSArtyFixLife** [comment]
It is, but the template is not in. Im sure, because Im only reinstalling it, same version before worked. But now is the config.php not pre-filed.

**Comment by DSArtyFixLife** [comment]
It is still showing me this message: Your core/config.php file is not writeable. Please check your file permissions.  - But it has permission.

**Comment by Derkades** [comment]
What is the output of ls -l in your core directory

**Comment by DSArtyFixLife** [comment]
I dont know what do you mean, but I tried.

root@debian:~# cd /var/www/html/core
root@debian:/var/www/html/core# ls -l
total 44
drwxr-xr-x 7 root root 4096 Mar 28 11:28 assets
drwxr-xr-x 3 root root 4096 Mar 28 11:28 classes
-rw-r--r-- 1 root root    0 Nov 22 15:43 config.php
drwxr-xr-x 2 root root 4096 Mar 28 11:28 converters
-rw-r--r-- 1 root root  463 Nov 22 15:43 email.php
drwxr-xr-x 8 root root 4096 Mar 28 11:29 includes
-rw-r--r-- 1 root root 6583 Nov 22 15:43 init.php
drwxr-xr-x 4 root root 4096 Mar 28 11:29 integration
drwxr-xr-x 7 root root 4096 Mar 28 11:30 modules
drwxr-xr-x 2 root root 4096 Mar 28 11:30 queries
-rw-r--r-- 1 root root  199 Nov 22 15:43 voice_server.php

**Comment by Derkades** [comment]
Root means it is not owned by www-data so it does not have permission

Run chown -R www-data:www-data * in /var/www/html

**Comment by DSArtyFixLife** [comment]
Oh My God! Thank you very much, I thninked, that was because of the core.php :D

**Comment by samerton** [comment]
Glad the issue is resolved :)
