### ISSUE TITLE
I cannot enter my forum section

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#991]
Hello,
I'm using NamelessMC web software, and before few hours I setupped my new page for server, and I maked news system, but in forums i cannot click on the News, and then i cannot make new post, *IT ISNT WORKING AS NORMAL BUTTON, BUT JUST A NORMAL TEXT* thank you. Sorry for my bad english.

**Comment by DSArtyFixLife** [comment]
www.spacehq.cf

**Comment by samerton** [comment]
In Nameless, each *discussion forum* needs to have a *parent category*.

This means that, if you create a forum and select the option for it to be a "category", you will not be able to enter it, as it is simply a group of discussion forums.

When you set up your forums, you should first create a category, and give it a general name like "Forums" or something. Then, you can create discussion forums (for example "News"), and their parent forum option should be "Forum".

If you look at the [Nameless website](https://namelessmc.com/forum), you can see that "NamelessMC" is a category, and "News & Announcements", "General Discussion" etc are discussion forums, with their parent forum set as "NamelessMC".

Hope that helps.
