### ISSUE TITLE
Profiles are not working + Icon is not working (favicon)

### ISSUE THREAD

**Issue by DSArtyFixLife** [NamelessMC/Nameless#992]
Hello,
Im using Namelessmc websoftware, but I cannot access to my or friend's profile, but before it worked, but I wanted to change profile.jpg from assests but after I changed it, the profile pages are giving me this mysql error message: Error:
SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'
Please check your database connection settings. - But other pages are working! - www.spacehq.cf / www.spacehq.cf/profile/DSArtyFixLife - Help me!!!!

**Comment by DSArtyFixLife** [comment]
Oh, and of course, I uploaded 16x16 icon (favicon.ico) to assests folder. And... It isn't working...

**Comment by DSArtyFixLife** [comment]
And, how I can remove the footer ad?

**Comment by DSArtyFixLife** [comment]
And, how I can add to news posts given reputation? (to middle of views and comments)

**Comment by samerton** [comment]
The profile issue is because you have enabled the Infractions addon in the AdminCP -> Addons tab, but you have not configured it.

Your favicon is working for me, you can try clearing your browser cache with Ctrl+F5 or you can use another browser for now; it's an issue on your end.

It looks like you have resolved the footer issue, we do ask that you leave some sort of link or credit to NamelessMC as it's free software, but the license does mean you don't have to do this.

There is currently no support for giving or viewing reputation on news posts on the front page, hopefully in the future I can add support.

**Comment by DSArtyFixLife** [comment]
Thank you.

**Comment by DSArtyFixLife** [comment]
And also, where i must past smartsupp html code?

**Comment by DSArtyFixLife** [comment]
And can I edit these messages like that? SQLSTATE[42S02]: Base table or view not found: 1146 Table 'arty_mysql.nl1_donation_settings' doesn't exist

**Comment by samerton** [comment]
You can try adding the Smartsupp <script> code (instructions [here](https://www.smartsupp.com/help/smartsupp-chat-code/)) to the bottom of core/includes/template/scripts.php

As for the SQLSTATE messages, there is no way to edit what they say at the moment. The error you mention (containing donation_settings) is because the Donate addon has not been configured in the AdminCP -> Addons tab.

**Comment by DSArtyFixLife** [comment]
Can you send me the tutor? Because i cannot acces the site you sended me.

**Comment by samerton** [comment]
Only Smartsupp can provide you with the code, it is a <script>....</script> tag.

**Comment by DSArtyFixLife** [comment]
Can you setup it for me? 
<script type="text/javascript">
var _smartsupp = _smartsupp || {};
_smartsupp.key = 'a40617661b0f304ed362a68ef8e712f6716290f9';
window.smartsupp||(function(d) {
  var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
  s=d.getElementsByTagName('script')[0];c=d.createElement('script');
  c.type='text/javascript';c.charset='utf-8';c.async=true;
  c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
})(document);
</script>


<?php 
/*
 *	Made by Samerton
 *  http://worldscapemc.co.uk
 *
 *  License: MIT
 */
 
/*
 *  Load scripts
 */

echo '<script src="' . PATH . 'core/assets/js/jquery.min.js"></script>' . PHP_EOL;
echo '	<script src="' . PATH . 'styles/themes/' . $theme_result . '/js/bootstrap.min.js"></script>' . PHP_EOL;
echo '	<script src="' . PATH . 'core/assets/js/jquery.cookie.js"></script>' . PHP_EOL;
echo '	<script src="' . PATH . 'core/assets/js/toastr.js"></script>' . PHP_EOL;
?>
	<script type="text/javascript">
	jQuery(function( $ ){
		<?php
		if(!$user->isLoggedIn()){
		?>
		// Check if cookie alert has been closed
		if( $.cookie('alert-box') === 'closed' ){

			$('.alert-cookie').hide();

		}

		 // Grab your button (based on your posted html)
		$('.close-cookie').click(function( e ){

			// Do not perform default action when button is clicked
			e.preventDefault();

			/* If you just want the cookie for a session don't provide an expires
			 Set the path as root, so the cookie will be valid across the whole site */
			$.cookie('alert-box', 'closed', { path: '/' });

		});
		<?php
		}
		?>
		
		// Announcements
		$("div[class*='alert-announcement-']").each(function() {
			var id = this.id;
			
			// Check if cookie alert has been closed
			if( $.cookie('announcement-' + this.id) === 'closed' ){

				$(this).hide();

			}

			// Grab your button (based on your posted html)
			$('.close-announcement').click(function( e ){

				// Do not perform default action when button is clicked
				e.preventDefault();
				
				/* If you just want the cookie for a session don't provide an expires
				 Set the path as root, so the cookie will be valid across the whole site */
				$.cookie('announcement-' + id, 'closed', { path: '/' });

			});
		});

	});
	</script>
<?php
foreach($custom_js as $item){
	echo $item;
}
?>

	<script type="text/javascript">
	<?php if($user->isLoggedIn()){ ?>
	$(document).ready(function() {
		toastr.options.closeButton = true;
		toastr.options.timeOut = 0;
		toastr.options.positionClass = 'toast-bottom-left';
		
		// Get alerts and messages, and then set them to refresh every 20 seconds
		$.getJSON('/core/queries/private_messages.php?uid=<?php echo $user->data()->id; ?>', function(data) {
			if(data.value > 0 && $('#pms').is(':empty')){
				$("#pms").html(' <i class="fa fa-exclamation-circle custom-nav-exclaim"></i>');
			}
		});
		$.getJSON('/core/queries/alerts.php?uid=<?php echo $user->data()->id; ?>', function(data) {
			if(data.value > 0 && $('#alerts').is(':empty')){
				$("#alerts").html(' <i class="fa fa-exclamation-circle custom-nav-exclaim"></i>');
			}
		});
		
		window.setInterval(function(){
		  $.getJSON('/core/queries/private_messages.php?uid=<?php echo $user->data()->id; ?>', function(data) {
			if(data.value > 0 && $('#pms').is(':empty')){
				$("#pms").html(' <i class="fa fa-exclamation-circle custom-nav-exclaim"></i>');
				toastr.info('You have ' + data.value + ' new messages');
			}
		  });
		  $.getJSON('/core/queries/alerts.php?uid=<?php echo $user->data()->id; ?>', function(data) {
			if(data.value > 0 && $('#alerts').is(':empty')){
				$("#alerts").html(' <i class="fa fa-exclamation-circle custom-nav-exclaim"></i>');
				toastr.info('You have ' + data.value + ' new alerts');
			}
		  });
		}, 20000);
	});
	<?php } ?>
	// popovers
	$(function () { $("[data-toggle='popover']").popover({trigger: 'hover', placement: 'top'}); });
	// tooltips
	$(document).ready(function(){
		$("[rel=tooltip]").tooltip({ placement: 'top'});
	});
	<?php
	// End page load timer
	$page_load = microtime(true) - $start;
	?>
	var timer = 'Page loaded in <?php echo round($page_load, 3); ?>s';
	$('#page_load_tooltip').attr('title', timer).tooltip('fixTitle');
	
    $(function() {
        $(".alert-dropdown").hover(
            function(){ $(this).addClass('open') },
            function(){ $(this).removeClass('open') }
        );
    });	
	</script>

**Comment by DSArtyFixLife** [comment]
Oh nonono, I setup it already, but thank you for help!

**Comment by samerton** [comment]
No problem :)

**Comment by DSArtyFixLife** [comment]
And how i can add font to website from my computer?

**Comment by DSArtyFixLife** [comment]
And if it is possible, how i can use in texts?

**Comment by samerton** [comment]
You can do this using CSS. Upload the font files onto your website (for example, create a new folder named "fonts" and upload them into there), and then add the CSS in [this post](https://stackoverflow.com/a/24990647) to the bottom of styles/themes/*theme*/css/custom.css, and also add (using oswald as the example from the link, change this to the name of your font):
```
body {
    font-family: oswald;
}
```

You may need to press Ctrl+F5 to view the changes. As this is a customisation to your website, I can't help you any more than this.

**Comment by DSArtyFixLife** [comment]
Thank you (for now) :D

**Comment by DSArtyFixLife** [comment]
Emh... Where I must make the folder?

**Comment by samerton** [comment]
It's up to you, your CSS must match the path.

For example, if you upload your font files (named, in this example, font.eot, font.woff, font.ttf and font.svg) to a folder named "fonts" in the Nameless **core/assets** folder, the path in your CSS would be `url('/core/assets/font.eot');`

**Comment by DSArtyFixLife** [comment]
oh, now i know, and how is name section with site name in navbar? -- But I want change font only of server name, no of pages.

**Comment by samerton** [comment]
The site name in the navbar is in **styles/templates/*template*/navbar.tpl**, it is the `{$SITE_NAME}` variable. To change the font of this, you change `body {` in the CSS in my previous code to `.navbar-brand {`

**Comment by DSArtyFixLife** [comment]
Can you do it for me? 

<link rel="stylesheet" type="text/css" href="custom_navbar/hvr.css">
<link rel="stylesheet" type="text/css" href="custom_navbar/hvr_full.css">

<nav class="navbar navbar-default navbar-fixed-top{$NAVBAR_INVERSE}">
<div class="container">
  
  <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_navbar_collapse">
	  <span class="sr-only">Toggle navigation</span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	</button>
	


<a class="navbar-brand" href="/">
<img src="custom_navbar/small-banner.png" height="30" class="hvr-pulse" alt=""></a>


  </div>

  
  <div class="collapse navbar-collapse" id="main_navbar_collapse">

<font size="3px"><b>
	<ul class="nav navbar-nav">
  <li><a class="navbar-nav hvr-buzz-out" href="/"><i class="fa fa-home" style="color:#adfccf"></i> Home</a></li>
  <li><a class="hvr-buzz-out" href="/forum"><i class="fa fa-comments" style="color:#adfccf"></i> Forums</a></li>
   <li><a class="hvr-buzz-out" href="/play"><i class="fa fa-server" style="color:#adfccf"></i> Servers</a></li>
    <li><a class="hvr-buzz-out" href="/mcshop"><i class="fa fa-cart-arrow-down" style="color:#adfccf"></i> Store</a></li>
	   <li><a class="hvr-buzz-out" href="/apply"><i class="fa fa-newspaper-o" style="color:#adfccf"></i> Staff Apps</a></li>
	       <li><a class="hvr-buzz-out" href="/banappeal"><i class="fa fa-ban" style="color:#fe665a"></i> Ban Appeal</a></li>
	</ul>
</b></font>
	
	<ul class="nav navbar-nav navbar-right">
	  {* User dropdown and notifications *}
	  {$USER_AREA}
	</ul>
  </div>
</div>
</nav>


{$GLOBAL_MESSAGES}

{if isset($ANNOUNCEMENTS) && !empty($ANNOUNCEMENTS)}
  <div class="container">
  {foreach from=$ANNOUNCEMENTS item=item}
    <br />
  <br />
    <div width="100%" class="alert alert-{$item.type}{if $item.can_close == 1} alert-announcement-{$item.id} alert-dismissible{/if} hvr-wobble-top" id="{$item.id}">
	  {if $item.can_close == 1}<button type="button" class="close close-announcement" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>{/if}
	  {$item.content}
	</div>
  {/foreach}
  </div>
{/if}



My font is in:
/var/www/html/styles/templates/StoneBros/fonts/Adventure.otf

Please :)

**Comment by DSArtyFixLife** [comment]
Emmm... Why it...

**Comment by samerton** [comment]
Like I say, as it's a customisation I can't really help, but your CSS to change the website name would be

```
@font-face {
    font-family: 'adventure';
    src: url('/styles/templates/StonerBros/fonts/Adventure.otf');
}

.navbar-brand {
    font-family: adventure;
}
```

That *might* work, but you should probably try and get the .eot, .woff, .ttf and .svg font files as well. Don't forget you might need Ctrl+F5 to view CSS changes.

**Comment by DSArtyFixLife** [comment]
AAAnd... How I can make facebook page widget there where are discord, ts and twitter widgets? I want to have there it with posts and more...

**Comment by DSArtyFixLife** [comment]
Yo, and I maked for you an account with developer rank (fullperms), your name is there Samerton and password is sam123 and I given you mail nomail@nomail.idk. :)

**Comment by samerton** [comment]
Thanks :)

**Comment by DSArtyFixLife** [comment]
But please help me with the fb widget... (two messages higher.)

**Comment by samerton** [comment]
You can get HTML code for your Facebook widget [here](https://developers.facebook.com/docs/plugins/page-plugin/), which then needs to be pasted into styles/templates/*template*/index.tpl; to add it to the social sidebar (by the Twitter widget) you can paste it onto line 40 which is currently empty ([this line](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/index.tpl#L40)).

**Comment by DSArtyFixLife** [comment]
And what are the height and width? (as default)

**Comment by samerton** [comment]
It depends on a number of things (such as screen resolution), I can only recommend you have a play around with those values to see what you like.

**Comment by DSArtyFixLife** [comment]
Can do it you? Im very big noob to do this.


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/sk_SK/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>










<div class="fb-page" data-href="https://www.facebook.com/mcspacehq" data-tabs="timeline" data-width="240" data-height="400" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/mcspacehq" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/mcspacehq">SpaceHQ</a></blockquote></div>




<div class="container">
  {$SESSION_FLASH}
  <div class="jumbotron jumbotron-homepage">
    <h1>{$SITENAME}</h1>
	<p>{$PLAYERS_ONLINE}</p>
	<p>{$CONNECT_WITH}</p>
  </div>
  <div class="row">
    {if !empty($TWITTER_FEED) || !empty($VOICE_VIEWER)}
    <div class="col-md-9">
	{else}
	<div class="col-md-8 col-md-offset-2">
	{/if}
	  
	  <h2>{$NEWS}</h2>
	  {foreach from=$newsArray item=news}
	    <div class="panel panel-primary">
		  <div class="panel-heading">
		    <a class="white-text" href="/forum/view_topic/?tid={$news.id}">{$news.title}</a>
			<span class="pull-right"><a class="white-text" href="/profile/{$news.author_mcname}">{$news.author_username}</a> {$news.author_avatar}</span>
		  </div>
		  <div class="panel-body">
		    <div class="forum_post">{$news.content}</div>
			<br /><br />
			<span class="label label-info">{$news.date}</span>
			<span class="pull-right">
			  <span class="label label-danger"><span class="glyphicon glyphicon-comment"></span> {$news.replies} | <span class="glyphicon glyphicon-eye-open"></span> {$news.views}</span>
			</span>
		  </div>
		</div>
	  {/foreach}
	</div>
	{if !empty($TWITTER_FEED) || !empty($VOICE_VIEWER)}
	<div class="col-md-3">
	  
	  <h2>{$SOCIAL}</h2>
	  {if !empty($TWITTER_FEED)}
	  {$TWITTER_FEED}
	  {/if}
	  
	  {if !empty($VOICE_VIEWER)}
	  {if {$VOICE_VIEWER_TITLE} != 'Discord'}
	  <div class="well well-sm">
	  <h4>{$VOICE_VIEWER_TITLE}</h4>
	  <strong>{$VOICE_VIEWER_IP}</strong><br />
	  {$VOICE_VIEWER}
	  </div>
	  {else}
	  {$VOICE_VIEWER}
	  {/if}
	  {/if}
	</div>
	{/if}
  </div>
</div>

**Comment by samerton** [comment]
You simply add the <script>...</script> you have there into line 40 of that file, which was linked in my last post.

**Comment by DSArtyFixLife** [comment]
But I dont know what from these two i must get there, the first on created only button to fb and the second not worked.

**Comment by DSArtyFixLife** [comment]
OOOH, GOD, I KNOW!

**Comment by DSArtyFixLife** [comment]
I doesnt do anything...

**Comment by DSArtyFixLife** [comment]
<div class="fb-page" data-href="https://www.facebook.com/mcspacehq" data-tabs="timeline" data-width="250" data-height="350" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/mcspacehq" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/mcspacehq">SpaceHQ</a></blockquote></div>

**Comment by DSArtyFixLife** [comment]
See...

**Comment by DSArtyFixLife** [comment]
The same is on my page.. :(

**Comment by samerton** [comment]
Honestly all I can say it that you need to add all the code the Facebook widget provides you (the <script>...</script> and also the <div>...</div>) into the index.tpl file in your template, and then the widget will appear.

**Comment by DSArtyFixLife** [comment]
But it is... Still only button...

**Comment by DSArtyFixLife** [comment]
If i will screen you the fb generated code, can you add the dav, and the script, bcs for me it doesnt work... Im very big noob.

**Comment by DSArtyFixLife** [comment]
https://upload.hicoria.com/files/M4HR5yeZ.png

**Comment by DSArtyFixLife** [comment]
https://upload.hicoria.com/files/mTWBajss.png

**Comment by samerton** [comment]
In that case you can edit styles/templates/*template*/index.tpl, and replace the code inside with [this new code](https://pastebin.com/raw/aF1pfcTD).

**Comment by DSArtyFixLife** [comment]
It works! Thank you!

**Comment by DSArtyFixLife** [comment]
My page isnt working after editing language...

**Comment by DSArtyFixLife** [comment]
How I can change language of site in configs?

**Comment by DSArtyFixLife** [comment]
FIXED.

**Comment by DSArtyFixLife** [comment]
Hmmm.. Is possible to get free ssl on nameless?

**Comment by samerton** [comment]
You'd need to ask your web host, Nameless is just a web software.

**Comment by DSArtyFixLife** [comment]
Where i must paste the AddThis code?

**Comment by DSArtyFixLife** [comment]
--
 <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5abd0b27ba228123"></script>

**Comment by samerton** [comment]
To the same place as your Smartsupp code, to the bottom of core/includes/template/scripts.php.

**Comment by DSArtyFixLife** [comment]
Oh, thanks!

**Comment by DSArtyFixLife** [comment]
Is possible to setup ts query without vir. port?

**Comment by DSArtyFixLife** [comment]
Aaand... Can you send me the code of footer ad? I want to remake it..
Example it will display:
 Software by Samerton

**Comment by samerton** [comment]
The generated HTML can be found [here](https://github.com/NamelessMC/Nameless/blob/master/core/includes/template/footer.php#L42-L48), which creates a `{$FOOTER_NAVIGATION}` variable for you to use in your template [like this](https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/footer.tpl#L6).

**Comment by DSArtyFixLife** [comment]
How I can make footer higher?

**Comment by DSArtyFixLife** [comment]
Can I run discord module and also teamspeak3 module? Because I dont see them. Only Discord
