### ISSUE TITLE
Register Error Bug

### ISSUE THREAD

**Issue by Tyrelis** [NamelessMC/Nameless#993]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.19
* How would you describe the issue? A error occurs when you click on register page without imputing any fields. You must first enable debug mode to reproduce the bug.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? 
> Notice: Undefined index: name in /var/www/html/core/integration/uuid.php on line 115 Notice: Undefined index: id in /var/www/html/core/integration/uuid.php on line 115 Notice: Undefined index: name in /var/www/html/core/integration/uuid.php on line 83 Notice: Undefined index: id in /var/www/html/core/integration/uuid.php on line 83 Notice: Undefined index: properties in /var/www/html/core/integration/uuid.php on line 83 
* Do you have an idea how or where the issue occurs? It shows it in the error where and what line.
* What Modules are you using ? Register
* What theme are you using ? Custom/StonerBros

**Comment by samerton** [comment]
These notices shouldn't actually cause any issues, they're caused by issues connecting to the Mojang API to retrieve UUIDs. 

As you say, they only appear when error reporting is enabled, so hopefully when that's disabled you shouldn't notice any problems.

**Comment by Tyrelis** [comment]
They only appear when debug mode is on. I aware they don't cause any issues although I sometimes notice it says a error this account is not a valid premium account when in fact it is. I don't know if that part of the reason it causing that error.

**Comment by samerton** [comment]
Unfortunately this is out of our control at the moment, it's to do with Mojang's API returning the invalid result. When the premium username error appears, the best solution is to wait a minute or so and try again.

**Comment by Tyrelis** [comment]
Okay so there is no way to fix that error I saw in debug mode? **Not including** premium username error

**Comment by samerton** [comment]
Unfortunately there's currently no way to fix it, I'm hoping to create an API specifically for Nameless in the future which should help, but I'm not sure when I'll be able to do this.

**Comment by Tyrelis** [comment]
Okay thanks for the information and reply.
