### ISSUE TITLE
Issue with going to admin cp or any other page.

### ISSUE THREAD

**Issue by kadenstratton** [NamelessMC/Nameless#995]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? Latest Release
* How would you describe the issue? 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
* Do you have an idea how or where the issue occurs?
* What Modules are you using ?
* What theme are you using ? Default

When I have freshly installed nameless to my webhost whenever I try to go to a different page it wont do anything but stay on the home page. My domain is skypulse.us .

**Comment by samerton** [comment]
Nameless needs to be installed directly in public_html, and not in the Nameless-1.0.19 subfolder.

For example, index.php, 404.php, and all the folders need to be in public_html.

**Comment by kadenstratton** [comment]
Thanks samertron,

However, I have figured out the issue.  Upon me purchasing a better hosting plan, my hosting provider didn't transfer my htaccess file and only my domains folder. Sorry for creating an issue for this software, as it is this at fault. 

Thanks,
Kaden

**Comment by kadenstratton** [comment]
Now I having an issue with the voice server modules. If you go to my home page skypulse.us you will see what I am talking about. My discord will not show up and I cannot get team speak off of there.

**Comment by Derkades** [comment]
No problem, glad you resolved the issue!
