### ISSUE TITLE
Certain user breaks member table

### ISSUE THREAD

**Issue by techied** [NamelessMC/Nameless#998]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 1.0.19
* How would you describe the issue? A player breaks DataTables
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Datatables shows this alert: `DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter '2' for row 0. For more information about this error, please see http://datatables.net/tn/4`
* Do you have an idea how or where the issue occurs? It occurs [here](https://www.nervousapocalypse.net/members/?v=Helper) and it also shows on All Members, but without an alert. It breaks the formatting of the page
* What Modules are you using ? Google Analytics, Registration, Voice Server, Staff Applications
* What theme are you using ? Lumen

**Comment by samerton** [comment]
It looks like your Helper group is missing a closing " in the Group HTML field (AdminCP -> Users and Groups), as the code is currently `<span class="label label-helper>`, without the " after label-helper.

**Comment by techied** [comment]
Yep, that was it. No bug here :I just me being a spoon
