### ISSUE TITLE
Scaling is weird at high resolutions

### ISSUE THREAD

**Issue by Gnat008** [NamelessMC/Nameless#999]
### Template:
* **What kind of issue is it (Question, Bug, etc.)?** Bug/Enhancement
* **In which version of NamelessMC did it occur (1.x.x)?** 1.0.19
* **How would you describe the issue?**

On high resolutions, the website scaling is... sub-optimal. This is best explained by pictures, so here is a full-screen screenshot on a 2560x1440 display: https://puu.sh/A0z2g/8f409b1414.png
As can be seen, there is a lot of wasted whitespace, and the website content is small in the center. I'm not sure if this is because of bootstrap or not, or if changes can be made if it is.

**Comment by samerton** [comment]
Interesting, thanks for the screenshot. 
The width is determined by Bootstrap's container component, and unfortunately in version 1 this can't be changed on *all* pages using the template (as pages like the UserCP, ModCP and AdminCP don't use templates), however you can edit the template files that do exist, and change `container` to `container-fluid` (for example, [this line] in (https://github.com/NamelessMC/Nameless/blob/master/styles/templates/Default/index.tpl#L1) in styles/templates/*template*/index.tpl)).

**Comment by samerton** [comment]
Just to add onto this, it appears Bootstrap aren't currently looking into support for 4k and 5k monitors currently ([link to issue](https://github.com/twbs/bootstrap/issues/22000)) which is a shame, hopefully it's something which can be looked into in the future.

**Comment by Gnat008** [comment]
Hmm yeah, I feared that was the case. I can only hope that eventually Bootstrap comes up with an actual solution to this, given that 4k+ monitors are becoming more and more prevalent. Thanks for the container type change, I may play around with that!

**Comment by samerton** [comment]
No problem, I'll mark this as closed for now, hopefully support for these higher resolutions will be added in a future Bootstrap update, in which case Nameless will be updated too.
